### ISSUE TITLE
Release Date?

### ISSUE THREAD

**Issue by levan1993** [ChrisRM/material-theme-jetbrains#1]
Hi,
when are you planning release this theme?

**Comment by ChrisRM** [comment]
Later today, I hope

**Comment by ryanwinchester** [comment]
nice... it is looking good so far. :+1:

**Comment by levan1993** [comment]
Dark theme will be awesome!

**Comment by ChrisRM** [comment]
I want to add a couple more icons, try to remove or prettify the separators and clean up the code before I release the source, but for those being a little impatient, here's the builds ;-)

**NOTE**: Make sure you backup the .jar's you are replacing. This is for PhpStorm only. Other applications will be supported later.

[php.jar](http://cdn.hifive.no/material-ui/php.jar) 
Required to replace the php file-icon.

**Installation**: Replace `/Applications/PhpStorm/Contents/plugins/php/lib/php.jar`

[phpstorm.jar](http://cdn.hifive.no/material-ui/phpstorm.jar)
UI Colors

**Installation**: Replace `/Applications/PhpStorm/Contents/lib/phpstorm.jar`

[Material Theme.jar](http://cdn.hifive.no/material-ui/Material%20Theme.jar)
Replaces all icons and sets the sidebar/tree background to the same as your editor background.

**Installation**: In PhpStorm go to `PhpStorm` - `Preferences` - `Plugins` - `Install plugin from disk` - `Select Material Theme.jar and restart`

[Material Theme.icls](http://cdn.hifive.no/material-ui/Material%20Theme.icls)
Colour scheme. 

**Installation**: Add it to `~/Library/Preferences/WebIde90/colors/Material Theme.icls` and select it from the preferences. You might need to restart PhpStorm after adding the file.

Yeah, it's alot, but I'll create an installer for all this later. Let me know how it goes!

**Comment by ryanwinchester** [comment]
Very nice.

I don't think I like the operation sings and constants being bold, but other than that it looks really good to me!

**Comment by ChrisRM** [comment]
Did you manage to install it @ryanwinchester?

**Comment by ryanwinchester** [comment]
Without issue

![screenshot](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screenshot+2015-09-27+14.50.17.png)

**Comment by ChrisRM** [comment]
Nice! Wish I could find a way to edit the tabs, but no luck so far. Personally I turn the tabs off, but it would be nice for those who keep it on there.

**Comment by meetbryce** [comment]
Unfortunately I didn't have any luck in PyCharm.

![screenshot 2015-09-28 10 12 45](https://cloud.githubusercontent.com/assets/1845143/10125955/cf30ef68-65c9-11e5-8677-16a70c670895.png)

Got this error when enabling the plugin and the color scheme didn't show up in the menu...

**Comment by meetbryce** [comment]
Had much better luck in Webstorm but the tabs are still showing up as lightly colored. Did I miss something?

![screenshot 2015-09-28 10 21 16](https://cloud.githubusercontent.com/assets/1845143/10125981/b93b0eae-65ca-11e5-9ed6-f54c1ca1e17f.png)

**Comment by ryanwinchester** [comment]
@meetbryce maybe set editor to darcula UI first?

**Comment by meetbryce** [comment]
After a whole lot of restarting, that works like a charm (in Webstorm) thanks @ryanwinchester.

![screenshot 2015-09-28 10 33 33](https://cloud.githubusercontent.com/assets/1845143/10126051/738e1f16-65cc-11e5-9dff-42e4f2f15c8d.png)

**Comment by shhetri** [comment]
No matter how much I try, I get this error every time. I have tried the installation process in both PhpStrom 9.0 and 9.5 (EAP) in mac.

![phpstrom-materaial-theme-installation-error](https://cloud.githubusercontent.com/assets/6878832/10128459/bf5cf650-65d2-11e5-9e5e-77457bb0ad3b.png)

**Comment by ryanwinchester** [comment]
If it makes a difference I had no issues and I'm using the version with bundled JDK 1.8

You can download it from their page, don't click the big blue button, look underneath:

![](https://photos-5.dropbox.com/t/2/AADL0-uX1MWfjRZL_Hn5-GJTUhlMCSozR7IU49LfvBEP_g/12/57631425/png/32x32/1/_/1/2/Screenshot%202015-09-27%2022.50.23.png/EPqEwSwYlJMFIAEoAQ/mX-xzaHi4bM1QA04GocfvZ5cMZHga1P6sLffkP2WHrs?size=1280x960&size_mode=2)

**Comment by shhetri** [comment]
@ryanwinchester will you please share your "About PhpStrom" screenshot?

I will open another issue, this thread is getting bloated. @ryanwinchester please reply in this [this](https://github.com/ChrisRM/material-theme-jetbrains/issues/2) issue.

**Comment by ChrisRM** [comment]
@meetbryce These initial builds are only for PhpStorm. I'll add all the other applications soon :)

**Comment by meetbryce** [comment]
Awesome. Thanks for letting me know it's on the cards.

As shown above, it works fine in Webstorm so it may be worth mentioning in
the instructions. (Just had to change the file name from phpstorm.jar to
webstorm.jar)
On Mon, 28 Sep 2015 at 4:56 PM, Chris Magnussen <notifications@github.com>
wrote:

> @meetbryce <https://github.com/meetbryce> These initial builds are only
> for PhpStorm. I'll add all the other applications soon :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisRM/material-theme-jetbrains/issues/1#issuecomment-143655692>
> .
>
-- 
Cheers,
Bryce York

**Comment by ChrisRM** [comment]
@meetbryce From the screenshot you provided, it doesn't seem to work correctly. The UI (Toolbar, statusbar etc) should have the same background color as your editor. That's why we need separate builds for other applications.

**Comment by meetbryce** [comment]
That's great news then. Will sit tight for now then.
On Mon, 28 Sep 2015 at 7:08 PM, Chris Magnussen <notifications@github.com>
wrote:

> @meetbryce <https://github.com/meetbryce> From the screenshot you
> provided, it doesn't seem to work correctly. The UI (Toolbar, statusbar
> etc) should have the same background color as your editor. That's why we
> need separate builds for other applications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ChrisRM/material-theme-jetbrains/issues/1#issuecomment-143685618>
> .
>
-- 
Cheers,
Bryce York

**Comment by AcoustickSan** [comment]
It's great!

**Comment by slovenianGooner** [comment]
Can confirm it works like a charm on Windows as well.

**Comment by ChrisRM** [comment]
Who would have thought. Does everything work as expected, @slovenianGooner? I guess the php icons aren't working, as I would have to provide you with a php-windows.jar package for that to work, right?

**Comment by blakedietz** [comment]
@ChrisRM so is this working for Intellij?

**Comment by ChrisRM** [comment]
@blakedietz I'm running it on IntelliJ IDEA CE without any issues, but there are a lot of icons to convert, so I won't release that specific version just yet. Should be ready within a couple days though.

**Comment by slovenianGooner** [comment]
Yeah, everything seems to work smoothly. The PHP icons are there aswell, seems it uses the same .jar package.

![material-theme](https://cloud.githubusercontent.com/assets/1257629/10157342/8c8632c0-6689-11e5-9c26-1604f1c29502.jpg)

**Comment by ChrisRM** [comment]
Yeah, that's working perfectly it seems. Thanks for the screenshot!

**Comment by slovenianGooner** [comment]
No problem. Doesn't have the clean look as the Mac Retina display does, it's my biggest issue with Windows really. In general, that is. :)

**Comment by ChrisRM** [comment]
Well, you can always switch to a mac... ;)

**Comment by slovenianGooner** [comment]
Don't get me started on that! Have one at home, not at work, so I know the difference full well. Keep up the good work, mate!

**Comment by ChrisRM** [comment]
I will! Be sure to download the first beta-release when I release it. I'll add MT icons for all file types, fix the preferences window and hopefully modify the tabs to a more MT-like appearance.

**Comment by zach-adams** [comment]
Just a note to Linux PHPStorm users, the file paths are different:

**php.jar**
Installation: Replace /usr/share/phpstorm/plugins/php/lib/php.jar

**phpstorm.jar**
Installation: Replace /usr/share/phpstorm/lib/phpstorm.jar

**Material Theme.icls**
Installation: Add it to ~/.WebIde90/config/colors/Material Theme.icls

***Make sure to backup before you replace***

**Comment by ChrisRM** [comment]
I think I cracked the code on this thing. So far I've managed to bundle all ui-icons including some of the plugin icons(php, sass etc), the colour theme and a plugin which sets the ui background to whatever color you choose for your editor. If all goes well, we're left with just a single installable plugin package.

**Comment by h3ku** [comment]
Im so excited to try it on IntelliJ :+1:

**Comment by slovenianGooner** [comment]
@ChrisRM just a quick question. Any way to disable the ugly "Project" bar on top of the sidebar? Basically the only thing that's bothering me and looks different to Sublime.

**Comment by ChrisRM** [comment]
@slovenianGooner That's not something I want to do with this package I'm afraid.
