### ISSUE TITLE
Analysis on scrollbar

### ISSUE THREAD

**Issue by ArabCoders** [ChrisRM/material-theme-jetbrains#100]
Hi, 

Not sure if this is error because of the theme or something else, but after activating the new theme, the scrollbar lost the usual marking for errors, it just shows the global one, see the attached photo.

![theme_error](https://cloud.githubusercontent.com/assets/1621552/10718365/f480d472-7b81-11e5-9b45-e3766fa62349.png)

**Comment by ArabCoders** [comment]
I tried to change the "Settings > General > Error stripe mark min height", and it had no effect, when i switch back to original theme (Dracula) it does show the "error stripe".

I have also noticed that the error stripe does work only on "Darker", "Default/Light" does not show it.

**Comment by Kendos-Kenlen** [comment]
I can confirm the problem on the default theme.
Plus, VCS related highlighting works, but color doesn't correspond to colors in the gutter (who are inverted compared to default settings in the gutter : green for edited code, blue for new code).

**Comment by ChrisRM** [comment]
Improvements coming soon guys. Sorry about the delay.

**Comment by ArabCoders** [comment]
@ChrisRM Thank you,
