### ISSUE TITLE
Messed up text display on HighDPI screens

### ISSUE THREAD

**Issue by brezanac** [ChrisRM/material-theme-jetbrains#1002]
Upgrading to 2.9.4 garbles up UI text on HighDPI screens (only UI, code is still legible)

![naluy4h](https://user-images.githubusercontent.com/389770/47103735-24af2c80-d240-11e8-9013-5b958d4cc29f.png)

* Windows 10, build 1803
* Screen resolution 3840x2160
* PhpStorm 2018.2.5
* Material Theme UI 2.9.4 (default configuration setup)

Issue confirmed on a fresh PhpStorm installation without any additional plugins.

**Comment by mallowigi** [comment]
Please read the readme

**Comment by brezanac** [comment]
I already have, multiple times. The issue is once the plugin is installed there is no way to change the settings because the bug is also affecting that section.

![settings](https://user-images.githubusercontent.com/389770/47105674-e700d280-d244-11e8-9a83-c2d41cf76496.png)

Unfortunately, it seems removing the plugin completely is the only way to solve the issue for now.

**Comment by mallowigi** [comment]
Hey, I've added a new update which would bundle the fonts inside the plugin. Unfortunately I couldn't try it since the bug doesn't reproduce in my workstation.

Can you please update to 2.9.4.1 and tell me if that fixes it? Thanks

**Comment by brezanac** [comment]
Thank you but unfortunately I also have no way of testing if the patch solves the issue now since I replaced the entire Roboto font family on all my computers yesterday. That solved the issue but I am left with no means to recreate the state of the machine which exhibits the issue.
