### ISSUE TITLE
Text entry box height too small to see text 

### ISSUE THREAD

**Issue by justinfx** [ChrisRM/material-theme-jetbrains#1003]
### Summary

After configuring my Material Theme settings, I found that when trying to set up the "Environment variables" field for a unittest, that the text entry fields for the key and value were so short that I couldn't read the text.

### Expected behavior

Text boxes should have proper height to view text contents

### Actual behavior

Text is either partially or fully clipped by the lack of height in the text box

### Steps to reproduce (if needed)

I've narrowed it down to having Material Design Components enabled in the Features. Furthermore if Compact Table Cells is enabled the problem is the worst case. Disabling the compact option lets me see maybe 60% of the height of the text.

Selected theme: Monokai Pro

1. Click the unittest dropdown in the upper toolbar and choose Edit Configurations
2.  Click the folder icon on the right side of "Environment variables" for the configuration screen of a unittest
3. Click + to add a new env line
4. Type text into the Name or Value fields and note that part of the text is clipped
5. Go to Material Theme settings and enable Compact Table Cells
6. Repeat steps 1-4 and notice problem is even more pronounced
7. Go to Material Theme settings and disable Features Material Design Components
8. Repeat steps 1-4 and notice problem is no longer present

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* Linux
* IntelliJ Ultimate 2018.3 EAP
* Material Theme Plugin version 2.10.3

**Comment by mallowigi** [comment]
There is no easy fix for that, it involves Jetbrains code and I can't change it. However I found out that if you enter one value, any value, then press save, once you open it again it will render it better.
