### ISSUE TITLE
roboto font failed to show Chinese font

### ISSUE THREAD

**Issue by wangkezun** [ChrisRM/material-theme-jetbrains#1005]
### Summary

default roboto font failed to show Chinese comment

### Expected behavior

default roboto font will show Chinese 

### Actual behavior

default roboto font failed to show Chinese 

### Steps to reproduce (if needed)

default roboto font screen 
![image](https://user-images.githubusercontent.com/3012882/47195320-fccddf00-d38d-11e8-8624-9d8dcb178809.png)

override roboto with lucida grande 
![image](https://user-images.githubusercontent.com/3012882/47195393-41597a80-d38e-11e8-81ed-48f01c36a6d8.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
Hum. I know that there is a Chinese version of roboto but I didn’t bundle it.

I’ll do it soon.

**Comment by mallowigi** [comment]
Try to download 2.9.4.3 and tell me the results
