### ISSUE TITLE
No Differentiation for Texts with Links in Notification

### ISSUE THREAD

**Issue by axopadyani** [ChrisRM/material-theme-jetbrains#1006]
Below, the "Restart" text is a link, but there's no differentiation for that from the other text.

![image](https://user-images.githubusercontent.com/23306744/47196649-cf803180-d38b-11e8-8175-3b022432d92a.png)

I know that's clickable when I hover to that text, but there's no way I could have known beforehand. It's not a big deal, but I hope there's some kind of differentiation (color, underline, etc.) between links and regular texts in the notification.

Great theme, though. Thanks!

**Comment by mallowigi** [comment]
I don’t think that’s a good idea, the accent color is more than enough.

**Comment by axopadyani** [comment]
Oh, I didn't even realize that's different. I'm partially colorblind. :laughing: 
Could you make that accent a little more different than the text color? For all the partially colorblind programmers, like me. :laughing:

**Comment by mallowigi** [comment]
You know there was a wizard that was asking you your preferred accent color, right?

Can you please read the documentation? You might find all your answers as well as stuff that can interest you.

--
Elior
