### ISSUE TITLE
Pycharm Language/Font Changed 

### ISSUE THREAD

**Issue by Invisible786** [ChrisRM/material-theme-jetbrains#1008]
I installed Material Theme UI from plugins when i restarted the Pycharm , either the language or fonts or don't know what changed and now i can't read anything .
I am using Windows OS,
Latest Pycharm Community Version 
Help me with this, I am attaching a screenshot 
Please Don't close this issue without solving it...

 
![untitled](https://user-images.githubusercontent.com/27002169/47232970-e015c380-d3ee-11e8-909d-b04245b54037.png)

**Comment by mallowigi** [comment]
Which version of the plugin are you on?

**Comment by Invisible786** [comment]
Its "v 2.9.4.3 which is updated on 19-10-2018 " as i can see on browse respositories....
I uninstalled the plugin to see the version
![image](https://user-images.githubusercontent.com/27002169/47233757-5a474780-d3f1-11e8-99fb-d427c36e1d40.png)

**Comment by mallowigi** [comment]
damn.................. that means that we're back to square one, it is using the wrong version of Roboto... 

Can you connect to Slack?

**Comment by Invisible786** [comment]
what is Slack ? I don't know about it!!!!

**Comment by mallowigi** [comment]
https://join.slack.com/t/material-theme-ui/shared_invite/enQtMzgzNTUxMjQ2MTQ1LWU3Y2ZlYTBlNDEyZmU5YTMzNjAxZjc0NmVkMTk1NzdmNDI1NDAwMzI4NWYxZjVmYzUyYTgwZWEzNjE2YTg2NTA

**Comment by Invisible786** [comment]
ok now i have joined on slack  and your workplace, Whats next ?
