### ISSUE TITLE
Material Components with Default Theme

### ISSUE THREAD

**Issue by mxyzve** [ChrisRM/material-theme-jetbrains#1009]
### Summary
I wanted to use the default Light Theme by PhpStorm but with the Material Options, like Project View, Icons, etc.
But there seems to be an odd behaviour. Some of the Settings will take effect, some won't or not as expected.

### Expected behavior
Material styling/components will take effect on the Default Themes shipped by JetBrains.

### Actual behavior
Settings which don't have an effect:
- Custom Sidebar Height
- Custom Tree

Settings which not work as expected:
- Arrow Style will always be Material, whatever choosen in the settings.
- Style will always be Compact Status Bar. If you change it for example via (CMD+Shift+A) the whole color schema change to a dark one.

### Steps to reproduce (if needed)

<img width="1205" alt="bildschirmfoto 2018-10-20 um 13 24 56" src="https://user-images.githubusercontent.com/24508472/47255156-d468e200-d46c-11e8-8ca6-b89c44a951f3.png">

![material](https://user-images.githubusercontent.com/24508472/47255171-172aba00-d46d-11e8-9f68-d95f9cc39eb1.gif)

### Environment

PhpStorm 2018.2.5
Build #PS-182.4892.16, built on October 11, 2018
Licensed to ***
Subscription is active until February 13, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

**Comment by mallowigi** [comment]
This is intended, albeit not explained very well. What you should know is that disabling the Material Components disable all components customizations, which means not only the apperance (checkboxes, dropdowns...) but also simple tweaks such as the Status Bar or the Dropdown items padding. 

So since the StatusBar is the default one, options such as compact status bar will not apply. Same for the Tree, since it is using the default tree, customizations like the Tree Row Height, Custom indent or Arrows will not apply as well.

But that's true, it shouldn't be like that. Some components should be allowed to be replaced even when the option is disabled.

Good find.

**Comment by mallowigi** [comment]
Update to the latest version and tell me the resoluts

**Comment by mxyzve** [comment]
Hello mallowigi,

thanks for working on the problem.

Maybe the mistake is mine and I don't understand or expressed it correctly.  😄 Sorry for that.

I will try to explain what I would like to do or what I think should be the intended behavior:
I want to use the default Light Theme with Material components (Large Status Bar, Custom Sidebar Height, Material Icons, everything in "advanced settings").

Because of that, I selected "Material Design Components" and try to set the settings I would like to be applied e.g. Custom Sidebar Height, Material UI Icons etc.

I thought, that first the styling of the selected theme (Default Light Theme, Darcula, Material, Atom...) is applied and after that, the customization of the advanced settings will be applied and change the stylings of the different components like the status bar, tree view, etc. 

Some settings will take effect, like the Material icons, but some don't take effect like the custom sidebar height or the status bar height or the arrow style.


I updated to the latest version:
- the arrow styling still will be Material, no matter what I have selected (Darcula)
- the status bar is still the compact one, no matter if I toggle the settings on or off
- the settings of the custom sidebar height don't have an effect

But as I said, maybe I am wrong and misunderstand how the stylings are applied.

**Comment by mxyzve** [comment]
Yes. For example the arrow style.
![material](https://user-images.githubusercontent.com/24508472/47266777-6ccd9800-d53b-11e8-8bd6-28b6fd38aa6a.gif)

**Comment by mallowigi** [comment]
Ok I understand it better. I'm afraid of such a change however, as it would mean refactoring my codebase.

I'd keep you informed

**Comment by mallowigi** [comment]
Please upgrade to the latest version!
