### ISSUE TITLE
Material standard folder icons are shown even when all material icons are disabled

### ISSUE THREAD

**Issue by marhkb** [ChrisRM/material-theme-jetbrains#1010]
### Summary
I have disabled all material icons in the preferences dialog. But for the standard folders in the project explorer the material icon is shown instead of the stock folder icon. Folders for "src", "resources" and packages correctly use the stock icons, but not the standard folders. One can see that those are not pixel perfect.
...

### Expected behavior
If all checkboxes in the Icons tab from the material preferences are unchecked the stock standard folder icon should be displayed in the project explorer.
...

### Actual behavior
The material standard folder icons are shown instead of the stock folder icons.
...

### Environment
IntelliJ IDEA 2018.2.5 (Community Edition)
Build #IC-182.4892.20, built on October 19, 2018
JRE: 1.8.0_152-release-1343-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.76-1-lts
Material version: 2.9.4.3

![darcula](https://user-images.githubusercontent.com/3630213/47255723-bf448100-d475-11e8-8929-7aa77fe2e3cd.png)
![material](https://user-images.githubusercontent.com/3630213/47255724-bf448100-d475-11e8-9dde-f8a67abd21a6.png)
![settings](https://user-images.githubusercontent.com/3630213/47255725-bf448100-d475-11e8-946b-eadba935f17f.png)

**Comment by mallowigi** [comment]
Yes this is a remainder of the issue that was plaguing the 2.9.1 release and this is the workaround proposed: that some icons like the folders, the pencils or the loading circles will stay material based instead of togglable.

It’s too dangerous to do otherwise, so at the moment this is not changeable

**Comment by marhkb** [comment]
Ok, then it is a known issue.
Thanks for the explanation.

**Comment by mallowigi** [comment]
Fixed in 2.9.5
