### ISSUE TITLE
How to make Tab height smaller

### ISSUE THREAD

**Issue by xinkunZ** [ChrisRM/material-theme-jetbrains#1013]
![image](https://user-images.githubusercontent.com/7759897/47276668-4e26da00-d5eb-11e8-9e1e-dafed0e49872.png)

- I like old tab height (on IDEA 18.2) more than 18.3
- It looks too fat, not cool

**Comment by xinkunZ** [comment]
em....
if it's not problem with Mterial theme plugin, why this tab height back to normal after disable this plugin?
![image](https://user-images.githubusercontent.com/7759897/47405508-6b42e080-d784-11e8-9947-47db16aae926.png)

**Comment by mallowigi** [comment]
Oh I didn’t know that. I’ll investigate.

Maybe it has something to do with the tab height option?

**Comment by xinkunZ** [comment]
yeah!

**Comment by vemilyus** [comment]
I just confirmed that this is an issue that arose with 2018.3. In 2018.2 the tab height setting works just fine.

**Comment by mallowigi** [comment]
Will be fixed in next release (2018.3) by setting the compact statusbar to true. I won't add a setting for that.
