### ISSUE TITLE
Override default fonts by doesn't work in 2.10.5

### ISSUE THREAD

**Issue by Alexgmin** [ChrisRM/material-theme-jetbrains#1014]
### Summary

On Ubuntu 18.04 the default system font is called "Ubuntu". This is the font that PyCharm used for the IDE UI. This could be changed in Appearance & Behavior > Appearance > Override default fonts by.

After upgrading from 2.10.3 to 2.10.5 Roboto is used everywhere in the UI. Using Override default fonts results in a weird combination of fonts
![image](https://user-images.githubusercontent.com/8340441/47286262-37ce4d80-d5ee-11e8-9268-8f029be41ffb.png)

Without that Roboto Material is used.
I would like to use "Ubuntu" for the UI again.

### Environment
PyCharm 2018.3 EAP (Professional Edition)
Build #PY-183.3795.9, built on October 16, 2018
JRE: 1.8.0_152-release-1343-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic

Material Theme UI v2.10.5

**Comment by mallowigi** [comment]
You need to disable the Material Fonts feature or check the “override fonts” option. Also don’t worry this is a bug from the ide, but as soon as you restart you will get the font applied to all the components.
