### ISSUE TITLE
Bug: Search input in settings

### ISSUE THREAD

**Issue by vladamx** [ChrisRM/material-theme-jetbrains#1016]
### Summary
Clear button for search input in settings is a bit off.

### Expected behavior
Clear button should be completely visible.

### Actual behavior
Clear button is not properly aligned.

### Steps to reproduce

1. Go to settings
2. Start typing in search input
3. Notice clear button alignment

![image](https://user-images.githubusercontent.com/11381171/47357096-23f61a80-d6c6-11e8-9a26-05ce7a278849.png)

### Environment

Android Studio 3.2
Build #AI-181.5540.7.32.5014246, built on September 17, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-38-generic

**Comment by vladamx** [comment]
It works on latest canary. 
However, it is a shame that someone needs to use bleeding-edge build for the theme to work properly.

I guess you can close the issue now, sorry for bothering.

**Comment by mallowigi** [comment]
Blame it on Android Studio to stay on 2018.1 even though we are almost in 2019
