### ISSUE TITLE
Add more icons for common folder types and options to customize folder icons

### ISSUE THREAD

**Issue by RastislavMirek** [ChrisRM/material-theme-jetbrains#1017]
Folder icons are one of the best features in Material Theme. They are crystal clear and  because icons are faster to recognize than text, they make it much easier to navigate large projects in Project Tool Window. This value increases with more icons for common folder types.

There are a few common folder icons that I am missing:

1. _Helper_ / _Utility_ folder - this is folder that is found in almost every project. Such icon is part of similar plugins e.g. Material Icons for VSCode
2. _Saga_ / _redux-saga_ folder that often contains project sagas, common in React projects
3. _Thunk_ / _redux-thunk_ folder, another common folder in React projects, almost as common as Reducer & Action folders
4. Specific icon for _react-components_ that is consistant with React folder icon
5. _Repository_ folder that contains implementation of repository pattern (reuse Database icon for this one?)

Some of these are specific to React but I am sure there are more for other frameworks and languages that would be usefull.

It would also be great if we could asign custom icons (or pick one of icons already bundled with Material Theme) to specific folders. 
Besides obvious use to visualize project specific folders it also solves these use case: 

- Some developers prefer different names for common folders e.g. _redux-action_ instead of _action_, _source_ instead of _src_, etc.
- Sometimes, the icon assigned by default is not appropriate, e.g. I use _Layout_ folder for different purpose than the icon visualizes

**Comment by mallowigi** [comment]
Yeah this feature is on my roadmap but it is a very hard to implement one, so I’m leaving it for a future version, once all bugs have been squashed and the 2018.3 eap is out.

But for the first version what I want to do is something like custom theme where people can edit their associations directly within the xml and afterwards design an interface for easier use (and thousand of bugs along the way)

In the meanwhile I’m taking your requests into consideration, but maybe you can send me a pr for the icons and associations you want to add.

**Comment by RastislavMirek** [comment]
@mallowigi Thank you for fast reply. Everything that you wrote sounds good to me. 
What do you mean by PR? I am mostly lost in English abbreviations...

**Comment by mallowigi** [comment]
Pull request

**Comment by RastislavMirek** [comment]
@mallowigi I'd love to but unfortunatelly I am no designer... Are those folder icons custom designed or are you using some set?
