### ISSUE TITLE
PHPStorm button styles break in 2.9.5.1

### ISSUE THREAD

**Issue by GabeAtWork** [ChrisRM/material-theme-jetbrains#1018]
### Summary

Button styles break in 2.9.5.1

### Expected behavior

The theme should not alter button styles in Phpstorm's config buttons.
Here, a screenshot when the theme is disabled:

*Github's image upload is broken, I'll retry later*

### Actual behavior

Default OS button styles are displayed. This happens whichever theme is enabled in Material UI (Custom Theme and others as well).
Here, a screenshot when the theme is enabled:

*Github's image upload is broken, I'll retry later*

### Environment

* PhpStorm 2018.2.5
* Build #PS-182.4892.16, built on October 11, 2018
* JRE: 1.8.0_152-release-1248-b8 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.13.6
* Material Theme Plugin version 2.9.5.1

**Comment by mallowigi** [comment]
can you post screenshots now ?

**Comment by GabeAtWork** [comment]
Still not I'm afraid, getting 500 on an OPTIONS request on `https://github-production-user-asset-6210df.s3.amazonaws.com/` 😕

**Comment by mallowigi** [comment]
Anyways can you post your material configureation here?

**Comment by GabeAtWork** [comment]
I've looked around the docs, looked at Phpstorm docs and snooped around PhpStorm config files on my Mac but I can't seem find it. Do you know where it's supposed to be located?

**Comment by mallowigi** [comment]
It’s in /Library/Preferences/.PhpStormXX/config

**Comment by GabeAtWork** [comment]
I'm afraid there's not `PhpStorm` related directory in `/Library/Preferences`. There are `PhpStormXX` folders in `~/Library/Preferences/`, but they don't contain a file or folder named `config`. Here's the content of the latest PhpStorm folder:

```
codestyles
colors
consoles
disabled_plugins.txt
disabled_update.txt
extensions
fileTemplates
inspection
javascript
jdbc-drivers
keymaps
options
phpstorm.key
phpstorm.vmoptions
port
port.lock
scratches
tasks
templates
tools
user.web.token
```

**Comment by mallowigi** [comment]
Check this: 

https://github.com/ChrisRM/material-theme-jetbrains/issues/1021
