### ISSUE TITLE
variable value displayed with strange character

### ISSUE THREAD

**Issue by guillaumesoul** [ChrisRM/material-theme-jetbrains#1019]
### Summary
With PHPStorm in debug window variable with value true, false and null display strange characters (don't know where these letter come fom but not from any known alphabet to me)

WithDataGrip same strange char displayed when input in filter_criteria (for example like operator is changed to strange char when inputting the final e)

### Expected behavior

To have correct char displayed

### Actual behavior

strange char displayed

DataGrip : 
![image](https://user-images.githubusercontent.com/3829351/47431082-650c2e80-d79b-11e8-93c6-492a5b69944e.png)

PHPStorm : 
![image](https://user-images.githubusercontent.com/3829351/47431267-c59b6b80-d79b-11e8-802b-e65d571ac83e.png)

### Environment
It is happenning since a while a version of phpstorm and datagrip doesn't seem to have an impact on it but here are my actual versions anyway

DataGrip : 
DataGrip 2018.2.4
Build #DB-182.4505.23, built on September 18, 2018
You have a perpetual fallback license for this version
Subscription is active until October 19, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
Material Theme UI version 2.9.5.2

PHPStorm : 
PhpStorm 2018.3 EAP
Build #PS-183.3647.13, built on October 10, 2018
PhpStorm EAP User
Expiration date: November 9, 2018
JRE: 1.8.0_152-release-1343-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by mallowigi** [comment]
please download last version of the plugin (2.10.5)
