### ISSUE TITLE
commit/push button is not visible

### ISSUE THREAD

**Issue by SmelayaPanda** [ChrisRM/material-theme-jetbrains#1021]
WebStorm => Git commit modal => no commit/push button after last update v. 2.9.5.2
Resize of modal doesn't help
<img width="726" alt="screen shot 2018-10-25 at 3 15 41 pm" src="https://user-images.githubusercontent.com/17514596/47486272-2b562900-d86a-11e8-963c-132fe1cbc6e6.png">

**Comment by mallowigi** [comment]
Webstorm version ?

**Comment by mallowigi** [comment]
Check that : `Settings > Material Theme > Features > Material Components` is enabled and that `Settings > Appearance> Theme` is Darcula, then restart the IDE

**Comment by SmelayaPanda** [comment]
That helped, thanks for amazing product =)!

**Comment by Gordondalos** [comment]
all theme not working,  forced to delete, without a push button, working is not convenient

**Comment by Lodin** [comment]
It also appears for me in WebStorm 2019.2.3 on Windows 10. The solution suggested by @mallowigi does not help, unfortunately.

![image](https://user-images.githubusercontent.com/8037479/66685145-522c8b80-ec84-11e9-85e3-934e1afb6a3c.png)
