### ISSUE TITLE
CMD+SHIFT+O unusually long indexing

### ISSUE THREAD

**Issue by tylerbobella** [ChrisRM/material-theme-jetbrains#1022]
### Summary

When `CMD+SHIFT+O` is used there seems to be a very long time to be able to start typing to search for a file. It almost seems as though there is some re-indexing happening. You have to wait ~10-15 seconds to start typing and searching

### Expected behavior

Searching for a file should work with default themes

### Actual behavior

Indexing (or something) is occurring when the file search bar is opened. 

### Steps to reproduce (if needed)

1. Using Oceanic Theme
2. Do `CMD+SHIFT+O` and attempt to immediately type for a file.

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
Licensed to Capria Solutions / Tyler Bobella
Subscription is active until April 7, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.1

Material Theme UI:
Version: 2.9.5.4

**Comment by mallowigi** [comment]
Hi

Can you try in the latest version of the IDE (2018.2.5)? Also clearing cache can help.

**Comment by tylerbobella** [comment]
hey! i was able to fix this with a reinstall.
