### ISSUE TITLE
Strange background color for excluded directories

### ISSUE THREAD

**Issue by wazum** [ChrisRM/material-theme-jetbrains#1023]
I found no setting to change the background color of excluded directories

<img width="372" alt="screen shot 2018-10-26 at 13 40 27" src="https://user-images.githubusercontent.com/146727/47564696-25be1900-d926-11e8-9979-0ccc0ed2079b.png">

**Comment by mallowigi** [comment]
You're right I need to update the documentation, but incidentally you'll find all the information here: 

http://www.material-theme.com/docs/configuration/excluded-files-colors/

I'll update this page in a jiffy.
