### ISSUE TITLE
[feature request] Dim down git gutter colors

### ISSUE THREAD

**Issue by ilyador** [ChrisRM/material-theme-jetbrains#1024]
Right now, in dark mode, the git change indicator colors are the brightest colors in the whole UI.
It will be great if you can tone them down so they will not stand out so much.
<img width="131" alt="screen shot 2018-10-26 at 15 29 46" src="https://user-images.githubusercontent.com/703551/47569481-0332fc80-d934-11e8-8f4e-bd0b5b8d0d21.png">

**Comment by mallowigi** [comment]
You can change them in the Color Scheme settings: `Settings > Editor > Color Scheme > VCS`
