### ISSUE TITLE
Easy configuration of UI font size vs. Editor font size

### ISSUE THREAD

**Issue by jpap** [ChrisRM/material-theme-jetbrains#1025]
It looks like  `Settings > Material Theme > Advanced Settings | Project View > Font Size` sets the UI font size, and not the editor font size.  Making that obvious by renaming that to something like "Override default UI font size" might be a good idea.

Similarly, it is not clear how one could actually change the editor font size:

1. The above option doesn't do it.
2. Setting the font size via `Settings > Editor > Font > Size` doesn't change it when the Material Theme plugin is in use.
3. I see older comments e.g. #249 or on [StackOverflow](http://stackoverflow.com/a/17545660/3173279) to "copy the theme and customize", but there's no path to doing that in the Material Theme configuration under `Settings > Appearance & Behavior >  Material Theme`.  (Was this removed sometime since 2016?)
4. The only route I see is to [create a new external theme](http://www.material-theme.com/docs/development/external-themes/)... I must be missing something here, because that would be overboard just to change the editor font size?!

Ideally I'd love to see:

1. A configuration option to change the editor font size, overriding what might be specified in the theme.
2. A keymap to increase and decrease the font size, similar to CMD-{+,-} on macOS in your browser (or other IDEs, like Visual Studio Code).

**Comment by mallowigi** [comment]
You’re talking about a basic feature of the IDE, something that has been here for ages and there is plenty of documentation for that. It’s completely unrelated to the plugin, even though it could be done via the plugin as well.

Changing the editor font is utterly simple and I have no idea how you missed that. Simply go to `Settings > Editor > Color Scheme > Color Scheme font` and select the font and font size of your choice. It’s as simple as that :)

**Comment by kompiuter** [comment]
@mallowigi I've done the steps you described yet editor font size stays the same.

@jpap Have you got it to work?

I'm on Ubuntu.

**Comment by wmsheng** [comment]
I have tried this way and it worked: Settings(or Ctrl + Alt + s)-> Editor -> Color Scheme -> Color Scheme Font.
Then you can change the "size" and it works with no necessary to restart the IDEA.

**Comment by aditya02468** [comment]
just open android studio and search for Color Scheme Font in the search bar and there you can change the font
