### ISSUE TITLE
2.9.6 Use feedback

### ISSUE THREAD

**Issue by hwtl** [ChrisRM/material-theme-jetbrains#1026]
1, the latest version 2.9.6 Chinese garbled
![image](https://user-images.githubusercontent.com/2331062/47635396-cd8a4f80-db8f-11e8-9fab-fa1071f3cdc3.png)
![image](https://user-images.githubusercontent.com/2331062/47635478-18a46280-db90-11e8-9f5e-1b363a201c07.png)

2, the run window font defaults all uppercase
![image](https://user-images.githubusercontent.com/2331062/47635430-f14d9580-db8f-11e8-84aa-059e3284ecee.png)
![image](https://user-images.githubusercontent.com/2331062/47635434-f579b300-db8f-11e8-9e1e-6ae012a08924.png)

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/47636337-9badc480-db60-11e8-97f4-7f781aad22c6.png)

Change the font here

**Comment by hwtl** [comment]
Thank you,
Is it necessary to modify the font in your picture?
If not, then modifying the font in this place will not solve the above problem.

**Comment by hwtl** [comment]
> ![image](https://user-images.githubusercontent.com/5015756/47636337-9badc480-db60-11e8-97f4-7f781aad22c6.png)
> 
> Change the font here

Thank you,
Is it necessary to modify the font in your picture?
If not, then modifying the font in this place will not solve the above problem.
