### ISSUE TITLE
Code is grey in 2.9.6

### ISSUE THREAD

**Issue by michalzubkowicz** [ChrisRM/material-theme-jetbrains#1028]
All TypeScript code is grey (look like comments after upgrade to 2.9.6). 

After downgrade to 2.9.5.4 everything is ok 

![obraz](https://user-images.githubusercontent.com/3389709/47677517-a186c280-dbbf-11e8-9520-484563e6e759.png)

### Environment
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29deepin-generic

**Comment by michalzubkowicz** [comment]
Still the same problem on 2.9.6.2

**Comment by mallowigi** [comment]
Have you done that: 
![image](https://user-images.githubusercontent.com/5015756/47703918-7dac9680-dc2a-11e8-9f7e-1a2f1ee6208d.png)

**Comment by mallowigi** [comment]
I can't reproduce... Are you talking about a specific color scheme ?

**Comment by BudiNverse** [comment]
Same exact issue with OP except that it only affects Material Darker Theme. All default settings
Lang: Typescript
Plugin version: 2.9.6

Material Darker
![bug](https://user-images.githubusercontent.com/18619849/47731329-d61d7b80-dc9e-11e8-8292-315a49408c02.JPG)

Atom One Dark
![nobug](https://user-images.githubusercontent.com/18619849/47731450-1bda4400-dc9f-11e8-8b33-244bbdefcbea.JPG)

**Comment by mallowigi** [comment]
Darker, OneDark and Palenight.

So weird

**Comment by mallowigi** [comment]
Somehow it failed before 2.9.6.2. Investigating

**Comment by mallowigi** [comment]
Ok i finally found the problem. Will issue a fix right away
