### ISSUE TITLE
Introduce Material Fonts v2

### ISSUE THREAD

**Issue by hwtl** [ChrisRM/material-theme-jetbrains#1029]
> 
> Change the font here

Thank you,
Is it necessary to modify the font in your picture?
If not, then modifying the font in this place will not solve the above problem.

_Originally posted by @hwtl in https://github.com/ChrisRM/material-theme-jetbrains/issues/1026#issuecomment-433829507_

**Comment by hwtl** [comment]
> This page is what is used for the font in text fields like the search bar or search everywhere. It is loaded at the start of the application which is why it requires restart.
> 
> You will need to select a font that can display chinese characters.

Thank you, but I was normal before upgrading 2.9.6. This happens after the upgrade. The font used is the font that comes with the mac system: monaco

**Comment by mallowigi** [comment]
Hmm I see a recurring behavior. I need to change that.

Type Ctrl+Shift+A (or CMD-Shift-A), then Registry, then check if you have the option "bigger.font.in.project.view" turned on. If that's the case, uncheck it and restart.

**Comment by hwtl** [comment]
> Hmm I see a recurring behavior. I need to change that.
> 
> Type Ctrl+Shift+A (or CMD-Shift-A), then Registry, then check if you have the option "bigger.font.in.project.view" turned on. If that's the case, uncheck it and restart.

perfect
