### ISSUE TITLE
Separate interface design from color scheme

### ISSUE THREAD

**Issue by Kendos-Kenlen** [ChrisRM/material-theme-jetbrains#103]
It's not a priority, but it could be good to have possibility to set separately the UI design and the color scheme like IDEA does with default and darcula designs using the "Appearance & Behavior => Appearance => Theme" option to set the UI design, and the color scheme option to set the color scheme itself.

Could be good for those who prefer to keep their current color scheme for example (even if the material one is good).

**Comment by ciscorucinski** [comment]
Correctly me if I am wrong, but you are talking about separating the whole of the IDE theme, and the Text Editor Color scheme?

That is currently what is available. Chris' Material Theme is not displayed in the dropdown menu, but it is there. If you are talking about creating a menu item for the Material theme, then I agree.

You can independently change the IDE Theme and the Color scheme.

Alternatives to Chris' color schemes:
 - You already SAVED your previous color scheme from before (you gave it a new name already), just select that color scheme in `Editor >> Colors & Fonts >> Scheme`
 - I provide only Color Schemes based on this Theme here - https://github.com/ciscorucinski/ChroMATERIAL

Just keep in mind that the background color of the Text Editor and the background color of the IDE in general will not match if you don't use ChrisRM's or my color scheme.

**Comment by ChrisRM** [comment]
@Kendos-Kenlen You are free to use whatever color scheme you like for the editor. Open your settings and change your color scheme under `Editor` -> `Colors & fonts`

**Comment by Kendos-Kenlen** [comment]
Hi,

Okay, I know where my mistake came from. At the first launching of the plugin, user need to go in `Colors & fonts` to change the theme. Next time, he have to use the menu in `Tools`, and I thought the settings in `Colors & fonts` was for the entire look and feel.

Sorry for the mistake.

But I still think that it could be a good idea to use the "real" theme menu to easily switch between LaF (classic themes and material themes), as currently the plugin override the current theme.

And to avoid to go in the settings to switch the color scheme, I think it's possible to do it automatically when the user select the LaF, as it's done when select Darcula.
