### ISSUE TITLE
bad chinese font in edit database table comment 

### ISSUE THREAD

**Issue by wsteel** [ChrisRM/material-theme-jetbrains#1030]
### bad chinese font in edit database comment 

when i use v2.9.5.1 , everything is fine , 
since update to v2.9.5.2 , font display error.

database table columns
![db_list](https://user-images.githubusercontent.com/20486291/47769382-aad67300-dd16-11e8-88b8-ed038e53232d.jpg)

v2.9.5.1 is ok
![db_right](https://user-images.githubusercontent.com/20486291/47769437-dbb6a800-dd16-11e8-98ee-abca94a55cc9.jpg)

since update to v2.9.5.2 , font display error.
![db_bad](https://user-images.githubusercontent.com/20486291/47769458-f557ef80-dd16-11e8-8069-1d75fc91754c.jpg)

### Environment
PhpStorm 2018.2.5
Build #PS-182.4892.16, built on October 11, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by hokut-o** [comment]
A similar problem happens in Japanese.

search box
![image](https://user-images.githubusercontent.com/10446161/47770137-9481e480-dd21-11e8-834f-4334aff765c0.png)

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/1026
