### ISSUE TITLE
Accept button covered, and not visible in some modals

### ISSUE THREAD

**Issue by Vanluren** [ChrisRM/material-theme-jetbrains#1031]
### Summary
The cancel button covers "Ok" button in some modals. In others the "Ok" button isn't visible at all.

...

### Expected behavior
That the "Ok"/Accept button is clear, whith some whitespace around it, and that the user can interact with the button.
...

### Actual behavior
Since the button is covered, the button is hard to interact with. In the other example, the button cannot be interacted with, since it is not visible to the user.
...

### Steps to reproduce (if needed)

<img width="530" alt="screenshot 2018-10-31 at 11 32 07" src="https://user-images.githubusercontent.com/3931039/47782867-86bc6700-dd01-11e8-922b-0c807e7193ff.png">
<img width="1440" alt="screenshot 2018-10-31 at 11 39 11" src="https://user-images.githubusercontent.com/3931039/47782898-9cca2780-dd01-11e8-8582-942b56f6c720.png">
![Uploading Screenshot 2018-10-31 at 11.32.34.png…]()

### Environment

WebStorm 2018.2.5
Build #WS-182.4892.25, built on October 18, 2018
Licensed to Villads Valur Korsholm Nielsen
Subscription is active until January 21, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b19 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

Material Theme info:
version: 2.9.6.3

**Comment by mallowigi** [comment]
Please enable MAterial Components in settings
