### ISSUE TITLE
New JS Additions in Color Scheme Highlighted In Comment Headers

### ISSUE THREAD

**Issue by nazrhyn** [ChrisRM/material-theme-jetbrains#1032]
### Summary
Any of the words in the additions are highlighted inside of comment headers (`/**`). Line comments (`//`) and normal block comments (`/*`) are unaffected. Perhaps the new JS Additions caused this?

#### Material Disabled
![image](https://user-images.githubusercontent.com/1672405/47805178-0dc30c80-dd0d-11e8-917f-4f3aa09b6d2a.png)

#### Material Enabled
![image](https://user-images.githubusercontent.com/1672405/47805123-e9673000-dd0c-11e8-8f5f-cf91299dee14.png)

### Environment
WebStorm 2018.2.5
Build #WS-182.4892.25, built on October 18, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-38-generic (Ubuntu 18.04)
Plugin Version: 2.9.6.3

**Comment by mallowigi** [comment]
fixed in 2.9.6.4 (good find!)

**Comment by nazrhyn** [comment]
@mallowigi The stuff above was fixed in that update. Now I'm seeing this:   
<sup>(Technically, this may have been a problem back when I submitted this issue, but I didn't notice it; so, "now" might not be 100% accurate.)</sup>

![image](https://user-images.githubusercontent.com/1672405/48572858-a2666680-e8d8-11e8-951f-373b6d4faeb6.png)

I assume that the type "expression" inside of `{ ... }` is a different "context".
