### ISSUE TITLE
Color of 'this'

### ISSUE THREAD

**Issue by michaelcamper** [ChrisRM/material-theme-jetbrains#1033]
### Summary

Since the last update, the 'this' keyword is colored red. IMO, nothing but errors should appear in a red color.

### Expected behavior

The 'this' keyword not be colored red.

### Actual behavior

The 'this' keyword is colored red.

**Comment by mallowigi** [comment]
This is because it’s red in the Visual Studio Code version of the Material Theme.

**Comment by ph55** [comment]
Ye, so stupid. Why such huge change. 
People using this theme for quite long time. Why not leave default behaviour and add option to change it to red.
