### ISSUE TITLE
Code lens - bad readability using Atom One Dark

### ISSUE THREAD

**Issue by maxOS1104** [ChrisRM/material-theme-jetbrains#1035]
Hello there! Awesome work!
But using the Atom One Dark Theme, Code Lens is very hard to read (see image).
I have neither found a way to change the font color used in code lens nor a way to change the background color used in code lens.
How can I resolve this problem?

Thanks for your help!

<img width="871" alt="bildschirmfoto 2018-11-02 um 23 32 58" src="https://user-images.githubusercontent.com/4730112/47943862-8afea500-def8-11e8-9c8d-1e7dc2bcba98.png">

**Comment by mallowigi** [comment]
I’ve changed the color to a darker one, but it will be available on 2018.3 only
