### ISSUE TITLE
JavaScript additions incorrect import keywords styles 

### ISSUE THREAD

**Issue by r3b311i0n** [ChrisRM/material-theme-jetbrains#1038]
### Summary

JavaScript `from` keyword uses default keyword colour and import statements ignore font style.

### Expected behaviour

Respect settings in JavaScript Additions.

### Actual behaviour

Settings are ignored.

![materal-theme](https://user-images.githubusercontent.com/10097295/48044957-66365600-e1b4-11e8-9641-f3a2d325266f.png)

### Environment

Material Theme 2.9.6.4
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.16-arch1-1-ARCH

**Comment by mallowigi** [comment]
Try in version 3.0.0

**Comment by r3b311i0n** [comment]
Updated to 3.0.0-pre4. Still happens. But I noticed that it only seem to happen with the Material themes (doesn't happen with Dracula, Monokai, etc.).
