### ISSUE TITLE
uninstall this plugin,how to reset android studio wallpaper?

### ISSUE THREAD

**Issue by mrliul** [ChrisRM/material-theme-jetbrains#1041]
![75759ffb-3f48-46b2-88ef-c7d96665454f](https://user-images.githubusercontent.com/13918990/48304087-3d181b80-e54e-11e8-8a37-2109c6b5ef38.png)

macOS 10.14.1
android studio 3.2.1

1.set BackgroundImage  don't work

**Comment by mallowigi** [comment]
Check on closed issues, it has already been answered

**Comment by mrliul** [comment]
![21ef8f29-7bfa-409b-9ca2-59f101d19c9d](https://user-images.githubusercontent.com/13918990/48309947-1514d080-e5bf-11e8-8ff6-b51c8fdbb961.png)

in adnroid studio,this is last version ,there is no change wallpaper action. 
I want to remove this wallpaper? how to?

**Comment by cyclic-reference** [comment]
@mrliul

To manually remove the wallpaper

1. [Locate you idea settings directory using this link](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) (it should be called AndroidStudio3.2)
1. Open the file in `<your config dir>/AndroidStudio3.2/config/options/options.xml`
1. Remove the `property` node named `idea.background.frame`
1. Restart the IDE.

That should fix that issue :)

**Comment by mrliul** [comment]
@cyclic-reference  thanks ,it's ok.
