### ISSUE TITLE
A style issue in "regular expression" dialog

### ISSUE THREAD

**Issue by kuige** [ChrisRM/material-theme-jetbrains#1042]
### Summary

The outline inside the regular expression dialog is not so elegant , I think it should be polished. The current effect is shown below.

<img width="646" alt="regular expression dialog" src="https://user-images.githubusercontent.com/8212800/48335083-a8b9d000-e697-11e8-9219-a9adbb7ca8f6.png">

### Expected behavior

A better looking, restyled regular expression dialog.

### Actual behavior

The outline inside the dialog is not polished.

### Steps to reproduce (if needed)

1. Show the search dialog(⌘ + F)
2. Click the question mark next to the regex checkbox
3. The regular expression dialog appears

<img width="744" alt="image" src="https://user-images.githubusercontent.com/8212800/48332031-583d7500-e68d-11e8-8893-4aa87bee4a26.png">

### Environment

WebStorm 2018.2.4
Build #WS-182.4505.50, built on October 3, 2018
Licensed to ****
You have a perpetual fallback license for this version
Subscription is active until August 29, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
Material theme UI version: 2.9.6
Plugin configuration (default)
Material Oceanic

**Comment by mallowigi** [comment]
I am not the maker of this dialog, please contact jetbrains.
