### ISSUE TITLE
Tab Font Size

### ISSUE THREAD

**Issue by pycodev** [ChrisRM/material-theme-jetbrains#1046]
1. I want to change the color of folder icon. How can I do that?
![image](https://user-images.githubusercontent.com/9066414/48820695-16998200-ed91-11e8-90b0-02b4414d21a3.png)

2. It's possible to change font size of the text in editor tab?
![image](https://user-images.githubusercontent.com/9066414/48820610-af7bcd80-ed90-11e8-8a50-3158301e774f.png)
It's like too small....

thx :)

**Comment by mallowigi** [comment]
You can’t change the colors in the bundled themes, however you can do it with the custom themes. I think this is done by the “Text color” setting.

The tab font size cannot be changed as well, but I admit it can be a good idea.

**Comment by mallowigi** [comment]
done
