### ISSUE TITLE
Fix Rider icons

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#1048]
Rider Icons are implementing a different set than other JB products, but Material Icons should apply there as well.

**Comment by jefersonla** [comment]
I'm not sure if it's the same problem but in WebStorm some icons like core, shared and constants are not appearing :/

![image](https://user-images.githubusercontent.com/4985788/48882513-7c215900-edf9-11e8-9887-2e67b07df5d7.png)

I'm using MacOS HighSierra 10.13.6, the version of WebStorm is 2018.2.1 and the version of MaterialTheme UI is 2.9.6.4. (sorry for the informal bug report)

**Comment by mallowigi** [comment]
Try in 3.0.0
