### ISSUE TITLE
Editor color schema font reset after upgrade to 2018.3

### ISSUE THREAD

**Issue by crazy-max** [ChrisRM/material-theme-jetbrains#1049]
### Summary

Editor color scheme font back to Default after upgraded IntelliJ 2018.2.6 to 2018.3

#### 2018.2.6

![2018 2 6](https://user-images.githubusercontent.com/1951866/48871622-c8629e00-ede5-11e8-9c5b-778fb36e827c.png)

#### 2018.3

![2018 3](https://user-images.githubusercontent.com/1951866/48871629-d1ec0600-ede5-11e8-9cfc-7afaaa10224f.png)

### Workaround

I have to select Material Darker in Editor > Color Scheme > Color Scheme Font :

![image8](https://user-images.githubusercontent.com/1951866/48871765-5fc7f100-ede6-11e8-94d4-49c8dfaa1443.png)

And it looks better now :

![image](https://user-images.githubusercontent.com/1951866/48871791-7bcb9280-ede6-11e8-82be-79e6f51f85a5.png)

### Environment

```
IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Licensed to XXX
Subscription is active until XXX
For non-commercial open source development only.
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

Material Theme **v2.10.6**

**Comment by mallowigi** [comment]
Is it happening at every restart or just after you updated?

**Comment by rashidul0405** [comment]
It happened to me as well, Looks like you have to upgrade the plugin manually, please check updates tab: https://d.pr/i/UXDEOy

**Comment by crazy-max** [comment]
@mallowigi Just after the update

**Comment by heregoesnoth** [comment]
@rashidul0405 same here with material theme e other plugins, like scala and lombok. Just reinstall (uninstal and install again) and works fine now.

**Comment by mallowigi** [comment]
No idea why is it happening, surely due to the major refactor. Anyway if it's not repeated then it's minor and I don't have the time to investigate such issues
