### ISSUE TITLE
can not find my ICONS!!!!!!!!!!

### ISSUE THREAD

**Issue by Rowandjj** [ChrisRM/material-theme-jetbrains#105]
in android studio,after i compiled the project,all icons are gone......
<img width="222" alt="2015-10-31 1 20 41" src="https://cloud.githubusercontent.com/assets/5766252/10862007/44f7321c-7fd2-11e5-95fa-670f5a0894e9.png">

**Comment by Rowandjj** [comment]
please fix the problem........

**Comment by ChrisRM** [comment]
With that attitude I might just wait a while before I look at this.

**Comment by jaaaaaaaaaam** [comment]
![screen shot 2015-11-04 at 10 11 02](https://cloud.githubusercontent.com/assets/4105611/10935206/60f96b94-82dc-11e5-8eed-984bc756bc09.png)
 also have this issue, not sure if it is a memory related issue or not though.

Using phpstorm 9, OSX 10.11

**Comment by montogeek** [comment]
Hi @ChrisRM First, sorry for that dude attitude, I dream with a OO era which all people realize that nobody is a slave and realize that you are not paying for it.

I installed your port on PHPStorm v9, it shows the same issue. Is very odd, sometimes are all the icons, sometimes is just some. I noticed that if you open the file the icon show up.

![Uploading Screen Shot 2015-11-06 at 22.14.02.png…]()

Thanks for create this excellent Material port.

Have a good weekend!

**Comment by montogeek** [comment]
After upgrading to PHPStorm 10 all icon are displayed correctly.
Probably was a cache thing.

**Comment by HeikoKanzler** [comment]
I installed the Theme and have the same issue with IntelliJ 14. After loading the application, all icons are there, but then the start disappearing. Similar to the screenshot montogeek was displaying.

**Comment by ChrisRM** [comment]
@HeikoKanzler Is this still an issue for you? Try the newest build and let me know.
