### ISSUE TITLE
Hardly visible disabled fonts on 3.0.0-pre1

### ISSUE THREAD

**Issue by pahan35** [ChrisRM/material-theme-jetbrains#1050]
### Summary
I noticed broken disabled text color right after updating to **3.0.0-pre1**

### Expected behavior
I see normal colors for disabled text

### Actual behavior
The disabled text is hardly visible

### Steps to reproduce (if needed)

1. Setup 3.0.0-pre1
2. Restart IDE
3. Open some setup page with disabled options. I've opened `Settings->Languages & Frameworks->JavaScript->Code Quality Tools->ESLint`
![image](https://user-images.githubusercontent.com/13823215/48879653-75084400-ee15-11e8-9992-8e18a2ca62ab.png)

### Environment
PhpStorm 2018.3 EAP
Build #PS-183.4284.100, built on November 14, 2018
PhpStorm EAP User
Expiration date: December 14, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**material_theme.xml**
```
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="upperCaseButtons" value="false" />
    <option name="settingsSelectedTab" value="1" />
    <option name="accentColor" value="80cbc4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="1acd2d71:163ebc0b880:-7fff" />
    <option name="version" value="3.0.0-pre1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Will be fixed on pre2. Thanks for the update
