### ISSUE TITLE
Radio Buttons visual bug

### ISSUE THREAD

**Issue by mohamadnorouzi20** [ChrisRM/material-theme-jetbrains#1051]
After changing the UI font family and font size the radio buttons wont be perfectly centered anymore. This issue has been there for a long time on different versions of windows, phpstorm and material theme but i was too lazy to report it.

Example:
![new bitmap image](https://user-images.githubusercontent.com/8435784/48914239-0b794b80-ee90-11e8-9c05-1f85fb71cecc.png)

* Windows v1809 build 17763.134
* PhpStorm 2018.3
* Material Theme 3.0.0-pre1

**Comment by mallowigi** [comment]
Won't fix
