### ISSUE TITLE
Active Tab background highlight in settings

### ISSUE THREAD

**Issue by sAs59** [ChrisRM/material-theme-jetbrains#1053]
Double clicking tabs in Settings -> Appearance & Behavior -> Material Theme -> Advanced
makes background white

![95102a07611c09daa9522a16227481fc](https://user-images.githubusercontent.com/9218560/48937456-3363c000-ef1f-11e8-9b67-5be837694160.gif)

Material Theme UI v3.0.0-pre2

WebStorm 2018.3
Build #WS-183.4284.130, built on November 19, 2018

JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

**Comment by mallowigi** [comment]
will be fixed in next version
