### ISSUE TITLE
Tab height cannot be applied

### ISSUE THREAD

**Issue by EivV** [ChrisRM/material-theme-jetbrains#1055]
### Summary

Tab height cannot be changed from the default (whatever it is).
![image](https://user-images.githubusercontent.com/45094143/49010123-fbf14f80-f17a-11e8-95dc-3921bd422b58.png)

### Expected behavior

Change the tab height to 24 px, see smaller tab height.

### Actual behavior

No change, regardless of the tab height.

### Environment

PyCharm 2018.3 (Professional Edition)
Build #PY-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-11-generic

Material Theme: v3.0.0-pre4

**Comment by mallowigi** [comment]
It still works, but you have to close all tabs for it to apply. 

There's no better implementation for now.
