### ISSUE TITLE
See #599 - Wrong tab background color for excluded directories (dark themes)

### ISSUE THREAD

**Issue by DrunkenPoney** [ChrisRM/material-theme-jetbrains#1056]
I have the exact same issue as described in #599 but the given link in this issue is dead.
It also does the same in the project files panel.

![2018-11-26 12_09_11-sct cig application c__dev_projets_sct cig application - _target_test-class](https://user-images.githubusercontent.com/14944216/49030013-2f7cab80-f174-11e8-8410-b454f7ab9ef4.png)

My actual theme is _Ocean Dark_ but anyway it doesn't solve my issue if I change the theme.

### Steps to reproduce
I have no idea. `¯\_(ツ)_/¯` <br/>
It just started doing this and I don't know what I did to produce it.

### Environment
IntelliJ IDEA 2018.3.1 EAP (Ultimate Edition)
Build #IU-183.4588.3, built on November 21, 2018
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
Material Theme UI v3.0.0-pre2

**Comment by mallowigi** [comment]
Have you tried reproducing the steps as written in the doc?
