### ISSUE TITLE
Compact Table Cells padding obscures Path Mappings

### ISSUE THREAD

**Issue by EivV** [ChrisRM/material-theme-jetbrains#1058]
### Summary
Enabling `Compact Table Cells` makes the text in `Path Mappings` invisible.

### Expected behavior
The text is visible.

### Actual behavior
Padding obscures the text.

### Steps to reproduce

1. Enable Compact Table Cells.
2. Go to a remote interpreter run configuration.
3. Open the `Edit Path Mappings` dialog.
4. Try to add a mapping.

No `Compact Table Cells`: 
![image](https://user-images.githubusercontent.com/45094143/49065191-ee44d400-f225-11e8-9596-b13c471d1975.png)

`Compact Table Cells` enabled:
![image](https://user-images.githubusercontent.com/45094143/49065206-f7ce3c00-f225-11e8-9662-55a59139dfb3.png)

### Environment
```
PyCharm 2018.3 (Professional Edition)
Build #PY-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-11-generic

Material Theme UI v3.0.0-pre4
```

Might be linked to #1057, where padding does not allow to reduce the tab height.

**Comment by mallowigi** [comment]
I know about this and there is nothing I can do unfortunately since the height is pretty much hardcoded. You can open a feature request to JetBrains though
