### ISSUE TITLE
Failing to initialize (Java ClassNotFoundException error)

### ISSUE THREAD

**Issue by MarketHubb** [ChrisRM/material-theme-jetbrains#106]
Originally tried to install on standard 9.02 build on Mac 10.10 with no luck. Updated the JRE to 1.8* and modified the Info.plist accordingly. Still no luck.

Finally opted to remove the application and re-download with the bundled JRE - and still no dice.

Any ideas why I'm having so much trouble?

<img width="1024" alt="screenshot 2015-10-31 19 01 28" src="https://cloud.githubusercontent.com/assets/5453922/10866390/67d9cdbe-8002-11e5-8637-c5633c32686a.png">

**Comment by ChrisRM** [comment]
I'm not sure to be honest. I'll see if I can replicate this behaviour using a different macbook at work tomorrow.

**Comment by cameronoxley** [comment]
Having the same issue

**Comment by cywen** [comment]
+1

**Comment by AlexZeitler** [comment]
Same here on Ubuntu 14.04 / WebStorm 10.0.4.
Works fine on OS X (Yosemite) / WebStorm 10.0.4 and another installation on Ubuntu 14.04 / WebStorm 10.0.4

If you need any details for investigation, let me know.

**Comment by AlexZeitler** [comment]
This also happens with WebStorm 11 on Windows 10 x64

**Comment by ChrisRM** [comment]
Maybe @denofevil could help shed some light on this issue, as I'm having a hard time reproducing it.

**Comment by denofevil** [comment]
Is there anything else on the message box (I see scrollbar there) or in the log files?

**Comment by AlexZeitler** [comment]
![materialthemeerrorosx](https://cloud.githubusercontent.com/assets/287480/10996225/80a13730-8483-11e5-903b-cd293ac4e72c.png)

**Comment by DmitryDorofeev** [comment]
+1

**Comment by AlexZeitler** [comment]
I'm not sure but did JetBrains always bundle the JRE with WebStorm?
Looks like old installations of WebStorm work fine but recent ones fail...

**Comment by DmitryDorofeev** [comment]
Works fine with WebStorm 10 without bundled jdk
Crashes with WebStorm 10 with bundled jdk

**Comment by AlexZeitler** [comment]
Workaround: https://github.com/ChrisRM/material-theme-jetbrains/issues/142#issuecomment-168303180
