### ISSUE TITLE
Environment Variables Inner Padding Obscures Content

### ISSUE THREAD

**Issue by nazrhyn** [ChrisRM/material-theme-jetbrains#1060]
### Summary
I'm not sure if this is present elsewhere, but in the Environment Variables editor for Run Configurations, while Compact mode is on, this happens:   
![peek 2018-11-27 17-21](https://user-images.githubusercontent.com/1672405/49115555-1b66a600-f269-11e8-8e23-dad8b6355a33.gif)

I have all of the Compact settings turned on:   
![image](https://user-images.githubusercontent.com/1672405/49115562-228db400-f269-11e8-966d-693191b6ac67.png)

It looks like the padding should also be removed in these cases, potentially? I'm not sure.

### Environment
WebStorm 2018.3
Build #WS-183.4284.130, built on November 19, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-39-generic
Plugin Version: v3.0.0-pre4

**Comment by mallowigi** [comment]
There's nothing i can do in here unfortunately

**Comment by mallowigi** [comment]
I'll try to take a look one day, if I found out that it's impossible i'll close again

**Comment by nazrhyn** [comment]
For reference, here's the same kind of GIF without Material enabled:   
![peek 2018-11-28 12-45](https://user-images.githubusercontent.com/1672405/49170991-79e46080-f30b-11e8-98c2-07a8a04c1d0e.gif)

**Comment by mallowigi** [comment]
will be fixed in next version
