### ISSUE TITLE
Text merges with background image on selected tab. One light 

### ISSUE THREAD

**Issue by Yerkon** [ChrisRM/material-theme-jetbrains#1064]
### Summary
Text merges with background image on selected tab. One light. Hight contrast  and contrast enabled
...

### Expected behavior
Text shouldn't merge with background color
...

### Actual behavior
Text merges with background image on selected tab. One light 
...

### Steps to reproduce (if needed)

1. Select Atom One light theme in Webstorm
2. Check High Contrast and contrast mode enabled
3. Look at 
![image](https://user-images.githubusercontent.com/4002847/49206238-a1a2f980-f3db-11e8-8a30-c42b479a902a.png)

You can also add Screenshots for a better understanding.

### Environment

WebStorm 2018.3
Windows 10 10.0

It should contain:

Material UI theme: v3.0.0-rc2
* Plugin configuration (found in material_theme.xml)

If possible please also give out your Material Theme/Material Custom Theme configuration file.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
Happens only on Lighter

**Comment by Yerkon** [comment]
Ho @mallowigi, why did you closed?

**Comment by mallowigi** [comment]
It's because it will be available in the next version

**Comment by Yerkon** [comment]
Great! Thanks 👍
