### ISSUE TITLE
Can you add darkula theme

### ISSUE THREAD

**Issue by urosjarc** [ChrisRM/material-theme-jetbrains#1065]
I really like JetBrains standard Darkula theme, but I like Material plugin because it adds a possibility to modify themes much more easily + all nice icons and other tweaks it adds on top of it.
It would be really cool if this plugin has standard "darkula + IntelliJ" theme so that user can tweak it...
Maybe this plugin then gets integrated in the standard jetBrains editors? Who knows :smiley: .

Does this make sens? :+1: :-1:

**Comment by urosjarc** [comment]
Well how dan I modify the built in appearence theme? Currently you can
modify only editor theme...

pet., 30. nov. 2018 10:25 je oseba Elior Boukhobza <notifications@github.com>
napisala:

**Comment by mallowigi** [comment]
There is a documentation website available, you will find all your answers there.
