### ISSUE TITLE
Custom color not persist after restart jetbrains(pycharm).

### ISSUE THREAD

**Issue by malinich** [ChrisRM/material-theme-jetbrains#1066]
### Summary
I choose  `solarized light` theme.  Set `contrast mode`.  Change color in `Material Custom Theme`. Reopen Pycharm. Color used like before. If I unset  `contrast mode` and immediately set  `contrast mode` again, then color return to my chose before.

![screen_settings](https://user-images.githubusercontent.com/2176614/49303071-d9906680-f4d9-11e8-9caa-0dcbf397c281.jpg)

after unset/set
 ![screen_settings_conrast_mode](https://user-images.githubusercontent.com/2176614/49303074-db5a2a00-f4d9-11e8-905e-052b8fd7e122.jpg)

### Expected behavior
open pycharm, custom color implimented 
...

### Actual behavior
open pycharm, used default color 
...

### Environment
PyCharm 2018.3 (Professional Edition)
Build #PY-183.4284.139, built on November 20, 2018
JRE: 1.8.0_152-release-1343-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-39-generic
[settings.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2634242/settings.zip)

**Comment by mallowigi** [comment]
To use the Custom Theme colors you must set the custom theme or custom light theme

**Comment by malinich** [comment]
Ah, You are right, but it not user-friendly to change one color for the theme. I need reset settings for a theme and define all colors

**Comment by mallowigi** [comment]
What do you mean?

**Comment by malinich** [comment]
after unset/set it's no impact on change 'black color". I close task
