### ISSUE TITLE
change background color of focused item in suggestions pop-up

### ISSUE THREAD

**Issue by shiftyshady** [ChrisRM/material-theme-jetbrains#1067]
![60xyc-6wrygfrv8mst_93q](https://user-images.githubusercontent.com/30387970/49338871-4281f680-f620-11e8-9ae6-ba69c6c5cca1.jpeg)
I would like to change the background color of the focused item in a suggestions pop-up window. 

I can't find the setting on: Settings/Appearance & Behaviour/Material Custom Theme
Editing Settings/Editor/Color Scheme/General->/Editor/Breadcrumbs/Current or Default or Hovered, did not make a change

Any help would be much appreciated.

**Comment by mallowigi** [comment]
This is the selection color.
