### ISSUE TITLE
downloading "browser repositories"

### ISSUE THREAD

**Issue by ArabCoders** [ChrisRM/material-theme-jetbrains#107]
Hi, 

Downloading the theme from "browser repositories" somehow trigger an update back to 0.1.16?
clicking on the theme name from the info windows forwards me to this [1] repo.

[1] https://github.com/equinusocio/material-theme

**Comment by ChrisRM** [comment]
Try to uninstall the plugin and install it again using "Browse repositories..."

**Comment by ChrisRM** [comment]
Btw, version 0.1.7 is waiting for approval, that's why it asks you to "update" down to 0.1.61 if you've installed it manually earlier
