### ISSUE TITLE
Typescript syntax highlighting doesn't match the color scheme preferences

### ISSUE THREAD

**Issue by sowelie** [ChrisRM/material-theme-jetbrains#1075]
### Summary
The syntax highlighting color isn't quite right after one of the latest updates. I thought maybe it was an issue with Intellij 2018.3, but after rolling back to 2018.2.7, it was still an issue.

Here is the color scheme window, which is how it is supposed to look:

![image](https://user-images.githubusercontent.com/2085036/49486297-d6fc7c80-f80b-11e8-9598-d7b4e82de375.png)

Now here is what I'm seeing when I actually open a typescript file:

![image](https://user-images.githubusercontent.com/2085036/49485587-8126d500-f809-11e8-97de-e68d77a0225a.png)

![image](https://user-images.githubusercontent.com/2085036/49485609-8c7a0080-f809-11e8-903a-5acbde368b49.png)

Notice the import, export and this keywords are the wrong colors.

### Environment

IntelliJ IDEA 2018.2.7 (Ultimate Edition)
Build #IU-182.5107.41, built on November 26, 2018
JRE: 1.8.0_152-release-1248-b22 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-12-generic

material_theme.xml:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.9.6.4" />
    <option name="selectedTheme" value="DARKER" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="userId" value="dd9b0c:1677c2c1012:-8000" />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

Material theme plugin version: 2.9.6.4 (also tried the 3.0.0.rc-4 version)

Thanks for the great work on this awesome plugin. It is the first plugin I install whenever I install Intellij now.

**Comment by mallowigi** [comment]
It’s a feature called Typescript additions. You can find it on Settings > Color Scheme > Typescript additions.

You can find more info in the documentation

**Comment by sowelie** [comment]
In case anyone else finds themselves here, the options for `export` and `this` were in the JavaScript Additions section of Color Scheme settings. The documentation link is here: https://www.material-theme.com/docs/configuration/color-scheme-additions/.
