### ISSUE TITLE
Deep ocean theme has a background issue in option list menus

### ISSUE THREAD

**Issue by gencer** [ChrisRM/material-theme-jetbrains#1076]
### Summary

Deep ocean theme has some issues on listviews

### Expected behavior

Flat as other themes

### Actual behavior

Broken background / hover color

### Steps to reproduce (if needed)

1. Choose Deep Ocean Theme and open settings.
2. Go to any settings that has three dot options menu.
3. Click on them and hover elements.

See here:

![image](https://user-images.githubusercontent.com/1711576/49520341-1c748480-f8b4-11e8-874d-9e2ee9e9981d.png)

### Environment
It should contain:
* OS: Windows
* IntelliJ Product + version RubyMine 2018.3
* Plugin version  (Latest available at the moment)

**Comment by mallowigi** [comment]
Yeah I saw that, it's happening on other themes too. Too lazy to search the cause of it.
