### ISSUE TITLE
Font size keep getting reverted to default value

### ISSUE THREAD

**Issue by ArabCoders** [ChrisRM/material-theme-jetbrains#108]
Hi

Using the default Material theme, and copying style and changing the font size somehow get lost once you reset the IDE.

**Comment by kporangehat** [comment]
I can confirm this is happening for me as well - PyCharm 5 CE. Even when playing with the font and font size in the settings, things seem to stop taking effect. Happy to provide any details requested to help diagnose.

**Comment by Luceos** [comment]
Appearance Font gets reset in phpstorm 10.0.1 after closing the app.

**Comment by beauchef** [comment]
Hummm... April 14th 2016 now, and it still does that.

**Comment by ChrisRM** [comment]
Sorry about that, I'll see if I can fix this later tonight.

**Comment by Luceos** [comment]
Was hoping this would have been fixed. Only thing from keeping me from using the theme :+1:

**Comment by thusfar7** [comment]
Anyone? Anything?

**Comment by rascafr** [comment]
I have the same problem (Kali Linux, last version of Android Studio). :(

**Comment by thusfar7** [comment]
Anyone? Anything?

**Comment by XiaominnHoo** [comment]
Is this issue fiexed?

**Comment by denofevil** [comment]
Duplicates #54
