### ISSUE TITLE
Unable to view flame chart 

### ISSUE THREAD

**Issue by cyb3rn3t1c1an** [ChrisRM/material-theme-jetbrains#1083]
Hello there!

### Expected behavior

Flame chart is visible ([source](https://blog.jetbrains.com/idea/2018/09/intellij-idea-2018-3-eap-git-submodules-jvm-profiler-macos-and-linux-and-more/))

![image](https://d3nmt5vlzunoa1.cloudfront.net/idea/files/2018/09/Profiler.png)

### Actual behavior

Flame chart is not visible (barely visible)

![image](https://user-images.githubusercontent.com/2145095/49735654-dbf07e80-fc98-11e8-906a-8c17212de078.png)

### Steps to reproduce

1. Install latest version of Intellij IDEA
2. Install theme plugin and choose dark theme
3. Press 2x shift and type "experimental features"
4. Enable "idea.profiler.enabled"
5. Try to run random code with profiler
6. Click on "CPU Profiler" tab

### Environment

* IntelliJ IDEA 2018.3.1 (Ultimate Edition)
* Build #IU-183.4588.61, built on December 4, 2018
* JRE: 1.8.0_152-release-1343-b16 amd64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Linux 4.18.16-100.fc27.x86_64
* Material Theme Plugin version 3.1.0

**Comment by mallowigi** [comment]
Thanks. I always wondered where is that flamechart property coming from

**Comment by mallowigi** [comment]
fixed
