### ISSUE TITLE
Sidebar font style and thickness seem a little out of place in 2018.3.1

### ISSUE THREAD

**Issue by cueo** [ChrisRM/material-theme-jetbrains#1086]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.

2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
Project tree font is slightly out of place and doesn't really fit in.
Expected
<img width="534" alt="Expected" src="https://user-images.githubusercontent.com/13873846/49817307-ddec3780-fd95-11e8-8f95-84e5ff038e62.png">

Actual
<img width="572" alt="Actual" src="https://user-images.githubusercontent.com/13873846/49817331-efcdda80-fd95-11e8-9c2a-c7211bcfc6f6.png">

### Environment

Mac OS
IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018

Material Theme v2.10.5

**Comment by mallowigi** [comment]
Did you enable material fonts?
