### ISSUE TITLE
Update Monokai Pro CLion

### ISSUE THREAD

**Issue by henryjetmundsen** [ChrisRM/material-theme-jetbrains#1088]
### Summary

The Monokai Pro theme in CLion has yet to be updated to the new colors said to be introduced in update 2.9.0. Other IDEs such as IntelliJ do have the updated colors.

From the screenshots below, you can see that CLion is still using the same colors that were seen in the Monokai Pro theme prior to the 2.9.0 update. This is happening on both MacOS Mojave as well as Ubuntu 18.04

### Screenshots

The first screenshot shows what CLion looks like

<img width="543" alt="screen shot 2018-12-12 at 3 58 02 pm" src="https://user-images.githubusercontent.com/32406734/49898427-053f1500-fe27-11e8-80a8-1805b30e2023.png">

This second screenshot is of IntelliJ

<img width="470" alt="screen shot 2018-12-12 at 3 59 14 pm" src="https://user-images.githubusercontent.com/32406734/49898429-07a16f00-fe27-11e8-932f-21a9ee535a99.png">

### Environment

CLion 2018.3.1
Build #CL-183.4588.63, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

I'm using Material theme v3.1.0

I haven't edited the configuration files in any way. I'm just using the default Monokai Pro configuration

**Comment by mallowigi** [comment]
fixed
