### ISSUE TITLE
CodePen logo used

### ISSUE THREAD

**Issue by brandonkelly** [ChrisRM/material-theme-jetbrains#1090]
Material Theme UI is using the copyrighted [CodePen](https://codepen.io) logo as its “Show editor and preview” icon when editing Markdown files.

<img width="190" alt="'Show editor and preview' icon" src="https://user-images.githubusercontent.com/47792/49948286-02383900-fea8-11e8-944f-bc7b8f123802.png">

(It should not.)

### Environment

Material Theme UI v3.1.0
PhpStorm 2018.3.1
Build #PS-183.4588.67, built on December 5, 2018
Licensed to Brandon D Kelly
Subscription is active until January 14, 2019
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

**Comment by mallowigi** [comment]
Icons from the material theme are from materialdesignicons.com which are opensource. As soon as I’m concerned they are okay to use, but if you insist I can consult a lawyer.

**Comment by mallowigi** [comment]
Well I'm using icons from this website https://materialdesignicons.com/tag/community, so I thought it would be fine. Are you sure about it ?

**Comment by mallowigi** [comment]
will be removed on next release
