### ISSUE TITLE
item height is too big

### ISSUE THREAD

**Issue by EyeMoney** [ChrisRM/material-theme-jetbrains#1092]
excuse me, 
win10 - 1809
.IntelliJIdea2018.3

My computer is a laptop, but in this theme, the mouse menu item is so high that when I right-click it, the screen is filled with menu items.

![image](https://user-images.githubusercontent.com/38517192/50098579-2e143f80-0257-11e9-8e28-dfb98df21053.png)
![image](https://user-images.githubusercontent.com/38517192/50098607-39676b00-0257-11e9-9a17-91e085f8a71d.png)

I can't find where to change it. 

Please help me

**Comment by mallowigi** [comment]
You can find everything you want in the documentation.

**Comment by emesterhazy** [comment]
@s8cm Did you ever find a solution to this? I am having the same issue and couldn't find anything useful in the documentation. Maybe I'm searching for the wrong thing, but "right click" and "context menu" turned up nothing.

**Comment by emesterhazy** [comment]
For anyone else looking, I finally found this setting after trial and error. I didn't see it anywhere in the documentation, but its possible I searched the wrong thing... "right click" and "context menu" turned up nothing.

**Material Theme > Compact > Compact Menus**

**Comment by liyangzbx** [comment]
> For anyone else looking, I finally found this setting after trial and error. I didn't see it anywhere in the documentation, but its possible I searched the wrong thing... "right click" and "context menu" turned up nothing.
> 
> **Material Theme > Compact > Compact Menus**

thanks！

**Comment by Jaggle** [comment]
@emesterhazy thank you so much!
