### ISSUE TITLE
Support for CLion 2018.3.2

### ISSUE THREAD

**Issue by pha3l** [ChrisRM/material-theme-jetbrains#1093]
### Summary

I looked through the issues and didn't see anything regarding this, I apologize if it's in there somewhere.

I'm seeing that after updating CLion to 2018.3 I'm no longer able to use the plugin.  I get a message saying that it's "incompatible with the current CLion version."

I found this odd because it seems to work beautifully with the new versions of Rider and IntelliJ which i also use daily.  Please let me know if you require any additional information.  Thanks for a plugin that makes the apps I stare at day in and day out much more visually appealing!

**Comment by mallowigi** [comment]
I just checked in CLion 3.2 with no issues. Did you try from the repository ?

**Comment by pha3l** [comment]
Yep, installed by adding the repo, worked a charm.  Thank you!
