### ISSUE TITLE
one dark theme doesn't changes colors

### ISSUE THREAD

**Issue by Dovhakin86** [ChrisRM/material-theme-jetbrains#1094]
Im new to Java and I'm trying to get inteliJ look like atom one dark theme, it changes some of the aspects but most of them stay white.

![image](https://user-images.githubusercontent.com/46194903/50482536-baf59080-09ef-11e9-9a73-6ac231fea518.png)

**Comment by mallowigi** [comment]
Make sure you’re not in power save mode
