### ISSUE TITLE
Package icon displayed as regular folder

### ISSUE THREAD

**Issue by kaspersoerensen** [ChrisRM/material-theme-jetbrains#1095]
### Summary
When using the theme for intelliJ the package icon in the tree view of the project, does not appear as a package, but as a folder, when adding files to the package.

### Expected behavior
Showing the package icon

### Actual behavior
Showing regular folder icon

### Steps to reproduce

1. Create a new project (I use Gradle) in intelliJ. Type in artifact and group id. 
2. Once initialized, create a package in the ``src/main/java`` folder.
3. The package should apper with the correct icon.
4. Add a .java file to the folder, the icon now changes to be a regular folder icon.

![sd_1](https://user-images.githubusercontent.com/2018894/50549513-73c10700-0c5e-11e9-9ff4-1adf9ea8a856.png)

![sd_2](https://user-images.githubusercontent.com/2018894/50549548-1bd6d000-0c5f-11e9-9741-689335dd8cb3.gif)

Am I missing something? 

### Environment

macOS 10.13.6

IntelliJ IDEA 2018.3.2 (Community Edition)
Build #IC-183.4886.37, built on December 17, 2018
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Material Theme Plugin version v3.3.0

**Comment by mallowigi** [comment]
It’s a known bug, thank you for reminding me to fix it. In the meanwhile you can revert to the original behavior by disabling the “Project View Decorators” setting

**Comment by kaspersoerensen** [comment]
Okay - sorry that I did not find this in the closed issue.
Disabling the setting fixed :-)
