### ISSUE TITLE
Uncustomizable features

### ISSUE THREAD

**Issue by Bilge** [ChrisRM/material-theme-jetbrains#1097]
I just started using Material Theme, and overall I like it, but there seem to be a few UI elements that exhibit regressive or otherwise undesirable behaviour that cannot(?) be customized.

1. Editor tab text becomes dimmed for the selected tab. I don't know why this is necessary, since the selected tab already receives the accent colour underline, making it fairly clear which tab is selected, but I notice it also always dims the text, which not only makes the text illegible for some tab colours but also seems counter-intuitive, since one generally expects selected text to be lighter, not darker. In any case, this seems to be a hard-coded behaviour that cannot be changed. If so, it should be configurable.
![image](https://user-images.githubusercontent.com/470626/50683096-cf95e200-1008-11e9-9286-90235f99e7a1.png)

2. Selected configuration name in the toolbar is forced into block capitals, despite almost no other UI elements being forced into block capitals. This makes it stand out unnecessarily and is also harmful because it means one cannot see the real capitalization of the configuration name without expanding the configuration drop-down, particularly if it is based on the name of a file, as is usually the case. That is, it makes it look like the file may have been misnamed in block capitals when, in fact, this is just a UI quirk which also appears to be non-customizable.
![image](https://user-images.githubusercontent.com/470626/50683151-f6ecaf00-1008-11e9-9cef-08dd68c91c2a.png)

3. In the structure window (Alt+7) there is an option to show inherited members. Normally such inherited members are shown in a different (darker) colour to indicate they are inherited and not implemented directly in the current class. However, with Material Theme, all members are displayed in the same colour and this also does not appear to be customizable.
![image](https://user-images.githubusercontent.com/470626/50683306-872af400-1009-11e9-9a42-972d3f1d5971.png)

**Comment by Bilge** [comment]
@mallowigi You missed the point on 1. I'm well aware files outside the project have a different background colour and this is good and correct and not part of the issue description at all. I just happened to picture a tab that's outside the project in the sceenshot. The issue is that the text becomes dimmed when selected. The background colour is not at all relevant whatsoever because the text dimming behaviour is exhibited by _all_ tabs regardless of their disposition.

**Comment by mallowigi** [comment]
Can you provide more information about your environment?

**Comment by Bilge** [comment]
I am using PhpStorm 2018.3 on Ubuntu 18.04.

**Comment by mallowigi** [comment]
Hi, sorry for not getting back

I've fixed the 3. it will be available next release. As for the first point I wasn't able to reproduce it. Can you provide more information about your environment ?

**Comment by Bilge** [comment]
@mallowigi I really don't think #3 is fixed at all. All entries are still coloured the same for me.

**Comment by mallowigi** [comment]
fixed in 4.2
