### ISSUE TITLE
Feature/Info request: indentation

### ISSUE THREAD

**Issue by gamort** [ChrisRM/material-theme-jetbrains#1099]
There is one feature of this plugin I really love, the ability to set custom indentation for the project view on the left.    

The default indentation is really cruddy with heavily nested directories.

However, that is the only feature I  find myself desperately wanting.   The changes to the buttons, spacing, and layout just don't appeal to me.   Their extremely well implemented, but I'm not a fan of Material UI.

Any chance you can point me to the code being used for the indentation?  I'm willing to put some work in to try to rip it out  so I am only using that single feature.

**Comment by mallowigi** [comment]
If you only need the custom indentation, you can try to create a plugin applying the change to the sidebar.

The only thing you need to do is to override the `Tree.leftSideIndent` property using `UIManager.set` at the start of your plugin.

For more information about creating a plugin, I invite you to refer to the Material Theme documentation and IntelliJ SDK documentation.
