### ISSUE TITLE
Items in auto complete list have different heights with the newest update

### ISSUE THREAD

**Issue by ChristianIvicevic** [ChrisRM/material-theme-jetbrains#1103]
### Summary

The auto complete list that can be triggered using Ctrl+Space will have different sizes depending on the context. In my particular case when editing a TypeScript file, it has bigger items when auto completing object members compared to general auto completion in a function scope-

### Expected behavior

All items should have the same height.

### Actual behavior

The auto complete lists have different height.

### Screenshots

![screenshot 2019-01-17 at 09 00 10](https://user-images.githubusercontent.com/45569997/51303927-1e933c80-1a37-11e9-8929-5eb9bf3bca6a.png)
![screenshot 2019-01-17 at 09 00 27](https://user-images.githubusercontent.com/45569997/51303932-205d0000-1a37-11e9-8d19-1639c6108ddc.png)

### Environment

IntelliJ IDEA 2018.3.3 (Ultimate Edition)
Build #IU-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

Material Theme Plugin Version 3.4.0

**Comment by mallowigi** [comment]
Seems like the icon sizes are not consistent. I'll check

**Comment by mallowigi** [comment]
should be fixed
