### ISSUE TITLE
Enhancement Request: Tab Highlight based on user specified Directory Color 

### ISSUE THREAD

**Issue by srsholmes** [ChrisRM/material-theme-jetbrains#1105]
Hello, thanks so much for your work on this plugin, it really is fantastic!

I have a use case for active tab highlights to be configured on a per folder basis.

I think it would be useful to be able to mark folders as a specific color, which is reflected in their tab highlight. This would enable developers to quickly see that the files they are editing are located in a specific folder, without having to look at the Navigation bar to see their path.

This would be especially useful when working with mono-repos containing both backend and frontend code. It would also be useful when navigating files which have the same name (e.g. index.js), to be able to quickly see if you currently editing backend or frontend code.

I have attached a quick mockup of what I think the solution could look like:

![plugin-mockup](https://user-images.githubusercontent.com/3579905/51337597-6e95f180-1a7f-11e9-918f-d954f698557b.jpg)

There is a similar issue currently raised for vscode here:
https://github.com/Microsoft/vscode/issues/31308

**Comment by mallowigi** [comment]
Awesome request! Note that you can already do that with the ide independently of the plugin through the file colors feature, but they apply to the tab background instead. 

I can make use of the api of that feature to color the active tab according to the file color, otherwise it would complicate things greatly. So theoretically you can define file colors in the settings (I can create a menu for that I think) but disable the “background coloring feature” (or use the “Tab Opacity setting” to set it to 0) to let the highlight only.

**Comment by srsholmes** [comment]
I had no idea that functionality was built in, so thanks for letting me know. I guess the fact it's hidden away inside the preferences means people might miss it.

It would be quite nice if the color could be applied to the tab highlight rather than the background, as it would look nicer / more minimal.  

I'll leave it up to you as to whether or not you think it would be a good addition to the plugin, given the functionality already exists in the IDE. Unfortunately I have little to no knowledge of Java / developing IntelliJ plugins, I am not the best person to help work on the feature. 

Thanks for getting back to me, and keep up the great work on the plugin!

**Comment by ERROPiX** [comment]
Hi @mallowigi ,

I had an issue when I was changing options in "Material File Colors" no matter what I use, it doesn't change some folders like "tests" and "node_modules".

then I come here and seen your tip about builtin file colors!!! it saved my day 👍

Thank you

**Comment by oreporan** [comment]
I've built a vscode extension that does exactly this (and a bit more)
Built for people who have monorepos or large projects and want to navigate more easily.

its called ColorTabs

Marketplace:
https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext

Repo:
https://github.com/oreporan/color-tabs-vscode/

**Comment by ERROPiX** [comment]
@oreporan this extension is for Jetbrain PHP Storm not VS Code

**Comment by mallowigi** [comment]
This is awesome! Thanks for the info

--
Elior

**Comment by mallowigi** [comment]
Finally closing this, I've decided it would conflict too much with the current options - accent color, accent mode, custom highlight color, override accent from theme... it would become too painful to handle.
