### ISSUE TITLE
Enhancement Request: White font and yellow background in console for Darker Theme.

### ISSUE THREAD

**Issue by CNBroderick** [ChrisRM/material-theme-jetbrains#1107]
# Hello, material theme teams:

  _Thank you for bringing us such a beautiful theme._ But, i have a problem in there:

# Summary
  Can't see warning line clearly when console print. Because **white font and yellow background** in console for Darker Theme.

# Actual behavior

![image](https://user-images.githubusercontent.com/27131135/51523019-a331f080-1e65-11e9-81df-621b12f6ea06.png)

**Only can see it if selected:**

![image](https://user-images.githubusercontent.com/27131135/51523108-e42a0500-1e65-11e9-81ed-fed58fcd35db.png)

# Steps to reproduce 

1. Select _**darker theme**_
2. Print a warning line in console.

![image](https://user-images.githubusercontent.com/27131135/51523267-4551d880-1e66-11e9-8063-8ed5dc05ec5e.png)

# Environment

_**Material theme version :** 3.3.0_

_**IDEA version:**_

> IntelliJ IDEA 2018.3.3 (Ultimate Edition)

> build #IU-183.5153.38, on January 9, 2019

> JRE: 1.8.0_152-release-1343-b26 amd64

# Wanna 

So, can there have a option in IDEA settings for change warning background or font color?

[Email: z@bkLab.org](mailto:z@bkLab.org)

**Comment by mallowigi** [comment]
Don't know how to reproduce this. Do you have an example project that i can run and see for myself?

**Comment by etshy** [comment]
I have a lot of these with composer and symfony command.

For exemple, when I run `composer init` on a brand new project, I get this
![](https://i.imgur.com/AK0tOBf.png)

For console colors,  I have the "Material Darker" scheme, I didn't modify it (I don't see any use of bg color there so I didn't change anything).

Same command in CMD
![](https://i.imgur.com/LkJxlq8.png)
and in PowerShell
![](https://i.imgur.com/HS23aHh.png)

The "Material Solarized Dark" them change this blue background and gray font colors so I guess it's possible to configure it (or for you to fix this ?)
For exemple: 
![not the same blue](https://i.imgur.com/QXJZOJN.png)

Most of the Material theme don't change the blue background color though.


As I said, it's a brand new project, with an unmodified color scheme.
