### ISSUE TITLE
No available version for 2019.1

### ISSUE THREAD

**Issue by Hunternnm** [ChrisRM/material-theme-jetbrains#1109]
### Summary
After update PhpStorm to 2019.1 eap plugin update to v1.3.0-173.3622. After update plugin phpstorm too long start and crash after load(too many errors)

### Steps to reproduce (if needed)

1. Update phpstorm to 2019.1 eap
2. Update plugin
3. See result

![default](https://user-images.githubusercontent.com/5153607/51627491-f0d45900-1f4a-11e9-827f-1df7a1700a0b.png)

### Environment
Ubuntu 18.10 Gnome

**Comment by mallowigi** [comment]
You can’t use plugin version 1.3.0 for 2019.1

Download the latest version

**Comment by Hunternnm** [comment]
@mallowigi, you did not understand me a little. When installing, it updates itself to this very old version, and the new one does not allow installing
![default](https://user-images.githubusercontent.com/5153607/51660831-9c1af780-1fb7-11e9-9a3a-5d102b306afd.png)
v3.4.1.1

**Comment by K900** [comment]
I've just tried rebuilding the plugin with max compatible version set to 191.*, and it worked just fine on PyCharm 2019.1.

**Comment by mallowigi** [comment]
New version is up. It will be available shortly

**Comment by sktdan** [comment]
Unable to install on Android studio 3.5 Canary 3 build.

Android studio Plugins store still shows 3.5 as the latest version, which does not set the color scheme
