### ISSUE TITLE
Addition: Identifier under caret - Error Stripe Mark 

### ISSUE THREAD

**Issue by thanos-irodotou** [ChrisRM/material-theme-jetbrains#111]
It'd be nice if you could add this.
It's hard to tell when the caret is on a variable/method/etc where that variable/method is used elsewhere in the file.
Setting this will provide useful markers on the right hand sidebar.

**Comment by jonnywilliamson** [comment]
Just about to leave a new issue for this until I saw this.

Here's an example. Say I'm using another theme - in this case a Monokai one. I put my cursor on a variable and the IDE shows me in the side bar where else that variable is in use throughout the file:

![image](https://cloud.githubusercontent.com/assets/2513663/11269860/f6627a78-8eb1-11e5-8b54-a4cae81f80b8.png)



Now if I switch to material theme these hints disappear:

![image](https://cloud.githubusercontent.com/assets/2513663/11269867/0c8d1b82-8eb2-11e5-981c-31e8014b28d9.png)


How can I get them back?

**Comment by thanos-irodotou** [comment]
Yeah, I had to manually edit colours to add a clear colour for the Error Stripe Mark Section.
You can do this by going to Settings>Editor>Colors & Fonts>General and selecting the `Identifier under caret`, then on the small top right you can tick `Error stripe mark` and set a colour to it. Idea's default is this green I think `036B13`, that's what I'm using at least.
Hope that helps.

**Comment by jonnywilliamson** [comment]
@thanos-irodotou That's exactly what I was looking for.

I had been through every single colour item but didn't realise I needed to select the `error strip mark` checkbox.

Working as I want now! Really appreciate that.

**Comment by thanos-irodotou** [comment]
Yeah they're pretty bad at naming things :smile: , glad that worked out for you.
Hopefully it'll be added in the material ui's schemes soon :smile: .
