### ISSUE TITLE
The plugin pollutes the logs

### ISSUE THREAD

**Issue by zolotov** [ChrisRM/material-theme-jetbrains#1110]
It's quite hard to read logs when the plugin is installed. Please got rid of the them or change their severity to a DEBUG or even TRACE.

![image](https://user-images.githubusercontent.com/140920/51671263-97673b00-1fd9-11e9-878c-f3ad646da2c6.png)

**Comment by mallowigi** [comment]
I’ve already fixed that it will be available in the next release
