### ISSUE TITLE
Why can't I see the navigation arrow on the left? What I use is material lighter theme.

### ISSUE THREAD

**Issue by zhangguan123** [ChrisRM/material-theme-jetbrains#1111]
<img width="288" alt="wx20190124-212750 2x" src="https://user-images.githubusercontent.com/13409949/51681300-2185c280-201f-11e9-8f2a-45ef74583d66.png">
<img width="185" alt="wx20190124-212822 2x" src="https://user-images.githubusercontent.com/13409949/51681313-264a7680-201f-11e9-9e4e-144ddad7fda6.png">
<img width="351" alt="wx20190124-213057 2x" src="https://user-images.githubusercontent.com/13409949/51681373-5e51b980-201f-11e9-84a0-60642d90b388.png">

**Comment by mallowigi** [comment]
Which version of the plugin do you use? Which IDE ? Which OS ?

**Comment by mallowigi** [comment]
Also it looks like you’ve disabled the Material components. While it shouldn’t affect the appearance of the arrows, tell me if your issue is working with the material components enabled

**Comment by zhangguan123** [comment]
No,I didn't.What I use is 3.4.4.1 and macOS Mojave 10.14 and IntelliJ IDEA 2018.2 Ultimate Edition

**Comment by zhangguan123** [comment]
No problem with black,White is problematic.
<img width="93" alt="wx20190124-223213 2x" src="https://user-images.githubusercontent.com/13409949/51684873-079cad80-2028-11e9-8565-39bf346f2773.png">
<img width="298" alt="wx20190124-223229 2x" src="https://user-images.githubusercontent.com/13409949/51684888-0ff4e880-2028-11e9-92a9-d2443dae0138.png">

**Comment by mallowigi** [comment]
Check in Settings > Material Theme > Features tab

**Comment by zhangguan123** [comment]
thank you.

**Comment by mallowigi** [comment]
Please change your rating.
