### ISSUE TITLE
Active component color is not configurable

### ISSUE THREAD

**Issue by IceSentry** [ChrisRM/material-theme-jetbrains#1112]
### Summary

The website mentions the option to change the color for active components. The setting is not available in the list of custom theme colors

### Expected behavior

Possibility to change the active component color

### Actual behavior

The active component color cannot be changed from the custom theme color menu

### Steps to reproduce (if needed)

![image](https://user-images.githubusercontent.com/8348954/51700280-b5826a80-1fdc-11e9-9b45-63a14890be41.png)

As you can see in my screenshot, the option is not there and the OK button uses a color that I cannot configure.

### Environment

IntelliJ IDEA 2018.3.3 (Community Edition)
Build #IC-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version: v3.4.1.1

material_theme.xml
`
<application>
  <component name="MaterialThemeConfig">
    <option name="accentScrollbars" value="false" />
    <option name="compactSidebar" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="isStyledDirectories" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="statusBarTheme" value="false" />
    <option name="themedScrollbars" value="false" />
    <option name="upperCaseButtons" value="false" />
    <option name="useMaterialIcons" value="false" />
    <option name="customSidebarHeight" value="20" />
    <option name="tabOpacity" value="100" />
    <option name="highlightThickness" value="3" />
    <option name="indicatorThickness" value="1" />
    <option name="leftTreeIndent" value="8" />
    <option name="rightTreeIndent" value="8" />
    <option name="settingsSelectedTab" value="6" />
    <option name="accentColor" value="0e639c" />
    <option name="highlightColor" value="4acc4d" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="2b4f85c7:16861fe890c:-8000" />
    <option name="version" value="3.4.1.1" />
    <option name="tabHighlightPosition" value="Top" />
  </component>
</application>
`

**Comment by mallowigi** [comment]
Well it's just a problem in wording, since the "activeComponent" color refers to a bunch of different stuff not necessarily related to each other (like selection text and primary button for example), it was hard to find the right title (in the beginning it was named "Misc")

Long story short, the option to configure the primary button is the "Selected Text color"

**Comment by mallowigi** [comment]
This doc may be outdated, but it can be of use: http://www.material-theme.com/docs/configuration/custom-themes/

**Comment by IceSentry** [comment]
Yes, I was reffering to that page actually. That's where I saw the entry for active component color in the screenshot, but couldn't find it in the plugin settings.
