### ISSUE TITLE
Project view tab height

### ISSUE THREAD

**Issue by Echolz** [ChrisRM/material-theme-jetbrains#1115]
1. I want to make the project view tabs height smaller than 18 because it is still too much for me, but the option does not go lower than 18. I tried to find some configuration xml file but could not.

2. It would be great feature if you could choose the font size and style for the project view only.

<img width="163" alt="screenshot 2019-01-25 at 10 03 22" src="https://user-images.githubusercontent.com/16500246/51732945-8b868200-2088-11e9-9912-aef1888c2fee.png">

<img width="863" alt="screenshot 2019-01-25 at 10 06 23" src="https://user-images.githubusercontent.com/16500246/51733111-fd5ecb80-2088-11e9-9db0-9516797a2758.png">

* GoLand 2018.3.2
* OS  Mac
* config - https://pastebin.com/iP0ujYFa

**Comment by mallowigi** [comment]
There’s no way without completely refactoring the project and I don’t plan to do that at the moment. As for the first point I don’t think a height smaller than 18 would look good, as the icon is minimum 16 px and you have to take into consideration the active tab highlighter which is at most 5px

**Comment by mallowigi** [comment]
will be available on ne
