### ISSUE TITLE
Current branch commits are not highlighted

### ISSUE THREAD

**Issue by renataogarcia** [ChrisRM/material-theme-jetbrains#1117]
### Summary

Current branch commits are not highlighted

### Expected behavior

The commits that are in the current branch should appear in a different color than the other commits when the "Presentation Settings -> Highlight -> Current Branch" is enabled in the VCS Log view.

### Actual behavior

All commits have the same background color

### Steps to reproduce (if needed)

1. Switch to VCS log view
2. Enable the "Current Branch" in the "Presentation Settings" menu on the Log toolbar.

### Environment

IntelliJ IDEA 2018.3.3 (Ultimate Edition)
Build #IU-183.5153.38, built on January 10, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.20.5-arch1-1-ARCH

material_theme.xml
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="fileIcons" value="false" />
    <option name="isContrastMode" value="true" />
    <option name="isDecoratedFolders" value="false" />
    <option name="isTabsShadow" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="statusBarTheme" value="false" />
    <option name="useMaterialIcons" value="false" />
    <option name="settingsSelectedTab" value="4" />
    <option name="accentColor" value="5a98cd" />
    <option name="selectedTheme" value="LIGHT_CUSTOM" />
    <option name="userId" value="-2a470839:167a059aefe:-8000" />
    <option name="version" value="3.5.0" />
  </component>
</application>
```

**Comment by renataogarcia** [comment]
Possibly because both "List.background" and "VersionControl.Log.Commit.currentBranchBackground" are using Secondary Background color here? https://github.com/ChrisRM/material-theme-jetbrains/blob/cdffe5a353d1b1d35efeeda5ee4580ecb58a976c/src/main/java/com/chrisrm/idea/themes/themes/MTAbstractTheme.java#L677-L704

**Comment by semioniy** [comment]
Why is this issue closed? Current branch is still highlighted with the same color as all other branches. On both light and darcula themes. Changing any colors in Editor-Color Scheme-VCS doesn't gain any effect.
