### ISSUE TITLE
Pycharm XStream vulnerablity 

### ISSUE THREAD

**Issue by ktavabi** [ChrisRM/material-theme-jetbrains#1118]
### Summary

UI plugin generates PyCharm IDE security error upon starting.

### Expected behavior

Executing IDE with Materials UI enabled and no security warning/error

### Actual behavior

> javassist.NotFoundException: com.intellij.ui.components.ScrollBarPainter$Thumb
> 	at javassist.ClassPool.get(ClassPool.java:452)
> 	at com.chrisrm.idea.MTHackComponent.hackScrollbars(MTHackComponent.java:99)
> 	at com.chrisrm.idea.MTHackComponent.<clinit>(MTHackComponent.java:53)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl.registerComponents(ComponentManagerImpl.java:371)
> 	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:81)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
> 	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:208)
> 	at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:74)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:342)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Security framework of XStream not initialized, XStream is probably vulnerable.
> Security framework of XStream not initialized, XStream is probably vulnerable.
> 
### Steps to reproduce (if needed)

1. Rename `.Pycharm` config folder
2. Start IDE 

### Environment

> PyCharm 2018.3.3 (Professional Edition)
> Build #PY-183.5153.39, built on January 9, 2019
> JRE: 1.8.0_152-release-1343-b26 amd64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Linux 4.15.0-44-generic
> Material UI v 3.5

With plugin Config...

> component name="MaterialThemeConfig"
> option name="isHighContrast" value="true"
> option name="isWizardShown" value="true"
> option name="overrideAccentColor" value="true"
> option name="userId" value="5134c5a:1689affaefa:-8000"
> option name="version" value="3.5.0"
>

**Comment by mallowigi** [comment]
should be fixed in hotfix

**Comment by ktavabi** [comment]
Actually `v3.5.0.1` just throws...

> Combined highlighters: 3633, 3649
> Security framework of XStream not initialized, XStream is probably vulnerable.
> Security framework of XStream not initialized, XStream is probably vulnerable.
>

**Comment by mallowigi** [comment]
It’s just a warning, it doesn’t prevent you of using the ide, is it? The scroll bar error was the reason of the hotfix.

If you see an erroneous behavior tell me but as far as I tested, it should be working.
