### ISSUE TITLE
Button overlay each other

### ISSUE THREAD

**Issue by khalilayache** [ChrisRM/material-theme-jetbrains#1119]
### Summary
When I used Material Darker or any other "Dark" themes  that came with plugin, the buttons overlay each other and in some cases dont appear on window...

### Actual behavior

<img width="1000" alt="screen shot 2019-01-31 at 17 05 36" src="https://user-images.githubusercontent.com/15621468/52081611-c9e8d900-2581-11e9-8aa2-3cc39a7b4fdb.png">

<img width="1150" alt="screen shot 2019-01-31 at 17 58 52" src="https://user-images.githubusercontent.com/15621468/52081674-fbfa3b00-2581-11e9-887b-65a601f59deb.png">

### Expectate behavior

<img width="1011" alt="screen shot 2019-01-31 at 18 58 01" src="https://user-images.githubusercontent.com/15621468/52084903-47184c00-258a-11e9-8419-e7ade4af320f.png">

### Steps to reproduce (if needed)

1. First step
Change the theme to Material Darker or any Dark theme
2. Second step
Close the Preference Window
3. Third step
Open Preference Window again

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos to the clipboard and paste it here.

Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

It should contain:
* If needed a list of enabled plugins: 
.ignore (2.6.2)
ADB Idea (1.5.3)
Android APK Support (1.0)
Android DPI Calculator (1.2)
Android Games (1.0)
Android NDK Support (1.0)
App Links Assistant (0.1)
CodeGlance (1.5.4)
Copyright (8.1)
Coverage (182.5107.16.33.5199772)
CVS Integration (11)
EditorConfig (182.5107.16.33.5199772)
Firebase App Indexing (0.1)
Firebase Services (0.1)
Firebase Testing (1.0)
Git Integration (8.1)
GitHub (182.5107.16.33.5199772)
Google Cloud Tools Core (0.2.8)
Google Cloud Tools For Android Studio (0.2.8)
Google Developers Samples (0.3.1)
Google Login (1.0)
Google Services (0.1)
Gradle (182.5107.16.33.5199772)
Groovy (9.0)
I18n for Java (182.5107.16.33.5199772)
IntelliLang (8.0)
Java Bytecode Decompiler (182.5107.16.33.5199772)
Java Stream Debugger (182.5107.16.33.5199772)
JUnit (1.0)
Key Promoter X (2019.1.1)
Kotlin (1.3.11-release-Studio3.3-2)
Markdown support (182.4892.20)
Material Theme UI (2.9.6.4)
Mercurial Integration (10.0)
Properties Support (182.5107.16.33.5199772)
Settings Repository (182.5107.16.33.5199772)
Smali Support (1.0)
Subversion Integration (1.1)
Task Management (1.0)
Terminal (0.1)
Test Recorder (1.0)
TestNG-J (8.0)
YAML (182.5107.16.33.5199772)

**Comment by mallowigi** [comment]
Please enable material components in settings > features

**Comment by Abgaryan** [comment]
@mallowigi I have the same issue on OSX, how can I fix it?
