### ISSUE TITLE
Incorrect accent colour of the selected item in a "Project View".

### ISSUE THREAD

**Issue by tmikus** [ChrisRM/material-theme-jetbrains#1124]
### Summary

Hi, I seem to have noticed that in the latest version (including the code on "master" branch) of the project the accent colour of a selected item in a "Project View" panel is not the same as the accent colour  set in the IDE.

Screenshot from IntelliJ Build #IU-183.5429.30

![before](https://user-images.githubusercontent.com/744210/52372908-3ddb2380-2a51-11e9-9928-9826847c0b0c.jpg)

It seems like the accent line is being rendered below the item highlight colour, and to test that I tried to change that in `src\main\java\com\chrisrm\idea\ui\MTTreeUI.java` in `paintRow` function and I got this:

![after](https://user-images.githubusercontent.com/744210/52373050-aa562280-2a51-11e9-8a58-a29452395159.jpg)

The code I used to achieve this was:

```java=
@Override
  protected void paintRow(final Graphics g,
                          final Rectangle clipBounds,
                          final Insets insets,
                          final Rectangle bounds,
                          final TreePath path,
                          final int row,
                          final boolean isExpanded,
                          final boolean hasBeenExpanded,
                          final boolean isLeaf) {
    final int containerWidth = tree.getParent() instanceof JViewport ? tree.getParent().getWidth() : tree.getWidth();
    final int xOffset = tree.getParent() instanceof JViewport ? ((JViewport) tree.getParent()).getViewPosition().x : 0;

    if (path != null) {
      final boolean selected = tree.isPathSelected(path);
      final Graphics2D rowGraphics = (Graphics2D) g.create();
      rowGraphics.setClip(clipBounds);
      if (selected) {
        final Color bg = getSelectionBackgroundColor(tree, true);
        rowGraphics.setColor(bg);
        rowGraphics.fillRect(xOffset, bounds.y, containerWidth, bounds.height);
      }
      super.paintRow(rowGraphics, clipBounds, insets, bounds, path, row, isExpanded, hasBeenExpanded, isLeaf);
      if (selected) {
        if (tree.hasFocus()) {
          LIST_FOCUSED_PAINTER.paintBorder(tree, rowGraphics, xOffset, bounds.y, containerWidth, bounds.height);
        } else {
          LIST_PAINTER.paintBorder(tree, rowGraphics, xOffset, bounds.y, containerWidth, bounds.height);
        }
      }
      rowGraphics.dispose();
    } else {
      super.paintRow(g, clipBounds, insets, bounds, null, row, isExpanded, hasBeenExpanded, isLeaf);
    }
  }
```

I could raise this as a Pull Request, but I'm not sure this is a correct fix.

### Environment

IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
Licensed to Tomasz Mikus
Subscription is active until November 3, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
It’s something that changed on 2018.3? Odd... I’ll take a look

**Comment by tmikus** [comment]
@mallowigi Sorry, I'm not sure when that changed, but I'm sure there was a moment this worked fine ;)

**Comment by mallowigi** [comment]
I'm not sure what I need to see here...

**Comment by tmikus** [comment]
Sorry, it’s a very subtle difference - take a look at a left border of the “folder_associations.xml”.

When I use the plugin from the jetbrains that border colour is washed out, and doing the change I described makes it stand out more.
