### ISSUE TITLE
Feature request: clone current settings

### ISSUE THREAD

**Issue by andyalbert** [ChrisRM/material-theme-jetbrains#1126]
I think adding an option to clone/copy the current settings (selected theme, colors, bar sizes, everything) will be great, I use the theme on many devices and I failed to make them like the one I managed to achieve on one device, It's hard to go through all the settings to copy one by one, I think it will also be useful in case of system failure when someone want to restore the previous settings by one click.

**Comment by mallowigi** [comment]
You can use the export settings feature provided by jetbrains though

**Comment by andyalbert** [comment]
Oops, I didn't see this feature before, I'll try it and see if it work as expected.
Thanks for the fast reply 👍
