### ISSUE TITLE
VSCode material theme ocean high contrast

### ISSUE THREAD

**Issue by zengjice** [ChrisRM/material-theme-jetbrains#1128]
### Summary

Can you add theme like material theme ocean high contrast for VSCode?

Thanks.

### Expected behavior
![](https://www.vscolors.com/img/1280/693e0a0785cd889203a6f3b375edca4a.png?2)
https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme
### Environment
It should contain:
* Mac
* Pycharm 2018.3.4
* Material Theme Plugin version 3.5.0.1

**Comment by mallowigi** [comment]
There is already a theme named "Deep Ocean"...

**Comment by zengjice** [comment]
I know, but I think there are still many differences between the two. May be a problem with color matching schemes?

**Comment by mallowigi** [comment]
There are a few mismatches, basically console being yellow and the operators taking the keywords color.

I'll check what I can do, but it should be consistent

**Comment by zengjice** [comment]
> There are a few mismatches, basically console being yellow and the operators taking the keywords color.
> 
> I'll check what I can do, but it should be consistent

Thanks.

**Comment by mallowigi** [comment]
After reconsideration, I've decided to NOT do that. I don't like the idea of having the keywords in cyan, after all this project is made following the Sublime Theme, not the VSCode one.

I'm happy as it is, though I'm going to add console as a JS Addition as well.
