### ISSUE TITLE
Rider: Settings save error

### ISSUE THREAD

**Issue by martinaguilar** [ChrisRM/material-theme-jetbrains#1129]
When installing Material UI in rider 2018.3.x, the IDE gives an error that cannot save IDE settings.
Next time you load Rider, the plugin is disable and your changes to configuration is lost.

Tested with material 3.5, 3.6 and 3.7
OS: Linux, Windows.

**Comment by mallowigi** [comment]
Could not reproduce. Can you provide the exact steps?

**Comment by shik4rishuffle** [comment]
I have the same issue, have removed cache, reinstalled the plug in, cannot fix this at all. have tried it on colleagues machine with same version of rider and it works fine, just not working on mine
