### ISSUE TITLE
Default Color for UI, Panels, Dialogs Etc.

### ISSUE THREAD

**Issue by 58bits** [ChrisRM/material-theme-jetbrains#113]
OMG - this is amazing. I was _so_ tired of the washed-out Darcula UI theme in PHPStorm.

Is it possible to set the default background color for all of the IDE UI components - such as side bars, trees, panels, dialogs etc? (i.e. not the editor syntax colors as I have my own syntax highlighting scheme).

Attached is the current color, which is sort of a dark teal. I'd like to make it a little darker if possible.

<img width="2021" alt="material-theme" src="https://cloud.githubusercontent.com/assets/405612/10991172/a9c4a840-848d-11e5-9534-941fbdcd537f.png">

**Comment by 58bits** [comment]
Ah - have just seen the material theme options settings...

<img width="569" alt="options" src="https://cloud.githubusercontent.com/assets/405612/10991300/b9a81c14-848e-11e5-9dac-9033c77600b2.png">

Very nice, but I was aiming for something like the screenshot below. It would be totally awesome if that single background color was configurable.

![dark](https://cloud.githubusercontent.com/assets/405612/10991330/d95ff25c-848e-11e5-9ef2-c3289d817483.png)

**Comment by robertboloc** [comment]
You should be able to achieve this by using the following plugin: https://github.com/dmalch/ColorIde

**Comment by ChrisRM** [comment]
I would advice not to use that plugin, as it actually replaces some core files.

**Comment by SkiftCreative** [comment]
Would that plugin cause issues? I have been using coloride for a long time so the panels fit my editor for a long time. over a year and it has worked great.

**Comment by ChrisRM** [comment]
I'm not sure tbh, but if you take a look at the [source](https://github.com/dmalch/ColorIde/blob/master/src/main/java/com/github/dmalch/PatchIdeApplicationComponentImpl.java) for that particular plugin, it seems to replace/patch some core files, which could potentially cause some issues when you update the application. I'm not sure if it permanently replaces the files or just patches the file, but either way it could cause problems. 

There will be an update to my plugin soon which enables you to set the UI colors to whatever you prefer.

**Comment by ova2** [comment]
Chris, thanks for this plugin first. It looks very nice, but I wish me more color customization too. Sometimes, the text is black on the black background. E.g. when you rename a file or when commit changes and want to put some commit description.

![image](https://cloud.githubusercontent.com/assets/767334/18029796/8e62a432-6ca2-11e6-813a-8b7087952b0d.png)

**Comment by mallowigi** [comment]
Could be a nice addition yeah. People still want it?

**Comment by guicara** [comment]
Yes definitely!
