### ISSUE TITLE
Shelve dialog doesn't disappear after shelving

### ISSUE THREAD

**Issue by bzx** [ChrisRM/material-theme-jetbrains#1130]
### Summary

Shelve modal dialog doesn't disappear after shelving. No matter how I invoke the dialog (mouse click, contextual menu, keyboard shortcut), it stays on the screen after shelving. I can dismiss it only by invoking another modal dialog - such as global search in files.

I've contacted JetBrains support about this, and they were not able to reproduce. However when I disable Material Theme, the issue is gone.

I didn't have this issue in IntelliJ version 2017.x.

### Steps to reproduce (if needed)

1. Make changes in your codebase.
2. Open "Local changes", and shelve changes from current Changelist (or use contextual menu, or keyboard shortcut)
3. When the modal dialog appears, click "Shelve Changes" button.

### Environment

IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Material Theme UI v3.5.0.1

Loaded custom plugins: Karma (183.5153.1), Lombok Plugin (0.23-2018.3), Material Theme UI (3.5.0.1), NodeJS (183.5429.1), TeamCity (2018.2.60977)

**Comment by mallowigi** [comment]
cannot reproduce

**Comment by mallowigi** [comment]
Can you provide more information about your environment, or how to reproduce? The aforementioned steps didn't work

**Comment by bzx** [comment]
I provided the repro steps and that's really all it takes.. however there must be something about the project environment because when I created a new one from some random git repo, the shelving happens without this glitch.

Which specific information would be helpful to identify this?

**Comment by mallowigi** [comment]
so it is project related... do you have maybe a logfile that I can see ?

**Comment by bzx** [comment]
The log is attached. Thanks for looking into it.
[idea.log](https://github.com/ChrisRM/material-theme-jetbrains/files/2888945/idea.log)

**Comment by mallowigi** [comment]
Sorry, I don't see anything pointing out the plugin being at fault here. 

If it happens again, look on the small red indicator on the bottom right, if it happens, that means that there is something with the plugin. On a side note, try to reproduce without the plugin on and tell me if it happens as well.

**Comment by bzx** [comment]
@mallowigi I never was able to see any kind of red indicator in bottom right. However, the problem is gone with the latest version of IJ (IntelliJ IDEA 2018.3.5 (Ultimate Edition) Build #IU-183.5912.21, built on February 26, 2019).

I think there was something in .4 that was causing it.. glad it's over.
