### ISSUE TITLE
Non editable menu and navigation bar.

### ISSUE THREAD

**Issue by Tylertron1998** [ChrisRM/material-theme-jetbrains#1131]
### Summary

The menu and (navigation bar?) seems to be non editable. Is this intentional? You can see the two stick out very much.

### Expected behavior

n/a

### Actual behavior

n/a

### Steps to reproduce (if needed)

n/a

![screenshot from 2019-02-20 16-57-07](https://user-images.githubusercontent.com/34944514/53109397-b1d8f980-3530-11e9-9beb-da1a78b9995d.png)

### Environment

Ubuntu - also the same on windows 10.

CLion 2019.1 EAP
Build #CL-191.5532.20, built on February 13, 2019
CLion EAP User
Expiration date: March 15, 2019
JRE: 1.8.0_202-release-1483-b4 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-15-generic

**Comment by mallowigi** [comment]
Thanks. It will be fixed next release.

**Comment by Tylertron1998** [comment]
Just to clarify - is there supposed to be a option for this? Or are you implementing it now? Thanks (:

**Comment by mallowigi** [comment]
You're talking about the background right? I fixed the issue with the navbar background, not for the menus though as I don't have a linux environment at the moment, but I don't think it will be too much of a hassle the same way the navbar does.

So yeah next version the navbar will be applied as well

**Comment by Tylertron1998** [comment]
![b](https://user-images.githubusercontent.com/34944514/53191453-c0dcac00-3603-11e9-8232-882696e6ed64.png)
Just to clarify which parts im on about (the parts in this image highlighted in yellow) - i don't know the exact name for them, but if there was an option to colour them and make them semi transparent like every other item/box/list, that would be really nice. Thank you for your responses!
