### ISSUE TITLE
[PHPSTORM] Run inspection > Eslint > Button text alignment

### ISSUE THREAD

**Issue by dmason30** [ChrisRM/material-theme-jetbrains#1132]
### Summary
![image](https://user-images.githubusercontent.com/20278756/53118600-64b35280-3545-11e9-8616-d4f5ee6e756c.png)

...

### Expected behavior
Button text not to overlap icon
...

### Actual behavior
Button text overlaps icon
...

### Steps to reproduce (if needed)
In a project with eslint enabled and configured:
1. Menu > Code >Run inspeciton by name
2. Search and select "Eslint"
3. When the panel pops up with the results click on one of the results and the above screen shot appears right hand side. 

### Environment
PhpStorm 2018.3.4
Build #PS-183.5429.47, built on February 8, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme Plugin: 3.5
Theme selected: Material Darker

**Comment by mallowigi** [comment]
Thanks. Will be fixed on the next release.
