### ISSUE TITLE
unused import no longer IDE default (gray + underlined)

### ISSUE THREAD

**Issue by michahell** [ChrisRM/material-theme-jetbrains#1133]
### Summary

It seems that unused imports (which áre working using the `Typescript Language Service`, because if I hover over them I can read the warning popup) are no longer showing up in grey (and grey underlined) as they used to. I have not changed anything in my Editor / syntax coloring settings but possibly after one or two Material UI updates this no longer works, an unused import stays yellow (using the default `Material Oceanic` theme)

### Expected behavior

unused imports etc. become grey or grey underlined

### Actual behavior

unused imports etc. stay yellow (or just the assigned color for `var / let / const`.

Screenshots:

![screenshot 2019-02-21 at 15 37 43](https://user-images.githubusercontent.com/225784/53176633-c7acf400-35ee-11e9-8748-b2b6a04f949f.png)

### Environment

env: `Help` -> `Settings Summary`

IDE Info:
Custom plugins: [Material Theme UI (3.5.0.1), nginx Support (0.1.6), .ignore (3.0.0.182), GNU GetText files support (*.po) (183.3795.13), BashSupport (1.7.4), Lines Sorter (1.0.1)]
Disabled plugins:[TeamCity Integration (2017.1.46654), IntelliJ Configuration Script (183.5429.34), Es6 intentions (0.2.2), RAML Plugin For IntelliJ (0.10)]
Build version: WebStorm 2018.3.4 Build #WS-183.5429.34 January 30, 2019
Java version: 1.8.0_152-release-1343-b26x86_64
Operating System: Mac OS X (10.14.3, x86_64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

screenshot:

![screenshot 2019-02-21 at 15 39 11](https://user-images.githubusercontent.com/225784/53176795-1195da00-35ef-11e9-81c6-6c8cdf2b5829.png)

**Comment by mallowigi** [comment]
It would be very troublesome to fix. In the meanwhile you can disable the "Language additions" in the "Other tab"

**Comment by mallowigi** [comment]
Are you sure you're not on Power Safe mode? Because it works well to me.

**Comment by michahell** [comment]
Hmm, this is still an issue.. I don't see unused imports in a different color anymore :(
