### ISSUE TITLE
Plugin crashes after updating to 3.8.0

### ISSUE THREAD

**Issue by vdrijt** [ChrisRM/material-theme-jetbrains#1134]
### Summary
After updating Material to 3.8.0 and restarting PhpStorm the plugin can't be loaded. Screenshot of the error: 
![image](https://user-images.githubusercontent.com/10928547/53228864-d80eae80-3682-11e9-9a7c-fb9e61bab72f.png)

PhpStorm 2019.1 EAP
Build #PS-191.5701.19, built on February 20, 2019
PhpStorm EAP User
Expiration date: March 22, 2019
JRE: 1.8.0_202-release-1483-b4 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Using Material custom theme:
https://github.com/xdrop/night-owl-jetbrains

**Comment by mallowigi** [comment]
I've issued a hotfix, it will be available shortly. Try it and tell me the results

**Comment by vdrijt** [comment]
Still had the problem, same error.
Tried a few things and the problem comes from the custom theme :).


- It works when I remove the custom theme plugin and reinstall Material.
- It crashes again when I reinstall the custom theme.

**Comment by mallowigi** [comment]
OK now (3.8.0.2) it should be fixed!
