### ISSUE TITLE
Added description of issue, with screenshots, to a shared evernote doc:

### ISSUE THREAD

**Issue by machinusx** [ChrisRM/material-theme-jetbrains#1135]
Last 3 versions not loading in IDE. Build number compatibility is probably the issue. I added details with pictures of failed install, and comparison values of plugins with build number masks which are loading, to a shared evernote. Pasting the note contents here not working.
https://www.evernote.com/l/AAX4UnpadstJe43_2GCu1p7CNCB61AthxXI/

**Comment by mallowigi** [comment]
I updated the readme, the latest available version for 2018.3 is 3.5.0

**Comment by mallowigi** [comment]
To use the new versions you must upgrade to the eap versions
