### ISSUE TITLE
High Contrast Mode Text Color

### ISSUE THREAD

**Issue by mustafaozhan** [ChrisRM/material-theme-jetbrains#1136]
Hello please check the picture comparison below.
![screenshot 2019-02-22 at 10 28 02](https://user-images.githubusercontent.com/30001999/53233578-0645bb80-368e-11e9-8e11-8db4e323e5ef.png)
![screenshot 2019-02-22 at 10 22 55](https://user-images.githubusercontent.com/30001999/53233575-034acb00-368e-11e9-9740-ff67558da3d7.png)

In first one `High Contrast Mode` disabled and in second one `High Contrast Mode` enabled.

Problem: when `High Contrast Mode` is enabled text color in project view is also changing. It causes to similar color with the file which has been changed (file which is different than the version in git.

Note: screenshots are cropped they look really similar in fullscreen, you can test it.

**Comment by mallowigi** [comment]
This is the expected behavior. High Contrast is making background color darker and text color brighter. Truly enough it can be a problem with the modified files color, but there's nothing that prevents you to change it to your needs.
