### ISSUE TITLE
Brogrammer color scheme/theme?

### ISSUE THREAD

**Issue by iHassan** [ChrisRM/material-theme-jetbrains#1139]
### Summary
Is it possible to add brogrammer color scheme/theme? I really like it and use it on sublime with material theme but I don't know how to port it to PHPStorm.

### Expected behavior
![bro1](https://user-images.githubusercontent.com/10136492/53291268-647bb700-37d2-11e9-9640-a0bb171fdb32.JPG)

### Environment

PhpStorm 2018.2.1
Build #PS-182.3911.43, built on August 8, 2018
Windows 10 10.0

**Comment by mallowigi** [comment]
Sorry, this is not in my priorities right now. But you can try to make a plugin with it.

See the tutorial at https://www.material-theme.com
