### ISSUE TITLE
A changelog.md would be nice

### ISSUE THREAD

**Issue by the-ult** [ChrisRM/material-theme-jetbrains#114]
It would be nice if you could provide a changelog, so people can see wat the major changes are in a new release.

Thanks again for this awesome theme.

**Comment by Anahkiasen** [comment]
:+1:

**Comment by ChrisRM** [comment]
Will do, I'll send out some updates this weekend.

**Comment by ChrisRM** [comment]
[CHANGELOG](https://github.com/ChrisRM/material-theme-jetbrains/blob/master/CHANGELOG.md) added.
