### ISSUE TITLE
Ctrl+click (go to declatation) no longer works with trackpad

### ISSUE THREAD

**Issue by Jesseppi** [ChrisRM/material-theme-jetbrains#1140]
### Summary
After installing Material-theme I have lost the ability to ctrl+click. Uninstalling does not fix the issue either.

### Expected behavior
ctrl+click on a class or method usage will navigate to the declaration of the class or method

### Actual behavior
cursor changes to "finger" pointer when holding ctrl, however when clicking, nothing happens. f12 still works

### Steps to reproduce (if needed)

1. Install material-theme
2. attempt to ctrl+click

### Environment

OS: Windows Server 2016 10.0
IDE: JetBrains Rider 2018.3.3
plugin version: v3.5.0.1
only enabled plugin

**Comment by mallowigi** [comment]
I don’t think it has anything to do with the plugin, but I’ll check.

**Comment by mallowigi** [comment]
Just tried and couldn't reproduce. 

Can you try with a fresh installation, see that it happens exactly after the plugin is installed? Thanks

**Comment by Jesseppi** [comment]
> Just tried and couldn't reproduce.
> 
> Can you try with a fresh installation, see that it happens exactly after the plugin is installed? Thanks

Hi Mallowigi, thanks for having a look. Ill try now.

**Comment by Jesseppi** [comment]
Hi @mallowigi ,
You are correct it does not seem to be material UI. It must have been coincidental the that it stopped working the first time I installed the plugin. Sorry for wasting your time
