### ISSUE TITLE
GUI elements get bright red color

### ISSUE THREAD

**Issue by pillimoj** [ChrisRM/material-theme-jetbrains#1144]
### Summary
I get a lot of bright red color in the menus when using the plugin on Fedora

### Expected behavior
Colors look like the color scheme

### Actual behavior
![screenshot from 2019-03-01 01-34-38](https://user-images.githubusercontent.com/20387136/53608961-134e3780-3bc5-11e9-80c6-2604a2fe9778.png)

### Recreate

1. Install plugin
2. Restart
3. Select default settings (the first indication that something is wrong are the checkboxes in the wizard)

### Environment
IntelliJ IDEA 2018.3.5 (Community Edition)
Build #IC-183.5912.21, built on February 26, 2019
JRE: 1.8.0_191-b13 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.20.7-100.fc28.x86_64
Material Theme version 3.5.0.1
material_theme.xml:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="userId" value="-520f845a:16936d43df2:-8000" />
    <option name="version" value="3.5.0.1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Some similar bug happened a while ago:

https://github.com/ChrisRM/material-theme-jetbrains/issues/943

However I couldn't reproduce. Please check with this issue if it helps you.
