### ISSUE TITLE
Pycharm Code Coverage background colour in Arc Darc too light

### ISSUE THREAD

**Issue by ashleysommer** [ChrisRM/material-theme-jetbrains#1145]
### Summary
Colour of Code coverage line backgrounds in Pycharm with Arc Dark theme leaves text barely readable.

### Expected behavior

Code Coverage line background colour should be dark enough to allow light code to be visible.

### Actual behavior

Code Coverage line background colour is not dark enough to allow light code to be visible.
[**See this screenshot**](https://i.imgur.com/UgLapZ1.png).

### Steps to reproduce (if needed)

Install Pycharm 2018.3, install Material Theme plugin.
Select Arc Dark theme in Material UI settings.
Select Arc Dark editor color scheme in editor settings. 
Open a python project and run tests with Code Coverage turned on.
See result as per screenshot.

### Environment
PyCharm 2018.3.3 (Professional Edition)
Build #PY-183.5153.39, built on January 10, 2019
Licensed to *****
Subscription is active until *****
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.20.10
Material Theme UI v3.5
material_theme.xml
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="42a5f5" />
    <option name="selectedTheme" value="ARC_DARK" />
    <option name="userId" value="xxxx" />
    <option name="version" value="3.5.0.1" />
  </component>
</application>
```
material_custom_theme.xml
```
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by ashleysommer** [comment]
Changing colour scheme "Line Coverage: Full" to something like `#3E5325` and "Line Coverage: Partial" to something like `#554057` Fixes this issue.

**Comment by mallowigi** [comment]
Im currenlty reworking all the schemes, I will fix this for next version

**Comment by sunbc0120** [comment]
Is it possible to show the background color only in "gutter", but **NOT** in the editor?

**Comment by mallowigi** [comment]
You are talking about a feature of the ide itself, not the plugin. I invite you to ask this question on JetBrains’s YouTrack

--
Elior
