### ISSUE TITLE
Per-project theme / accent color

### ISSUE THREAD

**Issue by Aralun** [ChrisRM/material-theme-jetbrains#1146]
I can very easily differentiate different IDEs with the same Material theme thanks to different accent colors.

Is it possible to get the same functionality across projects? For example, two IntelliJ IDEA projects opened at the same time with different themes, or at least project-specific accent color.

**Comment by mallowigi** [comment]
I will be quick: no. I want this as well but as long as we are not able to have different color schemes per window, we can’t have different themes nor settings per window.

**Comment by Aralun** [comment]
Aw, too bad. When you say that we can't have different color schemes per window, are you referring to an API limitation?

**Comment by mallowigi** [comment]
At one point I managed to implement project settings and it worked well, unfortunately it wasn’t working well if you opened two projects at the same time, so I discarded it.

You’re free to open an issue request At jetbrains though.

**Comment by Aralun** [comment]
I would be glad to. Just to be entirely sure and to refine my search of existing issues on Jetbrains' side: What is needed is a way to have different color schemes and themes per window and / or projects ?

**Comment by mallowigi** [comment]
To be more technical, well, according to Java Swing guidelines, in a Java application there is a service called the UIManager which is like a bank for all colors, fonts, ui styles and so on, and all Java components are using this manager to allow switching fonts and colors at ease. However, when you open two projects side by side, you're not opening two instances of the IDE, instead you're using the same instance, it's just that you're having "floating windows" for each project. As a result, they share the same UIManager and therefore cannot display different colors at the same time.

It's the same limitation that would prevent you using the Darcula and Default look and feel simultaneously.

There has been an open issue for at least 4 years, so I think they can't do anything at that point. Still, you can try to vote, see if that gains traction in the future. https://youtrack.jetbrains.com/issue/IDEA-130956

**Comment by Aralun** [comment]
Well, hopefully it will. Thank you =)
