### ISSUE TITLE
Material Theme Suggestions

### ISSUE THREAD

**Issue by Davoleo** [ChrisRM/material-theme-jetbrains#1147]
### Summary

- Some way to disable all the Material theme features at once
- Make it so that the themes are on the same level of JetBrains themes, so that you can choose them from the settings instead of themes that cover the vanilla themes 
(I don't know if this is possible but it would be nice)
- Some way to see what features the various modules are hooked to, for example preview screenshots of what the IDE will look like

### Expected behavior

The whole point of this issue is to make theme choice and customization more efficient and a bit less "clunky"

### Actual behavior

Now if you want to disable the theme you either disable every module (which takes a lot :P) of it or you disable the plugin entirely (That seems to disable it in all the jetbrains products :/). 

You're not able to see what is going to change if you disable one module, and you may need to restart several times before getting the configuration you like the most

### Environment

IntelliJ IDEA 2018.3.3 (Ultimate Edition)
Build #IU-183.5153.38, built on January 9, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme Plugin version: 3.5

If possible please also give out your Material Theme/Material Custom Theme configuration file.
I don't know where it's located ^^^

**Comment by mallowigi** [comment]
I'm planning to release a "Material Theme Lite" plugin that will cover only the themes and the color schemes, without the customization features. It will be available as soon as the Theme API from Jetbrains is done.

Stay tuned!

**Comment by Davoleo** [comment]
nice to know! Looking forward to try it out
