### ISSUE TITLE
setting font on Webstorm

### ISSUE THREAD

**Issue by agileago** [ChrisRM/material-theme-jetbrains#115]
Now , my machine has installed Souce Code Pro font. like this
![image](https://cloud.githubusercontent.com/assets/11799110/10996914/cecfe920-84c3-11e5-8aa1-7a24b3bcc57a.png)

I want to use Source Code Pro Italic font.   but i can't find this font in font setting.     Do you know how to set it . BTW. i can set it on sublime

![image](https://cloud.githubusercontent.com/assets/11799110/10996949/1b07b660-84c4-11e5-80e9-8001b2974d44.png)

![image](https://cloud.githubusercontent.com/assets/11799110/10996958/2d5bb154-84c4-11e5-9210-6b7ea79a6993.png)

**Comment by mikeerickson** [comment]
@agileago this is not something related to the theme, it is an operation of WebStrom (and PHPStorm).  I would suggest you send this message to support@jetbrains.com
