### ISSUE TITLE
Add Yarn Version Manager rc file icon

### ISSUE THREAD

**Issue by Grawl** [ChrisRM/material-theme-jetbrains#1153]
[`Yarn Version Manager`](https://yvm.js.org) is a tool to switch [`yarn`](https://yarnpkg.com) versions. Like [`nvm`](https://github.com/creationix/nvm) but for `yarn`.

> YVM will automatically use the correct yarn version when you run any yarn commands in any folder with a `.yvmrc` file. Otherwise, it will use you a globally set version of yarn.

For now, `.yvmrc` icon is "plain text" file:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/846774/54170445-7a6fc400-44c2-11e9-8481-42f737873949.png">

I suggest to change icon for this file to YVM or Yarn icon.

---

There is an icon on YVM website:

![yarn](https://user-images.githubusercontent.com/846774/54170232-9c1c7b80-44c1-11e9-8927-d489e960c414.png)

Not sure we want use YVM website icon or Yarn website favicon for `.yvmrc` files

![yarn-icon](https://user-images.githubusercontent.com/846774/54170348-10571f00-44c2-11e9-90ac-60bb1ba2bd93.png)

**Comment by mallowigi** [comment]
will be added on next release

**Comment by Grawl** [comment]
maybe you should close issue when it's resolved?

**Comment by mallowigi** [comment]
no
