### ISSUE TITLE
Add WebP image icon

### ISSUE THREAD

**Issue by Grawl** [ChrisRM/material-theme-jetbrains#1155]
### Summary

[WebP](https://en.wikipedia.org/wiki/WebP) image format files does not have an image icon.

### Expected behavior

Files with `.webp` extension displayed with image icon, the same as `.png` or `.jpeg`

### Actual behavior

Files with `.webp` extension displayed with white blank file icon.

### Steps to reproduce (if needed)

1. Add any image in WebP format to a project
2. Look at sidebar
3. Or open it and look in breadcrumbs

<img width="488" alt="image" src="https://user-images.githubusercontent.com/846774/54410696-4d2c4b80-4738-11e9-9038-800d0c6afe02.png">

<img width="516" alt="image" src="https://user-images.githubusercontent.com/846774/54410707-57e6e080-4738-11e9-9fca-b3e08d355108.png">

### Environment

IntelliJ IDEA 2019.1 Beta (Ultimate Edition)
Build #IU-191.6014.8, built on March 6, 2019
IntelliJ IDEA EAP User
Expiration date: April 5, 2019
JRE: 1.8.0_202-release-1483-b31 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Material Theme UI v3.8.0.2

**Comment by Grawl** [comment]
Why this issue is closed?

**Comment by mallowigi** [comment]
will be added on next release
