### ISSUE TITLE
Chinese Scrambling Problem

### ISSUE THREAD

**Issue by NSLogName** [ChrisRM/material-theme-jetbrains#1156]
![image](https://user-images.githubusercontent.com/20921512/54513314-06d22900-4992-11e9-8c40-c4710bad5e64.png)
 Material theme laster version！
Thanks!

**Comment by mallowigi** [comment]
Please change the font in Appearance > Override Fonts

**Comment by NSLogName** [comment]
Hello, I tried the method you provided, but it didn't work. And I'm sure this font supports Chinese display.Thanks！
![image](https://user-images.githubusercontent.com/20921512/54891730-76439d80-4ee9-11e9-8678-6490b20560c9.png)
![image](https://user-images.githubusercontent.com/20921512/54891746-83608c80-4ee9-11e9-9c2e-e0de24c0e81b.png)

**Comment by mallowigi** [comment]
Hmmm, so the issue is with the tooltips

I'll investigate

**Comment by NSLogName** [comment]
Thank you very much. Have a good time!

**Comment by mallowigi** [comment]
The tooltip font follows the color scheme font (Settings > Editor > Color Scheme > Color Scheme Font). Since the themes are made to work with Menlo font, I will not change it for Chinese users. Please change it by yourself thanks.

**Comment by NSLogName** [comment]
Thank you, it's working now! 😄
