### ISSUE TITLE
Uninstalling or disabling this plugin should reset the colors to the original state

### ISSUE THREAD

**Issue by geekrumper** [ChrisRM/material-theme-jetbrains#1157]
### Summary
After uninstalling or disabling this plugin, some color properties remain.

### Expected behavior
I would like the IDE to have all colors before installation resp. activation

### Actual behavior
As mentioned, some colors remain and toggling color scheme does not change the output. It seems to me that this plugin is overriding previously existing color schemes.

### Steps to reproduce (if needed)

1. First step
- Install plugin and activate any theme

2. Second step
- disable or uninstall plugin

3. Third step
- check out tab header colors
- file colors in "Version Control" window

You can also add Screenshots for a better understanding.
![2019-03-18 15_04_17-Window](https://user-images.githubusercontent.com/662318/54535964-0173df00-4990-11e9-8ce5-7e0f19710495.png)

**Comment by mallowigi** [comment]
There's no way to do so. Please refer to http://www.material-theme.com/docs/faq-troubleshooting/#file-status-colors

**Comment by mallowigi** [comment]
On a sidenote, now that they are making custom themes available, there is a high chance that an API will be available to change file status colors again.

**Comment by geekrumper** [comment]
@mallowigi 
Thank you for the heads up. The only solution was to uninstall the IDE, delete my settings and re-install it from scratch.
