### ISSUE TITLE
Support for Windows Forms Designer

### ISSUE THREAD

**Issue by edokan** [ChrisRM/material-theme-jetbrains#1158]
### Summary

JetBrains Rider recently added Windows Form designer support in 2019.1 EAP. Designer surface does not use theme colors. I believe it is not possible in its current form, but please provide support for Windows Forms designer.

### Expected behavior

Designer surface to use theme colors.

### Actual behavior

Designer surface uses windows theme colors.

![image](https://user-images.githubusercontent.com/1482410/54587661-cf1abe00-4a31-11e9-8604-e312a21c41ed.png)

### Steps to reproduce (if needed)

1. Open Rider 2019.1 EAP
2. Enable Windows Form Designer
3. Create a Windows Desktop App
4. Open main for of the app in designer view

More details can be found here: https://youtrack.jetbrains.com/issue/RIDER-1034

### Environment

JetBrains Rider 2019.1 EAP
Build #RD-191.6062.275, built on March 15, 2019
Rider EAP User
Expiration date: April 14, 2019
JRE: 1.8.0_202-release-1483-b37 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme v 3.8.0.2
[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2982057/material_theme.zip)
[material_custom_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2982060/material_custom_theme.zip)

**Comment by mallowigi** [comment]
I think that it's not possible to customize this view. IT's not something built by Jetbrains but rather the builtin Windows Form Designer from the .NET SDK or something like that. You can see how the UI is off compared to the rest of the IDE.
