### ISSUE TITLE
Topless tabs

### ISSUE THREAD

**Issue by edokan** [ChrisRM/material-theme-jetbrains#1159]
### Summary

Please provide an option for tabs to be topless, Like bottomless but without top.
But only for tabs that is shown below of the screen like the one in Rider Windows Form Designer.

### Expected behavior

![image](https://user-images.githubusercontent.com/1482410/54588882-37b76a00-4a35-11e9-8c1e-c3f2d819c2fa.png)

Designer and Text tabs should be able to use topless, while document tabs should use bottomless.

### Actual behavior

All tabs use selected one

### Steps to reproduce (if needed)

Open Windows Forms Designer in Rider.

### Environment

JetBrains Rider 2019.1 EAP
Build #RD-191.6062.275, built on March 15, 2019
Rider EAP User
Expiration date: April 14, 2019
JRE: 1.8.0_202-release-1483-b37 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
Will be added on next release

**Comment by edokan** [comment]
@mallowigi Thank you for implementing this, but I feel like I've explained this wrong.

Rider shows two tabs at the same time as you can see in screenshot, one for document itself (name and all) at the top of the document view, and one for the inside view (Designer / Text) at the bottom of the document view. 

First tabs looks wonderful, but second looks terrible, so I requested you to add a topless option, but just for that inner tab view. I'm not sure if its is possible you to distinguish that inner tabs from outer ones.

![image](https://user-images.githubusercontent.com/1482410/55884424-b759d400-5bb0-11e9-8981-54729c02d4db.png)

Sincerely

**Comment by mallowigi** [comment]
I see, should be easy to implement
