### ISSUE TITLE
The and operator is not sown in Javascript.

### ISSUE THREAD

**Issue by saul-lopez** [ChrisRM/material-theme-jetbrains#116]
Hi. 

I'm using material theme in PHPStorm 10 #PS-143.381 and it works great, however, I'm having a little problem here: the and operator (&&) is not shown in a Javascript file as shown here:

![image](https://cloud.githubusercontent.com/assets/929038/11015717/5f339d1c-852e-11e5-9ecb-862195aa233f.png)

As shown in the screenshot, the or operator is shown as expected. 

Possibly it's a configuration issue, but I couldnt find the propper setting to make this operator visible.

Thanks.

**Comment by ByScripts** [comment]
For information, I just tried (same PhpStorm version) and I don't get the problem.

**Comment by caccialdo** [comment]
Tried in WebStorm 11 Final. Didn't get the problem as well

**Comment by saul-lopez** [comment]
Thanks @ByScripts and @caccialdo. You're right. I've made some customizations to the Default Material Theme and the problem presents. When I revert to the original, the operator is shown correctly.

I only have to find out what setting is causing the problem. 

Thanks.

**Comment by Mopolo** [comment]
Hi,

I've been searching for a solution for a moment when I found this old thread. In case someone has the same issue, I juste had to install the last version of the font I use ([Source Code Pro](https://github.com/adobe-fonts/source-code-pro)) and that @saul-lopez seems to be using too.

It's fixed now!
