### ISSUE TITLE
Link on Market Place pointing to the wrong repository

### ISSUE THREAD

**Issue by garhbod** [ChrisRM/material-theme-jetbrains#1161]
The link in Jetbrain's market place is pointing to the wrong repo.
The line that says "This will add the Material Theme look to your IDE."

**Comment by mallowigi** [comment]
What?

**Comment by garhbod** [comment]
https://plugins.jetbrains.com/plugin/8006-material-theme-ui

On that page the line that says "This will add the Material Theme look to your IDE." doesn't point to this package. Makes it a bit confusing is all

**Comment by mallowigi** [comment]
That's because it points to the original Material Theme, where it all began.
