### ISSUE TITLE
Editor colors don't change when using the settings drop down

### ISSUE THREAD

**Issue by clehene** [ChrisRM/material-theme-jetbrains#1164]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

Editor colors seem to always be one of the light / darcula defaults rather than the themes

### Expected behavior

Editor colors should follow theme colors

### Actual behavior

They seem to be overridden by the theme in "Appearance" rather than the plugin

### Steps to reproduce (if needed)
![Screen Shot 2019-03-22 at 5 43 49 PM](https://user-images.githubusercontent.com/101597/54859457-9e08ea80-4cca-11e9-9ac8-bee62338b81e.png)
![Screen Shot 2019-03-22 at 5 48 46 PM](https://user-images.githubusercontent.com/101597/54859477-c4c72100-4cca-11e9-91c8-357865ed175a.png)
![Screen Shot 2019-03-22 at 5 54 47 PM](https://user-images.githubusercontent.com/101597/54859534-a0b80f80-4ccb-11e9-965e-ef137e940579.png)

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.62, built on March 21, 2019
Licensed to Cosmin Lehene
Subscription is active until April 2, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
If possible please also give out your Material Theme/Material Custom Theme configuration file.

## To reproduce

I can't talk about a concrete reproduction, because it has never actually worked properly, and I'm unable to get it to work in any scenario, but I'll describe the context.

I have two versions if IDEA 2018 and 2019 (both latest)
IDEA settings syncing is enabled 

I've noticed the behavior while switching between themes. Initially I think I did see some properly rendered editors, but didn't always work.
I then disabled the plugin in both versions. 
Then before re-enabling it.  I had enabled the default high-contrast darcula. 
After that I would always see the high contrast darcula upon re-enabling / re-install of the Material theme, but mostly  in conjunction with dark themes (and the default light one with light themes). I cycled the default themes from high contrast to darcula to light both with plugin installed as well as while the plugin is uninstalled just to reinstall it over a different state, etc.
Sometimes, I can notice a rendering attempt which could be the correct one, but it ends up being default.

**Comment by mallowigi** [comment]
Please write the steps to reproduce

**Comment by clehene** [comment]
@mallowigi updated the original post, with some context. It's not reproduction per se because I can't get it to work in order to break it, but provided some context

**Comment by mallowigi** [comment]
I still don't understand.

The correct behavior of the plugin is the following:
1. Select a theme using the Material Theme Switcher (not the one provided by Jetbrains)
2. The UI and the color scheme should take the selected theme

Changing the Look and Feel via the Appearance setting will temporarily override the Material Theme theming, but will revert back to the selected theme upon restart. It doesnt work in conjunction of Jetbrains themes such as Darcula, High Contrast or Plugin themes.

**Comment by clehene** [comment]
@mallowigi  I did suspect that that's how it's supposed to behave. What I'm trying to say is that it doesn't and I'm not able to get the editor to show the correct theme regardless of the sequence of actions I'm taking.

**Comment by clehene** [comment]
Retrying it looks like it will get stuck to older themes

<img width="395" alt="Screen Shot 2019-03-23 at 12 03 32 PM" src="https://user-images.githubusercontent.com/101597/54870469-46b75880-4d64-11e9-8909-afc76e695377.png">
<img width="311" alt="Screen Shot 2019-03-23 at 12 03 45 PM" src="https://user-images.githubusercontent.com/101597/54870470-46b75880-4d64-11e9-9f03-437fc531b998.png">
<img width="290" alt="Screen Shot 2019-03-23 at 12 03 49 PM" src="https://user-images.githubusercontent.com/101597/54870471-46b75880-4d64-11e9-8b6b-daf8badaa905.png">
<img width="398" alt="Screen Shot 2019-03-23 at 12 04 08 PM" src="https://user-images.githubusercontent.com/101597/54870472-46b75880-4d64-11e9-8bfa-05f62f52fbfe.png">
<img width="560" alt="Screen Shot 2019-03-23 at 12 04 42 PM" src="https://user-images.githubusercontent.com/101597/54870473-46b75880-4d64-11e9-86cc-55a2f7d9ffdd.png">
<img width="483" alt="Screen Shot 2019-03-23 at 12 05 09 PM" src="https://user-images.githubusercontent.com/101597/54870474-46b75880-4d64-11e9-98f3-72c70ee0c448.png">
<img width="144" alt="Screen Shot 2019-03-23 at 12 05 12 PM" src="https://user-images.githubusercontent.com/101597/54870475-474fef00-4d64-11e9-818f-fda3915da003.png">
<img width="226" alt="Screen Shot 2019-03-23 at 12 05 26 PM" src="https://user-images.githubusercontent.com/101597/54870476-474fef00-4d64-11e9-8f0b-cc4335d9cb76.png">
<img width="561" alt="Screen Shot 2019-03-23 at 12 05 36 PM" src="https://user-images.githubusercontent.com/101597/54870477-474fef00-4d64-11e9-8f49-a04445f6ba2d.png">
<img width="155" alt="Screen Shot 2019-03-23 at 12 05 50 PM" src="https://user-images.githubusercontent.com/101597/54870478-474fef00-4d64-11e9-9019-50e8febdcfb6.png">
<img width="501" alt="Screen Shot 2019-03-23 at 12 05 59 PM" src="https://user-images.githubusercontent.com/101597/54870479-474fef00-4d64-11e9-99fd-30ddd8adb0cc.png">
<img width="363" alt="Screen Shot 2019-03-23 at 12 06 46 PM" src="https://user-images.githubusercontent.com/101597/54870480-474fef00-4d64-11e9-9530-2df0aae278e8.png">

**Comment by clehene** [comment]
So each (light / dark) will always use the corresponding IDEA light / dark instead of the actual theme. 
I did the last few tests on 2019.RC but I saw similar behavior on 2018.3 I can / try with a particular version if that helps.

**Comment by mallowigi** [comment]
Hmm, 

So weird, it's the first time I heard about that.

Quick question: When you type Cmd+~ and select "Color Scheme", do you see the Material ones ?

**Comment by clehene** [comment]
Assuming its "command + shift + ~" - the shortcut was not set. I did set the theme chooser to it and I do see the themse after 
<img width="357" alt="Screen Shot 2019-03-23 at 12 29 59 PM" src="https://user-images.githubusercontent.com/101597/54870726-80d62980-4d67-11e9-9c1d-c0397e6c0fc6.png">

**Comment by clehene** [comment]
Ok, this is weird. Choosing themes through that (rather than through settings) seems to apply the theme correctly

**Comment by mallowigi** [comment]
Nope, the color schemes, not the themes

**Comment by mallowigi** [comment]
aha. Hmm I see using the dropdown menu doesn't apply the schemes then. It's a bug then.

**Comment by clehene** [comment]
Also:
<img width="190" alt="Screen Shot 2019-03-23 at 12 32 48 PM" src="https://user-images.githubusercontent.com/101597/54870750-ceeb2d00-4d67-11e9-8061-0d4a9daa4f17.png">

**Comment by mallowigi** [comment]
Ok, fixed for next release

**Comment by clehene** [comment]
@mallowigi amazing! Thanks for the quick responses, workaround and fix!!
