### ISSUE TITLE
How to remove the color of changed folders?

### ISSUE THREAD

**Issue by kangarko** [ChrisRM/material-theme-jetbrains#1165]
Hi,

how can I remove the color of changed folders? I was able to remove the accented color of individual files when they are uncommited but cannot find this one. It seems to use the main accent color.

![idea64_2019-03-23_14-45-49](https://user-images.githubusercontent.com/1918426/54866909-812bf000-4d7a-11e9-9cf5-9426122a02ae.png)

Thanks

**Comment by mallowigi** [comment]
Material theme settings > Project View > Custom Directories style

**Comment by kangarko** [comment]
@mallowigi thanks, I did try this previously but I cannot find the respective option there. I even tried to add gray color manually to seemingly relevant options but without success. Removing Material theme plugin solves this issue but I really enjoy it so would love to have this small thing fixed.

![a](https://i.imgur.com/LXd7wEp.png)

**Comment by mallowigi** [comment]
In this same menu there is an option "Directories", try changing there

**Comment by kangarko** [comment]
I tried sorry but it wont work. Can you look into it please? I know it is a small thing but pretty distractive as I am trying to get the colors to gray (monochrome does not affect

**Comment by mallowigi** [comment]
Ok found it, it's the "Project View Decorators" option.

**Comment by kangarko** [comment]
Thanks man <3
