### ISSUE TITLE
Code editor background color doesn't change with theme background color

### ISSUE THREAD

**Issue by Allmeta** [ChrisRM/material-theme-jetbrains#1167]
As you see in this picture, the code editor background won't change with the background color I have set for the custom theme. And yes, the custom theme is selected.
![image](https://user-images.githubusercontent.com/22347443/55067586-3c58cf80-5080-11e9-83e1-64bf8db7b1dc.png)

**Comment by Allmeta** [comment]
I duplicated the Material Ocean theme for the Color Scheme, but I can't change the background color anywhere in these settings 
![image](https://user-images.githubusercontent.com/22347443/55070133-e1c27200-5085-11e9-8ea9-b18a78986aba.png)

**Comment by Allmeta** [comment]
It probably has something with parent theme to do, I'd guess?

**Comment by mallowigi** [comment]
They are not related. Themes control the UI, whereas Color Schemes control the editor. Since the custom theme is a customized theme, it has no color scheme associated by it, therefore uses the current color scheme.

For more information on color schemes I invite you on reading the docs.
