### ISSUE TITLE
highlight tab placement

### ISSUE THREAD

**Issue by apodgorbunschih** [ChrisRM/material-theme-jetbrains#117]
When the tab placement is right or left
![screenshot - 2015-11-09 13 04 36](https://cloud.githubusercontent.com/assets/7089880/11032206/82338006-86e2-11e5-9f8c-edc616739712.png)
, the current file is not highlighted

**Comment by jameslk** [comment]
I was just about to open an issue for this. I'm having the exact same problem, so it's hard to determine which tab I'm currently on. It makes vertically stacked tabs much less useful.

**Comment by sepehr** [comment]
Encountering the issue as well when placing tabs on bottom.

**Comment by daniellz** [comment]
<details> 
  <summary><a id="spoiler2" href="#spoiler2" title="Pic for the "tabs on bottom" case ">Pic for the "tabs on bottom" case </a></summary>
   ![ls_layout - 5bc__yandexdisk_projects_ls_layout 5d - _js_main js - phpstorm 10 0 3 2016-03-02 11 17 28](https://cloud.githubusercontent.com/assets/7566711/13454478/87004440-e068-11e5-9ce8-d20d7748f8f5.png)
</details>

**Comment by sepehr** [comment]
Dying to see this fixed.

**Comment by ChrisRM** [comment]
Fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/23742ee8d836ac7c19838feef0d08cd49dff1925

**Comment by sepehr** [comment]
Would you update it in Jetbrains repo as well?

Thank you.

**Comment by ChrisRM** [comment]
The plugin seems to misbehave with the newest version(145) of PHPStorm, so I need to figure out what's wrong there first. See #177
