### ISSUE TITLE
Add Setting to customize Open Folders Color

### ISSUE THREAD

**Issue by ERROPiX** [ChrisRM/material-theme-jetbrains#1171]
Hi,

I have tried all the custom theme settings and custom file colors settings, but I can not get rid of these folder colors that are highlighted with some colors as the chosen accent color: see screenshot:

![Capture](https://user-images.githubusercontent.com/6576868/55240984-6bb33c00-523a-11e9-85a1-90daf00174b1.PNG)

This occurs when I open a project in PHPStorm, if I have a file open, all it's parent folders get colored, doesn't happens when I open a file after starting the editor, even if I modify it, but if I leave it open, then close the project, open it again, it get highlighted!

Thanks

**Comment by mallowigi** [comment]
It’s the project view decorators setting

**Comment by ERROPiX** [comment]
Can you please tell me where I can change it?

**Comment by ERROPiX** [comment]
I tried changing all of the folder colors in File | Settings | Editor | Color Scheme | Material File Colors
but no luck

**Comment by mallowigi** [comment]
You can’t change it, only disable it

--
Elior

**Comment by ERROPiX** [comment]
I don't understand your response, please tell me which setting should I disable? I don't know which of the directories colors is controlling this!

**Comment by mallowigi** [comment]
You  need to go to Settings > Appearance > Material Theme > Other Tweaks > Uncheck the Project View Decorators

**Comment by ERROPiX** [comment]
That's the answer man!
Thank you so much

**Comment by ERROPiX** [comment]
Can you add these other tweaks to **File | Settings | Editor | Color Scheme | Material File Colors** this will be awesome

**Comment by mallowigi** [comment]
That makes sense, I'll think about it.

**Comment by mallowigi** [comment]
By the way, you can also setup the color via the option "Directories" in Material File Colors, along with the option "Styled Directories" in the Project View Tab

**Comment by ERROPiX** [comment]
Yes, I have used that, I set my directories to white colors, but that green was overriding on active folders

**Comment by DmitryTronin** [comment]
Hi, this color comes from File | Settings | Version Control | File Status Colors:
- Have changed descendants
- Have immediate changed children
and some others.
After uninstalling the plugin those values aren't reset to Defaults. They should get, ideally.
Could you please address that?

**Comment by ERROPiX** [comment]
@DmitryTronin I have set all the colors in **File | Settings | Version Control | File Status Colors** to white and my issue still remain, it is not related to the color I shown in the screenshot

**Comment by ERROPiX** [comment]
Also @DmitryTronin I don't use any Version Control tool in my project

**Comment by DmitryTronin** [comment]
@ERROPiX Alright, sorry for hijacking the thread. I'll submit another one
