### ISSUE TITLE
Problem scrolling on Windows

### ISSUE THREAD

**Issue by zzm-note** [ChrisRM/material-theme-jetbrains#1172]
### Summary
[Material Theme UI Lite](https://github.com/mallowigi/material-theme-ui-lite/issues) page not found,forgive me for asking questions here.

### Expected behavior
Get used to moving the mouse cursor to the far right of the screen to operate the scroll bar.

### Actual behavior
1. I hope to operate the scroll bar when the mouse cursor is at the far right of the screen.

### Environment

It should contain:
* OS (Windows)
* IDEA and Pycharm 2019.1
* Material Theme UI Lite V1.3

Theme:**Atom One Dark Contrast
Default settings

**Comment by mallowigi** [comment]
Can you provide more screenshots?

**Comment by zzm-note** [comment]
Maximize the window,If the mouse pointer moves to the right edge of the screen, the scroll bar cannot be operated.
But under the default theme you can.
![无标题_爱奇艺](https://user-images.githubusercontent.com/25860330/55682115-48d30700-5961-11e9-980f-de103548771b.jpg)

**Comment by mallowigi** [comment]
Do you refer to the fact that the scrollbar is thinner than the regular one? I have no plans of making it larger, sorry.
