### ISSUE TITLE
Material Theme icons persist after being unchecked

### ISSUE THREAD

**Issue by rgcv** [ChrisRM/material-theme-jetbrains#1176]
### Summary

Akin to #1010, upon unchecking every box for disabling material icons, some icons remain different from the standard icons. The image below shows the folders whose names are highlighted/selected still have the Material Theme folder icons.

![image](https://user-images.githubusercontent.com/4052080/55435739-68011b80-5592-11e9-8f14-4e812f162080.png)

### Expected behavior

When Material Theme related iconography is disabled, IDEA icons *alone* are displayed

### Actual behavior

Some Material Theme icons still override IDEA's icons

### Steps to reproduce (if needed)

1. Install and configure Material Theme
2. Disable all the icons by unchecking the boxes in `File > Settings > Appearance & Behavior > Material Theme > Icons`
3. Apply settings

### Environment

**IntelliJ IDEA 2019.1 (Ultimate Edition)**
Build #IU-191.6183.87, built on March 27, 2019
JRE: 11.0.3+4 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.0.5-arch1-1-ARCH

**Material Theme**
Version: 3.8.0.2
```xml
<!-- material_theme.xml -->
<application>
  <component name="MaterialThemeConfig">
    <option name="arrowsStyle" value="Darcula" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="fileIcons" value="false" />
    <option name="fileStatusColorsEnabled" value="false" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isDecoratedFolders" value="false" />
    <option name="isHighContrast" value="true" />
    <option name="isPsiIcons" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="useMaterialIcons" value="false" />
    <option name="customSidebarHeight" value="22" />
    <option name="settingsSelectedTab" value="2" />
    <option name="tabsHeight" value="24" />
    <option name="accentColor" value="009dee" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="-b86c51d:169dfa5b74e:-8000" />
    <option name="version" value="3.8.0.2" />
  </component>
</application>
```

Custom theme didn't show any relevant information

**Comment by rgcv** [comment]
Okay, I feel incredibly silly, but I still think opening the issue was worthwhile since it might be happening or might've happened to other people thus far.

Apparently.. collapsing the folders and restarting **whilst remembering to also invalidate caches** did the trick. I swear for the life of me that I attempted this before. However, I'm guessing the trick is in open folder trees beforehand.

**Comment by mallowigi** [comment]
You have a point, this is a bug and a confusion that is occurring to a lot of users. Also this feature is very old so I’ll probably refactor it for version 4.0 to become more apparent.

The issue is from the “Project view decorators” which replaces the open folders with their hollow ones. And as you guessed this doesn’t check whether there Material Icons are checked.

I think for version 4.0 I’ll rephrase this option to become “open folders decorators” and depend upon Material Icons, which will be more apparent.
