### ISSUE TITLE
Filename hard to read with Deep Ocean

### ISSUE THREAD

**Issue by lh-engineering** [ChrisRM/material-theme-jetbrains#1179]
### Summary

In normal and contrast mode, the file/directory names are hard to read with the Deep Ocean theme. This is not an issue with the high contrast mode.

### Expected behavior

Selected filenames are easy to read when inactive.

### Actual behavior

Selected filenames are almost impossible to read.

### Steps to reproduce (if needed)

1. Change theme to Deep Ocean
2. Select a file on the sidebar
3. Click into the editor window

Normal inactive:
<img width="202" alt="Screen Shot 2019-04-03 at 1 00 51 PM" src="https://user-images.githubusercontent.com/49072813/55509341-ae955b00-5610-11e9-943a-dfaacba1aa17.png">

Normal active:
<img width="191" alt="Screen Shot 2019-04-03 at 1 01 10 PM" src="https://user-images.githubusercontent.com/49072813/55509356-b5bc6900-5610-11e9-93eb-388e0d3e5d28.png">

High contrast inactive:
<img width="188" alt="Screen Shot 2019-04-03 at 1 01 24 PM" src="https://user-images.githubusercontent.com/49072813/55509361-bb19b380-5610-11e9-89b1-c3d95210da83.png">

### Environment

PyCharm 2019.1 (Professional Edition)
Build #PY-191.6183.50, built on March 19, 2019
JRE: 11.0.2+9-b159.30 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

Material Theme version: 3.8.0.2

**Comment by mallowigi** [comment]
Fixed in 3.9.0.3
