### ISSUE TITLE
Fonts are too bold inside tree view

### ISSUE THREAD

**Issue by Yackbz** [ChrisRM/material-theme-jetbrains#1181]
### Summary

After updateing PHPStorm to 2019.1 the fonts inside the tree view are too bold.
There has been a similar issue before in 2017. [https://github.com/ChrisRM/material-theme-jetbrains/issues/541](url)
The font-weight was fine before the update.
It only appears on non high ppi screens.
Fonts inside the editor are fine.

### Expected behavior

Font shouldn't have diferent font-weights on different screens

### Actual behavior

Fonts are too bold on non high ppi screens

### Environment

PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
Subscription is active until July 20, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

![Bildschirmfoto 2019-04-04 um 09 00 51](https://user-images.githubusercontent.com/23305603/55539844-ef997800-56c1-11e9-9f1b-83af77e208c0.jpg)
![Bildschirmfoto 2019-04-04 um 09 00 09](https://user-images.githubusercontent.com/23305603/55539884-05a73880-56c2-11e9-82e4-8b37a2e156dc.jpg)

**Comment by mallowigi** [comment]
There's something happening with antialiasing, seeing it as well since latest EAP...

Don't really know why this happens, I'll check this for 4.0

**Comment by mikeerickson** [comment]
@mallowigi hmmm, as you can see by his screenshots, his project view appears to have a different background color than "default"  @Yackbz I can't immediately help you fix your issue, but I would surely like to ask how you configured your project view to have a different background color?

As I have asked in other issues, I am not able to figure out how this is set. I have an issue where it looks as expected in some projects, while other projects seem to ignore the setting.

![img1](https://user-images.githubusercontent.com/183153/55675009-0df1a600-5871-11e9-98cd-891ab3d8795e.png)

![img2](https://user-images.githubusercontent.com/183153/55675012-1518b400-5871-11e9-8dcb-abe307811515.png)

**Comment by mikeerickson** [comment]
@Yackbz @mallowigi Looks like my fonts dont have the same issue as you are reporting.  Yet another issues with Material theme doing as it pleases.  Heck, I dont even know where the font attributes are configured.

**Comment by mallowigi** [comment]
Just to be sure, is this behavior happening with the plugin off as well? @Yackbz

**Comment by Yackbz** [comment]
@mallowigi 
It seems like an antialiasing issue. Screenshots from plugin turned on and off are attached.

![1](https://user-images.githubusercontent.com/23305603/55794806-8c935100-5ac6-11e9-846d-c2e2a88f124b.jpg)
![2](https://user-images.githubusercontent.com/23305603/55794807-8c935100-5ac6-11e9-9010-63ee3e6a51e1.jpg)

**Comment by mallowigi** [comment]
In any case I don't think it's related to the plugin. Closing.
