### ISSUE TITLE
Editor colour scheme not being fully applied

### ISSUE THREAD

**Issue by TheLazyHatGuy** [ChrisRM/material-theme-jetbrains#1182]
### Summary
The colour scheme applies to every other aspect of the editor apart from the actual code editor itself.

### Expected behaviour
The theme applies to the entire editor concistently 

### Actual behaviour
The theme applies to everything but the code editor

### Screenshot
![](https://i.imgur.com/oD8sVg1.png)

### Environment
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
Licensed to Cameron Scholes
Subscription is active until January 25, 2020
For educational use only.
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by mallowigi** [comment]
Please read the documentation before opening bugs

**Comment by TheLazyHatGuy** [comment]
> 
> 
> Please read the documentation before opening bugs

I did. Did I miss something?

**Comment by mallowigi** [comment]
There is a troubleshooting section there.

**Comment by TheLazyHatGuy** [comment]
Yeah, but the "troubleshooting" guide doesn't give any indication as to how to make sure that only the Material Darker theme is applied.
It worked before and it works on my other PC, so why all of a sudden has it changed and how do I change it back.

**Comment by TheLazyHatGuy** [comment]
I finally figured it out.
You have to force the theme change by going to `Settings > Editor > Color Scheme > General` and forcing a scheme change.
You should add this to the troubleshooting guide.
