### ISSUE TITLE
Different file explorer background across projects

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#1183]
### Summary

I am seeing an issue where the background color varies across projects and I am not quite sure how this has happened, is this something that I can configure with Material UI theme (I would like them to be the same for all projects

### Expected behavior

I would expect them to be the same, when in fact they are different and I have no idea why, nor can I find the place to change them.

In my case, the `laravel-craftsman` project has the desired apperance (although I have no idea why this one differs from the `vessel-test` project)

![image](https://user-images.githubusercontent.com/183153/55639010-4c0d9d80-577d-11e9-8d26-13bc2e9349b5.png)

![image](https://user-images.githubusercontent.com/183153/55639034-562f9c00-577d-11e9-89ba-0dffa9ca3e54.png)

**Comment by mallowigi** [comment]
This is a bit odd behavior... Can you connect to Slack so we can troubleshoot?

**Comment by mikeerickson** [comment]
@mallowigi Sure, let me track down where I should be connecting on slack.  Is it on your website or something?

**Comment by mikeerickson** [comment]
@mallowigi Which slack channel would you like to discuss this?

**Comment by mikeerickson** [comment]
@mallowigi Further, I live in California, United States so let me know what would be an ideal time to chat so we don't have long delays between messages (as has happened with this thread).

**Comment by mikeerickson** [comment]
@mallowigi Instead of waiting for you to provide me the above information (at this pace, it will be difficult to get things resolved).  Can you simply tell me where and how to configure the project list background color?   It is so random, I can't make heads and tails of it.  Some projects look fine, while others have a different background color.

**Comment by mikeerickson** [comment]
@mallowigi I started a brand new project and it is using the black background.  I start another new project and it has the correct background color, there is no simple pattern that I can see which would cause it to be different.

**Comment by mallowigi** [comment]
You can;t change the background color, but I find it hard to understand the behavior you encounter. It looks like you're using the Oceanic theme, but your project view color is purple like Palenight.

Do you happen to have custom Jetbrains themes installed as well ? Like the Dark Purple or something?

**Comment by mikeerickson** [comment]
Nope, I have customized the editor background the color you see.

So, if you cant change these items, how are they change?

**Comment by mikeerickson** [comment]
My editor is consistent across all projects, and it is to what I have defined for editor background color (and a few other items).  My base theme is Material Oceanic, but it has been tweaked a bit from default.

Regardless, that is not my issue.  It is how does the background in the Project View vary across projects AND how did it get changed if it is not something I did.

**Comment by mallowigi** [comment]
https://join.slack.com/t/material-theme-ui/shared_invite/enQtMzgzNTUxMjQ2MTQ1LWU3Y2ZlYTBlNDEyZmU5YTMzNjAxZjc0NmVkMTk1NzdmNDI1NDAwMzI4NWYxZjVmYzUyYTgwZWEzNjE2YTg2NTA

**Comment by mikeerickson** [comment]
After having a direct conversation on Slack with @mallowigi it was debugged down to this setting in PHPStorm

![image](https://user-images.githubusercontent.com/183153/55676079-28804b00-5882-11e9-8a46-71f267220f7d.png)

So in short, it was NOT an issue with the Material UI theme at all, it was actually a PHPStorm setting causing the confunsion

* Select Appearance | File Colors
* Create an item and assign to `All` and set the desired color

Note: This will override some of the Material UI settings so proceed with caution and make sure it is what you want.  There is no "general" setting to customize just the sidebar (not sure why, but it is what it is).
