### ISSUE TITLE
Simple:  How to set the background color of Project pane

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#1184]
I have a simple question, which seems to be a difficult answer.   

Simply, how do I set the background color of the Project sidebar (Project Tree)

I have hunted high and low trying to find out how to do this, but seeing as I can't find anything, it speaks to the difficulty others must have.

@mallowigi simply stated, that does seem right and that is all I have heard since.  He offered to ask on Slack, but I can't find the slack channel anywhere and he has not responded with where it is located.

**Comment by mallowigi** [comment]
The location of the slack channel is written on the README as well as the documentation website (but you didn't find it, as it seems).

As to answer your question, there is no option to customize the background color of the Project View. The only things you can change is to switch themes, apply the contrast mode or to write a custom theme with the colors you want
