### ISSUE TITLE
Material UI Docs

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#1185]
Does anybody know where the documentation is located, trying to find anything but am not having much success?  I would like to see all the areas which can be customized in the documentation.  Trial and error is very time consuming and confusing.

This is a great project, but a lack of clear documentation makes applying changes a real PITA

**Comment by mallowigi** [comment]
Are you kidding me? The documentation is displayed everywhere:
- In the wizard
- In the Plugins page
- In the README of this repository
- In the Slack channel
- By clicking on the help button in the Material Theme settings

**Comment by mikeerickson** [comment]
@mallowigi nice feedback, no I am not kidding you!

My question is more, how did I get this changed in the project explorer if it cant be modified

**Comment by mikeerickson** [comment]
So, based on your "are you kidding me" response, I should be able to find out how to change the project explorer in one of these places

**Comment by mikeerickson** [comment]
So, I am not kidding you... But I will make my question more specific

"Where can I find documentation on how to customize the sidebar"  I can't find it anywhere

Then your response will be, you can't
Then my response will be "then how did it get changed?"
