### ISSUE TITLE
Plugin Material Theme UI Download or Install failed Pycharm Pro 2019.1.1

### ISSUE THREAD

**Issue by amirhfarzaneh** [ChrisRM/material-theme-jetbrains#1186]
Pycharm Professional Edition 2019.1.1
Ubuntu 18.04.2

I was able to install it last night! But today it fails!

**UPDATE**
fails on Windows 10 too

**Comment by Nothing-Works** [comment]
same for phpstorm

**Comment by martin-luo** [comment]
Same for the Intellij 2019.1

When I tried to install it from the market place, the following error message popped up: `Request failed with status code 404`

Platform:
macOS 10.14.4

**Comment by Fenoman** [comment]
same problem with DataGrip 2019.1

**Comment by mallowigi** [comment]
Will try to reupload later on, but it looks like an issue with jetbrains. You can still download the plugin from the plugin page

**Comment by mikeerickson** [comment]
@mallowigi FYI, I am having the same issue (well, assuming it is the same issue) in macOS w/ PHPStorm

![image](https://user-images.githubusercontent.com/183153/55694689-22fe3000-596a-11e9-81ff-9ae2bcdb028a.png)

**Comment by mikeerickson** [comment]
@mallowigi Just tried installing it manually and all is right in the world.

![image](https://user-images.githubusercontent.com/183153/55694898-247c2800-596b-11e9-93fd-9d81d5fd713d.png)

**Comment by amirhfarzaneh** [comment]
> @mallowigi Just tried installing it manually and all is right in the world.
> 
> ![image](https://user-images.githubusercontent.com/183153/55694898-247c2800-596b-11e9-93fd-9d81d5fd713d.png)

**Comment by martin-luo** [comment]
> Will try to reupload later on, but it looks like an issue with jetbrains. You can still download the plugin from the plugin page

Yes it's true we can download it from the website and then load it into Intellij, unfotrunately, when we restart the IDE, other error messages will show up.

**Comment by mallowigi** [comment]
Ok I've tried twice and it still doesnt work. It is definitely a problem from Jetbrains. I'll contact them sooner or later.

**Comment by chrisaligent** [comment]
Funnily enough, when I copy the URL which 404'd into my browser, it downloads the file right away (which I can then install via the UI). Very weird!

**Comment by zazido** [comment]
Same for Webstorm 2019.1

Temporary workaround here:

1. manually download latest version from [Jetbrains plugins page](https://plugins.jetbrains.com/plugin/8006-material-theme-ui)
2. uninstall old version from `IDE/preference/plugins`
3. select "Install Plugin from Disk"

![image](https://user-images.githubusercontent.com/1901146/55701027-378f0680-5a04-11e9-838e-54503a9cc0f0.png)

**Comment by anyuxuan** [comment]
Same with Webstorm 2019.1
I uninstalled it
finally, I cannot install it anyway.

**Comment by relloyd** [comment]
Same here for Goland 2019.1.

**Comment by thebedroomprogrammer** [comment]
Facing the similar issue with Goland

**Comment by BryanMootoosamy** [comment]
same issue with PhpStorm 2019.1

**Comment by mallowigi** [comment]
Please follow status there: https://youtrack.jetbrains.com/issue/MP-2197

**Comment by mallowigi** [comment]
Ok, it works now.

**Comment by amirhfarzaneh** [comment]
@mallowigi Thanks for attending to this :-)
