### ISSUE TITLE
404 on attempt to update plugin

### ISSUE THREAD

**Issue by edclement** [ChrisRM/material-theme-jetbrains#1187]
Attempting to update the plugin in webstorm 2019.1 results in a 404 not found. See screenshot:
![image](https://user-images.githubusercontent.com/5667395/55722509-84f37f80-59d4-11e9-991a-6edb6eca2304.png)

**Comment by edclement** [comment]
...same in intelliJ community edition 2019.1:
![image](https://user-images.githubusercontent.com/5667395/55722590-b53b1e00-59d4-11e9-8b8a-c07031f65a04.png)

**Comment by Goazil** [comment]
Every jetbrains IDE has 404 error :/

**Comment by aenciso** [comment]
And ultimate
![image](https://user-images.githubusercontent.com/3810819/55724250-eaf6fb80-5a02-11e9-8a7c-6db16fc3f8fc.png)

**Comment by NeerajJadhav** [comment]
And PHPStorm
![image](https://user-images.githubusercontent.com/13821977/55724556-aacf5300-59d9-11e9-8270-30c121c6c917.png)

**Comment by linaori** [comment]
@mallowigi I see you've closed this issue, but I still can't install the material theme. I've just reinstalled my OS and thus intelliji, but it still gives a 404 on this particular plugin, also did before reinstalling my OS. What's the solution to install it?

**Comment by mallowigi** [comment]
It's because its a duplicate, go on the other thread.

**Comment by linaori** [comment]
Heya, thanks for your reply! I found it by now, but it's a bit difficult to know which thread if it's not linked. When you put the issue number in the thread when closing, people will know why it's closed and where to look.

**Comment by kstratis** [comment]
@mallowigi Which one is the "other thread"?

**Comment by linaori** [comment]
The Issue name is a bit cryptic, hence I didn't find it at first. You can find the other issue here: #1186
