### ISSUE TITLE
Support custom themes

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#1190]
e.g. support having the custom themes while still keeping the Material Theme features and settings such as the components or compactness.

Probably need to refactor :'(

**Comment by sriharshachilakapati** [comment]
I'm having a similar issue as @mallowigi here. I want to keep using the Material Darker UI theme. However I just want to change the editor theme (color scheme) to my own port of Ayu Dark. Every time I restart the IDE, the colour scheme is being reset to Material Darker. I now have to keep enabling this each and every time.

**Comment by mallowigi** [comment]
Have you tried on version 3.9.0.3? This should not happen there

**Comment by sriharshachilakapati** [comment]
Yes, tried the update now, it was working great! Thanks a lot!!

**Comment by clnt** [comment]
@mallowigi This still seems to be happening for me, setup a modified Material Darker theme earlier and it keeps resetting the code colour scheme to "Material Darker' whenever I restart PhpStorm.

**Comment by mallowigi** [comment]
For the sake of simplicity, I will not work on this feature. If you want custom themes, please download them and remove the MT.

I will try to send PRs to theme authors to make them implement their themes using the custom theme API.
