### ISSUE TITLE
Oscillatory behavior of side-by-side editor views when smooth scrolling enabled

### ISSUE THREAD

**Issue by rulatir** [ChrisRM/material-theme-jetbrains#1191]
### Summary

When smooth scrolling is enabled, side-by-side code views like Local History exhibit oscillatory behavior when scrolled.

### Expected behavior

Scrolling should work steadily.

### Actual behavior

Scroll position of both panes oscillates wildly with ~8Hz frequency on my machine.

### Steps to reproduce (if needed)

1. Open a file that is several screens long
2. Make some edits that delete lines and some edits that insert lines
3. Context menu -> Local history -> Show history, scroll to get some differences into view

### Environment

PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.6-arch1-1-ARCH

Material Theme UI v3.9.0.2
```
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="settingsSelectedTab" value="3" />
    <option name="accentColor" value="80cbc4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="selectedTheme" value="DEEPOCEAN" />
    <option name="userId" value="44522e0b:1662b53ef83:-8000" />
    <option name="version" value="3.8.0.2" />
  </component>
</application>
```
(I note the version mismatch between plugin and config; unsure what the significance of this is)

I suspect that the quasi-physics of smooth scrolling is implemented as something resembling an overdamped harmonic oscillator, but the additional "spring factor" involved in maintaining relative positions of highlighted differences makes the oscillator no longer overdamped.

P.S. https://www.youtube.com/watch?v=010KyIQjkTk

**Comment by mallowigi** [comment]
I don't see how is it related to the plugin except for performance issues. Have you tried turning off the plugin and see if the behavior still happens?

**Comment by mallowigi** [comment]
Can you show a video perhaps?

**Comment by rulatir** [comment]
Indeed it is unrelated to the plugin. Will report upstream. I seemed to remember that I had once done the check without the plugin and it was OK, but I must have been mistaken.

**Comment by mallowigi** [comment]
At least I learned about the smooth scroll ;0
