### ISSUE TITLE
[Question] How to change the color of special symbols in editor?

### ISSUE THREAD

**Issue by YuryScherbakov** [ChrisRM/material-theme-jetbrains#1193]
Since version 3.9.0 we have a new color schema and I want to revert the color of whitespace symbols, but I can't find such configuration.

![Clip2net_190409104455](https://user-images.githubusercontent.com/9347932/55782561-3a95ff80-5ab5-11e9-94f8-401ece43f544.png)

**Comment by mallowigi** [comment]
Color Scheme > General > Whitespaces
