### ISSUE TITLE
UI elements such as the project view and toolbar reset to darcula randomly after relaunching IntelliJ

### ISSUE THREAD

**Issue by uglyluigi** [ChrisRM/material-theme-jetbrains#1196]
Upon restarting IntelliJ and plugins synching, all UI elements besides the editor, gutter, and tabs reset to the Darcula theme until I re-select my custom theme (this also happened with all of the default themes). The material icons persist but the coloration resets to Darcula randomly on the UI elements I mentioned.

Material Theme UI version: 3.9.0.3
IntelliJ version: Ultimate 2019.1

This happens on both installations I sync plugins on. I'm using the JetBrains account plugin sync, not a settings repository.
![Capture](https://user-images.githubusercontent.com/5006946/55823950-74bccc80-5ac8-11e9-9c51-f247b6b928bf.JPG)

**Comment by mallowigi** [comment]
Does this happen with the latest release only or is it happening with previous release (like 3.8?)

**Comment by uglyluigi** [comment]
It's been happening since I installed it (4-5 days ago), during which period I think I updated it 3 times. So the current release on the marketplace (3.9.0.1) and the two previous versions, at least. This also occurred when I installed MTUI on IntelliJ Ultimate 2018.3. The only other plugins I have installed are the Rust language support plugin, Rainbow Brackets, and Key Promoter X, if that matters, but I don't have any other theming plugins installed, so I'm unsure if there's any incompatibility.

**Comment by uglyluigi** [comment]
I'd also like to mention that when this happens, the theme appears to apply correctly on startup and looks normal for a few moments, then some sort of update seems to occur that changes everything except the editor/tabs/gutter to the darcula theme.

**Comment by clnt** [comment]
Hey, I just put a tweet out to PhpStorm regarding this: https://twitter.com/mattclinton8/status/1115894788535013376 

It started with 2019.1 for me, and I think it is related to the IDE settings sync (which makes sense with the above comment from @uglyluigi about the delay). When this happens you cannot select the Material Theme from the dropdown on the Appearance page:
![Screen Shot 2019-04-10 at 10 04 29](https://user-images.githubusercontent.com/19330442/55866580-8f4e7e80-5b78-11e9-944f-b07e6f28793e.png)

This morning I have updated the plugin (which fixes the problem making the theme work), but doesn't fix that dropdown. I then tried reinstalling the plugin but that doesn't fix that dropdown either.

Possibly setting sync is applying the value of the Theme dropdown on startup.

**Comment by uglyluigi** [comment]
I tested another case today that makes me believe it's a plugin sync issue, because I left the IntelliJ instance on my desktop open all day with the material theme properly applied. I just logged back into my computer without restarting IntelliJ and it changed to a state like the image I posted in my OP after a few seconds; my laptop will probably follow suit. 

I no longer think this is a plugin sync problem, though, because after restarting IntelliJ once it improperly applies the darcula theme, the theme is properly applied. Perhaps when MTUI detects a configuration change over the plugin sync, it's using some weird default value and not the information present in the actual configuration. I will update here if I come across any more information that helps narrow the cause down.

**Comment by mallowigi** [comment]
So it’s an issue with the IDE Settings Sync?

**Comment by clnt** [comment]
> So it’s an issue with the IDE Settings Sync?

Possibly, but I think its related to the plugin as the theme should be showing properly in that theme dropdown.

**Comment by mallowigi** [comment]
It should not (yet). The Theme dropdown is only for IntelliJ based themes, and the Material Theme themes are using a different implementation, named the theme switcher.

I have plans to implement this in the future but for now it's not the case.

If it's an issue with the sync it's not solvable at the moment.

**Comment by clnt** [comment]
@mallowigi I think this issue is now resolved, did you implement the theme switcher? I was having issues still until I looked at the theme dropdown again which had all the different themes showing:

![Screen Shot 2019-05-03 at 09 16 11](https://user-images.githubusercontent.com/19330442/57126321-83736800-6d84-11e9-9d3f-4dfc6bf68db5.png)

When I selected Material Oceanic and then restarted PhpStorm everything was fine, I had to set my code color scheme again but it seems to have resolved it. This was 2 days ago and so far it hasn't happened again, usually it happens every time I open it in the morning.

**Comment by uglyluigi** [comment]
I can confirm this problem is resolved when selecting themes from the theme dropdown, but the problem still persists with the Custom Theme option. I've switched to using Material Darker for now so I don't suppose I'll have this problem again.
