### ISSUE TITLE
Material Oceanic default font changed from Fira Code to Monospaced in 3.9

### ISSUE THREAD

**Issue by bdurkovic** [ChrisRM/material-theme-jetbrains#1197]
### Summary

After the update Matierial Oceanic theme font is Monospaced

### Expected behavior

Material Oceanic default font is Fira Code.

### Actual behavior

Material Oceanic default font is Monospaced.

### Environment

PhpStorm 2019.1
Build #PS-191.6183.95, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

material_theme.xml
```
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="settingsSelectedTab" value="5" />
    <option name="accentColor" value="009688" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="61d1532d:16914b76536:-8000" />
    <option name="version" value="3.9.0.2" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I switched from Fira Code to Menlo as it is better rendered, but I forgot that it's not available on Windows...

I'll add it back as a fallback

**Comment by bdurkovic** [comment]
Thanks for the fix and for the awesome plugin! :)
