### ISSUE TITLE
Strange background for One Dark Theme

### ISSUE THREAD

**Issue by Luladjiev** [ChrisRM/material-theme-jetbrains#1198]
### Summary

One Dark Theme has a strange background. It differs from the original Atom theme. Also differs from material theme website showcase.

### Expected behavior

Example of Atom One Dark theme:
![image](https://user-images.githubusercontent.com/4628170/55867712-b06c9a80-5b8b-11e9-9db3-327810a3cd96.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/4628170/55867428-2290af80-5b8b-11e9-8e65-3996af3a53df.png)

### Environment

WebStorm 2019.1
Build #WS-191.6183.63, built on March 21, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
OpenSUSE Linux 5.0.5-1-default
Plugin version: v3.9.0.3
Default theme settings (I've just deleted my config folder)

**Comment by mallowigi** [comment]
Hmmm true... I remember doing that because it looked darker on VSCode, but now that I see it again it is the same color as in atom (282c34)...

I'll fix this for next release

**Comment by Luladjiev** [comment]
@mallowigi does that means that you are going to swap the colors of whole IDE (23262D) and Text background (282c34) to be similar to Atom, or just setting Text Background with color 282c34?

**Comment by mallowigi** [comment]
It will be for the color scheme, setting back to 282c34. Theme won't change
