### ISSUE TITLE
Any plan to materialize Jupyter tab on Pycharm > 2019.1?

### ISSUE THREAD

**Issue by amirhfarzaneh** [ChrisRM/material-theme-jetbrains#1204]
Currently, the Jupyter preview tab and the editor are not consistent theme-wise!
![Screenshot from 2019-04-11 15-52-54](https://user-images.githubusercontent.com/9829572/55995565-0ddb1700-5c72-11e9-85bb-e287c1884592.png)

**Comment by mallowigi** [comment]
Unfortunately this is not something themeable, it's like the Markdown editor preview

You can easily see it when applying a custom theme such as Dark Purple.

You can open an issue request at Jetbrains's YouTrack
