### ISSUE TITLE
File Status Highlights

### ISSUE THREAD

**Issue by pepela** [ChrisRM/material-theme-jetbrains#1207]
Android studio lost File Status Highlights, even after unisntalling. Colors are set but edit does not display them

![Color scheme for VCS](https://user-images.githubusercontent.com/4414460/56367256-88b9aa00-61fd-11e9-98cd-438241041211.png)

I removed icls files as stated [here](https://github.com/ChrisRM/material-theme-jetbrains#material-status-file-colors)

**Comment by mallowigi** [comment]
Settings>Editor>General>Highlight modified lines in gutter
