### ISSUE TITLE
Support eslint icon for alternative extensions

### ISSUE THREAD

**Issue by onrige** [ChrisRM/material-theme-jetbrains#1208]
Hello. Could you please add icon support for other eslint extensions? (not only `.eslintrc`)

Thanks.

**Comment by mallowigi** [comment]
What are they?

**Comment by onrige** [comment]
According to the [docs](https://eslint.org/docs/user-guide/configuring#configuration-file-formats): `js`, `yaml`, `yml` and `json`.

**Comment by onrige** [comment]
Also there are no icon associations for [semantic-release](https://github.com/semantic-release/semantic-release), [commitlint](https://github.com/conventional-changelog/commitlint) and [husky](https://github.com/typicode/husky).

**Comment by mallowigi** [comment]
Can you do a pull request?

**Comment by onrige** [comment]
Sure. Already in progress.
