### ISSUE TITLE
Colors is not customizable in my IDE

### ISSUE THREAD

**Issue by Pum-purum** [ChrisRM/material-theme-jetbrains#1209]
I want to customize colors in PHPStorm 2019.1.1, but this is not working anymore http://joxi.ru/MAjBVaMTj1Yj4A

**Comment by mallowigi** [comment]
What do you mean customize colors? Can you elaborate?

**Comment by Pum-purum** [comment]
See them on screenshot please. Arrows notices, what color/style must be, and what the one actually is.

**Comment by mallowigi** [comment]
It looks like an issue with PHPStorm. Can you try without the theme enabled and tell me if it happens ?
