### ISSUE TITLE
Java icons and font color in Android Studio

### ISSUE THREAD

**Issue by AcoustickSan** [ChrisRM/material-theme-jetbrains#121]
At start all ok! But after indexing project java icons replacing to *
![2015-11-18 11 07 23](https://cloud.githubusercontent.com/assets/2283454/11233148/de1f49aa-8de4-11e5-9081-b20767cd90e1.png)
And one a little font color bug
![2015-11-18 11 11 58](https://cloud.githubusercontent.com/assets/2283454/11233186/3f0f1920-8de5-11e5-9202-004676d9a524.png)

**Comment by CandySunPlus** [comment]
+1, also in intelliJ IDEA

**Comment by nishtahir** [comment]
Confirmed in IDEA 15

**Comment by redarqas** [comment]
IDEA 15

**Comment by vivitarjos** [comment]
IDEA 2016
