### ISSUE TITLE
Plugin not compatible with PyCharm Community edition 2018.3

### ISSUE THREAD

**Issue by lefuturiste** [ChrisRM/material-theme-jetbrains#1210]
When I want to install the plugin via the marketplace or via the zip directly with the correct the support on PyCharm. I can't manage to install it. I have a error:

![](https://i.imgur.com/j8bQ8Ai.png)

### Environment

PyCharm 2018.3.5 (Community Edition)
Build #PC-183.5912.18, built on March 5, 2019
JRE: 10.0.2+13 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 5.0.2-arch1-1-ARCH

**Comment by mallowigi** [comment]
Just tried on 2018.3.6 from the Marketplace with no issues.
