### ISSUE TITLE
The kotlin icon is terrible

### ISSUE THREAD

**Issue by Xetera** [ChrisRM/material-theme-jetbrains#1213]
Maybe you guys disagree but the current icon for Kotlin: <img src="https://raw.githubusercontent.com/ChrisRM/material-theme-jetbrains/master/src/main/resources/icons/files/kotlin.svg?sanitize=true">  looks hideous to me.

I think it would look a lot better if it was <img src="https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin-logo.svg" width="16">. I'd be happy to submit a PR for that change as well, just wanted to make sure you're OK with getting icon change PRs. 👀

**Comment by mallowigi** [comment]
I know but I can’t seem to find a svg for it. If you have one of make one be my guest and submit a PR.

**Comment by mallowigi** [comment]
Any news?

**Comment by Xetera** [comment]
I managed to find a fitting svg for it but I haven't had any luck building the project. It's the right dimension and everything, should I go ahead and just do a PR anyway?

**Comment by mallowigi** [comment]
Alright I managed to do it. See it in 3.9.3
