### ISSUE TITLE
Button alignment

### ISSUE THREAD

**Issue by NSLogName** [ChrisRM/material-theme-jetbrains#1214]
![image](https://user-images.githubusercontent.com/20921512/56545248-937f9080-65a9-11e9-932f-8f4f6f7720d4.png)

I found a problem that the buttons were not aligned.
OS: Mac
IDE: Intellij IDEA 2019.1.1
Plugin: Material Theme UI 3.9.1

**Comment by mallowigi** [comment]
I see that but there's nothing I can do. I can only control the appearance, not their position.
