### ISSUE TITLE
Themed Title Bar is no longer working for PyCharm

### ISSUE THREAD

**Issue by golimpio** [ChrisRM/material-theme-jetbrains#1216]
### Summary

_Themed Title Bar_ option is no longer working for PyCharm, nothing happens when checking this option.

### Expected behavior

When checking the _"Themed Title Bar"_ option, the title bar should have the same color as the theme: [the title bar should be completely transparent, and therefore take the same color as the current theme](http://www.material-theme.com/blog/whats-new-in-2-5/#themed-title-bar-for-macs).

### Actual behavior

When the _"Themed Title Bar"_ option is selected, nothing is changed, the default MacOS title bar is still being displayed.

### Steps to reproduce (if needed)

1. Open PyCharm
2. Try to select _"Themed Title Bar"_ on: `Preferences` > `Appearance & Behaviour` > `Material Theme` > `Other Tweaks`

### Environment

I have updated PyCharm to the latest version, but it wasn't working on the previous version as well.

Current version:
```
PyCharm 2019.1.2 Preview (Community Edition)
Build #PC-191.7141.11, built on April 25, 2019
JRE: 11.0.2+9-b159.46 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
```

**Comment by golimpio** [comment]
Note: the current theme I have set is _Solarized Light_

**Comment by mallowigi** [comment]
It looks like something broke with PyCharm, unfortunately I can't debug why at the moment...

**Comment by mallowigi** [comment]
They dropped the transparent title bar for JRE 11 ................
