### ISSUE TITLE
when loading all white?

### ISSUE THREAD

**Issue by aoeng** [ChrisRM/material-theme-jetbrains#1217]
![image](https://user-images.githubusercontent.com/23565714/56875279-523c2480-6a72-11e9-98b5-8496503437f2.png)

All new versions!
oceanic theme!
why?

**Comment by mallowigi** [comment]
What is your current look and feel ? (Settings > Appearance > Look and Feel) ?

**Comment by ekvedaras** [comment]
I have the same thing. When you freshly open PhpStorm it shows white background until it loads the workspace. When using dark mode this really burns your eyes :) To answer the question above I have Darcula set as look and feel.

**Comment by mallowigi** [comment]
I know this, this only happens on Windows. I don't have Windows though so I can't help at the moment.

**Comment by ekvedaras** [comment]
I have this issue on Linux. However, just checked on OSX and its working fine there. I wonder what that is. Can I help somehow though? Some additional info maybe needed? Is there a way I could try to fix it myself? Although that would be a challenge for me :))

**Comment by mallowigi** [comment]
I think it's related to a method called "patchGray" or something like that, in UIReplacer.

**Comment by bvalyou** [comment]
I have this (MacOS) where every time I open a project it comes up blank with the Oceanic background color until I drag the window. I just uninstalled/reinstalled the plugin and it didn't happen without and did happen with. I'm seeing it in both WebStorm and IntelliJ.

**Comment by ekvedaras** [comment]
This sounds like another issues that was also happening to me some time ago but it seems to be solved. Make sure your editor and the plug-in is up to date

**Comment by lllopo** [comment]
I also can confirm this on Windows (latest versions of everything), plus a weird double progress window while project is loading. Really a BSOD (bright screen of death ;-)) :

![Untitled](https://user-images.githubusercontent.com/5485902/70860967-b132a900-1f30-11ea-9ce6-a7a9cf348da9.png)

**Comment by mallowigi** [comment]
fixed
