### ISSUE TITLE
Themed Title Bar is no longer working for JRE 11

### ISSUE THREAD

**Issue by golimpio** [ChrisRM/material-theme-jetbrains#1218]
See issue #1216 for more information.

According with the information posted on #1216, they dropped the transparent title bar for JRE 11. Once JetBrains starts to update the embedded JRE for their IDEs, this option (themed title bar) will stop to work for all JetBrains IDE.

My suggestion is to check the JRE version (e.g. `System.getProperty("java.version")`) and then hide the checkbox when the JRE is `11` or bigger.

IMO, leaving the _"Themed Title Bar"_ checkbox there might lead some users (like myself) to think that this is a bug on the _Material Theme_ side, generating unnecessary bug reporting.

**Comment by mallowigi** [comment]
You’re right, I’ll try to check if there’s a method to check the current jre and disable the checkbox in this case. I’ve also created an issue in YouTrack, hoping that they will implement it there as well.

**Comment by mallowigi** [comment]
Fixed in 3.9.4

**Comment by wee911** [comment]
> Fixed in 3.9.4

in 3.10.0 , it's not working again

**Comment by mallowigi** [comment]
What’s fixed is the disabledness of the feature

**Comment by SeanBerce** [comment]
@mallowigi I just updated to phpstorm 2019.2.3 mac. The "Themed Title Bar" checkbox is checked and disabled so I cannot implement the workaround from this issue that was referenced in 4.2 version history. [https://youtrack.jetbrains.com/issue/IDEA-219015](https://youtrack.jetbrains.com/issue/IDEA-219015)
![image](https://user-images.githubusercontent.com/15696235/67100977-bcff2a80-f18e-11e9-8ee5-0389af19f3d3.png)

Is there a workaround to disable this feature without use of this checkbox?

**Comment by mallowigi** [comment]
Please update to latest version.
