### ISSUE TITLE
The UI is unstable and finally crashes when using light themes 

### ISSUE THREAD

**Issue by jeugeneDS** [ChrisRM/material-theme-jetbrains#1219]
> 
> ### Summary
> 
> Since version 3.9.3 WebStorm is unstable and finally unusable when using light themes (Material Lighter, Atom One Light and Solarized Light) if the parameter `File icons` is enabled and SVG files are displayed in the Project panel.
> 
> ### Expected behavior
> 
> No crash using light themes in all cases
> 
> ### Actual behavior
> 
> WebStorm is unstable and finally unusable in some conditions.
> 
> ### Steps to reproduce (if needed)
> These conditions must be filled:
> - use a light theme
> - enable the setting `File icons` in `Appareance & Behavior` > `Material Theme` > `Icons tabs`. Obviously the setting `Hide File Icon` must be disabled.
> - SVG file is present in the project.
> 
> 1. Set a light Theme (like `Material Lighter`)
> 
> 2. Open a folder where a SVG file is present => Instead of the icon + name of an file we have a blue rectangle.
![ui-unstable](https://user-images.githubusercontent.com/22612242/57017847-42af0e00-6c21-11e9-8479-f764bd3aa808.PNG)
> 
> 3. Click on this rectangle to open the svg => the UI crashed. You have to restart the IDE.
![ui-crashed](https://user-images.githubusercontent.com/22612242/57017859-4d69a300-6c21-11e9-9545-0c4bd14395cd.PNG)
> 
> 4. Disable the setting `File icons` / choose a dark theme => The problem has disappeared.
> 
> ### Environment
> 
>     * Windows 10 1803
> 
>     * WebStorm 2019.1.1
>       
>       * Build #WS-191.6707.60, built on April 16, 2019
> 
>     * Material Theme UI 3.9.3

**Comment by mallowigi** [comment]
Can you show me which plugins you have currently ?

**Comment by mallowigi** [comment]
@jeugeneDS

**Comment by jeugeneDS** [comment]
@mallowigi The only two plug-ins I have downloaded are Material UI and Save Actions.
The others are plugins installed by default.
![Capture](https://user-images.githubusercontent.com/22612242/57027036-92023800-6c3b-11e9-95c4-9f7788426679.PNG)

**Comment by egorzekov** [comment]
Same issue after updating Material-UI this morning.

@mallowigi any info I can provide you?

**Comment by mallowigi** [comment]
I'm not able to reproduce, sadly. Is it happening with previous versions as well ?

**Comment by jeugeneDS** [comment]
I did a fresh install of Webstorm and Material UI 3.9.3 on another PC. The default settings being used; new project. It's 100% reproducible.
This is not reproducible on the 3.9.2.
When the UI freeeze before to display the blue rectangle a new folder **threadDumps-freeze** is created in system/log. I don't know if that can help.
[threadDumps-freeze-20190505-020022-WS-191.7141.24-17sec.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3145262/threadDumps-freeze-20190505-020022-WS-191.7141.24-17sec.zip)

**Comment by egorzekov** [comment]
Hello @mallowigi.

I didn't happen before the latest update. The problem usually occurs for me when I open a folder in Navigator which has `svg` file inside:
![image](https://user-images.githubusercontent.com/17830199/57191886-1f42d680-6f33-11e9-9816-df180962bb3b.png)

It seems that the strange image located instead of `filename.svg` is the part of your logo or something like that.

**Comment by mallowigi** [comment]
I still can't reproduce. Can you send me the svg file, maybe there's a connection to it ?

**Comment by mallowigi** [comment]
Reproduced on a fresh install. Investigaitng

**Comment by mallowigi** [comment]
Ok it's fixed. I don't know what happened, it looks like the version has been corrupted for some reason. Just redeployed now and it looks ok.

**Comment by jeugeneDS** [comment]
Excellent! Thank you for your work and your reactivity.

**Comment by egorzekov** [comment]
Yeah, it works properly after the update.

Thanks a lot @mallowigi!
