### ISSUE TITLE
Cmd+click (go to declaration) partially works

### ISSUE THREAD

**Issue by disljenko** [ChrisRM/material-theme-jetbrains#1220]
Using PhpStorm and Laravel framework and after i installed This theme i lost ability to use (go to declaration) just for my routes inside web.php file. When i press cmd+click doesn't recognize as clickable link. This is only true when i want to jump to my Controller/function, all other Classes, etc works just fine. When i disable Material Theme Plugin everything just works fine. 

    Route::post('kep/dl13/dashboard', 'KepApiController@dl13Dashboard');

### Environment

PhpStorm 2019.1.1
Build #PS-191.6707.66, built on April 17, 2019
JRE: 1.8.0_202-release-1483-b44 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
Material Theme Plugin version: 3.9.3

**Comment by mallowigi** [comment]
To reproduce I need to understand which kind of PHP framework are you using

**Comment by mallowigi** [comment]
Which plugins are you using?

I tried to reproduce without the plugin and they are not clickable...

**Comment by disljenko** [comment]
I'm using php Laravel framework  and list of installed plugins are:
[https://www.screencast.com/t/UeSc3tTyyU](https://www.screencast.com/t/UeSc3tTyyU)

Laravel Plugin gives that ability but once Material Theme plugin is enabled that feature disappears. Like it has been overwritten by it.
