### ISSUE TITLE
It turned my persian comments into gibberish

### ISSUE THREAD

**Issue by hossmf** [ChrisRM/material-theme-jetbrains#1221]
### Summary

writing comment in Persian is not possible while writing as code have no problem not to say it is prohibited by Java
![image](https://user-images.githubusercontent.com/14359326/57062210-c4ac3f00-6cd4-11e9-9208-46b7cbe03049.png)

### Expected behavior

the comment should look like as is!

### Actual behavior

Commenting in Persian becomes gibberish while uncommenting that same text will make it readable

### Steps to reproduce

1. Write some comment in Persian or Arabic
2. The comment inside the parenthesis is unreadable:
![image](https://user-images.githubusercontent.com/14359326/57062063-55cee600-6cd4-11e9-8a06-20f9b7abf9f3.png)

### Environment

IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
Subscription is active until February 18, 2020
JRE: 11.0.2+9-b159.44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Material Theme v3.9.3**
`<application>
  <component name="MaterialThemeConfig">
    <option name="compactDropdowns" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="tabsHeight" value="32" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="651dc3b3:16a77776839:-8000" />
    <option name="version" value="3.9.3" />
  </component>
</application>`

**Comment by mallowigi** [comment]
Looks like a problem with the editor font. Which editor font do you use?

**Comment by hossmf** [comment]
I didn't change the defaults

**Comment by mallowigi** [comment]
Then go to settings > editor > color scheme > Color scheme font

**Comment by hossmf** [comment]
![image](https://user-images.githubusercontent.com/14359326/57063799-aeed4880-6cd9-11e9-9bc8-971148bddcff.png)

**Comment by mallowigi** [comment]
I am not able to reproduce, neither on Windows nor Mac. Can you make sure that it happens only with the plugin on?

**Comment by hossmf** [comment]
Here's the same comment without the plugin installed. Notice that I removed IntelliJ for getting back everything to their defaults and Material theme is the only plugin that I have. the problem appears as soon as I install the plugin and restart my intellij. and the other noticeable thing is at this time even uninstalling the plugin doesn't help and the only solution is removing the Idea user folder.
![image](https://user-images.githubusercontent.com/14359326/57181674-0c38f380-6eac-11e9-9eba-af1ac83defa0.png)

**Comment by hossmf** [comment]
> 
> 
> I am not able to reproduce, neither on Windows nor Mac. Can you make sure that it happens only with the plugin on?

do you have Persian keyboard? 🤔 that's superb!

**Comment by mallowigi** [comment]
Can you update to the latest version? I found out that the last version (3.9.3) has been sort of corrupted, so maybe your issue is related to this as well.

**Comment by hossmf** [comment]
I downloaded v3.9.3.1 and I got the same result.

**Comment by hossmf** [comment]
I uninstalled intelliJ+JBR11 and installed the normal intelliJ and the problem fixed! I think there is a compatibility issue with your plugin and JBR11.

**Comment by mallowigi** [comment]
Hmmm okay thanks for the heads up, I’ll check what I can do .

**Comment by borookner** [comment]
به نظر من این مشکل به دلیل فونت مونواسپیس است، چون خاصیت این فونت‌ها یکسان نوشتن تمام حروف در زبان‌های لاتین است. اما در زبان فارسی به دلیل پیوسته نویسی این قابلیت معنا ندارد. بنابراین پیشنهاد من این است که به تنظیمات برنامه بروید و برای حالت‌هایی که فونت مونواسپیس ساپورت نمی‌کند مثل زبان فارسی یا بعضی سیمبل‌هایی که در یک فونت بخصوص وجود دارد مانند تصویر زیر عمل کنید:

![image](https://user-images.githubusercontent.com/17924562/68567747-0c273b00-046f-11ea-9024-e0279fa80be8.png)

در بخش تنظیمات به مسیر زیر بروید و فونتی را برای آن تعیین کنید:
Editor>Font  ->  Fallback font
برای این فونت یک فونت فارسی مناسب در نظر بگیرید
