### ISSUE TITLE
[Question] How to change `Usage of` popup font size?

### ISSUE THREAD

**Issue by ltpquang** [ChrisRM/material-theme-jetbrains#1222]
![image](https://user-images.githubusercontent.com/4617357/57119818-3ea4fc80-6d97-11e9-98a7-4446de4e7568.png)

The title of `Usage of` popup dialog is quite big to me, it was not that before. Can I change this font size?

**Comment by mallowigi** [comment]
Nope. It’s one of the few settings that are not customizable, sorry :(

**Comment by ltpquang** [comment]
That's sad, but thank you for answering :(
