### ISSUE TITLE
text selection highlight is invisible in webstorm in solarized light

### ISSUE THREAD

**Issue by joysword** [ChrisRM/material-theme-jetbrains#1226]
### Summary

Solarized Light selected text has the same background color as current line, which essentially makes the selection invisible.

### Expected behavior

In Solarized Light, selected text should be highlighted with a different background color from the one that highlights current line.

### Actual behavior

In Solarized Light, selected text is highlighted with the same color as the background color of current line.

### Steps to reproduce (if needed)

1. use Solarized Light theme
2. open a file and move mouse to a line with plenty of text (for best result)
3. use mouse or keyboard to select some text of that line
4. there's no visual cue for the selection because the color is the same as the background of current line

![image](https://user-images.githubusercontent.com/1168623/57309688-20e4d980-70ae-11e9-8740-fb2b4516b7b4.png)

(note that in this screenshot I actually selected the whole line of the opening div tag)

### Environment

About:

```
WebStorm 2019.1.1
Build #WS-191.6707.60, built on April 16, 2019
Licensed to OP
Subscription is active until some time in the future
For educational use only
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

Material Theme Plugin version: 3.9.3

Configuration:

```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="customSidebarHeight" value="22" />
    <option name="indicatorThickness" value="4" />
    <option name="accentColor" value="d33682" />
    <option name="selectedTheme" value="SOLARIZED_LIGHT" />
    <option name="userId" value="f0f37e0:167c7df4b78:-8000" />
    <option name="version" value="3.9.0.3" />
  </component>
</application>
```

Notes:

* I was able to reproduce this bug in macOS with the same version of WebStorm.
* I was NOT able to reproduce this bug in PyCharm Pro (mac and windows)

**Comment by mallowigi** [comment]
Please reset your color schemes in Settings > Editor > Color Scheme

**Comment by joysword** [comment]
Cool. This not only fixed the selection highlighting, but also fixed some other weird highlighting colors for me. No idea when and how the colors went wild/non-default.

Thanks Elior.

**Comment by mallowigi** [comment]
Usually it’s when some plugins (mine included) adds new colors upon installation, causing the color schemes to be “dirty”. There’s no fix for that, just be aware I reset the color schemes at every update
