### ISSUE TITLE
Change background of editor

### ISSUE THREAD

**Issue by florisvanwoudenberg** [ChrisRM/material-theme-jetbrains#123]
Hi,

Maybe this can be done in the config, but I can not find where:

When no file is opened, I see a dark-grey background that I want to adjust to something like the editor default text background. Can you do this in the theme or can I do this by myself?

**Comment by ChrisRM** [comment]
I'll see what I can do. It's not an option in the settings as far as I know.

**Comment by mallowigi** [comment]
It's another hardcoded color (thanks Jetbrains...), but tbh I like this dark grey background :)

Maybe I'll make it configurable
