### ISSUE TITLE
Add setting to unify icon colors

### ISSUE THREAD

**Issue by sebastiaanluca** [ChrisRM/material-theme-jetbrains#1231]
I've enabled Material UI icons, file icons, and PSI icons, and enabled monochrome icons, but as you can see in the screenshot, there's still some variance in icon color. Source, resource, and excluded directories get a more highlighted icon. File icons vary, some white, some gray, some material theme colored.

Is there a way to make them *all* the same color? Regardless of file or directory, or directory type. Would be great if we could change that color too, so they can be faded into the background more. Matching them with the file/directory color would be cool too (i.e. displaying version control status via color).

Thanks!

![Screenshot 2019-05-10 at 13 20 34](https://user-images.githubusercontent.com/711940/57523894-893df000-7326-11e9-9bab-3086dc91efb0.png)

**Comment by mallowigi** [comment]
Ermmm I don’t think it’s possible. The monochrome setting is actually a black and white filter removing all saturation and applying a certain tint (usually the theme’s primary text color), but then, a non saturated red would not look like a non saturated yellow or green, which is what you’re seeing.

The only way to do what you want would be to completely disable folder icons except for the regular icon, and it can not be done without refactoring everything.

If you want you can fork the project so you can replace all folder icons to have the same color. I can easily guide you once you have an environment running.
