### ISSUE TITLE
Undesirable button background when legacy design components are used

### ISSUE THREAD

**Issue by xplwowi** [ChrisRM/material-theme-jetbrains#1232]
### Summary

Buttons have ugly background when "Material design components" are unchecked. 
I'm using this mode because I choose better readability (IMO) over style consistency.

Setting button background under "Material Custom Theme" to the same color as window backround solves the problem but makes some other components (like section frames) invisible.

As I have no Java knowlege to propose conditional solution for button painting logic, for my private use I'm patching MTAbstractTheme.java by commenting out "Button.background" line in getButtonColorResources(). But it breakes the button styling when material components are used. 

### Expected behavior

Roughly (not 100% perfect) like in this patched plugin:
![image](https://user-images.githubusercontent.com/5732649/57580355-b31f2000-74a8-11e9-8f63-300d2d16621f.png)

### Actual behavior

Look at buttons and help icon:
<img width="870" alt="idea-buttons" src="https://user-images.githubusercontent.com/5732649/57580275-d72e3180-74a7-11e9-98fa-b8440d7328d7.png">

### Steps to reproduce (if needed)

1. Install plugin
2. Uncheck "Material design components" 
3. Restart IDE

### Environment

IntelliJ IDEA, PyCharm - any version
Kubuntu 19.04
KDE Plasma 5.15.4
Bundled JRE 1.8.xxx

**Comment by mallowigi** [comment]
Hi, 

I think in the future updates to completely remove the Material Design Components feature as it becomes very tedious to fix since the plugin is making extensive use of the Material Design components.

On the other hand you can also download the Material Theme UI plugin which only changes the theme and scheme while leaving the components untouched. And you can install the Atom Material Theme plugin for the icons.

I’ll try to look at another option but I can’t promise anything.

**Comment by xplwowi** [comment]
Hi,
In such case I will be forced to use material components and stay with your great work as all other features of the plugin are very convenient for me - compact options, components height customization, transparency, arrows, ...
Elements that I prefer from original theme are: smaller buttons, frames around imput fields and dropdowns.

**Comment by mallowigi** [comment]
I’ll still try to see if a simple solution exists, otherwise I’ll close this ticket :)

**Comment by xplwowi** [comment]
Don't bother with it if I'm the only one interested in this feature. I found that theme customization introduced recently is extremely flexible and gives easy access to the features I asked you.

Thanks for the hint. I have quite satisfying results after just 2 hours of playing with plugin designer.

![image](https://user-images.githubusercontent.com/5732649/57586106-35cbcd80-74f1-11e9-99e1-afcee97b8e8f.png)
