### ISSUE TITLE
SilverStripe templates (.ss)

### ISSUE THREAD

**Issue by kinglozzer** [ChrisRM/material-theme-jetbrains#1235]
Hi,

I’d like to submit a pull request to add a file icon for SilverStripe (a PHP framework) templates, which are files with an extension of `.ss` and would like some advice before I submit it. I’ve noticed that a [recent commit](https://github.com/ChrisRM/material-theme-jetbrains/commit/94eb77aa61d0cb448539757a63fe1e8124e9e3fe#diff-21a07cb3b29447477d7f0271afdaa67cR309) also added an icon for files with a `.ss` extension, so these may conflict.

I’m not familiar with Scheme, but SilverStripe templates are always beneath a “templates” directory, for example:

- `app/templates/Foo.ss`
- `app/templates/Foo/Bar.ss`
- `themes/mytheme/templates/Foo/Bar.ss`

Would it be possible to apply the SilverStripe icon to only files contained within a “templates” directory, or does it match on filename only and not directory?

The only other way I can think to detect SilverStripe instead of Scheme would be to detect the template language plugin (https://github.com/raket/idea-silverstripe), but I’m not sure if it’s possible for the theme to detect that

Thanks!

**Comment by mallowigi** [comment]
It's actually possible to prefix with a directory.

**Comment by kinglozzer** [comment]
Oh, neat! Would it be achieved with a regex in `icon_associations.xml`? For example `templates\/.*\.(ss)$`? Thanks

**Comment by mallowigi** [comment]
Yep. I’ll need to test to make sure but yes.

**Comment by kinglozzer** [comment]
Great, I’ll open a pull request tomorrow 😄

**Comment by kinglozzer** [comment]
@mallowigi Sorry, it doesn’t look like the association worked. I’m not overly familiar with Java (or IntelliJ’s APIs), but it looks like the regex-based associations currently match on filename and not path: https://github.com/ChrisRM/material-theme-jetbrains/blob/06b5aa0da2bc8d80195b059ebe9f12d7fd6717b3/src/main/java/com/chrisrm/idea/icons/associations/RegexAssociation.java#L56

If changing that to `file.getPath()` is too risky, perhaps introducing a `RegexPathAssociation` class would be a better solution?

**Comment by mallowigi** [comment]
I'll change the scheme icon to silverstripe, nobody uses scheme anyway
