### ISSUE TITLE
Unexpected project view file hierarchy behavior with JDK 11 

### ISSUE THREAD

**Issue by egtoney** [ChrisRM/material-theme-jetbrains#1236]
### Summary

When a new class is added to a package the project view no longer considers the package a java package and instead considers it a regular directory. This results in the project view displaying full package names on all root level packages that do not include the new file. ~~I haven't tested this behavior thoroughly, but when I switched the project's java version to 1.8 the problem seemed to resolve itself.~~

Project Setup:
Gradle Version: 5.2.1
Java Version: 11.0.1

### Expected behavior

Normally with the selected options the folder hierarchy should look something like this but with a new class inside of the package.

![image](https://user-images.githubusercontent.com/8811242/57800830-575ecc00-7720-11e9-85ed-b559887e2633.png)

### Actual behavior

The top level packages not containing a new file become root packages with full package names.

![image](https://user-images.githubusercontent.com/8811242/57800924-9260ff80-7720-11e9-9e07-1819c5356e70.png)

### Environment

IntelliJ IDEA 2019.1.2 (Community Edition)
Build #IC-191.7141.44, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Material Theme UI: v3.9.4
Material Theme Config (material_theme.xml):

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactSidebar" value="true" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="isDecoratedFolders" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="customSidebarHeight" value="22" />
    <option name="rightTreeIndent" value="6" />
    <option name="accentColor" value="009688" />
    <option name="userId" value="-3ddf2c83:16ab70fe22c:-8000" />
    <option name="version" value="3.9.4" />
  </component>
</application>
```

Material Theme Custom Config (material_custom_theme.xml):

```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Quick question: is it working fine with JDK 8 ?

**Comment by egtoney** [comment]
I thought it did when I first made this issue, but I just tried and it did not work with JDK 8 or JDK 11

**Comment by egtoney** [comment]
@mallowigi I did some more testing and it seems to only happen when using the Production, Test, Problems, and Changed Files views in the Project View tab.

**Comment by mallowigi** [comment]
Don't know how to fix this, sorry.
