### ISSUE TITLE
Appearance doesn't to dark theme

### ISSUE THREAD

**Issue by khaledkbadr** [ChrisRM/material-theme-jetbrains#124]
When I change the theme from the default to dark theme, only the editor is changed, while appearance stay on the default. I cannot find anyway to change the appearance also to the dark theme.

**Comment by ChrisRM** [comment]
Try applying the style using <kbd>Tools</kbd> › <kbd>Material Theme</kbd> › <kbd>Darker Theme</kbd> in the top navigation bar.

**Comment by khaledkbadr** [comment]
Works like a charm, thanks!
