### ISSUE TITLE
Issue with Firebase icon in Webstorm

### ISSUE THREAD

**Issue by DawnImpulse** [ChrisRM/material-theme-jetbrains#1244]
### Summary

There is an issue with the firebase icon in the files/folder section. The icon has only outline of a firebase but no lines or shadows inside as a typical firebase icon.

![Screenshot](https://i.imgur.com/cmRHBg6.png)

### Expected behavior

![Actual Icon](https://i.imgur.com/ka11tZ9.png)

### Actual behavior

...

### Steps to reproduce (if needed)

1. Inside a Webstorm project.

### Environment

WebStorm 2019.1.3
Build #WS-191.7479.11, built on May 21, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme Version : v3.10.0

[Custom Theme File](https://ufile.io/i5te4l6h)
[Material Theme File](https://ufile.io/6ca5zels)

**Comment by mallowigi** [comment]
This is the expected behavior. Material Icons, with the exception of Youtrack, have only one major color, no shadows.
