### ISSUE TITLE
Feature Request: Icon Association

### ISSUE THREAD

**Issue by justnewbee** [ChrisRM/material-theme-jetbrains#1246]
### Summary

Please support icon associating

### Expected behavior

I want to associate some of my folders to some icons

For example,

Folder named 'rc' is now a plain folder icon, however, i just want it a "component" icon

### Actual behavior

There's no such customization for now.

**Comment by mallowigi** [comment]
I have this feature in mind for some time, but I have no time to do so at the moment

**Comment by ryzr** [comment]
An additional use-case would be to change existing file associations.

Currently I have a trait named `HasLatest.php` which is being marked as a test due to the `test.php` suffix.

**Comment by timcreatedit** [comment]
This would be so amazing! The Material Theme plugin for VS Code already supports that and it makes organizing your project so much easier! I really hope that this will be implemented soon

**Comment by mallowigi** [comment]
I'll be doing it in the atom side project.
