### ISSUE TITLE
EAP. Visual bugs with tabs in settings.

### ISSUE THREAD

**Issue by chrisands** [ChrisRM/material-theme-jetbrains#1247]
### Summary

In settings > Editor > Code Style > JavaScript tabs doesn't show up

In Plugins tab text doesn't align by the center 

Here is a screenshot of those windows.
https://imgur.com/a/RQNa3Kv

### Environment

* WebStorm 2019.2 EAP
* Build #WS-192.4787.13, built on June 5, 2019
* WebStorm EAP User
* Expiration date: July 5, 2019
* Runtime version: 11.0.3+12-b281.38 x86_64
* VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.14.5
* GC: ParNew, ConcurrentMarkSweep
* Memory: 725M
* Cores: 8
* Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
* Non-Bundled Plugins: String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.godwin.json.parser, com.intellij.ideolog, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, org.intellij.plugins.postcss, com.deadlock.scsyntax, com.intellij.lang.jsgraphql, ru.adelf.idea.dotenv
* Plugin version: 4.0.1.
* Plugin configuration:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactDropdowns" value="true" />
    <option name="fileStatusColorsEnabled" value="false" />
    <option name="isCompactMenus" value="true" />
    <option name="isPsiIcons" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="upperCaseButtons" value="false" />
    <option name="settingsSelectedTab" value="5" />
    <option name="tabsHeight" value="38" />
    <option name="accentColor" value="ffd866" />
    <option name="selectedTheme" value="MONOKAI" />
    <option name="userId" value="4847740e:1699b1dc1c1:-8000" />
    <option name="version" value="4.0.0.1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Fixed. Will be available in next release for 2019.2 ASAP.
