### ISSUE TITLE
How to change HTML color text inside a tag?

### ISSUE THREAD

**Issue by sylouuu** [ChrisRM/material-theme-jetbrains#125]
Hi @ChrisRM,

Thank's for this plugin!

Look at this screen, I'm looking for a way to change the "PhpStorm" green color to another color like white because there are too many green in a HTML file.

![capture d ecran 2015-11-25 a 10 18 51](https://cloud.githubusercontent.com/assets/2300259/11393123/26005fb0-935e-11e5-88d0-e82b31c0c87f.png)

Bests

**Comment by ChrisRM** [comment]
Try changing the <kbd>General</kbd> › <kbd>Default text</kbd> setting.

**Comment by sylouuu** [comment]
Thank's but already checked, it's gray...

![capture d ecran 2015-11-25 a 11 59 09](https://cloud.githubusercontent.com/assets/2300259/11395553/067a1736-936c-11e5-945c-200e2fe0a67a.png)

**Comment by ChrisRM** [comment]
Oh, <kbd>XML</kbd> › <kbd>Tag data</kbd> should be it.

**Comment by sylouuu** [comment]
Perfect!
