### ISSUE TITLE
Editor Tab no text Intellij 2019.2

### ISSUE THREAD

**Issue by jpayne97** [ChrisRM/material-theme-jetbrains#1251]
### Summary

The editor tab is short and does not contain any text.  This was after the update to version 4.0.3.  I tried rolling back intellij to a previous version, even though it didn't update yesterday.  Disabling the plugin fixed the editor tabs.  Removed and Reinstalled.  Default options and theme.  Same behavior.

Manually installing 4.0.0.1 from the versions page fixed it.
https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions

### Expected behavior

The editor tab to contain the file name and be a normal height

### Actual behavior

The editor tab is short and does not contain any text.

### Steps to reproduce (if needed)

1. Install latest intellij
2. Install plugin (4.0.2 or 4.0.3)

### Environment

IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.4205.45, built on May 24, 2019
IntelliJ IDEA EAP User
Expiration date: June 23, 2019
Runtime version: 11.0.3+12-b248.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Lombook Plugin, com.ppolivka.gitlabprojects, mobi.hsz.idea.gitignore, net.ashald.envfile, org.intellij.RegexpTester, org.jetbrains.plugins.hocon, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
Please update to latest eap, something like 192.4707
