### ISSUE TITLE
Directories highlighted when files opened instead of modified

### ISSUE THREAD

**Issue by Bilge** [ChrisRM/material-theme-jetbrains#1252]
### Summary

I have configured directories to be highlighted when they contain files that are changed (no matter how deep in the hierarchy). However, with Material Theme, it is using this highlight to colour directories whenever any file within its hierarchy is _open in the editor_, whether or not it has actually been changed since last commit.

### Expected behavior
Directories highlighted only when they contain changed files.

### Actual behavior
Directories highlighted when any of their files are opened in an editor tab.

### Steps to reproduce (if needed)

1. Open file
2. See parent directory highlighted

Sometimes this doesn't work because it's not entirely clear under what circumstances the directory highlight updates. It is definitely highlighting on the basis of opened files instead of changed files, but it doesn't actually update just because files are opened or closed, so it's difficult to test sometimes. However, it certainly will update if the IDE is restarted.

![image](https://user-images.githubusercontent.com/470626/59354635-620b8180-8d1d-11e9-8eac-9106b44407dd.png)

### Environment

PhpStorm 2019.1.2
Build #PS-191.7141.52, built on May 8, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-50-generic

[material.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3281483/material.zip)

**Comment by Bilge** [comment]
Actually it seems the relevant options was cryptically labelled _Hollow Folders_.

![image](https://user-images.githubusercontent.com/470626/59418917-c8e27680-8dc1-11e9-8a4f-529b8eb29344.png)

Disabling it does stop this weird behaviour, but at the same time, it also removes _all_ folder colouring. I still want folders to be highlighted when they have changed descendents, and I have these options turned on, but they don't seem to do anything.

![image](https://user-images.githubusercontent.com/470626/59419046-07783100-8dc2-11e9-8e38-b2583de47a8d.png)

![image](https://user-images.githubusercontent.com/470626/59419022-f92a1500-8dc1-11e9-972a-8e19e1e35bea.png)

**Comment by mallowigi** [comment]
I've added a new option "Colored Open Directories" in 4.1.
