### ISSUE TITLE
No title bar on most recent EAP (All idea-besed platform）  plugin: v4.0.3

### ISSUE THREAD

**Issue by yyyreal** [ChrisRM/material-theme-jetbrains#1254]
### Summary

No title bar on most recent EAP.

### Expected behavior

with title bar

### Actual behavior

no title

### Steps to reproduce (if needed)

1. First step
install most recent EAP(for example IDEA 192.5118.30)
2. Second step
install material-theme-plugin
3. Third step
restart EAP

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5118.30, built on June 13, 2019
IntelliJ IDEA EAP User
Expiration date: July 13, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, Lombook Plugin, com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets

This issus occurred on IDEA, pycharm, clion(what I am using)

Material Theme Plugin version:  4.0.3
<img width="889" alt="屏幕快照 2019-06-14 21 10 41" src="https://user-images.githubusercontent.com/13974360/59511766-b6fbf300-8ee9-11e9-862a-fa70ec2e4a33.png">

**Comment by mallowigi** [comment]
damn.............. what have they done

**Comment by yyyreal** [comment]
@mallowigi Thanks for your hard work. Do you need more info? I can provide whatever I can get.

**Comment by mallowigi** [comment]
There's no fix for that, see there: https://youtrack.jetbrains.com/issue/JBR-1569

**Comment by yyyreal** [comment]
when I disable the plugin from the setting, title bar comes back.
<img width="889" alt="屏幕快照 2019-06-14 22 00 01" src="https://user-images.githubusercontent.com/13974360/59514635-db5ace00-8eef-11e9-89ec-e61f10e6d65f.png">

**Comment by mallowigi** [comment]
I've issued a hotfix that disables the titlebar altogether. I've created a PR to fix the titlebar, and I hope they'll merge it, but anyway it would not be available until the next release of JDK11

**Comment by yyyreal** [comment]
@mallowigi hi! The latest version of plugin (v4.1) occurs the privious problem.(2019.2RC)  
![屏幕快照 2019-07-22 14 41 14](https://user-images.githubusercontent.com/13974360/61611614-d3304400-ac8e-11e9-83dd-c4d417902e0a.png)
Would you please investigate it? THX

**Comment by mallowigi** [comment]
I know and it will stay like this until the transparent title bar is merged in the source code

**Comment by yyyreal** [comment]
Thanks

**Comment by taylorgoolsby** [comment]
@yyyreal If you disable "Themed Title Bar" and then restart WebStorm, it will look better.
![image](https://user-images.githubusercontent.com/14286600/61740946-ab031c80-ad44-11e9-9316-c3eb1c3e29cd.png)

**Comment by jgreenemi** [comment]
Experienced this same behaviour today on Intellij IDEA CE 2019.2, found the fix to be similar to the fix mentioned above, but I couldn't change the Themed Title Bar setting in Preferences as it was greyed out. The fix was to toggle it under the Tools heading, then restart Intellij.

![Screen Shot 2019-08-20 at 12 36 55 PM](https://user-images.githubusercontent.com/29902881/63378562-548afd00-c347-11e9-8141-e67e34e85442.png)
