### ISSUE TITLE
Android Studio uses different theme for editor than for chrome

### ISSUE THREAD

**Issue by geajack** [ChrisRM/material-theme-jetbrains#1256]
### Summary
Jetbrains uses the solarized light theme for the editor, even when I switch to other themes. Looks like this:

![](https://i.imgur.com/tM2g4Lu.png)

This happens with all the light themes. It happens with the dark themes as well, but weirdly, not with the solarized light theme:

![](https://i.imgur.com/icvFyF9.png)

### Steps to reproduce (if needed)
Not entirely clear. Seems to just be "install Android studio, install material theme, use solarized light theme once, then try using other light themes".

### Environment

```
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 1, 2019
JRE: 1.8.0_152-release-1343-b16-5323222 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-51-generic
```

- [Material theme config files](https://github.com/ChrisRM/material-theme-jetbrains/files/3294018/materialconfig.zip)

**Comment by geajack** [comment]
Finally tracked down the culprit... In the **Settings** menu, navigate to **Editor > Color Scheme**. For some reason I guess the editor and the chrome can have separate color schemes set in Jetbrains IDEs.

**Comment by mallowigi** [comment]
How do you switch themes ?

**Comment by mallowigi** [comment]
I see. I fixed it in one of the recent versions, but your Android Studio is too old for that. Just switch using the Quick Actions Panel (Cmd + `/ Ctrl+~)
