### ISSUE TITLE
Git diff window not working properly in IDEA EAP 2019.2

### ISSUE THREAD

**Issue by sabith-th** [ChrisRM/material-theme-jetbrains#1259]
### Summary
In Idea EAP, when you click on a git change to see the diff, the window is not shown properly
...

### Expected behavior

Screenshot on IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019

<img width="783" alt="Screen Shot 2019-06-18 at 3 27 34 PM" src="https://user-images.githubusercontent.com/14370454/59672876-f5412d00-91dd-11e9-8f22-b500cb7f79cc.png">

...

### Actual behavior
Screenshot on IDEA EAP 2019.2
<img width="783" alt="Screen Shot 2019-06-18 at 3 27 17 PM" src="https://user-images.githubusercontent.com/14370454/59672863-f07c7900-91dd-11e9-9dfb-7ef037c2173b.png">
...

### Environment
IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5118.30, built on June 13, 2019
IntelliJ IDEA EAP User
Expiration date: July 13, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Registry: bigger.font.in.project.view=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Infinitest, Lombook Plugin, Mongo Plugin, mobi.hsz.idea.gitignore, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, org.sonarlint.idea

Material Theme Plugin version - 4.0.4

**Comment by mallowigi** [comment]
Can't reproduce.

**Comment by alexsergin** [comment]
Same issue for me too. It displays empty window when click on a file from git log.
