### ISSUE TITLE
After install on MAC phpStorm, some Info Boxes are now large and obtrusive 

### ISSUE THREAD

**Issue by bgraham1125** [ChrisRM/material-theme-jetbrains#126]
![screen shot 2015-11-18 at 3 39 25 pm](https://cloud.githubusercontent.com/assets/3603685/11400842/88eaedb2-935d-11e5-9ada-328feb271c87.png)

**Comment by bbashy** [comment]
Steps to reproduce?

**Comment by bgraham1125** [comment]
Appeared after first install of plug in three or four weeks ago.  For a while phpStorm flashed a dialog box stating it could not find a font library when it started up.  Reinstalled the plugin today and the issue remains. Also, issue remains after uninstalling plugin.
