### ISSUE TITLE
Version Control Log Table Headers are Cut Off

### ISSUE THREAD

**Issue by meyerluk** [ChrisRM/material-theme-jetbrains#1261]
### Summary
The table headers of the "Version Control" -> "Log" tab are cut off
Already tried "Compact Table Cells" option but it didn't help.

### Expected behavior
Table headers should be readable

### Actual behavior
Table headers are cut off
![Screenshot 2019-06-24 at 14 29 42](https://user-images.githubusercontent.com/1007232/60019147-83f5f400-968d-11e9-8871-2bd03498ae67.png)

### Environment
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
Material Theme Plugin version: v3.10.0

**Comment by mallowigi** [comment]
I know about this but I'll tell you, this won't be fixed. This is very hard to fix and has very low priority.
