### ISSUE TITLE
Filenames in Conflicts window are not fully visible

### ISSUE THREAD

**Issue by pf1gura** [ChrisRM/material-theme-jetbrains#1264]
### Expected behavior

Filenames are fully visible in the window that list conflicted files

### Actual behavior

Filenames are not fully visible in the window that list conflicted files

### Steps to reproduce (if needed)

1. Merge two branches that edited same files

![image](https://user-images.githubusercontent.com/41795518/60255398-02da6f00-98d0-11e9-969f-2c730a2b9216.png)

### Environment

PhpStorm 2019.1.3
Build #PS-191.7479.51, built on June 18, 2019
Licensed to Przemyslaw Figura
Subscription is active until August 25, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3333947/material_theme.zip)

![image](https://user-images.githubusercontent.com/41795518/60255252-b2fba800-98cf-11e9-9ce3-fd52f7f1f5a5.png)

**Comment by mallowigi** [comment]
After investigation, this is related to the "Project View > Line Height" setting, and is also happening on regular JetBrains themes.

Please open an issue on JetBrains for this.
