### ISSUE TITLE
Align file icons

### ISSUE THREAD

**Issue by equinusocio** [ChrisRM/material-theme-jetbrains#1267]
Hi @mallowigi what do you think about updating the file icons with the original ones? Right now the repo of the source files is private, but I can add you to get the svg's. Let me know

**Comment by mallowigi** [comment]
I know but I preferred to fork from the Atom File Icons directly.

However if you want I can create a plugin that will use them independently.

**Comment by equinusocio** [comment]
Unfortunately I don't have the skills required to build a Jetbrains plugin. For vscode, there is a separated extension that provide file icons, it could be awesome if something similar existed  :(

https://github.com/equinusocio/vsc-material-theme-icons

**Comment by mallowigi** [comment]
I can make one if you want, and add you as a collaborator so you can update the icons.

--
Elior

**Comment by equinusocio** [comment]
Why not. Can you make it and follow the publication on Jetbrains repo?

**Comment by mallowigi** [comment]
I'll try to find a time, but it's not the priority.

Additionally you can try to fork the Atom-Material-File-Icons repository and submit a PR with the new icons.

**Comment by mallowigi** [comment]
Can you do a pull request with all the new icons in, say, a new folder?
