### ISSUE TITLE
UI settings reset at "random" points

### ISSUE THREAD

**Issue by rherrick** [ChrisRM/material-theme-jetbrains#1268]
### Summary

Occasionally the IntelliJ IDEA UI resets to something like default colors.

### Expected behavior

The UI doesn't randomly reset.

### Actual behavior

The UI does randomly reset. In order to get back to my preferred theme, I either have to switch to a different theme then back to my preferred theme or quit IntelliJ and restart.

### Steps to reproduce (if needed)

I'm not really sure what causes it. The latest reset happened when a message appeared indicating that an update to another plugin (not Material Theme) was available.

### Environment

IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5438.14, built on June 26, 2019
IntelliJ IDEA EAP User
Expiration date: July 26, 2019
Runtime version: 11.0.3+12-b304.2 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: bigger.font.in.project.view=true, external.system.substitute.library.dependencies=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: A move tab left and right using the keyboard plugin - by momomo.com, A prevent pinned tabs from closing plugin - by momomo.com, Builder Generator, CheckStyle-IDEA, FindBugs-IDEA, GrepConsole, Lombook Plugin, RegexPlugin, Scratch, color.scheme.GapStyle, com.alayouni.ansiHighlight, com.daylerees.rainglow, com.facebook.rucinskic.chromaterial, com.intellij.ideolog, com.jensteichert.themes.nightowl, com.jetbrains.darkPurpleTheme, com.jetbrains.plugins.ini4idea, com.therdnotes, com.thvardhan.gradianto, com.tobszarny.activetabhighlighter.plugin.id, com.vermouthx.idea, com.atlassian.bitbucket.references, io.codearte.props2yaml, jms-messenger, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.antlr.intellij.plugin, org.asciidoctor.intellij.asciidoc, org.intellij.plugins.hcl, com.chrisrm.idea.MaterialThemeUI, io.github.satr.idea.plugin.connector.la, com.hotswap.agent.plugin, BashSupport, com.beust.kobalt.intellij, com.intellij.plugins.html.instantEditing, cucumber-javascript, izhangzhihao.rainbow.brackets, org.intellij.scala, org.jetbrains.plugins.vagrant, com.intellij.kubernetes, com.intellij.lang.puppet, com.zhaow.restful.toolkit, org.jeto.taskfocus, org.nik.presentation-assistant, org.scalafmt.ScalaFmt, org.zalando.intellij.swagger, ru.adelf.idea.dotenv, some.awesome

My config is below:

```
<application>
  <component name="MaterialThemeConfig">
    <option name="arrowsStyle" value="Arrows" />
    <option name="allowDataCollection" value="true" />
    <option name="highlightColorEnabled" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="useMaterialFont2" value="true" />
    <option name="indicatorStyle" value="Dot" />
    <option name="highlightThickness" value="5" />
    <option name="settingsSelectedTab" value="6" />
    <option name="accentColor" value="2f3aa0" />
    <option name="highlightColor" value="2f3aa0" />
    <option name="selectedTheme" value="DEEPOCEAN" />
    <option name="userId" value="57eeb1f0:16403aa6f00:-7fff" />
    <option name="version" value="4.0.5" />
  </component>
</application>
```
I've also attached [ui-scheme-reset.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3350863/ui-scheme-reset.zip). This includes idea.log from when the last reset happened (the first entry in that log file is the first one from today, so there wasn't any context prior to that). It also includes a thread freeze dump that occurred at the same time and a screen shot showing the state of the UI. As the config indicates, I normally run the Deep Ocean theme.

**Comment by mallowigi** [comment]
I heard there was a problem with the IDE Settings Sync. Please try without it and tell me if it occurs. 

Anyway if you can't reproduce exactly, I can't help.

**Comment by scaytrase** [comment]
For me it's for sure caused by IDE Settings Sync. This plugin isn't compatible with them?
