### ISSUE TITLE
[BUG] IDEA crash when I open Material theme UI-3.10.0 on mac catalina beta3

### ISSUE THREAD

**Issue by erheng** [ChrisRM/material-theme-jetbrains#1269]
## Summary
When I upgrade the system to macOS catalina 10.15 beta3 ，open idea and crashed.
when shut down it, is ok

## use plugins
activate-power-mode  v0.1.8
Alibaba Java Coding Guidelines v2.0.0
CodeStream v1.3.0+1
FindBugs-IDEA v1.0.1
GsonFormat v1.5.0
JRebel for Intellij v2019.1.3
Lombok v0.25-EAP
Maven Helper v4.5.183.41390
Nana-Mybatis v1.0.2
NodeJS v191.7479.1
Nyna Progress Bar v1.12
Rainbow Brackets v5.20
Translation v2.3.2

## Environment
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15 beta3

**Comment by mallowigi** [comment]
Sorry the plugin is not supported on Catalina 10.15 at the moment. Please use Material Theme UI Lite.

**Comment by ToniNgethe** [comment]
When will it be supported?
