### ISSUE TITLE
Doc block formatting issue with code tags

### ISSUE THREAD

**Issue by jonnywilliamson** [ChrisRM/material-theme-jetbrains#127]
I initially submitted this thinking it was a bug with phpstorm 10. However it turns out it is actually an issue with this theme.

Original bug request here: https://youtrack.jetbrains.com/issue/WI-29877

Synopsis:
When viewing a doc bloc with a `<code>` tag in it WITHOUT this theme, the doc block looks like this:
![image](https://cloud.githubusercontent.com/assets/2513663/11431687/1d2cad48-9495-11e5-80db-b1a3405871b1.png)

When enabling this theme, the same docbloc looks like this:
![image](https://cloud.githubusercontent.com/assets/2513663/11431689/2bdc475e-9495-11e5-8c3b-037ca4aaf764.png)

Original docblock source is:

``` php
/**
     * Send text messages.
     *
     * <code>
     * $params = [
     *   'chat_id'                  => '',  //Required
     *   'text'                     => '',  //Required
     *   'parse_mode'               => '',  //Optional
     *   'disable_web_page_preview' => '',  //Optional
     *   'reply_to_message_id'      => '',
     *   'reply_markup'             => '',
     * ];
     * </code>
     *
     * @link https://core.telegram.org/bots/api#sendmessage
     *
     * @param array    $params
     * @return Message
     */
```

Not sure where or how to fix this myself.

**Comment by mallowigi** [comment]
Should be fixed in the latest release

**Comment by jonnywilliamson** [comment]
Thank you. Will check.
