### ISSUE TITLE
Themed Title bar is not working in WebStorm 2019.1

### ISSUE THREAD

**Issue by TheCodersPlayground** [ChrisRM/material-theme-jetbrains#1271]
Versions:

WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
Licensed to Raman Natarajan
You have a perpetual fallback license for this version
Subscription is active until May 13, 2020
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Material Plugin: 3.10.0

**Comment by mallowigi** [comment]
The Themed Title Bar feature is suspended for a while. I'll update when it comes back.
