### ISSUE TITLE
Fatal Error with WebStorm 2019.2 EAP

### ISSUE THREAD

**Issue by ovr** [ChrisRM/material-theme-jetbrains#1273]
Hello!

### Summary

Open IDE and it dies

### Steps to reproduce (if needed)

1. Open IDE
2. GG WP

### Environment

WebStorm: `192.5281.21`
Plugin: 4.0.5
OS: OSX 10.15 Catalina Beta 3

[java_error_in_webstorm_63998.log](https://github.com/ChrisRM/material-theme-jetbrains/files/3367246/java_error_in_webstorm_63998.log)

Thank you

**Comment by kallard1** [comment]
Hello, I've same problem in [Pycharm](https://gist.github.com/kallard1/acc4281384ab49af5b4c231cb183607f) and [PHPStorm](https://gist.github.com/kallard1/c54e39486ca5889aabb3546cba0a21cb)

**Comment by mallowigi** [comment]
Plugin is not working in Catalina. Sorry

**Comment by sifex** [comment]
[https://media.giphy.com/media/pPhyAv5t9V8djyRFJH/giphy.gif](https://media.giphy.com/media/pPhyAv5t9V8djyRFJH/giphy.gif)

**Comment by sifex** [comment]
![tenor](https://user-images.githubusercontent.com/2058557/61169450-ecefce00-a5a0-11e9-982b-107d4883d21a.gif)
