### ISSUE TITLE
Color differences between 3.8 and 3.9+ for Atom One Dark

### ISSUE THREAD

**Issue by svencowart** [ChrisRM/material-theme-jetbrains#1276]
### Summary

The changes made to Atom One Dark look very poor.

### Expected behavior

Bring back 3.8 styles for Atom One Dark.

### Actual behavior

- JSX code is italic.
- Font weight is significantly heavier and line height was condensed making the code look crunched together.
- All the colors are much brighter.  This is not a good thing for the Atom One Dark theme.  It was good because it did not use bright colors.
- Missing highlight for excluded directories.

### Steps to reproduce (if needed)

Compare Atom One Dark for 3.8 with 3.9.

![Screen Shot 2019-07-12 at 3 57 34 PM](https://user-images.githubusercontent.com/8366524/61159467-26a1d580-a4ca-11e9-8b26-8ae6763fcbb4.png)
![Screen Shot 2019-07-12 at 4 00 55 PM](https://user-images.githubusercontent.com/8366524/61159468-26a1d580-a4ca-11e9-9d9c-84564e53f276.png)
![Screen Shot 2019-07-12 at 4 02 06 PM](https://user-images.githubusercontent.com/8366524/61159522-4cc77580-a4ca-11e9-8f16-bcf4c1661c94.png)

### Environment

WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
Licensed to Sven Cowart
Subscription is active until February 4, 2020
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by mallowigi** [comment]
I'm not going over the color schemes again. If you don't like them, you can still download the previous version, make a copy and import it.

**Comment by svencowart** [comment]
I appreciate your work on this plugin, but there is a real problem here with the excluded folders not showing up and the JSX code being italic (which is only the case for the One Dark and One Light themes).  A few of the dark themes have this heavy font-weight and it is much more difficult to read on non-4K+ monitors.

**Comment by mallowigi** [comment]
Hi, have you tried that: http://www.material-theme.com/docs/configuration/excluded-files-colors/

For the font weight, you simply have to change the font (Settings>  Color Scheme > Color Scheme Font) from Menlo to Fira Code and it should do the trick.

**Comment by mallowigi** [comment]
As for the italic for the tags, I agree that it's not intended. I'll fix that for next release.

**Comment by svencowart** [comment]
Thank you, that helps.  For reference to other, I was able to change the JSX tag names back to non-italic by going to (Settings> Color Scheme > Color Scheme Font -> XML -> Tag Names)
