### ISSUE TITLE
Unexpected dialog confirmation applying of preferences with 3.10 plugin

### ISSUE THREAD

**Issue by svencowart** [ChrisRM/material-theme-jetbrains#1277]
### Summary

Any update I make to Webstorm preferences, even ones unrelated to the theme causes a confirmation dialog to appear related to a custom theme.

### Expected behavior

This dialog should not display unexpectedly.

### Actual behavior

Any update to preference trigger a dialog confirmation

### Steps to reproduce (if needed)

![Screen Shot 2019-07-12 at 4 01 37 PM](https://user-images.githubusercontent.com/8366524/61159719-e858e600-a4ca-11e9-84f7-76d2e789901f.png)

### Environment

WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
Licensed to Sven Cowart
Subscription is active until February 4, 2020
JRE: 1.8.0_202-release-1483-b53 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**Comment by mallowigi** [comment]
Not from my plugin, but from Jetbrains. This means that your color scheme is a light scheme while you have a dark UI theme. Please make sure you have a dark scheme applied.

**Comment by svencowart** [comment]
Here is my configuration:

- Color Scheme -> Scheme: Atom One Dark
- Appearance -> Theme: Atom One Dark
- Material Theme -> Selected Theme: Atom One Dark

Am I missing something?  Otherwise, this is a fresh install of webstorm 2019.1.3 with only the Material UI plugin installed.
