### ISSUE TITLE
Causes a crash, on opening the IDE in macOS 10.15 (beta)

### ISSUE THREAD

**Issue by imageaid** [ChrisRM/material-theme-jetbrains#1278]
### Summary

With Material Theme plugin enabled, you cannot open a project in the IDE (DataGrip and/or RubyMine)

### Expected behavior

I should be able to open my IDE with Material Theme enabled.

### Actual behavior

It crashes as it tries to open the project/IDE.

### Steps to reproduce (if needed)

1. Install macOS 10.15 (most current beta)
2. Launch RubyMine or DataGrip
3. Watch it crash

### Environment

Since I cannot open the IDE (both DataGrip and RubyMine have failed with the most recent 2019.1 release and the most recent 2019.2 EAP), I have attached the error log. 

[java_error_in_datagrip_10001.log](https://github.com/ChrisRM/material-theme-jetbrains/files/3392420/java_error_in_datagrip_10001.log)

**Comment by mallowigi** [comment]
Catalina is not yet supported, sorry.

**Comment by LanikSJ** [comment]
@mallowigi are there any plans to support macOS Catalina before it's released or after?

If you need someone to test things out I volunteer my PyCharm setup.

**Comment by mallowigi** [comment]
No. When Catalina is out, I'll update my Mac like everyone and then, I can fix the issues. I'm not planning to do so before the release date.

But anyone is welcome to submit PRs
