### ISSUE TITLE
The bug hides the layout editor in AS 3.5

### ISSUE THREAD

**Issue by oky2abbas** [ChrisRM/material-theme-jetbrains#1279]
**Bug description**
After installing the Material UI, the layout editor functionality is lost, the image of this bug is attached.

**Info**
- OS: macOS Mojave 10.14.5
- Android Studio: 3.5 RC1
- Material UI: 3.10.0

**Steps to Bug**
###### step One
```Install the material UI plugin and restart AS.```
###### Step Two
```
Select the Atom On Dark them and select the set no arrows style option.
Note: Everything works fine.
```
###### Step Three
```Again restart AS.```
###### Step Four
```Create bugs and hide layout editor windows.```

**Please fix this bug.**

<img width="1280" alt="material ui bug in AS 3 5" src="https://user-images.githubusercontent.com/8849632/61578298-c9310880-ab09-11e9-852c-73a8beeb25bf.png">

**Comment by oky2abbas** [comment]
**I found the reason for this problem.**
The problem occurs when I select the `set no arrows style` option and then restart Android studio.
Please check and fix this problem.

**Comment by mallowigi** [comment]
I absolutely have no idea why this happens, and can't do anything about it.

Thanks, I'll add it to the common issues.
