### ISSUE TITLE
Color scheme (sometimes) breaks in PyCharm 5.0+

### ISSUE THREAD

**Issue by cryzed** [ChrisRM/material-theme-jetbrains#128]
Any idea what might be causing the bug described [here](https://youtrack.jetbrains.com/issue/PY-17819)? Is it an expected incompatibility following the update?

**Comment by melqkiades** [comment]
Hi, I'm still having the same problem, but I have my own color scheme, which took me a while to build.
What can I do to solve this?
Here is a screenshot.
Thanks

![screen shot 2016-02-16 at 14 29 01 2](https://cloud.githubusercontent.com/assets/7023350/13078980/c0f1fb86-d4b9-11e5-9534-46b3bbaebe9e.png)

**Comment by fcoclavero** [comment]
Hi! I am still experiencing this issue in PyCharm. Has anyone found a solution?
Thanks!

**Comment by cryzed** [comment]
Yes, it never was fixed for me. There's even a recent issue where a user mistakingly assumes that the theme is supposed to look like that.

**Comment by farrokhi** [comment]
Using PyCharm 2016.1.4 (Build #PY-145.1504), still experiencing the same problem.
