### ISSUE TITLE
Visibility keywords incorrectly styled on Palenight theme on macOS IntelliJ IDEA 2019.1.3

### ISSUE THREAD

**Issue by jrhenderson1988** [ChrisRM/material-theme-jetbrains#1280]
### Summary

The colour and style of Java visibility keywords (`public`, `private`, `protected` etc.) don't follow the configured style for the Palenight theme in IntelliJ IDEA 2019.1.3 on macOS Mojave.

As you can see in the provided screenshot, the `public` and `private` keywords are orange and italic rather than the purple colour defined in the configuration. Other keywords such as `static`, `void` and `final` as displayed in the screenshot seem to be coloured correctly.

I've only noticed this issue on macOS IntelliJ IDEA with Java code. PyCharm on macOS and IntelliJ IDEA on Windows both seem okay to me, as does Kotlin code in IntelliJ IDEA on macOS. I have also tried clearing out all of my plugins, caches and settings, as well as completely reinstalling IntelliJ IDEA but the issue seems to persist.

I currently have a bunch of other plugins installed but I was able to replicate the issue following a fresh reinstall of IntelliJ IDEA and the Material Theme plugin (with no others present).

### Expected behavior

The visibility keywords should be styled as configured in the settings.

### Actual behavior

The visibility keywords don't seem to be registered as keywords and instead seem to be picking up another style.

### Steps to reproduce (if needed)

1. Install IntelliJ IDEA on macOS
2. Install Material theme plugin
3. Choose Palenight from the Material Theme Chooser

<img width="1394" alt="Screenshot 2019-07-20 at 14 52 05" src="https://user-images.githubusercontent.com/8791010/61579626-a6015b80-aaff-11e9-8b33-d4f7082fb5da.png">

### Environment

IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

* macOS Mojave 10.14.5
* IntelliJ IDEA 2019.1.3
* Material Theme UI v3.10.0

**Comment by mallowigi** [comment]
You have to change them in the “Java Additions” color page.

**Comment by jrhenderson1988** [comment]
Oh thanks, I didn't realise that existed. Is it intended that by default the Palenight theme is different on macOS vs Windows, in that case?

**Comment by mallowigi** [comment]
What do you mean ?
