### ISSUE TITLE
Toolbar icons rendered wrong placement obsurs Mac bullets

### ISSUE THREAD

**Issue by hakuseki** [ChrisRM/material-theme-jetbrains#1285]
### Summary
Toolbar icons rendered wrong placement obsurs Mac bullets
...

### Expected behavior
not obscure
...

### Actual behavior
see screendump
...

### Environment

Toolbar icons rendered wrong placement obsurs Mac bullets
![gui____IdeaProjects_gui__-_____src_main_resources_static_css_default_css_and_New_Issue_·_ChrisRM_material-theme-jetbrains](https://user-images.githubusercontent.com/5478862/61767627-2caa8700-ade5-11e9-80c3-bd0091411e03.png)

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by ihachani** [comment]
Same issue in Webstorm 2019.2

**Comment by sebastiaanluca** [comment]
Bit similary here. Seems like the title bar was removed or something?

![Screenshot 2019-07-25 at 14 05 58](https://user-images.githubusercontent.com/711940/61873160-898d6680-aee5-11e9-8c7b-218a0b5f90c5.png)

**Comment by mallowigi** [comment]
Its' the intended behavior (well not really but it is for the time being). It will return back on 2019.3 probably, in the meantime you can disable the "Themed Title Bar" in the options and restart

**Comment by coleman17** [comment]
But it's so cool having the combined title bar @mallowigi ;) - thanks for the tip!

**Comment by ahokinson** [comment]
> Its' the intended behavior 

Can you explain what you mean by this? How do you know that JetBrains will make a change supporting this in 2019.3?

**Comment by mallowigi** [comment]
https://youtrack.jetbrains.com/issue/JBR-1569

Please follow up this

**Comment by mallowigi** [comment]
https://youtrack.jetbrains.com/issue/IDEA-219015
