### ISSUE TITLE
File Colors in Tabs stop working in IntelliJ 2019.2

### ISSUE THREAD

**Issue by krouxe** [ChrisRM/material-theme-jetbrains#1288]
### Summary

Tabs are not colored regarding File Colors configuration in Intellij 2019.2 using plugin version 4.1

### Expected behavior

Tabs should have their background colored using File Colors configuration

### Actual behavior

No background color 

### Steps to reproduce (if needed)

1. Install IntelliJ 2019.2
2. Install Material Theme 4.1
3. Configure File Colors for Tests, Production files
4. Open Test and Production class

![file-colors-issue](https://user-images.githubusercontent.com/998578/61926468-f69a0e00-af70-11e9-901b-0cc8f30e5495.png)

### Environment

IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3038M
Cores: 4
Matherial Theme UI 4.1
Non-Bundled Plugins: CMD Support, Compare Directories, EclipseCodeFormatter, GrepConsole, Mongo Plugin, Statistic, SvgViewer 2, Unicode Browser, UpperLowerCapitalize, ch.dasoft.iconviewer, com.arcticicestudio.nord.jetbrains, com.daylerees.rainglow, com.intellij.apacheConfig, Git Scope, com.karateca.elementorIdea, com.karateca.jasmineDescriber, com.markskelton.one-dark-theme, com.samdark.intellij-visual-studio-code-dark-plus, com.thvardhan.gradianto, com.atlassian.bitbucket.references, idea-mini-ibatis, nl.jworks.intellij.bootstrap3, org.asciidoctor.intellij.asciidoc, com.chrisrm.idea.MaterialThemeUI, com.github.mturlo.intellij.theme.spacegray, Karma, com.dmarcotte.handlebars, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.jade, izhangzhihao.rainbow.brackets, JProfiler, Pythonid, org.jetbrains.spek.spek-idea-plugin, ru.artyushov, training

material_theme.xml

```
<application>
  <component name="MaterialThemeConfig">
    <option name="highlightColorEnabled" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="upperCaseButtons" value="false" />
    <option name="useMaterialFont2" value="true" />
    <option name="settingsSelectedTab" value="5" />
    <option name="tabsHeight" value="26" />
    <option name="accentColor" value="e57373" />
    <option name="highlightColor" value="cb3114" />
    <option name="userId" value="-5fa23197:1661ef322f6:-8000" />
    <option name="version" value="4.1" />
  </component>
</application>

```
material_custom_theme.xml

```
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="009688ff" />
    <option name="notificationsColor" value="323232ff" />
    <option name="treeSelectionColor" value="546e7aff" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="607d8bff" />
    <option name="foregroundColor" value="b0bec5ff" />
    <option name="backgroundColor" value="263238ff" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
fixed in 4.2
