### ISSUE TITLE
Function and method calls became grey in Darker 2019.2?

### ISSUE THREAD

**Issue by zzell** [ChrisRM/material-theme-jetbrains#1289]
### Summary
Function and method calls in Darker theme are grey instead of blue in GoLand v2019.2. Is that intended?

### Expected behavior
Function and method calls should be blue as always.

![Screenshot from 2019-07-26 13-42-40](https://user-images.githubusercontent.com/30296653/61946845-46e29180-afac-11e9-8a97-212e45c27f6c.png)

### Actual behavior
They are grey.

![Screenshot from 2019-07-26 13-42-57](https://user-images.githubusercontent.com/30296653/61946896-6c6f9b00-afac-11e9-9690-97dc791dc2c9.png)

### Environment

GoLand 2019.2
Build #GO-192.5728.103, built on July 23, 2019

Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-25-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1925M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, io.protostuff.protostuff-jetbrains-plugin, BashSupport, PythonCore, org.jetbrains.settingsRepository

**Comment by robertsteilberg** [comment]
I have seen similar discolorations with Material Palenight in WebStorm 2019.2.

**Comment by alexpolozov** [comment]
Similarly for Arc Dark in PyCharm.

**Comment by drdgvhbh** [comment]
help

**Comment by Tomotoes** [comment]
+1

**Comment by NickKaramoff** [comment]
I have experienced this in WebStorm 2019.2 with Material Darker. All instance member functions turned pale orange (although they were blue before).

If you want to bring that back, you can locate the rule in `Settings > Editor > Color Scheme > %LANGUAGE_NAME% > Instance member function` and check the box "Inherit values from":

<img width="215" alt="image" src="https://user-images.githubusercontent.com/6566248/62013607-891ef500-b19d-11e9-89c4-07035687c6fe.png">

This will make the function the default (blue) color. I guess, that can help with other themes and other code elements (such as constructors and local variables).

**Comment by mallowigi** [comment]
This happens every once and every update, the default color schemes are updated and with it, custom color schemes have their colors overridden if they do not define a value. It’s pretty annoying.

Anyway I’ve fixed that and the next update should have the colors back, but I won’t release it until at least two weeks

**Comment by drdgvhbh** [comment]
Is there a way to get that update before you release it?
