### ISSUE TITLE
Modified files don't respect * mark

### ISSUE THREAD

**Issue by vgsystems** [ChrisRM/material-theme-jetbrains#1291]
### Summary
Edited files don't appear as modified marked with * as the previous version.

### Expected behavior
Files should be marked with * when they have been modified if this option is selected in PHPStorm options.

### Actual behavior
Modified files appear as modified with a small green line in the top-left side of the tab. Very close to the icon file. This doesn't help to identify modified files quickly

### Steps to reproduce

![Captura de pantalla 2019-07-26 a las 20 00 55](https://user-images.githubusercontent.com/7352160/61971768-26ccc580-afe0-11e9-8936-5274b219a9f8.png)

### Environment

PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, de.espend.idea.laravel, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
This is the icon that replaces the asterisk as it has always been. If you don’t like this icon the only way would be to remove all icons altogether by unchecking the “Material UI Icons”

**Comment by vgsystems** [comment]
> This is the icon that replaces the asterisk as it has always been. If you don’t like this icon the only way would be to remove all icons altogether by unchecking the “Material UI Icons”

This is not true @mallowigi, if I rollback to 4.1 this icon (green line) don't appear and unsaved files were marked with * following the pref set.

![Captura de pantalla 2019-07-26 a las 20 32 35](https://user-images.githubusercontent.com/7352160/61973649-cd1aca00-afe4-11e9-9202-86c2040077b8.png)
![Captura de pantalla 2019-07-26 a las 20 34 14](https://user-images.githubusercontent.com/7352160/61973655-d0ae5100-afe4-11e9-82ac-ff8e1ff2427c.png)

**Comment by mallowigi** [comment]
https://www.material-theme.com/img/accents/editIndicator.png

This is what it’s supposed to be. The location was at the bottom right originally but in 2019.2 they moved it to the top left hence why the icon is now there.
Previous versions of the plugin still had the old version of the icon at the bottom right which ended up being cropped.

There is no way you see either the icon or the asterisk. You simply would have seen nothing.
