### ISSUE TITLE
GoLand 2019.2 One Dark theme doesn't work for syntax highlighting 

### ISSUE THREAD

**Issue by SuddenGunter** [ChrisRM/material-theme-jetbrains#1292]
### One Dark theme doesn't work for syntax highlighting 
![image](https://user-images.githubusercontent.com/15653599/61999884-be5f1080-b0d3-11e9-8f5d-0854afb775e0.png)

### Expected behavior
Colors in editor follow One Dark theme

### Actual behavior
Colors in editor look like Darkula

### Steps to reproduce (if needed)

1. Uninstall any existing GoLand installations
2. Remove ~/.GoLand* directories
3. Install GoLand 2019.2 from jebrains toolbox 
4. Install MaterialUI and select One Dark theme

### Environment

GoLand 2019.2
Build #GO-192.5728.103, built on July 23, 2019
Licensed to A***** ****
Subscription is active until ***********
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.3-arch1-1-ARCH
GC: ParNew, ConcurrentMarkSweep
Memory: 1946M
Cores: 6
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, io.protostuff.protostuff-jetbrains-plugin, BashSupport

MaterialUI version 4.2
[options.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3438670/options.zip)

**Comment by Tomotoes** [comment]
[GoLand 2019.2](https://www.jetbrains.com/go/promo/whatsnew/)
![image](https://user-images.githubusercontent.com/32236122/62001618-fd6a8180-b126-11e9-9dae-98beabaa62f5.png)
