### ISSUE TITLE
Themed title bar font

### ISSUE THREAD

**Issue by Sartoric** [ChrisRM/material-theme-jetbrains#1293]
I've just installed the last update that fix the themed title bar issue, but it seems there's something strange with the font
It looks like it has been reduced a bit making it barely readable and afair there's no option to change it. Am I wrong ? 

No theme
![Schermata 2019-07-30 alle 11 11 18](https://user-images.githubusercontent.com/6607379/62117033-82869f80-b2bb-11e9-8ef8-24f3e235ae0c.png)

Themed
![Schermata 2019-07-30 alle 11 07 12](https://user-images.githubusercontent.com/6607379/62117111-9cc07d80-b2bb-11e9-89c0-21e6e0b3e021.png)

**Comment by mallowigi** [comment]
It should be using the font you specified in General > Appearance.

**Comment by Sartoric** [comment]
Yes, right.
But I would expect it to be the same shown while theme is not applied, or at least (if theme is applied) the same used for tab or sidebar for instance. Isn't it ? 
Looks like a rendering issue (anti-aliasing?).
I'm not saying it is a theme bug, maybe something related to the new engine.

![Schermata 2019-07-30 alle 15 28 50](https://user-images.githubusercontent.com/6607379/62133283-cfc83880-b2de-11e9-820b-6f388743fdd4.png)

![Schermata 2019-07-30 alle 15 16 25](https://user-images.githubusercontent.com/6607379/62132884-2ed97d80-b2de-11e9-8031-bd39d039b325.png)

I'm not using material Font  or Tab's custom setting

**Comment by mallowigi** [comment]
It could be, there are many artifacts with font rendering usually.

I'd suggest to turn off the themed title bar feature.

**Comment by Sartoric** [comment]
Thanks. 
Anyway, not a big issue. For sure I can live with it :D

**Comment by kstratis** [comment]
I second that. Not a big issue but really annoying...

**Comment by mallowigi** [comment]
If it's annoying so don't use it.
