### ISSUE TITLE
File Colors appear to have reverted to the dull defaults in 2019.2

### ISSUE THREAD

**Issue by connrs** [ChrisRM/material-theme-jetbrains#1294]
### Summary

After upgrading to 2019.2 and also updating this plugin to the latest version I've noticed that the named File Colors that are available when in Settings -> Appearance & Behavior -> File Colors -> ... -> Edit Color Label are no longer the vivid ones I used to have in older versions of Intellij/PHPStorm.

*(The only similar issue report is #1288 but that doesn't appear to be related to the colours themselves. I've been through the settings and can't see anything that relates to configuring the file colors.)*

Just before I submitted this I tried toggling everything in the Material Theme settings in case I'd somehow turned something off but nothing seems to affect it.

### Expected behavior

Colours such as Amber, Crimson, DeepPurple, Forest, Sea and Spice should be vivid and bright.

### Actual behavior

These colours are now dull. Amber is \#634900

### Steps to reproduce (if needed)

*Apologies that these aren't very good repro steps*

1. Have PHPStorm 2019.1
2. Upgrade to 2019.2 
3. Update Material Theme to latest version
4. Notice that File Colors are dull

(Screenshot included in Dropbox link below)

### Environment

- PhpStorm 2019.2
- Build #PS-192.5728.108, built on July 24, 2019
- Licensed to [REDACTED]
- Subscription is active until April 22, 2020
- Runtime version: 11.0.3+12-b304.10 x86_64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- macOS 10.14.5
- GC: G1 Young Generation, G1 Old Generation
- Memory: 2000M
- Cores: 8
- Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
- Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.demonwav.autosync, com.jonathonstaff.ideaascii, com.github.masahirosuzuka.PhoneGapIntelliJPlugin

[Material theme files (and screenshot of File Colors panel)](https://www.dropbox.com/sh/knk6znazm6kyrjb/AABS7n2NPNeN19NRsvhEwd-za?dl=0)

**Comment by mallowigi** [comment]
Yes, I darkened these colors because I found them too bright to be usable, dark or light themes. I rarely used them but when I do I always see this chunk of Red/Blue/Green and it hurts my eyes so I thought that I wouldn't be the only one.

Anyway it's purely a question of taste here, besides I'm planning to have different ones per theme related to the theme colors (keywords, functions, attributes etc, but darkened).

You can still revert the old behavior by selecting Custom and check the old ones here: https://github.com/ChrisRM/material-theme-jetbrains/commit/9dbc4d29c28c93fb2dcfe6e11dfe20882eebfdfe#diff-c6dfd0a2504f44fd41f01fc031d5c342

**Comment by connrs** [comment]
Thanks for the info @mallowigi. When I first switched to using this plugin I was also quite shocked at how vivid those colours were but then I really got used to it.

If this is a conscious design decision to reduce eye strain then I'm happy sticking with the colour names rather than going custom. Especially if you plan to make different ones per-theme at some point and I'd end up missing out on those changes!

Unless you want to keep this open for any reason, I'm happy to close this.
