### ISSUE TITLE
Check Box Appear Error

### ISSUE THREAD

**Issue by Invoker-liu** [ChrisRM/material-theme-jetbrains#1295]
![image](https://user-images.githubusercontent.com/20022777/62177399-5deffd80-b377-11e9-8a09-6e2c0203a343.png)
Why my checkbox appear like this,can l fix it by remove my local setting?
Thanks for you working!

**Comment by mallowigi** [comment]
Please provide more information about your environment

**Comment by Invoker-liu** [comment]
> Please provide more information about your environment

I remove all my IDEA config ,it comes true,guess maybe caused by the version of my IDEA, l will close this issue,Thanks again!
