### ISSUE TITLE
The result list expands when the query runs again

### ISSUE THREAD

**Issue by gecimli** [ChrisRM/material-theme-jetbrains#1297]
[Result.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3450698/Result.zip)

# Summary

Step 1. Running the query.
Step 2. I'm running the same query again to see if there are any changes.

The columns in the result area are expanding.
I've added a screen video.

Version List:
DataGrip 2019.2
Windows 10, 10.0
Plugin version: 4.2.1

**Comment by renzo-ezagui** [comment]
Same here, just installed Material theme and notice this behavior.

**Comment by sassdavid** [comment]
I have the same problem
Windows 10
DataGrip 2019.2.1
Material Theme 4.3.1

**Comment by mallowigi** [comment]
Fixed
