### ISSUE TITLE
Material UI is broken in PhpStorm 2019.2

### ISSUE THREAD

**Issue by nhatthm** [ChrisRM/material-theme-jetbrains#1298]
### Summary

Material UI is broken in PhpStorm 2019.2

### Expected behavior

PhpStorm works properly, UI is not broken

### Actual behavior

UI is broken

### Steps to reproduce (if needed)

1. First step

Open PhpStorm

2. Second step

Observe that the window is just blank, there is nothing else

You can also add Screenshots for a better understanding.

### Environment

```
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Licensed to XXX
Subscription is active XXX
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: PHPUnit code coverage, String Manipulation, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.paperetto.dash, name.kropp.intellij.makefile, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, BashSupport, de.espend.idea.php.annotation, de.espend.idea.php.phpunit, cz.daku.intellij.extraActions, com.intellij.kubernetes, fr.adrienbrault.idea.symfony2plugin, org.mule.tooling.intellij.raml, org.psliwa.idea.composer, org.toml.lang, ru.adelf.idea.dotenv, uk.co.ben-gibson.remote.repository.mapper
```

### Screenshot

![image](https://user-images.githubusercontent.com/1154587/62204569-bcc07180-b38d-11e9-9069-ce833db9c136.png)

### Notes

I can open Preferences > Plugins. If I disable Material UI and restart PhpStorm, the UI is back

**Comment by nhatthm** [comment]
OK the UI is back after I followed the suggestion in https://github.com/ChrisRM/material-theme-jetbrains/issues/1296

But now the title bar is kinda ugly :(

**Comment by mallowigi** [comment]
Please disable title bar
