### ISSUE TITLE
Padding in non-editor spaces

### ISSUE THREAD

**Issue by davidstanley01** [ChrisRM/material-theme-jetbrains#130]
Not an issue but a question...

With this theme, how would someone increase the padding and/or line-height of the sidebar project explorer (and other sidebar lists) as well as increase the padding around the icons in the various toolbars?

Thanks.

**Comment by blazeworx** [comment]
I mentioned this a while back also (https://github.com/ChrisRM/material-theme-jetbrains/issues/72). It was closed by @ChrisRM. He did however say he would consider adding an optional config/setting. Unfortunately, I haven't heard anything about it since. Any info if this can be achieved @ChrisRM ?

**Comment by mallowigi** [comment]
Is still feature still requested?

**Comment by blazeworx** [comment]
If there is a way to do it then yes. At least as a configurable option.

**Comment by andrzejsliwa** [comment]
please add configurable options, or stop plying with customs padding. After update its just waste of space.

**Comment by andrzejsliwa** [comment]
looks like there is already option: 
  "Compact Sidebar: Reduce line height between list items in sidebars"

**Comment by blazeworx** [comment]
Reduce line height? how does this option close this issue? we are talking about increasing the spacing .. not reducing it? see #72 (or am I missing something?)
