### ISSUE TITLE
[Enhancement] Full screen to hide title bar

### ISSUE THREAD

**Issue by timrspratt** [ChrisRM/material-theme-jetbrains#1300]
The recent update has introduced the title bar back, but it has also added it to full screen mode too. Would be great if it can hide when full-screen (on mac btw) as it currently looks like it shouldn't be there (maybe that's personal opinion though - open for a vote!)

Thanks 

![image](https://user-images.githubusercontent.com/20431294/62285513-a7ab1780-b44d-11e9-9b97-b5498ad0252d.png)

**Comment by mallowigi** [comment]
I'll do it

**Comment by mallowigi** [comment]
Should be fixed in 4.2.2

**Comment by ches** [comment]
This seems to be back for me in IntelliJ 2019.3, Material Theme plugin v4.10.0. Turned off the Themed Title Bar tweak as a workaround.
