### ISSUE TITLE
Double click header not resizing

### ISSUE THREAD

**Issue by sonersivri** [ChrisRM/material-theme-jetbrains#1302]
### Summary
Double click header not resizing

### Expected behavior

Resize the idea window

### Actual behavior

Not Resizing when uninstall resize is ok

### Environment

IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Lombook Plugin, com.samdark.intellij-visual-studio-code-dark-plus, com.thoughtworks.gauge, com.chrisrm.idea.MaterialThemeUI, BashSupport, Docker

**Comment by mallowigi** [comment]
Fixed in 4.2.2
