### ISSUE TITLE
Duplicate title bar

### ISSUE THREAD

**Issue by leaxoy** [ChrisRM/material-theme-jetbrains#1303]
After I upgrade to 4.2.2, there is a bug happened, duplicate title bar at welcome page, so and fullscreen page.
Here is the picture.
![xxx](https://i.loli.net/2019/08/04/43ekfqH6GJa17hP.png)

https://i.loli.net/2019/08/04/43ekfqH6GJa17hP.png

**Comment by mallowigi** [comment]
Yes I know. I have the same problem.

Can you provide more details about your system? Which JDK especially?

**Comment by leaxoy** [comment]
OS version is 10.15 beta 5, Goland is 2019.2, so jdk is bundled jbr jdk

**Comment by chinaxy1** [comment]
OS version 10.14.6, IDEA 2019.2 as same problem.

**Comment by mallowigi** [comment]
I think I found the issue. Not sure though since it depends on many factors.

I'll issue a release on Friday.

**Comment by leaxoy** [comment]
With version 4.3 there is another issue.
![QQ20190806-132038@2x.png](https://i.loli.net/2019/08/06/HUFaY41jTRfLQI7.png)

https://i.loli.net/2019/08/06/HUFaY41jTRfLQI7.png

**Comment by mallowigi** [comment]
4.3 was not supposed to be out. Something is not working with the gradle plugin, it should have uploaded only to the private repository, but oh well.

But I am testing the 4.3 at the moment and i can't reproduce. Can you provide more details about your environment?

**Comment by mallowigi** [comment]
Ok I managed to reproduce. Are you in Fullscreen mode ?

**Comment by leaxoy** [comment]
yes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nabeelio** [comment]
I'm seeing it after switching to the JDK suggested in [this comment](https://youtrack.jetbrains.com/issue/JBR-1174#focus=streamItem-27-3530165.0-0) for OSX, trying to fix the font rendering issue in the new IJ version. IJ info:

```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Runtime version: 11.0.2+9-b159.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by rtoomey-coatue** [comment]
I'm affected as well.  Using Material theme 4.2.2 with latest preview on Mojave:

```
IntelliJ IDEA 2019.2.1 Preview (Ultimate Edition)
Build #IU-192.6262.9, built on August 6, 2019
Runtime version: 11.0.2+9-b159.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
```

**Comment by rikiless** [comment]
The same here. Both on iMac and Macbook Pro.

**Comment by rtoomey-coatue** [comment]
Still present in 4.2.1, downgraded to 4.1 and the duplicate titlebar is gone.  I also noticed a _worse_ issue with the 2019.2.1 Preview where the file tabs were present but missing the name of the file.  Not handy to reproduce it now as I just got things working again 😊 but you might want to check that.  Thank you!

**Comment by nabeelio** [comment]
You can also disable the themed title bar, which is what I did.

**Comment by mallowigi** [comment]
4.3 should have been able to fix scenarios when you’re in full screen and you have no title bars in dialogs, as well as the duplicate title bars.

Please report if you have other title bars issues as well.
