### ISSUE TITLE
CheckStyle icons does not load properly

### ISSUE THREAD

**Issue by jun097kim** [ChrisRM/material-theme-jetbrains#1304]
### Expected behavior

CheckStyle icons should load properly.

### Actual behavior

CheckStyle icons does not load properly.

<img width="753" alt="checkstyle-icons" src="https://user-images.githubusercontent.com/16279779/62448795-8dea3700-b7a3-11e9-91aa-840e54b5f4e0.png">

### Environment

IntelliJ IDEA 2019.2 (Ultimate Edition)

**Comment by pmnanez** [comment]
I can confirm same problem with PyLint.
![image](https://user-images.githubusercontent.com/4487678/62866008-2b97b600-bd10-11e9-83df-c3e34265df90.png)

### Environment
PyCharm Professional 2019.2
