### ISSUE TITLE
Tab Height no longer goes down to 10 again

### ISSUE THREAD

**Issue by detwetter** [ChrisRM/material-theme-jetbrains#1305]
### Summary
The Tab Height option is not working correctly. 

### Expected behavior
Previous to the last 2 updates, the Tab Height could be set to as low as 10.

### Actual behavior
Currently I can only set the Tab Height as low as 18.

### Steps to reproduce (if needed)

![image](https://user-images.githubusercontent.com/29411391/62477268-a4c66480-b776-11e9-8553-120823da1132.png)

### Environment
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Subscription is active until April 2, 2020
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2476M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, jp.co.future.ideausqlfmt, jp.roundrop.sqlformatter, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, izhangzhihao.rainbow.brackets, org.psliwa.idea.composer

**Comment by mallowigi** [comment]
Really? 18 is the absolute minimum... Before that you can't even see the font.

Are you sure you're not talking about the project line height ?

**Comment by detwetter** [comment]
Yes, really!  10 matches the project view height, and has been my setting for tab height since you implemented that value a while ago.

**Comment by detwetter** [comment]
For me, there is a ton of space around the tab name with the value set to 18.  Oh and I use vertical tabs.
![image](https://user-images.githubusercontent.com/29411391/62488296-f203ff80-b791-11e9-8364-61d6598e16a5.png)

**Comment by mallowigi** [comment]
alright i can see that. I'll include it in the next release

**Comment by detwetter** [comment]
Thanks so much @mallowigi !!!

**Comment by detwetter** [comment]
BTW, I see you added the ability to set it to 10 again, unfortunately it's still the same size as 18.  Interestingly, 23 & 24 are smaller then 18 & 10, but still not as small as the old 10.
