### ISSUE TITLE
Project view font size value is not respected

### ISSUE THREAD

**Issue by kstratis** [ChrisRM/material-theme-jetbrains#1306]
### Summary

Setting a custom value in the `Font Size` field under `Project View` is not working.

### Expected behavior

Font sizes should be respected. For example setting a value of `6` should make the font look really small in the project view tree.

### Actual behavior

The font size value is not respected and I get a fixed size of about 13-14pt.

### Steps to reproduce (if needed)

* Activate Material theme plugin
* Use Material Oceanic
* Change the Font size value in `Appearance & Behavior -> Material Theme -> Advanced Settings -> Project View -> Font Size`

![Screenshot 2019-08-05 19 18 42](https://user-images.githubusercontent.com/1859806/62479900-2b029b00-b7b7-11e9-91d6-aa2714aa0f72.png)

### Environment

```
RubyMine 2019.2
Build #RM-192.5728.104, built on July 23, 2019

Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: bigger.font.in.project.view=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, intellij.prettierJS
```
Using the latest Material Theme UI plugin version v4.2.2.

**Comment by mallowigi** [comment]
It works, it's just that you have to restart to apply it.

However I do remember that it worked without needing to restart so I'll investigate

**Comment by krims0n32** [comment]
I cannot get this to work, the setting does not seem to have any effect, restarting does not help either.

PyCharm 2019.2, material 4.5.1.

**Comment by mallowigi** [comment]
Please make sure you don’t have the “bigger.fonts.in.project.view” in the registry (ctrl shift A -> Registry)

--
Elior

**Comment by krims0n32** [comment]
I had this enabled, but after disabling and restarting, font size change still does not have any effect. I can change the font size of tabs and such, but not the project view.

> Please make sure you don’t have the “bigger.fonts.in.project.view” in the registry (ctrl shift A -> Registry)
> […](#)
> -- Elior
> On 15 Oct 2019, 21:21 +0300, krims0n32 ***@***.***>, wrote: I cannot get this to work, the setting does not seem to have any effect, restarting does not help either. PyCharm 2019.2, material 4.5.1. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mallowigi** [comment]
That’s really weird... can you check with factory settings see if it works there?

--
Elior

**Comment by krims0n32** [comment]
Reverted to factory by deleting the .PyCharm2019.2 folder, restarted, reinstalled material plugin. Adjusted project view font size, restarted, no change.

**Comment by mallowigi** [comment]
Hmmm I have no idea... are the material fonts disabled ?

--
Elior

**Comment by krims0n32** [comment]
Disabled/enabled makes no difference. I can see something is done to the project view font when I apply the font size, it seems to flash for a bit, but then it returns to its original size.

Anyway, not a big issue for me, just wondering why it doesn't work as expected.

> Hmmm I have no idea... are the material fonts disabled ?
> […](#)
> -- Elior
> On 15 Oct 2019, 21:49 +0300, krims0n32 ***@***.***>, wrote: Reverted to factory by deleting the .PyCharm2019.2 folder, restarted, reinstalled material plugin. Adjusted project view font size, restarted, no change. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
