### ISSUE TITLE
Scrollbar border color (4.2.2)

### ISSUE THREAD

**Issue by ipmrlx** [ChrisRM/material-theme-jetbrains#1307]
How to change scrollbar border color?
phpstorm 2019.3
<img width="99" alt="Screen Shot 2019-08-06 at 13 43 22" src="https://user-images.githubusercontent.com/4567995/62533802-38b82f00-b850-11e9-8f05-ae529c8a6a8b.png">
<img width="1115" alt="Screen Shot 2019-08-06 at 13 42 59" src="https://user-images.githubusercontent.com/4567995/62533803-38b82f00-b850-11e9-9b16-e48e2ec901c5.png">
<img width="1058" alt="Screen Shot 2019-08-06 at 13 45 04" src="https://user-images.githubusercontent.com/4567995/62533890-6c935480-b850-11e9-940a-166a77a9938f.png">
<img width="1056" alt="Screen Shot 2019-08-06 at 13 44 31" src="https://user-images.githubusercontent.com/4567995/62533891-6c935480-b850-11e9-9057-3fae526cf9b5.png">

**Comment by mallowigi** [comment]
Settings > Appearance > Color Scheme > General > Scrollbars

**Comment by ipmrlx** [comment]
> Settings > Appearance > Color Scheme > General > Scrollbars

Screenshot 3. Dont't work (

**Comment by mallowigi** [comment]
I see... it's jetbrains bug then.

Please open an issue in their YouTrack

**Comment by amleaver** [comment]
Looks like there are several open issues relating to setting scrollbar colours in YouTrack [but this workaround](https://youtrack.jetbrains.com/issue/IDEA-140850#focus=streamItem-27-3374621.0-0) allowed me to change the editor scrollbar colour by effectively exporting the editor colour scheme, manually tweaking the scrollbar related entries and re-importing it.

If you switch Material themes after doing this then you'll need to remember to manually set the editor colour scheme as well.

**Comment by mallowigi** [comment]
Yes but they should add it to the options so it’s their bad, basically. In the past I added myself a page for the scrollbars so you would have been able to do it, but I deprecated it since it’s not really my job to do so.

**Comment by amleaver** [comment]
I don't disagree. I was just linking to an official workaround to a known Intellij bug which might benefit other people having this problem.

**Comment by kdion4891** [comment]
Heres how I fixed it using the material darker theme on Mac.

Open up `/Users/USERNAME/Library/Preferences/PhpStorm2019.2/colors/_@user_Material Darker.icls` and edit the following lines like so:

```
    <option name="ScrollBar.Mac.Transparent.hoverThumbBorderColor" value="" />
    <option name="ScrollBar.Mac.Transparent.hoverThumbColor" value="" />
    <option name="ScrollBar.Mac.Transparent.hoverTrackColor" value="" />
    <option name="ScrollBar.Mac.Transparent.thumbBorderColor" value="" />
    <option name="ScrollBar.Mac.Transparent.thumbColor" value="" />
    <option name="ScrollBar.Mac.Transparent.trackColor" value="" />
    <option name="ScrollBar.Mac.hoverThumbBorderColor" value="" />
    <option name="ScrollBar.Mac.hoverThumbColor" value="" />
    <option name="ScrollBar.Mac.hoverTrackColor" value="" />
    <option name="ScrollBar.Mac.thumbBorderColor" value="" />
    <option name="ScrollBar.Mac.thumbColor" value="" />
    <option name="ScrollBar.Mac.trackColor" value="" />
```

Save the file and restart PHPStorm.
