### ISSUE TITLE
Themed title bar is no more anti-aliased

### ISSUE THREAD

**Issue by rikiless** [ChrisRM/material-theme-jetbrains#1309]
When I upgraded to PhpStorm 2019.2 and updated all plugins (currently Material Theme 4.3.1) I noticed that a font is rastered differently as UI/sidebar/menus/settings and code editor.

Using macOS High Sierra (10.13.6).

![Screen Shot 2019-08-08 at 06 25 27](https://user-images.githubusercontent.com/589851/62675248-8181fc00-b9a6-11e9-940e-02f61063f378.png)
![Screen Shot 2019-08-08 at 06 31 30](https://user-images.githubusercontent.com/589851/62675249-821a9280-b9a6-11e9-8133-718b4113e52d.png)

**Comment by mallowigi** [comment]
I’ve seen that too but I thought it was only my imagination,

**Comment by rikiless** [comment]
On my other macOS devices (Mojave, up to date) everything is ok. Problem persist only on High Sierra.

**Comment by mallowigi** [comment]
Ow. Then I'm afraid it will be harder to test...

**Comment by mallowigi** [comment]
should be better now ?

**Comment by rikiless** [comment]
Thanks. Title bar is ok in 4.3.4.
