### ISSUE TITLE
Tabs too small

### ISSUE THREAD

**Issue by codegrady** [ChrisRM/material-theme-jetbrains#1310]
When I upgraded to IntelliJ IDEA 2019.2.1 Preview and updated all plugins (currently Material Theme 4.3.1)
 I noticed File path bar cover the title bar in editor, I can't see filename . 
 But when disable Material UI , normal.
macOS 10.14.6
<img width="1048" alt="material" src="https://user-images.githubusercontent.com/7309053/62679567-79967c00-b9e7-11e9-828c-309509974d98.png">

**Comment by mallowigi** [comment]
Can you tell me what is the height of the tabs ? (Settings > Appearance > Material Theme > Tabs > Tab Height)

**Comment by codegrady** [comment]
32.
But, I tried other height. it doesn't works.

**Comment by mallowigi** [comment]
I see. So this is something from the 2019.2.1

I'll start working on it

**Comment by mallowigi** [comment]
[Material Theme-4.3.2.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3480754/Material.Theme-4.3.2.zip)

Please find attached an hotfix restoring the tabs. The tab height setting doesn't work but at least you can see the tabs again

**Comment by codegrady** [comment]
OK!  thank you...

**Comment by mallowigi** [comment]
Fixed upgrading issues with tabs. I'm also experimenting a new versioning system to be more in sync with Jetbrains updates. Not sure how it's going to turn off, but lets' try.

**Comment by MrJmpl3** [comment]
I have same error but with 4.3.5 , in the 4.3.2 work perfect .. please downgrade

**Comment by mallowigi** [comment]
If you have the eap please use the 4.4 versions. Otherwise use the 4.3 versions

**Comment by MrJmpl3** [comment]
I use 4.3.5 with WebStorm 2019.2.1 was released yesterday

**Comment by misabiko** [comment]
I updated to 4.4.6 and now have the same issue.
MrJmpl3's fix doesn't seem to work, changing the tabs height doesn't do anything.

![Screenshot_2019-08-24_02-28-17](https://user-images.githubusercontent.com/5178073/63633499-99e54e00-c617-11e9-94ed-3dde46adc7d5.png)

**Comment by mallowigi** [comment]
Please make sure you have a Tab Height of more than 18, restart the IDE and check if it works. If not, please connect to the Slack Channel so we can pinpoint this issue.
