### ISSUE TITLE
Ui parts duplicated behind tab bar when activating "Accent Mode"

### ISSUE THREAD

**Issue by Vortilion** [ChrisRM/material-theme-jetbrains#1311]
### Summary
When I activate the Accent Mode, some other parts of the Intellij UI get duplicated and put behind the tab bar above the editor. When hovering over it it flashes and when clicking on lines in the editor it changes, sometimes I see the file path bar, sometimes parts of the editors' content, other times the footer bar...

![materialthemeui_error](https://user-images.githubusercontent.com/400503/62688341-f1a17980-b9c8-11e9-8d97-b93187affaf8.jpg)

### Expected behavior
Not having a bar visible through the tab bar. ;-)

### Actual behavior
see summary.

### Steps to reproduce (if needed)
Activate "Accent Mode".

### Environment
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Licensed to XXXXXXXXXXXXXXX
Subscription is active until XXXXXXXXXXXXXXXX
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1961M
Cores: 8
Registry: debugger.watches.in.variables=false, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support, CMD Support, com.alayouni.ansiHighlight, com.intellij.ideolog, com.intellij.plugins.watcher, mobi.hsz.idea.gitignore, Karma, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.lang.ejs, ua.in.dej.myEmmet, zielu.svntoolbox

Material Theme UI 4.3.1

Config Files:
[options.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3480684/options.zip)

**Comment by mallowigi** [comment]
Oo WTF... ok but it will take less priority than other bugs. Please disable the option for now

**Comment by Vortilion** [comment]
That's ok, just wanted to notify you guys.

**Comment by YuiiraX** [comment]
Not only in accent mode, it's happening for me on any intellij windows that's not in focus

**Comment by SuperDJ** [comment]
This is also appearing in the menu bar:
![image](https://user-images.githubusercontent.com/6484766/62930765-5ab83100-bdbd-11e9-91c5-685ae53065fc.png)

**Comment by Sylk** [comment]
This is a windows 10 problem. Oh lordy @mallowigi good luck to solving this one, when you have a pr in, I'd be interested to see what the resolution is.

**Comment by develerik** [comment]
@Sylk this is not a windows 10 problem. I have the same issue on Arch Linux.
