### ISSUE TITLE
Tabs not showing filename

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#1313]
### Summary

It seems the tabs are not showing correctly (see screenshot)

### Expected behavior

Expecting to see the filename appear in tabs

### Actual behavior

As demonstrated in the screeshot, the tabs are not fully displayed, including the actual filename.  All that I can see is the active tab highlight

### Steps to reproduce (if needed)

1. Using the 2019.2 release (also tried with Preview 1)
2. Open two or more files
3. You will see the tabs title do not appear

You can also add Screenshots for a better understanding.

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/183153/62731726-ae9ad280-b9d7-11e9-882b-a3b054de3d18.png">

### Environment

<img width="686" alt="image" src="https://user-images.githubusercontent.com/183153/62731960-1bae6800-b9d8-11e9-842f-0340cabbf5aa.png">

PhpStorm 2019.2.1 Preview
Build #PS-192.6262.16, built on August 8, 2019
Licensed to Mike Erickson
Subscription is active until August 12, 2019
Runtime version: 11.0.3+12-b304.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: GrepConsole, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.devwook.copy_path_helper, com.dubreuia, com.karateca.jstoolbox, com.line.plugin.auto.align, com.paperetto.dash, com.vexus2.intellij.marked, com.wakatime.intellij.plugin, io.cacher.intellij, mobi.hsz.idea.gitignore, net.vektah.codeglance, BashSupport, com.dmarcotte.handlebars, com.axeldev.php1Up, com.wix.eslint, intellij.prettierJS, org.sylfra.idea.plugins.linessorter, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
Duplicate https://github.com/ChrisRM/material-theme-jetbrains/issues/1310

**Comment by mikeerickson** [comment]
@mallowigi Thanks for the quick fix, I have installed 4.3.2 and it has cured the issue
