### ISSUE TITLE
Git Compare header problem

### ISSUE THREAD

**Issue by sonersivri** [ChrisRM/material-theme-jetbrains#1315]
### Summary
4.3.1 plugin version
Git Compare header problem 

### Actual behavior
Header close extend button location is wrong

### Steps to reproduce (if needed)

1. First step
![image](https://user-images.githubusercontent.com/682447/62764082-ba4cce80-ba95-11e9-9c96-c6ed434ee165.png)

git compare panel
Version Control CTRL + D 

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Lombook Plugin, com.samdark.intellij-visual-studio-code-dark-plus, com.thoughtworks.gauge, com.chrisrm.idea.MaterialThemeUI, BashSupport, Docker

**Comment by mallowigi** [comment]
Are you in fullscreen mode ?

**Comment by sonersivri** [comment]
No Not fullscreen mode

**Comment by mallowigi** [comment]
Will be fixed next version
