### ISSUE TITLE
Porting on Gmail, Google Calendar, Trello

### ISSUE THREAD

**Issue by CharlieEtienne** [ChrisRM/material-theme-jetbrains#1316]
Hi and thanks for your amazing work!

For Material theme addicts, I redesigned some well known tools with material theme colors.
3 themes available: Oceanic, Darker, Palenight

### Gmail
https://userstyles.org/styles/174257/material-dark-gmail

### Google Calendar
https://userstyles.org/styles/174228/material-dark-google-calendar

### Google Keep
https://userstyles.org/styles/174291/material-dark-google-keep

### Trello
https://userstyles.org/styles/167605/material-dark-trello

Probably more websites coming. (Github should be the next one)

**Comment by mallowigi** [comment]
That's good but for consistency you should rename your "Dark" theme to "Oceanic"

**Comment by CharlieEtienne** [comment]
> That's good but for consistency you should rename your "Dark" theme to "Oceanic"

@mallowigi thanks, it's done

**Comment by mallowigi** [comment]
Thanks, done
