### ISSUE TITLE
idea color scheme does not work

### ISSUE THREAD

**Issue by quaider** [ChrisRM/material-theme-jetbrains#1317]
my idea version is 2019.2， when i changed the Editor -> Color schema -> Java  schema, it can't work，i apply and restart it serval timrs, but still not work, what should i do?

<img width="1243" alt="屏幕快照 2019-08-10 下午7 44 31" src="https://user-images.githubusercontent.com/12459496/62821429-51557b80-bba7-11e9-9bba-d206bfcf7948.png">

**Comment by mallowigi** [comment]
What exactly did you change ?

**Comment by quaider** [comment]
it's my settings error, i am sorry!
