### ISSUE TITLE
"Find everywhere" section header colour not distinguishable

### ISSUE THREAD

**Issue by errikos** [ChrisRM/material-theme-jetbrains#1318]
### Summary

In the "find everywhere" window, the section headers ("Recent files", "Classes", etc.) colour is not distinguishable from the background. This is true for all variants of the theme and for all IDEs (reproduced on IntelliJ, Pycharm, Clion).

Here is a screenshot of the Dracula variant:

<img width="716" alt="Capture d’écran 2019-08-11 à 13 46 45" src="https://user-images.githubusercontent.com/5298184/62833467-8b725c00-bc3f-11e9-977d-5b2883f01493.png">

### Environment

```
CLion 2019.2
Build #CL-192.5728.100, built on July 23, 2019
Licensed to Ergys Dona
Subscription is active until July 5, 2020
For educational use only.
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 4070M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.4lex4.intellij.solarized, com.chrisrm.idea.MaterialThemeUI, com.vermouthx.idea, org.intellij.plugins.markdown, org.rust.lang
```

Material theme version: 4.3.2, all settings default, Dracula variant.

**Comment by mallowigi** [comment]
Fixed, will be available in next version
