### ISSUE TITLE
JSX is not properly highlighted in Dark themes

### ISSUE THREAD

**Issue by Anahkiasen** [ChrisRM/material-theme-jetbrains#132]
Using PHPStorm 10, JSX looks like this, same in Darker theme. Light theme looks fine.

![screen shot 2015-12-09 at 10 43 18](https://cloud.githubusercontent.com/assets/1321596/11681851/b2a2b766-9e61-11e5-92af-efcefcd5ee23.png)

**Comment by Anahkiasen** [comment]
Seems it's actually XML highlighting itself that is off:

![screen shot 2015-12-09 at 10 44 44](https://cloud.githubusercontent.com/assets/1321596/11681891/ef6c37da-9e61-11e5-81fe-e9ed2bfb1276.png)

Tried to reinstall the theme but same thing.

**Comment by ChrisRM** [comment]
I'll be fixing a lot of issues this weekend. This just made it to the list.

**Comment by nonameolsson** [comment]
Isn't this the same as https://github.com/ChrisRM/material-theme-jetbrains/issues/136? Because it still has some problems.
