### ISSUE TITLE
Title Bar is not anti-aliased.

### ISSUE THREAD

**Issue by bcorcoran** [ChrisRM/material-theme-jetbrains#1321]
OS X Mojave 10.14.6
PhpStorm 2019.2
Material Theme 4.3.2

The title bar is no longer anti-aliased... it actually looks so bad it's distracting. I think this is the same issue as #1309 

I have done nothing but update the theme. I know it is the theme because I disabled the theme and restarted and presto... anti-aliased titlebar!

Not sure if it helps, but I am not running a retina display. I have a mac mini with a 3840x1600 dell display (so `@1x` rendering).

![Screen Shot 2019-08-13 at 22 56 10](https://user-images.githubusercontent.com/313697/62991419-8cf97b00-be1d-11e9-869e-73f3dacf3be4.png)

**Comment by mallowigi** [comment]
[Material Theme-4.3.3.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3500093/Material.Theme-4.3.3.zip)

Please try this and tell me if it solves the issue

**Comment by mallowigi** [comment]
Please approve so i can release an update

**Comment by errikos** [comment]
Title-bar is OK for me with the above zip.

**Comment by bcorcoran** [comment]
Sorry for the delay - I went to sleep. I just upgraded to 4.3.4 via phpstorm and it is fixed!
