### ISSUE TITLE
Material Theme breaks Show Git History for Selection in RubyMine

### ISSUE THREAD

**Issue by jasonheecs** [ChrisRM/material-theme-jetbrains#1322]
### Summary
The "Show History for Selection" option in RubyMine does not work with Material Theme.

### Expected behavior
A window should show up with the Git history of the selected text

### Actual behavior
A blank window shows up.

### Steps to reproduce (if needed)
- Select a block of code
- Right Click -> Git -> Show History of Selection
Screencap of issue: https://recordit.co/FbptauC2AA

### Environment
```
RubyMine 2019.2
Build #RM-192.5728.104, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.valueTooltipAutoShowOnSelection=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: PlantUML integration, com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.intellij.plugins.hcl, com.dmarcotte.handlebars, com.emberjs, ru.adelf.idea.dotenv
```

material_theme.xml:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="80cbc4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="userId" value="-7719647a:1666670d347:-8000" />
    <option name="version" value="4.3.2" />
  </component>
</application>
```

[options.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3500696/options.zip)

**Comment by mallowigi** [comment]
Are you in full screen by chance ?

**Comment by jasonheecs** [comment]
Nope, I'm in windowed mode. Tried with full screen, same issue occurs.

**Comment by mallowigi** [comment]
[Material Theme-4.3.3.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3500979/Material.Theme-4.3.3.zip)

Can you try with this version ?

**Comment by jasonheecs** [comment]
Hi, same issue occurs even on that Material Theme version :(

**Comment by jasonheecs** [comment]
After more experimentation, it seems like the git history shows up after full screening the popup window:

https://recordit.co/jeSeW5Km4b

**Comment by mallowigi** [comment]
Weird I can’t reproduce it but there is a huge bug regarding the transparent title bar, I can’t find a fix at the moment (because it’s a jetbrains experimental feature and they declined fixing it) so I’ve decided to disable it by default and add an alert for people willing to enable it.

Sorry for the trouble.
