### ISSUE TITLE
Diff of comments isn't sensible

### ISSUE THREAD

**Issue by DimaDK24** [ChrisRM/material-theme-jetbrains#1323]
### Summary
Not nice diff of comments in Atom One Dark theme

### Expected behavior
It's easy to read modified comments lines

### Actual behavior
It's difficult to read modified comments lines
![image](https://user-images.githubusercontent.com/25607790/63025642-4f92fd00-beb2-11e9-82ed-4d7b715458a2.png)

### Steps to reproduce (if needed)

1. Create commit with comment
2. Change this comment in next commit
3. View diff of the second commit

### Environment

WebStorm 2019.2
Build #WS-192.5728.87, built on July 22, 2019
Licensed to ****
Subscription is active until  ****
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, codes.rudolph.idea.cfg, com.chrisrm.idea.MaterialThemeUI, mobi.hsz.idea.gitignore, BashSupport, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
There is no way to change this. The background color applies no matter what the text is, comments or not comments.

If you want you can change the colors in Settings > Color Scheme > Diff and Merge

**Comment by DimaDK24** [comment]
Thanks, will try such solution
