### ISSUE TITLE
window title bar background color and font size in pycharm

### ISSUE THREAD

**Issue by yxd0018** [ChrisRM/material-theme-jetbrains#1324]
1. The plugin works fine in Intellij Idea, but when in pycharm 2018, after installation, it seems the window title bar background color is too bright and nowhere to change it. 
![material_problem1](https://user-images.githubusercontent.com/1706618/63030977-46d60300-be81-11e9-8cf9-b25132759a68.png)
![material_problem2](https://user-images.githubusercontent.com/1706618/63030978-46d60300-be81-11e9-8a63-3dcbfa50074c.png)

2. The plugin for pycharm doesn' t have font size like that for Idea. The font in the tab list is too small to see. 
![material_problem3](https://user-images.githubusercontent.com/1706618/63031299-d1b6fd80-be81-11e9-807a-e02070d04b6a.png)

**Comment by mallowigi** [comment]
Hi, 

There is no support for 2018 versions anymore.

Please update the Ide to a recent version
