### ISSUE TITLE
Bad rendering on Title Bar, Notifications, Editor Tabs

### ISSUE THREAD

**Issue by vemilyus** [ChrisRM/material-theme-jetbrains#1326]
### Summary

Rendering of the title bar, editor tabs, and notifications is completely broken. See the attached screenshots for the results.

This occurs both on Windows 10 and Elementary OS (Ubuntu) with different degrees of brokenness.

On both the active theme is "Arc Dark" but the problems are the same with other themes.

1. Windows
![W10-TitleBarEditorTabs](https://user-images.githubusercontent.com/7115009/63060169-c26f9880-bef1-11e9-88d3-75cda870d5c9.png)

There the title bar doesn't render correctly when the window is out of focus and the editor tabs disappeared.

2. Elementary OS
![Elementary-EditorTabs](https://user-images.githubusercontent.com/7115009/63060152-b84d9a00-bef1-11e9-8762-7406db16ee89.png)

![Elementary-Notifications](https://user-images.githubusercontent.com/7115009/63060223-e632de80-bef1-11e9-8953-2d33164fd325.png)

### Environment

Plugin version is `4.3.4` on both systems

[config_files.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3503571/config_files.zip)

1. Windows 10
IntelliJ IDEA 2019.2.1 Preview (Ultimate Edition)
Build #IU-192.6262.9, built on August 6, 2019
Licensed to ***
Subscription is active until April 8, 2020
Runtime version: 11.0.3+12-b304.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 8125M
Cores: 8
Registry: bigger.font.in.project.view=true, svn.filter.unique.roots.by.url=true, terminal.buffer.max.lines.count=1000000, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0, tabs.alphabetical=true
Non-Bundled Plugins: Copyright, com.jetbrains.jbre.bintray.downloader, com.jetbrains.plugins.ini4idea, mobi.hsz.idea.gitignore, org.antlr.intellij.plugin, org.jetbrains.idea.grammar, BashSupport, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, com.dmarcotte.handlebars, com.intellij.lang.jsgraphql, com.intellij.plugins.html.instantEditing, org.majki.intellij.ldapbrowser, org.toml.lang, org.rust.lang, ru.artyushov

2. Elementary OS (Ubuntu 18.04.2 LTS)
IntelliJ IDEA 2019.2.1 Preview (Ultimate Edition)
Build #IU-192.6262.9, built on August 6, 2019
Licensed to ***
Subscription is active until April 8, 2020
Runtime version: 11.0.3+12-b304.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.2.8-050208-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: by.vkatz.decorate_mode_switcher, mobi.hsz.idea.gitignore, com.chrisrm.idea.MaterialThemeUI

**Comment by mallowigi** [comment]
If you are in 2019.2.1 preview please download 4.4.3 since 4.3 is for the release candidate.

**Comment by mallowigi** [comment]
I must admit that I never tested on windows yet, so my bad but I’ll try to do it as soon as I can

**Comment by mallowigi** [comment]
In your second screenshot, you have the Accent Mode enabled. This mode is still broken, as I have opened another issue about it.

**Comment by vemilyus** [comment]
Where do I get version 4.4.3? It's not on the marketplace and there's no build artifact on GitHub.

**Comment by mallowigi** [comment]
https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions

**Comment by fluffynuts** [comment]
Just a note that I experience the same sort of thing:

![image](https://user-images.githubusercontent.com/4669340/63094042-8e36bf00-bf67-11e9-8135-8ee768be605e.png)

I can't update to 4.4.3 because that requires an EAP version of Rider, which I'm not willing to take a chance on right now.

Of course, the Lite variant of Material UI Theme works -- but I really like the tweaks to reduce whitespace in tree views, as well as the more minimal tree/node icon. Part of the reason for adding a comment here is so that I can be notified if there are changes here. @mallowigi please post here when the raised issues are resolved -- no rush, I'd just appreciate to know (: Rider won't notify me since I no longer have the full plugin installed (tried uninstalling to install the eap).

**Comment by mallowigi** [comment]
The 4.4.3 only fixes the issue with the tabs becoming too small, the issue with opacity is not yet resolved.

**Comment by Sylk** [comment]
@mallowigi please fix it when you have the chance. Thank you.

**Comment by fluffynuts** [comment]
@Sylk in the mean-time, the lite theme is quite good -- I really just want to be able to tweak spacings and such: the material spacings are far too information-sparse for me :/

**Comment by Sylk** [comment]
@fluffynuts the light theme has the exact same problem.

**Comment by SuperDJ** [comment]
Might be related to https://github.com/ChrisRM/material-theme-jetbrains/issues/1311

**Comment by fluffynuts** [comment]
@sylk I think we may be talking past each other. I don't mean the light theme from the full plugin, I mean the lite theme plugin, which has all of the same themes, but doesn't have the customisation tweaks. Search for it in available plugins.

**Comment by mallowigi** [comment]
should be fixed

**Comment by fluffynuts** [comment]
@mallowigi thanks! I'm assuming this only applies to the current EAP release? It's not available for download from the Plugins dialog and a manual install says "not supported".

If so, thanks anyway -- I'll wait for the current EAP to go mainstream. I used to EAP Rider, but the constant IDE exceptions (blinking icon down the bottom right) get a bit much after a while :/

**Comment by mallowigi** [comment]
Hmmmmm have you tried the version 4.3.5? The 4.4 version is for 2019.2.1+ but the 4.3 should still support 2019.2

**Comment by fluffynuts** [comment]
I'm not seeing 4.3.5 for download:
![image](https://user-images.githubusercontent.com/4669340/63524280-066b2a80-c4fc-11e9-943b-dd9af9ba6549.png)

what am I missing?

**Comment by mallowigi** [comment]
Something happened and I deleted the release. I'll redeploy soon enough

**Comment by fluffynuts** [comment]
@mallowigi I just got an update to 4.4.6 -- working nicely. Thanks for sorting this out :+1:

**Comment by fluffynuts** [comment]
my mistake -- I see Rider has 4.2.2 in it right now, which is obviously not right. I must have been high earlier ^^
