### ISSUE TITLE
RubyMine editor tabs not showing

### ISSUE THREAD

**Issue by MattIPv4** [ChrisRM/material-theme-jetbrains#1327]
### Summary

RubyMine editor tabs aren't displaying file names properly.
I have reset to default settings and this still occurs.
Disabling the plugin allows the tabs to render correctly.

### Expected behavior

Tabs render correctly (screenshot from WebStorm)
![image](https://user-images.githubusercontent.com/12371363/63169536-f69ca380-c02e-11e9-92a1-99bde1efe523.png)

### Actual behavior

Tabs aren't showing file names with plugin enabled
![image](https://user-images.githubusercontent.com/12371363/63169560-0320fc00-c02f-11e9-9878-338493d3cd2f.png)

### Steps to reproduce (if needed)

1. Using the 2019.2.1 release of RubyMine
2. Install plugin (4.3.4) from JB
3. Open file
4. Observe that tab does not render

You can also add Screenshots for a better understanding.

### Environment

RubyMine 2019.2.1 RC
Build #RM-192.6262.39, built on August 15, 2019
Licensed to Matthew Cowley
Subscription is active until September 16, 2019
For educational use only.
Runtime version: 11.0.3+12-b304.39 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, BashSupport, NodeJS, com.emberjs

[config.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3509704/config.zip)

**Comment by mallowigi** [comment]
Please update to 4.4.3. I don't know why it doesn't give you that the update is available.

**Comment by MattIPv4** [comment]
@mallowigi Both RubyMine & WebStorm are showing 4.3.4 as latest, where do I get 4.4.3 from?

**Comment by mallowigi** [comment]
From the plugins page in plugins.jetbrains.com

**Comment by MattIPv4** [comment]
@mallowigi That also has 4.3.4 as the latest?

**Comment by MattIPv4** [comment]
Ah, found it under versions, weird that it think 4.3.4 is a higher version that 4.4.3
