### ISSUE TITLE
How to change language keyword color for specific theme?

### ISSUE THREAD

**Issue by daggerok** [ChrisRM/material-theme-jetbrains#1329]
Hello!

Sorry if there are no place for questions... I have a quick one:
I like Material Darker high contrast theme, thank you for it! But I cannot understand how can I change `this` keyword color (now it has look and feel like not compiling / broken code):

![image](https://user-images.githubusercontent.com/2445604/63214206-eca59e00-c11d-11e9-8b40-bb5b57cb56c2.png)

can you please tell me how I can re-configure its color to something less error-like?

Thanks!

![image](https://user-images.githubusercontent.com/2445604/63214030-f4644300-c11b-11e9-88df-6eea88ff25a4.png)

* Plugin version 4.3.4

---
Regards,
Maksim

**Comment by mallowigi** [comment]
Check in Color Scheme Settings > Java Additions

**Comment by daggerok** [comment]
Thanks a lot!

`CCBBAA` looks nicer!
