### ISSUE TITLE
[BUG] PhpStorm 10.0.2 Update

### ISSUE THREAD

**Issue by vinkla** [ChrisRM/material-theme-jetbrains#133]
In the latest version of PhpStorm constructor variables looks weird. Is it only for me or is someone else having the same issue? I'm using the Darker theme.

<img width="414" alt="screen shot 2015-12-11 at 11 03 21 am" src="https://cloud.githubusercontent.com/assets/499192/11741094/0266f442-9ff7-11e5-8795-872072bcd6bb.png">

**Comment by borNfreee** [comment]
+1.
This is for all function/method parameters.

**Comment by vinkla** [comment]
This can be fixed in *Preferences > Editor > Colors & Fonts > PHP* and then select parameter.

**Comment by kstratis** [comment]
Yes. It can be fixed but shouldn't be fixed by us.

**Comment by vinkla** [comment]
Yeah, just wanted to let you know.

**Comment by ChrisRM** [comment]
I'm on it!

**Comment by vinkla** [comment]
:+1:

**Comment by hedii** [comment]
+1
<img width="419" alt="capture d ecran 2015-12-14 a 10 45 26" src="https://cloud.githubusercontent.com/assets/5358048/11777668/2e54b282-a250-11e5-99e8-298b8c7eced9.png">

**Comment by kevinjbayer** [comment]
I'm not sure if I need to create a new issue, but the RubyMine 8.0.2 update seems to have really messed up the theme. I have a lot of code that's showing up with a white background that makes it nearly unreadable.

**Comment by YozhEzhi** [comment]
![Color bug](http://dl1.joxi.net/drive/0001/1889/128865/151222/2ed0dbe0cf.jpg)

+1

**Comment by aaemnnosttv** [comment]
+:100:

**Comment by brunodevel** [comment]
What is the correct color for the parameters?

**Comment by sergeyklay** [comment]
+1

**Comment by YozhEzhi** [comment]
@ChrisRM Thank you!
