### ISSUE TITLE
checkbox bug

### ISSUE THREAD

**Issue by Abdelraman** [ChrisRM/material-theme-jetbrains#1330]
![Untitled](https://user-images.githubusercontent.com/4821833/63216290-20fe6780-c0e8-11e9-941d-b84ef2a463ab.png)

checkbox appears like this after importing settings. this issue is not found if i remove all my settings.
unfortunately i need some live templates and extra settings to import but this issue happened

**Comment by mallowigi** [comment]
Weird. Is this happening if you change the font?

**Comment by Abdelraman** [comment]
After some investigation it seems to happen after increasing the font size of the UI
![Annotation 2019-08-17 233116](https://user-images.githubusercontent.com/4821833/63217462-bb1bdb00-c0fb-11e9-84ed-6a88b445d2a9.jpg)

**Comment by dionysous** [comment]
Yes, for me, it is the same. I can change the font-family without problems, but when I change the font-size, it breaks.

**Comment by Abdelraman** [comment]
any updates? it seems to happen when also using material component in the components tab

**Comment by mallowigi** [comment]
Yeah yeah I managed to reproduce, but so far could not find a solution that would not break users not using scaled mode.

The best way would be to replace checkboxes with icons but honestly I don't want to do that.

**Comment by Abdelraman** [comment]
Can we have as an option whether to show an icon or normal check boxes ? Thanks for your efforts

**Comment by Abdelraman** [comment]
Thanks a lot for your great effort but unfortunately it does not seem to work with 2019.2.3 versions (latest version by that day)

**Comment by mallowigi** [comment]
No, I am not releasing fixes for old IDEs, please download the EAP or wait for the release.
