### ISSUE TITLE
Exception Name: JavaNativeException

### ISSUE THREAD

**Issue by chinaerserver** [ChrisRM/material-theme-jetbrains#1332]
The newest version 4.4.4 of plugins . Appear on any of jetbrain IDE (e.g. IDEA Webstorm) . Has the same exception as  follows up:

Exception Name: JavaNativeException
Description: java.lang.IllegalArgumentException: null source
	at java.base/java.util.EventObject.<init>(EventObject.java:56)
	at java.desktop/java.awt.AWTEvent.<init>(AWTEvent.java:317)
	at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:286)
	at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:244)
	at java.desktop/sun.lwawt.macosx.LWCToolkit.invokeAndWait(LWCToolkit.java:804)
	at java.desktop/sun.lwawt.macosx.CInputMethod.characterIndexForPoint(CInputMethod.java:777)

User Info: (null)

0   CoreFoundation                      0x00007fff42fd12fd __exceptionPreprocess + 256
1   libobjc.A.dylib                     0x00007fff6d6a2a17 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff42feae59 -[NSException raise] + 9
3   JavaNativeFoundation                0x00007fff4703ada0 JNFCallIntMethod + 218
4   libawt_lwawt.dylib                  0x0000000116ff2e1b -[AWTView characterIndexForPoint:] + 123
5   AppKit                              0x00007fff40f0038e -[NSTextInputContext(NSInputContext_WithCompletion) characterIndexForPoint:completionHandler:] + 115
6   AppKit                              0x00007fff40832b51 -[NSTextInputContext handleTSMEvent:completionHandler:] + 1428
7   AppKit                              0x00007fff40832545 _NSTSMEventHandler + 306
8   HIToolbox                           0x00007fff4217722e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
9   HIToolbox                           0x00007fff421765df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
10  HIToolbox                           0x00007fff42176465 SendEventToEventTargetWithOptions + 45
11  HIToolbox                           0x00007fff421ddf8f SendTSMEvent_WithCompletionHandler + 383
12  HIToolbox                           0x00007fff4237ef61 __SendTextInputEvent_WithCompletionHandler_block_invoke + 489
13  HIToolbox                           0x00007fff4237d749 SendTextInputEvent_WithCompletionHandler + 1126
14  HIToolbox                           0x00007fff423e1264 -[IMKInputSession _postEvent:completionHandler:] + 170
15  HIToolbox                           0x00007fff423f8018 -[IMKInputSession characterIndexForPoint:tracking:completionHandler:] + 389
16  HIToolbox                           0x00007fff423d1bd2 -[IMKInputSession _commitOnMouseDown:completionHandler:] + 510
17  HIToolbox                           0x00007fff423d2a26 __49-[IMKInputSession handleEvent:completionHandler:]_block_invoke_3 + 81
18  HIToolbox                           0x00007fff423d1dc9 -[IMKInputSession tryHandleEvent_commitOnMouseDown_withDispatchCondition:dispatchWork:continuation:] + 87
19  HIToolbox                           0x00007fff423d2944 __49-[IMKInputSession handleEvent:completionHandler:]_block_invoke + 271
20  HIToolbox                           0x00007fff423ddd5b -[IMKInputSession _eventIsOn:completionHandler:] + 2085
21  HIToolbox                           0x00007fff423d21c8 -[IMKInputSession handleEvent:completionHandler:] + 823
22  HIToolbox                           0x00007fff4238db8c IMKInputSessionProcessEventRefWithCompletionHandler + 114
23  HIToolbox                           0x00007fff4238d2fe InputMethodInstanceProcessEventRef_WithCompletionHandler + 122
24  HIToolbox                           0x00007fff4237cc32 __TSMEventToInputMethod_WithCompletionHandler_block_invoke + 117
25  HIToolbox                           0x00007fff42380165 __SendTSMDocumentLockEvent_WithCompletionHandler_block_invoke + 95
26  HIToolbox                           0x00007fff421e0db9 ___ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec_block_invoke + 110
27  AppKit                              0x00007fff408329ac -[NSTextInputContext handleTSMEvent:completionHandler:] + 1007
28  AppKit                              0x00007fff40832545 _NSTSMEventHandler + 306
29  HIToolbox                           0x00007fff4217722e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
30  HIToolbox                           0x00007fff421765df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
31  HIToolbox                           0x00007fff42176465 SendEventToEventTargetWithOptions + 45
32  HIToolbox                           0x00007fff421ddf8f SendTSMEvent_WithCompletionHandler + 383
33  HIToolbox                           0x00007fff4237cb76 TrySendLockEvent_BeforeEventToInputMethod_WithContinuationHandler + 315
34  HIToolbox                           0x00007fff4237ca01 TSMEventToInputMethod_WithCompletionHandler + 147
35  HIToolbox                           0x00007fff4237c94e TSMEventToKeyboardInputMethod_WithCompletionHandler + 120
36  HIToolbox                           0x00007fff421e536b TryEventToKeyboardInputMethod_WithContinuationHandler + 235
37  HIToolbox                           0x00007fff422182e1 __TSMProcessMouseEventWithCompletionHandler_block_invoke_3 + 131
38  HIToolbox                           0x00007fff42218255 __TSMProcessMouseEventWithCompletionHandler_block_invoke_2 + 130
39  HIToolbox                           0x00007fff422181ca __TSMProcessMouseEventWithCompletionHandler_block_invoke + 130
40  HIToolbox                           0x00007fff42218124 TSMProcessMouseEventWithCompletionHandler + 225
41  AppKit                              0x00007fff40efd4a2 -[NSTextInputContext _handleEvent:options:allowingSyntheticEvent:completionHandler:] + 278
42  AppKit                              0x00007fff40efd086 -[NSTextInputContext _handleEvent:allowingSyntheticEvent:] + 107
43  libawt_lwawt.dylib                  0x0000000116ff0306 -[AWTView mouseDown:] + 80
44  AppKit                              0x00007fff40746937 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5724
45  AppKit                              0x00007fff4067d1a6 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2295
46  AppKit                              0x00007fff4067c667 -[NSWindow(NSEventRouting) sendEvent:] + 478
47  libawt_lwawt.dylib                  0x0000000116ff3d1a -[AWTWindow_Normal sendEvent:] + 86
48  AppKit                              0x00007fff4051be6b -[NSApplication(NSEvent) sendEvent:] + 331
49  libosxapp.dylib                     0x0000000116938b0c -[NSApplicationAWT sendEvent:] + 287
50  AppKit                              0x00007fff4050a5e0 -[NSApplication run] + 755
51  libosxapp.dylib                     0x000000011693881e +[NSApplicationAWT runAWTLoopWithApp:] + 222
52  libawt_lwawt.dylib                  0x0000000117023940 +[AWTStarter starter:headless:] + 834
53  JavaNativeFoundation                0x00007fff4703dfce +[JNFRunLoop _performCopiedBlock:] + 17
54  Foundation                          0x00007fff45212742 __NSThreadPerformPerform + 328
55  CoreFoundation                      0x00007fff42f37683 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
56  CoreFoundation                      0x00007fff42f37629 __CFRunLoopDoSource0 + 108
57  CoreFoundation                      0x00007fff42f1afeb __CFRunLoopDoSources0 + 195
58  CoreFoundation                      0x00007fff42f1a5b5 __CFRunLoopRun + 1189
59  CoreFoundation                      0x00007fff42f19ebe CFRunLoopRunSpecific + 455
60  idea                                0x00000001095e7df4 main + 332
61  libdyld.dylib                       0x00007fff6ee703d5 start + 1

**Comment by mallowigi** [comment]
Can you provide more information about your environment
