### ISSUE TITLE
Sorting arrow doesn't appear in query result

### ISSUE THREAD

**Issue by Benjozork** [ChrisRM/material-theme-jetbrains#1334]
Query results don't show sorting arrow.

![image](https://user-images.githubusercontent.com/4503241/63450943-2114a500-c411-11e9-87c8-6a579c27b7d3.png)

Clicking on the header of the column changes the sorting order, but no arrow or sorting indicator appears.

**Comment by mallowigi** [comment]
You probably switched a theme or color scheme while the window was opened. There is a bug about it since day one and I have no idea on how to fix this. Restarting the IDE usually fixes that
