### ISSUE TITLE
Semantic highlighting

### ISSUE THREAD

**Issue by svenjacobs** [ChrisRM/material-theme-jetbrains#1336]
### Summary

It seems *semantic highlighting* (`Preferences/Editor/Color Scheme/Language Defaults/Semantic highlighting`) partially stopped working when using Material Theme. Local variables and function arguments are still highlighted semantically but constructor arguments for instance are not.

### Expected behavior

Semantic highlighting should work.

### Actual behavior

Semantic highlighting only works partially.

### Steps to reproduce (if needed)

1. Select theme Material Darker
2. Enable semantic highlighting
3. Observe highlighting of local variables in contrast to constructor arguments

### Environment

* macOS 10.14.6
* Android Studio 3.5
* Material Theme UI 3.10.0
* Theme Material Darker

**Comment by mallowigi** [comment]
Can't reproduce. Can you provide a screen?

**Comment by svenjacobs** [comment]
![2019-08-23 at 09 14](https://user-images.githubusercontent.com/255313/63573869-c3a26480-c586-11e9-87ce-7a4f9da759e4.png)

**Comment by svenjacobs** [comment]
To be more precise, constructor **properties** are not semantically highlighted. Constructor arguments are colorized in the **same** color.

<img width="323" alt="Screenshot 2019-08-23 at 09 22 20png" src="https://user-images.githubusercontent.com/255313/63574218-94402780-c587-11e9-948d-cd22aa9aea9d.png">

**Comment by mallowigi** [comment]
And are you sure this is a bug from the plugin and not the ide?

--
Elior

**Comment by svenjacobs** [comment]
I'm sorry, I was of the impression that semantic highlighting also counts for constructor arguments and properties. I just disabled Material Theme and noticed that this is not the case. If this is something that can be done through the plugin, this would be a nice feature 👍 

On another note, why is it that the plugin is only available as version 3.10.0 in Android Studio but in IntelliJ IDEA it's 4.4.6?

**Comment by mallowigi** [comment]
Theoretically it should be 4.0.5 but still, AS is still using an old fork of the IDE, and the latest features only work for the latest IDE releases.
