### ISSUE TITLE
Button icons are misaligned in AVD

### ISSUE THREAD

**Issue by Thomas-James-Rose** [ChrisRM/material-theme-jetbrains#1337]
### Summary

A very minor gripe in a generally awesome plugin but the icons for the help and refresh buttons in the Android Virtual Device Manager look as though they are misaligned.

### Expected behavior

The icons should be centre aligned as they are originally. 

![Screenshot 2019-08-22 at 16 18 58](https://user-images.githubusercontent.com/9136302/63527246-98713400-c4f8-11e9-90ba-532eda2d6c8e.png)

### Actual behavior

The icons are aligned to the left of the wide buttons.

![Screenshot 2019-08-22 at 16 11 08](https://user-images.githubusercontent.com/9136302/63526836-f18c9800-c4f7-11e9-9e2c-9298093710da.png)

### Environment

**_Jetbrains IDE_**
Android Studio 3.5 RC 3
Build #AI-191.8026.42.35.5781497, built on August 5, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5

**_Material Theme Config_**
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="2979ff" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="version" value="3.10.0" />
  </component>
```

**Comment by mallowigi** [comment]
I remember this issue, but it's not easily fixeable. Closing this because I have much more important issues.
