### ISSUE TITLE
Terminal tabs

### ISSUE THREAD

**Issue by nWidart** [ChrisRM/material-theme-jetbrains#134]
Hello,

I see the terminal tabs don't have the same styles as the file tabs. 
![screen shot 2015-12-14 at 13 45 30](https://cloud.githubusercontent.com/assets/882397/11781295/17d40dbe-a269-11e5-88b0-324f921b6947.png)

Would maybe be nice to have those in the same style.

**Comment by mallowigi** [comment]
Pain in the butt to fix unfortunately (I tried)

**Comment by zenithtekla** [comment]
Please don't make the terminal tabs look bigger. It is a waste of landscape.

**Comment by mallowigi** [comment]
This is because the Editor Tabs and the Terminal Tabs are the same component. Changing the tab height will affect these tabs.

Since it's not an open API, I won't leave this open unless JB agrees to merge my pull request to make it open (which they probably won't)
