### ISSUE TITLE
Unable to update to version v4.4.5

### ISSUE THREAD

**Issue by kstratis** [ChrisRM/material-theme-jetbrains#1340]
RubyMine 2019.2.1 is stuck in version 4.2.2. 

When I try to update the plugin... nothing happens.

Manually trying to update from the marketplace results in the following error:

<img width="918" alt="Screenshot 2019-08-23 09 25 29" src="https://user-images.githubusercontent.com/1859806/63571141-06187100-c588-11e9-9c7b-320034e89cbd.png">

I also downloaded the plugin manually from the releases page (.zip file) and tried to install it but again...no luck:

<img width="916" alt="Screenshot 2019-08-23 09 27 21" src="https://user-images.githubusercontent.com/1859806/63571204-3829d300-c588-11e9-8999-30cc039b8de1.png">

Please advise... thnx

**Comment by mallowigi** [comment]
I've removed the bad releases, but 4.4.6 is out now.
