### ISSUE TITLE
The second window does not display file paths

### ISSUE THREAD

**Issue by pog2g** [ChrisRM/material-theme-jetbrains#1342]
# Info
* System:Mac;
* GoLand version:2019.2.1
* plug-in:4.3.5
# bug-info:</br>
 The second window opens in full screen mode. The second window does not display the file path. Turn off the full screen and then turn on the full screen to return to normal

## First window:
![image](https://user-images.githubusercontent.com/48884933/63581387-88755500-c5c9-11e9-9f77-26df018bb5bb.png)
## The second window opens in full screen:
![image](https://user-images.githubusercontent.com/48884933/63581438-9fb44280-c5c9-11e9-8c30-1cc09d6797db.png)
## The second window closes the full screen and opens it again:
![image](https://user-images.githubusercontent.com/48884933/63581485-ba86b700-c5c9-11e9-927c-84a71f32f572.png)

**Comment by mallowigi** [comment]
Please download 4.4.6

**Comment by pog2g** [comment]
# Idea occurred in version 4.46
## First window:
![image](https://user-images.githubusercontent.com/48884933/63582659-0dfa0480-c5cc-11e9-8fe3-ab309e609b8d.png)
## The second window opens in full screen:
![image](https://user-images.githubusercontent.com/48884933/63582681-181c0300-c5cc-11e9-8232-ba87b88ec491.png)
## The second window closes the full screen and opens it again:
![image](https://user-images.githubusercontent.com/48884933/63582696-21a56b00-c5cc-11e9-81c1-315f94fdab59.png)

**Comment by goxr3plus** [comment]
I have exactly the same issue :

![image](https://user-images.githubusercontent.com/20374208/63765534-e65bb280-c8d1-11e9-99a4-1cc512b1ef14.png)

**Comment by asolopovas** [comment]
+1

**Comment by goxr3plus** [comment]
I solved the issue as following . 

CTRL+SHIFT+A => switch boot sdk => I went to jdk 11
