### ISSUE TITLE
The tabs in the "modify table" window appear behind the main panel.

### ISSUE THREAD

**Issue by Hugo4400** [ChrisRM/material-theme-jetbrains#1347]
### Summary
In DetaGrip, when opening the window for modifying the table structure : The navigation tabs (Columns, keys, Indices, Foreign keys) appear behind the main panel. The tabs are still clickable but only barely.

### Expected behavior
View should contain full size navigation tabs.

### Actual behavior
Tabs appear behind the main panel and are only barely visible/clickable.
<img alt="screenshot" src="https://i.imgur.com/spyKTup.png">

### Environment

```
DataGrip 2019.2.2
Build #DB-192.6262.49, built on August 16, 2019
Runtime version: 11.0.3+12-b304.39 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: bigger.font.in.project.view=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, bundled-datagrip-help, com.chrisrm.idea.MaterialThemeUI
```

[Link to Material Theme configuration file.](https://drive.google.com/open?id=1SHV_sZ4upyD3azxDYAtlOaFD6Sk3XD05)

**Comment by goxr3plus** [comment]
I have exactly the same issue :

![image](https://user-images.githubusercontent.com/20374208/63765534-e65bb280-c8d1-11e9-99a4-1cc512b1ef14.png)

**Comment by peterkc** [comment]
Had to revert to [4.2.2](https://plugins.jetbrains.com/plugin/8006-material-theme-ui/update/66593).
