### ISSUE TITLE
Editor tabs are broken.

### ISSUE THREAD

**Issue by sastep** [ChrisRM/material-theme-jetbrains#1348]
As can see in the picture the tabs in the editor look like they were cut in half.
![image](https://user-images.githubusercontent.com/20317847/63691349-fe72f980-c81f-11e9-9502-b04aa3830bfd.png)

**Comment by mallowigi** [comment]
What version of the plugin are you on?

**Comment by pacproduct** [comment]
Had a similar issue after updating PHPStorm to version 2019.2.1 (Build-PS-192.6262.66 August 22 2019):

![PHPStorm-2019 2 1-Build-PS-192 6262 66-august-22-2019__Material-tabs-KO](https://user-images.githubusercontent.com/2098407/63698105-717b7080-c81e-11e9-8ec2-c2a56eae91a3.png)

But Upgrading Material to version `4.4.6` solved the issue for me.

**Comment by sastep** [comment]
@mallowigi I'm using version 4.4.6 and Webstorm 2019.2.1 and I still have this issue.
