### ISSUE TITLE
Auto-completion window is initially a solid color, no readable text until pressing an arrow key

### ISSUE THREAD

**Issue by onContentStop** [ChrisRM/material-theme-jetbrains#1349]
### Summary

When using the auto-complete feature, the box containing completions is entirely a solid color with no text until pressing down arrow.

### Expected behavior

Auto-completion shows available completions correctly. (This works for the Darcula theme, as seen below)

Before pressing down arrow:
![Screenshot from 2019-08-26 08-10-27](https://user-images.githubusercontent.com/9062746/63693365-81bd2c80-c7d9-11e9-94f9-b8bcc90abe88.png)
After:
![Screenshot from 2019-08-26 08-10-36](https://user-images.githubusercontent.com/9062746/63693372-8550b380-c7d9-11e9-8402-732ad3a1f990.png)

### Actual behavior

Auto-completion is initially a solid color, then shows the text correctly after pressing down arrow. (Using Atom One Dark in the screenshot, but this applies to all themes)

Before pressing down arrow:
![Screenshot from 2019-08-26 08-11-02](https://user-images.githubusercontent.com/9062746/63693381-897cd100-c7d9-11e9-96bb-13cbcdd8d874.png)
After:
![Screenshot from 2019-08-26 08-11-12](https://user-images.githubusercontent.com/9062746/63693385-8d105800-c7d9-11e9-9e8b-284168a34648.png)

### Steps to reproduce (if needed)

1. Set the IDE theme to a Material Theme UI theme.
2. Begin typing some code.
3. The auto-complete window looks like the screenshot until the selection box is moved.

### Environment

CLion 2019.2.1
Build #CL-192.6262.62, built on August 21, 2019
Licensed to **********
Subscription is active until *************
For educational use only.
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.19.62-1-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.jetbrains.lightThemePreview, com.mallowigi.idea, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.toml.lang, org.rust.lang

Material Theme UI Lite version 4.0

**Comment by mallowigi** [comment]
Something is odd with your screenshot. Why would Atom One Dark have the colors of Darcula? Please send me your settings

**Comment by mallowigi** [comment]
So what is the exact steps?

**Comment by mallowigi** [comment]
I can't reproduce your issue. Any chance you send me a video of the scenario ?

**Comment by mallowigi** [comment]
Something is weird in your video, did you disable the Material Components perhaps ?

**Comment by mallowigi** [comment]
Hmm it should not be, but in any case this is not the right place. Please open an issue on the right repository

**Comment by mallowigi** [comment]
Sorry it was private. You can check now.
