### ISSUE TITLE
question about icon of java file

### ISSUE THREAD

**Issue by singlepig** [ChrisRM/material-theme-jetbrains#1353]
### Summary
Hello, I'm confused about icon of java file when I using plugin material-theme-jetbrains on Android Studio 3.5(problem also showing on AS 3.4).
According to [official page](http://www.material-theme.com/docs/reference/file-icons/), I cannot find this ![QQ20190828-144608.jpg](https://i.loli.net/2019/08/28/QZaD1S5msVtdwPK.jpg) icon. I don't know what it represents.
 Should not Java file be this icon ![java](http://www.material-theme.com/img/fileIcons/java.svg)?

### Steps to reproduce (if needed)
You can see from the following screenshot.

![QQ20190828-114817@2x.jpg](https://i.loli.net/2019/08/28/N5AtkpgQzrbGDT7.jpg)

### Environment

* OS (Windows, Linux, Mac)
* Android Studio 3.5
* Material Theme UI Plugin v3.10.0

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/icons-settings/#psi-icons

**Comment by singlepig** [comment]
> http://www.material-theme.com/docs/configuration/icons-settings/#psi-icons

After turning off PSI Icons, it still not showing the java file icon. The icon becomes IDEA default icon.

![QQ20190829-153730.jpg](https://i.loli.net/2019/08/29/SmZTB3elRqMvkC4.jpg)

**Comment by mallowigi** [comment]
Yes this is IDEA's default behavior. There is no way as far as i know to disable this

**Comment by singlepig** [comment]
@mallowigi Thank you for your reply! 👍
