### ISSUE TITLE
Enhancement Request: Add style to differentiate between split editor tabs

### ISSUE THREAD

**Issue by yaykyle** [ChrisRM/material-theme-jetbrains#1355]
### Summary

I might be missing something, but when I use horizontally split editor tabs (Window > Editor Tabs > Split Horizontally), it's very hard to tell where one side of the split ends and the next one begins. 

Would it be possible to style some sort of divider between the horizontally split panes?

### Expected behavior

A thin rule or differently colored area is used to delineate the two panes.

### Actual behavior

The panes run into each other, making it harder to recognize where one ends and the next begins.

### Steps to reproduce (if needed)

Enable a Material Theme, such as Palenight.
Split your current file horizontally (Window > Editor Tabs > Split Horizontally)

![image](https://user-images.githubusercontent.com/4280/63864830-7f480780-c97e-11e9-93bf-d045c4b59db2.png)

### Environment

* Material Theme Plugin version 4.2.2

PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, search.everywhere.settings=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0, tabs.alphabetical=true
Non-Bundled Plugins: GrepConsole, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.daylerees.rainglow, com.dubreuia, com.intellij.ideolog, net.seesharpsoft.intellij.plugins.csv, BashSupport, ImportCost, de.espend.idea.laravel, de.espend.idea.php.annotation, intellij.prettierJS, izhangzhihao.rainbow.brackets, cz.daku.intellij.extraActions, org.psliwa.idea.composer, org.toml.lang, ru.adelf.idea.dotenv, some.awesome

Plugin Configuration:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isCompactStatusBar" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="useMaterialFont2" value="true" />
    <option name="selectedTheme" value="MONOKAI" />
    <option name="userId" value="-145541c:169ede51ee1:-8000" />
    <option name="version" value="4.2.2" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I already tried to do so in the past, maybe I’ll try again, but I’m in hiatus for some time so you better be patient

**Comment by mallowigi** [comment]
Hi,

I'm not planning on changing the current themes, but if you must know, the color is defined by the "Separators Color" property of the themes. And because I want to be as much borderless as possible, I prefer to leave the separators color as it is now.

However you can make use of the Custom Theme and the Theme presets to have your own versions of the predefined themes. Check the documentation at : http://www.material-theme.com/docs/configuration/custom-themes/#importing-and-exporting-custom-themes
