### ISSUE TITLE
Editor tabs close button (x) hidden behind dots

### ISSUE THREAD

**Issue by sbattistin** [ChrisRM/material-theme-jetbrains#1357]
### Summary

Closing the rightmost editor tabs with the `x` button is difficult if not impossible without moving the tab somewhere on the left (like one or two tabs on the left) if you want to use your mouse. For sure there are other options available like `right-click -> close` or `Ctrl+F4` (on Windows).

Note: The editor tabs won't scroll further using the mouse wheel.

### Expected behavior

I'm expecting the `x` button on the rightmost editor tab to be visible and clickable

### Actual behavior

The `x` button is not visible and trying to click on it, the IDE will show the list of hidden editor tabs since the button is behind it.

**Issue** screenshot:
![Issue](https://user-images.githubusercontent.com/20923264/63930698-2185ef00-ca54-11e9-8065-ff82a255cc95.png)

### Steps to reproduce

1. Open IntelliJ Idea
2. Make sure the "Show tabs in one row" and "Hide tabs if there is no space" are checked, as in "Settings" screenshot
3. Open several tabs in order to fill the tabs bar and make some tabs hidden
4. Closing the rightmost tab with the `x` button is not possible since appears under the three dots as shown in the "Issue" screenshot

**Settings** screenshot:
![Settings](https://user-images.githubusercontent.com/20923264/63931450-94dc3080-ca55-11e9-8587-d34d2c8fc8c9.png)

### Environment

IntelliJ IDEA 2019.2.1 Preview (Ultimate Edition)
Build #IU-192.6262.9, built on August 6, 2019
Licensed to ***
Subscription is active until September 21, 2019
Runtime version: 11.0.3+12-b304.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, Lombook Plugin, PlantUML integration, YAML/Ansible support, com.intellij.plugins.watcher, mobi.hsz.idea.gitignore, net.sjrx.intellij.plugins.systemdunitfiles, net.vektah.codeglance, BashSupport, com.chrisrm.idea.MaterialThemeUI, org.jetbrains.plugins.vagrant, org.sonarlint.idea

Material Theme configuration:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="darkTitleBar" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="settingsSelectedTab" value="6" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="***" />
    <option name="version" value="4.4.6" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Can’t fix this, it also happens without the plugin
