### ISSUE TITLE
New theme proposal: Nebula

### ISSUE THREAD

**Issue by eliaperantoni** [ChrisRM/material-theme-jetbrains#1358]
I propose adding a new theme: Nebula. It's a theme originally made for Atom by [tjkohli](https://github.com/tjkohli). I think it looks really good and would fit nicely with all the other material themes.

https://github.com/tjkohli/nebula-syntax
https://github.com/tjkohli/nebula-ui

![](https://camo.githubusercontent.com/51873aabf904249bf6966b6880c4ec6476e11f49/687474703a2f2f746a6b6f682e6c692f71344f522f34375133723039322b)

**Comment by mallowigi** [comment]
That's great, but I don't plan on adding new themes now. You can still download your own extension by following the guidelines here: http://www.material-theme.com/docs/development/external-themes/
