### ISSUE TITLE
Bank window for diff

### ISSUE THREAD

**Issue by alexsergin** [ChrisRM/material-theme-jetbrains#1359]
### Summary

Diff displays blank window

### Steps to reproduce (if needed)

It can be reproduced with different ways. Here is one of it:
1. Open random file
2. Enable annotations (from context menu select Git->Annotate)
3. Click on any annotation on the left side
4. Select "Show Diff" for any file from the patch dialog
5. You'll see blank window instead of diffs

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Build #IU-192.6262.58, built on August 20, 2019
Runtime version: 11.0.3+12-b304.39 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.mac.allowDarkWindowDecorations=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: JAXB 2.0 XJC generator, Lombook Plugin, Jetbrains TeamCity Plugin, com.ppolivka.gitlabprojects, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, BashSupport, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, JProfiler, org.intellij.scala, org.jetbrains.plugins.vue
Material Theme Plugin version 4.4.6

Theme configs were attached.
[configs.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3555556/configs.zip)

**Comment by mallowigi** [comment]
Please make sure you are not in full screen

**Comment by alexsergin** [comment]
> Please make sure you are not in full screen

I'm not in full screen of course. But diff window expanded to the whole display. And if resize it to smaller one it magically starts to work properly. It looks like a bug as for me.

**Comment by mallowigi** [comment]
It's a bug but a duplicate of this one: https://github.com/ChrisRM/material-theme-jetbrains/issues/1282
