### ISSUE TITLE
$this has wrong color (after last update)

### ISSUE THREAD

**Issue by annechko** [ChrisRM/material-theme-jetbrains#1360]
### Summary
I have custom color scheme and "$this" is configured to be "red", but it has purple color, which is wrong

### Expected behavior
"$this" should be red, as I configured in my Scheme - Material Theme - default copy
![red](https://user-images.githubusercontent.com/12374676/64020266-777c9480-cb31-11e9-9989-9a4bd9f57e58.PNG)

### Actual behavior
After the last update - all $this now have purple color

![purple](https://user-images.githubusercontent.com/12374676/64020296-8e22eb80-cb31-11e9-8d7a-694e5a589fda.PNG)

### Environment

PhpStorm 2019.2.1
Build #PS-192.6262.66, built on August 22, 2019

Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1998M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, bigger.font.in.project.view=true, debugger.watches.in.variables=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.hal.phpmetrics.id

* Material Theme Plugin version 4.4.6
* OS (Windows)

<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="009688ff" />
    <option name="notificationsColor" value="323232ff" />
    <option name="treeSelectionColor" value="546e7aff" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="607d8bff" />
    <option name="foregroundColor" value="b0bec5ff" />
    <option name="backgroundColor" value="263238ff" />
  </component>
</application>

**Comment by mallowigi** [comment]
Interesting. Can you check in the PHP additions page what is the value of $this?

**Comment by annechko** [comment]
it is purple indeed :( 

![image](https://user-images.githubusercontent.com/12374676/64027796-c0d4e000-cb41-11e9-9d1c-6caf687be40b.png)
