### ISSUE TITLE
Highlight can't found where use  implicit conversion

### ISSUE THREAD

**Issue by jxnu-liguobin** [ChrisRM/material-theme-jetbrains#1361]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

Highlight Black underline that does not display where use implicit conversion when i open it in IDEA，Maybe the background color overrides it

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Subscription is active until July 20, 2020
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true, git.explicit.commit.renames.prohibit.multiple.calls=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, org.intellij.scala

**Comment by mallowigi** [comment]
Sorry I don't understand the issue. Can you provide screenshots maybe ?

**Comment by jxnu-liguobin** [comment]
This is a display feature of IDEA 

```
 implicit class LocalDateTimeOpt2StringOPt (localDateTime: Option[LocalDateTime]) {
    def toStrOpt = localDateTimeToString(localDateTime)

    def toStrNoMsOpt = localDateTimeToStringNoMS(localDateTime) 
  }
```
every where I use this implicit ‘toStrOpt’ operate ，You can see there's an underline here.
![64815E9A-1E49-4BC7-B8B2-D1D25BFEA91B](https://user-images.githubusercontent.com/29496873/64072372-d8d26e00-ccbf-11e9-847c-1b561a958a75.png)

**Comment by jxnu-liguobin** [comment]
when use material theme,I can't see underline here.But  scala language has many operates like that,It can remind user when see code,I think it's the background color that covers it.

**Comment by mallowigi** [comment]
Can you check in Settings>  Editor > Color Scheme > Scala , it should be there. It's possible that the bundled themes are removing this feature, but I'm not a Scala developer and I don't know. If you found it, please report it to me I'll see what I can do

**Comment by jxnu-liguobin** [comment]
![image](https://user-images.githubusercontent.com/29496873/64237169-687d5400-cf2e-11e9-95ec-f8438e25e9b0.png)

oh thanks,I think I might have found it
