### ISSUE TITLE
Autocomplete does not show current item highlight.

### ISSUE THREAD

**Issue by distante** [ChrisRM/material-theme-jetbrains#1362]
### Summary
Autocomplete does not show current item highlight.

### Expected behavior

The autocomplete popup should show correctly the active item with a highlight.

### Actual behavior

No highlight is visible an there is no way to know the active item without see the description.

### Steps to reproduce (if needed)

1. Reference an object with several properties.
2. Try to select one property in the autocomplete popup.

Screenshot:
![image](https://user-images.githubusercontent.com/5490201/64150292-3c77ab00-ce28-11e9-90c6-7f4f59e1cd3c.png)

### Environment

WebStorm 2019.2.1
Build #WS-192.6262.59, built on August 20, 2019
Licensed to ***redacted***
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.tooltip.initialDelay=845, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: GrepConsole, com.bashorov.mainMenuToggler, com.chrisrm.idea.MaterialThemeUI, com.kstenschke.copypastestack, io.github.qeesung.component.HighlightBracketPair, izhangzhihao.rainbow.brackets

Material Theme version 4.4.6

## material_theme:
```
<application>
  <component name="MaterialThemeConfig">
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="e9df36" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="-5b6c9e69:1679c302c0b:-8000" />
    <option name="version" value="4.3.4" />
  </component>
</application>
```

## material_custom_theme:
```
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="083f4dff" />
    <option name="accentColor" value="d33682ff" />
    <option name="notificationsColor" value="2e4c52ff" />
    <option name="treeSelectionColor" value="2e4c5280" />
    <option name="highlightColor" value="11353fff" />
    <option name="secondBorderColor" value="0d3640ff" />
    <option name="tableSelectedColor" value="11353fff" />
    <option name="contrastColor" value="00252eff" />
    <option name="disabledColor" value="2e5861ff" />
    <option name="secondaryBackgroundColor" value="003745ff" />
    <option name="buttonColor" value="073642ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="003745ff" />
    <option name="textColor" value="586e75ff" />
    <option name="foregroundColor" value="839496ff" />
    <option name="backgroundColor" value="002b36ff" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Is this only happening with the solarized dark theme ?

**Comment by distante** [comment]
Looks like is a combination. The editor uses: Material Deep Ocean but the rest is based on Solarize Dark.

To get my complete look and feel I do:

1. Select Solarize Dark.
2. Apply
3. Select Material Custom.
4. Apply
an then I get

![image](https://user-images.githubusercontent.com/5490201/64152799-9fb80c00-ce2d-11e9-9cdf-8c65beceeac9.png)

I have search a way to customize the highlight color but I haven't found anything.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/64153475-a77cae00-ce37-11e9-80bf-166f34f70515.png)

Your "selected background color" and "list background color" are pretty much the same

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/custom-themes/

**Comment by distante** [comment]
Oh sorry for this. This happened after an webstorm update and I thought that was the problem. 

Thank you for your help.

**Comment by mxs42** [comment]
I have this as well and it was triggered by update.
