### ISSUE TITLE
Plugin stop working for PhpStorm 2019.2.1 after updating to version 4.5

### ISSUE THREAD

**Issue by juanOS85** [ChrisRM/material-theme-jetbrains#1370]
Once the plugin was updated to version 4.5 and the IDE was restarted, I got this exception:

<img width="971" alt="Screen Shot 2019-09-11 at 14 37 42" src="https://user-images.githubusercontent.com/201116/64729040-f4006300-d4a1-11e9-9621-e765cf8216f8.png">

I have tried disable/enable it multiple times but the result is the same.

**Comment by mallowigi** [comment]
4.5.1?

**Comment by juanOS85** [comment]
Thanks so much for the quick reply.

Thanks for letting me know there is an update for this; 4.5.1 it is working as expected.

For the record, PhpStorm was telling me there wasn't any pending update and that's why I decided to open this ticket.

<img width="782" alt="Screen Shot 2019-09-11 at 15 08 08" src="https://user-images.githubusercontent.com/201116/64731202-4e9bbe00-d4a6-11e9-9906-5cc65f098883.png">

**Comment by mallowigi** [comment]
This is something that I noticed as well. Lately a lot of similar complaints are flooding the issues and JB’s YouTrack about my plugin where a simple update would have prevented it.

It looks like fetching updates is now delayed where before it was at start, just like VSCode.
