### ISSUE TITLE
Some file icons are different in Kotlin than in Java

### ISSUE THREAD

**Issue by ChristianIvicevic** [ChrisRM/material-theme-jetbrains#1372]
### Summary

The icons in the project view for some of my Kotlin files are not the same as the ones in Java projects.

### Expected behavior

Kotlin files that contain only a single entity, be it class, interface, abstract class, annotation or enum should have the same icon as their respective Java counterparts.

### Actual behavior

Abstract classes and enums have the default IntelliJ circle icons and not the same icons as respective Java files.

### Steps to reproduce (if needed)

1. Create a Kotlin project
2. Create files containing only abstract classes or enums

#### Kotlin icons
![Screenshot 2019-09-12 at 16 51 01](https://user-images.githubusercontent.com/45569997/64795493-778f8200-d57e-11e9-8427-8d4073164c14.png)

#### Java icons
![Screenshot 2019-09-12 at 16 51 19](https://user-images.githubusercontent.com/45569997/64795524-84ac7100-d57e-11e9-9a67-15cb4ee5bcfb.png)

### Environment

IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
Non-Bundled Plugins: Lombook Plugin, com.dubreuia, google-java-format, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets, org.sonarlint.idea
MaterialTheme v4.5.1

**Comment by ChristianIvicevic** [comment]
@mallowigi Just coming by to point out this isn't entirely fixed yet. There are still two issues that are as follows:

1. enum classes aren't picked up at all:
```kotlin
package net.foo.bar.models.entities

enum class BuildingType {
    FOO, BAR, BAZ
}
```
The previous snippet yields the following item in the project view:
![Screenshot 2019-11-07 at 01 27 09](https://user-images.githubusercontent.com/45569997/68349605-07c0f200-00fe-11ea-8cd5-d7809c4e627b.png)

2. abstract classes aren't picked up either:
```kotlin
package net.foo.bar.models.entities

abstract class CelestialObjectEntity
```
Once again the previous snippets has the following icon for the respective file:
![Screenshot 2019-11-07 at 01 27 36](https://user-images.githubusercontent.com/45569997/68349687-448ce900-00fe-11ea-9752-3ed95578ef16.png)

**Comment by ChristianIvicevic** [comment]
Oh I just noticed that I am running v4.5.2 of your theme in IntelliJ 2019.2.4 although you seemingly have released newer versions of the theme. The plugin manager however isn't prompting me to update whatsoever.

**Comment by mallowigi** [comment]
I’m not releasing for 2019.2 anymore but regardless I think you’re right and it’s still not fixed (???) in latest version.

--
Elior
