### ISSUE TITLE
Dark UI during install

### ISSUE THREAD

**Issue by MrAmericanMike** [ChrisRM/material-theme-jetbrains#1373]
The UI during the install is a bit dark itself. Look at the bottom right button for example. Unreadable almost.

![image](https://user-images.githubusercontent.com/8037559/64880965-e973d400-d62f-11e9-88d3-89d4bb564bd7.png)

Would be nice to have it adjusted to something neutral.

**Comment by MrAmericanMike** [comment]
I don't know what info you need in order to know exactly what combination I'm using, but this combination isn't readable neither. Check this:
![image](https://user-images.githubusercontent.com/8037559/64881388-0a88f480-d631-11e9-9bfc-a41cca6bed8e.png)

I can't read that, can you?

**Comment by mallowigi** [comment]
Ok steps to reproduce maybe?

**Comment by MrAmericanMike** [comment]
I honestly forgot what I set as the installation offered so many options, that I'm not even sure what I did. I now switched to other UI so not sure how to reproduce. I know I was going for some dark theme. But that was too dark.
