### ISSUE TITLE
Tab height behaviour

### ISSUE THREAD

**Issue by quantumwebco** [ChrisRM/material-theme-jetbrains#1374]
### Summary

Tab height settings in Settings > Appearance & Behaviour > Material Theme changes all tabs including tool windows. Can this be distinct between editor tabs and tool window tabs maybe have a height for each?

### Expected behavior

Tab height changes only editor tabs

### Actual behavior

Tab height changes all tabs

### Steps to reproduce (if needed)

1. Change tab height
2. Restart 

You can also add Screenshots for a better understanding.

### Environment

PhpStorm 2019.2.2
Build #PS-192.6603.42, built on September 12, 2019
Licensed to quantumweb / Russell Leigh
Subscription is active until September 17, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CVS, CVSToolBox, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.codestream.jetbrains-codestream, com.dubreuia, com.faebeee.vuecomponentcreator, com.intellij.ideolog, com.karateca.jstoolbox, com.wix.scss.lint, com.xinkun.theme.md, mobi.hsz.idea.gitignore, net.vektah.codeglance, nl.bixie.intellij.uikit, BashSupport, com.dmarcotte.handlebars, com.intellij.plugins.html.instantEditing, com.alicannklc.codeigniter.snippets, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.laravel, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, lt.martynassateika.idea.codeigniter, me.artspb.idea.php.latest.plugin, net.king2500.plugins.PhpAdvancedAutoComplete, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, ru.adelf.idea.dotenv, org.igu.plugins.nativescript, tv.twelvetone.intellij.plugins.intellivue, zielu.gittoolbox

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
No it can’t be done. It’s simply the same code for both panes. It also makes sense, because now tool windows can be tabbed as well.

At the moment there is no way to differentiate the two, but maybe they will add the distinction in the future.
