### ISSUE TITLE
Android Studio not opening, after installing theme

### ISSUE THREAD

**Issue by anesask** [ChrisRM/material-theme-jetbrains#1376]
Android Studio just not showing after completing theme wizard.
Anyone have a similar problem?

**Comment by mallowigi** [comment]
Which version ?

**Comment by dmzobel** [comment]
Material Theme also appears to crash PyCharm and DataGrip versions 2019.2+. The app only loads a blank black screen. I'm using Material Theme version 3.10.0 in PyCharm and version 4.5.1 in DataGrip. Uninstalling Material Theme worked, allowing DataGrip 2019.2.4 to load.

**Comment by anesask** [comment]
Fresh install of Android Studio have fixed issue. Thanks.

**Comment by dmzobel** [comment]
@mallowigi DataGrip and PyCharm are still having this issue. Only a blank grey screen loads, and you have to manually delete the directory containing the Material Theme install to fix.

**Comment by mallowigi** [comment]
Please give me more details I’m not a medium

**Comment by dmzobel** [comment]
> Material Theme also appears to crash PyCharm and DataGrip versions 2019.2+. The app only loads a blank black screen. I'm using Material Theme version 3.10.0 in PyCharm and version 4.5.1 in DataGrip. Uninstalling Material Theme worked, allowing DataGrip 2019.2.4 to load.
