### ISSUE TITLE
Material Theme UI prevents Local History from showing.

### ISSUE THREAD

**Issue by HumidBrains** [ChrisRM/material-theme-jetbrains#1377]
### Summary

Webstorm does not display Local History when Material Theme UI is activated.

### Expected behavior

Clicking "VCS > Local History > Show History" should show a new window with local file history.

### Actual behavior

The new window shows, but it is completely blank.
Disabling or uninstalling Material Theme UI makes the history show as expected.

### Environment

WebStorm 2019.2.2
Build #WS-192.6603.19, built on September 3, 2019
Licensed to WebStorm Evaluator
Expiration date: October 12, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.intellij.laf.enable.animation=true, ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.intellij.plugins.vscodekeymap, com.markskelton.one-dark-theme, com.paperetto.dash, com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete, com.pyango.gmbh, net.seesharpsoft.intellij.plugins.file-preview, org.intellij.plugins.postcss, com.deadlock.scsyntax, com.intellij.lang.jsgraphql, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, ru.crazycoder.plugins.tabdir

* Material Theme Plugin version 4.5.1

**Comment by mallowigi** [comment]
Please disable the themed title bar, restart and try again

**Comment by HumidBrains** [comment]
@mallowigi Sorry for slow response and yup, that worked. Guessing a fix will come for this at some point.

**Comment by HumidBrains** [comment]
> Please disable the themed title bar, restart and try again

@mallowigi Sorry for slow response and yup, that worked. Guessing a fix will come for this at some point.

**Comment by HumidBrains** [comment]
@mallowigi I'm surprised this issue is closed. It's a clear bug and to me turning off the themed title bar can hardly be seen as anything but a temporary workaround until the bug is fixed. Am I missing something?

**Comment by mallowigi** [comment]
These are the kind of bugs that are not related to the plugin but from the JRE itself. If you had checked other similarly closed issues you would have known.

--
Elior

**Comment by HumidBrains** [comment]
> These are the kind of bugs that are not related to the plugin but from the JRE itself. If you had checked other similarly closed issues you would have known.
> […](#)
> -- Elior
> On 22 Sep 2019, 14:38 -0400, Jimmy Nordbeck ***@***.***>, wrote: @mallowigi I'm surprised this issue is closed. It's a clear bug and to me turning off the themed title bar can hardly be seen as anything but a temporary workaround until the bug is fixed. Am I missing something? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

If this problem is known and that it kills a core functionality of the editor, then it doesn't make a whole lot of sense to me keeping the title bar theming as a feature. And if it stays, I'd suggest to put some info about its quirks.

**Comment by mallowigi** [comment]
This has already been done if I remember correctly, I’ve added this info in the website and there is an alert as well when you switch it on (I can’t be sure at the moment since I don’t have a computer but I remember having done so)

Besides as I said this is a JRE problem, and true enough in the latest versions it seems to have been resolved.



--
Elior

**Comment by tonmanayo** [comment]
I'm still getting this bug...
