### ISSUE TITLE
Mix dark ide theme with light code theme

### ISSUE THREAD

**Issue by DefiCzech** [ChrisRM/material-theme-jetbrains#1379]
### Summary
If I want to mix Palenight theme for IDE and Solarized Light theme for code, the file names in tab of changed files are blue (I assume color from Solarized Light) and unreadable.

![image](https://user-images.githubusercontent.com/2785663/65315769-f39a5300-db98-11e9-8c69-41a324cabe85.png)

### Expected behavior
Readable file colors if themes are mixed.

### Environment
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1973M
Cores: 8
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: mobi.hsz.idea.gitignore, ImportCost, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.php, org.jetbrains.plugins.vue, com.vladsch.idea.multimarkdown

**Comment by mallowigi** [comment]
You can change the colors in Editor > Color Scheme > Material file colors

**Comment by DefiCzech** [comment]
Ok I tried Palenight for IDE and for Editor, and color is the same blue on purple, unreadable text.
