### ISSUE TITLE
Material Theme UI slows down IDE startup due to a network call on UI thread

### ISSUE THREAD

**Issue by radomirm-g** [ChrisRM/material-theme-jetbrains#1380]
Android Studio team noticed users' UI freeze report showing long time spent in `com.chrisrm.idea.MTApplicationComponent.initComponent()` (some reports show 120+ freeze, more often it is in 10-20 seconds range).

Here is a relevant part of a typical report (here the report captured 41.5 seconds UI freeze):
```
AWT-EventQueue-0 3.5#AI-191.8026.42.35.5791312 Studio, eap:false, os:Mac OS X 10.14.6, java-version:JetBrains s.r.o 1.8.0_202-release-1483-b49-5587405, TID: 25 [41500ms]
java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [41500ms]
[...]
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [41500ms]
com.intellij.idea.IdeaApplication$$Lambda$105/183840932.run(Unknown Source) [41500ms]
com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:77) [41500ms]
com.intellij.idea.IdeaApplication.run(IdeaApplication.java:217) [41500ms]
com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:394) [41500ms]
com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:408) [41500ms]
com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88) [41500ms]
com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:474) [41500ms]
[...]
com.chrisrm.idea.MTApplicationComponent.initComponent(MTApplicationComponent.java:74) [41500ms]
com.chrisrm.idea.MTApplicationComponent.initAnalytics(MTApplicationComponent.java:44) [41500ms]
com.chrisrm.idea.MTAnalytics.getInstance(MTAnalytics.java:95) [41500ms]
[...]
com.chrisrm.idea.MTAnalytics.<init>(MTAnalytics.java:91) [41500ms]
com.chrisrm.idea.MTAnalytics.ping(MTAnalytics.java:192) [41500ms]
com.mixpanel.mixpanelapi.MixpanelAPI.sendMessage(MixpanelAPI.java:71) [41500ms]
com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:83) [41500ms]
com.mixpanel.mixpanelapi.MixpanelAPI.deliver(MixpanelAPI.java:107) [41500ms]
com.mixpanel.mixpanelapi.MixpanelAPI.sendMessages(MixpanelAPI.java:172) [41500ms]
com.mixpanel.mixpanelapi.MixpanelAPI.sendData(MixpanelAPI.java:134) [41500ms]
sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259) [41500ms]
[...]
sun.net.www.http.HttpClient.openServer(HttpClient.java:463) [41500ms]
sun.net.NetworkClient.doConnect(NetworkClient.java:175) [41500ms]
java.net.InetSocketAddress.<init>(InetSocketAddress.java:220) [41500ms]
java.net.InetAddress.getByName(InetAddress.java:1077) [41500ms]
java.net.InetAddress.getAllByName(InetAddress.java:1127) [41500ms]
java.net.InetAddress.getAllByName(InetAddress.java:1193) [41500ms]
java.net.InetAddress.getAllByName0(InetAddress.java:1277) [41500ms]
java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324) [41500ms]
java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929) [41500ms]
java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method) [41500ms]
```

`MTAnalytics.ping()` shouldn't happen on UI thread as any I/O operation can cause long freezes. Also, consider guarding `MTAnalytics.ping()` with `MTConfig.getInstance().isDisallowDataCollection()` as there is no need to even connect to the server if data collection is not allowed.

**Comment by radomirm-g** [comment]
I looked at the commit b887970993efa0e29d39f5aeb9eb2799b6c7400b, but it will not fix the problem. It postpones the initialization of `MTAnalytics` and ping to happen after `initComponent`, but write actions are also blocking the UI thread (write action always happen on the UI thread) and it will block any background read actions.

Better choice is to call `Application.executeOnPooledThread()`, which will run the initialization/ping on a background thread.

When initializing objects in the background you have to be careful to make sure that future callers to `MTAnalytics` interact with fully initialized objects. That said, `MTAnalytics.initAnalytics()` doesn't seem to change the state of the `MTAnalytics` object, the object is fully usable once it gets constructed, so currently no such synchronization is needed.

**Comment by mallowigi** [comment]
To be honest I'm not very knowledgeable about threads, I didn't know about your method.

I'll check if it solves the issue

**Comment by mallowigi** [comment]
Will be fixed in next release
