### ISSUE TITLE
 The spacing between the drop-down menu bar options can be a little smaller?

### ISSUE THREAD

**Issue by liyangzbx** [ChrisRM/material-theme-jetbrains#1381]
The spacing between the drop-down menu bar options can be a little smaller.?
As you can see, the drop-down menu bar covers almost all of my screen, which makes it less convenient for me to operate.
![TIM截图20190921104208](https://user-images.githubusercontent.com/22143121/65366949-1857fe80-dc5d-11e9-96fa-c9bee7822ed3.png)
![TIM截图20190921105421](https://user-images.githubusercontent.com/22143121/65367031-3c680f80-dc5e-11e9-9d16-34fb165e4fc0.png)

**Comment by mallowigi** [comment]
Three is an option in the settings to disable it.
