### ISSUE TITLE
Theme reverts when switching between machines using plugin sync

### ISSUE THREAD

**Issue by hellopablo** [ChrisRM/material-theme-jetbrains#1383]
### Summary
I have the theme installed on two machines, an iMac and a MacBook Pro.

I find when I open PhpStorm on one machine, having used it on the other the theme resets to an undefined value. In order to fix it I need to go to the Appearance preference screen and choose a different theme (the correct value, i.e. "Material Oceanic" is set, but the visuals are wrong). I click "apply", the new settings take hold, I then reset to Oceanic again and "ok" out of the screen.

If I open PhpStorm on the other machine (giving it some time), I find that the same thing happens there - i fix it there and then the next time in on the other machine it's the same issue.

FWIW I use the inbuilt plugin and theme synchronisation feature.

Some screenshots:

1. On first load, the pick project screen - incorrect colours
<img width="889" alt="Screenshot 2019-09-23 10 23 42" src="https://user-images.githubusercontent.com/233585/65415048-d78eef80-ddec-11e9-9836-2502c385ac44.png">

2. Theme setting, note that "Oceanic" is selected, but Oceanic colours are not being used.
<img width="1326" alt="Screenshot 2019-09-23 10 24 49" src="https://user-images.githubusercontent.com/233585/65415067-e70e3880-ddec-11e9-9085-51379958d30e.png">

3. I set to "Material Darker" and click apply, correct colours (for Darker theme) apply
<img width="1326" alt="Screenshot 2019-09-23 10 28 56" src="https://user-images.githubusercontent.com/233585/65415113-fbeacc00-ddec-11e9-899d-a611e600b609.png">

4. I reset and apply the oceanic theme, colours are now corret
<img width="1326" alt="Screenshot 2019-09-23 10 29 39" src="https://user-images.githubusercontent.com/233585/65415146-0e650580-dded-11e9-937d-b90ea9548373.png">

### Expected behavior

The theme to stay consistent across multiple instances of the theme.

### Actual behavior

The theme varies.

### Environment
```
PhpStorm 2019.2.2
Build #PS-192.6603.42, built on September 12, 2019
Licensed to Shed Collective Ltd / Pablo de la Pena
Subscription is active until July 15, 2020
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 4
Registry: search.everywhere.symbols=false, run.processes.with.pty=TRUE, search.everywhere.configurations=false, ide.mac.allowDarkWindowDecorations=true, search.everywhere.toolwindows=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.dubreuia, com.steve.plugins.autoscroll, main.kotlin.com.jimschubert.intellij.swaggercodegen
```

**Comment by mallowigi** [comment]
Settings synchronization between third-party plugin installations is not supported. What you're seeing is the current look and feel syncing but it's faulty since it's saved in Material Theme Settings which are not synchronized. Until then, there's nothing I can do.
