### ISSUE TITLE
change height of tabs

### ISSUE THREAD

**Issue by annechko** [ChrisRM/material-theme-jetbrains#1386]
the tab height is really large, it might be beautiful etc, but I need to work - I barely see my code because the whole area is small now
![image](https://user-images.githubusercontent.com/12374676/65606844-d952e180-dfab-11e9-8026-84145750b665.png)

can I somehow change the height of bars - like bottom one, while running tests and open tabs heigth?

**Comment by mallowigi** [comment]
No there is no such way to do so at the moment. Perhaps in the future JB will create an api to do so but at the moment is not possible.
