### ISSUE TITLE
Do you have a build which works with PHPStorm 2019.3 EAP?

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#1387]
Hey there

Just curious if you have a build that works with PHPStorm 2019.3 EAP?  I am currently refraining from using the EAP release based on the notification that it is not supported

I am guessing this is a broad version statement and have not tried it yet myself.

No worries at all if not, just curious.  I am working just fine with the current PHPStorm 2019.2 release.

Thanks in advance 😃

**Comment by mallowigi** [comment]
What? MT 4.6.0 is supposed to work with 2019.3

**Comment by mikeerickson** [comment]
@mallowigi when you do a Check for updates, it states this project is not compatible (I can send you screenshot later). But If you say so, I will believe you 🤓

**Comment by mikeerickson** [comment]
@mallowigi Here is the screenshot I was referring.  This warning prompted my report

<img width="993" alt="image" src="https://user-images.githubusercontent.com/183153/65825312-62774c00-e22a-11e9-804e-df3f1db5522d.png">

**Comment by mallowigi** [comment]
Well you will have to download 4.6.0 after you update.

**Comment by mikeerickson** [comment]
Not a problem, I was just telling you where I saw it. Not a big deal at all, just giving you information.
