### ISSUE TITLE
Projects sometimes don't load in DataGrip

### ISSUE THREAD

**Issue by natematykiewicz** [ChrisRM/material-theme-jetbrains#1388]
### Summary

Sometimes when I open a project in DataGrip, I get nothing. Just a blank screen. No "Loading Projects" window or anything. Trying to open a project from the menu does nothing. When I disable the plugin, my projects load fine.

### Expected behavior

Launch DataGrip and see my "default" Project.

### Actual behavior

Launch DataGrip and see a blank screen.

### Steps to reproduce (if needed)

1. Open DataGrip.
2. See empty screen

<img width="1792" alt="Screen Shot 2019-09-26 at 10 30 36 PM" src="https://user-images.githubusercontent.com/5104186/65740152-692c8480-e0ad-11e9-853f-5b1181bcfc6e.png">

### Environment

* macOS 10.14.6
* DataGrip 2019.2.5
* Plugins: IdeaVim
* Material Theme 4.5.1
* material_theme.xml

```
<application>
  <component name="MaterialThemeConfig">
    <option name="fileIcons" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="settingsSelectedTab" value="2" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="[REDACTED]" />
    <option name="version" value="4.5.1" />
  </component>
</application>
```

**Comment by mikumi** [comment]
I have exactly the same issue in Webstorm, regardless of the selected color theme. As soon as I resize the window the project appears though. So it looks like it's not an "project not loading" issue but rather something like a a "UI is not being drawn" issue 🤔

**Comment by natematykiewicz** [comment]
@mikumi It must be the same issue, because resizing the window magically fixes it. Suddenly my "Loading Project..." menu opens, I get a little status bar on the window that tells me it's running 2 processes, which quickly close. It's like the entire app doesn't always initialize, but a resize causes it to load.

I should point out that I can go days without an issue. Sometimes if I close and re-open DataGrip a few times it'll finally load. But just before I created this ticket, I must have tried closing and re-opening a dozen times and still nothing. This window resize trick made it functional again.

**Comment by mallowigi** [comment]
This issue has been resolved by the latest JB Runtime, but it's only since 2019.3 which is not the case here. Another workaround is to disable the "Themed Title Bar" in the Material UI settings and restart.

**Comment by natematykiewicz** [comment]
I don’t have a DataGrip 2019.3 available. I just updated to DataGrip 2019.2.5 yesterday, which is when it stopped working yesterday. Are you saying I need to wait for DataGrip 2019.3 to release and then this issue will resolve itself?

**Comment by natematykiewicz** [comment]
To be clear, I’ve had this problem intermittently for a little bit now, so it’s not just that 2019.2.5 introduced it.
