### ISSUE TITLE
Bug: macOS 10.14: Theme blocks my editor content (screenshot)

### ISSUE THREAD

**Issue by om2c0de** [ChrisRM/material-theme-jetbrains#1389]
<img width="718" alt="Screen Shot 2019-09-29 at 5 27 36 PM" src="https://user-images.githubusercontent.com/24379113/65834103-3e764200-e2e0-11e9-96b9-507b6ed21372.png">

### Summary
When I open my PyCharm on macOS 10.14.6 my IDE looks like on the screenshot, but all other windows like "Preferences" and so on - works correctly, I can fix my problem with choosing "File->Open->(And then after finder opens, my editor looks fine, I just click "Cancel" and continue to use plugin in the correct way.)

Also, I know, that if I delete the "Material theme" plugin, all works fine. 

### About my IDE configuration.
PyCharm 2019.2.2 (Professional Edition)
Build #PY-192.6603.34, built on September 10, 2019
Runtime version: 11.0.3+12-b304.56 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.paperetto.dash, me.fingerart.idea.apidebugger, mobi.hsz.idea.gitignore, BashSupport, ru.meanmail.plugin.requirements, zielu.gittoolbox

Plugin version: 4.5.1.

**Comment by mallowigi** [comment]
Please disable the themed title bar setting and restart

**Comment by om2c0de** [comment]
Yes, it works correct in this way..but I love themed title bar)

**Comment by om2c0de** [comment]
I set themed title bar again and restart, seem like all looks fine...I think we can close bug

**Comment by mallowigi** [comment]
So please close it

--
Elior
