### ISSUE TITLE
Theme is disabled when PC is resumed from sleep

### ISSUE THREAD

**Issue by Stefan-Z-Camilleri** [ChrisRM/material-theme-jetbrains#1392]
### Summary

When restoring PC from sleep mode, theme is disabled until the IDE is restarted.

### Expected behavior

Theme should persist without changes.

### Actual behavior

A mixture of the basic IDE theme and material theme is used.

### Steps to reproduce (if needed)

1. First step
Configure IDE theme to Material UI.

2. Second step
Put your PC to sleep (in my case, generally for over 10hr)

3. Third step
Restore PC from sleep.

### Environment
Windows 10.  
IDE Settings Sync enabled.

IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.3793.14, built on September 25, 2019
IntelliJ IDEA EAP User
Expiration date: October 25, 2019
Runtime version: 11.0.4+10-b485.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 64
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.plugins.watcher, CMD Support, GrepConsole, JProfiler, Karma, Lombook Plugin, Pythonid, Statistic, awesome.console, com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.dubreuia, org.intellij.scala, com.github.ArtsiomCh.NestedBracketsColorer, com.github.kisstkondoros.codemetrics, com.godwin.json.parser, com.intellij.ideolog, com.intellij.kubernetes, com.intellij.plugins.html.instantEditing, com.jotc.nsis.plugin.nsis, com.khmelyuk.multirun, com.krylysov.nsisplugin, com.thoughtworks.gauge, com.webstorm.symbols, com.wix.sasslint, com.wix.scss.lint, intellij.prettierJS, io.github.qeesung.component.HighlightBracketPair, io.pivotal.jasmine, io.plugin.tsnode, izhangzhihao.rainbow.brackets, krasa.CpuUsageIndicator, nb-mind-map-idea, net.vektah.codeglance, org.elm.klazuka, org.jetbrains.plugins.vue, org.para.plugin.openInSplittedTab, reasonml, tv.twelvetone.intellij.plugins.intellivue

* Material Theme Plugin version - 4.6.0

**Comment by mallowigi** [comment]
Do you have sync settings enabled ? The plugin doesn't work well with sync settings because sync settings doesn't work with third party plugins, so it reverts to the original LAF - Darcula/Light

**Comment by Stefan-Z-Camilleri** [comment]
Indeed I do (as mentioned in description).

Ok, then I will live with it :) Thank you @mallowigi
