### ISSUE TITLE
Background under breakpoint line is too dark in Atom One Light theme

### ISSUE THREAD

**Issue by lephuongbg** [ChrisRM/material-theme-jetbrains#1393]
### Summary

Background under breakpoint line is too dark in Atom One Light theme

### Expected behavior

The background should be lighter.

### Actual behavior

![image](https://user-images.githubusercontent.com/1001176/66184471-27a46680-e6b7-11e9-9705-6db8e683e7b5.png)

### Environment

PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-23-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 951M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, keymap.windows.as.meta=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.dubreuia, com.mallowigi.idea, mobi.hsz.idea.gitignore, com.jetbrains.intellij.datalore, NodeJS, com.jetbrains.plugins.jade, org.jetbrains.plugins.vue, AWSCloudFormation, org.jetbrains.plugins.node-remote-interpreter, org.toml.lang, ru.adelf.idea.dotenv, some.awesome, zielu.gittoolbox

Material Theme Plugin version: 5.0

**Comment by mallowigi** [comment]
will be fixed in next release
