### ISSUE TITLE
Project view not loading in latest rubymine eap

### ISSUE THREAD

**Issue by RobertCristian** [ChrisRM/material-theme-jetbrains#1394]
### Summary

In the latest version of Rubymine EAP(193.4099.3) coupled with Material Theme UI v4.7.0, the project view with the code and basically everything, is not loading. There is no error whatsoever or if there is, I can't see it.

![Screenshot 2019-10-04 at 09 47 45](https://user-images.githubusercontent.com/5216587/66187128-be0f6280-e68c-11e9-8495-cb476ce161e9.png)

I didn't have any custom settings for material theme plugin, just a simple install and set the theme to material darker.

### Steps to reproduce (if needed)

1. Install latest Rubymine EAP
2. Install material theme ui plugin
3. Restart App and that's it

### Environment

RubyMine 2019.3 EAP
Build #RM-193.4099.3, built on October 1, 2019
RubyMine EAP User
Expiration date: October 31, 2019
Runtime version: 11.0.4+10-b485.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: org.jetbrains.plugins.vue, ru.adelf.idea.dotenv
Plugins: Vue.js + material theme ui

**Comment by mallowigi** [comment]
Are you in full screen ? If yes try to exit full screen and re enter it.

**Comment by RobertCristian** [comment]
I completely uninstalled rubymine following https://intellij-support.jetbrains.com/hc/en-us/articles/206544519 and made a clean install which resolves this.

**Comment by mallowigi** [comment]
In any case, turning off the themed title bar is usually fixing it
