### ISSUE TITLE
Notification gets cut off

### ISSUE THREAD

**Issue by GregShanken** [ChrisRM/material-theme-jetbrains#1396]
### Summary

Notification on the bottom right of the screen is always cut off when showing

### Expected behavior

Should show the notification without cutting off the content

### Actual behavior

Content of notification is cut off

### Steps to reproduce (if needed)

Happens when a notification is shown. Link of screenshot below:

https://www.dropbox.com/s/ijo94odtycdsdu6/Screenshot%202019-10-07%2019.19.57.png?dl=0

### Environment

- MacOS Mojave 10.14.6
- PhpStorm 2019.2.3
- Material Theme UI 4.5.1
- Other plugins
  - IdeaVim 0.53
  - Laravel 0.15.4

Material Theme XML

```
<application>
  <component name="MaterialThemeConfig">
    <option name="arrowsStyle" value="Plus-Minus" />
    <option name="allowDataCollection" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="80cbc4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="userId" value="44f459ea:1640500a0db:-8000" />
    <option name="version" value="4.5.1" />
  </component>
</application>
```

Material Custom Theme XML

```
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Cannot reproduce. Are you in HiDPi?

**Comment by GregShanken** [comment]
hi @mallowigi, not sure what my mac is using, but this happens on both my main monitor (retina) and extended monitor (non retina).

**Comment by mallowigi** [comment]
I don't see your status bar either. Looks like your window is overflowing your screen. Make sure you are in maximized state.
