### ISSUE TITLE
(question) which icon is this dabbing pickle?

### ISSUE THREAD

**Issue by bariod** [ChrisRM/material-theme-jetbrains#1397]
What's the original svg for this icon?  

![image](https://user-images.githubusercontent.com/35639254/66454302-c3dbbe00-ea67-11e9-81ef-eedc534bd2a7.png)

It's kinda hard to make out what it's displaying with this small size, so yeah; dabbing pickle.

**Comment by mallowigi** [comment]
its a thread.

**Comment by bariod** [comment]
oooh :D  
why is it assigned to ``.ini`` files for me?

**Comment by mallowigi** [comment]
Probably another plugin, can you tell me the list of plugins you use?

**Comment by bariod** [comment]
![image](https://user-images.githubusercontent.com/35639254/66545734-a841e780-eb3b-11e9-8bdf-a1f62c618105.png)

**Comment by mallowigi** [comment]
Cannot reproduce... try to disable plugins

**Comment by bariod** [comment]
Try to add a registered pattern to the ``INI Config`` file type, as I did. Maybe that's the cause.

**Comment by mallowigi** [comment]
Managed to reproduce, but this is unrelated to the plugin. Simply the Ini plugin is using the same icon as the threads icon. If you disable the Material Theme you'll see what I mean.
