### ISSUE TITLE
README link to contributors wrong

### ISSUE THREAD

**Issue by bariod** [ChrisRM/material-theme-jetbrains#1398]
### Summary
The hyperlink on the contributors list adds ``/blob/master/`` to the url.  (line 449 in file)  
That page does not exist.

### Expected behavior
https://github.com/ChrisRM/material-theme-jetbrains/graphs/contributors

### Actual behavior
https://github.com/ChrisRM/material-theme-jetbrains/blob/master/graphs/contributors

**Comment by mallowigi** [comment]
please do a PR for this
