### ISSUE TITLE
Port to Android Studio 

### ISSUE THREAD

**Issue by objaa** [ChrisRM/material-theme-jetbrains#14]
Hello, thanks for your work!
It looks very nice, soon please add support for AS! <3

(cant add label enhancement)

Thanks, thanks!

**Comment by ChrisRM** [comment]
I'm working on it :-)

**Comment by ChrisRM** [comment]
I might try porting it to AS later, but this project is for JetBrains IDEs only.

**Comment by lyt1025** [comment]
works well on AS

**Comment by ChrisRM** [comment]
@lyt1025 Does it? Are you sure you're not mixing the two (IntelliJ IDEA and Android Studio)?

**Comment by lyt1025** [comment]
Yes it is ,I try it  on  Android  Studio. Android Studio is based on  IntelliJ IDEA,but it has a litile unclear.
![qq 20151006230023](https://cloud.githubusercontent.com/assets/4133185/10312499/1a7eaaf4-6c7e-11e5-9e57-2b4b1cbd02d6.png)

**Comment by ChrisRM** [comment]
Wow, I didn't know that. I'll be sure to add better support for it then :)

**Comment by objaa** [comment]
What's happening? :DD

ITS REALLY WORK ON AS!!

but what happend with default font? it is really biggest

![image](https://cloud.githubusercontent.com/assets/7000585/10312685/e86a23dc-6c54-11e5-93de-ddad3cecdee3.png)

**Comment by ChrisRM** [comment]
It's on my todo-list!

**Comment by objaa** [comment]
hm, light theme are available or coming soon?

**Comment by ChrisRM** [comment]
Coming very soon!
