### ISSUE TITLE
Java, gradle icons in not shown, Android Studio 2.0

### ISSUE THREAD

**Issue by Pedramrn** [ChrisRM/material-theme-jetbrains#140]
![image](https://cloud.githubusercontent.com/assets/7994739/12025559/6f598fc0-adc5-11e5-8fcb-4632ad61d729.png)
I have seen the #121

**Comment by Not2EXceL** [comment]
Bug is with all variants. https://github.com/ChrisRM/material-theme-jetbrains/issues/121 fixed the editor issue not the icons.

https://github.com/ChrisRM/material-theme-jetbrains/blob/master/resources/icon_associations.xml#L61

It's been commented out. Based on history it was an accident I'm guessing?

**Comment by ChrisRM** [comment]
Should be fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/4d1622e92d7bb667880416f3f4fe8dd275978b0e
