### ISSUE TITLE
Unused import is not distinguishable with regular import

### ISSUE THREAD

**Issue by lephuongbg** [ChrisRM/material-theme-jetbrains#1400]
### Summary

*As title*. Current theme is Atom One Light.

### Expected behavior

Unused import should be of different style.

### Actual behavior

![image](https://user-images.githubusercontent.com/1001176/66625853-e967f380-ec30-11e9-9550-216be151940c.png)

### Environment

PyCharm 2019.2.3 (Professional Edition)
Build #PY-192.6817.19, built on September 25, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-23-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 951M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, keymap.windows.as.meta=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.dubreuia, com.mallowigi.idea, mobi.hsz.idea.gitignore, com.jetbrains.intellij.datalore, NodeJS, com.jetbrains.plugins.jade, org.jetbrains.plugins.vue, AWSCloudFormation, org.jetbrains.plugins.node-remote-interpreter, org.toml.lang, ru.adelf.idea.dotenv, some.awesome, zielu.gittoolbox

Material Theme Plugin version: 5.0

**Comment by mallowigi** [comment]
Fixed, but I'm not releasing fixes for 2019.2. You will have to update to EAP to have it. You can also change it manually though.
