### ISSUE TITLE
Not working with Intellij 2019.2.3

### ISSUE THREAD

**Issue by mabecth** [ChrisRM/material-theme-jetbrains#1401]
### Summary

The plugin does not work with Intellij 2019.2.3. It casues a blank page at startup leading to not being able to develop.

### Expected behavior

Working as usual

### Actual behavior

Not working

### Environment

IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Licensed to Marcus Bertilsson
Subscription is active until July 22, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Registry: ide.mac.allowDarkWindowDecorations=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi, com.konifar.material_icon_generator
Material Theme Plugin version: 4.5.1

**Comment by mallowigi** [comment]
Please disable Themed title bar and restart.

**Comment by abhinav1602** [comment]
@mallowigi thanks. working now
