### ISSUE TITLE
Rework color schemes

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#1403]
Okay assigning default values to color schemes proved to be a bad idea as it breaks between updates of the main color schemes, leading to some inconsistencies. Happened with PHP and Go, now Markdown. 

Need to redo all this and assign hardcoded values -sigh-

**Comment by GiorgioBalestrieri** [comment]
I still have this issue... not sure why multiple issues about this have been closed without a clear solution

**Comment by mallowigi** [comment]
Because there is no solution. I tried to decouple the schemes from the default ones but many functions of the IDE broke as a result of that, so I had to revert back to inherit from Light/Darcula, and thus this is once again a problem.

I've had enough of fixing this honestly, I don't know how many times I had to check every color of every color scheme because of an update from JetBrains. If you find an issue, please open a PR with the fix. I won't do it unless it conflicts with my day to day work, which is usually Java, Ruby and JavaScript. Other languages are out of scope.
