### ISSUE TITLE
The push dialog lacks the bottom toolbar

### ISSUE THREAD

**Issue by Lodin** [ChrisRM/material-theme-jetbrains#1404]
### Summary
The push dialog miss the toolbar with the `Push` button, `Push tags` checkbox etc. since the WebStorm 2019.2 on Windows. It makes the theme unusable because I cannot push any of my changes to the GitHub. 

### Expected behavior
The push toolbar is visible as it was before the WebStorm 2019.2 update.

### Actual behavior
The push toolbar is missing since WebStorm 2019.2 on Windows 10.

### Steps to reproduce (if needed)

1. Open WebStorm >= 2019.2 on Windows. 
2. Open project with initialized git repo.
3. Try to push changes to the remote repository.

### Screenshot
![image](https://user-images.githubusercontent.com/8037479/66685145-522c8b80-ec84-11e9-85e3-934e1afb6a3c.png)

### Environment
```
WebStorm 2019.2.3
Build #WS-192.6817.13, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0, jest.test.tree.use.jasmine.reporter=false
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.intellij.properties, com.jetbrains.darkPurpleTheme, org.intellij.plugins.postcss, BashSupport, org.toml.lang, org.rust.lang, ru.adelf.idea.dotenv
```

<details>
  <summary>material_theme.xml</summary>

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactDropdowns" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="rightTreeIndent" value="6" />
    <option name="settingsSelectedTab" value="6" />
    <option name="accentColor" value="4caf50" />
    <option name="selectedTheme" value="DARKER" />
    <option name="version" value="4.5.1" />
  </component>
</application>
```
</details>

<details>
  <summary>material_custom_theme.xml</summary>

```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="33424a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```
</details>

**Comment by mallowigi** [comment]
Please make sure you have the latest Material Theme version

**Comment by Lodin** [comment]
@mallowigi, thanks for the answer. I have the latest version, it is 4.5.1. And I probably found what is happening. 

I reinstalled my WebStorm from scratch and found that by default the push window is OK. However, I cannot decrease its height: it starts to hide control buttons if I do it, and in the end the window becomes like at the screenshot I provided. 

![image](https://user-images.githubusercontent.com/8037479/66829480-23503700-ef5c-11e9-94c3-24f27ebdba44.png)
Default state.
![image](https://user-images.githubusercontent.com/8037479/66829526-3b27bb00-ef5c-11e9-8e4a-68fd7ca0f07c.png)
Trying to decrease the height.
![image](https://user-images.githubusercontent.com/8037479/66829558-4d095e00-ef5c-11e9-8599-502eece016ee.png)
Decreased height.

I suppose the original issue happens because of something like the size of the font I used.

**Comment by Lodin** [comment]
@mallowigi, I found the source of the problem. It is connected with some specific settings of the IDEA for the Windows. It affects not only the Material UI theme, but all the IDEA products. The global issue can be found [here](https://youtrack.jetbrains.com/issue/IDEA-219173).

The solution can be found there as well. I also leave it here for anyone who tries to solve this issue like me:

> please try disabling borderless UI by adding `ide.win.frame.decoration=false` in **Help | Edit Custom Properties** and restarting the IDE.

This fix helped me.
