### ISSUE TITLE
Font setting should keep with default one in default

### ISSUE THREAD

**Issue by leaxoy** [ChrisRM/material-theme-jetbrains#1406]
First, I change color schema setting global font setting,  then I install this material ui and change use material ui, but the font different with the global one.
Example: I change font to Jetbrains Mono, but material ui keep Menlo one.

**Comment by mallowigi** [comment]
Material UI schemes specify a font for their editors, so it overrides the default global font. If you want to change it, go to Color Scheme Font in the Settings
