### ISSUE TITLE
Turns function names to black color in pycharm - issue persists ( #174)

### ISSUE THREAD

**Issue by ScoobyQ** [ChrisRM/material-theme-jetbrains#1408]
Why was this issue closed before please?

https://github.com/ChrisRM/material-theme-jetbrains/issues/174

It remains a problem with 2019 community edition. One has to manually make changes to settings in lots of places. Surely, the theme should pretty much render as advertised where ever downloaded from.

Issue persists with the following set-up:

PyCharm 2019.2.3 (Community Edition)
Build #PC-192.6817.19, built on September 25, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry:
Non-Bundled Plugins:

**Comment by mallowigi** [comment]
Closing this in favor of #1403
