### ISSUE TITLE
Cannot close the Last tab using the cross x button

### ISSUE THREAD

**Issue by Neokyuubi** [ChrisRM/material-theme-jetbrains#1409]
I cannot close the last tab using the cross x because it's not there (it should be where i marked it in red in the attachment), this happens only when the number of the tabs that are opened exceed the number of the tabs that are shown.
![sc](https://user-images.githubusercontent.com/40678329/67053562-b2ff0c80-f139-11e9-8372-edcfe72cdca9.jpg)

I might be wrong but it seems like the last tab get cropped !

And this is my tabs limit number : 
![sc1](https://user-images.githubusercontent.com/40678329/67054539-d4152c80-f13c-11e9-9426-cd8488eb4c3b.jpg)

Windows
PhpStorm 2019.2.3
Material Theme UI 4.5.2
```
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="customSidebarHeight" value="36" />
    <option name="settingsSelectedTab" value="5" />
    <option name="accentColor" value="528569" />
    <option name="selectedTheme" value="DARKER" />
    <option name="version" value="4.5.2" />
  </component>
</application>

**Comment by mallowigi** [comment]
Yeah I now about this but I think it’s a bug independent of the plugin. However if you select that tab it should scroll into view am I right?

**Comment by Neokyuubi** [comment]
@mallowigi Well that's the thing no mater how i try to scroll it never reach the right end of the last tab to see the close button ! 
But i just disabled the plugin and you were right, the bug is still there, so it's IDE related,
Sorry, i should have try it before posting.

**Comment by mallowigi** [comment]
It’s okay but as I said whenever it happens to me, once I select this tab the x scrolls into view usually.

**Comment by Neokyuubi** [comment]
Ok thanks, so i'm closing this one since it has nothing to do with the plugin.
