### ISSUE TITLE
Accent color is not being assigned/used

### ISSUE THREAD

**Issue by TheMesoria** [ChrisRM/material-theme-jetbrains#1412]
### Summary

Accent color is being not correctly assigned.
Let me give you example. I pick "Darker theme" and expect that I will get `orange` accent. Instead for some reason it forces the `pink` color from monokai accent. Moreover, pop up boxes inherit this color, which is extremely annoying.

![image](https://user-images.githubusercontent.com/9269398/67276988-15ebfd00-f4c6-11e9-8dc2-d7bf3dda6942.png)

...

### Expected behavior
When I pick accent, I desire it to be set correctly.
...

### Actual behavior
It is not set correctly, and have to do it by hand
...

### Steps to reproduce (if needed)

Might be just my local issue, but
1. Install material theme on any machine

![image](https://user-images.githubusercontent.com/9269398/67277074-4895f580-f4c6-11e9-818c-8b74d1c9da48.png)
Even that I have choosen to set one from theme.
Moreover, It is already selecting this color on material theme installer...

### Environment

CLion 2019.2.4
Build #CL-192.6817.32, built on October 9, 2019
Licensed to `XXX`
You have a perpetual fallback license for this version
Subscription is active until August 1, 2020
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-18-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi

<application>
  <component name="MaterialThemeConfig">
    <option name="accentMode" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="1bfb057a:16df2f47661:-8000" />
    <option name="version" value="4.5.2" />
  </component>
</application>%

**Comment by TheMesoria** [comment]
Minor twist, while playing with contrast to fix another strange (for me) issue The colors just updated themselves but created another awkwardness:

![image](https://user-images.githubusercontent.com/9269398/67279414-3a96a380-f4cb-11e9-92b1-2e8151b6ad5e.png)

### Workaround I used:

Turn on and off high contrast multiple times...

**Comment by mallowigi** [comment]
Can you specify the whole steps? I don't really understand the issue...

**Comment by TheMesoria** [comment]
The issue is that the Material theme sometimes tends to color too much of space with an accent. I ask for forgiveness, I was busy, and this issue just fell out of my mind.

**Comment by mallowigi** [comment]
Try to disable the "Accent Mode"
