### ISSUE TITLE
Theme and accent look bad on footer

### ISSUE THREAD

**Issue by dogmaxpeppe** [ChrisRM/material-theme-jetbrains#1414]
I'm on Linux Mint, and the indicator for Theme Name and Accent color placed on footer looks very bad, as you can see on this picture:

![Schermata del 2019-10-24 16-52-25](https://user-images.githubusercontent.com/1201742/67498192-59d63200-f67f-11e9-8375-f7a208667cc0.png)

Am I need certain fonts to make it look better? (I've already installed Roboto Fonts)

**Comment by mallowigi** [comment]
I'm not developing for Linux unfortunately, so if you can figure out the solution yourself and do a PR, that would be appreciated.
