### ISSUE TITLE
Editor scrollbars border not themed correctly

### ISSUE THREAD

**Issue by gempir** [ChrisRM/material-theme-jetbrains#1417]
### Summary

Scrollbar color of Editor scrollbars doesn't edit border color. 

### Expected behavior

Scrollbars are completely colored with desired color.

### Actual behavior

Theme color stays on the scrollbar as border and only inner color is customized.

### Steps to reproduce (if needed)

1. Select any Material Theme
2. Go to Editor->Color Scheme->General->Vertical Scrollbar->Thumb
3. change the Background color
4. Below in the preview you will see the border of the scrollbar be still color of the theme (purple in the screenshot below)

![image](https://user-images.githubusercontent.com/9765622/67956287-23a33000-fbf4-11e9-9f22-27a72aa88f7e.png)

### Environment

Plugin Version: 4.5.2

IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Runtime version: 11.0.4+10-b304.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, BashSupport, com.jetbrains.php, com.jetbrains.twig, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, org.jetbrains.plugins.phpstorm-remote-interpreter, Pythonid, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer

**Comment by mallowigi** [comment]
Please open an issue in jetbrains
