### ISSUE TITLE
Git diff is not readable

### ISSUE THREAD

**Issue by tenhobi** [ChrisRM/material-theme-jetbrains#1418]
### Summary

In current behavior, when I select the git diff, there is (w/ enabled Hightlight Words) not readable text highlighting.

### Expected behavior

Git diff (Highlight Words) is readable.

### Actual behavior

The color of git diff (Highlight Words) is not readable.

![image](https://user-images.githubusercontent.com/5287596/67993822-e0bc7900-fc42-11e9-9e41-2c2a223f6201.png)
![image](https://user-images.githubusercontent.com/5287596/67993828-e9ad4a80-fc42-11e9-9dec-0f4d01a1a541.png)

### Steps to reproduce (if needed)

1. Click to the git diff gutter rectangle icon
2. See the modal

### Environment

IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 29, 2019
Licensed to Jan Bittner
Subscription is active until September 23, 2020
For educational use only.
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 978M
Cores: 4
Registry: java.completion.argument.hints.internal=false, ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.almightyalpaca.intellij.plugins.discord, com.bloc.intellij_generator_plugin, com.chrisrm.idea.MaterialThemeUI, Dart, io.flutter, de.mariushoefler.flutter_enhancement_suite

Material Theme UI is in version 4.5.2 w/ Material Darker

**Comment by mallowigi** [comment]
I'm afraid i can't reproduce. However at the current time I'm working on fixing a lot of inconsistencies in the color schemes, so please wait until it's done, then after resetting to defaults try to see if that reproduces.
