### ISSUE TITLE
Kotlin class icon is same as Java class icon

### ISSUE THREAD

**Issue by binaryfork** [ChrisRM/material-theme-jetbrains#1420]
<img width="189" alt="Screenshot 2019-11-02 at 13 40 33" src="https://user-images.githubusercontent.com/5114308/68069820-a2c07180-fd76-11e9-8724-f9d2c906cc65.png">
As you can see JavaClass and KotlinClass are same. Also no icon for Kotlin enum.

### Expected behavior
Maybe use KotlinFile icon for KotlinClass? Or place little kotlin icon on all kotlin icons.

### Environment

Android Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 26, 2019
JRE: 1.8.0_202-release-1483-b49-5587405 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6

Material theme 3.1.0 Arc Dark

**Comment by mallowigi** [comment]
It’s been fixed in recent versions, unfortunately android studio is lagging behind so there is nothing I can do.

Try with Android studio canary
