### ISSUE TITLE
Add null, true, false, undefined to additions

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#1422]

**Comment by leo4all** [comment]
Does is possible to add support for PHP Additions ? Primitives Type: null, true, false, undefined.

**Comment by mallowigi** [comment]
Someone already did that: https://plugins.jetbrains.com/plugin/13592-php-syntax-color-highlighter

I'm considering removing this feature as it creates conflicts with other extensions of the same flavor.
