### ISSUE TITLE
Project File list icons extremely small

### ISSUE THREAD

**Issue by cralvarado** [ChrisRM/material-theme-jetbrains#143]
I am having an issue where the icons next to each file in the project file list view are extremely small. Wondering if there is a known issue with this. I am attaching a screenshot as reference.

![webstorm](https://cloud.githubusercontent.com/assets/2000148/12145916/8f970e7e-b456-11e5-9983-ad377ca1ba01.png)

**Comment by ChrisRM** [comment]
Is this still a problem for you @cralvarado? I'm not able to reproduce this.
