### ISSUE TITLE
Specification/documentation for decorators and colors in folders

### ISSUE THREAD

**Issue by pleger** [ChrisRM/material-theme-jetbrains#1431]
Hi, I am Paul and thanks a lot for your work.
     I know decorators and colors provide useful information to developers, but I cannot find the information. For example, I don't know what no-filled folder means in the following folders (see image). Any information would welcome.  

![image](https://user-images.githubusercontent.com/702443/68356944-1be50d80-0157-11ea-9a22-1af5f2918cab.png)

**Comment by mallowigi** [comment]
Hi, you can find more information about obscure parts of the plugin in the documentation site. Go take a look!
