### ISSUE TITLE
Background color tabs bar looks ugly and different

### ISSUE THREAD

**Issue by claudioviola** [ChrisRM/material-theme-jetbrains#1432]
### Summary
In latest webstorm version I installed Material UI theme with Material Palenight
Background color tabs bar file looks very strange and ugly (bright green)

I attached screenshot of my Webstorm and one screenshot of material ui.
As you can see theere is an ugly green background in the editor tabs
Anyway I don't think the issue comes from Material UI Theme

...

### Expected behavior
Background color tabs bar should looks like as screenshot in material theme website. More fashion then mine
...

### Actual behavior
Background color tabs bar file looks very strange and ugly bright greens
In screenshot of Material UI Theme website looks more fashion

...

### Environment
Mac 10.15
Webstorm 2019.2
Material 4.5.2

[material_theme_configs.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3823839/material_theme_configs.zip)
![my-webstorm](https://user-images.githubusercontent.com/6689594/68465317-8909a900-0212-11ea-9ef3-80c232697965.png)
![material_ui_screenshot](https://user-images.githubusercontent.com/6689594/68465318-8909a900-0212-11ea-8471-36bcf93dc1fa.png)

**Comment by mallowigi** [comment]
You probably activated the “Accent mode” inadvertently. You can disable it in the Material theme settings or using the action palette.

**Comment by claudioviola** [comment]
@mallowigi and yes!
it worked!
Accent mode was on in  Settings -> Appearance  - > Material Theme - > Components

Many thanks!
