### ISSUE TITLE
Autocompletion window filled with tree selection color when appear

### ISSUE THREAD

**Issue by OptimumDev** [ChrisRM/material-theme-jetbrains#1433]
### Summary

In WebStorm when code autocompletion window appears all variants have background of tree selection color
![image](https://user-images.githubusercontent.com/38810090/68534561-bdd34880-0357-11ea-8ba2-c8c58a8b75dc.png)
Autocompletion however works fine (as though first variant is selected)
![image](https://user-images.githubusercontent.com/38810090/68534584-fffc8a00-0357-11ea-9438-018bd23ae167.png)
This selection disappear and colors became fine as soon I use arrow keys
![image](https://user-images.githubusercontent.com/38810090/68534623-418d3500-0358-11ea-9efd-d08125ff2386.png)

### Expected behavior

I whould expect first variant selected when autocompletion window opens:
![image](https://user-images.githubusercontent.com/38810090/68534657-a21c7200-0358-11ea-85b8-191331c9c835.png)

### Actual behavior

![Behavior gif](https://media.giphy.com/media/TLCWwn6aJW8aap05xj/giphy.gif)
All variants are selected with tree selection color:
![image](https://user-images.githubusercontent.com/38810090/68534958-dbef7780-035c-11ea-8582-82a77b7a4fc9.png)
![image](https://user-images.githubusercontent.com/38810090/68534989-296be480-035d-11ea-9dba-22b56e38fbbb.png)

### Steps to reproduce (if needed)

1. Start to write any code
2. Wait until autocompletion window appear

It works this way only on automatic appearance of this window. If you use `Ctrl+Space` shortcut, window opens normaly and colors are good

### Environment

WebStorm 2019.2.2
Build #WS-192.6603.19, built on September 3, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 947M
Cores: 4
Registry: ide.tree.ui.experimental=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI

**Comment by mallowigi** [comment]
Sigh this auto completion problem again...

**Comment by mallowigi** [comment]
fixed
