### ISSUE TITLE
Vertical spacing between tabs when displayed on the side

### ISSUE THREAD

**Issue by MichaelBrock** [ChrisRM/material-theme-jetbrains#1435]
I installed the Material UI  in Phpstorm and it is a breath of fresh air.  One thing however, I would like to change is the spacing between file names when displaying the tabs on the side.   Currently there is a lot more space than in the native theme.   There is a Materials UI to "Toggle Compact Sidebar" which does a very nice job of removing whitespace on the project listing but does not change the side-tab bar listing of open files.

This is in Phpstorm 2019.2.5  and the version of Material UI is listed as 4.5.2.  I see that the latest version here for jetbrains is 4.9.2.  Is it possible to force it to update to the latest version?

**Comment by mallowigi** [comment]
Have you tried to reduce the tan height? They might be on the side but they still keep the tab height you defined. Try it.

**Comment by MichaelBrock** [comment]
Thanks for the suggestion. I tried this before with no luck.   I changed the tab height in the Material Theme Wizard and it makes no difference to the appearance of the  side positioned tabs.  Even set to just 1, makes no change.

**Comment by MichaelBrock** [comment]
I moved the tabs to the top by way of testing and the "Tab Height" setting does not appear to make any change to the tabs there either. 
![Capture](https://user-images.githubusercontent.com/16259627/69151749-38fbd380-0aa9-11ea-9e4d-79dd6aad0e0c.PNG)

**Comment by mallowigi** [comment]
In your settings I'm seeing the tabs at the top, not sure I'm following. Also sometimes it doesn't fully apply until next restart.

**Comment by MichaelBrock** [comment]
I moved the tabs to the top just to test to see whether it made a difference  where the tabs were located.  However, your suggestion to restart Phpstorm has done the trick!  The "tab height" setting now affecting the tabs on the side.  Thanks!
