### ISSUE TITLE
Space being added on find and open windows

### ISSUE THREAD

**Issue by moyeradon** [ChrisRM/material-theme-jetbrains#1436]
### Summary

When using the find, replace, and open windows (so far as I can tell for now), an extra space is being added automatically. It's not detrimental nor does it appear to affect the accuracy of the search results; it is more of an inconvenience and UI issue. 

### Expected behavior

When I type in the input boxes, it shouldn't add extra space and should appear to be verbose to what I type.

### Actual behavior

When I type in the aforementioned windows, it adds extra space.

### Steps to reproduce (if needed)

1. Open the Find in Path Window
2. Start Typing
3. Notice Space added at end of entered text.

![image](https://user-images.githubusercontent.com/24224641/69236394-67d58080-0b61-11ea-868c-f823009a8d64.png)

![image](https://user-images.githubusercontent.com/24224641/69236290-3492f180-0b61-11ea-9c08-dc98b8774367.png)

![image](https://user-images.githubusercontent.com/24224641/69236351-51c7c000-0b61-11ea-84ac-d3c33e27dbc5.png)

### Environment

I mostly noticed this after I upgraded to Max OS X Catalina. I don't recall seeing this beforehand. I can confirm this is in RubyMine and PhpStorm so far as I've seen it. Below is my configuration for RubyMine.

```
RubyMine 2019.3 Beta
Build #RM-193.5233.24, built on November 14, 2019
RubyMine EAP User
Expiration date: December 14, 2019
Runtime version: 11.0.4+10-b520.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1092M
Cores: 4
Registry: bigger.font.in.project.view=true, ide.balloon.shadow.size=0, completion.stats.show.ml.ranking.diff=true
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI
```

And my custom theme.xml: 
```
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="009688ff" />
    <option name="notificationsColor" value="323232ff" />
    <option name="treeSelectionColor" value="546e7aff" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="607d8bff" />
    <option name="foregroundColor" value="b0bec5ff" />
    <option name="backgroundColor" value="263238ff" />
  </component>
</application>
```

Thanks!

**Comment by mallowigi** [comment]
I know about this, I’ll fix this in a future version

**Comment by mallowigi** [comment]
I thought it was gonna be an easy fix but it is breaking a few things. I will leave it as it is as it is pretty minor. Sorry.
