### ISSUE TITLE
Issues with items on the bottom of the IDE (phpstorm / intelliJ Idea Ultimate)

### ISSUE THREAD

**Issue by InfRandomness** [ChrisRM/material-theme-jetbrains#1437]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
Bottom informations in PHPStorm and IntelliJIdea (Ultimate edition) all messed up.
...

### Expected behavior
Having each elements at the bottom of the IDE not stacking up. 
...

### Actual behavior
Each items at the bottom of the IDE are stacking up (chars count, line breaks, (codota icon)).
...

### Steps to reproduce (if needed)

1. Install IntelliJ Idea 2019.3 RC | PHPStorm 2019.2.5
2. Install the material theme plugin (and codota if you wanna test it out with this plugin too)
3. Configure it to Material darker, High contrast, default, default

You can also add Screenshots for a better understanding.
PHPStorm:
https://imgur.com/Hh7RGu5
IntelliJ Idea:
https://imgur.com/8cfs9WP
### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

PHPStorm:
`
PhpStorm 2019.2.5
Build #PS-192.7142.51, built on November 13, 2019
Licensed to xx xx xx
Subscription is active until September 26, 2020
For educational use only.
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.11-1-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 1939M
Cores: 16
Plugin Version: 4.5.2
Installed plugin:
.env files support,
ANSI Highlighter,
Atom Material Icons,
Discord Integration (Almighty Alpaca),
Ideolog,
Laravel,
Material Theme UI,
Nord,
PHP Annotations,
PHP Toolbox,
Symfony support,
UIkit
`
Plugin Configuration: https://paste.titin.fr/#b50b49.xml

IntelliJ Idea 
`
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.57, built on November 20, 2019
Licensed to Brice Nourry-Cabrol
Subscription is active until September 26, 2020
For educational use only.
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.11-1-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 3939M
Cores: 16
Plugin version: 4.9.2.1
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, Dart, Jetbrains TeamCity Plugin, com.almightyalpaca.intellij.plugins.discord, com.arcticicestudio.nord.jetbrains, com.chrisrm.idea.MaterialThemeUI, com.codota.csp.intellij, com.intellij.vaadin, com.maff.codingcounter, com.mallowigi, com.strv.linecounter, io.flutter, org.sonarlint.idea
`
Plugin Configuration: https://paste.titin.fr/#b50b49.xml

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
This is a common issue in Linux. I will not be fixing that.

Please note that you can disable the statusbar widget in the settings.

**Comment by InfRandomness** [comment]
That's not my problem. This program does not work correctly.
