### ISSUE TITLE
The color of the frame will be lost suddenly during the use

### ISSUE THREAD

**Issue by 625250353** [ChrisRM/material-theme-jetbrains#1438]
During my normal use,The tool's frame suddenly loses its theme color.Reset will take effect.This problem has happened many times,But it doesn't happen every time you use it.

**Comment by mallowigi** [comment]
Do you have sync settings enabled ?

**Comment by 625250353** [comment]
Yes,Synchronization is on.Is it because of it?What to do?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Elior Boukhobza"<notifications@github.com&gt;; 
发送时间: 2019年11月25日(星期一) 下午5:40
收件人: "ChrisRM/material-theme-jetbrains"<material-theme-jetbrains@noreply.github.com&gt;; 
抄送: "孙"<625250353@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ChrisRM/material-theme-jetbrains] The color of the frame will be lost suddenly during the use (#1438)




Do you have sync settings enabled ?

**Comment by mallowigi** [comment]
Yes, material theme settings are not synced as opposed to ide settings. This causes an out of sync issue when the current Look and Feel (such as Darcula) overrides the Material Theme LaF. It happened to me as well when using Sync Settings

Please follow up the issues https://youtrack.jetbrains.com/issue/IDEA-218426 https://youtrack.jetbrains.com/issue/IDEA-202248 https://youtrack.jetbrains.com/issue/IDEA-219861

In the meanwhile, please disable Sync Settings if you're not using it. If you need to use it anyway, simply restart the IDE if it happens again.

**Comment by 625250353** [comment]
Thank you for your answer,It helped me a lot.
