### ISSUE TITLE
Feature Request: Mac OS dark mode automatic change

### ISSUE THREAD

**Issue by VictorKolb** [ChrisRM/material-theme-jetbrains#1439]
Thank for incredible plugin! Is planning of automatic themes change support in Mac OS depending on the time of day?

**Comment by mallowigi** [comment]
The problem is that the plugin doesn’t have a light theme and dark theme per se. It has multiple themes.

What do you suggest?

**Comment by VictorKolb** [comment]
Hello, @mallowigi! For example, in Telegram I can choose dark theme when Mac OS change system theme on dark: 
![image](https://user-images.githubusercontent.com/14196649/69549230-ef7c1e80-0fa9-11ea-90ad-3c74666e913d.png)

**Comment by mallowigi** [comment]
Yes but there are no dark theme in the plugin...

**Comment by VictorKolb** [comment]
> Yes but there are no dark theme in the plugin...

Wait, this is ANOTHER plugin? 
![image](https://user-images.githubusercontent.com/14196649/69549514-7c26dc80-0faa-11ea-9d15-87d6b1923848.png)

**Comment by VictorKolb** [comment]
I thinks this feature possible realize with a choice – in daylight pick one theme, and dark – another

**Comment by mallowigi** [comment]
Interesting. However I don't think such an issue will be popular because the plugins light themes are not that interesting.

I'll leave it open for now.

**Comment by TansanDz** [comment]
Thank u for this Superb information about printer sites. It is very useful for all the printer users . If you need any help related to printer related queries just visit my blogs given here

<a href="https://www.salut-itech.com/2019/11/how-writers-can-use-github-to-store-their-work.html"> العنوان </a>
<a href="https://www.salut-itech.com/2019/11/how-to-copy-and-paste-on-a-chromebook.html"> العنوان </a>
<a href="https://www.salut-itech.com/"> العنوان </a>

**Comment by nymo** [comment]
I would like to see this feature too. On daytime when you are in very bright places a dark theme is not usable. At evening it is another case. So currently I have to switch every day manually my theme from light to dark. This would be really handy.
I think a choice which theme I want to use for daylight and which one for night would be enough.

**Comment by zjopy** [comment]
Just to add another endorsement, I would very much appreciate an automatic theme change based on the system theme. I, for one, like to use the light theme during the day, because text is easier to read.

**Comment by kenime** [comment]
Vote for this feature as well! I tried another plugin [macOS Dark Mode Sync](https://plugins.jetbrains.com/plugin/12515-macos-dark-mode-sync) and it is not compatible with Material UI Theme (which is pretty obvious).

There seems to be a easy way of checking by polling
`defaults read -g AppleInterfaceStyle`
However I am unfamiliar with JetBrain plugin development and I am at no position to judge the complexity.

**Comment by riconeitzel** [comment]
I’m in as well!

**Comment by IncPlusPlus** [comment]
@kenime Thanks for mentioning that plugin. Using the method that plugin uses to detect the OS theme would make this change compatible with MacOS and Windows! The tricky bit is to make a mechanism for selecting which theme is associated with the dark and light modes (and periodically polling for changes?).

**Comment by mallowigi** [comment]
Guys, someone already thought of that: I suggest you to check, it works wonderfully.

https://plugins.jetbrains.com/plugin/14076-auto-dark-mode

Please use this plugin in conjunction with the Material Theme plugin (or any theme you want actually).

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/80617744-266bca00-8a4b-11ea-8e07-5b1af471c29b.png)
