### ISSUE TITLE
Plugin incompatible with WebStorm 2019.3

### ISSUE THREAD

**Issue by bender316** [ChrisRM/material-theme-jetbrains#1441]
### Summary

After update to WebStorm 2019.3 the plugin gets disabled with the following error:

Plugin "Material Theme UI" is incompatible (target build range is 192.6262.7 to 192.*).

### Environment

WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Licensed to ***
Subscription is active until May 7, 2020
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 4
Registry: ide.balloon.shadow.size=0, js.debugger.use.node.options=false
Non-Bundled Plugins: BashSupport, CMD Support, com.denis.zaichenko.angular.2.ws.live.templates, com.widerwille.afterglow, io.probst.idea.clangformat

**Comment by mallowigi** [comment]
Please update to the latest Material UI version

**Comment by bender316** [comment]
Argh. For whatever reason it didn't offer me an update of Material UI in WebStorm. I got it updating now. Sorry for the disturbance.
