### ISSUE TITLE
.KT files not changing into corresponding icons only if the class has a different name than the file

### ISSUE THREAD

**Issue by blendicavlad** [ChrisRM/material-theme-jetbrains#1442]
As the title says, if for example i have the file UserService.kt with a class declared as UserService the file icon is the java one, but if i change the class name to Userservice the file icon changes to kotlin logo.
I know it is a very minor issue but if i have kt and java classes in the same package i can't distinguish them, thanks! :)

**Comment by mallowigi** [comment]
Imo it’s because the file name should be the same as the class name, so it displays the cube one. By putting service you discredited the PSI linking between the class and the file, so you get the default kotlin icon. Am I right?

**Comment by mallowigi** [comment]
This being said I don’t have any plans to have different psi icons, so it’s unfortunate. You can use the default icons if you’d like.

**Comment by blendicavlad** [comment]
Oh, ok then, i thought the cubes were supposed to be java classes, you can mark this as solved.
