### ISSUE TITLE
Quarkus Dark Theme - Request

### ISSUE THREAD

**Issue by VMGlobantGNBSudameris** [ChrisRM/material-theme-jetbrains#1445]
Hello! 
Any chance on taking a look at the Quarkus theme? is  beautiful theme.

![image](https://user-images.githubusercontent.com/55590914/69875569-7885a500-128b-11ea-8b09-20a43f9fc34a.png)

**Comment by mallowigi** [comment]
Hmm I don't think I'll do it. You're free to download your own plugin as an extension though.
