### ISSUE TITLE
unreadable variable names

### ISSUE THREAD

**Issue by can0199** [ChrisRM/material-theme-jetbrains#1446]
Hey if you have an unused variable PHPStorm make the name darker, if you go with the cursor in the name of the variable PHPStorm mark this and all other variables with the same name. 
So the problem is now if the variable is unused and you go with the cursor into the variable you can not read the variable name

![Bildschirmfoto 2019-11-29 um 15 21 15](https://user-images.githubusercontent.com/6803382/69875438-6d4b6d00-12bd-11ea-924d-fcb25755cadf.png)

It would be better if the text change his color to white so long its marked

It should contain:
MAC OS 10.14
PhpStorm 2019.2.5 Build #PS-192.7142.51, built on November 13, 2019
Plugin version 4.5.2

I use the darker theme

Thank you in advance

**Comment by mallowigi** [comment]
I would have done it but unfortunately this would apply to all identifiers under the caret, not only the ones that are unused. This would call all identifiers to become white/dark. I'll try other solutions.

**Comment by mallowigi** [comment]
I'll add opacity to the identifier under caret background.
