### ISSUE TITLE
Pom.xml not showing text colors on Intellij IDEA 

### ISSUE THREAD

**Issue by kaduartur** [ChrisRM/material-theme-jetbrains#1449]
My pom are not showing the text colors **(Atom one dark theme | V4.9.2.1)**:
![image](https://user-images.githubusercontent.com/17505818/69886269-df24b600-12bf-11ea-86a7-f2fac3241ccb.png)

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/70083227-ad3f8680-1614-11ea-9686-414a64df419a.png)

have you checked with the plugin off ?
