### ISSUE TITLE
Outdated color scheme

### ISSUE THREAD

**Issue by ShahidH** [ChrisRM/material-theme-jetbrains#145]
material-theme-jetbrains is currently using outdated color scheme that look a bit different to Sublime Material Theme updated color scheme.

On Sublime Material Theme github, the old color scheme has been moved to OLD folder, see https://github.com/equinusocio/material-theme/tree/master/schemes

**Comment by ShahidH** [comment]
Has color scheme been updated?

**Comment by mannykary** [comment]
@ShahidH - Not sure if it has been updated here, but I did have some issues with the color scheme in Ruby. I ended up grabbing the updated theme from that repo and converted it to a format compatible with Jetbrains. The converted format is available [here](https://raw.githubusercontent.com/mannykary/editor-themes/master/idea/Material-Theme.xml).

Depending on your OS, you'll have to place it in the `colors` folder (create it it doesn't exist):

OS X: `~/Library/Preferences/RubyMineXX/colors/`
Linux: `~/.RubyMineXX/config/colors`
Windows: `<USER HOME>\.RubyMineXX\config\colors`

(replace RubyMineXX with the name of your IDE)

Then restart the IDE and you should be able to select the new color scheme in Preferences (or Settings) > Editor > Colors & Fonts.

I made the suggestion to use this color scheme in another [ticket](https://github.com/ChrisRM/material-theme-jetbrains/issues/199#issuecomment-237245160) but I'm not sure when or if it'll be done.
