### ISSUE TITLE
Cannot find the plugin in Pycharm under Deepin (a linux distro)

### ISSUE THREAD

**Issue by catriuspham** [ChrisRM/material-theme-jetbrains#1450]
### Summary

Material Theme is missing from Market place.

### Expected behavior

Type in "material" in the search box of Market place should show our plugin on the top of the result.

### Actual behavior

The plugin does not show up.

![material missing](https://user-images.githubusercontent.com/17242255/69928901-b6830300-14ef-11ea-87e9-0172866f36cc.png)

### Environment

PyCharm 2019.1.2 (Professional Edition)
Build #PY-191.7141.48, built on May 7, 2019
JRE: 1.8.0_181-8u181-b13-2~deb9u1-b13 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.15.0-30deepin-generic

**Comment by mallowigi** [comment]
Hi! I don’t know why would the plugin not appear in the repository, but you should probably ask Jetbrains about it. Have you tried downloading the plugin directly from the marketplace?
