### ISSUE TITLE
Full screen title bar is redundant 

### ISSUE THREAD

**Issue by breeze-ev** [ChrisRM/material-theme-jetbrains#1451]
version 4.10.0, phpstorm 2019.3

Full screen title bar is redundant When i enable Themed Title Bar, could you remove that in full screen mode (sorry, from google translation)
<img width="182" alt="image" src="https://user-images.githubusercontent.com/13219988/69933479-e4754100-1509-11ea-94e1-2d87047f8e37.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/13219988/69933663-72e9c280-150a-11ea-8c23-542b0bad6841.png">

**Comment by mallowigi** [comment]
You need to restart the ide

**Comment by breeze-ev** [comment]
I'm sure that I enabled this feature and then restarted the ide, but it still, Unless I turn Themed title bar  off
