### ISSUE TITLE
Add icon for Go file creation

### ISSUE THREAD

**Issue by dpcat237** [ChrisRM/material-theme-jetbrains#1452]
### Summary
It would be nice to add an icon for the Go file on the menu for GoLand. I could add it if you can guide me.

### Expected behavior
Have a Go icon on the menu.

### Actual behavior
No icon

### Steps to reproduce

1. Open top menu 'File'
2. Click 'New'

You can also add Screenshots for a better understanding.

### Environment

	GoLand 2019.3
	Build #GO-193.5233.112, built on November 28, 2019
	Licensed to Denys Pasishnyi
	You have a perpetual fallback license for this version
	Subscription is active until January 3, 2021
	Runtime version: 11.0.4+10-b520.11 amd64
	VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
	Linux 5.3.9-050309-generic
	GC: ParNew, ConcurrentMarkSweep
	Memory: 1921M
	Cores: 8
	Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true, folding.check.collapse.state.before.placeholder.text=TRUE, ide.balloon.shadow.size=0, ideFeaturesTrainer.welcomeScreen.tutorialsTree=TRUE
	Non-Bundled Plugins: BashSupport, Key Promoter X, NodeJS, com.chrisrm.idea.MaterialThemeUI, io.protostuff.protostuff-jetbrains-plugin, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.hcl, org.jetbrains.plugins.vue

### Material Theme Config

	<application>
	  <component name="MaterialThemeConfig">
	    <option name="allowDataCollection" value="true" />
	    <option name="isWizardShown" value="true" />
	    <option name="accentColor" value="009688" />
	    <option name="userId" value="8f19084:16ec6300065:-8000" />
	    <option name="version" value="4.10.0" />
	  </component>
	</application>

**Comment by mallowigi** [comment]
Go there: 

![image](https://user-images.githubusercontent.com/5015756/70083586-5b4b3080-1615-11ea-9067-3a14177408c5.png)

**Comment by dpcat237** [comment]
@mallowigi The icons are specified no on this page but on "Editor" -> "File Types".
Here is from the original design:
![original](https://user-images.githubusercontent.com/388031/70387198-a6b16600-19aa-11ea-942a-b96e88a41233.png)

Here is with Material design
![material](https://user-images.githubusercontent.com/388031/70387209-bdf05380-19aa-11ea-9d32-8ef7d24c8710.png)
Differences:
- "Go" types doesn't have icon
- "Go Template" has the original icon
- Opened file `tf.go` has Go icon from Material design. It's strange why it isn't configured globally.

It's not possible to set an icon from IDE's settings. Exists issue related to this https://youtrack.jetbrains.com/issue/IDEA-70992.

As you can see this issue appears activating Material design and can't be changed from Settings.

**Comment by mallowigi** [comment]
fixed

**Comment by dpcat237** [comment]
Thanks! Funny icon :D
