### ISSUE TITLE
Upgrading Phpstorm to 2019.3 but theme plugin is not compatible

### ISSUE THREAD

**Issue by MichaelBrock** [ChrisRM/material-theme-jetbrains#1454]
I recently installed the Material Theme UI plugin in Phpstorm version 2019.2.5. I'd like to update to 2019.3 but the update process reports that the Material Theme UI is not compatible.  The version of Material Theme reported in Phpstorm is only 4.5.2 and does not show the option to update.  How do I update it to a version compatible with 2019.3, preferably 4.10?

**Comment by mallowigi** [comment]
Just update PHPStorm first, then update the plugin after.
