### ISSUE TITLE
Change color or add icon to touched files that have not been submitted to source control

### ISSUE THREAD

**Issue by born2net** [ChrisRM/material-theme-jetbrains#1455]
I often have many files open in my Tabs, but would like to clearly see which files I touched but have NOT submitted to source control. Right now they are colored light green but it is VERY hard to see in dark theme and distinguish them over the normal white text .
Be awesome if we could change color to red or something or maybe show an icon the same way we have it for edited files.

see image

![color](https://user-images.githubusercontent.com/5090936/70062153-5c8b4780-159a-11ea-98d8-6d4ad6d51e0e.png)

Thank you got a great project,

Sean.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/70083444-0ad3d300-1615-11ea-8322-ca4dbbf69a54.png)

Make sure you are using pristine color schemes.

**Comment by born2net** [comment]
Sorry but where do I find that? looked under themes and did not see that,,

**Comment by born2net** [comment]
do I edit that in an XML file?
could not find pristine setting anywhere...
TX

Sean

**Comment by mallowigi** [comment]
I mean check if you had unmodified color schemes. You can find this in Settings > Color Scheme and check if your color schemes are modified.
