### ISSUE TITLE
Colors are not applied to pom.xml file in Night Owl Theme 

### ISSUE THREAD

**Issue by normanwss** [ChrisRM/material-theme-jetbrains#1456]
### Summary
As caption say,colors are not applied to pom.xml in Night Owl Theme in IDE IntelliJ Community edition.

### Expected behavior
We expect that the theme can render pom.xml,instead of current dark-grey color.

### Actual behavior
Screenshot for reference:
![night owl theme](https://user-images.githubusercontent.com/3325876/70118557-4321f280-16a3-11ea-8b8e-1340def39677.jpg)

### Steps to reproduce (if needed)

1. Open a maven project which its pom.xml contains tags <dependency>,<plugin> etc.. in IDE intelliJ Community.
2. Open pom.xml file
3. Colors are applied after the file is opened,but it turns to dark-grey color after 1 seconds.

### Environment
OS:Windows 10
IDE:IDE Intellij Community 2019.3
Materia UI version:4.10.0

**Comment by mallowigi** [comment]
Are you sure this happens on material theme plugin? Can you check with the plugin disabled ?

**Comment by normanwss** [comment]
> Are you sure this happens on material theme plugin? Can you check with the plugin disabled ?

Not sure if casued by Material theme plugin or IDEA itself.
Other XML files are rendered well,except pom.xml.

No plugin is disabled in my idea intelliJ ide.

**Comment by mallowigi** [comment]
Can you try disabling the plugin and see if it is rendered correctly ?

--
Elior

**Comment by normanwss** [comment]
> Can you try disabling the plugin and see if it is rendered correctly ?
> […](#)
> -- Elior
> On 5 Dec 2019, 4:08 +0200, Sam Woo ***@***.***>, wrote: > Are you sure this happens on material theme plugin? Can you check with the plugin disabled ? Not sure if casued by Material theme plugin or IDEA itself. Other XML files are rendered well,except pom.xml. No plugin is disabled in my idea intelliJ ide. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for the reply.
Just follow your suggetions and the result is same.Colors are applied at begging but,after finished process "Loading Annotations",some content within pom.xml are turn to color dark-grey.

**Comment by mallowigi** [comment]
Can you post a list of plugins you are using ?
