### ISSUE TITLE
Goland "crashes", on load, when using Goland

### ISSUE THREAD

**Issue by OmisNomis** [ChrisRM/material-theme-jetbrains#1457]
### Summary

When opening some projects, Goland opens with a blank screen and does nothing until the window is resized. 

### Expected behavior

Goland loads properly.

### Actual behaviour

Goland loads with a blank screen, like it has crashed, and doesn't move on. As soon as the window is resized it loads correctly. 

Disabling the `Material UI` theme plugin resolves this issue. 

![image](https://user-images.githubusercontent.com/14848394/70228640-9439f100-174c-11ea-9e08-c49459053c62.png)

### Steps to reproduce (if needed)

1. Download `Material UI` plugin
2. Open Goland

You can also add Screenshots for a better understanding.

### Environment

GoLand 2019.3
Build #GO-193.5233.112, built on November 28, 2019

Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16

**Comment by mallowigi** [comment]
Are you sure you’re using the last version?

**Comment by OmisNomis** [comment]
> Are you sure you’re using the last version?

Yeah, definitely.

**Comment by mallowigi** [comment]
Are you in fullscreen?

**Comment by OmisNomis** [comment]
> Are you in fullscreen?

It happens in full screen and not full screen, but I am normally in full screen. I was able to replicate with the Goland `LearnProject` but can't share the video here.

**Comment by OmisNomis** [comment]
![screencast 2019-12-05 14-21-26](https://user-images.githubusercontent.com/14848394/70243730-133e2200-176b-11ea-8b55-c36dcbf55e4d.gif)

**Comment by OmisNomis** [comment]
Managed to get it uploaded after all ^^

**Comment by mallowigi** [comment]
This was a common problem in 2019.2 but it should have been fixed for 2019.3 ... Anyway I unfortunately cannot reproduce this, but there is an easy fix: just disable the `Themed Title Bar` feature from the settings and restart, that should do the trick.

**Comment by adampetrovic** [comment]
Also happening for me since 2019.3 (never before).

I notice it's mainly triggered when I have multiple Goland windows (different projects) opened simultaneously.
