### ISSUE TITLE
Arrow style "None" are broken

### ISSUE THREAD

**Issue by golman** [ChrisRM/material-theme-jetbrains#1458]
### Summary

Arrow style "None" don't work correctly

### Expected behavior

No arrows

### Actual behavior

"Darcula" arrows

### Steps to reproduce (if needed)

In plugin settings
1. Project view
2. Arrow style
3. Select "None"

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/1263663/70234838-f4478c00-177a-11ea-8347-9e61d63da8a6.png">

### Environment

IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: CheckStyle-IDEA, Key Promoter X, co.nums.intellij.aem, com.chrisrm.idea.MaterialThemeUI, com.dmarcotte.handlebars, com.dubreuia, com.intellij.plugins.html.instantEditing, org.intellij.scala, org.jetbrains.plugins.go-template, org.jetbrains.plugins.go, com.jetbrains.edu, com.jetbrains.php, com.jetbrains.plugins.jade, com.perl5, com.softwareco.intellij.plugin, com.tabnine.TabNine, com.wakatime.intellij.plugin, com.wix.sasslint, intellij.prettierJS, izhangzhihao.rainbow.brackets, mobi.hsz.idea.gitignore, org.jetbrains.plugins.vue, training, zielu.gittoolbox
Material Theme Plugin: 4.10.0

**Comment by mallowigi** [comment]
fixed for next version
