### ISSUE TITLE
PHPStorm 2019.3 Incompatibility issue release 4.10

### ISSUE THREAD

**Issue by J5Dev** [ChrisRM/material-theme-jetbrains#1459]
Hi after updating from PHPStorm 2019.2 to 2019.3 I am receiving both an issue whereby the plugin is identified as incompatible, and also if attempting to use the plugin, project simply open to a grey screen.

I do not believe this is related to issue #1454 as I was able to upgrade to version 4.10. However, following from that article as I had seen it before, I did follow the guidance given, but to no avail.

As instructed, I updated PHPStorm first, then my plugins, but Material theme still shows as incompatible even after updating to the latest version (4.10). If attempting to use the plugin by setting the plugin to be active, then upon opening a project, I simply get a grey screen. Disabling the plugin and restarting again lets project open again as normal

I have tried uninstalling & installing the plugin from scratch, but still the same issue.

Plugin Version 4.10
PHPStorm version 2019.3

**Comment by mallowigi** [comment]
I don't understand. What exactly happened and how to reproduce it?

Do you actually have PHPStorm 2019.3, but upon activating the plugin you are greeted with a gray screen? Care to share a screenview of it? 

Also please share your environment - PhpStorm exact version, OS, JDK etc.

**Comment by J5Dev** [comment]
Im not at the machine at the minute to get the exact versions or a screen, however in the interest of clarifying things till a point where I can...

1. I was using PHPStorm 2019.2, and used the PHPStorm update mechanism to update the platform (not a new install).
2. Once the update had completed, I was prompted that a number of plugins were not compatible (Material Theme being one).
3. I then proceeded to update the Material Theme plugin to the latest available version (4.10)
4. I then observed that he plugin was still identified as not compatible (little red stop symbol)
5. I then un-installed the plugin completely and re-installed to see if that helped, but it still showed as not compatible
6. I then activated the plugin anyway to see if it was simply a bug in identifying compatibility, however when the Material Theme plugin is active, when opening a project or starting a new one, the window which the project opens in is completely solid grey.

Hopefully that may help a little more, but once I am able I will also post some specifics for you.

**Comment by J5Dev** [comment]
Additional details:

PhpStorm 2019.3
Build #PS-193.5233.101, built on November 27, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1

Material Theme: 4.10.0 (No further updates seemingly available)

![image](https://user-images.githubusercontent.com/2751683/70339410-b6179e80-1846-11ea-8d7d-1f631144b373.png)

**Comment by mallowigi** [comment]
Can you try with the `themed title bar` option disabled ?

**Comment by J5Dev** [comment]
Perfect, this resolved the issue... Well it prevented it not working and the incompatibility icon is no longer present.

But I guess theres still a big there, but huge thanks for the help.

**Comment by mallowigi** [comment]
It's a regular issue with the JRE 11 owned by JetBrains. Which is odd though is that I could never reproduce it in any of my machines. I honestly have no idea why and there is no fix for this.

Please note that you can also check in the doc for future complaints: https://www.material-theme.com/docs/faq-troubleshooting/#settings

**Comment by J5Dev** [comment]
Thanks Mallowigi, awesome support as usual
