### ISSUE TITLE
Border Issue on Active Tabs

### ISSUE THREAD

**Issue by Raistlfiren** [ChrisRM/material-theme-jetbrains#146]
The border for active tabs does not seem to work properly. I use PHPStorm 10.0.3. Here are a few examples of what I am talking about:
![screen shot 2016-01-20 at 2 06 24 pm](https://cloud.githubusercontent.com/assets/234712/12461532/0cb145cc-bf7f-11e5-9291-1ca2215659bc.png)
![screen shot 2016-01-20 at 2 07 57 pm](https://cloud.githubusercontent.com/assets/234712/12461574/429eb566-bf7f-11e5-989e-fe2f9e1821ea.png)

**Comment by DericArlie** [comment]
Just to add to this, vertical tabs are the problem for me.  When tabs are placed on top or bottom it seems to be fine, but when they're vertical  it always shows the top/first tab as being always active.

**Comment by stygiansabyss** [comment]
This is now fixed in version 1.0.8.  At the time of this post it is not updated on jetbrains yet, but you can manually install the plugin to get the fix for this.

**Comment by Raistlfiren** [comment]
Awesome, thanks for the update @stygiansabyss! :+1:  I just tried it out, and it does seem to be working just fine.

Cheers!

**Comment by ChrisRM** [comment]
Fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/23742ee8d836ac7c19838feef0d08cd49dff1925
