### ISSUE TITLE
Version control log tree "current branch" not themed

### ISSUE THREAD

**Issue by cswgr** [ChrisRM/material-theme-jetbrains#1460]
In the version control log window, usually all commits from within the same branch are highlighted.
When the material theme plugin is activated, all commits have the same color, which is difficult to work with.
Have a look on the screenshot for which setting I mean.
![phpstorm64_nnYGkloIRo](https://user-images.githubusercontent.com/36189631/70244736-48e80880-1775-11ea-9fb9-14cfcd21d118.jpg)

**Comment by mallowigi** [comment]
Will be fixed on next version
