### ISSUE TITLE
IntelliJ 2019.3 Unused gray for curly braces and used symbols

### ISSUE THREAD

**Issue by charlesritchea** [ChrisRM/material-theme-jetbrains#1461]
### Summary

Since 2019.3

Used symbols and curly braces look unused

### Expected behavior

Only unused code should be this gray color

### Actual behavior

lots of things look unused

### Steps to reproduce (if needed)

![image](https://user-images.githubusercontent.com/1656349/70252767-fc3e0680-174f-11ea-9e38-702087c66f39.png)

### Environment

IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 27, 2019
Licensed to Pointivo / Charles Ritchea
Subscription is active until December 27, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-24-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4012M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Pythonid, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.intellij.kubernetes, com.intellij.plugins.html.instantEditing, net.ashald.envfile, org.intellij.plugins.hcl, org.jetbrains.kotlin, ru.adelf.idea.dotenv

Material Theme UI 4.10.0

[material_.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/3927941/material_.zip)

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
Do you have some project to share so we can reproduce?

**Comment by charlesritchea** [comment]
Not currently sorry

**Comment by mallowigi** [comment]
Can you pay the list of plugins you use?
