### ISSUE TITLE
Explicitly setting Java/Kotlin package icons feature request

### ISSUE THREAD

**Issue by DallasP9124** [ChrisRM/material-theme-jetbrains#1462]
I have a feature request. Currently when naming Java/Kotlin packages with a specific keyword, e.g. resource, data, layout, etc, the package icon is no longer a folder but the image tied to that keyword. In my opinion it makes the package structure a little confusing by giving unwanted emphasis on a set of code and having a bunch of packages represented with unrelated icons.

For example:
![example-dont-want](https://user-images.githubusercontent.com/13224109/70268769-f77c5100-1755-11ea-80b7-ef3621c7585a.png)

I think it would be nice to leave all package icon's as a default image of the folder and have an option to explicitly set an image for a package so we have more control over the emphasis.

**Comment by mallowigi** [comment]
The problem is that there is no way to differentiate a package from a regular folder, so it’s not possible to disable it on a package level. The only option would be to completely disable the feature.

**Comment by DallasP9124** [comment]
Right, that's what I mean by explicitly setting it when in the IDE. That way the user has full control after a certain project structure level. Maybe a language level feature?
Such as we know java has a src/main/java, anything within there can be selected for an icon assignment?
Just brainstorming.

**Comment by mallowigi** [comment]
Hmmm... the problem is that there is no way currently of knowing the parent folders. In any case there is no plans of adding a feature that have so few uses. 

I’ll check with vscode plugins equivalents to see if they had the same issue and got a solution.

Ideally one day I’ll implement the UI to disable and customize the file and folder associations
