### ISSUE TITLE
Invisible Color

### ISSUE THREAD

**Issue by julmot** [ChrisRM/material-theme-jetbrains#1463]
### Summary

I'm using PHPStorm 2019.3 with the Material Theme and 'Material Darker' theme. I've encountered issues like:

![000377](https://user-images.githubusercontent.com/8310677/70352036-85496080-186a-11ea-9953-58bf4215789c.png)

("Ok" isn't readable)

![000378](https://user-images.githubusercontent.com/8310677/70352040-867a8d80-186a-11ea-9a72-bcd7a5bfd31c.png)

(Minimize and maximize Windows icons aren't readable)

### Expected behavior

The font should always be visible

### Actual behavior

Sometimes the font is invisible

### Environment

I haven't applied any customization to the defaults.

PhpStorm 2019.3
Build #PS-193.5233.101, built on November 27, 2019
Licensed to Julian Kühnel
Subscription is active until April 11, 2020
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3981M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, Karma, com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.deadlock.scsyntax, com.dmarcotte.handlebars, com.intellij.ideolog, com.intellij.react.css.modules, com.wix.react-templates, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, nl.bixie.intellij.uikit, org.jetbrains.plugins.rest, org.jetbrains.plugins.stylus, ru.adelf.idea.dotenv

**Comment by mallowigi** [comment]
I really need some context for this. Please try to give a reproducible scenario.

**Comment by julmot** [comment]
The screenshot with the unreadable minimize icon can be found in the upper right corner of any PHPStorm window, especially in the main window.

The screenshot with the unreadable "Ok" font can be found in the Git push window when having all pushed already.

**Comment by julmot** [comment]
Here's another issue with unreadable font in TypeScript (when the const isn't used yet):

![000379](https://user-images.githubusercontent.com/8310677/70371319-cd4f9e00-18d1-11ea-895b-4d86db2cab6e.png)

**Comment by mallowigi** [comment]
This one has been fixed and will be available next release.

**Comment by mallowigi** [comment]
As for the button issue, I suspect this is after having switched themes from a lighter theme to darker, am I correct ?

**Comment by julmot** [comment]
I had the default PHPStorm dark theme previously, never had any other theme or lighter theme installed. I tried switching between material themes after I've encountered these issues, but none of the other themes had these things readable either.

**Comment by robibi78** [comment]
Hello,
Same problem for me, for the maxi/mini icons.

**Comment by iiegor** [comment]
Same here 🙋‍♂️

Just to note, this is a problem I'm having since the first day of the borderless window change (2019.2)

**Comment by mallowigi** [comment]
please try with latest version (4.1..2)
