### ISSUE TITLE
Can't save Matched brace color

### ISSUE THREAD

**Issue by xianggithubli** [ChrisRM/material-theme-jetbrains#1464]
OS:win7 material themeUI:4.5.2 webstorm:2019.2.4 theme:Material Darker color theme: MonoKai 
Can't save the custom Matched brace backgroud color, after restart webstorm , the color reset to the origial color 3b514d.

**Comment by mallowigi** [comment]
This is a bug from the Rainbow Brackets plugin. Please open an issue there.
