### ISSUE TITLE
imports highlighting WebStorm(2019.3)

### ISSUE THREAD

**Issue by victororlyk** [ChrisRM/material-theme-jetbrains#1467]
### Summary
the colors of imports in Webstorm (2019.3) with plugin Material Plugin 4.11.0. is highlighting colors differently without any reason
...

### Expected behavior
highlight with the same style at least for a project level.
...

### Actual behavior
it highlights the imports with different colors.
...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

<img width="362" alt="imports" src="https://user-images.githubusercontent.com/33072590/70379435-43d1b780-1935-11ea-9054-636ee5e8056c.png">
<img width="318" alt="imports2" src="https://user-images.githubusercontent.com/33072590/70379436-43d1b780-1935-11ea-92eb-203d6a370521.png">
<img width="525" alt="imports3" src="https://user-images.githubusercontent.com/33072590/70379437-43d1b780-1935-11ea-907d-576d3a3c34ad.png">
<img width="472" alt="imports4" src="https://user-images.githubusercontent.com/33072590/70379438-446a4e00-1935-11ea-8226-a4f88b7ae4ff.png">

You can also add Screenshots for a better understanding.

### Environment

WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.codota.csp.intellij, com.deadlock.scsyntax, com.intellij.lang.jsgraphql, com.wakatime.intellij.plugin, com.wix.eslint, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv

It should contain:
* OS ( Mac)
* Webstorm (2019.3)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version 4.11.0

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/color-scheme-additions/
