### ISSUE TITLE
Not compatible with rainbow brackets

### ISSUE THREAD

**Issue by izhangzhihao** [ChrisRM/material-theme-jetbrains#1469]
### Summary
Not compatible with rainbow brackets

### Expected behavior

The color scheme should not be override

![image](https://user-images.githubusercontent.com/12044174/70410769-26aefd00-1a8b-11ea-97c5-f9cde029d48c.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/12044174/70410746-0da64c00-1a8b-11ea-8318-ac24b816f776.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 4
Registry: java.completion.argument.hints.internal=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, com.cursiveclojure.cursive, com.jetbrains.php, izhangzhihao.rainbow.brackets, org.intellij.scala, org.jetbrains.plugins.ruby
```

**Comment by izhangzhihao** [comment]
Also related to https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/365#issuecomment-562902926

**Comment by mallowigi** [comment]
fixed

**Comment by izhangzhihao** [comment]
Greate!

**Comment by kaushikkamal** [comment]
![error](https://user-images.githubusercontent.com/30615934/89733778-752af600-da75-11ea-9c53-1c146d7c195a.jpg)

Where is the colour changing options?

**Comment by izhangzhihao** [comment]
Which version are you using? Try to upgrade to the latest?
在 2020年8月9日，下午9:52，Kaushik Kamal Borah <notifications@github.com> 写道：

﻿

[error]<https://user-images.githubusercontent.com/30615934/89733778-752af600-da75-11ea-9c53-1c146d7c195a.jpg>

Where is the colour changing options?

**Comment by kaushikkamal** [comment]
I am using the latest android studio 4.0.1 with Material Theme UI (Material Darker)
and the plugin is also up to date.
But still, no colour scheme is shown

**Comment by izhangzhihao** [comment]
> I am using the latest android studio 4.0.1 with Material Theme UI (Material Darker)
> and the plugin is also up to date.
> But still, no colour scheme is shown

I mean which rainbow brackets plugin version are you using?

**Comment by kaushikkamal** [comment]
the latest one downloaded from the android studio marketplace 4.9
but then I again download it from the JetBrains website, it's 5.35
but no one works, the same issue

//all info about android studio
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b01 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, com.chrisrm.idea.MaterialThemeUI, com.google.services.firebase, com.mallowigi, io.flutter, izhangzhihao.rainbow.brackets

**Comment by izhangzhihao** [comment]
Any error messages?

**Comment by kaushikkamal** [comment]
nope...

**Comment by izhangzhihao** [comment]
> nope...

What about trying to disable material theme ui plugin temporarily？
