### ISSUE TITLE
Black class and function definitions in Python

### ISSUE THREAD

**Issue by flying-sheep** [ChrisRM/material-theme-jetbrains#147]
`def` and `class` are black on dark grey/blue

**Comment by kodi** [comment]
Same here:


![image](https://cloud.githubusercontent.com/assets/51153/12759516/d4a18e90-c9e1-11e5-9395-ed8e9efbd993.png)

Also, that blue for annotation is not that good/visible as well.

**Comment by flying-sheep** [comment]
and more…

**Comment by syphar** [comment]
same here, what is needed for a fix? Any information / test? 

I'm happy to review/test everything

**Comment by syphar** [comment]
<img width="271" alt="screenshot 2016-02-03 08 04 07" src="https://cloud.githubusercontent.com/assets/540890/12775243/c8e15516-ca4c-11e5-8677-f5caba45d39f.png">

another strange color would be the kwargs names

**Comment by Someguy123** [comment]
Definitely needs fixed, affects both `default` and `darker`. Makes editing Python a nightmare, currently stuck with the default theme for now until this is fixed.

**Comment by Someguy123** [comment]
For anyone who needs a good temporary fix, here are some colours that work (tested on `darker`):

Function Definition: #6A96B6

Keyword Arguments: #BF6870

Built-in Name: #507794

Class Name: #389E34

Decorator: #389E34

An image example:
![Image](https://i.imgur.com/Sisu7Sl.png)

**Comment by syphar** [comment]
thanks @Someguy123 :) definitely helps

**Comment by kodi** [comment]
Hi,
Any news on this?

**Comment by ChzenChzen** [comment]
=( project is die

**Comment by kodi** [comment]
This project started so great, and then it just went silent for a month :-1: 

:(

**Comment by arcticicestudio** [comment]
The repository owner wrote that he's busy at work atm in another issue, you could try to fix it on your own and push a PR so he can check and merge it as soon as he got time for it again.

**Comment by ChrisRM** [comment]
I'll go through all the issues as soon as I have time, I want to improve this and make it more flexible. Just got to prioritize my primary job atm. Tbh, I'm no Java-developer and I hoped someone else with a little more Java experience would have forked the repo and improved it by now.

I'll see if I can free up some time to deal with all the issues here asap.

**Comment by kstratis** [comment]
@Someguy123 Thank you. Much appreciated.

**Comment by carlthome** [comment]
:+1: on a fix.

**Comment by mallowigi** [comment]
Should be fixed in the latest release.

**Comment by SalahAdDin** [comment]
@mallowigi Which have we to use: yours of this?

**Comment by mallowigi** [comment]
both
