### ISSUE TITLE
Icon for LICENSE files is too permissive

### ISSUE THREAD

**Issue by lukeify** [ChrisRM/material-theme-jetbrains#1470]
### Summary

I have an application that has a database model of `License`, and as such, I have several files throughout the application that have this term as a prefix. `LicenseStore.php`, `LicenseController.php`. These are being given a yellow copyright symbol as the file icon in the Project viewer, instead of the correct filetype icon. For example:

<img width="207" alt="Screen Shot 2019-12-10 at 10 33 15 PM" src="https://user-images.githubusercontent.com/5379845/70517538-97ded500-1b9d-11ea-81ad-8990f5a2ddea.png">

### Expected behavior

I would expect to see this icon only if the file is fully named  `LICENSE` (in uppercase) or some of the format-specific derivatives, such as `LICENSE.md`.

### Actual behavior

It appears the usage of this icon is not sufficiently constrained, and appears as seen in the above screenshot.

### Environment

PhpStorm 2019.3
Build #PS-193.5233.101, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
macOS 10.15.1
Non-Bundled Plugins: BashSupport, com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.jetbrains.lang.ejs, in.xiv.cs, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.postcss, org.jetbrains.plugins.rest, org.toml.lang, org.rust.lang, ru.adelf.idea.dotenv

No custom Material Theme configuration.

**Comment by mallowigi** [comment]
fixed in 4.11.4
