### ISSUE TITLE
Editor tabs placement 'none' + accent mode is still visible

### ISSUE THREAD

**Issue by nicovak** [ChrisRM/material-theme-jetbrains#1471]
### Summary

Activate the component `accent mode` with an editor tab settings placement set to none (invisible) still show 1 or 2 px.

### Expected behavior

Accent mode shouldn't show the editor tab

### Actual behavior

Accent mode show the editor tab on 1 or 2 px

### Steps to reproduce (if needed)

1. Set Editor tabs > tab placement to `None`

![Image 1](https://i.imgur.com/Ss5ZPeT.jpg)

2. Activate `Acent mode` in components tab of material theme plugin settings

![Image 2](https://i.imgur.com/mrcClmd.jpg)

### Environment

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.31, built on December 10, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1092M
Cores: 4

**Comment by mallowigi** [comment]
should be fixed

**Comment by nicovak** [comment]
It is fixed with the last version, thanks ;)
