### ISSUE TITLE
WHITE SCREEN

### ISSUE THREAD

**Issue by MarshallTaylorV** [ChrisRM/material-theme-jetbrains#1472]
Hello I have a little problem when I deactivate the theme everything works but when I activate the screen becomes white as snow

![Sans titre 3](https://user-images.githubusercontent.com/28553653/70878045-c868a980-1fb7-11ea-8e83-5318a2e0c6ce.png)

**Comment by MarshallTaylorV** [comment]
I use Idea 2019.3
for the theme I use the latest version

**Comment by sclihuiming** [comment]
me too
![image](https://user-images.githubusercontent.com/9551770/70882283-1a3a1f80-200a-11ea-8c47-b81a2f3efe2a.png)
environment：
intelli idea 2019.3 Ultimate
macos 10.13.6
material ui 4.11.1

**Comment by mallowigi** [comment]
Please disable theme title bar and restart.
