### ISSUE TITLE
Weird border under active tab

### ISSUE THREAD

**Issue by lllopo** [ChrisRM/material-theme-jetbrains#1473]
Their is a similar (and fixed) issue from 2016, but I'm not sure it is the same, so I'm creating a new one. There is a weird border appearing under the active tab since latest release. Here's what I'm talking about :

![Untitled](https://user-images.githubusercontent.com/5485902/70893393-ac82f900-1ff3-11ea-82e4-89603a196f16.png)

**Comment by mallowigi** [comment]
It's the tab shadow. you can disable it in the settings

**Comment by lllopo** [comment]
@mallowigi No, tab shadow is disabled.

**Comment by lllopo** [comment]
I can confirm this is still an issue in 5.0 :

![Untitled](https://user-images.githubusercontent.com/5485902/75013251-86af2000-548c-11ea-82a1-c2d3c5b8003a.png)

As visible from the screenshot - apart from the original issue of the visible line on the bottom, there is also a pixel difference on top, between the active tab and the hovered tab.

**Comment by mallowigi** [comment]
I'm confused, I have this: 

![image](https://user-images.githubusercontent.com/5015756/75068827-9f551f80-54f8-11ea-953a-888f6550fec0.png)

**Comment by mallowigi** [comment]
In any case, this is probably the result of fixing this bug: https://github.com/ChrisRM/material-theme-jetbrains/issues/1471

Reverting to the old behavior would reopen the said issue, so I decided to leave things like that rather than overwork on such a small issue.

**Comment by lllopo** [comment]
@mallowigi Well .. it is up to you, but I think there's something very wrong there. Too many issues at once - this weird bottom ... I don't know what it is ... either border or offset. The misalignment of the active and inactive tabs. And then there also this thing with the active tab highlight - I've set it to 1, but as you can see from the screenshot - it is actually 2px thick.

What pops in my mind - could this all be coming from the fact, that I run my desktop in 125% scaling ? There is no blurring or something, so I didn't pay attention to that, but still ...

**Comment by mallowigi** [comment]
Hmmm you have a point, I always skip the tests with scales as I don’t have an external monitor with scaling.

Can you test without the scale and see if the issue is still there ?

**Comment by lllopo** [comment]
Just did. Unfortunately it is not that. Issue still there, also the highlight still 2px wide while set to 1px in settings. I'm running 2020 EAP, but it was the same with the latest production 2019 too ... for sure.

**Comment by mallowigi** [comment]
Can reproduce.
