### ISSUE TITLE
Window is not displayed

### ISSUE THREAD

**Issue by yhan219** [ChrisRM/material-theme-jetbrains#1475]
### Summary

 On the Mac system, when the current item is full-screen, and then open other items, the window is not displayed, you need to reduce the window to display.

### Expected behavior

  Window display is normal

### Actual behavior
  Window is not displayed

### Steps to reproduce (if needed)
There are two ways to reproduce
- First：
  - 1. Current project full screen
  - 2. `File---Open recent` and just pick one

- Second:
  - 1 Just choose a file
  - 2 Right click,`Local history ----- Show history`

![gif](https://raw.githubusercontent.com/yhan219/image/master/Dec-17-2019-09-51-29.gif)

You can also add Screenshots for a better understanding.
```
IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019
Licensed to GUO BIN
Subscription is active until April 5, 2020
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, Gradle View, GrepConsole, Lombook Plugin, MavenRunHelper, MyBatisLogPlugin, cn.yiiguxing.plugin.translate, com.alibaba.p3c.smartfox, com.ccnode.codegenerator.MyBatisCodeHelperPro, com.chrisrm.idea.MaterialThemeUI, com.vladsch.idea.multimarkdown, com.zhaow.restful.toolkit, de.endrullis.idea.postfixtemplates, io.github.biezhi.plugins.gitmoji, izhangzhihao.rainbow.brackets, mobi.hsz.idea.gitignore, net.vektah.codeglance, org.mapstruct.intellij, uk.co.ben-gibson.remote.repository.mapper, zielu.gittoolbox
```

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by Gaulomatic** [comment]
Having a similar problem - only with the whole app window not coming to life after loading a project.

**Comment by mallowigi** [comment]
Caused by the "Themed title bar" option. Please disable this option and restart.

I'll be removing this feature from now on.
