### ISSUE TITLE
Feature request: switch between Dark/Light theme with an icon

### ISSUE THREAD

**Issue by IgorErmakov** [ChrisRM/material-theme-jetbrains#1476]
I often do a switch between dark/light theme (atom one light & material darker) depending on the time of the day. Every time I click on the icon in the bottom bar and then select the theme manually. Would it be possible to switch it faster in few clicks (maybe show "last used" themes on  the icon click). Or something similar. 
Thank you very much, love your plugin.

**Comment by mallowigi** [comment]
I'm working on such a feature already. Closing this. Thanks
