### ISSUE TITLE
Positive Issue: Companion colour scheme.

### ISSUE THREAD

**Issue by daylerees** [ChrisRM/material-theme-jetbrains#148]
Hi Chris,

Thanks very much for the UI theme! It's certainly fixed PHPStorm for me. I'm the author of the `daylerees/colour-schemes` package which contains `Peacock`, a colour scheme used by hundreds of thousands of developers.

Out of respect of your fantastic UI theme, I've created a variant of Peacock that is optimized for your UI. You'll find it here:

https://github.com/daylerees/material-peacock

I'd love it if you'd link to it in the readme. I've linked back here, naturally. :)

Thank you!

**Comment by ChrisRM** [comment]
Looks fantastic, @daylerees :-) I'll be launching a new plugin enabling you to change the colors/styles of the entire UI soon. Should make your theme even more awesome :-)

**Comment by talios** [comment]
On 25 Jan 2016, at 2:38, Dayle Rees wrote:

> Out of respect of your fantastic UI theme, I've created a variant of Peacock that is optimized for your UI. You'll find it here:
> [https://github.com/daylerees/material-peacock](https://github.com/daylerees/material-peacock)

Looking nice! Installed via the jar and just disabled all the extra settings you had in there ( just a few :p )

Mark


-- 
Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by daylerees** [comment]
Haha. :) I included the icls for standalone colours too.
