### ISSUE TITLE
Use stock windows Icons for window controls if available

### ISSUE THREAD

**Issue by J-Cake** [ChrisRM/material-theme-jetbrains#1480]
Windows 10 has a default icon library called `Segoe MDL2 Assets` that comes in a truetype Font format. These contain icons for the classic window controls that can be seen in native windows applications such as the file explorer and office programs and in fact IntelliJ without the Material UI plugin installed. I would recommend attempting to use these icons before using the customised ones for consistency and aesthetic reasons. If you disagree, please at least add an option to use native icons for the window controls.

### Summary
Use Windows' standard icon pack for window controls if possible.
...

### Expected behaviour
The native Window control icons to be used instead of custom ones.
The window controls use icons that are more accustomed to windows versions other than 10, specifically, windows 8.1. 
...

### Actual behavior
Custom icons used
...

### Steps to reproduce (if needed)
None

![non-native icons](https://user-images.githubusercontent.com/29561775/71144212-5f13bf80-2271-11ea-90bd-582462dc0e56.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* **OS** Windows 10
* **IntelliJ Version** Webstorm (really, any) WebStorm 2019.3.1, Build #WS-193.5662.54, built on December 18, 2019
* **Plugin Version** 4.11.4
* **Plugin Config** 
``` 
<project version="4">
  <component name="JsBuildToolGruntFileManager" detection-done="true" sorting="DEFINITION_ORDER" />
  <component name="JsBuildToolPackageJson" detection-done="true" sorting="DEFINITION_ORDER" />
  <component name="JsGulpfileManager">
    <detection-done>true</detection-done>
    <sorting>DEFINITION_ORDER</sorting>
  </component>
  <component name="VcsLogIndexCollector">
    <option name="indexTime" value="2085" />
  </component>
  <component name="YarnPnpManager">
    <pnp-files />
  </component>
</project>
```

**Comment by mallowigi** [comment]
think i fixed it, it will be available next release.

**Comment by J-Cake** [comment]
@mallowigi Awesome. Please let me know when the next release is available. Thanks

**Comment by J-Cake** [comment]
@mallowigi YES YES YES!! Thanks so much!
