### ISSUE TITLE
Arrow styles cannot be set in the personalization project view.

### ISSUE THREAD

**Issue by github-halen** [ChrisRM/material-theme-jetbrains#1483]
Summary
        Arrow styles cannot be set in the personalization project view.

Environment

	IntelliJ IDEA 2019.3 (Ultimate Edition)
	Build #IU-193.5233.102, built on November 28, 2019
	Subscription is active until April 5, 2020
	Runtime version: 1.8.0_222-release-1626-b3 amd64
	VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
	Windows 10 10.0
	GC: ParNew, ConcurrentMarkSweep
	Memory: 976M
	Cores: 8
	Registry: ide.balloon.shadow.size=0
	Non-Bundled Plugins: FindBugs-IDEA, GrepConsole, Lombook Plugin, MyBatisLogPlugin, Statistic, cn.wuzhizhan.plugin.mybatis, com.chrisrm.idea.MaterialThemeUI, com.widerwille.afterglow, izhangzhihao.rainbow.brackets, net.vektah.codeglance

**Comment by mallowigi** [comment]
what?

**Comment by github-halen** [comment]
![TIM图片20200102102424](https://user-images.githubusercontent.com/34368101/71649500-47950600-2d4a-11ea-81df-9528664148d4.png)

The problem is I can't set the arrow style.

**Comment by github-halen** [comment]
![Image20200102102424](https://user-images.githubusercontent.com/34368101/71649572-ee79a200-2d4a-11ea-8845-153d227eab4f.png)

The problem is I can't set the arrow style.

**Comment by github-halen** [comment]
Setting->Appearance & Behavior->Material Theme->Project view->Arrows Style

**Comment by mallowigi** [comment]
Yopu need to click OK to see it, right ?

**Comment by github-halen** [comment]
Of course I clicked ok, but the arrow style didn't change. This setting does not take effect.

**Comment by mallowigi** [comment]
Make sure you are on the latest version then. Funny enough when I tried to reproduce the plugin crashed but after that it worked well. So please verify.

--
Elior

**Comment by github-halen** [comment]
![image](https://user-images.githubusercontent.com/34368101/71796153-5f3ef800-3084-11ea-8db7-9b8ca0c68091.png)

**Comment by github-halen** [comment]
Find out why i can't set the arrow style. The cause of this problem is a conflict with another plug-in called afterglow theme.
