### ISSUE TITLE
Blindly white startup screen 

### ISSUE THREAD

**Issue by S-B99** [ChrisRM/material-theme-jetbrains#1484]
### Summary
When launching the startup screen doesn't match my theme

### Expected behavior
It does match my theme

### Actual behavior
It doesn't match my theme, is instead pure white.

### Steps to reproduce (if needed)

1. Open Intellij

![On Open](https://user-images.githubusercontent.com/17222512/71388027-9ad9bc80-25c4-11ea-96c3-66ad9d383f4f.png)
![Opened](https://user-images.githubusercontent.com/17222512/71387995-7978d080-25c4-11ea-973a-18b31ccb2f0d.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* KDE Neon 5.17
* Intellij Idea 
![Screenshot_20191223_204327](https://user-images.githubusercontent.com/17222512/71388090-e12f1b80-25c4-11ea-9810-cdfbcea79b24.png)
* 1.1
* https://pastebin.com/raw/EXqPVXZX
* Discord Presence
* 1.1

**Comment by mallowigi** [comment]
Please update to 2019.3. I’m not working on older versions.
