### ISSUE TITLE
"Solved"  file icon, question cant seem to find a answer to   

### ISSUE THREAD

**Issue by error13** [ChrisRM/material-theme-jetbrains#1485]
https://drive.google.com/file/d/1LG4eFHH4-OC_OBYFhBZzMmqjrTpWJXUV/view?usp=sharing
what is the beaker icon in the file tab telling me its always the same python icon tried googling and pycharm docs cant figure out why its different
solved:
            beaker = Test, Python
file name includes the word Test and is a python file

PyCharm 2019.3.1 (Community Edition)
Build #PC-193.5662.61, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.8.0-53-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, com.chrisrm.idea.MaterialThemeUI, com.ludditelabs.autodocintellij.plugin

**Comment by mallowigi** [comment]
What?
