### ISSUE TITLE
After update idea to 2019.3.1, themed titlebar option can't click

### ISSUE THREAD

**Issue by 404cn** [ChrisRM/material-theme-jetbrains#1486]
<img width="661" alt="Screen Shot 2019-12-25 at 5 43 08 PM" src="https://user-images.githubusercontent.com/24653356/71442010-f92aaa80-273e-11ea-86ac-c8f2fca66f21.png">

### Environment

* intellid idea 2019.3.1

* os: macos 10.15.2

* plugin version: 4.11.4

**Comment by jonlimx** [comment]
I think it's the theme disabled "Themed Title Bar" not idea. Then I got the ugly IDE, I don't like it.

**Comment by mallowigi** [comment]
This is because this option was randomly causing issues with windows becoming blank, I decided to remove the option enabling it. You can still enable it manually by changing the config file by adding 

`  <option name="darkTitleBar" value="false" />`

**Comment by mallowigi** [comment]
I mean true

**Comment by 404cn** [comment]
> I mean true

yes, it worked, thanks very much :)
