### ISSUE TITLE
It shows 'public' as a PHP internal keyword in string 

### ISSUE THREAD

**Issue by foremtehan** [ChrisRM/material-theme-jetbrains#1487]
Windows 10, 2019.3 | Laravel

![image](https://i.imgur.com/eFA4p29.png)

Dont know it related to this theme but i posted in jetbrain website too https://youtrack.jetbrains.com/issue/WI-50486

**Comment by maidzen** [comment]
this issue happens with class reserved keywords get used string context
public, protected, private, function, static 

To reproduce go to any php file and add 
`echo "private";`

pls fix

**Comment by mallowigi** [comment]
don't know how to fix, sorry.
