### ISSUE TITLE
Unable to open files with double click

### ISSUE THREAD

**Issue by singhattinder** [ChrisRM/material-theme-jetbrains#1488]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

No file is being opened in project tree with double click . Sometimes it does work. Everything is currently on the latest version. 
...

### Expected behavior
Double click to open file should work.
...

### Actual behavior
Double click to open file does not work 
...

### Steps to reproduce (if needed)

1. First step - open project tree of any project
2. Second step - click on any file to open it
3. Third step - The file does not open.

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, aws.toolkit, com.chrisrm.idea.MaterialThemeUI, org.intellij.scala, com.intellij.bigdatatools, mobi.hsz.idea.gitignore

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

I am using default theme 'Material Oceanic.'

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by Gopikrishna19** [comment]
I have the same problem. It does work but you have to double click the file name to open. Clicking on the empty space doesn't do it. I thought it was an IDE problem, since I upgraded both IDE and plugin at the same time. But if I disable the plugin the double clicking on the file "row" opens the file.

Aside from double-click-to-open-the-file part, it seems like every other mouse events are working. Like, right click, drag and drop, etc.

![Annotation 2019-12-30 075619](https://user-images.githubusercontent.com/2506698/71584941-79079a80-2ada-11ea-9fd5-5aaa05806c1f.png)

**Comment by mallowigi** [comment]
Duplicate
