### ISSUE TITLE
Breaks with PhpStorm 7.1

### ISSUE THREAD

**Issue by Levanth** [ChrisRM/material-theme-jetbrains#149]
Hi, I installed your theme and I really like the look of it but apparently it won't apply completely to PhpStorm 7, I'll attach a Screenshot, I think that this explains everything.
![phpstorm7](https://cloud.githubusercontent.com/assets/2901975/12577646/f3c70f50-c41b-11e5-9bd7-d719f5f0d858.PNG)

I use the Darcula Setting as Default.

**Comment by mallowigi** [comment]
Should be fixed in the latest release (these striped tables caused me great pain...)
