### ISSUE TITLE
Is this the current repo?

### ISSUE THREAD

**Issue by Jarvvski** [ChrisRM/material-theme-jetbrains#1490]
I've noticed after an update that we're now on `4.11.4` https://plugins.jetbrains.com/plugin/8006-material-theme-ui/versions

But this repo only goes to `4.9.2` https://github.com/ChrisRM/material-theme-jetbrains/releases

@mallowigi any news?

**Comment by mallowigi** [comment]
Yes, I've forked the project to my account so it is now private.

**Comment by Jarvvski** [comment]
What? You’ve made it private?

Why?

Honestly.. I think that’s pretty nuts. I don’t see why you would take a good project and make it private.

Clearly this should be sent out to people. You can’t just auto update the plugin which people have installed with a private version. That changes everything.

**Comment by mallowigi** [comment]
And why exactly can’t I do that? Is there anything preventing me to do so? The code I’m writing is my property so I can decide whether or not I can disclose it or not.

Nobody ever participated in the development of the project so it’s not like I am missing anything. If someone wants to collaborate, I can open up access to the private repo.

**Comment by mallowigi** [comment]
After consideration, I can understand why it's a problem, specifically for companies who use the product. I'll update the code as soon as possible until I figure out how to deal with it.

**Comment by Jarvvski** [comment]
Thanks. Please let me/others know in this thread when you've opened it back up.

This opened a real can of worms in my team at work...

Sucks that no one else is contributing, but that shouldn't stop you from wanting to keep it open source. Then others can _see_ that it's you working on it.

**Comment by mallowigi** [comment]
The reason because I want to privatize it is not because I don’t care about people but because I am planning to make the plugin a paid one. As I have worked on it alone on my free time I want to get normal retribution for it. So the first step for it is to stop publishing publicly.

But I hadn’t don’t that yet so for now this is not actual, but at some point I will have to make some changes and this would be one of them.

--
Elior

**Comment by Jarvvski** [comment]
I can understand that, fair point.

If you wanted to do that, then I'd recommend making a _new_ version of this which publishes entirely different.

For publicity, add the info about this to the changelog so that people updating in IntelliJ can see it. Change the readme here to reflect as such, how this repo will be retired etc. Link to where people can purchase the new one.

But leave this repo as it is and have whatever's running currently merged in. Let this repo die effectively, and the plugin can slowly end out. But don't try and force the many users who have it installed via the intellij marketplace suddenly be unaware that they've been switched to a private repo.

**Comment by Jarvvski** [comment]
@mallowigi any news about keeping the original as the base version?

**Comment by mallowigi** [comment]
I've restored the previous condition, meaning the repo is currently open source. I'll be discussing with JetBrains about the process of migrating to a paid plugin and what needs to be done. I am not sure when it will happen, but I'll update everyone when it will be the case.

**Comment by Jarvvski** [comment]
Thank you @mallowigi!
