### ISSUE TITLE
All grey parent pom.

### ISSUE THREAD

**Issue by fl0gic** [ChrisRM/material-theme-jetbrains#1491]
### Summary
The parent pom.xml file in my multi-module maven project is all grey despite being valid XML. This issue occurs in any Material color scheme.

#### Note:
- The grey XML only occurs in Material theme color schemes, even if Material is installed if the color scheme is set to Darcula, for example, the formatting is restored.
- As a result, uninstalling/disabling Material does not necessarily fix this problem unless you also switch your color scheme back to Darcula or another JetBrains default color scheme.

...

### Expected behavior
Correctly colored XML as in other XML files or as seen in default IntelliJ color schemes.
...

### Actual behavior
XML is entirely grey, aside from a few things at the top. Also, any child poms that reference the parent pom are grey when they reference the parent pom.

<img width="775" alt="Grey parent pom" src="https://user-images.githubusercontent.com/13630061/71648946-c301a380-2cc7-11ea-91a3-12cec9fd0b9e.png">

_All grey parent pom._

<img width="768" alt="Grey parent pom reference" src="https://user-images.githubusercontent.com/13630061/71648938-b5e4b480-2cc7-11ea-98e0-f2fde71f650b.png">

_Grey parent reference from child pom._

...

### Steps to reproduce (if needed)

1. Create a new maven project.
2. Right-click the project files side and create a new module.
3. View the pom.xml in the project base directory, and it is all grey.

### Environment

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 17, 2019
Licensed to Caden Kriese
Subscription is active until April 13, 2020
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, JProfiler, Lombook Plugin, carbon-now-sh, com.alayouni.ansiHighlight, com.almightyalpaca.intellij.plugins.discord, com.chrisrm.idea.MaterialThemeUI, com.codota.csp.intellij, com.demonwav.minecraft-dev, com.intellij.ideolog, com.ppolivka.gitlabprojects, de.thomasrosenau.diffplugin, jd-intellij, mobi.hsz.idea.gitignore, net.scrumplex.fxmlhelper, org.intellij.scala, tanvd.grazi

Plugin version: 4.11.5
Plugin config: 
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="2979ff" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="b4ceec2:16f63e4fef2:-8000" />
    <option name="version" value="4.11.5" />
  </component>
</application>
```

**Comment by Slava96** [comment]
+1

**Comment by pettersp** [comment]
+1

**Comment by juceliohv** [comment]
+1
For me happens with Monokai Theme.

**Comment by mallowigi** [comment]
Please try again with latest version (4.13)

**Comment by juceliohv** [comment]
I did not make it. I downloaded the .zip from the jetBrains website, but ide throws the error saying that the package is not compatible. I also noticed that 4.13 is not a stable package, but EAP on the jetbrains website. In that case, what do you suggest?

**Comment by fl0gic** [comment]
> I did not make it. I downloaded the .zip from the JetBrains website, but ide throws the error saying that the package is not compatible. I also noticed that 4.13 is not a stable package, but EAP on the JetBrains website. In that case, what do you suggest?

Ensure you are using the latest EAP of IntelliJ. 4.13 seems to fix the issue for me on there.

**Comment by AndreG-P** [comment]
The issue still remains!

Plugin Version: 4.13.1

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.4865.12, built on February 5, 2020
Linux 5.3.0-29-generic
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI

**Comment by mallowigi** [comment]
Please make sure to reset your color schemes

**Comment by juceliohv** [comment]
I use the community version.

**Comment by AndreG-P** [comment]
@mallowigi 
> Please make sure to reset your color schemes

How am I supposed to do that? I uninstall and reinstalled material theme plugin but it didn't help. 

I don't understand why this ticket is closed, by the way. Will this not be fixed for Intellijs 2019 edition? I'm asking since the only solution you have is to update to EAP versions.

**Comment by AndreG-P** [comment]
It turns out that it seems to be a problem with comments in the pom. I have some one-line comments `<!-- comment -->`. If I move them to other places, it occasionally activates the correct highlighting. If I change it again, it suddenly greys out everything. Very strange behavior.

**Comment by mallowigi** [comment]
I have created a full documentation website for questions like these, please use it accordingly.

**Comment by mallowigi** [comment]
I closed it because I figured that the issue was because the provided color schemes lacked an attribute. Since I fixed that issue in the latest releases, the colors should be back. However you might still be using a copy of the bundled schemes so the issue will still persist for you. That’s why I asked to reset the schemes.

Please note that this will reset your custom color scheme settings.

**Comment by AndreG-P** [comment]
Indeed, uninstall the plugin does not delete the schemes the plugin ships. I deleted them manually and installed them again. Now it works.

**Comment by scheinercc** [comment]
Thanks @mallowigi !! FYI, this e.g. also fixed greyed color values in scss files :)

**Comment by vuachom94** [comment]
> Indeed, uninstall the plugin does not delete the schemes the plugin ships. I deleted them manually and installed them again. Now it works.

Where folder i will delete for fix it?

**Comment by vuachom94** [comment]
> I have created a full documentation website for questions like these, please use it accordingly.

You can provide me a link of it

**Comment by Gurkinator** [comment]
> Indeed, uninstall the plugin does not delete the schemes the plugin ships. I deleted them manually and installed them again. Now it works.

Where did you find the files? I've been searching for quite a while now but couldn't find the safe files

**Comment by AndreG-P** [comment]
@Gurkinator @vuachom94 
Sorry, you should ping my name if you want me to see your questions.

> Where did you find the files? I've been searching for quite a while now but couldn't find the safe files

It depends on your system. Here is the official guide: [JetBrains Plugin-Directory](https://www.jetbrains.com/help/idea/tuning-the-ide.html#plugins-directory)

In linux it would be under: `~/.local/share/JetBrains/IntelliJIdea2020.1/MaterialTheme`. I don't remember if I also deleted the cache of IntelliJ. Might be useful also. See here: [Directories used by the IDE to store settings, chaches, plugins and logs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs).
`~/.config/JeBrains/IntelliJIdea2020.1/`

**Comment by Gurkinator** [comment]
That was still extremely fast, Thank you.

**Comment by ronaldsuwandi** [comment]
Hi, this issue still persist for Material Theme Deep Ocean Theme on parent pom.xml. See screenshot below

Deep Ocean
![image](https://user-images.githubusercontent.com/4120788/116014403-b5fc8680-a667-11eb-8ee5-a4a862289bc5.png)

Darker Theme (works)
![image](https://user-images.githubusercontent.com/4120788/116014415-c90f5680-a667-11eb-95d0-5791d58e3e1e.png)
