### ISSUE TITLE
why delete

### ISSUE THREAD

**Issue by hongqian** [ChrisRM/material-theme-jetbrains#1492]
- 
<img width="435" alt="snipaste_20200102_183109" src="https://user-images.githubusercontent.com/14159505/71662932-3e2d8d00-2d8e-11ea-96db-9623659a5744.png">

**Comment by mallowigi** [comment]
what?

**Comment by hongqian** [comment]
Class still has dependencies but you delete it

> what?
Class still has dependencies but you delete it
