### ISSUE TITLE
INTELLIJ IDEA IS BLANK

### ISSUE THREAD

**Issue by MarshallTaylorV** [ChrisRM/material-theme-jetbrains#1493]
Hello everyone I wish you a happy new year.
Anyway I have a little problem I activate the Title Bar which was deactivated by default but I like the Title Bar its makes IDEA young there is a solution to activate it without having a white background
![idea](https://user-images.githubusercontent.com/28553653/71704391-1102ce00-2dd2-11ea-945e-dfdc071a378a.png)

**Comment by mallowigi** [comment]
This was the reason why it was deactivated. There is no way to fix that as it depends on the underlying JRE.

A workaround users found is to resize those same blank windows to see the content.

I added a warning explaining that same issue, so I’m closing this.

**Comment by MarshallTaylorV** [comment]
Thank you I hope you will soon find a solution
