### ISSUE TITLE
Slow performance in 2019.3

### ISSUE THREAD

**Issue by gotenxds** [ChrisRM/material-theme-jetbrains#1494]
Since upgrading to 2019.3 preformance became a real issue so I opened up the activity montior and saw that the material-ui thread is taking up to 150%cpu.
After reverting back to darcula the ui thread is taking no more then 15%cpu

### Environment

WebStorm 2019.3
Build #WS-193.5233.80, built on November 25, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, cn.yiiguxing.plugin.figlet, com.atlassian.bitbucket.references, com.deadlock.scsyntax, com.google.gct.core, com.jinsihou.react.snippets, com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete, mobi.hsz.idea.gitignore
plugin version: 4.11.2

**Comment by mallowigi** [comment]
I'm using the Material Theme all the time and could not see such a spike in cpu. Can you provide the steps ?

**Comment by gotenxds** [comment]
There are really no steps as this is a clean install of webstorm + material ui I can only say that at my home computer in which I have the same setup only on windows this does not happen

**Comment by gotenxds** [comment]
I can also say that my teammates (3 more people suffer from the same issue (to a lesser extant) on their macs

**Comment by mallowigi** [comment]
Can you provide more info about your environment ? Is it in JavaScript? Java? etc

**Comment by faizan-ali** [comment]
FWIW I was about to switch off from Jetbrains until I tried uninstalling this theme. All the lag, slowdows, freezes I encountered on two different Macs and 3 different codebases vanished.

**Comment by mallowigi** [comment]
cool story bro
