### ISSUE TITLE
Nested classes in SASS show as element selectors

### ISSUE THREAD

**Issue by larsmunkholm** [ChrisRM/material-theme-jetbrains#1495]
Nested classes in SCSS (using `&`) are colored like tag names instead of like classes.

![image](https://user-images.githubusercontent.com/6906782/71881246-3f660d80-3132-11ea-9cb6-ab334566d57a.png)
`.feedback` and `&__feedback-buttons` (which will be ouputted as `.help-text__feedback-buttons`) should probably be colored the same.

### Environment

WebStorm 2019.3.1
Build #WS-193.5662.54, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1959M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: ImportCost, com.chrisrm.idea.MaterialThemeUI

**Comment by mallowigi** [comment]
Please check with the plugin off before opening an issue
