### ISSUE TITLE
Does not work with 2019.3.1

### ISSUE THREAD

**Issue by gochev** [ChrisRM/material-theme-jetbrains#1497]
Doesnt work with latest IntelliJ IDEA 2019.3.1 possibly 2019.3 as well.

![Screenshot 2020-01-10 at 16 41 26](https://user-images.githubusercontent.com/5537142/72161177-4c039380-33c8-11ea-8903-8b0930929ccb.jpg)

**Comment by mallowigi** [comment]
Please uninstall the plugin and try to reinstall it
