### ISSUE TITLE
Branch name is not visible in terminal using oh my zsh

### ISSUE THREAD

**Issue by singhattinder** [ChrisRM/material-theme-jetbrains#1499]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
When using material design branch name with oh my zsh on mac is not visible. 
...

### Expected behavior
The branch name should be visible.
...

### Actual behavior
The branch name is not visible. It is visible on other terminals but not in intelliJ's terminal.
...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Licensed to Attinderpal Singh
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, aws.toolkit, com.chrisrm.idea.MaterialThemeUI, org.intellij.scala, com.intellij.bigdatatools, mobi.hsz.idea.gitignore

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

<img width="407" alt="iTerm" src="https://user-images.githubusercontent.com/8941845/72214278-b92c3b80-3524-11ea-918b-32894187d247.png">
<img width="477" alt="IntelliJ terminal" src="https://user-images.githubusercontent.com/8941845/72214281-be898600-3524-11ea-9e41-88b853eb8c01.png">

Note that not providing any of the required info will result of your issue being closed.

**Comment by singhattinder** [comment]
1st picture is from iTerm and 2nd picture is from intelliJ Idea's terminal

**Comment by mallowigi** [comment]
Sorry I am not handling support with third party products. Besides you can change colors from the color scheme settings.
