### ISSUE TITLE
Any plans to replace all UI icons?

### ISSUE THREAD

**Issue by vbsessa** [ChrisRM/material-theme-jetbrains#150]
First of all, the theme is great!!
Unfortently, many UI icons rely on old intellij ones, not giving a concise appearence. Is there any plans to replace all remaining icons from the UI? Jetbrains guys should take a look on this...

**Comment by arcticicestudio** [comment]
You can use the [IconLoader](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/work_with_icons_and_images.html) class from the official JetBrain API to write a plugin to replace the default icons, e.g. use the [Material Design Icons](https://materialdesignicons.com/).
I don't know if newer versions like v15/v16 EAP support `.svg` icon file format, but if it should be supported you can even make use of the the pre-defined `.css` / `.scss` stylesheets.

**Comment by ChrisRM** [comment]
Replacing all the icons is time consuming, and I would like to fix the other issues before doing the rest of the icons.

**Comment by mallowigi** [comment]
IMO it would not be best to use simple glyphs, colored icons are better for me.

I'm in the process of replacing action icons with their MD equivalents, so please bear with it :)
