### ISSUE TITLE
Strange icon for 'Project' sidebar

### ISSUE THREAD

**Issue by Jamesking56** [ChrisRM/material-theme-jetbrains#1500]
### Summary

The icon showing for the 'Project' sidebar tab looks out of place compared with all other icons in the theme 'Arc Dark'.

### Expected behavior

A colourised icon matching the other icons in the theme.

### Actual behavior

A black and white icon that doesn't seem to resemble anything.

### Steps to reproduce (if needed)

1. Open PHPStorm
1. Install plugin and activate Arc Dark theme
1. See project tab on left side

Screenshot:

![image](https://user-images.githubusercontent.com/253237/72341862-43aaa180-36c3-11ea-8231-eddb9b0a094c.png)

### Environment

* OS: **Ubuntu 18.04.3 LTS**
* Product version: **PHPStorm 2019.3.1** (Build PS-193.5662.63)
* Plugin version: **4.11.5**
* `material_theme.xml`:

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="rightTreeIndent" value="6" />
    <option name="settingsSelectedTab" value="6" />
    <option name="accentColor" value="42a5f5" />
    <option name="selectedTheme" value="ARC_DARK" />
    <option name="userId" value="705c298a:163f836dc69:-7fff" />
    <option name="version" value="4.11.5" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Not gonna change it. Sorry

**Comment by Jamesking56** [comment]
Is there a reason why?

**Comment by mallowigi** [comment]
Because I like it.
