### ISSUE TITLE
Class names, function names, etc are grayed out 

### ISSUE THREAD

**Issue by reubenfirmin** [ChrisRM/material-theme-jetbrains#1501]
### Summary
Material Deep Ocean theme is overriding the class/function name colors in Editor>Kotlin colors. When I view the colors in the Editor>Kotlin UI, they blink between what they should be and what they actually render as. (See attached video.)
...

### Expected behavior
Theme should respect the Editor>Kotlin overrides.
...

### Actual behavior
Strange blinking, as shown in video.
...

### Environment

Ubuntu
2019.3.2
Material 4.11.5
[Screencast 2020-01-23 14:42:11.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4105150/Screencast.2020-01-23.14.42.11.zip)

**Comment by mallowigi** [comment]
Please try again with the latest version and tell me if it fixed that.
