### ISSUE TITLE
Add Support for IntelliJ IDEA 2020.1 EAP

### ISSUE THREAD

**Issue by alins** [ChrisRM/material-theme-jetbrains#1503]
I know this just got released, i figure there should be an issue for tracking

**Comment by Mattwmaster58** [comment]
I wonder why this was closed? If you preemptively added support for the next EAP version, you'd be able to find bugs before the new stable is released.

**Comment by alins** [comment]
not sure i follow your logic here (i'm just curious, not trying to push back or anything). support for EAP was not exactly preemptive, the EAP was out there by the time the support was added. 

the issue asked for a build with 2020.1 EAP support, build was provided...issue closed.

**Comment by Mattwmaster58** [comment]
Oversight in my part it looks like. I assumed no 2020.1 version was
released, turns out I just didn't update the plugin.
