### ISSUE TITLE
Broken color in rename dialog box for Night Owl theme

### ISSUE THREAD

**Issue by NeroMorto** [ChrisRM/material-theme-jetbrains#1509]
### Summary

Something wrong with colors in "rename" dialogue box
It is looks like similar to #566 

### Expected behavior
Readable string during editing
### Actual behavior
Unreadable string during editing
### Steps to reproduce (if needed)

1. Get something to raname in JS file
2. Shift + F6 - to call rename dialogue box
![image](https://user-images.githubusercontent.com/1481943/73259307-8d71ac80-41d8-11ea-8c6c-2d98a702c872.png)

3. Move cursor (left/right arrow key for example)
![image](https://user-images.githubusercontent.com/1481943/73259355-b6923d00-41d8-11ea-96c4-a903f5c064b0.png)
4. As you can see name is disappeared) It is can be reselected
![image](https://user-images.githubusercontent.com/1481943/73259656-4b953600-41d9-11ea-84fa-1a04ab315241.png)

### Environment
WebStorm 2020.1 EAP
Build #WS-201.3803.72, built on January 24, 2020
WebStorm EAP User
Expiration date: February 23, 2020
Runtime version: 11.0.5+9-b674.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.13-3-MANJARO
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, org.intellij.plugins.postcss, com.jinsihou.react.snippets, net.vektah.codeglance, com.suming.react.PropTypes, com.wix.eslint, org.igu.plugins.consolelog, ru.adelf.idea.dotenv

**Plugin version: 4.12 (configured only by wizard)**
**Theme: Night Owl**

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/73265518-c7917d00-41dd-11ea-89df-2f5bac189868.png)
Cannot reproduuuuuuuuuuuuucccccccccceeeeeeeeee

**Comment by NeroMorto** [comment]
@mallowigi Did you used **2020.1 EAP**?
Checked it again and problem still here. Also tried to rollback to stable and reinstall EAP again.
I'll try ti reproduce on my home machine with window, with both stable and EAP versions.

**Comment by mallowigi** [comment]
Maybe it’s a conflicting plugin. Can you please disable other plugins and test again?

**Comment by NeroMorto** [comment]
Yes i tried it - same result
Tested on another machine with the same env as my - no problem, everything works fine (difference - there was no Material plugin installed before).
Tried to reinstal Material plugin - no result
Tried to remove ~/.config/JetBrains/WebStorm2020.1/material_theme.xml - no result (and yes they are was equal)
Tried to create new WebStorm config - it is worked, but there only some difference in~/.config/JetBrains/WebStorm2020.1/colors/_@user_Night Owl _Material_.icls
And most of them around brackets settings.

No idea what is can be wrong)
I have a backup of old WS config, may be I will try to find difference one more time later.
For now I think problem is solved and everything works fine with my others plugins.

Thank you
