### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by ifahrentholz** [ChrisRM/material-theme-jetbrains#151]
Hi there,
First of all - **You did a brilliant job with that theme - totally love it!**

**Question:**
I would love to contribute here - but unfortunately I've no experience in how to customize Jetbrains UI/UX. Are you aware of any good resource to learn that ?

**Comment by ChrisRM** [comment]
There are no good resources to learn from I'm afraid, but take a look at the source for this plugin and google `intellij laf`, `intellij look and feel`. Should get you going, but the IntelliJ platform doesn't have a clear API for this.
