### ISSUE TITLE
Weird highlight background colors

### ISSUE THREAD

**Issue by SilencerWeb** [ChrisRM/material-theme-jetbrains#1511]
I selected a variable name and all places where it is using were highlighted but with very weird and not really notable color
![image](https://user-images.githubusercontent.com/20713191/73590584-f5403400-4505-11ea-8a2d-ac4e10b96407.png)

### Environment
* OS (Windows, Linux, Mac): Mac
* IntelliJ Product + version (IDEA, RubyMine...): WebStorm 2019.3.1
* Plugin version: 4.11.5
* Plugin configuration (found in material_theme.xml): Couldn't find it inside app's package contents, there is no either such file or folder for this plugin inside the plugins folder
* Material Theme Plugin version: What's the difference between "Plugin version"?

**Comment by mallowigi** [comment]
This is in order to see the selected text independently of the type of token. There were cases where unused variables, which are “dimmed”, once highlighted became indiscernible. This is done to prevent such cases. 

Please note that you can change this color from the color scheme settings.

**Comment by SilencerWeb** [comment]
@mallowigi, could you tell me where exactly I can change it? I tried to find it but all I could find is where to change the color of the selected variable

**Comment by mallowigi** [comment]
It’s called identifier under caret
