### ISSUE TITLE
Feature - Material Design Off Theme

### ISSUE THREAD

**Issue by mikegonzalez2k** [ChrisRM/material-theme-jetbrains#1517]
### Summary
Add a Default Theme which preserves the original Darcula Theme.
This way if a user doesn't like the changes they can use this default Dark Theme and not have to disable the plugin.

**Comment by mallowigi** [comment]
Hey,

I'm currently working on the version 5.0 in which I'm trying to incorporate external themes into the Material UI. This way you can have Light and Darcula, but also custom themes working alongside the plugin features.

It is taking more time that I thought, so my ETA would be for the next month, hopefully
