### ISSUE TITLE
Directory icons not appearing in navbar

### ISSUE THREAD

**Issue by Benjozork** [ChrisRM/material-theme-jetbrains#1518]
### Summary

Directory icons do not appear in navbar, only the final file/method/class icon. See screenshot bellow.

### Expected behavior

Directory icons should appear before every navbar entry.

### Actual behavior

![image](https://user-images.githubusercontent.com/4503241/74296346-85098d80-4d11-11ea-8b84-b8e135621298.png)

### Environment

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.4865.12, built on February 5, 2020
IntelliJ IDEA EAP User
Expiration date: March 6, 2020
Runtime version: 11.0.6+8-b702.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.4.15-200.fc31.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, by.vkatz.decorate_mode_switcher, com.chrisrm.idea.MaterialThemeUI, com.daylerees.rainglow, org.jetbrains.plugins.hocon, com.intellij.ideolog, org.exbin.deltahex.intellij, com.jetbrains.plugins.jade, ru.adelf.idea.dotenv, io.ktor.intellij.plugin

Material Theme UI version: 4.13.1

**Comment by mallowigi** [comment]
It’s something new from 2020.1. Please check without the plugin, it should be disabled there too.
