### ISSUE TITLE
Theme constantly broken after a while with IDE open 

### ISSUE THREAD

**Issue by sergyu91ma** [ChrisRM/material-theme-jetbrains#1519]
I get this broken theme window in PHPStorm after i came to myPC after some time.
The IDE stays open in this time. (time means 12 hours or so, it stays over night) 
I have to constantly restart the IDE to make it work again. 
So frustrating. 
Also I have other editor Color Scheme than the theme and this is always changing back to theme color scheme. 

Broken theme after some time: 
![image](https://user-images.githubusercontent.com/6949205/74723892-0eeeb480-5244-11ea-880b-4aed1fed1d32.png)
![image](https://user-images.githubusercontent.com/6949205/74724310-c1267c00-5244-11ea-8e07-c65f012d8a09.png)

Custom editor color scheme
![image](https://user-images.githubusercontent.com/6949205/74724755-75280700-5245-11ea-9244-4b18d999e1d2.png)

The way that IDE is expected to look: 
![image](https://user-images.githubusercontent.com/6949205/74724806-8a049a80-5245-11ea-804b-3875ef200ee2.png)

Theme that i use i Material Darker. 

PHPStorm 2019.3.3 with sync activated. 
OS: Windows 10 1909

Thanks.

**Comment by mallowigi** [comment]
Please disable sync settings. It doesn’t work well with the plugin. If you can’t then I’ll suggest you to install the material UI lite instead.

**Comment by sergyu91ma** [comment]
Hmm, but i want to have synced settings so cannot disable. 
But can't you make it work well? 
I tried material ui lite but that one doesn't have icons and a lot of other customization settings.

**Comment by mallowigi** [comment]
Sync Settings is maintained by JetBrains, and they don't have support for third party plugins. They said they have it planned but it's not for now, as a result, you cannot sync the plugin settings leading to the sync changing the theme to Darcula even though the plugin settings are set to something else.

It just doesn't work. Either disable MTUI or Sync Settings.
