### ISSUE TITLE
Invisible buttons/elements in the VCS Commit window

### ISSUE THREAD

**Issue by Ghosty141** [ChrisRM/material-theme-jetbrains#1524]
When opening the Commit window the buttons and UI elements are not visible. They only appear after moving the mouse over them.

![grafik](https://user-images.githubusercontent.com/17564201/75099695-e1e42e00-55c4-11ea-9b60-a33ef16b7aac.png)

### Environment

PyCharm 2019.3.3 (Community Edition)
Build #PC-193.6494.30, built on February 6, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2010M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.daylerees.rainglow, com.thvardhan.gradianto, com.vermouthx.idea, mobi.hsz.idea.gitignore, org.toml.lang, org.rust.lang

Material Theme options: [material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4240055/material_theme.zip)

**Comment by mallowigi** [comment]
cant reproduce... are you sure this happens all the time ?

**Comment by Ghosty141** [comment]
@mallowigi, hi, thanks for looking into this. For me yes it does. Interestingly, only with this theme, the others work correctly, like you can see here:
![grafik](https://user-images.githubusercontent.com/17564201/75288010-be66f080-581b-11ea-9d9f-31d201aa2e2e.png)

What I also noticed, is that the window content does not change when resizing the window. It's just very weird that this happens only with this one theme.
