### ISSUE TITLE
Material Theme and Jet Brains IDE sync

### ISSUE THREAD

**Issue by khalwat** [ChrisRM/material-theme-jetbrains#1525]
### Summary

I use PhpStorm primarily on two computers, both using your amazing Material Theme (thank you -- I love it!) 

With Jet Brains IDE Sync enabled, when I use PhpStorm on one computer with the Material Oceanic, when I go to use the other computer, it will appear to be using that theme as well, but the backgrounds of the windows will be white, rather than a dark color.

Then if I re-save the theme on that computer to use the Material Oceanic dark theme, when I go to the _other_ computer that was properly using the theme, it will have white as a window background.

So every time I switch between machines, I have to resave the theme.

### Expected behavior

The theme settings should sync between computers

### Actual behavior

The settings all sync, and appear correct, but we end up with a white background for the Ocean Theme

### Steps to reproduce (if needed)

See above

### Environment

PhpStorm 2019.3.2
Build #PS-193.6015.48, built on January 22, 2020
Licensed to Ambrosia Software, Inc. / Andrew Welch
You have a perpetual fallback license for this version
Subscription is active until January 9, 2021
Runtime version: 11.0.5+10-b520.30 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.almightyalpaca.intellij.plugins.discord, com.chrisrm.idea.MaterialThemeUI, com.intellij.lang.jsgraphql, com.jetbrains.lang.ejs, com.jetbrains.plugins.yeoman, com.kalessil.phpStorm.phpInspectionsEA, com.kalessil.phpStorm.yii2inspections, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, mobi.hsz.idea.gitignore, org.intellij.plugins.postcss, org.jetbrains.plugins.node-remote-interpreter, org.jetbrains.plugins.rest

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/settings/#frequently-asked-questions
