### ISSUE TITLE
Ruby Inspection scrollbar highlighter in RubyMine doesn't show with Github Theme 

### ISSUE THREAD

**Issue by HoDuyQuang** [ChrisRM/material-theme-jetbrains#1529]
### Summary

Ruby Inspection scrollbar highlighter in RubyMine doesn't show with Github Theme 

### Expected behavior

The scroll bar is highlighted with multiple color at Ruby Inspection warning location

### Actual behavior

The scroll bar doesn't highlight anything, even for Ruby default inspection

### Steps to reproduce (if needed)

1. Change RubyMine to GitHub theme 
2. create Ruby file with these code :
```
def abc(num)
  bibi
  if num == "five"
    return 5
  end

  return 0
end
```
Both Ruby default inspection and Rubocop have warning, but scrollbar not highlight

This is Screenshot when using Github Theme
![image](https://user-images.githubusercontent.com/17638038/75307627-c3a95700-587e-11ea-8bd7-6158eb565fc8.png)

and then change to Atom One Light theme
![image](https://user-images.githubusercontent.com/17638038/75308310-bab98500-5880-11ea-8a20-3089be593088.png)

### Environment

* Ubuntu 18.04.4
* RubyMine 2020.1
* Material Theme Plugin version : 5.1.0

**Comment by mallowigi** [comment]
fixed in 5.2
