### ISSUE TITLE
Kotlin support?

### ISSUE THREAD

**Issue by radicaled** [ChrisRM/material-theme-jetbrains#153]
Looks like there's quite a few misses with the syntax themes if you're using Kotlin. Is there a color guide for this theme I can use to improve Kotlin support?

**Comment by jvtrigueros** [comment]
Also, the icons are just the generic star.

**Comment by apouche** [comment]
There's one annoying thing it's that ping bg color for class variables. I would happily submit a PR if I knew where to dig

<img width="367" alt="screen shot 2016-03-19 at 11 58 56 pm" src="https://cloud.githubusercontent.com/assets/528492/13901764/79ef6d7a-ee2e-11e5-9f84-77f8021c66b8.png">
