### ISSUE TITLE
Icons are not replaced

### ISSUE THREAD

**Issue by theArina** [ChrisRM/material-theme-jetbrains#1532]
### Summary

I've switched from WebStorm to WebStorm EAP and kept Material Theme settings for it, but now icons are default, not from the Theme.

### Expected behavior

Icons from the Material Theme
![image](https://user-images.githubusercontent.com/32187787/75544197-88508900-5a34-11ea-846d-ba000c8fbb01.png)
![image](https://user-images.githubusercontent.com/32187787/75544216-930b1e00-5a34-11ea-8396-5fc779f3a148.png)

### Actual behavior

Default WebStorm icons

![image](https://user-images.githubusercontent.com/32187787/75544099-52130980-5a34-11ea-9e03-c56e077d7d06.png) ![image](https://user-images.githubusercontent.com/32187787/75544171-766ee600-5a34-11ea-8ab6-183f91bf006b.png)

### Environment

Windows
WebStorm 201.5259.16
Material Theme 5.1.0

**Comment by mallowigi** [comment]
Yes it has been removed. Please check the change log

**Comment by morozov** [comment]
@mallowigi so what is the recommended approach to retaining the previous styling? Could you please point to the issue where it was decided to remove them?

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/icons-settings/
