### ISSUE TITLE
[Feature] Add option to permit "Extra icons" overwrite "Material Theme UI" icons

### ISSUE THREAD

**Issue by BoGnY** [ChrisRM/material-theme-jetbrains#1533]
### Summary

Is it possible to add an option to enable/disable overwriting your "Material Theme UI" icons with "Extra icons" icons?

How it works: JetBrains application load "Material Theme UI" icons but, if an icons is overwritten by an "Extra icons" icons (and new option is enabled), show "Extra icons" icons. Because now, if there are "Extra icons" icons, will be ignored 😫 

### Environment

> IntelliJ IDEA 2019.3.3 (Ultimate Edition)
> Build #IU-193.6494.35, built on February 11, 2020
> Licensed to XXXXXXXXXXXXXXXXXX
> Subscription is active until XXXXXXXXXXXXXX
> Runtime version: 11.0.5+10-b520.38 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1966M
> Cores: 4
> Registry: ide.balloon.shadow.size=0
> Non-Bundled Plugins: Dummy Text Generator, Flagiarism, GrepConsole, com.intellij.plugins.html.instantEditing, com.jetbrains.php, NEON support, String Manipulation, cn.yiiguxing.plugin.translate, com.alicannklc.laravel.snippets, com.chrisrm.idea.MaterialThemeUI, com.intellij.apacheConfig, com.intellij.ideolog, com.intellij.kubernetes, com.intellij.plugin.adernov.powershell, com.jetbrains.php.blade, com.jetbrains.plugins.ini4idea, com.jetbrains.twig, com.mallowigi.imageicon, com.mnr.java.intellij.idea.plugin.base64helper, com.ppolivka.gitlabprojects, com.smartbit8.laravelStorm.intellij, com.thanosp.phpstorm.inheritdoc, com.wakatime.intellij.plugin, de.domjos.ideaMantis, de.espend.idea.laravel, de.espend.idea.php.toolbox, de.espend.idea.php.annotation, de.netnexus.camelcaseplugin, fr.adrienbrault.idea.symfony2plugin, intellij.prettierJS, io.github.biezhi.plugins.gitmoji, io.snyk.snyk-intellij-plugin, lermitage.intellij.extra.icons, me.artspb.idea.php.latest.plugin, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, nb-mind-map-idea, org.github.otanikotani.checks-plugin, org.intellij.RegexpTester, org.intellij.plugins.postcss, org.jetbrains.plugins.node-remote-interpreter, org.jetbrains.plugins.phpstorm-remote-interpreter, org.jetbrains.plugins.slim, org.jetbrains.plugins.ruby, org.jetbrains.plugins.vagrant, org.jetbrains.plugins.vue, org.psliwa.idea.composer, ru.adelf.idea.dotenv, ru.mobiledev.plugins.uigd
>

**Comment by mallowigi** [comment]
I already unbundled the icons from the plugin in version 5.0. It’s only available for eap for now but eventually it will allow people to load icon plugins of their choice.
