### ISSUE TITLE
Release 5.0

### ISSUE THREAD

**Issue by Benjozork** [ChrisRM/material-theme-jetbrains#1534]
Hello, this is a just a question, not a bug report.

Has this project been closed-sourced ? I was wondering since the code for versions 5.0 and up does not appear on GitHub. No big deal, just wondering.

Thanks,

**Comment by mallowigi** [comment]
No but you’re right, I forgot to push it

**Comment by KiranMohan** [comment]
Hi,

Is this version available in the marketplace? 
I still have only 4.11.5 Feb 28 2020.

Thanks.

**Comment by mallowigi** [comment]
Ok, I checked and it's not that I forgot, but rather that it's on another branch, origin/newThemeAPI. The reason for that is that version 5.0 is only available for EAP, so I'm leaving master out in case I need to add hotfixes to 2019.
