### ISSUE TITLE
Grey sections in pom.xml

### ISSUE THREAD

**Issue by mnisius** [ChrisRM/material-theme-jetbrains#1538]
### Summary
Hello, 
so some sections in my pom.xml are use grey text. The pom looks normal if I deactivate the material theme. Is this a bug or a feature? Can I deactivate this somehow? I find it deeply distracting. 

### Expected behavior

No grey sections in pom.xml

### Actual behavior

Grey sections in pom.xml

### Steps to reproduce (if needed)
Open a pom.xml, wait until the indexing is done, some text gets grey
![grey-pom](https://user-images.githubusercontent.com/56688244/76848551-31c0b880-6844-11ea-9ab5-5b4421f7161a.png)

### Environment
Material UI Version: 4.11.5
Theme: Atom One Dark 

IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to someone
You have a perpetual fallback license for this version
Subscription is active until March 11, 2021
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3933M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: DBN, VisualVMLauncher, com.chrisrm.idea.MaterialThemeUI, com.intellij.plugin.adernov.powershell, org.asciidoctor.intellij.asciidoc, org.sonarlint.idea

**Comment by mallowigi** [comment]
It's been fixed in version 5.0. 

I won't issue a fix for versions 4.11, please bear until 2020.1 is released.
