### ISSUE TITLE
Add folder icon for organised unit tests

### ISSUE THREAD

**Issue by Axieum** [ChrisRM/material-theme-jetbrains#1540]
# Summary

Have a folder icon specifically for "unit" tests.

### Expected behavior

To show a unique folder icon when organising tests in the following folder structure:
![image](https://user-images.githubusercontent.com/7577851/77524267-c70e1d80-6ed2-11ea-9c1f-e9618f06221d.png)

**Comment by mallowigi** [comment]
ok but please open an issue to the atom-material-icons repo

**Comment by Axieum** [comment]
Sorry about that, I have moved the issue over to mallowigi/a-file-icon-idea#51.
