### ISSUE TITLE
In Scala imports and not operator `!` have wrong color and there's no way to change

### ISSUE THREAD

**Issue by gmyuval** [ChrisRM/material-theme-jetbrains#1542]
### Summary
In Scala imports and not operator `!` have wrong color and there's no way to change

### Expected behavior
Imports and all operators should inherit colors as required

### Actual behavior
Imports and not operator have color #212121

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
Licensed to Wix.com LTD / Yuval Moran
You have a perpetual fallback license for this version
Subscription is active until January 1, 2021
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, org.intellij.scala, com.google.idea.bazel.ijwb, com.intellij.plugins.html.instantEditing, com.mallowigi,  com.wixpress.intellij.plugin, io.protostuff.protostuff-jetbrains-plugin, wallaby.js, zielu.gittoolbox

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/78882611-f7bc8e00-7a60-11ea-931b-4e925dc9175b.png)

Cant reproduce
