### ISSUE TITLE
conflict with other plugins

### ISSUE THREAD

**Issue by shui4** [ChrisRM/material-theme-jetbrains#1543]
https://github.com/Vanco/SequencePlugin/issues/53

**Comment by shui4** [comment]
The combination of SequencePlugin and Material Theme will make it become:
![image](https://user-images.githubusercontent.com/40482524/78529532-6062fb00-7814-11ea-811d-400c519f15f2.png)
For other themes I use, it can be displayed normally:
![image](https://user-images.githubusercontent.com/40482524/78550407-9b762600-7836-11ea-8a26-38b11070b82e.png)
But I like the author ’s plugin very much and do n’t want to change to another Theme

**Comment by mallowigi** [comment]
Can you tell me how to reproduce? thanks

**Comment by shui4** [comment]
> Can you tell me how to reproduce? thanks

 download a sequencediagram plug-in, and use sequencediagram to enable the comparison between enabling material theme and not enabling material theme plug-in。
 When material theme is disabled, sequencediagram can be used normally, if enabled:
![image](https://user-images.githubusercontent.com/40482524/78566126-5d3a3000-7851-11ea-8107-0f76b74d5bc3.png)
I need to click this button sequencediagram in the picture to appear normally

**Comment by mallowigi** [comment]
I’ve downloaded sequencediagram but I don’t know how to activate it. It doesn’t show any tool window or anything that’s why I’m asking

--
Elior

**Comment by shui4** [comment]
1） select a method right click
![image](https://user-images.githubusercontent.com/40482524/78668257-f37f5c00-790c-11ea-83b5-bff8f39414c5.png)

2) select this
![image](https://user-images.githubusercontent.com/40482524/78668291-04c86880-790d-11ea-86d9-20bd07f381da.png)

3)  A dialog box pops up, select OK.

4）There was a problem at this time, it showed like this：
![image](https://user-images.githubusercontent.com/40482524/78668589-80c2b080-790d-11ea-97f7-5df602d954cf.png)

5）I disabled material-theme and used sequencediagram again
![image](https://user-images.githubusercontent.com/40482524/78668690-ae0f5e80-790d-11ea-95e2-6cc4ec7ac3ea.png)

![image](https://user-images.githubusercontent.com/40482524/78668783-d8611c00-790d-11ea-8338-782ab18b1952.png)

**Comment by shui4** [comment]
> I’ve downloaded sequencediagram but I don’t know how to activate it. It doesn’t show any tool window or anything that’s why I’m asking
> […](#)
> -- Elior
> On 6 Apr 2020, 17:02 +0300, 标准萌新 ***@***.***>, wrote: > > Can you tell me how to reproduce? thanks > download a sequencediagram plug-in, and use sequencediagram to enable the comparison between enabling material theme and not enabling material theme plug-in。 > When material theme is disabled, sequencediagram can be used normally, if enabled: > I need to click this button sequencediagram in the picture to appear normally > 点击这个按钮之后才能够出现 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

1） select a method right click
![image](https://user-images.githubusercontent.com/40482524/78668257-f37f5c00-790c-11ea-83b5-bff8f39414c5.png)

2) select this
![image](https://user-images.githubusercontent.com/40482524/78668291-04c86880-790d-11ea-86d9-20bd07f381da.png)

3)  A dialog box pops up, select OK.

4）There was a problem at this time, it showed like this：
 -> note there is nothing here
![image](https://user-images.githubusercontent.com/40482524/78668934-152d1300-790e-11ea-9fa0-151572690a65.png)


5）I disabled material-theme and used sequencediagram again
![image](https://user-images.githubusercontent.com/40482524/78668690-ae0f5e80-790d-11ea-95e2-6cc4ec7ac3ea.png)

![image](https://user-images.githubusercontent.com/40482524/78668783-d8611c00-790d-11ea-8338-782ab18b1952.png)

**Comment by mallowigi** [comment]
Well, I've checked with the lastest version (5.1) and...

![image](https://user-images.githubusercontent.com/5015756/78672859-e735d780-78e9-11ea-847a-6ea18890e433.png)

**Comment by shui4** [comment]
> Well, I've checked with the lastest version (5.1) and...
> 
> ![image](https://user-images.githubusercontent.com/5015756/78672859-e735d780-78e9-11ea-847a-6ea18890e433.png)

I reinstalled the computer IDE again, and this problem did not appear. thank you very much!
