### ISSUE TITLE
Option to disable Wizard

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [ChrisRM/material-theme-jetbrains#1544]
Actually I have my settings in a GitHub repo but I can't sync correctly because every time I override local settings, Material Theme shows the Wizard and it overrides my custom theme. Is there any way to solve this problem?

**Comment by mallowigi** [comment]
From the documentation:

Q: The wizard idea was great! But I’ve made an error and the wizard won’t show up anymore!

A: The wizard will show only once and only when you don’t have the `isWizardShown` option set to true in the config file. But you can reopen it by simply clicking on the action from the Material Theme Toolbar, in the Features menu.

Therefore, just set this property to true to prevent it from showing.
