### ISSUE TITLE
WebStorm 2020.1 Material Theme Fails

### ISSUE THREAD

**Issue by zeg-io** [ChrisRM/material-theme-jetbrains#1546]
### Summary
After upgrading to WebStorm 2020.1 Material Themes ceased to work :(

### Expected behavior

Continued workage

### Actual behavior

Non-workage

### Steps to reproduce (if needed)

1. Have Material Theme UI installed on an older version of WebStorm
2. Upgrade to WebStorm 2020.1
3. Cry

You can also add Screenshots for a better understanding.

### Environment

WebStorm 2020.1
Build #WS-201.6668.106, built on April 6, 2020
Licensed to Me
Subscription is active until December 30, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: bigger.font.in.project.view=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: Dummy Text Generator, String Manipulation, awesome.console, com.chrisrm.idea.MaterialThemeUI, com.jetbrains.php.framework, mobi.hsz.idea.gitignore, net.vektah.codeglance, BashSupport, ru.adelf.idea.dotenv, aws.toolkit, jballant.CommonJSAutoComplete, lv.midiana.misc.idea-plugins.deep-js-completion, ua.in.dej.myEmmet, com.mallowigi

**Comment by mallowigi** [comment]
Please uninstall and reinstall the plugin, it should be working
