### ISSUE TITLE
Icons in Preferences are not Visible when window is below certain height

### ISSUE THREAD

**Issue by simPod** [ChrisRM/material-theme-jetbrains#1547]
Preferences | Languages & Frameworks | PHP

When the window is below certain height, the icons at the bottom are not visible.

See following gif:

![2020-04-05 13-41-52 2020-04-05 13_43_21](https://user-images.githubusercontent.com/327717/78949803-09d41600-7acd-11ea-8924-694e34097f0f.gif)

```IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
Plugin 5.1.2```

**Comment by mallowigi** [comment]
This happens when the settings page contains a Tree/List. Because of the "Padded components" it takes much more space than expected. Which settings are we talking about ?

**Comment by simPod** [comment]
It's in this `Preferences | Languages & Frameworks | PHP` section

**Comment by mallowigi** [comment]
There's no way to fix this. If it bothers you that much, you can check the "Compact Table Cells" in the settings, this should do the trick

**Comment by simPod** [comment]
Kk thanks!
