### ISSUE TITLE
XML and Java files issues

### ISSUE THREAD

**Issue by blackat** [ChrisRM/material-theme-jetbrains#155]
Hi,
thanks a lot for the theme, it looks very great.
When I develop in JavaScript I do not have any problem, but with `Java` and `XML` there are some small issues.

I use the _Default Theme_.
#### XML

![material-xml](https://cloud.githubusercontent.com/assets/2487288/13052401/f95f17d0-d3fe-11e5-9c02-610267d49e18.JPG)
#### Java

![java](https://cloud.githubusercontent.com/assets/2487288/13053610/a92f86ee-d405-11e5-8073-6ff379f26350.JPG)

I have done a correction locally to my environment, but I do not know what are the right colors for them, in the XML I have just remove the white background for the tag because it was inherited.

Thanks a lot for your attention :wink:

**Comment by forfuns** [comment]
U need change settings in **Editor** - **Color & Fonts** - **java**,but I have some problem is the icon cant distinguish the java file between `interface` and `class`

**Comment by JimmyLincole** [comment]
confirmed in  IntelliJ IDEA 15.0.3

**Comment by mallowigi** [comment]
please install the latest release (And do not forget to reset your color schemes)
