### ISSUE TITLE
Material icons no longer showing for WebStorm 2020.1

### ISSUE THREAD

**Issue by roni-frantchi** [ChrisRM/material-theme-jetbrains#1551]
### Summary
All IDE icons seem to have the default look after upgrading to WebStorm 2020.1 .  
Have also tried uninstalling the plugin and reinstalling as well as switching themes.  

### Expected behavior
Show material UI icons.  

### Actual behavior
Default IDEA icons are shown.  

![image](https://user-images.githubusercontent.com/3658029/79069426-bd5c2680-7cd6-11ea-94a4-55c136839cb5.png)

### Environment

WebStorm 2020.1
Build #WS-201.6668.106, built on April 6, 2020
Subscription is active until December 23, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1956M
Cores: 12
Registry: debugger.valueTooltipAutoShow=false, debugger.valueTooltipAutoShowOnSelection=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, org.intellij.plugins.hcl, com.intellij.lang.jsgraphql, org.toml.lang
Material Plugin 5.1.3

**Comment by roni-frantchi** [comment]
Hey @mallowigi why was this closed?.. Did I miss something?..

**Comment by mallowigi** [comment]
Duplicate. Please check for closed issues.

**Comment by roni-frantchi** [comment]
Sorry @mallowigi , searched for WebStorm 2020 didn't search for IDEA like I should have 🤦‍♂️

**Comment by blackmonthstudio** [comment]
@roni-frantchi I have the same problem as you, you can try installing plugins on this site 
`https://plugins.jetbrains.com/plugin/10044-atom-material-icons`

**Comment by mendesbarreto** [comment]
> Duplicate. Please check for closed issues.

@mallowigi you sad the problem was duplicated, I tried to find on issues but I couldn't can you past the issue number please?

It because I have the same problem

**Comment by blocks-master** [comment]
Anyone fixed this issue?

**Comment by mehmedmaljoki** [comment]
![image](https://user-images.githubusercontent.com/30213495/185232687-4cb86d8b-9e92-4677-8039-f09b6be8b223.png)
Java Icon (and only the java icon) is not working in IntelliJ. Do you guys have some idea how to fix that?

**Comment by jawainc** [comment]
<img width="164" alt="Screenshot 2022-08-30 at 5 33 54 PM" src="https://user-images.githubusercontent.com/8276213/187437709-bc4ee3e6-84b9-4841-b923-3dda3992c407.png">

IntelliJ
Icons appear for a sec then changed to something as shown in the image

**Comment by aychernov** [comment]
> 

same problem on index.* file. I`m can resolve this like that: https://stackoverflow.com/questions/68332760/atom-material-icon-not-working-in-webstorm
