### ISSUE TITLE
DarkTitleBar set to true results in blank IDE

### ISSUE THREAD

**Issue by slifin** [ChrisRM/material-theme-jetbrains#1555]
### Summary
IDE is blank when darkTitleBar is set to true, opening files via the command palette does not work but settings windows etc do render, this appears to be new behaviour from recent upgrades

### Expected behavior
<img width="1438" alt="Screenshot 2020-04-14 at 15 33 10" src="https://user-images.githubusercontent.com/198857/79236758-499c5400-7e65-11ea-8654-07203fb5bf29.png">

This but without the weird blue bar, (this is a screenshot with darkTitleBar is false)

### Actual behavior

<img width="1440" alt="Screenshot 2020-04-14 at 15 25 42" src="https://user-images.githubusercontent.com/198857/79236393-cbd84880-7e64-11ea-9073-5dd693a7099e.png">

### Environment

* OS: MacOS
* IntelliJ Product: 
<img width="585" alt="Screenshot 2020-04-14 at 15 29 02" src="https://user-images.githubusercontent.com/198857/79236343-bcf19600-7e64-11ea-9e88-b615d67d9864.png">

* Plugin version 
<img width="423" alt="Screenshot 2020-04-14 at 15 31 10" src="https://user-images.githubusercontent.com/198857/79236569-06da7c00-7e65-11ea-9fb2-52cf5948e798.png">
* If needed a list of enabled plugins
<img width="514" alt="Screenshot 2020-04-14 at 15 32 27" src="https://user-images.githubusercontent.com/198857/79236687-325d6680-7e65-11ea-8a44-f5f9bc2e468d.png">

* Plugin configuration (found in material_theme.xml)

material_theme.xml
```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="styledDirectories" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isStyledDirectories" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="treeFontSizeEnabled" value="true" />
    <option name="tabFontSizeEnabled" value="true" />
    <option name="upperCaseButtons" value="false" />
    <option name="treeFontSize" value="15" />
    <option name="tabFontSize" value="15" />
    <option name="indicatorThickness" value="1" />
    <option name="settingsSelectedTab" value="5" />
    <option name="tabsHeight" value="24" />
    <option name="accentColor" value="ffffff" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="332b20ba:1689bce9e5a:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Hi, yes I'm aware of this bug. Please do the following: just resize your window one pixel smaller, the window should reappear.

**Comment by slifin** [comment]
@mallowigi That works, thank you
