### ISSUE TITLE
About the Project Frame Colors feature - Discussions

### ISSUE THREAD

**Issue by Alejandrom3** [ChrisRM/material-theme-jetbrains#1556]
As the name implies, with the new update of PHPStorm and Material Theme UI, now the proyects name appears in the top part of the IDE, but ita have an insane color where i dont see where to change it.

How i can do this?
![bg_issue](https://user-images.githubusercontent.com/10180045/79240715-c0225d00-7e37-11ea-8d79-f123d213d9cd.jpg)

**Comment by mallowigi** [comment]
Hmm, this color is autogenerated from the project name, so there's no way to change it at the moment. Later I'll allow finer customization but for now that's the only choice. You could try to rename your project name from the Project Tree, or disable the whole feature in the settings/action toolbar.

**Comment by mallowigi** [comment]
On the other side, maybe the problem is that it's too bright? Maybe darken up a bit would be better ?

**Comment by HollyIT** [comment]
@mallowigi - mind if I ask where you disable that bar all together? I've tried to find the settings/action toolbar, but can't locate it, even with searching.

**Comment by maxacarvalho** [comment]
@mallowigi I also would like to be able to disable that, sorry man, your work is amazing but the *Project Frame Color* is too much, I have a crazy green thing stealing my focus.

**Comment by maxacarvalho** [comment]
@HollyIT I found it here: [https://a.cl.ly/4guyYNyp](https://a.cl.ly/4guyYNyp)

**Comment by HollyIT** [comment]
@maxacarvalho - lol must have been looking at the same time. I was just coming back to say I found it. Thanks!

**Comment by mallowigi** [comment]
FYI: http://www.material-theme.com/docs/configuration/features-settings/#project-frame-colors

**Comment by Alejandrom3** [comment]
@maxacarvalho you are hero! It was way TOO distracting

**Comment by mallowigi** [comment]
I think I'll dim the colors a bit more for the next update. It's true that they stick out like a sore thumb

**Comment by HollyIT** [comment]
@mallowigi - I wonder if it wouldn't be possible to incorporate that idea into the Navigation Bar? If you've got that showing, then you already got the project name right there. That way it conserves a bit of the overall real estate when it comes to the height. That or even make it possible to adjust the height of the bar.

**Comment by mallowigi** [comment]
Adjusting the height is out of my skills, since it's Java Swing and it's pretty much war to do anything from it. I could put it in the navbar but again, the idea was to follow up https://marketplace.visualstudio.com/items?itemName=stuart.unique-window-colors 

Besides, I want something togglable, since it is not always useable, only if you have a lot of opened windows and it becomes a hassle distinguishing your opened projects. Since there is no way to have different themes per windows, a stripe is kind of a better solution. If I would incorporate within the navbar, that would require disabling both altogether.

**Comment by mallowigi** [comment]
Reopening for the sake of asking questions

**Comment by NinoFloris** [comment]
Could the status bar be a good place for it (if contrasting text color can be automatically determined)?

**Comment by mallowigi** [comment]
No unfortunately, the status bars are pretty much untouchable... though I could create a widget like the current theme widget. In any case I'll issue a hotfix that will blend it with the window by setting 25% opacity. Hope that would help.

**Comment by mallowigi** [comment]
Great, now it's dimmed and I can't differentiate my projects haha...

Alright I'll work on a color customization feature for now

**Comment by fatalist** [comment]
Any chance to remove it?

**Comment by Alejandrom3** [comment]
> Any chance to remove it?

Check @maxacarvalho answer

**Comment by mallowigi** [comment]
I'll turn off the feature for now. Don't want to close thousands of issues related. It will be opt-in. And i'll reduce the transparency.

**Comment by mallowigi** [comment]
I must say that I'm disappointed that nobody reads the changelog...

**Comment by fatalist** [comment]
> Check @maxacarvalho answer
Thanks for pointing me out to there.

**Comment by maxacarvalho** [comment]
> I must say that I'm disappointed that nobody reads the changelog...

Hi @mallowigi.
I did read the changelog, but I must say, it wasn't clear to me at first. I'm not a VSCode and have no idea about its features.
I made the connection when I first looked this issue.

But in fairness, people should also read the issue thread.

**Comment by ATXMJ** [comment]
@mallowigi not sure if this is the place for this, but I was thinking that if both the themed title bar and project frame colors were enabled, it'd be nice if the title bar was also colored with the project color. Would that be possible?

**Comment by mallowigi** [comment]
As I said in a previous thread, this could be possible but only for Mac OS and Windows, and the “themed title bar” option must be activated to work, since it removed the “real title bar”

**Comment by AridTag** [comment]
It seems that the frame color is deterministically generated based on the project name (solution name in my case using C# and Rider)

Where I work I sometimes need to open an older version of the software in another window. It of course has the same solution name but the frame color is exactly the same.

Could this take into consideration the full path perhaps? (Open to other ideas)

**Comment by mallowigi** [comment]
I'm going to implement an external plugin for this, with more settings such as per-project color and opacity, showing or hiding the project title and the height. I'll then remove this feature from this plugin.

**Comment by spencersmb** [comment]
This was an awesome idea - just need the ability to change the color! Cant wait for the next update. Cheers!

**Comment by thisisjamessmith** [comment]
I just updated the Material plugin and found that this Project Frame feature is enabled. I can't disable it as I'm using the free licence! Surely it should be the other way around? Is there any way I can disable this feature?

**Comment by mallowigi** [comment]
Please don't hijack old threads. Open an issue in the material-theme-issues repository.

In any case it shouldn't happen as even if you had it enabled forcibly it should detect that you're on the free plan and disable it, so it's a bit weird. But nonetheless you can edit the config file manually to disable it.

Please refer to the documentation for more info

**Comment by thisisjamessmith** [comment]
Thanks for the fast reply! And sorry for hijacking an old thread but it seemed broad enough in subject matter to cover this. I've been trying to find the config file(s) as per these directions: https://material-theme.com/docs/configuration/settings/#settings-file but there's nothing like that in my ~/Library/ApplicationSupport/JetBrains/.../jba_config/ directory (I'm using Settings Sync).

**Comment by thisisjamessmith** [comment]
Ah, I managed to turn it off under Tools > Material Theme > Material Theme Features > Toggle Project Frame Colors - The whole bar then disappears.
