### ISSUE TITLE
Custom Theme not being applied to the editor window

### ISSUE THREAD

**Issue by colinbarber** [ChrisRM/material-theme-jetbrains#1557]
Is there some sort of option to make the custom theme apply to the editor? It only seems to theme everything but the editor, which is useless at the moment :(

![image](https://user-images.githubusercontent.com/29033135/79244614-19dd5400-7e45-11ea-87dd-d0072c39754a.png)

**Comment by mallowigi** [comment]
Ummm... change the color scheme...

**Comment by colinbarber** [comment]
thank you, I was going crazy this morning <3
