### ISSUE TITLE
Problem with re-order of tabs

### ISSUE THREAD

**Issue by Alejandrom3** [ChrisRM/material-theme-jetbrains#1560]
I currently don't know if this is a bug of the PHPStorm or Material Theme UI update but since then I can't re-order the tabs at will. Now they are stuck in place and I can't move them in any project.

**Comment by mallowigi** [comment]
??? can you post a screenvid ?

**Comment by Alejandrom3** [comment]
Excuse the delay, i was struggling to convert the video in a gif format:

![2020-04-14 11-31-23](https://user-images.githubusercontent.com/10180045/79252355-19de5380-7e47-11ea-9e76-8d40f3fc3104.gif)

**Comment by mallowigi** [comment]
May be cliche but... works fine to me 
![b](https://user-images.githubusercontent.com/5015756/79254913-22a64800-7e8e-11ea-9ffb-3a54e90df490.gif)

**Comment by Alejandrom3** [comment]
I will have to restart and check it out

**Comment by Alejandrom3** [comment]
Restarted and now it works properly
