### ISSUE TITLE
Duplicate titlebar on pycharm 2020.1 with ubuntu

### ISSUE THREAD

**Issue by lminer** [ChrisRM/material-theme-jetbrains#1561]
There's an extra titlebar showing in ubuntu.

![Screenshot from 2020-04-14 10-28-56](https://user-images.githubusercontent.com/5126549/79255497-37a5bb80-7e3b-11ea-83e7-bbe1be7bdc1c.png)

**Comment by mallowigi** [comment]
Please check open issues before creating new ones

**Comment by lminer** [comment]
Sorry. Wasn't sure what to do since the issue on this was closed a while back so I figured it was stale.
