### ISSUE TITLE
Extra top bar appeared after MT update 5.2.1

### ISSUE THREAD

**Issue by fatalist** [ChrisRM/material-theme-jetbrains#1562]
Additional top bar appeared after last plugin last update.
See the screen below:
<img width="1169" alt="Screen Shot 2020-04-14 at 20 44 07" src="https://user-images.githubusercontent.com/313991/79256501-cc86d400-7e90-11ea-9087-4da6b7e2354f.png">

PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Licensed to paul

Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.editor.tabs.open.at.the.end=true, bigger.font.in.project.view=true, documentation.show.toolbar=true, debugger.valueTooltipAutoShowOnSelection=true, ide.tooltip.initialDelay=301, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.mallowigi, mobi.hsz.idea.gitignore, BashSupport, com.intellij.kubernetes, ru.adelf.idea.dotenv, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA

**Comment by mallowigi** [comment]
Please check open issues before creating new ones
