### ISSUE TITLE
Add null, true, false to PHP Additions

### ISSUE THREAD

**Issue by leo4all** [ChrisRM/material-theme-jetbrains#1564]
### Summary
Does is possible to add support for PHP Additions ? Primitives Type: null, true, false.

Only Java Additions have this feature, and it will be great as well to have it for PHP to distinguish those specific Keywords.

**Comment by mallowigi** [comment]
Someone already did a plugin for that:
https://plugins.jetbrains.com/plugin/13592-php-syntax-color-highlighter

I've endorsed his project, go take a look!
