### ISSUE TITLE
Unreadable test output 

### ISSUE THREAD

**Issue by dmason30** [ChrisRM/material-theme-jetbrains#1565]
### Summary

When running phpunit through the runner the test results have a very bright background? This is with the `oceanic` theme and using default colors.

![image](https://user-images.githubusercontent.com/20278756/79288179-f86c7e80-7ebd-11ea-9c7a-164be1d8a379.png)

When running directly in the console this coloration does not happen:

![image](https://user-images.githubusercontent.com/20278756/79288254-25b92c80-7ebe-11ea-825d-c295abb0c496.png)

### Environment

PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Subscription is active until July 4, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, com.alicannklc.tailwind, com.chrisrm.idea.MaterialThemeUI, com.upsolver.PreCommitHook, nl.jworks.intellij.bootstrap3, me.mbolotov.cypress, ru.adelf.idea.dotenv, de.espend.idea.laravel, ru.adelf.idea.dingo, de.beyondco.tinkerwell.tinkerwell, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.psliwa.idea.composer, com.mallowigi

**Comment by mallowigi** [comment]
I can't reproduce as I don't have PHPUnit, can you check changing the color at `Settings > Editor > Color Schemes > Console Colors > ANSI Colors > Green`?

**Comment by dmason30** [comment]
@mallowigi Great that appears to be causing the issue but it is using 'Foreground so it is strange why it is being applied as a background. 

**Before**
![image](https://user-images.githubusercontent.com/20278756/79454893-e553ce80-7fe3-11ea-8b6d-0dfb3a926283.png)

**After**
![image](https://user-images.githubusercontent.com/20278756/79454928-fc92bc00-7fe3-11ea-994d-22c0db48f256.png)

**Comment by mallowigi** [comment]
Looks like an issue with phpunit plugin

**Comment by dmason30** [comment]
It comes with PHPStorm by default doesn't appear in the plugins list so I assume it is a PHPStorm bug then. Created issue https://youtrack.jetbrains.com/issue/WI-52399
