### ISSUE TITLE
Visual Studio Code Dark Theme No Longer Exists

### ISSUE THREAD

**Issue by Zile1** [ChrisRM/material-theme-jetbrains#1566]
### Summary
After update to latest version(5.2.0) VSC Dark Theme disabled automatically and no longer exists.

### Expected behavior
Be able to select defined theme.

### Actual behavior
Theme does not exists as option.

### Environment

PhpStorm 2020.1

Build #PS-201.6668.153, built on April 13, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-91-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1456M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: zielu.gittoolbox, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, de.netnexus.camelcaseplugin, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, org.intellij.RegexpTester, BashSupport, com.dmarcotte.handlebars, com.intellij.lang.jsgraphql, ru.adelf.idea.dotenv, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, org.zalando.intellij.swagger, org.sylfra.idea.plugins.linessorter
Current Desktop: Unity

**Comment by mallowigi** [comment]
Ummm... there was never a VSC Dark Theme theme...

**Comment by Zile1** [comment]
I'm very sorry in that case. Probably I made combination using your theme and some color chemes. After PHP storm update everything just restarted. Keep going on!
