### ISSUE TITLE
[Material Theme UI 5] After the update, new default colours make text hard to read

### ISSUE THREAD

**Issue by leodamsky** [ChrisRM/material-theme-jetbrains#1567]
I see default colours of General Color Scheme have been changed and now some of them make the code unreadable:
* Errors and Warnings -> Unused symbol (#464B5D)
* Templates -> Live Template (#8BE9FD)

I use the default `Material Deep Ocean` colour scheme. Also, I have the `High Contrast` flag set for the theme. For example, here is a part of Groovy config (Groovy because IDEA treats lots of its code as unused :D):
![image](https://user-images.githubusercontent.com/23016452/79329352-516cfe80-7f20-11ea-9e36-6e379a7913cd.png)
And here is the "rename to" dialog:
![image](https://user-images.githubusercontent.com/23016452/79329418-719cbd80-7f20-11ea-8519-51febca3b1fe.png)

 Could they be changed?

**Comment by mallowigi** [comment]
I disagree for the unused symbols, it's the intended purpose, to highlight unused symbols so you can remove them. If Groovy is failing at its job, not my fault, I'd suggest to disable the inspection for the file ;)

For the live template, I'm also aware of this. I will try to add opacity to it.

**Comment by leodamsky** [comment]
It makes sense for the themes that are not contrasting. But with the `Material Deep Ocean` theme and `High Contrast` mode, it doesn't seem expected 🤔

**Comment by mallowigi** [comment]
Well, you can change it if you want, but I'd rather respect the purpose of this color for now. As for the live template, I've added opacity, hope it will help!

**Comment by leodamsky** [comment]
@mallowigi Which version of the plugin will have that opacity? I have 5.2.2 and it didn't change.
Before:
![image](https://user-images.githubusercontent.com/23016452/79430060-0c54d500-7fd1-11ea-8dc8-c926f7c34494.png)
Now:
![image](https://user-images.githubusercontent.com/23016452/79430074-11b21f80-7fd1-11ea-949e-086f7fd3714b.png)

**Comment by mallowigi** [comment]
Oh yeah sorry, I mean it will be available for next release, planned for next week.
