### ISSUE TITLE
Tab Bar Color

### ISSUE THREAD

**Issue by eclectic-coding** [ChrisRM/material-theme-jetbrains#1568]
After the last Material Theme update (v.5.2.2), in Rubymine the Tab Bar is a bright color (see screenshot). It displays properly in Webstorm. 
![Screenshot from 2020-04-15 07-34-02](https://user-images.githubusercontent.com/13651291/79333096-eefa0b00-7eeb-11ea-9f79-83b230cef068.png)

**Comment by mallowigi** [comment]
You probably activated inadvertently the "Accent Mode" feature. You can disable it via the settings.

**Comment by eclectic-coding** [comment]
Thank you that was it. There are so many settings in MT they are hard to find sometimes. Thanks for a great fast evolving product.
