### ISSUE TITLE
File colors aren't working (5.2.2, intellij 2020.1)

### ISSUE THREAD

**Issue by chadselph** [ChrisRM/material-theme-jetbrains#1570]
### Summary

My tests file in project view / tabs have no background colors. Under `Appearance & Behavior` > `File Colors`, I have the standard defaults (tests are green, non-project files are brown) but the dialog seems to be broken.

Here's a snippet of a stack trace from intellij log file when I try to add a File Color with the plugin enabled:

```
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at com.intellij.ui.tabs.ColorSelectionComponent.initDefault(ColorSelectionComponent.java:102)
        at com.intellij.ui.tabs.FileColorConfigurationEditDialog.<init>(FileColorConfigurationEditDialog.java:51)
        at com.intellij.ui.tabs.FileColorSettingsTable$ModelAdapter.addRow(FileColorSettingsTable.java:253)
        at com.intellij.ui.TableToolbarDecorator$3.run(TableToolbarDecorator.java:117)
        at com.intellij.ui.TableToolbarDecorator$3.run(TableToolbarDecorator.java:108)
        at com.intellij.ui.ToolbarDecorator$3.doAdd(ToolbarDecorator.java:453)
```
(with plugin disabled this works)
[ColorSelectionComponent.java:102](https://github.com/JetBrains/intellij-community/blob/master/platform/lang-impl/src/com/intellij/ui/tabs/ColorSelectionComponent.java#L102)

### Expected behavior

Green test files.
Here's my test files with material theme disabled:

<img width="191" alt="Screen Shot 2020-04-15 at 2 00 03 PM" src="https://user-images.githubusercontent.com/315988/79388012-7c0b8700-7f21-11ea-906a-26ae601895c1.png">

### Actual behavior

No green test files :( 

Test files with material theme enabled:

<img width="211" alt="Screen Shot 2020-04-15 at 1 58 42 PM" src="https://user-images.githubusercontent.com/315988/79387851-3949af00-7f21-11ea-82a6-1db57528c60a.png">

### Environment
```
IntelliJ IDEA 2020.1 (Community Edition)
Build #IC-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.dubreuia, org.jetbrains.kotlin, com.mallowigi, google-java-format, org.intellij.scala, com.chrisrm.idea.MaterialThemeUI, PythonCore
```

```
<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="009688" />
    <option name="userId" value="7381c247:17156c30ad6:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
This is because the prebundled "File Colors" when the Material Theme is enabled are different from the original ones. 

Go to Settings > Appearance > File Colors > Tests. I suspect you will see "Green" for Tests file, according to your screenshot. However, "Green" is not available in the plugin, instead you have other options such as "Forest". If you want to use the plugin, please use those instead. Otherwise I'm afraid you should remove the plugin.

**Comment by chadselph** [comment]
The problem was I couldn't change the colors (i.e. to Forest) because of the `NullPointerException`. IntelliJ just wouldn't respond. I never changed it to Green, I've had the issue with file colors since the first install.

Anyway, I deleted material_theme.xml, disabled, re-enabled and the File Colors settings dialog is working again, so I can't reproduce.
