### ISSUE TITLE
Nonactive tab is not colored

### ISSUE THREAD

**Issue by glolsh** [ChrisRM/material-theme-jetbrains#1571]
#1408 # Summary
Nonactive tab is not colored with corresponding color (from DB colors)

### Expected behavior
Nonactive tab should be colored with corresponding color (slightly) like it was before
![image](https://user-images.githubusercontent.com/14776737/79413936-871eef80-7fd3-11ea-8935-09af88659b59.png)
Screenshot made from Intellij 2019.3.4 with old plugin with corresponding version

### Actual behavior
Nonactive tab is not colored
![image](https://user-images.githubusercontent.com/14776737/79413939-8c7c3a00-7fd3-11ea-9c89-03abed6a1dd7.png)
Screenshot made from Intellij 2020.1 with plugin with 5.2.2 version

### Steps to reproduce (not needed but here we go)
1. Connect to two databases
2. Color each other with different colors via Right click and Color settings
3. Open console to each database.

### Environment
OS: Windows 10, Version: 1909, Build 18363.778
Product: Intellij Idea 2020.1
Plugin version: 5.2.2
Plugin configuration: [material_theme.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/4485007/material_theme.txt)
About: [about.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/4485008/about.txt)

**Comment by mallowigi** [comment]
Will be fixed in 5.3

**Comment by glolsh** [comment]
Thank you!
