### ISSUE TITLE
dotCover highlight not working

### ISSUE THREAD

**Issue by frederikstonge** [ChrisRM/material-theme-jetbrains#1572]
### Summary

In Rider, dotCover highlight for both code and gutter doesn't work.

### Expected behavior

Gutter has a different color for the unit test coverage status : covered, not covered etc.

Line background changes color if is covered or not.

### Actual behavior

Gutter is always pink

Line background turns the code gray.

### Steps to reproduce (if needed)

1. Use Atom One Dark theme
2. Run unit tests with code coverage information
3. Third step

![image](https://user-images.githubusercontent.com/5427239/79605153-692db980-80bd-11ea-9893-f177389062a8.png)
![image](https://user-images.githubusercontent.com/5427239/79605209-777bd580-80bd-11ea-8327-a3cb88f075be.png)
![image](https://user-images.githubusercontent.com/5427239/79605257-91b5b380-80bd-11ea-981c-3c9d29c9ff31.png)

### Environment

Rider 2020.1 
on Windows 10, 
plugin v5.2.2

**Comment by mallowigi** [comment]
Tested this on a Mac, got this:

<img width="1260" alt="Screen Shot 2020-04-18 at 22 03 22" src="https://user-images.githubusercontent.com/5015756/79668869-7aabba00-81c0-11ea-92eb-5f2ace72f1a6.png">

I suppose there's something wrong with your config. Are you sure you're using the bundled, non-modified color schemes?

**Comment by frederikstonge** [comment]
Hmm I can't tell, I didn't edit the config file if this is what you are asking. Is there a way to reset it?

**Comment by salmanbabri** [comment]
I am facing the same issue. If I change my theme to Jetbrains light/dark themes, colors appear correctly. However as soon as I change it back to Material Oceanic, the gutter color changes to pink.

**Comment by cheng93** [comment]
Can confirm, this was happening also before 2020.1
WIndows 10

**Comment by frederikstonge** [comment]
> Can confirm, this was happening also before 2020.1
> WIndows 10
> 
> Clearing my ics files fixed it

Could you tell me where I can delete these files?

**Comment by frederikstonge** [comment]
> Can confirm, this was happening also before 2020.1
> WIndows 10
> 
> Clearing my ics files fixed it

Thanks, clearing mine fixed it too.

%appdata%\Roaming\JetBrains\Rider2020.1\colors

**Comment by salmanbabri** [comment]
> 
> 
> Can confirm, this was happening also before 2020.1
> WIndows 10
> 
> Clearing my ics files fixed it

Thank a lot. I've been facing this time for quite some time. For me, the mentioned .icls were found at the following path:-
%appdata%\JetBrains\Rider2020.1\jba_config\colors

**Comment by BrHubbard** [comment]
Faced this issue on Mac OS after update to 2020.1.
Before update i used latest Rider EAP.
