### ISSUE TITLE
The font display is not normal, this problem occurs in many places

### ISSUE THREAD

**Issue by JeffreyBool** [ChrisRM/material-theme-jetbrains#1573]
goland 2020.1 version

install material-theme version `5.1.3` Causes font display to be abnormal，

![image](https://user-images.githubusercontent.com/24415888/79735545-07728700-832b-11ea-8964-7910091c2331.png)

![image](https://user-images.githubusercontent.com/24415888/79735678-3b4dac80-832b-11ea-9712-a8deb2feb65a.png)

![image](https://user-images.githubusercontent.com/24415888/79735741-515b6d00-832b-11ea-9d00-71a4e5834635.png)

![image](https://user-images.githubusercontent.com/24415888/79735754-57514e00-832b-11ea-9ad8-0bd25cd25256.png)

![image](https://user-images.githubusercontent.com/24415888/79735763-5c160200-832b-11ea-82cc-bf407c99797e.png)

**Comment by mallowigi** [comment]
I don't think it's related to the plugin.

**Comment by JeffreyBool** [comment]
I tried to install this topic to cause this problem. Uninstalling this topic will not cause this problem

**Comment by mallowigi** [comment]
Is it related to this? https://youtrack.jetbrains.com/issue/JBR-2264

**Comment by Windly213** [comment]
I have experienced the same problem only on Goland. Removing the material-theme-jetbrains plugin fixed my problem.
