### ISSUE TITLE
Question about Tabs

### ISSUE THREAD

**Issue by eclectic-coding** [ChrisRM/material-theme-jetbrains#1575]
### Summary
I just have a question ... I love you product. 

Is there a setting somewhere to in Title Section when you open the Terminal in the Jetbrain products? It is easy to set the editor tabs but I have not found a setting for the terminal tabs to increase the size or padding. 

![Screenshot from 2020-04-21 19-28-22](https://user-images.githubusercontent.com/13651291/79924645-488b9980-8406-11ea-8246-d349c1259d76.png)

**Comment by mallowigi** [comment]
Currently there is no support for it. Enabling it for the Editor tabs was very hard to do. If at some time JetBrains decides to provide customization to the DefaultTabs, I'll check for it.
