### ISSUE TITLE
Material Darker background color conflicts with matching variables when unused

### ISSUE THREAD

**Issue by linaori** [ChrisRM/material-theme-jetbrains#1576]
### Summary
I'm using Material Darker with contrast mode. When a variable is unused, it will receive a grey color, while Intellij will also give it a grey background because it tries to show matching variables. I have been unable to find which option causes this, perhaps this is something that can be fixed in the theme, or perhaps I can fix it myself if someone has a pointer where to look for this.

This is also the case for class properties, not just variables.

### Expected behavior
Readable variables, as shown in the screenshot where the variable is used:
![image](https://user-images.githubusercontent.com/1754678/80209188-e0b99680-8631-11ea-860f-3263c080ab9b.png)

### Actual behavior
The variable is unreadable due to conflicting colors:
![image](https://user-images.githubusercontent.com/1754678/80209206-ec0cc200-8631-11ea-83e6-8324e6725c68.png)
Both unselected
![image](https://user-images.githubusercontent.com/1754678/80209239-fb8c0b00-8631-11ea-8042-ca122ec8689e.png)

### Steps to reproduce (if needed)

1. introduce undefined variable
2. put cursor on this variable (happens you first start typing)

### Environment

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-46-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2416M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.intellij.apacheConfig, com.intellij.ideolog, com.jetbrains.php, com.jetbrains.twig, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, de.espend.idea.php.phpunit, net.king2500.plugins.PhpAdvancedAutoComplete, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.phpstorm-remote-interpreter, org.jetbrains.plugins.vagrant, fr.adrienbrault.idea.symfony2plugin, ru.adelf.idea.dotenv
Current Desktop: ubuntu:GNOME

Material plugin version: 5.3.0.2

Config files, I don't think I've changed anything here from the defaults. I'm using 2020, though since updating I have not touched this, there was no 2020 directory.
```
cat ~/.IntelliJIdea2019.3/config/options/material_custom_theme.xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="009688ff" />
    <option name="notificationsColor" value="323232ff" />
    <option name="treeSelectionColor" value="546e7a50" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="607d8bff" />
    <option name="foregroundColor" value="b0bec5ff" />
    <option name="backgroundColor" value="263238ff" />
  </component>
</application>
```
```
cat ~/.IntelliJIdea2019.3/config/options/material_theme.xml 
<application>
  <component name="MaterialThemeConfig">
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="5704604f:16a012ea6e5:-8000" />
    <option name="version" value="4.11.5" />
    <option name="tabHighlightPosition" value="Left-Right" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Yeah I noticed it too...

I'm thinking on changing this color to something else. I want to use opacity too but I'm not sure if it would fix the issue. Agreed, this would happen only for Darker since it uses shades of gray, but still. The problem is that I have no idea of what color to use for identifier not under caret.
