### ISSUE TITLE
Light themes doesn't working properly with color preview

### ISSUE THREAD

**Issue by itscorey** [ChrisRM/material-theme-jetbrains#1577]
### Summary

Hi folks, I'm currently experimenting the GitHub Theme on Android Studio 3.6.2 and Android Studio 4.0, but on Android Studio 4.0 I got some very awkward issue: when the color preview is shown, its XML attribute color change to a light color making it hard to read.

Note that this is only happening on Android Studio 4.0 and only with Light themes, Dark ones works just fine.

### Expected behavior

![image](https://user-images.githubusercontent.com/20311112/80235447-1c536100-8630-11ea-8e3b-56696d0433ad.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/20311112/80235530-342ae500-8630-11ea-9a94-7087279e414a.png)

### Steps to reproduce (if needed)

1. Define a color on XML using AS 4.0

### Environment

Android Studio 4.0 Beta 4
Build #AI-193.6911.18.40.6348893, built on March 30, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Dart, com.chrisrm.idea.MaterialThemeUI, com.intellij.lang.jsgraphql, io.flutter

**Comment by mallowigi** [comment]
Haven't checked yet, but there was a similar issue in the past... Please make sure you're using the latest color schemes. If needed, please delete the icls files directly.
