### ISSUE TITLE
Random parts of IDE not being "materialized"

### ISSUE THREAD

**Issue by Seluj78** [ChrisRM/material-theme-jetbrains#1580]
### Summary

When relaunching the IDE (Pycharm, CLion or RubyMine), I don't always get the full material theme on the whole IDE

### Expected behavior

<img width="1680" alt="Screenshot 2020-04-29 at 12 04 33" src="https://user-images.githubusercontent.com/4641317/80584189-9a897c00-8a11-11ea-8867-1925872af8bb.png">

### Actual behavior

<img width="1680" alt="Screenshot 2020-04-29 at 12 03 22" src="https://user-images.githubusercontent.com/4641317/80584149-8d6c8d00-8a11-11ea-8a0b-322a228efc5e.png">

### Steps to reproduce (if needed)

1. First step: Quit the editor
2. Second step: Restart it
3. Third step: ??? (/s)

It doesn't seem that reliable, it's random...

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac): Macos 10.14.6, tested on 10.15, same problem
* IntelliJ Product + version (IDEA, RubyMine...) : Pycharm 2020.1 and RubyMine 2020.1
* Plugin version `5.3.0.2` on both

Also worth noting: I LOVE WHAT YOU DO, keep it up 🙌 ❤️

**Comment by mallowigi** [comment]
Hmmm you probably have the Sync Settings plugin installed, right?

**Comment by Seluj78** [comment]
Yes ! Could that pose a problem ?

**Comment by mallowigi** [comment]
> Q: I use two computers and while everything is fine in the first one, when I check the second one it is completely messy, some windows are empty, or I am getting Darcula even though I configured Material Oceanic…

> A: This is probably because you are using JetBrains’s Sync Settings feature. While this is a great feature when you have multiple computers, unfortunately it does not sync third party settings, and as a result settings from the plugin are not synchronized between machines. And since Themes/Look and Feels are indeed synchronized, this would cause some weird behaviors like the ones mentioned previously.

> If you need to use Sync Settings, then I’ll suggest to disable synchronizing look and feels/themes. Or use the Lite version of the plugin which should be working fine.

from the docs

**Comment by Seluj78** [comment]
Alright, I'll see what I can do about that! Thanks ! 🙌
