### ISSUE TITLE
Custom theme "load from" does not copy background across correctly for Material Deep Ocean

### ISSUE THREAD

**Issue by unikitty37** [ChrisRM/material-theme-jetbrains#1581]
### Summary

When using a custom theme based on Material Deep Ocean, the code area's background appears to have been copied from a different theme, as it is considerably lighter than if the selected theme was Material Deep Ocean.

The color can be manually edited in Preferences > Editor > Colour Scheme > General > Default Text, but if Material Theme can change it when using a built-in theme, it would really help if it could do it with custom themes as well…

### Expected behavior

![image](https://user-images.githubusercontent.com/139183/80592516-7af55200-8a17-11ea-9c53-c8caf619a264.png)

(albeit with the font **not** changed, as "Material Fonts" is disabled in Advanced Settings > Features!)

### Actual behavior

![image](https://user-images.githubusercontent.com/139183/80592415-526d5800-8a17-11ea-8538-a87db2d08439.png)

### Steps to reproduce (if needed)

1. Set the theme to "Material Deep Ocean" and observe that the code editing area has the same background colour as the sidebar.
1. Edit the custom theme and choose "Material Deep Ocean" from the "Load from…" menu.
1. Select the custom theme.

### Environment

RubyMine 2020.1.1 RC
Build #RM-201.7223.64, built on April 27, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: editor.skip.copy.and.cut.for.empty.selection=true, editor.maximize.on.double.click=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi

Material Theme plugin version is 5.3.0.2.

material_theme.xml:

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="contrastMode" value="true" />
    <option name="highContrast" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="settingsSelectedTab" value="4" />
    <option name="accentColor" value="fe6c00" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="-b90bce6:169afc58bfb:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

material_custom_theme.xml:

```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="37373dff" />
    <option name="accentColor" value="fe6c00ff" />
    <option name="notificationsColor" value="262a33ff" />
    <option name="treeSelectionColor" value="09477170" />
    <option name="highlightColor" value="393f4cff" />
    <option name="secondBorderColor" value="404552ff" />
    <option name="tableSelectedColor" value="41416aff" />
    <option name="contrastColor" value="262b33ff" />
    <option name="disabledColor" value="d3dae345" />
    <option name="secondaryBackgroundColor" value="393f4cff" />
    <option name="buttonColor" value="383c4aff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="8888ff55" />
    <option name="textColor" value="8b9eb5ff" />
    <option name="foregroundColor" value="d3dae3ff" />
    <option name="backgroundColor" value="2f343fff" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
This is not possible because Custom Themes are, by default, Custom. Therefore they are not associated with a color scheme in particular. In your case you're using a variant of Deep Ocean but you could have changed it completely so it wouldn't have any relation with Deep Ocean, so the plugin cannot magically detect a color scheme to use.
