### ISSUE TITLE
JavaScript doc comment syntax highlighting

### ISSUE THREAD

**Issue by nazrhyn** [ChrisRM/material-theme-jetbrains#1586]
## Background
One of the only things I like about VSCode more than WebStorm is that it has better syntax highlighting for doc comments. Here's the VSCode version:   
![image](https://user-images.githubusercontent.com/1672405/81221230-8d8c0000-8fb0-11ea-9d44-5f1ed325b875.png)
Here's the WebStorm version:   
![image](https://user-images.githubusercontent.com/1672405/81221297-a4325700-8fb0-11ea-9294-bc29b66dd62a.png)
VSCode seems aware of the `@directive`, the `{Type}` and the `param` being different elements.

## Observations
Interestingly, though, in WebStorm, under **Editor / Color Scheme / Language Defaults**, it seems like there are many aspects of a doc comment that WebStorm is generally aware of:   
![image](https://user-images.githubusercontent.com/1672405/81221363-ba401780-8fb0-11ea-927f-5a911a2f961b.png)
And, the example shows something a lot closer to what's in VSCode:   
![image](https://user-images.githubusercontent.com/1672405/81221822-5407c480-8fb1-11ea-9ef0-4f0fbdfa5add.png)
It's just that, for JavaScript, only two items are listed:   
![image](https://user-images.githubusercontent.com/1672405/81221404-c9bf6080-8fb0-11ea-9b94-ad879dde4331.png)
Of those two, it doesn't even seem like "markup" even works. In the JavaScript example pane, you can't click on the `<code>` tag.   
![image](https://user-images.githubusercontent.com/1672405/81221878-6da90c00-8fb1-11ea-976f-27ffa18e832c.png)

## Enhancement
The **JavaScript Additions** seem like they're extending what syntax can be highlighted, so I wondered if it's possible to add better doc comment highlighting using a similar technique?

---
Originally a post in Slack at https://material-theme-ui.slack.com/archives/CB9T8GZEF/p1588793088001500.

**Comment by mallowigi** [comment]
I'll tell you frankly, the probability I'll be developing this is pretty thin. It's not a highly requested feature and it possibly requires a better parser than the one used for the additions thing (since it's not recognizing keywords but pretty much the structure of the comments). I think you should post this request to JetBrains' YouTrack. If they did it for Java, they should be able to do it for other languages too.

**Comment by nazrhyn** [comment]
Yeah it seems odd it's not in there already, given it's in the base language stuff. I'll take a look over there and link the issue here if I set it up.

**Comment by nazrhyn** [comment]
https://youtrack.jetbrains.com/issue/WEB-45532

Issue created. We can close this over here, if you want. Thanks for the response.
