### ISSUE TITLE
VCS gutter highlights in pycharm are far brighter than in Intellij

### ISSUE THREAD

**Issue by yunti** [ChrisRM/material-theme-jetbrains#1587]
### Summary
I've been using intellij and pycharm but the vcs gutter highlights are quite different between the two and very bright and distracting in pycharm. (To the best of my knowledge I'm just using the material oceanic theme unaltered).

...

### Expected behavior
VCS changes in pycharm should not be visually distracting

### Actual behavior
It's bright orange for every change.

### Steps to reproduce (if needed)

1. Just install the plugin and use the default theme.

Intellij:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/1826271/81274049-b4494580-9047-11ea-81c9-c98a4aaa610b.png">

pycharm
<img width="392" alt="image" src="https://user-images.githubusercontent.com/1826271/81274136-ce832380-9047-11ea-903f-14ff021aad38.png">

### Environment

**Intellij**
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: June 6, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: editor.distraction.free.mode=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, String Manipulation, intellij.haskell, com.paperetto.dash, mobi.hsz.idea.gitignore, org.jetbrains.plugins.localization, org.jetbrains.plugins.rest, BashSupport, ru.adelf.idea.dotenv, izhangzhihao.rainbow.brackets, com.chrisrm.idea.MaterialThemeUI, com.intellij.plugins.html.instantEditing, com.intellij.lang.jsgraphql, reasonml, org.sylfra.idea.plugins.linessorter, org.toml.lang, org.rust.lang, org.vayafulano.relativeLineNumbers

material-theme.xml
<application>
  <component name="MaterialThemeConfig">
    <option name="contrastMode" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="416a9b" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-5faadb1e:168dc77d939:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>

material-custom-theme.xml
<application>
  <component name="MaterialThemeConfig">
    <option name="contrastMode" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="416a9b" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-5faadb1e:168dc77d939:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/1826271/81276888-882fc380-904b-11ea-8e68-40083c2b07a1.png">

**Pycharm:**
PyCharm 2020.1 (Professional Edition)
Build #PY-201.6668.115, built on April 7, 2020
Licensed to XXX
Subscription is active until December 17, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: editor.distraction.free.mode=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: AceJump, IdeaVIM, org.jetbrains.IdeaVim-EasyMotion, com.alicannklc.tailwind, com.chrisrm.idea.MaterialThemeUI, mobi.hsz.idea.gitignore, NodeJS, com.jetbrains.intellij.datalore, ru.adelf.idea.dotenv, ru.meanmail.plugin.requirements, org.toml.lang

From material_theme.xml

```
<application>
  <component name="MaterialThemeConfig">
    <option name="contrastMode" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="416a9b" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-3255c740:16d8c5ef846:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1826271/81277273-17d57200-904c-11ea-8ec6-8d52936e1825.png">

**Comment by mallowigi** [comment]
This is highly opinionated. I suggest you do the changes you want in the color scheme settings.

**Comment by yunti** [comment]
Will do thanks, I manage to resolve the difference between intellij and pycharm by resetting the defaults.   
I think I previous update to the skin updated the defaults to make these more vibrant and in intellij I seemed to be using the older defaults. Is that correct there was an update to make them more vibrant? Thanks.

**Comment by mallowigi** [comment]
It was vibrant since day one I think, since they are taken inspiration from the VSCode and Sublime Material Theme equivalents.

**Comment by yunti** [comment]
Ok maybe I did something when I transistioned from pycharm to intellij.  Thanks, sorry for the noise.
