### ISSUE TITLE
How to decide the icon when two or more options match the expression?

### ISSUE THREAD

**Issue by damonpam** [ChrisRM/material-theme-jetbrains#1588]
Hello,

I'd like to display the icons associated with `.feature` like `Cucumber feature`.
![image](https://user-images.githubusercontent.com/12949398/81587074-ce23b900-93b6-11ea-9293-96381c014d28.png)

But I realised that `Behat` has the same pattern
![image](https://user-images.githubusercontent.com/12949398/81587168-f0b5d200-93b6-11ea-88ce-c0617cf48b0e.png)

I guess Behat icon is displayed because it has more priority... how can we change that? How can we manage when two or more icons have the same pattern?

Thanks a lot and congrats for the plugin it is really useful!

**Comment by mallowigi** [comment]
There's currently no way to do so, but in any case this is the wrong behavior. There shouldn't be associations which match the same regex.

**Comment by mallowigi** [comment]
After checking I found that they should match the same extension because they are competitive frameworks. Therefore I've decided to enforce cucumber as it is more prominent. Behat will only be for `feature.php` files

**Comment by damonpam** [comment]
@mallowigi great! So, there is no PR needed from my side, right? you already took care of it... When will it be released?

Thanks a lot!

**Comment by mallowigi** [comment]
I don’t have an eta for now as I am currently working on the custom file associations and it might take a while. Stay in touch
