### ISSUE TITLE
Automating Material Theme

### ISSUE THREAD

**Issue by lemoney** [ChrisRM/material-theme-jetbrains#1589]
### Summary

Is there a way to control the theme chooser through MacOS Automator? I switch from being outside on the deck to being inside (or just daytime/night time) and I was wondering if there was a way to script material theme to change either via an automator script *or* by potentially adding support for reading what the OS's setting is and setting a light and dark mode in material theme. 

If none of this is possible that's okay too! Material is the first plugin I install and it still will be. Thanks for all the support and hard work y'all do here!!

### Expected behavior

Be able to run an automator automation from the touchbar to pick the theme I like

### Actual behavior

I don't know the write text to put into automator to do this

### Steps to reproduce (if needed)

1. be me
2. be dumb (optional I think)
3. not know what to do

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 29, 2020
Subscription is active until May 15, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 16300M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.ideolog, mobi.hsz.idea.gitignore, net.sjrx.intellij.plugins.systemdunitfiles, org.intellij.plugins.hcl, com.intellij.kubernetes, ru.adelf.idea.dotenv, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, com.chrisrm.idea.MaterialThemeUI, wu.seal.tool.jsontokotlin

**Comment by mallowigi** [comment]
I have no idea about IntelliJ tools compatibility with Automator, but if it's the light and dark mode support you're looking for, there's already a plugin that does just that, as you can see here: 
http://www.material-theme.com/docs/acknowledgements/#auto-dark-mode

**Comment by lemoney** [comment]
This is it exactly. You're the best!
