### ISSUE TITLE
[Question] How to change the color for selection in drop down on Github Theme

### ISSUE THREAD

**Issue by amadeu01** [ChrisRM/material-theme-jetbrains#1590]
I'm trying to use github theme, but I couldn't find an option to change the colour of this suggestion drop-down menu.

Do you know how to change the color? Right now, it isn't much visible.
![image](https://user-images.githubusercontent.com/11631092/81748965-27581f00-9481-11ea-926f-e467bde46d0e.png)

**Comment by mallowigi** [comment]
what version aree you using?
