### ISSUE TITLE
Android studio unexpected grey color in color.xml

### ISSUE THREAD

**Issue by kikasik** [ChrisRM/material-theme-jetbrains#1594]
### Summary

I have Android Studio 4.0 RC 1. I cannot change colors for color tag in color.xml. Changing themes doesn't help too.

### Expected behavior

Colored color.xml file

### Actual behavior

![Снимок экрана 2020-05-22 в 15 51 03](https://user-images.githubusercontent.com/26849835/82669489-35a5f800-9c44-11ea-8739-d53faac02415.png)

### Environment

Android Studio 4.0 RC 1
Build #AI-193.6911.18.40.6453388, built on May 1, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 16300M
Cores: 12
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.developerphil.adbidea

Material Theme Plugin version 4.11.5

**Comment by mallowigi** [comment]
I'm not usually testing for Android Studio, but in any case please use Canary as the RC is usually pretty much behind the JetBrains' counterparts
