### ISSUE TITLE
Support monochrome theme

### ISSUE THREAD

**Issue by mingrammer** [ChrisRM/material-theme-jetbrains#1595]
Hi.

Would you mind supporting the monochrome theme? The vscode already supports a monochrome theme: https://marketplace.visualstudio.com/items?itemName=mikehhodgson.monochrome-dark

Thank you.

**Comment by mallowigi** [comment]
Hi, I'm not planning on adding new themes for the moment, but please be aware that you can create it either as a custom theme or an external theme.

http://www.material-theme.com/docs/configuration/custom-themes/
http://www.material-theme.com/docs/development/external-themes/#tutorial
