### ISSUE TITLE
Tab color differences between git states are too subtle

### ISSUE THREAD

**Issue by BHSPitMonkey** [ChrisRM/material-theme-jetbrains#16]
I often look at my open file tabs to quickly identify the ones that have been modified (or are untracked) in git. In standard themes these are easy to tell apart, but with this theme the differences in color are very subtle and require some strain to distinguish from one another. 

Along these lines, it's also a little hard to spot the currently active tab among the inactive ones.

**Comment by ChrisRM** [comment]
I'll look into it. I hope to be able to extend the tabs to support the teal bottom border as in the sublime version.

**Comment by BHSPitMonkey** [comment]
That sounds great, thanks!

**Comment by blazeworx** [comment]
+1 I too am having trouble figuring out the active tab etc. If we could figure out how to get the border bottom on the tab like sublime that would be awesome!

**Comment by ChrisRM** [comment]
Active tab border is fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/8158ca6ec07b2e14bb9f5ec9631f3f38645325cf. Different VCS states are controlled by the colour scheme. An improved version is on its way.
