### ISSUE TITLE
Plugin miss behaving in pycharm.

### ISSUE THREAD

**Issue by Simouche** [ChrisRM/material-theme-jetbrains#1601]
### Summary
I updated to the latest version of the PyCharm IDE, then I updated the material theme plugin.

### Expected behavior
Shows beautiful IDE as is always had.

### Actual behavior
Showing a brown bar, with the project's name between the top menu bars
as shown in the picture: [here](https://imgur.com/BpVan9b)

### Steps to reproduce (if needed)
it disappears if deactivate the plugin.

You can also add Screenshots for a better understanding.

### Environment
PyCharm latest version, windows 10.

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/features-settings/#project-frame-colors
