### ISSUE TITLE
IDE update changelog is unreadable on Deep Ocean theme

### ISSUE THREAD

**Issue by hertz1** [ChrisRM/material-theme-jetbrains#1602]
### Summary
Changelog has black font color on a dark background, making the text almost impossible to read.

### Expected behavior
Font color should be lighter and the text should readable.

### Actual behavior
Font color is black and text is unreadable.

### Steps to reproduce (if needed)

1. Use the "Deep Ocean" theme 
2. Check for update
3. Click on "Update" to open the "IDE and Plugin Updates" dialog
4. Try to read the text:

![Screenshot_1](https://user-images.githubusercontent.com/9440816/84032213-5d4bce80-a96d-11ea-8daf-0029c5b097f1.png)

### Environment

**OS:** Windows 10
**IntelliJ Product + Version:** PhpStorm 2020.1.1 Build #PS-201.7223.96, built on April 30, 2020
**Plugin version:** 5.3.2.1
**Plugin configuration:** [material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4746034/material_theme.zip).

**Comment by mallowigi** [comment]
What's this changelog thing? First time I heard about it

**Comment by hertz1** [comment]
It lists what are the changes in the new version, such as bug fixes and new features.

**Comment by hertz1** [comment]
I can no longer reproduce this.
