### ISSUE TITLE
PHP syntax highlighting inconsistencies

### ISSUE THREAD

**Issue by Naxon** [ChrisRM/material-theme-jetbrains#1603]
### Summary
There are some inconsistencies with the PHP syntax highlighting. For some reason words of the same type (e.g. two booleans) are being colored differently.

### Steps to reproduce (if needed)

![image](https://user-images.githubusercontent.com/293026/84147007-52746500-aa65-11ea-9d6c-24d556f849ef.png)

### Environment

PhpStorm 2020.1.2
Build #PS-201.7846.90, built on June 3, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: zielu.gittoolbox, carbon-now-sh, com.alicannklc.tailwind, com.chrisrm.idea.MaterialThemeUI, com.godwin.json.parser, com.intellij.ideolog, com.mallowigi, mobi.hsz.idea.gitignore, net.seesharpsoft.intellij.plugins.csv, BashSupport, ru.adelf.idea.dotenv, com.alicannklc.codeigniter.snippets, com.laravel_idea.plugin, de.espend.idea.php.annotation, org.psliwa.idea.composer

Material Theme UI 5.3.2.1

**Comment by benjamw** [comment]
Confirmed on the following environment:

PhpStorm 2020.1.2
Build #PS-201.7846.90, built on June 3, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1088M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.tooltip.initialDelay=248, ide.balloon.shadow.size=0
Non-Bundled Plugins: BrowseWordAtCaret, Shifter, String Manipulation, com.perl5, com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.steve.plugins.autoscroll, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.vektah.codeglance, com.dmarcotte.handlebars, com.axeldev.php1Up, com.daveme.intellij.chocolateCakePHP, com.vexus2.cakestorm, net.king2500.plugins.PhpAdvancedAutoComplete

**Comment by ArabCoders** [comment]
confirmed as well i had a chat with phpstorm dev team about it and they said it's related to material UI

PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, net.sjrx.intellij.plugins.systemdunitfiles, mobi.hsz.idea.gitignore, NEON support, com.kalessil.phpStorm.phpInspectionsEA, de.espend.idea.php.annotation, net.king2500.plugins.PhpAdvancedAutoComplete, ru.adelf.idea.dotenv

https://twitter.com/phpstorm/status/1302966649927196672?s=20

**Comment by liamkeily** [comment]
I'm also experiencing this 

Environment
PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE, search.everywhere.configurations=false, search.everywhere.actions=false, search.everywhere.toolwindows=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.vermouthx.idea, net.seesharpsoft.intellij.plugins.csv, com.wix.eslint

**Comment by eexit** [comment]
Hello,

I had this issue for years and I thought it was a phpStorm issue: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009903899-Color-scheme-bug

Turned out, this issue is only happening with this plugin and when the option Preferences | Appearance & Behavior | Material Theme | Advanced Settings | Other Tweaks | Language Additions is turned on.

This whether or not any Material Theme is applied or not.

**Comment by mallowigi** [comment]
I managed to reproduce. What I can find is that the plugin is adding the PHP Additions as expected, but for some reason the IDE doesnt' always return the required annotation (e.g. the color from the PHP Additions). This might be happening on other languages as well.

I tried to find a way to prevent the default annotatation to show up, but could not find out. 

I need to refactor this feature anyways, so maybe at that time this will be solved out.

**Comment by mallowigi** [comment]
fixed

**Comment by benjamw** [comment]
Is there a commit that goes with this fix? Or is this now a Premium feature that has to be paid for?

**Comment by mallowigi** [comment]
As stated in the doc, the project has went closed source so it is not available in this repository. And indeed, the language additions is now a premium feature. Sorry.
