### ISSUE TITLE
Notification toasts 

### ISSUE THREAD

**Issue by slifin** [ChrisRM/material-theme-jetbrains#1604]
### Summary

Notification toasts don't align correctly with the bottom of the window

### Actual behaviour

https://youtu.be/OXrLa8FvS74

### Steps to reproduce (if needed)

Create a notification toast

### Environment
Plugin version  `5.3.2.1`
```
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: documentation.show.toolbar=true, editor.distraction.free.mode=true, ide.max.editor.tabs=1, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, by.vkatz.decorate_mode_switcher, com.chrisrm.idea.MaterialThemeUI, com.github.gtache.lsp, com.cursiveclojure.cursive, com.jpospisil.gototabs
```

```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="styledDirectories" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isStyledDirectories" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="treeFontSizeEnabled" value="true" />
    <option name="tabFontSizeEnabled" value="true" />
    <option name="upperCaseButtons" value="false" />
    <option name="treeFontSize" value="15" />
    <option name="highlightThickness" value="0" />
    <option name="indicatorThickness" value="0" />
    <option name="tabsHeight" value="10" />
    <option name="accentColor" value="ffffff" />
    <option name="selectedTheme" value="CUSTOM" />
    <option name="userId" value="332b20ba:1689bce9e5a:-8000" />
    <option name="version" value="5.2.0" />
    <option name="tabHighlightPosition" value="None" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Please open an issue for jetbrains. The plugin has no relation with the positioning.

**Comment by mallowigi** [comment]
I never encountered that, maybe it’s a Linux issue. In any case this is not something the plugin controls, we are simply changing the colors. Maybe it’s like you did, so removing the title bar might be the cause.

--
Elior

**Comment by slifin** [comment]
Am I on the right repo for the plugin that shows these settings right? 
I'm running `macOS 10.15.5`
It does things like compact status bar, font sizes, padding, colours etc

<img width="1263" alt="Screenshot 2020-06-11 at 09 51 38" src="https://user-images.githubusercontent.com/198857/84365404-4d302b00-abc9-11ea-928c-c5715221135b.png">

I did some tests disabling the custom themed title:

- Disabling
    - <img width="999" alt="Screenshot 2020-06-11 at 09 55 14" src="https://user-images.githubusercontent.com/198857/84365751-d21b4480-abc9-11ea-85e5-a4ca144a7539.png">
    - <img width="880" alt="Screenshot 2020-06-11 at 09 55 49" src="https://user-images.githubusercontent.com/198857/84365763-d6476200-abc9-11ea-95a5-cf987cb7ad6a.png">
- Re-enabling  
    - <img width="905" alt="Screenshot 2020-06-11 at 09 57 37" src="https://user-images.githubusercontent.com/198857/84365924-0f7fd200-abca-11ea-931c-607bda7b1fa1.png">

**Comment by mallowigi** [comment]
Are you

**Comment by slifin** [comment]
I'm not sure really my display settings look like this:
<img width="661" alt="Screenshot 2020-06-11 at 15 43 57" src="https://user-images.githubusercontent.com/198857/84400851-7917d480-abfa-11ea-9d82-0b03855ae132.png">
