### ISSUE TITLE
Enhancement of custom theme preferences

### ISSUE THREAD

**Issue by martipe** [ChrisRM/material-theme-jetbrains#1606]
Color picker components are stacked too tight and too far from it's label for me to tell which color I will be editing. I have to put my mouse cursor at one of the labels then slowly scan across the area to the picker.

![Screenshot 2020-06-11 at 19 11 49](https://user-images.githubusercontent.com/65338441/84418944-2c42f680-ac18-11ea-9ec9-21922705a874.png)

This could be improved, preferably with a preview of the changes or at least wit ha link to load  the settings file in the editor.

**Comment by mallowigi** [comment]
I understand. I'll add different background in between items.

**Comment by mallowigi** [comment]
done
