### ISSUE TITLE
Secondary Accent Color change is not reloaded when Intelij Restarts

### ISSUE THREAD

**Issue by jimmymain** [ChrisRM/material-theme-jetbrains#1607]
### Summary

The custom colours are not being reloaded when Intelij restarts.
...

### Expected behavior
When you restart intelij the color should be restored.

### Actual behavior
When intelij is restarted the color reverts to the chosen theme color.
...

### Steps to reproduce (if needed)
I have tested this from scratch with a new install.

1. Unzip a brand new installation of intelij
  (downloaded today 2020.1.2 with all intelij settings and temp directories removed)
2. Install Material UI, and Material Icons
3. In settings choose the material theme "Material Deep Ocean".
4. Click "click here to configure custom theme colors"
5. Change the Secondary Text Color to be lighter (Brightness 80 in my case).
6. Click Apply.
7. UI Responds it looks like you configured a custom theme, Would you like to activate it. (YES)
8. The project view immediately shows the lighter colors and it's readable.
9. Restart the IDE.

You will see the color is now the original darker color, the project view is not as readable, and I have to select the color again. The settings in the IDE show the color I selected, so the settings are remembered. They are just not applied to the project view, effectively being "lost". If I tweak the color and choose apply, the project view is restored to the selected color. So the color is set correctly, and seems to be saved, just not reapplied when intelij is started.

### Environment

IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on June 1, 2020
Licensed to Craig Main
You have a perpetual fallback license for this version
Subscription is active until May 4, 2021
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, Lombook Plugin, com.mallowigi, aws.toolkit, com.chrisrm.idea.MaterialThemeUI

Here are the colors and options files:

[colors and options.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4769618/colors.and.options.zip)

**Comment by jimmymain** [comment]
If it helps, here are all my IDE settings, that you can import using File/Manage IDE Settings/Import Settings.

[Uploading idea-settings-2.zip…]()

**Comment by mallowigi** [comment]
I can reproduce it. The issue is from the popup asking you to switch to the custom theme, it doesnt' persist the choice.

**Comment by jimmymain** [comment]
that's great, good to know it's a genuine issue and will be attended to.
i did second guess myself a few times, which is why I tried it from a clean installation.

**Comment by jimmymain** [comment]
As a note, I did also try and manually choose custom theme, but I found that all the other settings from   "Material Dark Ocean" are not copied over. By using the mechanism above I should have all the Dark Ocean settings + my small color change.

it will be nice to have it fixed.

**Comment by mallowigi** [comment]
That’s not how it is. The Material Custom Theme Settings are only for the “Custom theme”, e.g it’s another theme completely. The popup appears because users complained in the past that it wasn’t clear enough they these settings were working only upon choosing the custom theme.

If you switch to custom theme manually though, it does get persisted. The problem is when switching to the custom theme via the popup action.

**Comment by jimmymain** [comment]
I tried it again, and it does work, in Intelij.
Something is not right though, in Intelij the first time I tried it, and now in DataGrip, I am getting a strange combination of colors, **not** a customised deep ocean.

![image](https://user-images.githubusercontent.com/2555050/84585015-501a5e00-ae0b-11ea-9001-87e3c0a2be63.png)

**Comment by jimmymain** [comment]
Ok, I have figured it out, it was just not applying the Material Deep Ocean theme to the editor theme as well as the material custom theme.

It's now working if I just set all the themes correctly, thanks!
