### ISSUE TITLE
Main screen glitching when windows is moved

### ISSUE THREAD

**Issue by Golotvinov** [ChrisRM/material-theme-jetbrains#1609]
When I start PHPStorm (the main screen windows, without any project or file open) and I MOVE the window with my mouse some visual artifacts / glitches appear. Text covered, text one over the other etc (see screenshot provded).

Windows 10
Material Theme v5.3.2.1
PHP Storm v2020.1.2

![Screenshot_1](https://user-images.githubusercontent.com/39648288/84590367-20cd1680-ae36-11ea-9049-5d5019d1a069.jpg)

**Comment by smye** [comment]
Also am experiencing this with CLion 2020.1.2 and Material Theme 5.3.2.1 on Windows 10.

![image](https://user-images.githubusercontent.com/17861005/85072512-25d0f380-b1b1-11ea-95ee-b5b68e69016a.png)

**Comment by Superkooka** [comment]
+1

**Comment by mallowigi** [comment]
closing this as the new ui will replace this screen
