### ISSUE TITLE
Android Studio 1.5 Critical bug

### ISSUE THREAD

**Issue by BryanJBryce** [ChrisRM/material-theme-jetbrains#161]
I installed the plugin as shown in the read me. When I restarted Android Studio I got multiple errors and I couldn't open the settings window to disable the plugin. I'm on Mac OS X 10.11.3. I had to reinstall Android Studio. Rather than say 'unstable' in the read me, be a little more explicit and say that it could bork your installation.

**Comment by joaoevangelista** [comment]
Idk if it adds something, I tested on AS 2.0 beta 5 running on Windows and everything works normal.

Does the AS complained about something when started and crashed? Something on logs maybe?

**Comment by ChrisRM** [comment]
Could this be related to #187?
