### ISSUE TITLE
[Request] Better Step Icons when Debugging

### ISSUE THREAD

**Issue by CWSpear** [ChrisRM/material-theme-jetbrains#1610]
### Disclaimer

Ok, I realize this may not even be the correct place to put this... I realize it's the `atom-material-icons` plugin, but I couldn't find a repo, and you have a link to them, and I'm all confused... so even if this isn't the correct place to be posting this, I am hoping someone can point me to the right place!

### Summary

When debugging in IntelliJ (at least in Node), the icons for **Smart Step Into** and **Force Step Into** are _exactly_ the same and very similar to **Step Into**. But all the icons themselves are not useful enough to understand which is which (let's be honest... who _does_ know the difference of those anyway)?

### Expected behavior

The icons are self-explanatory enough that maybe I have to check the tooltips once, but then it's clear which icon is which and what they do and I don't have to constantly check the tooltips to know what the icons are supposed to do.

### Actual behavior

I have to constantly check the tooltips to know what's what.

### Steps to reproduce (if needed)

1. Create a breakpoint that is sure to get hit when debugging in step 2.
2. Debug JavaScript code in IntelliJ, e.g. a Jest test.
3. Note the Step icons (see attached screenshot. Note the very helpful red box drawing your attention to the icons in question).

![step-icons](https://user-images.githubusercontent.com/495855/84837332-b27e8480-afec-11ea-8dec-c24e968fa028.png)

### Environment
```
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
Build #IU-201.7846.76, built on May 31, 2020
Licensed to Cameron W Spear
Subscription is active until January 14, 2021
Runtime version: 11.0.7+10-b765.53 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 8083M
Cores: 16
Registry: bigger.font.in.project.view=true, ide.tooltip.initialDelay=576, ide.balloon.shadow.size=0, tslint.service.node.arguments=--max_old_space_size=4096, jest.test.tree.use.jasmine.reporter=false
Non-Bundled Plugins: String Manipulation, mobi.hsz.idea.gitignore, com.dubreuia, com.jetbrains.plugins.ini4idea, com.mallowigi, com.paperetto.dash, ideanginx9, org.jetbrains.plugins.go, Karma, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, org.jetbrains.plugins.vue, com.intellij.lang.jsgraphql, com.jetbrains.php, ru.adelf.idea.dotenv, intellij.prettierJS, io.pivotal.jasmine
```

**Material Theme Plugin version:** 5.3.2.1

Config files below:

```xml
<!-- ~/Library/Application Support/JetBrains/IntelliJIdea2020.1/options/material_custom_theme.xml -->
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="caretColor" value="ffcc00" />
    <option name="inactiveColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

```xml
<!-- ~/Library/Application Support/JetBrains/IntelliJIdea2020.1/options/material_theme.xml -->
<application>
  <component name="MaterialThemeConfig">
    <option name="highlightColorEnabled" value="true" />
    <option name="allowDataCollection" value="true" />
    <option name="isHighlightColorEnabled" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="highlightThickness" value="5" />
    <option name="accentColor" value="42a5f5" />
    <option name="highlightColor" value="ffff00" />
    <option name="selectedTheme" value="ARC_DARK" />
    <option name="userId" value="344c056e:16437fb9f83:-7fff" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I see, to be honest when I'm replacing icons I'm looking in many icon libraries to find which icon is the most suited for the purpose. But sometimes I just can't find anything useful, so I'm left out of options that to use an icon close to that, but with a different color, or with a small icon on the bottom or something.

If you have an idea for a better option, you can look into https://materialdesignicon.com, icoMoon, font-awesome, github octicons or flaticon to see if there is a free icon that better represents the concept. Of course it should be svg and monochromatic.
