### ISSUE TITLE
Tomorrow Theme

### ISSUE THREAD

**Issue by tajetaje** [ChrisRM/material-theme-jetbrains#1613]
### Summary

Add the [tomorrow](https://github.com/chriskempson/tomorrow-theme) suite of themes, the theme is very popular and with it already including a JetBrains scheme the port to Material Theme should be trivial.

**Comment by mallowigi** [comment]
I can't take care of this. While I would admit could be a great theme, new themes requires a complete management of both UI colors and the editor color schemes, not to mention wallpapers, icons in the action bar, wizard etc...

I can suggest you to write an external theme plugin, and manage it yourself.
