### ISSUE TITLE
green dot on bottom of the icon for running conf (tabs)

### ISSUE THREAD

**Issue by diablade** [ChrisRM/material-theme-jetbrains#1614]
### Summary
indicator running conf is not green dot but brown or something like that

### Expected behavior
to be green or at least to be found in parameters to change color

### Actual behavior
the indicator of running configurations are some dark color

### Steps to reproduce (if needed)

chose Night-Owl theme color
and start some conf 
the dot will be dark

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.
![greendot](https://user-images.githubusercontent.com/3831334/86477906-a4996500-bd49-11ea-881b-197a76362460.png)

It should contain:
* OS (Windows10)
* IntelliJ 2020.1
* Plugin version 5.3.2.1
* Plugin configuration 5.2.0

**Comment by mallowigi** [comment]
It's a feature, it's the accent color.
