### ISSUE TITLE
Missing Light Owl and Night Owl themes

### ISSUE THREAD

**Issue by ben-xD** [ChrisRM/material-theme-jetbrains#1615]
### Summary

I am using Android Studio, but cannot find my favorite theme, the `Light Owl`.

![Screenshot 2020-07-05 at 11 30 12](https://user-images.githubusercontent.com/24711048/86530715-f5789d00-beb2-11ea-8518-dc73d8af924f.png)

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. First step
I installed it as normal, but did not find the light owl theme. Going back to the theme wizard did not show the light theme.

### Environment

![Screenshot 2020-07-05 at 11 32 59](https://user-images.githubusercontent.com/24711048/86530747-5607da00-beb3-11ea-9021-63776984f2d7.png)

Running on macOS 10.15.5
I am using Material Theme UI 4.5.2, which is not even listed as a version on the [plugin site](https://plugins.jetbrains.com/plugin/8006-material-theme-ui)

![Screenshot 2020-07-05 at 11 35 34](https://user-images.githubusercontent.com/24711048/86530781-a97a2800-beb3-11ea-9d05-71a4647e62cf.png)

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

**Comment by mallowigi** [comment]
Your Android Studio is based off IDEA 192.X, which is 2019.2

The latest features are available from 2020.X, so unfortunately you have to wait until AS update their base API to 2020 as well.

**Comment by ben-xD** [comment]
After installing https://plugins.jetbrains.com/plugin/10936-night-owl-theme, the 2 themes were added to thed drop down list.

**Comment by mallowigi** [comment]
It's a completely separate plugin and not affiliated with Material Theme.
