### ISSUE TITLE
Material Darker changed to Darcula, and changing it back fucks up my IDE?

### ISSUE THREAD

**Issue by LoganDark** [ChrisRM/material-theme-jetbrains#1616]
I've been panicking about this for like an hour and I REALLY need help with it!!

After updating my IDE (CLion 2018.3.3) to CLion 2020.1.2, THIS happened.

Before:
![image](https://user-images.githubusercontent.com/4723091/87361538-4e82a980-c521-11ea-9ec2-1e1cc43c5d40.png)

After:
![image](https://user-images.githubusercontent.com/4723091/87361545-53dff400-c521-11ea-920b-c0b399c55395.png)

WTF?

I checked my settings for Material Theme and this is what I saw:

![image](https://user-images.githubusercontent.com/4723091/87361567-622e1000-c521-11ea-974c-8309ea1a0b4c.png)

What the heck is this? This is what it should be (2018 IDE):

![image](https://user-images.githubusercontent.com/4723091/87361591-6d813b80-c521-11ea-85d9-0ffa9a292570.png)

So I decided to try changing it. Simple, right? WRONG

Changing it causes the entire fucking IDE to change its color from blue to orange, and it absolutely ruins my syntax highlighting preferences, to the point where THIS:

![image](https://user-images.githubusercontent.com/4723091/87361641-8853b000-c521-11ea-885f-730bbeebd217.png)

Becomes THIS:

![image](https://user-images.githubusercontent.com/4723091/87361658-91448180-c521-11ea-8742-b6fca549cebc.png)

Luckily, thanks to settings sync, I can get all settings from my account and fix all this right?

![image](https://user-images.githubusercontent.com/4723091/87361816-e7192980-c521-11ea-9a25-5717fe1af6f1.png)

Well, I can revert the chaos caused by switching themes, but it's still not Material Darker.

So far the only thing I can think of is manually changing the settings XML, to change the theme back to Material Darker ***WITHOUT*** ruining my entire IDE... But now the heck do I do that??

**Comment by LoganDark** [comment]
Note: This is what my 2018 IDE looks like. It's what all my IDEs look like, from CLion to WebStorm to IDEA.

![image](https://user-images.githubusercontent.com/4723091/87362198-d87f4200-c522-11ea-81d1-6b8185e46d19.png)

See? NOT ORANGE. (And yes, I'm aware Material Darker usually is orange - I changed it myself.)

One solution to this issue would be not interpreting 2018 Material Darker as 2020 Darcula. That way I can run the sync again (account->IDE) and the theme will be proper.

Another solution to this issue would be letting me use the fricking dropdown without changing my syntax highlighting settings and accent color settings. Like, what the heck, why would changing the theme make keywords italic...

**Comment by LoganDark** [comment]
Restarting the IDE alone doesn't do this, but importing settings (even if I uncheck both Material Theme and Material Custom Theme) resets the material theme to Darcula.

This seems impossible to get out of at the moment. What is going on here?

1. Settings sync -> Darcula.
2. Settings import -> Darcula.
3. Material Darker + unrelated settings import -> Darcula.

**Comment by mallowigi** [comment]
I don't like your tone. Please remove Material Theme UI plugin and move on.

**Comment by LoganDark** [comment]
#1617
