### ISSUE TITLE
Settings sync and settings import cause the theme to be Darcula

### ISSUE THREAD

**Issue by LoganDark** [ChrisRM/material-theme-jetbrains#1617]
### Summary

When syncing settings from my JetBrains Account, Material Theme thinks the selected theme is Darcula.

### Expected behavior

In my other IDEs, I have it set to Material Darker. I've manually pushed settings to my account from my other IDEs, and then manually pulled them down to CLion 2020.1.2, but Material Theme still thinks it's Darcula.

### Actual behavior

My theme should be recognized as Material Darker, not Darcula.

### Steps to reproduce (if needed)

1. Using CLion 2018.3.3, settings sync to your JetBrains account some settings where the theme is Material Darker
2. In CLion 2020.1.2, pull those settings back to the IDE
3. All accent colors / syntax highlighting is the same as before, but Material Theme is Darcula instead of Material Darker

Here is the IDE I use to push settings to my account, 2018.3.3:

![image](https://user-images.githubusercontent.com/4723091/87454836-64dc4400-c5b9-11ea-936a-e85a569be458.png)

Here is the IDE that pulls those settings down, CLion 2020.1.2:

![image](https://user-images.githubusercontent.com/4723091/87454917-81787c00-c5b9-11ea-9565-1587d44aee9a.png)

As you can see the theme isn't Material Darker, it's Darcula.

Additionally, importing any settings exported from 2018.3.3 into 2020.1.2 (even if Material Theme and Material Custom Theme are unchecked) resets the theme to Darcula once again. Restarting the IDE without import doesn't do this.

### Environment

OS: macOS 10.14.6

2018.3.3:
![image](https://user-images.githubusercontent.com/4723091/87455024-aa007600-c5b9-11ea-93df-25ada2347fe1.png)
[material_theme.xml.2018.3.3.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4920194/material_theme.xml.2018.3.3.zip) (freshly synced to account)
Material Theme UI v3.5.0.1

2020.1.2:
![image](https://user-images.githubusercontent.com/4723091/87455174-e207b900-c5b9-11ea-81d3-70163d71706b.png)
[material_theme.xml.2020.1.2.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4920198/material_theme.xml.2020.1.2.zip) (freshly synced from account)
Material Theme UI v5.3.2.1

**Comment by mallowigi** [comment]
A bit shameless to open an already closed issue without even an apology but in any case: please make sure you're not using Sync Settings. As stated in the documentation the plugin does not sync between machines, but because the installed look and feels do, you get a messed up sync state. 

Therefore please refrain from using it, or if you can deselect synchronization of the look and feels.

**Comment by mallowigi** [comment]
Second, you should be able to select a material theme even if you get redirected to Darcula. Please make sure that the theme selected in Settings > Appearance is the selected theme as well.

**Comment by mallowigi** [comment]
Last but not least, from 2018 to 2020 there has been a lot of versions with their breaking changes. Check the change log in the website if you want to see what has changed but you can't expect something from two years ago to be exactly the same as today.

**Comment by LoganDark** [comment]
> A bit shameless to open an already closed issue without even an apology

You were disrespectful. I do not meet disrespect with respect.

> you should be able to select a material theme even if you get redirected to Darcula. Please make sure that the theme selected in Settings > Appearance is the selected theme as well.

It doesn't. The theme in the dropdown shows as Darcula; changing it causes #1618. Because of both of these issues, it's impossible for me to change the theme back because any attemps either end at Darcula or messed up settings.

I believe the bug here is Material Theme interpreting Material Darker as Darcula, as that's the only setting that's messed up. If Material Theme recognized my 2018 settings (either from sync, or from exported settings.zip) correctly, then the theme would still be Material Darker instead of Darcula.

**Comment by LoganDark** [comment]
> Last but not least, from 2018 to 2020 there has been a lot of versions with their breaking changes. Check the change log in the website if you want to see what has changed but you can't expect something from two years ago to be exactly the same as today.

Yeah, I see that. Although I believe you could fix the issue by recognizing the old setting or something, I'm not an expert on this so I don't know how possible that is. Still, it's the combination of both issues that causes me to be unable to change the theme. If one were fixed, this issue would be acceptable.

**Comment by mallowigi** [comment]
From your settings file, I can see that you are indeed on Darcula. And you stipulate that changing to Material Darker from the Dropdown and pressing OK doesn't change the theme?

**Comment by mallowigi** [comment]
What if you change to another theme and then to Darker? I remember having these issue sporadically, but never managed to reproduce it.

**Comment by LoganDark** [comment]
@mallowigi No, it does change the theme. But I'm only on Darcula because Material Theme changed it.

On 2018, I'm on Material Darker.

When syncing or importing settings, from 2018 to 2020, Material Theme thinks that *2018 Material Darker* == *2020 Darcula*.

2020 ends up on Darcula with all other 2018 settings intact.

That's why you see Darcula in the settings.zip - Because *2020 IS on Darcula*. My issue is that it *should be* on Material Darker.

**Comment by LoganDark** [comment]
> What if you change to another theme and then to Darker? I remember having these issue sporadically, but never managed to reproduce it.

Well, now you have an entire settings.zip with the issue, so you should be able to now :D 

Meanwhile, I managed to fix the issue by changing the theme and then importing my settings.zip, but *only* for color schemes.

Then to fix the icons (they all went blank after that) I installed the material atom icons thingy and everything is fixed!

**Comment by mallowigi** [comment]
I think the reason it gets switched to Darcula is because back in the day there were no "native themes", instead, the plugin was based off Darcula to work. In 2018 if you go to the installed Look And Feels you will see Darcula. Therefore, it will get propagated to 2020.

**Comment by LoganDark** [comment]
Honestly I have no idea what you mean by the installed Look And Feels, but any way to get this solved would be a big help to anyone else upgrading from an older version of the IDE to a newer one.

**Comment by mallowigi** [comment]
Settings > Appearance > Look and Feels. But there's no "smooth transition" from an old version to a recent one. In this day and age nobody expects to overdo such large heaps in versions. Not in applications, not in plugins, not anywhere. Even between CLion 2018 and 2020 there were pretty huge changes. 

In that specific case the issue is that during those two years the Material UI plugin went from a plugin that "hacked" Darcula and replaced icons, colors and UI components to a plugin using new theming APIs developed and made accessible by JetBrains after so much time. But I don't get the big deal of that since you didn't lose a lot of settings. Only the applied look and feel, I agree, and for that you can easily reapply those settings.

**Comment by LoganDark** [comment]
What about this then: Any time I make any minor change like changing the Tab Height it reverts all my color scheme changes and changes the accent color back to orange.

**Comment by mallowigi** [comment]
That's really strange. Let me try to reproduce.

**Comment by LoganDark** [comment]
[settings.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/4920432/settings.zip)

Settings with the fixed theme, for reproduction.

**Comment by mallowigi** [comment]
Let's move this conversation to Slack, it will be easier to trace.

**Comment by LoganDark** [comment]
I don't know where your Slack is.

**Comment by mallowigi** [comment]
https://join.slack.com/t/material-theme-ui/shared_invite/zt-4w78iblt-cHXYRYERpuGNbD~TqsD8rg

**Comment by justrhysism** [comment]
Yes, I too experience this, and it is very annoying. I use WebStorm at work during the day, and when I get home at night I do some private coding—and each time I do, when the settings sync the theme reverts to Darcula (both ways).

Because I use multiple machines (I also use some cloud VMs with WebStorm installed) the settings sync is too useful to _not_ use.

Is there an alternative form of syncing? I'd happily forego _plugin_ syncing (often I require more plugins professionally than I do privately, but also privately I tend to experiment more) if I could still sync the _theme_ itself.

Happy to assist any way I can—unfortunately, I haven't done Java since university so not sure I would be much use technically.

**Comment by LoganDark** [comment]
@justrhysism During my discussion with a maintainer about this (a month or so ago since that's when this issue was opened), it seems like the general stance on this is "this is just how settings sync works"... since your IDE theme is Darcula, Material Theme decides it should helpfully switch to Darcula for you, even though you already selected a different material theme.

It doesn't look like it's going to be fixed :/

**Comment by 18728759866** [comment]
![image](https://user-images.githubusercontent.com/65099914/101628441-c61a1d80-3a5a-11eb-9bd7-c98c6a74957a.png)
想问下这个蓝色框怎样去啊？

**Comment by mallowigi** [comment]
https://www.material-theme.com/docs/configuration/features-settings/#project-frame-colors

这是项目框架颜色，您可以在此处进行控制

**Comment by 18728759866** [comment]
不好意思再打扰您了，就是我现在还是不知道该如何删除这个框架颜色，希望您再指导一下，只是我看着感觉很不舒服，这个框架
![image](https://user-images.githubusercontent.com/65099914/101633487-485a1000-3a62-11eb-951d-036b87bb235c.png)

**Comment by mallowigi** [comment]
try to read the site i gave you

**Comment by nathggns** [comment]
This is still occurring with me so I don't know why this has been marked as fixed?

**Comment by Martyrer** [comment]
Happens to me as well, every time i switch pc, so annoying. This issue clearly is not fixed yet.

**Comment by mallowigi** [comment]
Please connect to the slack channel for individual issues

**Comment by Kokuyo3** [comment]
In case anyone finds this thread while looking for solutions, a work around to fix this without restarting the IDE is to: 

1. Go to `Appearance & Behavior -> Appearance` 
2. Select another theme (shouldn't need to click apply/ok)
3. Select original theme
4. Click Apply or OK to save settings

Would be nice see the issue fixed, but at least this work around isn't too much effort.

**Comment by ValorMorgan** [comment]
> In case anyone finds this thread while looking for solutions, a work around to fix this without restarting the IDE is to:
> 
>     1. Go to `Appearance & Behavior -> Appearance`
> 
>     2. Select another theme (shouldn't need to click apply/ok)
> 
>     3. Select original theme
> 
>     4. Click Apply or OK to save settings
> 
> 
> Would be nice see the issue fixed, but at least this work around isn't too much effort.

I also noticed the "Sync with OS" flag was enabled which seemed to screw with my theme.  Disabling that helped prevent the theme change.

![image](https://user-images.githubusercontent.com/7775950/217556179-c974ab58-62b1-4627-bab8-2a0b3a8bf334.png)
