### ISSUE TITLE
Android Studio 4.0 plugin error.

### ISSUE THREAD

**Issue by cett01** [ChrisRM/material-theme-jetbrains#1619]
### Summary

Updating Android Studio from 3.5 to 4.0 this plugin, lots of crashes revealed.

### Problem

I think Material Theme is not compatible with Android Studio 4.0. Maybe it is known issue but users did not know that, and if they upgrade to 4.0,  they can struggle with lots of problems. Like that 

- gives error already "setup JDK"

-  The settings panel can not be opened

- Search Everywhere (Double Shift) didn't work properly
### Temporary Solution 
 Deleting plugin from the cache. And Invalidate cache and restart. But o want to use Material Theme on new Android Studio 4.0 

### Environment
       Android Studio 4.0.1
       Build #AI-193.6911.18.40.6626763, built on June 25, 2020
       Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
       VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
       macOS 10.14.6
       GC: ParNew, ConcurrentMarkSweep
       Memory: 1981M
         Cores: 8

**Comment by mallowigi** [comment]
reinstall the plugin from the plugin repository to make sure you have the latest version

**Comment by cett01** [comment]
I could not reach Preferences -> Plugins for uninstall. But I removed manually, deleted related plugin files from the file system `( ⁨Users⁩ ▸ ⁨xxxx⁩ ▸ ⁨Library⁩ ▸ ⁨Application Support⁩ ▸ ⁨AndroidStudio4.0⁩ ▸ Material Theme)`.  After Invalidate Cache And Restart, I reinstalled as you said. It perfectly runs. Thanks to @mallowigi
