### ISSUE TITLE
change .jsx file icon to react logo?

### ISSUE THREAD

**Issue by InsidersByte** [ChrisRM/material-theme-jetbrains#162]
Currently .jsx files have a star icon (see below), I think it would be nice if the icon was the react logo.

<img width="204" alt="screen shot 2016-02-28 at 12 43 13" src="https://cloud.githubusercontent.com/assets/6938575/13379265/e0870e06-de18-11e5-8881-38205dba3041.png">

**Comment by mayrsascha** [comment]
+1

**Comment by mikeerickson** [comment]
+1

**Comment by InsidersByte** [comment]
@ChrisRM  :+1:
