### ISSUE TITLE
Material Darker's currently typed property color is unreadable

### ISSUE THREAD

**Issue by mustaqimM** [ChrisRM/material-theme-jetbrains#1620]
### Summary
With the Darker scheme enabled, I'm unable to see the current property being typed.
![image](https://user-images.githubusercontent.com/24436622/87796641-2654bc80-c839-11ea-9eac-6ba8fc351458.png)
...

### Expected behavior
Highlighted property colour should be different to the text colour
...

### Actual behavior
Unreadable property until the error is fixed or the cursor moves away from the highlighted word
...

### Environment

```
Android Studio 4.0.1
Build #AI-193.6911.18.40.6626763, built on June 25, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.6.19_1
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, org.jetbrains.kotlin, color.scheme.Tomorrow Dark, com.chrisrm.idea.MaterialThemeUI, com.google.services.firebase
```

**Comment by mallowigi** [comment]
I can't reproduce. Make sure your themes are resetted to defaults
