### ISSUE TITLE
Enhancement request remove inspection icons

### ISSUE THREAD

**Issue by slifin** [ChrisRM/material-theme-jetbrains#1621]
<img width="648" alt="Screenshot 2020-07-19 at 19 46 11" src="https://user-images.githubusercontent.com/198857/87882552-8a71af00-c9f8-11ea-81ec-83e6a985dd48.png">

IntelliJ can be configured to remove all stripe errors in the sidebar but not the top-right icon, which switches between the following icons:
- orange square
- green tick
- pause icon
- eye open icon
- off icon

Is it possible to have an option that converts these icons into empty icons to simulate a hide button for this area?

**Comment by mallowigi** [comment]
Frankly, no. This is not something that the plugin should be providing. But I find it odd that JB didn't add a switch for that. Have you tried asking the question in their tracker ?
