### ISSUE TITLE
Error squiggles missing in failed jest tests (WebStorm, TypeScript/JavaScript)

### ISSUE THREAD

**Issue by JofBigHealth** [ChrisRM/material-theme-jetbrains#1622]
### Expected behavior

When a jest test fails, with the built-in themes you get an error squiggle on the line that failed. E.g.:

![Screenshot 2020-07-20 10 08 49](https://user-images.githubusercontent.com/38071585/87920378-03145200-ca71-11ea-90f0-1b93be6dd778.png)

### Actual behavior

This does not happen when Material Themes are enabled

### Steps to reproduce (if needed)

1. Create a simple failing jest test. E.g.

```
test('fails', () => {
  expect(2).toBe(1)
})
```

2. Expected to see an underline under "toBe". This is not seen

You can also add Screenshots for a better understanding.

### Environment

Note I currently don't have material theme running but it's the latest as of 20 July 2020 and the issue has existed for at least the last two months

```
WebStorm 2020.1.3
Build #WS-201.8538.32, built on July 7, 2020
...
You have a perpetual fallback license for this version
Subscription is active until May 7, 2021
Runtime version: 11.0.7+10-b765.64 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: com.dubreuia, zielu.gittoolbox, IdeaVIM, com.intellij.properties, ru.adelf.idea.dotenv, JSTestDriver Plugin, com.deadlock.scsyntax, com.markskelton.one-dark-theme
```

**Comment by segrey** [comment]
Failure line in test code is highlighted with `CodeInsightColors.RUNTIME_ERROR`:
```
      ProblemDescriptor descriptor = ...
      descriptor.setTextAttributes(CodeInsightColors.RUNTIME_ERROR);
      holder.registerProblem(descriptor);
```

Hope it will help.

**Comment by mallowigi** [comment]
fixed
