### ISSUE TITLE
Material Theme Icons disapeared!

### ISSUE THREAD

**Issue by Simouche** [ChrisRM/material-theme-jetbrains#1625]
### Summary
Formatted my pc and installed windows, intellij, once of the first things i do is adding material design plugin, i like the files' icons so much. but i don't know why this time i can't find the theme icons, and the files' icons appear normally.
Check the image bellow.

[https://imgur.com/M4SESDC](url)

### Expected behavior
Icons showing properly.

### Actual behavior
Icons not showing properly

### Steps to reproduce

1. Installed Intellij and added the plugin.

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
Material Theme Plugin Version: 5.3.2.1

**Comment by mallowigi** [comment]
Please read the README

**Comment by Simouche** [comment]
I read the README several times, it has informations about sponsors, authors... the only thing about icons is from where they are provided.
Where can i find the fix ?

**Comment by mallowigi** [comment]
You're right, it's not in the README anymore. However it's still in the documentation website. Besides, you should have received a popup in the IDE prompting you to add the icons as part of a separate plugin.

**Comment by Simouche** [comment]
I read it too at : http://www.material-theme.com/docs/configuration/icons-settings/
I'm sorry if i'm bothering you, but i didn't start using your plugin yesterday, and i like the icons so much.
I didn't receive the pop up, i only received the one about anonymous logs collection.
What's the separate plugin?

**Comment by mallowigi** [comment]
Well, that's odd. But anyway: https://plugins.jetbrains.com/plugin/10044-atom-material-icons

**Comment by mallowigi** [comment]
I haven't worked on the plugin for a while but last time I checked there was a notification popup that redirected you to the installation page. You can also find the link in the plugin description.
