### ISSUE TITLE
IntelliJ Light Theme Cannot See Labels on Homescreen unless hovered on. IDEA 2020.2

### ISSUE THREAD

**Issue by JC-ProgJava** [ChrisRM/material-theme-jetbrains#1626]
Material UI Theme version of IntelliJ Light Theme on IDEA Ultimate 2020.2 has an issue where labels on the home screen are transparent(white) unless hovered on with mouse. This issue makes it harder to navigate the home screen. Same issue on IntelliJ Community Edition version 2020.2.

### Environment
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
For educational use only.
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.jetbrains.edu, com.intellij.plugins.html.instantEditing, training
Material Theme Version: 5.3.4

Plugin Config:
Custom Theme:
`<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="7e9692ff" />
    <option name="notificationsColor" value="323232ff" />
    <option name="treeSelectionColor" value="546e7a50" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="7f828bff" />
    <option name="foregroundColor" value="aabec5ff" />
    <option name="backgroundColor" value="303538ff" />
  </component>
</application>`

Material Theme Config XML:
`<application>
  <component name="MaterialThemeConfig">
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="highlightThickness" value="4" />
    <option name="accentColor" value="63a9f1" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-19dd4797:1736a506643:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>`

Screenshot:
<img width="486" alt="Screen Shot 2020-07-29 at 10 49 40 AM" src="https://user-images.githubusercontent.com/61588096/88751792-eec80780-d18a-11ea-9f2a-b47462295743.png">

**Comment by kennethhuang31** [comment]
I also met this bug. My theme is Github

**Comment by 007spy9** [comment]
I am also seeing this issue

**Comment by litzh** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/1627 same issue

**Comment by sven-ahrens** [comment]
Same Issue with GitHub (Material): https://github.com/ChrisRM/material-theme-jetbrains/issues/1638

**Comment by litzh** [comment]
It works fine on CLion 2020.3

**Comment by mallowigi** [comment]
Homescreen has been updated by Jetbrains, so this issue is now obsolete.

Though if other instances of the same issue appear elsewhere, please inform me.

**Comment by JC-ProgJava** [comment]
@mallowigi seems to still be a problem in IDEA 2020.3(see attached).
1. The three buttons on the top left part of the screen turns white when hovered on.
2. The 'help' button is white unless hovered on.

https://user-images.githubusercontent.com/61588096/103144646-189c4f00-4768-11eb-96f6-15af3b801d38.mp4
