### ISSUE TITLE
Change text color inside HTML Tags

### ISSUE THREAD

**Issue by ysupr** [ChrisRM/material-theme-jetbrains#163]
![screen shot 2016-03-03 at 4 12 27 pm](https://cloud.githubusercontent.com/assets/1949957/13488235/e3729b7c-e15a-11e5-984c-1225d2faa2d3.png)

Hi, i love this material theme. But i want to change the color of text inside html tags. I have checked every settings but can't find it. can you tell me where i should changes the color of these text?

thanks

**Comment by ChrisRM** [comment]
You need to make a copy of the color scheme and adjust the `Language Defaults` -> `String` -> String text` option.

**Comment by Echosgraphik** [comment]
Hi,
That doesn't works for me
![sans-titre-1-recupere](https://cloud.githubusercontent.com/assets/17746434/14631447/be5d290a-0613-11e6-91d1-d9830ffa5a69.jpg)

**Comment by ysupr** [comment]
Yep, it changes the other string text (red arrow) instead text inside html tag (blue box)

![preferences_and_login_blade_php_-_snapshot_-____sites_lampp_htdocs_snapshot_](https://cloud.githubusercontent.com/assets/1949957/14637054/8c2c9a3a-0661-11e6-8101-72020cbc978b.png)

**Comment by Echosgraphik** [comment]
And css like : '\e0000'
