### ISSUE TITLE
UI font fuzzy and thin after updating Material Theme UI to 5.3.4 and Webstorm to 2020.2

### ISSUE THREAD

**Issue by yackinn** [ChrisRM/material-theme-jetbrains#1630]
### Summary

After updating from Webstorm version 2020.1 to 2020.2 the font of the tree view changes when the Material Theme UI plugin is activated.
Disabling the plugin will solve the issue.
The editor looks fine as it was before.

### Expected behavior

The font weight and anti aliasing should stay as before.

### Actual behavior

The font looks fuzzy and thin. Screenshots are attached.

### Environment

WebStorm 2020.2
Build #WS-202.6397.88, built on July 24, 2020
Licensed to Bounty Communication Group GmbH
Subscription expired on August 13, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi, ideanginx9, mobi.hsz.idea.gitignore, socrates.tabshifter, com.hasintech.intellij.angularTemplates, com.intellij.lang.jsgraphql, ru.adelf.idea.dotenv

The Material Theme UI plugin version is 5.3.4

The screenshot seems a little bit washed out on the before_update_2020.1.png but the letters are sharp and concise.

after updating
![after_update_2020 2](https://user-images.githubusercontent.com/61085055/90181952-834c7f80-ddb1-11ea-8a88-1dc0f5b9845c.png)

before updating
![before_update_2020 1](https://user-images.githubusercontent.com/61085055/90181957-847dac80-ddb1-11ea-99c0-d492a108638d.png)

[config_xml.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/5071202/config_xml.zip)

**Comment by mallowigi** [comment]
Not related to the plugin.

https://youtrack.jetbrains.com/issue/JBR-2264
