### ISSUE TITLE
Git Diff View's Tab is difficult to see with Solarized Light

### ISSUE THREAD

**Issue by lephuongbg** [ChrisRM/material-theme-jetbrains#1633]
### Summary

Git Diff View's Tab is difficult to see with Solarized Light theme.

### Expected behavior

The background color and text color should follow normal tabs' ones.

### Actual behavior

When active:

![image](https://user-images.githubusercontent.com/1001176/91160653-a3126a80-e704-11ea-9e04-7ec1945ca698.png)

When inactive:

![image](https://user-images.githubusercontent.com/1001176/91160708-b58ca400-e704-11ea-9c02-e6787490fd70.png)

### Environment

Material Theme UI Lite 10.2 (stock config)
PyCharm 2020.2 (Professional Edition)
Build #PY-202.6397.98, built on July 27, 2020
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-42-generic

**Comment by mallowigi** [comment]
Late to the party, but i don't know why your tab is green. Make sure you don't have a File Colors active.
