### ISSUE TITLE
Git Diff Viewer - No marks near the scroll

### ISSUE THREAD

**Issue by dmitry-ivanov** [ChrisRM/material-theme-jetbrains#1634]
### Summary

There's a special highlighting for the VCS changes in the editor near the scroll:

![1-editor](https://user-images.githubusercontent.com/1286821/91287954-11a10800-e799-11ea-8f7b-2edcc22c3db1.png)

But for the Diff Viewer, those marks are gone starting from the `2020.2`.

### Expected behavior

Marks are shown in the Diff Viewer near the scroll, as it was before.

### Actual behavior

No marks are shown in the Diff Viewer near the scroll:

![2-diff-viewer](https://user-images.githubusercontent.com/1286821/91288230-6e042780-e799-11ea-9205-b3a9e93944d0.png)

### Environment

PhpStorm 2020.2
Build #PS-202.6397.115, built on July 29, 2020
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 4
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, terminal.buffer.max.lines.count=100000, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi, com.microsoft.vso.idea, de.espend.idea.laravel, com.kalessil.phpStorm.phpInspectionsUltimate, ru.adelf.idea.dotenv

Material Theme UI 5.3.4

Thanks!

**Comment by mallowigi** [comment]
Are you sure this is a behavior of the plugin? what happens in Darcula ?

**Comment by dmitry-ivanov** [comment]
Yeah, you're right - the same thing happens in Darcula.

I've created an [issue on the JetBrains tracker](https://youtrack.jetbrains.com/issue/WI-55159). Thanks!
