### ISSUE TITLE
When I selected the GitHub theme, the main screen font was not visible

### ISSUE THREAD

**Issue by LiJunYi2** [ChrisRM/material-theme-jetbrains#1638]
### Summary
When I selected the GitHub theme, the main screen font was not visible

![1598947672(1)](https://user-images.githubusercontent.com/40384503/91824919-17518e80-ec6e-11ea-815b-b2e9fe07d46e.jpg)

**Comment by 007spy9** [comment]
I see this but using the IntelliJ Light theme

**Comment by sven-ahrens** [comment]
I've the same problem with the **GitHub (Material)** theme!

**PHPStorm Version: 2020.2.3**

![Bildschirmfoto 2020-11-04 um 13 38 45](https://user-images.githubusercontent.com/18313443/98113005-520cb880-1ea3-11eb-89dc-b451b4ffac79.png)

**Comment by mallowigi** [comment]
This is obsolete in 2020.3
