### ISSUE TITLE
It's not clear enough which tab is the active tab

### ISSUE THREAD

**Issue by jlem** [ChrisRM/material-theme-jetbrains#164]
Right now we only get a thin underline for the active tab, and it's not immediately clear which one is active as it's easily lost in all of the UI noise in the IDE.

What's more is there's a bug when you have multi-row tabs enabled. The highlight border appears at the TOP of the bottom row, and at the BOTTOM of the top row, making it almost impossible to know which tab is actually active, as the border 

Ideally, the whole tab would just be one obvious, solid color that is immediately visible at a glance.

**Comment by stygiansabyss** [comment]
This actually goes further.  If your tabs are anywhere other than the top, they break.

Tabs on bottom, the highlight bar stays on the top of the window.

Tabs on left or right it always leaves the first tab with the highlight bar.

**Comment by stygiansabyss** [comment]
This is now fixed in version 1.0.8.  At the time of this post it is not updated on jetbrains yet, but you can manually install the plugin to get the fix for this.
