### ISSUE TITLE
Unexpected background color at the git log window

### ISSUE THREAD

**Issue by qioalice** [ChrisRM/material-theme-jetbrains#1640]
### Summary

Take a look to the attached screenshot.
The background of commit's list is not the same as other's.
Where I can change it? Didn't find any related color at the settings. 

<img width="813" alt="Screenshot 2020-09-04 at 17 31 53" src="https://user-images.githubusercontent.com/16417743/92251012-e030e680-eed4-11ea-8755-1317be29b9a4.png">

I also checked it at the a few of others themes (material) and found the same color mismatch.

### Expected behavior

Everything that is background has the same color: 2d2a2e.

### Actual behavior

The background of everything but git commit's list is 2d2a2e.
Git commit's list is 221f22 (darker than usual).

### Steps to reproduce (if needed)

Open IntellijIDEA, download Material theme plugin, select Monokai Pro theme, open Git log.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 25, 2020
Licensed to ...
Subscription is active until September 30, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: org.elixir_lang, com.chrisrm.idea.MaterialThemeUI, org.jetbrains.plugins.go
Material Theme plugin version: 5.3.4

**Comment by mallowigi** [comment]
You can modify it if you use the custom theme. I think it was called Secondary Background Color but I'm not sure. It could also be the misc1 and misc2 colors (don't remember the real names, you have the doc for that).
