### ISSUE TITLE
Improve Contrast for Unused Variables and Filenames

### ISSUE THREAD

**Issue by fny** [ChrisRM/material-theme-jetbrains#1641]
I switched over to Material because it seemed to provide the best contrast of all of the themes that came bundled with IntelliJ. The biggest problem that I have is that the color chosen for unused identifiers and file names is very difficult to read for all of the dark themes. Material Deep Ocean is a more specific example.

Please consider packaging a color that has more contrast in future releases. I have actually changed mine so the file names and unused identifiers match the base text color, and then I have gray underlines. I'm not suggesting that this be done in whatever the next release is, but I'm strongly suggesting a contrast improvement.

**Comment by AradAral** [comment]
Agreed. Unused variables are almost invisible!

**Comment by mallowigi** [comment]
fixed for next version
