### ISSUE TITLE
Make Tooltip "Selected element" color configurable

### ISSUE THREAD

**Issue by mathildebuenerd** [ChrisRM/material-theme-jetbrains#1642]
### Summary

The color of a selected/hovered option of the tooltip is too similar to the non-selected one. It is difficult to visually see a difference between the two.

I am using **Material Deep Ocean Contrast** theme.

Thank you

### Expected behavior

Contrast between selected / non-selected elements in Tooltip should be either configurable or more visible.

### Actual behavior

Contrast between hovered / non-hovered elements is too low. On this screenshot, the second element is selected (background is slightly more blue).

![alt](https://screenshot.click/14-11-6qpsp-yojyj.png)

### Environment
* OS: Mac OS 10.15.6
* IntelliJ Product: Webstorm 2020.2.1
* Material Theme Plugin version version: 5.3.4
* Plugin configuration:

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="1f222d" />
    <option name="selectedTheme" value="NATIVE" />
    <option name="userId" value="-1b461c22:1747c538ddb:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

If possible please also give out your Material Theme/Material Custom Theme configuration file. -> Not found 😕

**Comment by mallowigi** [comment]
Can you tell me how to reproduce? I supposed it was the autocomplete popup, but in my setup the distinction is visible, albeit very slight when the tooltip is not in focus.

Besides the original Material Theme has the same behavior.
