### ISSUE TITLE
Highlight style position of selected menu item is not correct

### ISSUE THREAD

**Issue by kuige** [ChrisRM/material-theme-jetbrains#1644]
### Summary

Highlight style position of selected menu item is not correct.

### Expected behavior

Highlight style position of selected menu item is vertical center.

### Actual behavior

Highlight style position of selected menu item has some offset.

### Steps to reproduce (if needed)

Select the corresponding menu, and you can see the highlight circle not vertically aligned center and has some offset.

The Material Theme chooser menu:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/8212800/93214882-4f8dbc80-f798-11ea-90f2-f2598f53951f.png">

The Accent Colors menu:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8212800/93214989-721fd580-f798-11ea-993f-7f56ccad27b7.png">

The Material Theme Options menu:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/8212800/93215049-7fd55b00-f798-11ea-9c58-b6ca5508a87c.png">

The Atom File Icon Settings menu:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/8212800/93215097-8c59b380-f798-11ea-8cdd-47f25eec9dd0.png">

### Environment

WebStorm 2020.2.1
Build #WS-202.6948.73, built on August 25, 2020

Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI, com.mallowigi
Material Theme UI 5.3.4

**Comment by mallowigi** [comment]
I know about this since day one, unfortunately it can't be fixed because of the way JetBrains is doing the highlighting. They do not expect the menu item height to be different from 18, and there is no way to control that.

Eventually I classified it as a non-issue. If one day the menu items height become more extensible, I'll fix it.
