### ISSUE TITLE
Add Support for IntelliJ IDEA 2020.3 EAP

### ISSUE THREAD

**Issue by alins** [ChrisRM/material-theme-jetbrains#1645]
open issue for tracking purpose.

Build #IU-203.3645.34 just got released and i see this plugin error

`Plugin 'Material Theme UI' (version '5.3.4') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.3645.34`

**Comment by mallowigi** [comment]
2020.3 is already there? Wow I have been very out of sync so long...

**Comment by titaniumlou** [comment]
to be fair it's: `IntelliJ IDEA 2020.3 EAP`

**Comment by dsvensson** [comment]
works! \o/

**Comment by alins** [comment]
confirmed! works
