### ISSUE TITLE
The background color is sometimes the same as the text color

### ISSUE THREAD

**Issue by SupianIDz** [ChrisRM/material-theme-jetbrains#1646]
### Summary

Sometimes when I write and it's done by autocomplete, the writing turns white, the same as the background color.

Even though I continued the autocomplete manually, the blending colors couldn't be lost.

The color will be normal again if I hover the text cursor to another line and press enter.

### The theme i use
- Atom One Light

but this also has an impact on other themes with light backgrounds.

### Expected behavior

The text is green

![y](https://user-images.githubusercontent.com/37969970/94227609-7634bb80-ff2d-11ea-9954-3a1fa15baa96.png)

### Actual behavior

Text transform to white color

![xx](https://user-images.githubusercontent.com/37969970/94227622-7a60d900-ff2d-11ea-957e-c93e3f517a1f.png)

### Steps to reproduce (if needed)

Write keywords, and press enter on autocomplete.

### Environment

PhpStorm 2020.2.1
Build #PS-202.6948.87, built on August 27, 2020
Licensed to  Supian M
Subscription is active until April 30, 2021
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-48-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1904M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.tree.collapse.recursively=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: BashSupport, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.mallowigi, com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete, net.seesharpsoft.intellij.plugins.file-preview, zielu.gittoolbox, de.espend.idea.laravel, org.endpointdeps.EndpointDependencies, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv
Current Desktop: zorin:GNOME

**Comment by KiranMohan** [comment]
I too face similar issue with Atom One Light theme. 
I noticed the issue while doing Refactor -> Introduce Variable and the updating the variable name.

**Comment by johnnywo** [comment]
Here too. I love Material Lighter but I have to switch back to a dark theme because everytime I like to edit a twig statement or expression I cannot see what I am typing because text and background color are the same --> unreadable.

**Comment by PatrickJosh** [comment]
I can confirm that this is also the case with Atom One Light and Github Themes on PyCharm 2020.2.3 (Community Edition), Build #PC-202.7660.27, built on October 6, 2020.
I could determine that it is caused by the live template colours. Although these are set correctly, the background is white nevertheless. 

![image](https://user-images.githubusercontent.com/32456639/99968261-39ecd280-2d99-11eb-9cbc-796b1e7a3e46.png)

As you can see in the following picture, the background is white.

![image](https://user-images.githubusercontent.com/32456639/99968393-5ee14580-2d99-11eb-8bff-9442cd8bc28b.png)

**Comment by jmarcher** [comment]
I have the same issue

**Comment by mallowigi** [comment]
Good catch. I'll update the light themes
