### ISSUE TITLE
Reserved words such as private, public, static gets wrong highlight in strings

### ISSUE THREAD

**Issue by rockymontana** [ChrisRM/material-theme-jetbrains#1648]
### Summary
When using some reserved keywords (such private, public, static, protected) it gets the wrong syntax highlight.
It doesn't get the same color as the rest of the strings.
...

### Expected behavior
It should look like a regular string.
...

### Actual behavior
It gets the same color as the respective keyword has in their own scenarios.
Say that it's a string having the same value as a visibility keyword, then it gets that.
This is, however, not for the string "class".

### Steps to reproduce (if needed)

1. Create a switch statement
2. Add the cases seen in the screenshot below

![image](https://user-images.githubusercontent.com/330839/95314367-8041ad00-0891-11eb-8195-c36f13d902ce.png)

### Environment

PhpStorm 2020.3 EAP
Build #PS-203.4203.36, built on October 1, 2020
PhpStorm EAP User
Expiration date: October 31, 2020
Runtime version: 11.0.8+10-b1098.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE, debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.dubreuia, String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, com.alicannklc.laravel.snippets, de.espend.idea.laravel, de.beyondco.tinkerwell.tinkerwell, de.espend.idea.php.annotation, ru.adelf.idea.dotenv

<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="highlightThickness" value="4" />
    <option name="accentColor" value="009688" />
    <option name="highlightColor" value="7893a1" />
    <option name="userId" value="-37115d5d:16e8cd34b32:-7ffd" />
    <option name="version" value="5.2.0" />
  </component>
</application>

**Comment by mallowigi** [comment]
This is because of the color scheme additions http://www.material-theme.com/docs/configuration/color-scheme-additions/

There is a way to improve that, but it would require refactoring the whole feature, and I don't want to do that for the moment.

Closing it for now.
