### ISSUE TITLE
Unsuitable colors for Ruby

### ISSUE THREAD

**Issue by resure** [ChrisRM/material-theme-jetbrains#165]
- `method names` are too dark (#0000FF)
- `line continuation` and  `string interpolation` backgrounds look wrong (#F5F5F5)
- `global variable`, `regexp group reference`, `hash association` and `heredoc id` are just plain black
- Too many red things :red_circle: 

http://i.imgur.com/5wyc4Pv.png

P.S. Yellow cursor rocks :+1:

**Comment by arcticicestudio** [comment]
I think all the color/syntax highlighting issues are not only related to the CSS itself. I'm the creator of an own theme and I've noticed some wierd bugs while migrating my theme from IntelliJ IDEA version `14.0.5` to `15.0.4`. I've compared all changes made by the IDE via `diff` and updated them to my theme, but there were still colors for some languages which aren't even defined in the theme. I tested some things and noticed that the wrong color will change if you tick the  "[x] Inherit from parent" once, apply the change and then untick [ ] it again and suddently it changed the colors to the once which I defined.

**Comment by resure** [comment]
It looks like this "#000" and "#00f" are just default ide settings for unspecified elements and after inherit checkbox toggling it just save that parent value.

**Comment by arcticicestudio** [comment]
I agree with this, there must be some hardcoded default values for this in the IDE code.
Best way to fix this is to
  1. initialize the configuration folder of the IDE as git repository,
  2. commit everything before you start the IDE,
  3. adjust all colors and then compare it via `diff` to implement it into the theme

I think there's no other way actually to get all the specific XML names for all the different languages and language defaults.
At least this is the way I got my theme working with all core languages and many plugins.

**Comment by NoICE** [comment]
I changed some of these to "inherit" and that looks OK to me. But I wonder... Is this how it's supposed to look? I mean, for "Go", lot of the colors are set to inherit by default.

**Comment by resure** [comment]
NoICE, I think that depends on the language syntax. For some of them defaults are fine, but for others additional tuning is required.

**Comment by mallowigi** [comment]
I think i get around ruby colors so please check with the latest release
