### ISSUE TITLE
Restarting the default theme causes the theme to be used

### ISSUE THREAD

**Issue by Acodemiao** [ChrisRM/material-theme-jetbrains#1652]
Every time I open phpstorm or GoLand, the theme always changes to default. I found that this problem is not my case. Please fix it or give a solution as soon as possible. My version of phpstorm is 2020.2.3

**Comment by mallowigi** [comment]
Do you use Settings Sync? If then, sorry but this is not possible.

**Comment by Acodemiao** [comment]
> Do you use Settings Sync? If then, sorry but this is not possible.

I found that it was not reset to the default theme. After I changed the theme, the other areas did not change successfully except for the editor interface
