### ISSUE TITLE
Exception: Wrong endOffset at line 293

### ISSUE THREAD

**Issue by timplateus** [ChrisRM/material-theme-jetbrains#1653]
### Summary

Webstorm informed me of an exception thrown on line 293. Did not notice the exception.

### Environment

* WebStorm 2020.2.3
* Build #WS-202.7660.23, built on September 30, 2020
* Runtime version: 11.0.8+10-b944.34 amd64
* VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
* Windows 10 10.0
* GC: ParNew, ConcurrentMarkSweep
* Memory: 1981M
* Cores: 8
* Registry: documentation.show.toolbar=true, ide.balloon.shadow.size=0
* Non-Bundled Plugins: String Manipulation, com.chrisrm.idea.MaterialThemeUI, com.mallowigi, Gitflow, org.sylfra.idea.plugins.linessorter
* Material Theme Plugin version: 5.3.4

**Comment by mallowigi** [comment]
Can't fix if there is no reproducible steps.
