### ISSUE TITLE
smooth scrolling become invaild after i installed plugin

### ISSUE THREAD

**Issue by alfred1994** [ChrisRM/material-theme-jetbrains#1659]
### Expected behavior

smooth scrolling works with the material-theme-ui

### Actual behavior

after I installed this plugin, scrolling will become unsmooth after i enabling smooth scrolling

### Steps to reproduce (if needed)

1. First step: enable smooth scroll(its enabled by default)

2. Second step: install material-theme-ui plugins, restart ide, do scrolling

3. Third step uninstall material-theme-ui, restart ide, do scrolling

### Environment

* Mac Os 10.14.6
* IDEA 2020.2.4
* Material Theme Plugin version 5.3.4

**Comment by mallowigi** [comment]
I couldn't reproduce. Works fine with me.
