### ISSUE TITLE
Update zip file?

### ISSUE THREAD

**Issue by stygiansabyss** [ChrisRM/material-theme-jetbrains#166]
Can we get a zip file update to 1.0.8?  Or a phpstorm plugin update for it?. 1.0.8 has a fix for vertical tabs I would really like to have and I can't figure out how to make the zip myself. Thanks!

**Comment by marioblokland** [comment]
Yes, this would be great.

**Comment by stygiansabyss** [comment]
With a manual install, this did solve it.  Thank you so much.  I can finally see which tab is active :)
