### ISSUE TITLE
Compatibility with the Pycharm 2020.3

### ISSUE THREAD

**Issue by marcinburzynski** [ChrisRM/material-theme-jetbrains#1660]
The plugin is not compatible with the latest JetBrains release.
Build no: PY-203.5981.165

**Comment by vonkanehoffen** [comment]
Yep same with PHPStorm :-(  
<img width="437" alt="Screenshot 2020-12-08 at 11 43 37" src="https://user-images.githubusercontent.com/1237951/101479758-9da2fe00-394a-11eb-860c-b30fd07ed7d4.png">

Wow I'd forgotten how ugly JetBrains stuff was without this theme! 😂

**Comment by vonkanehoffen** [comment]
...oh actually it turns out it was just a failed patch following the upgrade. Did "Check for Updates" again to retry the process and everything's fine now. Hope that helps someone :-)

Anyway, this has served as a great reminder just how awesome your work is @mallowigi 🤩  ....so thanks 😁
