### ISSUE TITLE
Comment text color being affected by keyword highlighting

### ISSUE THREAD

**Issue by dtgay** [ChrisRM/material-theme-jetbrains#1661]
### Summary

In a fresh install of RubyMine and the Material Theme plugin, Ruby keywords in comments are being highlighted. See screenshot:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/1376599/101092705-0e7f9a00-3588-11eb-8b93-b32c43766321.png">

This does not happen with any of the built-in themes, only with the Material themes.

...

### Expected behavior

Comment coloring is not affected by language keywords.

...

### Actual behavior

Theme is highlighting Ruby keywords within comments.

...

### Steps to reproduce (if needed)

1. Fresh install of RubyMine and Material Theme plugin
2. Set editor theme to one of the Material themes (I use Oceanic but it looks like the issue affects all themes)
3. Write a comment like `# Testing to see if this works`
4. `if` should be colored differently than the rest of the words in the comment

### Environment

RubyMine 2020.2.3
Build #RM-202.7660.39, built on October 8, 2020
Licensed to David Gay
Subscription is active until April 13, 2021
Runtime version: 11.0.8+10-b944.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 989M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.chrisrm.idea.MaterialThemeUI, com.mallowigi

### Config

```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="allowDataCollection" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="highlightThickness" value="1" />
    <option name="tabsHeight" value="10" />
    <option name="accentColor" value="009688" />
    <option name="userId" value="9bd83c0:175d7463fd1:-8000" />
    <option name="version" value="5.2.0" />
  </component>
</application>
```

Happy to provide any additional info.

**Comment by mallowigi** [comment]
This is not a bug of the Material Theme plugin, but rather a bug of the Ruby plugin. This color is set by Editor > Color Schemes > RDoc > Tag

Obviously wanting to put a color to a RDoc tag should not affect the keywords in comments so I suppose it's an issue to put in their bug tracker.
