### ISSUE TITLE
Not working with PHPStorm 2020.2.4

### ISSUE THREAD

**Issue by leanzafrancesco** [ChrisRM/material-theme-jetbrains#1663]
### Summary

I've just updated **PHPStorm** to the latest version **2020.2.4**, but with this version the Material Theme UI plugin doesn't work at all 😦 

### Actual behavior
In the plugin settings I see an error: **Incompatible (since build 203.5600 > PS-202.819411)**
![image](https://user-images.githubusercontent.com/16973833/101740480-2cd62000-3ac9-11eb-887f-ac354da4bbee.png)

### Environment

PhpStorm 2020.2.4
Build #PS-202.8194.11, built on November 25, 2020
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1961M
Cores: 8
Registry: run.processes.with.pty=TRUE, light.edit.file.open.enabled=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.ideolog, ru.adelf.idea.dotenv

Material Theme Plugin version: 5.5.1

**Comment by mallowigi** [comment]
I'm not providing updates for 2020.2 (although i have no idea why it would stop working as the upper limit should be 203). But please update to 2020.3 asap.

**Comment by leanzafrancesco** [comment]
Thank you very much. I've just updated PHPStorm to 2020.3 and everything works fine!
