### ISSUE TITLE
Plugin "Material Theme UI" is incompatible (since build 203.5600 > PS-202.8194.11).

### ISSUE THREAD

**Issue by jonnyhocks** [ChrisRM/material-theme-jetbrains#1664]
### Summary

As the title subject displays in the error log when launching PHPStorm after the most recent update.

### Environment

* OS (Windows, Linux, Mac) - MacOS 11.0.1 
* IntelliJ Product + version (IDEA, RubyMine...) - PHPStorm 2020.2.4
* Material Theme Plugin version 5.5.1

**Comment by mallowigi** [comment]
Try to remove and reinstall the plugin

**Comment by jonnyhocks** [comment]
Thank you, this has solved it.
