### ISSUE TITLE
Themed Title Bar gives a blank screen in fullscreen mode

### ISSUE THREAD

**Issue by driesvints** [ChrisRM/material-theme-jetbrains#1666]
### Summary

When I have the themed title bar enabled in PhpStorm from JetBrains I get a blank screen every time I open up a new project. I've know this issue to happen for about 2 years now (or more) and finally decided to file this bug report to look for a constructive solution. I've had some interactions with JetBrains about this over the past 2 years. 

It was suggested by them as well as the maintainer (in this issue: https://github.com/ChrisRM/material-theme-jetbrains/issues/1395) to disable the themed title bar and restart the IDE. However, if I do this, PhpStorm slightly becomes broken and always displays a piece of the top screen where the title bar should be when I use windows such as the Terminal screen. See a screenshot here:

<img width="768" alt="Screenshot 2020-12-15 at 12 38 54" src="https://user-images.githubusercontent.com/594614/102211218-998b5900-3ed3-11eb-94ff-94f19d407fba.png">

At this point I'm a bit desperate to see this resolved. I'd like to continue using my IDE in fullscreen mode without experiencing the blank screen. I might even be willing to fund some development time to fix this issue. But first I'd like to see if it's resolvable at all?

I hope I got everything right here. If anything's missing feel free to let me know. I'd also like to thank you for building and maintaining this theme. It's given me a real joy of using PhpStorm over the past years 👍 

PS. as a side note I want to mention that every time I change the Themed Title Bar setting, PhpStorm's editor color scheme changes to Material Lighter. I'm not sure why changing Material Theme settings changes settings in a total different part of the IDE.

### Expected behavior

Open new project with themed title bar enabled and immediately be able to use your project.

### Actual behavior

Blank screen appears. I have to exit fullscreen mode and adjust the window size slightly to be able to use my project again.

### Steps to reproduce (if needed)

1. Enable themed title bar
2. Open a project while PhpStorm was in full screen mode
3. See the blank screen (happens most of the time, though not always. I'd say around 90%).

### Environment

```
PhpStorm 2020.3
Build #PS-203.5981.175, built on December 2, 2020
Licensed to Dries Vints
Subscription is active until July 31, 2021
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.max.recent.projects=75, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.alayouni.ansiHighlight, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.mallowigi, com.github.inxilpro.intellijalpine, com.dmarcotte.handlebars, com.intellij.lang.jsgraphql, de.espend.idea.laravel, com.pestphp.pest-intellij, de.espend.idea.php.annotation, ru.adelf.idea.dotenv
```

I'm using Material Theme 5.5.1

My Material config file is (with Themed Title Bar enabled):

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="darkTitleBar" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="useMaterialFont" value="false" />
    <option name="useColoredDirectories" value="false" />
    <option name="settingsSelectedTab" value="5" />
    <option name="accentColor" value="00bcd4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="selectedTheme" value="LIGHTER" />
    <option name="userId" value="-538fca21:163ff1c91a1:-7fff" />
    <option name="version" value="5.5.0" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I have also this issue and the fix is simple. Simply resize the window one pixel down and the issue will stop happening.

No fix planned as this is from JetBrains.

**Comment by driesvints** [comment]
> I have also this issue and the fix is simple. Simply resize the window one pixel down and the issue will stop happening.

But that's not a solution. That's the actual problem. And extremely frustrating that you have to do that each time.

> No fix planned as this is from JetBrains.

@mallowigi so you're saying this is a problem with JetBrains' IDE's?

**Comment by mallowigi** [comment]
You don't have to do this everytime. Just once and the problem will not appear again. Did you double click on the title bar to maximize it? That's what I did that caused the issue. But after I resized just one pixel down, it didnt happen again.

And no, this is not a problem I've reported long ago but it wasn't in their priorities to fix: https://youtrack.jetbrains.com/issue/JBR-1569

You can follow the status of the implementation here: https://youtrack.jetbrains.com/issues?q=theme%20title%20bar

**Comment by driesvints** [comment]
> You don't have to do this everytime. Just once and the problem will not appear again.

Ah well the problem happens all the time for me, not just once.

> Did you double click on the title bar to maximize it?

No, I'm using macOS's fullscreen button on the IDE window to run the IDE fullscreen.

> And no, this is not a problem I've reported long ago but it wasn't in their priorities to fix:

Thanks for linking to that. So if I understand you correctly is that if they fix/re-implement this the problem should be solved?

Thanks for replying btw!

**Comment by mallowigi** [comment]
Even so, try to resize like I said and then click in fullscreen. This should fix the problem as well

**Comment by driesvints** [comment]
@mallowigi yeah so to give you the exact steps:

1. I open a project while the IDE is in fullscreen (it appears blank)
2. I leave full screen mode
3. I downsize by 1px or more (this displays the project again)
4. I re-enter full screen mode

And what I'm trying to say is that I have to do this every single time for every single project.

**Comment by mallowigi** [comment]
Yeah but if you quit and reopen the project, is the issue back ?

**Comment by driesvints** [comment]
I've recorded a short video to illustrate the problem. When I first open the project the issue happens. But when I close it and re-open it it doesn't happens again. However, when I quite my IDE and restart it the issue happens again. That's what I'm trying to tell.

Here's the video: https://we.tl/t-iwGFBDd3Z5

**Comment by mallowigi** [comment]
OK so bear with me. If instead of sizing left, you size down, did you try that?

**Comment by driesvints** [comment]
I can't seem to do that as that displays my menu bar from macOS which hovers over the top edge. When I move the window it also displays the contents of the IDE again but the same issue re-appears when I quit/restart the IDE again.

**Comment by driesvints** [comment]
I also can't resize from the bottom because it invokes my dock which blocks the entire bottom edge.

**Comment by driesvints** [comment]
I managed to resize from the bottom now by clicking through onto the contents but again the same issue re-appears when quitting/restarting the IDE.

**Comment by mallowigi** [comment]
Hmmm, I wish I could help but alas I can't reproduce... Please bear without the Themed Title Bar then.

**Comment by driesvints** [comment]
@mallowigi I really appreciate all the help so far 👍 

To answer one of my questions from above: do you think the issue will be fully resolved is JetBrains fixes this issue you linked? https://youtrack.jetbrains.com/issue/JBR-1569

**Comment by mallowigi** [comment]
Well if they decide to natively implement the themed title bars for all themes, then the Material Theme would not need to bundle its own implementation. I'm waiting for this to happen, maybe it will happen next year.

**Comment by driesvints** [comment]
Gotcha. Thanks :)
