### ISSUE TITLE
Broken tabs in fullscreen mode

### ISSUE THREAD

**Issue by keizah7** [ChrisRM/material-theme-jetbrains#1669]
### Summary
Tabs style is broken in default phpstorm installation. Only in fullscreen mode

### Actual behavior
![Screenshot 2020-12-20 at 13 18 54](https://user-images.githubusercontent.com/49227202/102711934-358ed900-42b5-11eb-8258-8d284772218c.png)
![Screenshot 2020-12-20 at 13 29 09](https://user-images.githubusercontent.com/49227202/102712157-b7333680-42b6-11eb-8274-f6b7883c9bcc.png)

You can also add Screenshots for a better understanding.

### Environment
PhpStorm 2020.3
Build #PS-203.5981.175, built on December 2, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: Pomodoro-tm, com.chrisrm.idea.MaterialThemeUI, com.intellij.ideolog, com.mallowigi, de.espend.idea.laravel, de.espend.idea.php.annotation, dev.nybroe.collector, ru.adelf.idea.dotenv

phpstrom 2020.3
Material theme ui 5.5.1
macOS Big SUr 11.1

**Comment by mallowigi** [comment]
Can you provide your material theme settings?

**Comment by keizah7** [comment]
@mallowigi Its default

**Comment by dragosandreidinu** [comment]
Same behavior here, only in fullscreen mode.

<img width="685" alt="Screen Shot 2021-01-28 at 09 08 59" src="https://user-images.githubusercontent.com/13589111/106102955-d8563500-6148-11eb-95e2-24ec07b6aac0.png">

### material_custom_theme.xml

```xml
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="excludedColor" value="2e3c43ff" />
    <option name="accentColor" value="009688ff" />
    <option name="notificationsColor" value="1e272cff" />
    <option name="treeSelectionColor" value="546e7a50" />
    <option name="highlightColor" value="425b67ff" />
    <option name="secondBorderColor" value="2a373eff" />
    <option name="tableSelectedColor" value="314549ff" />
    <option name="contrastColor" value="1e272cff" />
    <option name="disabledColor" value="415967ff" />
    <option name="secondaryBackgroundColor" value="32424aff" />
    <option name="buttonColor" value="2e3c43ff" />
    <option name="selectionForegroundColor" value="ffffffff" />
    <option name="selectionBackgroundColor" value="546e7aff" />
    <option name="textColor" value="607d8bff" />
    <option name="foregroundColor" value="b0bec5ff" />
    <option name="backgroundColor" value="263238ff" />
  </component>
</application>
```

### material_theme.xml

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="highlightColorEnabled" value="true" />
    <option name="accentScrollbars" value="false" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isHighlightColorEnabled" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="treeFontSizeEnabled" value="true" />
    <option name="tabFontSizeEnabled" value="true" />
    <option name="customSidebarHeight" value="22" />
    <option name="treeFontSize" value="14" />
    <option name="highlightThickness" value="1" />
    <option name="tabsHeight" value="18" />
    <option name="accentColor" value="2979ff" />
    <option name="highlightColor" value="80cbc4" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="" />
    <option name="version" value="5.5.0" />
    <option name="tabHighlightPosition" value="Bottom" />
  </component>
</application>
```

### Environment

PhpStorm 2020.3.1
Build #PS-203.6682.180, built on December 30, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.13.3

**Comment by mallowigi** [comment]
Can 't reproduce. Can you post your list of plugins?

**Comment by dragosandreidinu** [comment]
### PhpStorm Plugins

.env files support (2020.3)
Handlebars/Mustache (203.5981.152)
Ideolog (203.0.26.0)
Laravel (0.15.4)
Material Theme UI (5.6.0.1)
PHP Annotations (8.0.0)
Phing (203.7148.74)
Database Tools and SQL (203.7148.74)
Docker (203.7148.74)
FTP/SFTP Connectivity (ex. Remote Hosts Access) (203.7148.74)
Vagrant (203.7148.74)
HTML Tools (203.7148.74)
Refactor-X (203.7148.74)
XPathView + XSLT (203.7148.74)
IDE Settings Sync (203.7148.74)
Settings Repository (203.7148.74)
Angular and AngularJS (203.7148.74)
CoffeeScript (203.7148.74)
JavaScript and TypeScript (203.7148.74)
JavaScript Debugger (203.7148.74)
JavaScript Intention Power Pack (203.7148.74)
Node.js (203.7148.74)
TSLint (203.7148.74)
Vue.js (203.7148.74)
Apache config (.htaccess) (203.7148.74)
DQL (203.7148.74)
Gherkin (203.7148.74)
GNU GetText files support (*.po) (203.7148.74)
Ini (203.7148.74)
Markdown (203.7148.74)
PHPT Support (203.7148.74)
Shell Script (203.7148.74)
YAML (203.7148.74)
Drupal (203.7148.74)
Joomla! (203.7148.74)
WordPress (203.7148.74)
PHP Docker (203.7148.74)
PHP Remote Interpreter (203.7148.74)
Hunspell (203.7148.74)
CSS (203.7148.74)
Less (203.7148.74)
Sass (203.7148.74)
Tailwind CSS (203.7148.74)
W3C Validators (203.7148.74)
Blade (203.7148.74)
Haml (203.7148.74)
Twig (203.7148.74)
Behat Support (203.7148.74)
Codeception Framework (203.7148.74)
PHPSpec BDD Framework (203.7148.74)
macOS Light Theme (203.7148.74)
ChangeReminder (203.7148.74)
Git (203.7148.74)
GitHub (203.7148.74)
Mercurial (203.7148.74)
Perforce (203.7148.74)
Subversion (203.7148.74)
Command Line Tool (203.7148.74)
Copyright (203.7148.74)
EditorConfig (203.7148.74)
File Watchers (203.7148.74)
Grazie (203.7148.74)
HTTP Client (203.7148.74)
IntelliLang (203.7148.74)
Machine Learning Code Completion (203.7148.74)
Performance Testing (203.7148.74)
PHPStan Support (203.7148.74)
PhpStorm Workshop (203.7148.74)
Psalm Support (203.7148.74)
ReStructuredText (203.7148.74)
Shared Indexes (203.7148.74)
Task Management (203.7148.74)
Terminal (203.7148.74)
TextMate Bundles (203.7148.74)
Time Tracking (203.7148.74)
UML (203.7148.74)

**Comment by keizah7** [comment]
Problem started again appear in newest PhpStorm

**Comment by mallowigi** [comment]
I can't seem to reproduce

**Comment by keizah7** [comment]
How I can help you?

**Comment by mallowigi** [comment]
Can you provide the steps to reproduce? I tried opening the project in full screen with and without the title bar option, but still couldn't get this issue.

**Comment by keizah7** [comment]
> Can you provide the steps to reproduce? I tried opening the project in full screen with and without the title bar option, but still couldn't get this issue.

It doesn't appear now, but there is another issue. Autocomplete modal sometimes appear in another monitor

![image](https://user-images.githubusercontent.com/49227202/147650730-6dcf5a5e-7ccc-4340-9455-649accb993cc.png)

**Comment by mallowigi** [comment]
This isn't related to the plugin, unfortunately.
