### ISSUE TITLE
Dark/default colour is unusable with clojure (Cursive plugin)

### ISSUE THREAD

**Issue by ronaldsuwandi** [ChrisRM/material-theme-jetbrains#167]
Since by default clojure keyword is set to black, it's impossible to read unless the color is manually changed

![image](https://cloud.githubusercontent.com/assets/4120788/13625694/47c76514-e5f5-11e5-8484-1269ef3feb67.png)

Note - the colour is inherited from Java static field (same issue in Java)

**Comment by ronaldsuwandi** [comment]
IMHO changing the following will improve readability 
- Java -> Class Fields -> Static Field colour to `#F0B94C`
- Language Defaults -> Comments colour to `#7B7B7B` (block, line, and doc comments)
- Line spacing -> 1.1 (optional)

**Comment by mallowigi** [comment]
Is it still relevant?

**Comment by ronaldsuwandi** [comment]
@mallowigi Seems like for the keyword it's fine now. Although personally I think comment colour  is still too dark to be readable.

As of the latest version I propose the following changes:
- Clojure/comment foreground: #BABABA 
- Language Defaults/Comments/Doc Comment/Tag Value: #808080
- Language Defaults/Comments/Doc Comment/Text: #BABABA
- Language Defaults/Inline parameter hint: #EDEDED (foreground) and #7E7E7E (background)

Screenshot for comparison between original Material Dark vs proposed change

![image](https://user-images.githubusercontent.com/4120788/27366133-bbed8fb6-5676-11e7-8a89-dc01a078fe8c.png)
Original

![image](https://user-images.githubusercontent.com/4120788/27366142-c7a288d4-5676-11e7-9433-5ae31330b645.png)
Proposed change

**Comment by mallowigi** [comment]
I understand why you would like it, unfortunately it does not comply with the color of comments/hints from other languages so it will not be in sync.

Maybe in the future I will propose a revision of the theme, but for the moment, please bear having a copy of the scheme (I won't change them for a while so it's pretty safe I think)

--
Elior

**Comment by ronaldsuwandi** [comment]
@mallowigi just curious when you said it doesn't comply with comments from other languages because the proposed change is on the Language Defaults level, so it should comply with others isn't it? Unless if other languages comment color is not derived from the Language Defaults..

**Comment by mallowigi** [comment]
What I mean is that the actual comments color is this dark gray #4a4a4a for all languages and it was taken from the scheme's creator. Therefore I cannot (or rather, don't want to) make an exception for Clojure for the sake of consistency. 

If you meant though that even after changing the language defaults it didn't change in Clojure, this is another issue, it's because I don't inherit colors from the Languages Defaults as there are bugs with this colors inheritance, so I prefer to set all colors manually.

**Comment by ronaldsuwandi** [comment]
Ah cool. Thanks for clarifying :-)
