### ISSUE TITLE
can i set menu color?

### ISSUE THREAD

**Issue by hermitcai** [ChrisRM/material-theme-jetbrains#1670]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.
![image](https://user-images.githubusercontent.com/45086633/102782081-b217d980-43d3-11eb-903b-c5e20aba595c.png)

can i set this menu color?
i want to set black or other.

**Comment by mallowigi** [comment]
I dont think you can, it is set by apple.

**Comment by hermitcai** [comment]
> I dont think you can, it is set by apple.

haha
![image](https://user-images.githubusercontent.com/45086633/102786958-49ccf600-43db-11eb-8c84-4653dd2a19b2.png)
apple can not set this.

why chrome can set
![image](https://user-images.githubusercontent.com/45086633/102787001-5e10f300-43db-11eb-8461-ac1c5527ff05.png)

**Comment by mallowigi** [comment]
Ah I thought you were referring to the menu bar (which you were), but you meant the title bar.

This is actually something available in the settings, it's called "themed title bar".

It's disabled by default because in some settings it creates some bugs on the ide. So it's up to you whether or not you want to use it.

--
Elior

**Comment by hermitcai** [comment]
> Ah I thought you were referring to the menu bar (which you were), but you meant the title bar. This is actually something available in the settings, it's called "themed title bar". It's disabled by default because in some settings it creates some bugs on the ide. So it's up to you whether or not you want to use it.
> […](#)
> -- Elior
> On 21 Dec 2020, 16:25 +0200, hermit ***@***.***>, wrote: > I dont think you can, it is set by apple. haha apple can not set this. why chrome can set — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Ask where set it？

**Comment by hermitcai** [comment]
![image](https://user-images.githubusercontent.com/45086633/102836327-1b2f3980-4434-11eb-9497-e96d926b029b.png)
i found is here
bug This will prevent me from opening intellij idea

**Comment by hermitcai** [comment]
![Uploading image.png…]()
like this

**Comment by hermitcai** [comment]
![image](https://user-images.githubusercontent.com/45086633/102836483-78c38600-4434-11eb-9d55-7fabc4721ae7.png)
like this

**Comment by hermitcai** [comment]
hope can pair this.

**Comment by hermitcai** [comment]
![image](https://user-images.githubusercontent.com/45086633/102837942-f6d55c00-4437-11eb-869b-00aeb3418363.png)
i use this type can solve problem

**Comment by hermitcai** [comment]
thanks, the new versions can used.
