### ISSUE TITLE
Editor - No Antialiasing doesn't work anymore after update PhpStorm to Build #PS-203.5981.175, built on December 2, 2020

### ISSUE THREAD

**Issue by cuongngoz** [ChrisRM/material-theme-jetbrains#1671]
Editor with **No Antialiasing** option worked properly before, but right after update PhpStorm to new version ( new version info below )
```
PhpStorm 2020.3
Build #PS-203.5981.175, built on December 2, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
```
```
MacOs Big Sur
MacBook Pro (13-inch, 2019)
```

![Screen Shot 2020-12-24 at 08 33 23](https://user-images.githubusercontent.com/63572184/103048978-f4533d80-45c2-11eb-9a58-a9f865cf5867.png)

Now editor front looks too bold and contrast. I used **No Antialiasing** before to reduce too much bold & contrast.

![image](https://user-images.githubusercontent.com/63572184/103049071-4005e700-45c3-11eb-900d-c76950b5fc58.png)

This is before one was lighter, not too bold & contrast.
![image](https://user-images.githubusercontent.com/63572184/103059985-4c953a00-45d9-11eb-899c-6c9ffdbd4579.png)

**Comment by mallowigi** [comment]
not related to the plugin. Check without the plugin and you'll see.
