### ISSUE TITLE
Enhancement request: Hide title bar

### ISSUE THREAD

**Issue by haringsrob** [ChrisRM/material-theme-jetbrains#1672]
### Summary

After installing material theme today and playing around with the experimental settings I suddenly got to this result on mac:
<img width="908" alt="Schermafbeelding 2020-12-27 om 11 54 14" src="https://user-images.githubusercontent.com/866743/103169265-70a38600-483a-11eb-869e-c90a7a330729.png">

Now while this might be a bug, I feel like it is actually quite nice.

I think I can only reproduce it when material icons are installed as well.

### Expected behavior

Have it like the screenshot consistently

### Actual behavior

After a restart the behaviour is gone.

### Steps to reproduce (if needed)

1. Install material theme and material icons
2. Play around with the custom titlebar setting

### Environment

PhpStorm 2020.3
Build #PS-203.5981.175, built on December 2, 2020
Subscription is active until April 24, 2021
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 2900M
Cores: 16
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: IdeaVIM, com.4lex4.intellij.solarized, com.chrisrm.idea.MaterialThemeUI, de.espend.idea.laravel, de.beyondco.tinkerwell.tinkerwell, mac-native, net.antelle.intellij-xcode-dark-theme, me.mbolotov.cypress, ru.adelf.idea.dotenv, com.laravel_idea.plugin

**Comment by mallowigi** [comment]
Ummm... no. This looks like a bug, is fairly inconvenient (a lot of OS features are available on the title bar such as maxmimizing, moving windows etc), and obstructs other features like the Project dropdown.
