### ISSUE TITLE
page error on https://www.material-theme.com/

### ISSUE THREAD

**Issue by ecom-moce** [ChrisRM/material-theme-jetbrains#1673]
PAGE ERROR after 

https://www.material-theme.com/docs/reference/associations/

If you click on:

<NEXT : FOLDER ASSOCIATIONS>

you will get a 404 file not found page:

https://www.material-theme.com/docs/reference/folder_associations

Look at the UNDERSCORE.

If you choose from the menu 'Folder Associations'

you will come in page

https://www.material-theme.com/docs/reference/folder-associations

OK, good luck and have a good 2021...
Gerard Frijters.

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
Thanks. I need to update the doc, it is fairly outdated...
