### ISSUE TITLE
High GPU usage when Commit View is in focus

### ISSUE THREAD

**Issue by tickez** [ChrisRM/material-theme-jetbrains#1674]
Raised an issue with Jetbrains, but the issue only occurs when I have the theme active. 
https://youtrack.jetbrains.com/issue/IDEA-258761

### Summary

iMac 5k 27" 2019, 64GB, Radeon Pro Vega 48 8GB, MacOS 11.1
Material Theme UI 5.5.1 Plugin with Atom Material Icons installed.

- Open "Commit View" and have it focused
GPU usage will go up to 100% with 65 FPS

Move focus away from commit view, eg. select an editor or anything else
GPU usage drops to 0% with 5 FPS

### Expected behavior

No GPU/CPU activity while Commit View is open. 

### Actual behavior

GPU at 100% and 65 FPS rendering

### Environment

IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.rest, com.failfast, de.sist.gitlab, com.github.timo_reymann.ansible_vault_integration, ir.msdehghan.plugins.ansible, ru.sadv1r.ansible-vault-editor-idea-plugin, GrepConsole, intellij.prettierJS, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI, com.intellij.plugins.html.instantEditing, com.jetbrains.php, org.jetbrains.plugins.ruby, Pythonid

Material Theme UI Plugin version 5.5.1. Atom Dark theme.

```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="contrastMode" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="pristineConfig" value="false" />
    <option name="customSidebarHeight" value="22" />
    <option name="settingsSelectedTab" value="1" />
    <option name="tabsHeight" value="24" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="userId" value="ac3f73f:1724b42f67b:-8000" />
    <option name="version" value="5.5.0" />
  </component>
</application>

```

**Comment by mallowigi** [comment]
What's commit view?

**Comment by tickez** [comment]
The non-modal version of the commit dialog. If i use the modal dialog, everything is fine.

**Comment by mallowigi** [comment]
But what do you mean by "open". Do you mean the tool window expanded?

**Comment by tickez** [comment]
Expanded and "in focus". It if just sits there expanded but you are actually working in an editor, the GPU usage drops.

**Comment by mallowigi** [comment]
I'm not available to reproduce, I am on Big Sur and have the commit view in focus but I don't notice any changes in CPU or GPU...

**Comment by tickez** [comment]
The only information I can capture currently is the below. If the window is in focus, the AWT-Appkit appears... 

 %CPU  Subsystem

 62.0  <Process total CPU usage>
 12.8  <infrastructure: AWT-AppKit>
  8.7  <infrastructure: Java2D Queue Flusher>
  8.4  <unidentified: UI thread>
  7.8  <unidentified: Java2D Queue Flusher>
  3.2  Plugin Material Theme UI: com.mallowigi.idea.ui
  2.7  <infrastructure: UI thread>
  2.0  ide.ui.laf.darcula.ui (in com.intellij)

**Comment by tickez** [comment]
When I profile the IDE this occurs to be to most likely cause.
```
com.mallowigi.idea.ui.MTButtonUI.paintText(Graphics, JComponent, Rectangle, String)
javax.swing.plaf.basic.BasicButtonUI.paintText(Graphics, AbstractButton, Rectangle, String)
com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.paintContents(Graphics, AbstractButton)
com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.paint(Graphics, JComponent)
javax.swing.plaf.ComponentUI.update(Graphics, JComponent)
com.intellij.ide.ui.laf.darcula.ui.DarculaButtonUI.update(Graphics, JComponent)
javax.swing.JComponent.paintComponent(Graphics)
javax.swing.JComponent.paint(Graphics)
com.intellij.ui.components.BasicOptionButtonUI$BaseButton.paint(Graphics)
javax.swing.JComponent.paintChildren(Graphics)
javax.swing.JComponent.paint(Graphics)
javax.swing.JComponent.paintChildren(Graphics)
javax.swing.JComponent.paint(Graphics)
javax.swing.JComponent.paintToOffscreen(Graphics, int, int, int, int, int, int)
javax.swing.BufferStrategyPaintManager.paint(JComponent, JComponent, Graphics, int, int, int, int)
javax.swing.RepaintManager.paint(JComponent, JComponent, Graphics, int, int, int, int)
javax.swing.JComponent._paintImmediately(int, int, int, int)
javax.swing.JComponent.paintImmediately(int, int, int, int)
javax.swing.RepaintManager$4.run()
javax.swing.RepaintManager$4.run()
java.security.AccessController.doPrivileged(PrivilegedAction, AccessControlContext)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext)
javax.swing.RepaintManager.paintDirtyRegions(Map)
javax.swing.RepaintManager.paintDirtyRegions()
javax.swing.RepaintManager.prePaintDirtyRegions()
javax.swing.RepaintManager$ProcessingRunnable.run()
java.awt.event.InvocationEvent.dispatch()
java.awt.EventQueue.dispatchEventImpl(AWTEvent, Object)
java.awt.EventQueue$4.run()
java.awt.EventQueue$4.run()
java.security.AccessController.doPrivileged(PrivilegedAction, AccessControlContext)
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(PrivilegedAction, AccessControlContext, AccessControlContext)
java.awt.EventQueue.dispatchEvent(AWTEvent)
com.intellij.ide.IdeEventQueue.defaultDispatchEvent(AWTEvent)
com.intellij.ide.IdeEventQueue._dispatchEvent(AWTEvent)
com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8()
com.intellij.ide.IdeEventQueue$$Lambda$647.175417086.compute()
com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(ThrowableComputable)
com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(AWTEvent, boolean, AWTEvent, EventWatcher, Class, long)
com.intellij.ide.IdeEventQueue$$Lambda$645.1062377984.run()
com.intellij.ide.IdeEventQueue.dispatchEvent(AWTEvent)
java.awt.EventDispatchThread.pumpOneEventForFilters(int)
java.awt.EventDispatchThread.pumpEventsForFilter(int, Conditional, EventFilter)
java.awt.EventDispatchThread.pumpEventsForHierarchy(int, Conditional, Component)
java.awt.EventDispatchThread.pumpEvents(int, Conditional)
java.awt.EventDispatchThread.pumpEvents(Conditional)
java.awt.EventDispatchThread.run()
```

**Comment by mallowigi** [comment]
I've been able to reproduce on 2020.3.1 on IntelliJ IDEA, but it doesnt happen on RubyMine.

**Comment by mallowigi** [comment]
Ok you're right on the spot, this happens because of the MTButtonUI.

I'll take a look.

**Comment by tickez** [comment]
Fantastic, thanks a lot!
