### ISSUE TITLE
set title bar theme problem.

### ISSUE THREAD

**Issue by hermitcai** [ChrisRM/material-theme-jetbrains#1677]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

when i use intellij idea set this.
![image](https://user-images.githubusercontent.com/45086633/103964013-5ef4a380-5195-11eb-934d-2fc592887590.png)
is faield

bug i set datagrid titile bar theme
can success
![image](https://user-images.githubusercontent.com/45086633/103964154-c01c7700-5195-11eb-82b3-48a73297c8e7.png)

datagrid the titile bar theme set success,
but intellij idea set is faield, why?
is i set have problem?

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
dont see problem

**Comment by hermitcai** [comment]
> dont see problem

i set themed title bar true
![image](https://user-images.githubusercontent.com/45086633/104118399-c5c7b780-5363-11eb-9a3a-b1006aa4ec02.png)

but not work
![image](https://user-images.githubusercontent.com/45086633/104118424-e4c64980-5363-11eb-837a-901201bf4247.png)

**Comment by hermitcai** [comment]
> dont see problem

can you see the problem?
i send again.

**Comment by mallowigi** [comment]
Sorry, I have troubles understanding you. But if you mean that the window is empty like in your screenshot, this is a known issue, this is why the setting is disabled by default. Usually just resizing the window is enough to fix it but there are cases when it's not.

**Comment by hermitcai** [comment]
> Sorry, I have troubles understanding you. But if you mean that the window is empty like in your screenshot, this is a known issue, this is why the setting is disabled by default. Usually just resizing the window is enough to fix it but there are cases when it's not.

okay, i try resizing the window, is success
my titile bar color set success,
But how can I fix this problem by not setting the window size?

**Comment by mallowigi** [comment]
It's a known bug, you even get a confirmation window when you try to enable the setting. I could not reproduce it to know how to fix it, that's why I decided to disable it by default and notify the user when enabling it. If it's too much bother you should disable it.
