### ISSUE TITLE
Grey to highlight selection is confusing in Atome One Light

### ISSUE THREAD

**Issue by Kwadz** [ChrisRM/material-theme-jetbrains#1685]
Normally we expect a selection with a high contrast color in light themes (usually blue). Since grey is already used to highlight the current line the cursor is on, I suggest to color selections with blue like the one used in the scroll bar for example to keep consistency.

![image](https://user-images.githubusercontent.com/1472599/106255029-bed0ee00-6219-11eb-8911-4dad7a3ad0f1.png)

**Comment by mallowigi** [comment]
The question is rather whether or not the Atom One Light themes in VSCode/Sublime/Atom behave like this or not. This plugin should be consistent with the other versions of the themes, so that's why.

**Comment by Kwadz** [comment]
Thanks @mallowigi, I understand. I installed Atom and checked. The selection color is grey but they remove the light grey on the full line when there is a selection to avoid any confusion. It is easy to copy the same behavior?

**Comment by mallowigi** [comment]
Nope, it's not possible. But you can open a feature request at JetBrains, maybe they'll implement it

**Comment by Kwadz** [comment]
Done [here](https://youtrack.jetbrains.com/issue/WI-58327) 🤞
