### ISSUE TITLE
Inconsistency with color of words where the cursor is on in Atome One Light

### ISSUE THREAD

**Issue by Kwadz** [ChrisRM/material-theme-jetbrains#1686]
![image](https://user-images.githubusercontent.com/1472599/106255264-1a02e080-621a-11eb-87cb-484e75fc75d0.png)

**Comment by mallowigi** [comment]
IMO this is to differentiate between the identifier under the caret and all other occurences of the said identifier.

I think it's better, but in any case you're free to change it in the Color Scheme settings.

**Comment by Kwadz** [comment]
@mallowigi, the cursor was on the selection line 34.
Why `$action` line 32 should be different from the ones at 33 and 36 in that case?

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/106287310-53a20e80-624f-11eb-871c-ac65351ff2e1.png)
