### ISSUE TITLE
PHP $this should be have color different from variable.

### ISSUE THREAD

**Issue by nvcken** [ChrisRM/material-theme-jetbrains#1687]
### Summary
PHP `$this` doesn't have any highlight color, just white as well as variable

### Expected behavior
`$this` would be better when have a different color

### Actual behavior
`$this` is white

### Screenshots

![image](https://user-images.githubusercontent.com/3489866/106696905-46e73700-6610-11eb-8c58-0a9805d08079.png)

### Environment
* macOS Big Sur 11.1
* PHPStorm 2020.3.2
* Material Theme Plugin 5.6.0.1
* Theme option selected: Material Oceanic

**Comment by mallowigi** [comment]
Weird... I dont use PHPStorm but last time I checked it was fine. Let me se eif that reproduces

**Comment by mallowigi** [comment]
I see, you're right. I'll fix that for next version.

**Comment by nvcken** [comment]
Wow cool, I just tricky by custom it in Color Scheme -> PHP -> `$this` variable
![image](https://user-images.githubusercontent.com/3489866/106733574-a5c6a380-6644-11eb-892a-7b97a0a6b5be.png)
Looks fine, but I think update fix would be better then.
Thanks

**Comment by nvcken** [comment]
@mallowigi seen this fixed, just in case when will be released for update.
Thanks
