### ISSUE TITLE
Don't replace file type icons when using this plugin

### ISSUE THREAD

**Issue by dlsniper** [ChrisRM/material-theme-jetbrains#169]
Hi,

Would you be open to allow an option to not replace the icons when using this plugin?
I really like what the plugin does but I really dislike that the icons for file types are replaced.
Thank you.

**Comment by ChrisRM** [comment]
I don't think I'll be using any time on setting up such an option for this plugin, but I've started working on another plugin which allows setting your own custom icons(or the default ones), colors and other settings. I want to fix the bugs in this plugin before I go all in on the other one though, so you would have to wait a while.

If you're restless, feel free to clone this repo and remove the icon replacer. Should be a matter of removing line 23 and 36-38 from META-INF/plugin.xml, build it and you should be good to go.
