### ISSUE TITLE
The debug breakpoint color could be lighter in the LighterMaterial theme

### ISSUE THREAD

**Issue by thiagoao** [ChrisRM/material-theme-jetbrains#1690]
**Summary**
The breakpoint highlight is too dark for lighter material which makes the code line hard to read.

**Actual color**
![image](https://user-images.githubusercontent.com/1511659/107721502-8f12f300-6cbb-11eb-83ef-5d747db2b813.png)

**Suggestion**
It would be more interesting if the background color was lighter. 

**Color suggestion**
Color: #FDD7D7
![image](https://user-images.githubusercontent.com/1511659/107722153-13b24100-6cbd-11eb-8e74-8631f5b199ed.png)

**Environment**
Windows 10 pro
PHPStorm 2020.3.2
Material Theme Plugin 5.6.0.1
Theme option selected: Material Lighter

**Comment by mallowigi** [comment]
Indeed. Thanks
