### ISSUE TITLE
GFY override doesn't seem to work

### ISSUE THREAD

**Issue by hankhank10** [ChrisRM/material-theme-jetbrains#1691]
### Summary

When I attempt to load the theme it now asks me for $5. Not a one time donation, $5 a month. I hit the "you must be joking, gfy" button but the "just kidding" dialogue fails to pop up.

...

### Expected behavior

That fonts and colours based on an open source design language developed by Matias Duarte and Google should not be monetised by a third party.

...

### Actual behavior

Laughable attempts at monetisation.

...

### Steps to reproduce (if needed)

None necessary.

**Comment by mallowigi** [comment]
Rude language is not tolerated. Thank you.

**Comment by vianch** [comment]
totally agree with hankhank10

**Comment by eshe-huli** [comment]
We are many having the same issue, please don't close it

**Comment by mallowigi** [comment]
It's not an issue, please grow up
