### ISSUE TITLE
WebStorm

### ISSUE THREAD

**Issue by St1ggy** [ChrisRM/material-theme-jetbrains#1692]
Can't see plugin page in WebStorm settings
### Summary
With 6.0v plugin page in WebStorm settings can't be displayed.
I can see this menu if I disable all plugins with concurrent option
![image](https://user-images.githubusercontent.com/13361661/108197966-9b7ccd00-714d-11eb-9f17-38768bdaf3e8.png)

### Expected behavior
Correct display for this point

### Actual behavior
No plugins in Marketplace and Installed

### Steps to reproduce (if needed)
1. Open Preferences->Plugins
2. ![image](https://user-images.githubusercontent.com/13361661/108197285-c0bd0b80-714c-11eb-9dbb-263e0d8ae110.png)

### Environment
WebStorm 2021.1 EAP
Build #WS-211.5538.3, built on February 2, 2021
WebStorm EAP User
Expiration date: March 4, 2021
Runtime version: 11.0.10+8-b1304.1 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation (8.10.191.000.0), com.chrisrm.idea.MaterialThemeUI (5.7.0), com.jetbrains.plugins.ini4idea (211.5538.10), com.mallowigi (36.0), com.tabnine.TabNine (0.3.2), etp.gpb.marketplace.uxg.plugin.id (1.0.11), zielu.gittoolbox (203.4.8), Dart (211.5538.10), com.hasintech.intellij.angularTemplates (1.1.3), com.codota.csp.intellij (4.2.2), com.github.ArtsiomCh.NestedBracketsColorer (0.5.0), izhangzhihao.rainbow.brackets (6.15), ru.adelf.idea.dotenv (2021.1)
Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

Can't see Plugins folder in ~/Library/Application Support/JetBrains/WebStorm2021.1/

**Comment by mallowigi** [comment]
Please update Webstorm, this should be fixed in the latest version.
