### ISSUE TITLE
Checkboxes in Solarized Light Theme are indistinguishable between states

### ISSUE THREAD

**Issue by lephuongbg** [ChrisRM/material-theme-jetbrains#1693]
### Summary

Please look at the screenshot. The checked and unchecked state of the checkboxes are not distinguishable under Solarized Light theme.

### Expected behavior

Checkboxes are supposed to look like this (had to use other theme for screenshot):

![image](https://user-images.githubusercontent.com/1001176/108322445-d0018f00-7208-11eb-8087-8074a96b27c7.png)

### Actual behavior

But now they're looking like this:

![image](https://user-images.githubusercontent.com/1001176/108322205-8b75f380-7208-11eb-922f-78629bb0a4ab.png)

### Environment

PyCharm 2020.3.2 (Professional Edition)
Build #PY-203.6682.179, built on December 31, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-65-generic
Registry: ide.intellij.laf.enable.animation=true, keymap.windows.as.meta=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, color.scheme.Monokai Materialized, com.mallowigi.idea, zielu.gittoolbox, mobi.hsz.idea.gitignore, org.sonarlint.idea, org.toml.lang, some.awesome, NodeJS, com.jetbrains.plugins.jade, intellij.prettierJS, org.jetbrains.plugins.vue, com.koxudaxi.pydantic
Current Desktop: KDE
Material Theme Plugin version: **12.5 Lite**

**Comment by mallowigi** [comment]
This is an issue of the Lite plugin, please open the issue in the correct repository, thanks!
