### ISSUE TITLE
Cannot save settings after activating license

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#1696]
### Summary

Switching from free model to paid model disabled the premium features. So far so good. But after activating the license I am found unable to edit my settings.

- Found in DataGrip

Need to check on multiple IDES, this is very problematic.

**Comment by welcoMattic** [comment]
Hi! I just issued the same experience with PHPStorm 2021.1 EAP and brand new licence

**Comment by mallowigi** [comment]
FYI, had to remove the `material_theme.xml` manually to fix it.

**Comment by rodicodi** [comment]
Hi, i just experienced the same issue. 

> FYI, had to remove the `material_theme.xml` manually to fix it.
This helped for me too, but i think in the background things still go wrong. 
Settings menu goes all wonky when applying any setting from the Material UI Settings menu.

**Comment by mallowigi** [comment]
I've found the issue and fixed it (hopefully), however the damage was already done and people that got affected cannot have their own settings reverted... 

Removing the xml file and restarting should fix things up. 

That being said, what do you mean @rodicodi ? Can you tell me the steps on hot to reproduce? Thanks.

**Comment by rodicodi** [comment]
Yes, i should've elaborated... 
What i mean is that when i change a setting, the background-color of the settings menu changes. 
Also some checkbox styles and border changes.

For example: When i change Custom Sidebar Height, and press apply, the background color changes (See screenshot).

I'm using PHPStorm 2021.1 EAP on Windows 10 Enterprise 10.0.18363 
(i don't know if this helps, but more info is better imo)

![Screenshot 2021-02-27 124911](https://user-images.githubusercontent.com/34191525/109386327-3cac1600-78fa-11eb-8805-47915f33fb32.jpg)

**Comment by mallowigi** [comment]
This issue looks like the Material Components are getting scrambled. You don't have the Material Theme Lite enabled wouldn't you?

**Comment by rodicodi** [comment]
> This issue looks like the Material Components are getting scrambled. You don't have the Material Theme Lite enabled wouldn't you?

No i have a paid licence for Material UI. The settings are being saved though, after i updated to the newest version.
