### ISSUE TITLE
jQuery duplicate Selectors.

### ISSUE THREAD

**Issue by Orillian** [ChrisRM/material-theme-jetbrains#17]
Was doing some cleanup on some old jQuery code and there was nothing to differentiate when a duplicate selector was used. 

Minor, but so very useful when refactoring lots of jQuery.

**Comment by ChrisRM** [comment]
Fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/7f1ebac95e49058034345f9a4c7eb8a39125b4a7
