### ISSUE TITLE
Java icon missing

### ISSUE THREAD

**Issue by vivitarjos** [ChrisRM/material-theme-jetbrains#170]
Hi, 
Great theme you have here. There's a problem with java icons, they just don't display. Please uncomment the line in the association icon xml file. You maybe commented it by mistake.
sorry for my bad english.
Thanks.

**Comment by hschroedl** [comment]
This is indeed a problem. It does not leave a good impression to try a new theme (in Idea) and suddenly not have icons for Interfaces, Classes.

**Comment by mxmind** [comment]
The same issue, the project panel looks really weird.

**Comment by vivitarjos** [comment]
What can solve the problem is to unzip the theme in your config intellij folder and uncomment the file then save it. Relaunch your IDE and it's going to work.

**Comment by mxmind** [comment]
Ok, the following command fixed my issue
```bash
$ jar uf "Material Theme.jar" icon_associations.xml
```
before run, put icon_associations.xml in the same folder where is the jar placed.

**Comment by hschroedl** [comment]
@mxmind This solution appears to only temporarily fix the issue. Upon restarting Idea the icons reset to the default (stars) after a couple of seconds. Any clue what that is about?

**Comment by ChrisRM** [comment]
I'll fix it guys. Give me an hour

**Comment by ChrisRM** [comment]
@hschroedl @mxmind Can you try the [newest build](https://github.com/ChrisRM/material-theme-jetbrains/raw/master/Material%20Theme.zip) and let me know how it goes?

**Comment by hschroedl** [comment]
That did it. The newest build fixes this issue.

**Comment by mxmind** [comment]
The same as for @hschroedl
