### ISSUE TITLE
How to activate paid license?

### ISSUE THREAD

**Issue by daniluk4000** [ChrisRM/material-theme-jetbrains#1701]
Hello there! I have bought license and installed it last EAP version of Webstorm. 

It shows me that I use free version thought. How do I upgrade my local version to Premium?

**Comment by mallowigi** [comment]
Hi, 

Sorry for the lack of visibility, I'll try to improve the flow.

To enable it you can either do it via the `Menu -> Help -> Buy/Register` or via the action `Activate License` in the Material Theme Actions Menu

**Comment by mallowigi** [comment]
Leave this open, surely other people will find it useful.
