### ISSUE TITLE
Incorrect font in Terminal using Git Bash

### ISSUE THREAD

**Issue by daniluk4000** [ChrisRM/material-theme-jetbrains#1703]
### Summary
After v6 font in Terminal (Git Bash version) looks really bad because of letter spacing (works without plugin)

### Steps to reproduce (if needed)

1. On Windows, install Git Bash
2. Open Settings -> Tools -> Terminal
3. Set Shell Path to `"C:\Program Files\Git\bin\sh.exe" --login -i`

![изображение](https://user-images.githubusercontent.com/10450717/109626335-79257f00-7b51-11eb-8b71-e9ba81a2c2bd.png)
_Material Theme UI_

![изображение](https://user-images.githubusercontent.com/10450717/109626497-aa9e4a80-7b51-11eb-9627-4e220943ae36.png)
_Default theme_

### Environment

WebStorm 2021.1 EAP
Build #WS-211.6222.6, built on February 26, 2021
WebStorm EAP User
Expiration date: March 28, 2021
Runtime version: 11.0.10+9-b1341.2 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.1.2), com.mallowigi (36.0), net.seesharpsoft.intellij.plugins.csv (2.14.4), org.jetbrains.plugins.hocon (2020.1.0), ru.adelf.idea.dotenv (2021.1)

**Comment by daniluk4000** [comment]
@mallowigi sorry, but this is still not fixed

Shell Path: "C:\Program Files\Git\bin\sh.exe" --login -i

And it works in default theme

**Comment by mallowigi** [comment]
Are you sure you don't have a modified color scheme ?

**Comment by daniluk4000** [comment]
> 
> 
> Are you sure you don't have a modified color scheme ?

Nope, I am using the default. Weird thing, I have updated to 6.2.0, but on Material Theme UI section is still shows 6.1.1. 

![изображение](https://user-images.githubusercontent.com/10450717/110244973-5ee50a00-7f72-11eb-9493-265ea2d96107.png)

![изображение](https://user-images.githubusercontent.com/10450717/110244979-64425480-7f72-11eb-8552-2ac4e9110f8e.png)

**Comment by mallowigi** [comment]
The wrong version is a bug on my end, I'll fix it thank you. But what I'm talking about is whether or not you have a modified color scheme. When you open the color scheme settings, do you see the current color scheme colored in the accent color ?

**Comment by daniluk4000** [comment]
> 
> 
> The wrong version is a bug on my end, I'll fix it thank you. But what I'm talking about is whether or not you have a modified color scheme. When you open the color scheme settings, do you see the current color scheme colored in the accent color ?
> 
> https://www.material-theme.com/docs/configuration/color-schemes/

![изображение](https://user-images.githubusercontent.com/10450717/110245755-90130980-7f75-11eb-98b0-2f0be5ff44c7.png)


![изображение](https://user-images.githubusercontent.com/10450717/110245739-88ebfb80-7f75-11eb-9930-c14772c982b0.png)

**Comment by mallowigi** [comment]
Ok so you see that `Material Darker` in the color scheme settings is orange, it means it is modified. If you didnt touch it, you can click on the three dots on the right and select "reset to defaults".

**Comment by daniluk4000** [comment]
> 
> 
> Ok so you see that `Material Darker` in the color scheme settings is orange, it means it is modified. If you didnt touch it, you can click on the three dots on the right and select "reset to defaults".

I left to Color Scheme -> Restore Defaults

That didn't help

**Comment by mallowigi** [comment]
Ok can you print here the settings page named "Console Font" ?

**Comment by daniluk4000** [comment]
> 
> 
> Ok can you print here the settings page named "Console Font" ?

![изображение](https://user-images.githubusercontent.com/10450717/110246778-074a9c80-7f7a-11eb-8a02-1e63d414d6e7.png)

**Comment by daniluk4000** [comment]
Note: if I switch, for example, to Jetbrains Mono, it works

**Comment by mallowigi** [comment]
So maybe you have a broken version of Menlo on your computer? Usually Menlo is not available on Windows.

**Comment by daniluk4000** [comment]
> 
> 
> So maybe you have a broken version of Menlo on your computer? Usually Menlo is not available on Windows.

Interesting. How do I check it?

It's not installed though.

![изображение](https://user-images.githubusercontent.com/10450717/110246889-8344e480-7f7a-11eb-821f-751541415e7b.png)

**Comment by daniluk4000** [comment]
Switching System language to English didn't help though.

**Comment by mallowigi** [comment]
я действительно не знаю... очень странно...

**Comment by mallowigi** [comment]
I'll try to take a look but it's the first time I encountered something like this. I thought the issue was with the fallback font.

**Comment by daniluk4000** [comment]
> 
> 
> I'll try to take a look but it's the first time I encountered something like this. I thought the issue was with the fallback font.

Nope, wallback font works fine.

And it seems like it **was** working in Webstorm 2020.3

**Comment by mallowigi** [comment]
could you try with 2020.3 and tell me if that's the case ?

**Comment by daniluk4000** [comment]
> 
> 
> could you try with 2020.3 and tell me if that's the case ?

Working perfectly in 2020.3

Console Font: JetBrains Mono

![изображение](https://user-images.githubusercontent.com/10450717/110247394-2a2a8000-7f7d-11eb-98b9-51d58c68f7da.png)

**Comment by mallowigi** [comment]
🤔  why is it written JetBrains Mono?

**Comment by daniluk4000** [comment]
Dunno, those are defaults

**Comment by mallowigi** [comment]
This is available since 6.2.0
