### ISSUE TITLE
Weird behaviour with external theme enabled (with paid licence)

### ISSUE THREAD

**Issue by welcoMattic** [ChrisRM/material-theme-jetbrains#1704]
### Summary

When I select an external theme (here Dracula Pro Van Helsing), the UI text gone black. On a dark UI, it becomes unreadable.

### Expected behavior

UI text keeps the color for dark UI.

### Actual behavior

Black text on dark UI.

### Steps to reproduce (if needed)

1. Use Material Theme Pro
2. Install Dracula Pro
3. Enable Dracula Pro (Van Helsing, or any other Dracula Pro theme)

![image](https://user-images.githubusercontent.com/773875/110020149-85fccb00-7d29-11eb-8e16-2ee091cf6bc5.png)

### Environment

PhpStorm 2021.1 EAP
Build #PS-211.6085.19, built on February 18, 2021
PhpStorm EAP User
Expiration date: March 20, 2021
Runtime version: 11.0.10+9-b1341.2 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.16-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: run.processes.with.pty=TRUE, bigger.font.in.project.view=true, ide.tooltip.initialDelay=539, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.1.0), com.draculatheme.idea (1.3.1), com.mallowigi (36.0), de.netnexus.camelcaseplugin (3.0.8), net.seesharpsoft.intellij.plugins.csv (2.14.4), org.intellij.plugins.hcl (0.7.10), name.kropp.intellij.makefile (211.6085.3), org.zalando.intellij.swagger (1.0.28), org.toml.lang (0.2.141.3674-211), rocks.blackcat.vcl (0.7.2), NEON support (0.5.1), de.espend.idea.php.toolbox (5.1.1), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.22.206), me.mbolotov.cypress (1.4), org.rust.lang (0.3.141.3674-211), ru.adelf.idea.dotenv (2021.1)
Current Desktop: i3

### Material Theme configuration:

```
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="compactStatusBar" value="true" />
    <option name="compactTables" value="true" />
    <option name="contrastMode" value="true" />
    <option name="highContrast" value="true" />
    <option name="accentScrollbars" value="false" />
    <option name="compactDropdowns" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="fileStatusColorsEnabled" value="false" />
    <option name="isCompactMenus" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isTabsShadow" value="false" />
    <option name="isWizardShown" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="themedScrollbars" value="false" />
    <option name="useColoredDirectories" value="false" />
    <option name="indicatorStyle" value="None" />
    <option name="customSidebarHeight" value="22" />
    <option name="tabsHeight" value="22" />
    <option name="accentColor" value="ff79c5" />
    <option name="selectedTheme" value="DRACULA" />
    <option name="userId" value="1d44fc37:168dc88f911:-8000" />
    <option name="version" value="6.1.1" />
    <option name="tabHighlightPosition" value="Top" />
    <option name="codeAdditionsEnabled" value="false" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Reproduced. I've taken a quick look but do far couldn't find the cause of the problem, especially since the black color doesn't seem to be in the original theme.

There must be some sorts of defaults set by JB that I probably missed.

I hope I'll be able to find the culprit soon.

**Comment by mallowigi** [comment]
Ok good news, I've managed to fix it :)

I'll release the update asap.
