### ISSUE TITLE
how can i change this font color?

### ISSUE THREAD

**Issue by hermitcai** [ChrisRM/material-theme-jetbrains#1706]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
![image](https://user-images.githubusercontent.com/45086633/110600290-bc6d9680-81be-11eb-9e2d-699ba97fc7f5.png)
 i want to change this color, but un success, please help me.
...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
you can find this in Settings > Color Scheme > Java > Instance field (I think)

**Comment by hermitcai** [comment]
Ok I find this, 
I like this theme very much, but I feel that my overall color is too bright, a bit piercing, I want to darken the overall color, but I am working on the content too much, there is a faster overall font color darker don’t Is it so piercing?

**Comment by mallowigi** [comment]
Hmm, it depends on what you like. I do use the Darker theme as well and it is good to me like that

**Comment by mallowigi** [comment]
I think it's the folded color

**Comment by hermitcai** [comment]
Where?

**Comment by mallowigi** [comment]
Sorry I can't look up for you. Try to change the color scheme values one by one until you find it.
