### ISSUE TITLE
Title bar can not hide in full screen model(macOS)

### ISSUE THREAD

**Issue by x4vierli** [ChrisRM/material-theme-jetbrains#1707]
### Summary
Title bar can not hide in full screen model(macOS)

### Expected behavior
Title bar can hide in full screen model(macOS)

### Steps to reproduce (if needed)

1. user Material theme in idea
2. trigger the full screen model
![image](https://user-images.githubusercontent.com/6872643/111031772-2185ee00-8444-11eb-8c6f-cbdbd1dc00f0.png)

### Environment
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
Non-Bundled Plugins: CMD Support, IdeaVIM, Statistic, com.mallowigi, com.alibaba.p3c.smartfox, MavenRunHelper, com.chrisrm.idea.MaterialThemeUI, cn.wuzhizhan.plugin.mybatis
Material Theme Plugin version: 5.6.0.1

**Comment by mallowigi** [comment]
I see some issues with the Fullscreen mode on mac myself, especially with the _Themed Title Bar_ option on.

- The title bar disappears completely in fullscreen (which is good), but after going back to windowed screen, the title bar doesn't come back
- When opening a new project once full screen, the window is blank.

I don't know how I can fix these issues, but I'll try

**Comment by x4vierli** [comment]
> I see some issues with the Fullscreen mode on mac myself, especially with the _Themed Title Bar_ option on.
> 
> * The title bar disappears completely in fullscreen (which is good), but after going back to windowed screen, the title bar doesn't come back
> * When opening a new project once full screen, the window is blank.
> 
> I don't know how I can fix these issues, but I'll try

Thanks a lot

**Comment by mallowigi** [comment]
Since the themed title bar has been sunsetted in 2021.2, I'm closing this
