### ISSUE TITLE
Scroll performance regression in Rider EAP (2021.1 EAP8)

### ISSUE THREAD

**Issue by peppy** [ChrisRM/material-theme-jetbrains#1709]
### Summary

With either Material Icons or Material Theme enabled in EAP8, there is a noticeable degradation in scroll performance, seemingly when gutter icons are visible. For me this drops me from smooth 144hz scrolling to <30fps.

This does not happen on 2020.3.4.

Not sure if this is something at your end or rider's end, but I'll leave that to your discretion.

### Steps to reproduce (if needed)

- Open a file with many gutter icons (ie. a class which is implementing an interface).
- Scroll

First half of the video shows scrolling in a section of the file without gutter icons; second half shows a section with gutter icons and a severe drop in scroll performance.

https://user-images.githubusercontent.com/191335/111737222-8c12b000-88c2-11eb-935a-1b435e876fcc.mp4

### Environment

```
JetBrains Rider 2021.1 EAP 8
Build #RD-211.6556.8, built on March 16, 2021
Rider EAP User
Expiration date: April 15, 2021
Runtime version: 11.0.10+9-b1341.20 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
.NET Core 5.0.3
macOS 11.2.2
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 32
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, search.everywhere.configurations=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.actions=false, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, search.everywhere.toolwindows=false, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=368, ide.balloon.shadow.size=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false, rider.enable.designer.winForms=false
Non-Bundled Plugins: AceJump (3.6.3), GLSL (1.19), IdeaVIM (0.65), com.chrisrm.idea.MaterialThemeUI (6.2.0), com.intellij.resharper.HeapAllocationsViewer (2021.1.0-eap04), com.mallowigi (36.0), izhangzhihao.rainbow.brackets (6.17)
```

All rider settings: 
[rider-all-settings.jar.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6168880/rider-all-settings.jar.zip)

**Comment by mallowigi** [comment]
Hmm, can you check if that reproduces when the plugin is disabled?

**Comment by peppy** [comment]
With both material icons and material theme disabled, it does not seem to occur. Enabling either of the two looks to reproduce.

**Comment by mallowigi** [comment]
My question is whether the Material Icons or the Material Theme is the culprit. Since you're talking about icons I suspect it is the former, but I need to be sure.

**Comment by peppy** [comment]
I did try toggling both separately, and strangely both of them cause the issue to being. I tried multiple times, restarting between each attempt. I also tried reinstalling and made sure no other plugins were enabled while testing.

**Comment by peppy** [comment]
I've tested on Rider beta 9 and this still occurs. I can also add that the reduction in performance is far less with *only* Material UI active, but it is still noticeable. With Material Icons active (both with and without Material UI), the performance is *far* lower.

If you need a reproduction case, the one I have been using is `SkinnableSound` in our project (https://github.com/ppy/osu), which works remarkably well due to the number of implemented interface methods.

**Comment by mallowigi** [comment]
I did take a look, and so far the performance change with Material UI theme is very benign. So I can rule this out. However, the Atom Material Icons plugin makes this much more noticeable.

What's even weirder is that **it is flawless in 2020.3**, even with both plugins. AFAIK nothing changed between 2020.3 and 2021.1 in AMI, so this might be something related to how they handled icons since 2021.

I'll take a look in their tracker to see if we can pinpoint it to something

**Comment by peppy** [comment]
Can confirm that I've been using both plugins on 2020.3 with no issue as well. Glad you can reproduce though. I did consider reporting this to jetbrains but it was hard for me to do that without knowing how these plugins are interacting, and where the problem lies.

Would be great to get this reported to them in a hope of a fix before the next major release goes live!

**Comment by peppy** [comment]
Not sure when this was resolved, but it definitely looks resolved at my end 👍🏻 .

**Comment by peppy** [comment]
Reporting back to say that this actually is not fixed, and I had to disable the plugin again.

**Comment by peppy** [comment]
Would you like me to open a bug with jetbrains on this project's behalf if you are sure it's an upstream issue?
