### ISSUE TITLE
Selection color same as occurence highlighting color

### ISSUE THREAD

**Issue by sangimed** [ChrisRM/material-theme-jetbrains#171]
Everything is on the image bellow :

![selection_055](https://cloud.githubusercontent.com/assets/857405/13901810/5b3ac1ac-ee30-11e5-94c4-99579052e010.png)

PS : There is an error in the code (should be Swift_Message instead of Swift_Mailer) but it's not really important for this issue

**Comment by mallowigi** [comment]
should be fixed in the latest release
