### ISSUE TITLE
Click in project tree hits item above cursor

### ISSUE THREAD

**Issue by bjoernmayer** [ChrisRM/material-theme-jetbrains#1710]
### Summary
Sometimes my clicks in the tree are not recognized correctly and hit the item above the clicked one.
See the video

...

### Expected behavior
Clicked item is opened
...

### Actual behavior
Item above clicked item is opened
...

### Steps to reproduce (if needed)

No idea what causes this. It just happens. Then a restart of IntelliJ fixes it.

https://user-images.githubusercontent.com/20116376/112016189-c97a7600-8b2c-11eb-99bd-78bb95d3102e.mov

### Environment

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Licensed to me
You have a perpetual fallback license for this version.
Subscription is active until December 9, 2021.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 8108M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.nativeDebug, com.jinsihou.react.snippets, com.mallowigi, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, name.kropp.intellij.makefile, org.sylfra.idea.plugins.linessorter, com.intellij.kubernetes, idea.plugin.protoeditor, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI

**Comment by mallowigi** [comment]
I have no idea what this is... Is it something new?

**Comment by bjoernmayer** [comment]
I'd say it started within the last month? I cannot pin it down to any special event

**Comment by mallowigi** [comment]
I can't reproduce, unfortunately. Do you know what might be causing this to occur?

**Comment by bjoernmayer** [comment]
I'll watch it tomorrow and try to observe what leads to this 🤞🏻

**Comment by bjoernmayer** [comment]
It is related to Mac OS BigSurs tabbing. I had a bunch of IDE tabs and closed all except one. And then the issue appeared.
I still cannot reproduce it everytime

**Comment by bjoernmayer** [comment]
Issues did not reappear with 2021.1. I will close the issue.
Thanks for taking time :)
