### ISSUE TITLE
The screen is blank after phpstorm is opened, and it is normal after dragging the software window.

### ISSUE THREAD

**Issue by tlerbao** [ChrisRM/material-theme-jetbrains#1713]
The screen is blank after phpstorm is opened, and it is normal after dragging the software window.

I tested the problem, and when the theme title bar is turned on, this bug will appear.

https://user-images.githubusercontent.com/20442232/113271408-16203700-930d-11eb-84bd-31f1a66868b9.mp4

**Comment by tlerbao** [comment]
I think this bug appeared after the custom theme was enabled

**Comment by mallowigi** [comment]
This is a known issue which sadly I couldn't reproduce. Please look at the troubleshooting section https://www.material-theme.com/docs/configuration/other-tweaks-settings/#themed-title-bar

**Comment by mallowigi** [comment]
In my case I managed to fix it by resizing a bit smaller, but I heard other users complaining that this didn't solve their issue.

**Comment by tlerbao** [comment]
Drag the window or change the size of the window to restore the content display; but every time you start it, you have to do this operation and look forward to fixing this bug.

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/1666
