### ISSUE TITLE
Can the background color of this prompt message be customized?

### ISSUE THREAD

**Issue by tlerbao** [ChrisRM/material-theme-jetbrains#1714]
Can the background color of this prompt message be customized?

![image](https://user-images.githubusercontent.com/20442232/113399641-200c6d80-93d3-11eb-9689-0e116caa7982.png)

**Comment by mallowigi** [comment]
This should use the same color as the background color apparently.

**Comment by tlerbao** [comment]
> This should use the same color as the background color apparently.

What I mean is how to set the background color. It seems that there is no such setting in the setting option Material Custom Theme.

**Comment by mallowigi** [comment]
Have you tried all options from https://www.material-theme.com/docs/configuration/custom-themes/ ?

**Comment by tlerbao** [comment]
@mallowigi thanks，I found this, but I did not find where the background color of the horizontal scroll bar is set. Do you know?
![image](https://user-images.githubusercontent.com/20442232/113472871-78f20980-9498-11eb-8d7e-945e28c4328f.png)

**Comment by mallowigi** [comment]
Currently no, but this could be a nice feature.

**Comment by mallowigi** [comment]
Done. Take a look at the scrollbars page, tell me if that solves the problem

**Comment by tlerbao** [comment]
![image](https://user-images.githubusercontent.com/20442232/115229153-48bb9380-a145-11eb-9987-a176091882c8.png)
@mallowigi I modified all the colors here and did not change the background color of the horizontal scroll bar below.

**Comment by mallowigi** [comment]
Is that so?  Then I'm afraid there's no way to do it

**Comment by tlerbao** [comment]
@mallowigiIt seems that the color of the horizontal scroll bar and the border line color can be changed, but the background color of the horizontal scroll bar is not.

**Comment by tlerbao** [comment]
@mallowigi 
I tried to change the two parameters of the color scheme to change the background color of the horizontal scroll bar.
![image](https://user-images.githubusercontent.com/20442232/115952158-129c5c00-a517-11eb-9b17-a99e873c1618.png)

![iShot2021-04-24 16 07 10](https://user-images.githubusercontent.com/20442232/115952222-568f6100-a517-11eb-8092-fc008743d0b5.gif)

Other TrackColor seems to affect here

**Comment by mallowigi** [comment]
I see. These values are indeed missing from the settings page. I'll add them as well.

**Comment by tlerbao** [comment]
I have updated the latest version, and found that many functions have to be paid to use. Is there a preferential purchase channel? Promo Code?

**Comment by mallowigi** [comment]
Yes, but there are many free tiers available. More info here: https://www.material-theme.com/docs/pricing/
