### ISSUE TITLE
How to downgrade?

### ISSUE THREAD

**Issue by labs20** [ChrisRM/material-theme-jetbrains#1716]
Hi.

First of all, I have no problem with you guys monetizing your own work, and I'm glad that you're going to it. 

But... 

I was using the plugin normally until yesterday, and this morning I was promped for an update, as it was the case many times before, but this time after the update, BUM! gone all features, pay me if you want it back! 

Looks like I got attacked by a ransomware. 

I got no warning about the new pay model before I update, and found no "go back to previous version" button anywhere. 

I felt disrespected.

Again, this is a nice plugin and you guys are entitled and deserve to be well paid for your good job, as much as any of us, but the way you changed the model it was no good.

By the way, you've probably had the news on your website, but at least in my case, I'm coding hard all day long and its not very common to me to stop and just pay a random visit on a plugin page unless I want to know more details on how to config a thing.

I wish you the best with your new version, but I want to downgrade for what I had yesterday, please.

Thank you.

**Comment by Lucaskyy** [comment]
See #1718

**Comment by LosEagle** [comment]
I wish it at least didn't mess up my IDE's UI so bad, it looks broken even after uninstalling the plugin  :-/

**Comment by mallowigi** [comment]
I have given a bit of a thought and I am willing to make some options available in the free plan as well, to not incapacitate users. These are:
- Tab Height
- Compact Settings
- Scrollbar colors

**Comment by NishargShah** [comment]
@mallowigi Thanks, we will hope it will come soon

Here is my question https://stackoverflow.com/questions/66980515/how-to-change-sidebar-height-and-tab-height-manually-in-jetbrains-webstorm?noredirect=1#66980515

**Comment by mallowigi** [comment]
New version is available, with more free features available. Tab Height, Compact Settings, Uppercase buttons and Scrollbars.
