### ISSUE TITLE
Gutter in the Webstorm editor became huge!

### ISSUE THREAD

**Issue by slavoroi** [ChrisRM/material-theme-jetbrains#1717]
### Summary

Gutter became huge in my webstorm editor!

### Expected behavior

Gutter should be smaller by ~30%

### Actual behavior

![image](https://user-images.githubusercontent.com/13114384/113863137-f88e1a00-97b1-11eb-8734-97512a0badd7.png)

### Steps to reproduce (if needed)

1. Open the code editor and you will find a huge gutter.

You can also add Screenshots for a better understanding.

### Environment

It should contain:
* Ubuntu 20.04
* Webstorm 2021.1
* Plugin version (latest 6.2.1)
* Using Atom One Dark theme.

In my friend's computer without material theme, the gutter seems smaller.

**Comment by mallowigi** [comment]
Usually the gutter expands if you have some gutter icons on it. Please check that you don't.

**Comment by slavoroi** [comment]
I think after a restart or something i did it was fixed.
![image](https://user-images.githubusercontent.com/13114384/114014130-f212a780-9870-11eb-9a15-3839d900ce50.png)
