### ISSUE TITLE
CLICK HERE IF YOU WANT TO KNOW HOW TO DOWNGRADE TO THE FREE VERSION (5.7.0)

### ISSUE THREAD

**Issue by Lucaskyy** [ChrisRM/material-theme-jetbrains#1718]
Hi.

Even though you made it paid, thank you for at least making the previous versions free; since they worked fine for me.

Download version `5.7.0`: [https://plugins.jetbrains.com/plugin/download?rel=true&updateId=109027](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=109027)

**Make sure you uninstalled the previous version of the plugin!** 

Move the `.zip` file into your IDE, and then click `Restart`.

Have fun! You now have the free version and if you did it right your theme and settings should be saved and should be the same.

**Comment by Lucaskyy** [comment]
If you want, you can also tell your users this at the bottom of the README so they know instead of having an issue here.

But it would be nice to tell your users how to because most probably don't know-how.

**Comment by LosEagle** [comment]
Thanks!

**Comment by mallowigi** [comment]
Thanks. I have no problem leaving the older versions free as long as there are no breaking changes in the underlying JetBrains SDK.

**Comment by labs20** [comment]
Thanks

**Comment by huypxgear** [comment]
Thanks

**Comment by Lucaskyy** [comment]
@mallowigi Sadly, the time has come. WebStorm 2021.2 and up don't seem to work anymore because the build version has been changed from `211.*` to `WS-212-*`
