### ISSUE TITLE
Change font color of inactive selected tabs (Oceanic)

### ISSUE THREAD

**Issue by Wexoo** [ChrisRM/material-theme-jetbrains#1719]
### Summary
Enable changing of font color of inactive selected tabs (Oceanic Theme)

### Expected behavior
Font color on tabs should be readable. White or a little darker than white, but way lighter as it is now.

### Actual behavior
![Screenshot 2021-04-07 at 20 42 08](https://user-images.githubusercontent.com/676195/113918361-9f8aaa00-97e2-11eb-9785-2ec0f770cd2d.png)

### Steps to reproduce (if needed)
1. Activate Material Oceanic
2. Open editor tab(s)
3. Click in another tool window / window

### Environment
IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
Plugin Version: 5.6.0.1

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/114035884-33fb1800-9888-11eb-9547-b83bf7f3ddbf.png)
