### ISSUE TITLE
Some buttons have a status bar overlay

### ISSUE THREAD

**Issue by konstantin-striukov** [ChrisRM/material-theme-jetbrains#1722]
Some modal or sidebar buttons have strange overlay when hovering them. Most often this is the bottom right corner of the IDE window (memory used, branch name).

Pull Requests Sidebar:
![image](https://user-images.githubusercontent.com/67154180/114378228-2dbeb180-9b90-11eb-816a-c1f6e24d285c.png)

Modal for open a separate project:
![image](https://user-images.githubusercontent.com/67154180/114378349-4af38000-9b90-11eb-91f1-fb1dee5380d8.png)

____

**OS:** Win 10
**IDE:** Webstorm 2021.1
**Plugin:** Material Theme UI 6.2.3 (Purchased)

**Comment by mallowigi** [comment]
Thanks, I'll take a look

**Comment by mallowigi** [comment]
I haven't been able to reproduce, however I did some upgrades in the highlighting component. Can you take a look and tell me if that happens again? thanks

**Comment by konstantin-striukov** [comment]
Your changes definitely have improvements., but the problem still remained and its behavior became somewhat different.

Below I have attached two videos (sorry for the strange size, there was no time to study software for the screencast). According to them, it can be seen that sometimes anomalous overlap does appear.

Moreover, I noticed some logic in the appearance of the bug.
Pay attention to the video, where I want to open another project. If I hover over a button, the hover effect works and then I move the cursor up (where there are no other buttons) and then everything is fine, but if I move the cursor from the first button to the second, then the second appears hover effect, plus an overlay from the first button, which didn't have time to disappear.

The second video also shows logic. 
When I hover over the button, while the hover effect is working out, you can see that the loader is spinning (from the bottom of the editor), but as soon as the effect is completed, the spinner freezes, and the behavior is similar when I remove the cursor (the loader spin again).

P.S. Can I give you more information about my system, so you can reproduce the bug?

---
Open another project
https://user-images.githubusercontent.com/67154180/115145193-074dba00-a059-11eb-854c-68971cc5928d.mp4

---
Modal for pulling a project
https://user-images.githubusercontent.com/67154180/115145199-09b01400-a059-11eb-8efd-81b59a274492.mp4

**Comment by mallowigi** [comment]
I think the issue resides with using opacity for buttons... I had a similar issue in the past... I've asked for advice and another fellow is using luminosity rather than opacity to simulate the "fade", so maybe this will work, but I can't promise it. I'll try to take a look, but in any case this is something that only happens on Windows, so it will be a bit hard to test :/

If you could come to Slack that would be useful!

**Comment by konstantin-striukov** [comment]
Yes, I can. Where I can to find a link to the channel?

**Comment by mallowigi** [comment]
There is a link in the readme and in the website's footer

**Comment by mallowigi** [comment]
Closed
