### ISSUE TITLE
[bug] Impossible to turn off language additions

### ISSUE THREAD

**Issue by daniluk4000** [ChrisRM/material-theme-jetbrains#1724]
### Summary
I don't want to use language additions, and I should have ability to turn them off

### Expected behavior
When I turn off language additions in settings, they are turned off

### Actual behavior
When I turn off language additions in settings, they are still enabled

### Steps to reproduce (if needed)

1. Turn off language additions
2. Try to write `!==` in code

![изображение](https://user-images.githubusercontent.com/10450717/114421316-dcc5b200-9bbd-11eb-945e-85890fa3e5c6.png)

### Environment

WebStorm 2021.1
Build #WS-211.6693.108, built on April 5, 2021
Licensed to Gorodskoy Supermarket LLC / Данила Родичкин
Subscription is active until January 12, 2022.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2016M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.properties (211.6693.44), com.mallowigi (36.0), com.jetbrains.twig (211.6693.44), com.chrisrm.idea.MaterialThemeUI (6.2.3), ru.adelf.idea.dotenv (2021.1)

**Comment by mallowigi** [comment]
!== is not a language addition.

**Comment by daniluk4000** [comment]
> 
> 
> !== is not a language addition.

Okay, sorry. So... How can I turn off !== conversion?

**Comment by mallowigi** [comment]
It's part of the colors for "operator". Look in Editor > Color Schemes

**Comment by mallowigi** [comment]
Or alternatively you can position the cursor on the !==, then open the command palette and write `Jump to colors and fonts`, then change the value here

**Comment by daniluk4000** [comment]
Thanks, found it. For those who will be looking for the same: open Editor -> Color Scheme -> Color Scheme Font. Uncheck the "Enable ligatures" flag.
