### ISSUE TITLE
Duplicate Tool Window Icons

### ISSUE THREAD

**Issue by guac420** [ChrisRM/material-theme-jetbrains#1726]
### Summary

With a project already open, I went to open another project, and when I did the tool window icons duplicated.
I went `File>Open` then selected "This Window" when asked, "Where would you like to open this project?"

### Expected behavior

There should only be one set of icons.

### Actual behavior

Duplicate tool window icons in the left and right toolbars
![Duplicate Icons](https://user-images.githubusercontent.com/60993440/115102890-bd52c000-9f02-11eb-8812-058913e86851.png)

If you open many new projects in the same window you can really break things
![Many Duplicates](https://user-images.githubusercontent.com/60993440/115103130-651cbd80-9f04-11eb-80ad-a90b9d9d8c7b.png)

 The duplicate icons also have no function to them.

### Steps to reproduce

1. Open project via `File>Open`
2. Open a different project but select "This Window" in the "Where to open" menu

The "Where to open menu" that appears after selecting a project from `File>Open`
![Where to open menu](https://user-images.githubusercontent.com/60993440/115102977-39e59e80-9f03-11eb-9990-15866bd153a1.png)

### Environment

CLion 2021.1
Build #CL-211.6693.114, built on April 6, 2021
Subscription is active until September 13, 2021.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.new.stripes.ui=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: GLSL (1.19), org.toml.lang (0.2.145.3797-211), com.chrisrm.idea.MaterialThemeUI (6.3.0), org.rust.lang (0.3.145.3797-211)

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="84ffff" />
    <option name="selectedTheme" value="DEEPOCEAN" />
    <option name="userId" value="1a4a7f64:177fb9f9300:-8000" />
    <option name="version" value="5.5.0" />
  </component>
</application>
```

#### Note

I also have the material theme icons plugin installed, but I determined that was not the issue by disabling it and reproducing the issue with just the material theme plugin active.

**Comment by mallowigi** [comment]
Wow, I never encountered that. Can you try to disable and reenable the striped tool windows to see if that fixes the issue? Thanks

**Comment by Rasool-deldar** [comment]
This problem will be solved when I close the program and reopen it. You probably wrote an append code in the plugin that you have to delete or make a condition and check if it does not exist it will append or the whole icon will load again

This problem only occurs on this windows option.

![image](https://user-images.githubusercontent.com/58503211/115106695-81a80c80-9f7b-11eb-81ef-e7f327fd49e8.png)
![image](https://user-images.githubusercontent.com/58503211/115106804-faa76400-9f7b-11eb-857a-ddbfc4ac84e8.png)

**Comment by mallowigi** [comment]
Nope, I managed to reproduce as well on Mac, and this happens only when the Themed Title Bar is active, that's why I couldn't reproduce it before. Unfortunately I am not able to find a fix at the moment, but I'll keep looking.

**Comment by Rasool-deldar** [comment]
> Nope, I managed to reproduce as well on Mac, and this happens only when the Themed Title Bar is active, that's why I couldn't reproduce it before. Unfortunately I am not able to find a fix at the moment, but I'll keep looking.

I think you will find this solution soon and you will solve the problem. I wish you success

**Comment by mallowigi** [comment]
Okay, I couldn't find a solution at the moment, therefore I've set the feature as disabled by default. I'll keep working on it, thanks!
