### ISSUE TITLE
Keyword inside doc comments are being highlighted (v6.3.2)

### ISSUE THREAD

**Issue by feRpicoral** [ChrisRM/material-theme-jetbrains#1727]
### Summary
Since the latest update (6.3.2), keywords in doc comments are now highlighted

### Expected behavior
That whole comment should be of the same color, except for special tags, like JSDoc tags.

### Actual behavior
All keywords within doc comments, like `new`, `string`, etc are highlighted as they were normal code.

![Screenshot from 2021-04-18 21-37-31](https://user-images.githubusercontent.com/30874402/115167511-4f3b0400-a08e-11eb-83d4-f61c6c9dd748.png)

### Environment

WebStorm 2021.1
Build #WS-211.6693.108, built on April 5, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-50-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: projectView.hide.dot.idea=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic (4.1.7), com.godwin.json.parser (1.4.1), com.intellij.apacheConfig (211.6693.108), com.mallowigi (36.0), com.almightyalpaca.intellij.plugins.discord (1.6.1), mobi.hsz.idea.gitignore (4.1.0), com.chrisrm.idea.MaterialThemeUI (6.3.2), com.codota.csp.intellij (4.2.4), izhangzhihao.rainbow.brackets (6.17), ru.adelf.idea.dotenv (2021.1)
Current Desktop: ubuntu:GNOME

### Config
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="omitted - if relevant I can send it" />
    <option name="version" value="6.3.2" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Started working on a fix. Thx

**Comment by mishkamishka47** [comment]
This is also happening in the body of JSX tags
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7673281/115270709-38ce9000-a102-11eb-8d1c-1f05796ee1db.png">
<img width="532" alt="image" src="https://user-images.githubusercontent.com/7673281/115270728-3d934400-a102-11eb-98ce-8c94c0d5229a.png">

**Comment by mallowigi** [comment]
Thanks for this. I fixed it, I hope that's the last of it!
