### ISSUE TITLE
Enabling "Striped Tool Windows" reverts editor theme

### ISSUE THREAD

**Issue by mirrana** [ChrisRM/material-theme-jetbrains#1728]
### Summary

I attempted to enable the experimental feature "Striped Tool Windows" and doing so changed my editor color scheme. I use Material Darker as my IDE theme, but Darkula for my editor colors. When I enabled the Stiped Tool Windows, my editor colors reverted to Material Darker. Similarly when I disabled the feature.

### Expected behavior

The editor color scheme should remain unchanged

### Actual behavior

The editor color scheme was reverted to match the IDE theme I had selected

### Steps to reproduce (if needed)

1. Select a different editor color scheme than what is used by the IDE (Settings | Editor | Color Scheme | Scheme)
2. Enable or disable the "Striped Tool Windows" feature
3. Note that the editor color scheme and fonts change.

### Environment

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to Sarah Skanes
Subscription is active until January 5, 2022.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: debugger.watches.in.variables=false, debugger.mayBringFrameToFrontOnBreakpoint=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.marketplace (211.6693.139), mobi.hsz.idea.gitignore (4.1.0), com.dmarcotte.handlebars (211.6693.44), com.chrisrm.idea.MaterialThemeUI (6.3.2), com.intellij.gwt (211.6693.65)
Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by mallowigi** [comment]
Fixed in 6.3.3. Hope this is enough.
