### ISSUE TITLE
Can't disable current theme indicator in status bar

### ISSUE THREAD

**Issue by richiksc** [ChrisRM/material-theme-jetbrains#1730]
### Summary

Can't hide the current theme indicator in the lower right hand corner of the status bar of the IDE.

### Expected behavior

I am able to toggle the selected theme indicator on and off from Material Theme settings, as there was before.

### Actual behavior

There is no such option.

![image](https://user-images.githubusercontent.com/8939680/115479142-65230300-a20d-11eb-99e8-48d0e285422f.png)

### Environment

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to Richik [Redacted]
Subscription is active until November 14, 2021.
For educational use only.
Runtime version: 11.0.10+9-b1341.35 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 1128M
Cores: 8
Registry: bigger.font.in.project.view=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), mobi.hsz.idea.gitignore (4.1.0), net.javaru.idea.frc (1.4.0-2021.1-eap.1), com.chrisrm.idea.MaterialThemeUI (6.3.3)
Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by mallowigi** [comment]
To disable it, right click on the status bar and unselect Material Theme
