### ISSUE TITLE
Striped Tool Window not working on Ubuntu 20.04 with latest version of WebStorm

### ISSUE THREAD

**Issue by niels-bosman** [ChrisRM/material-theme-jetbrains#1733]
### Summary

When trying out the new "Striped Tool Window" on Ubuntu 20.04 nothing happens.

### Expected behavior

A striped tool window appears on the left.

### Actual behavior

Nothing happens.

![material theme](https://user-images.githubusercontent.com/25898715/115518121-22524100-a288-11eb-87c6-0bedc966c86d.gif)

### Environment

WebStorm 2021.1
Build #WS-211.6693.108, built on April 5, 2021
Licensed to Niels Bosman
Subscription is active until August 23, 2021.
For educational use only.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-50-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.new.stripes.ui=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.pyango.gmbh (1.0), com.almightyalpaca.intellij.plugins.discord (1.6.1), com.chrisrm.idea.MaterialThemeUI (6.3.3)
Current Desktop: ubuntu:GNOME

**Comment by mallowigi** [comment]
Have you tried closing and reopening the project ?

**Comment by niels-bosman** [comment]
@mallowigi Yes. This has been happening since release of the Striped Tool Window and I tried on multiple times after multiple reboots.

**Comment by mallowigi** [comment]
Hm, I never tried it on Linux nor Windows, I'll take a look whenever I can.

**Comment by seanmuth** [comment]
Similar Issue on macOS 10.14.6

Tool window tabs just go away. New behavior on 6.3.3 is also that the changes don't get applied after selection, but only after the "Material Theme Options" button is clicked.

Not sure if I'm just missing a setting in View or something but nothing is jumping out to me.

PyCharm 2021.1 (Professional Edition)
Build #PY-211.6693.115, built on April 6, 2021
Licensed to Digital First Media / Sean Muth
Subscription is active until July 20, 2021.
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: bigger.font.in.project.view=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic (4.1.7), YAML/Ansible support (0.11.2), com.godwin.json.parser (1.4.1), com.jetbrains.php.framework (211.6693.44), com.mallowigi (36.0), com.chrisrm.idea.MaterialThemeUI (6.3.3), com.jedide.apex (3.0.5.211), com.leinardi.pycharm.pylint (0.12.2), org.tonybaloney.security.pycharm-security (1.24.0), ru.adelf.idea.dotenv (2021.1), ru.meanmail.plugin.requirements (2021.3-211)

![img](http://g.recordit.co/b69K8Bq38R.gif)

**Comment by mallowigi** [comment]
This is a known issue, you need to close and reopen the project for the toolbars to get added. However once you do you can toggle with no problems.

**Comment by seanmuth** [comment]
@mallowigi that did it, thanks!

**Comment by niels-bosman** [comment]
@mallowigi Today when I restarted WebStorm it suddenly worked. I am happy it works now but I still think it is strange.
