### ISSUE TITLE
Trees are too compact with 6.4.0

### ISSUE THREAD

**Issue by bjoernmayer** [ChrisRM/material-theme-jetbrains#1741]
### Summary

After updating Intellij and PHPStorm to 2021.1.1 the plugin was also updated to 6.4.0.

Since then project view and other tool windows using trees are too compact / tight.

### Expected behavior

whitespaces between tree entries

### Actual behavior

![Bildschirmfoto 2021-05-03 um 12 01 28](https://user-images.githubusercontent.com/20116376/116864787-ac939100-ac08-11eb-97ce-72350541030a.png)

### Environment

IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry: ide.new.stripes.ui=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.nativeDebug (211.7142.13), com.jinsihou.react.snippets (1.1.0), com.mallowigi (36.0), org.intellij.plugins.hcl (0.7.10), org.jetbrains.plugins.go-template (211.6693.44), name.kropp.intellij.makefile (211.6693.108), org.sylfra.idea.plugins.linessorter (1.0.1), com.intellij.kubernetes (211.7142.13), idea.plugin.protoeditor (2.3.1), com.chrisrm.idea.MaterialThemeUI (6.4.0)
Kotlin: 211-1.4.32-release-IJ7142.27

**Comment by mallowigi** [comment]
Yes I noticed. I will fix it soon, it should be 28, not 18

**Comment by bjoernmayer** [comment]
Workaround is to set sidebar height to 28 :)

**Comment by IdkMan2** [comment]
It's so annoying, in my case after each update this issue occurs again and again.

**Comment by mallowigi** [comment]
sent an hotfix, please update

**Comment by IdkMan2** [comment]
> sent an hotfix, please update

I have just updated and can confirm that it's fixed now. Thank you so much for the fast replay and quick fix.
