### ISSUE TITLE
JavaScript keywords are highlighted when used as object keys

### ISSUE THREAD

**Issue by ddubrava** [ChrisRM/material-theme-jetbrains#1742]
### Summary

JavaScript keywords are highlighted when used as object keys

### Expected behavior

![image](https://user-images.githubusercontent.com/22116465/116877158-3c940380-ac26-11eb-8008-a8369d36e07e.png)
![image](https://user-images.githubusercontent.com/22116465/116878282-cf816d80-ac27-11eb-8430-1660addee8b0.png)
![image](https://user-images.githubusercontent.com/22116465/116878654-56364a80-ac28-11eb-892a-1e68317e29c7.png)
![image](https://user-images.githubusercontent.com/22116465/116878667-59313b00-ac28-11eb-9c1c-1181e7a2e26c.png)

### Actual behavior

No difference between these keys: type, import, name etc. They are all object's keys. But they are highlighted like keywords

![image](https://user-images.githubusercontent.com/22116465/116877073-1d957180-ac26-11eb-8d68-60fdce4be265.png)
![image](https://user-images.githubusercontent.com/22116465/116878252-c42e4200-ac27-11eb-9f50-0afbe9d702bd.png)

### Environment

WebStorm 2021.1
Build #WS-211.6693.108, built on April 5, 2021
Licensed to WebStorm Evaluator
Expiration date: May 31, 2021
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2042M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, editor.maximize.on.double.click=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.chrisrm.idea.MaterialThemeUI (6.4.0)

Material Theme UI version 6.4.0
Material Theme Darker, language additions + enforce highlighting are enabled

**Comment by ddubrava** [comment]
Same for typescript

![image](https://user-images.githubusercontent.com/22116465/116878128-91844980-ac27-11eb-9ca7-4e6caf94514a.png)

**Comment by mallowigi** [comment]
Thanks, will take a look
