### ISSUE TITLE
GitHub Student Pack

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ChrisRM/material-theme-jetbrains#1746]
On this page: https://www.material-theme.com/docs/pricing/
It says, that the plugin is free for students and teachers and those should write to the email address listed there to get their discount.
It would be very nice (although I don't know if this would even be possible) if this student status could simply verified by reading if the user is part of the GitHub Student Program, i.e. has access to the GitHub Student Pack.
Since JetBrains already uses the Program to verify a student's status and access, it could maybe be possible to configure this even in the Marketplace itself, although I don't know if that's possible. Otherwise, it may be possible via an external web page, which supplies License Keys when access to the Pack is granted.

This would also help minimizing email traffic (I also wrote an email, but didn't receive an answer yet and am looking forward to one :) ).

If this is out of scope, you can just ignore/close this issue.

**Comment by mallowigi** [comment]
This is a nice idea, I don't know if there is an API for this, but yeah I'll keep that in mind. That would ease off the list of mails i have to answer to, for sure.

**Comment by ThexXTURBOXx** [comment]
Thanks for appreciating this! :)

I actually found one reference in the Marketplace Paid Plugins FAQ to such stuff: https://plugins.jetbrains.com/docs/marketplace/license-types.html
Under "Free Licenses", there is a list of some types that should support students, teachers and even more people. I don't know too much about JetBrains plugins and especially licensing stuff, but maybe this gives you a good starting point!

P.S. Just received an answer, thank you very much :)

**Comment by mallowigi** [comment]
Yeah, I know about it, but I don't know if I can use it in the code. I know for sure that even if you have a student pack, JetBrains doesn't automatically grant you a free license for the plugin even though I checked the option in the Marketplace. I can ask JB for more info.

**Comment by HealerLu** [comment]
> On this page: https://www.material-theme.com/docs/pricing/
> It says, that the plugin is free for students and teachers and those should write to the email address listed there to get their discount.
> It would be very nice (although I don't know if this would even be possible) if this student status could simply verified by reading if the user is part of the GitHub Student Program, i.e. has access to the GitHub Student Pack.
> Since JetBrains already uses the Program to verify a student's status and access, it could maybe be possible to configure this even in the Marketplace itself, although I don't know if that's possible. Otherwise, it may be possible via an external web page, which supplies License Keys when access to the Pack is granted.
> 
> This would also help minimizing email traffic (I also wrote an email, but didn't receive an answer yet and am looking forward to one :) ).
> 
> If this is out of scope, you can just ignore/close this issue.

If possible could you tell me what is included in the email you wrote? I would also like to apply for a free student permit, thank you.

**Comment by mallowigi** [comment]
Also I just remembered that student licenses are related to one JB account, but you can use a different account for each plugin. I can try checking if we have information about the "main account" if there is such thing, but I'm not promising anything.

**Comment by mallowigi** [comment]
Closing this, as JetBrains told me they are working on a solution to incorporate Students and OpenSource packs to plugins.
