### ISSUE TITLE
Please do not revert my legacy settings that used to be free

### ISSUE THREAD

**Issue by LoganDark** [ChrisRM/material-theme-jetbrains#1747]
### Summary

I have been a long time user of Material Theme UI and have a really pretty settings file that I import into all my new installs of CLion. Recently, I got a new computer so I set up CLion, installed the plugin and imported all my settings. Everything worked fine on version 6.3, and even though I don't have a paid license yet, none of my customizations were overridden.

### Expected behavior

I get to keep my legacy settings and my blue accent color, even though I'm ok with it staying that way since you now need to pay to change it.

### Actual behavior

6.4 recently released, and upon updating to it, my accent color was immediately reverted to bright orange, and no amount of settings importing would fix it. Sideloading version 6.3 allowed me to re-import my accent color correctly.

I feel that this is a regression (well, an additional one) because I changed my accent color a long time ago before it was paid, and now I am being asked to pay or else have it **forcibly** reverted to the default.

### Environment

* OS: Windows 10
* IntelliJ Product + version: CLion 2021.1.1
* Plugin version: 6.4

**Comment by mallowigi** [comment]
True, the accent color is part of the free plan. I'll take a look.
