### ISSUE TITLE
A small issue when using Magnet for MacOS

### ISSUE THREAD

**Issue by yurique** [ChrisRM/material-theme-jetbrains#1748]
### Summary

When using the the Magnet app: https://magnet.crowdcafe.com to resize the IDEA window, if before the resize the top toolbar contained 2 rows, after maximizing the window the second row remains (empty).

### Expected behavior

The top toolbar is resized to a single row, no blank space under it.

### Actual behavior

The top tool bar has two rows, second one being blank.

### Steps to reproduce (if needed)

1. resize the IDEA window down to the size when the top toolbar needs a second row to contain the icons
2. maximize the IDEA window using the "Maximize" shortcut of the Magnet app (or "Maximize" item in its menu)
3. the top toolbar has a second, blank, row
3. manually resize the window a bit down and then back to full screen
4. the top toolbar is back to normal

A screen recording:

https://user-images.githubusercontent.com/919230/117369110-1e9bfc80-aecd-11eb-827b-71f555a83af9.mp4

### Environment

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to ...
Subscription is active until December 26, 2021.
Runtime version: 11.0.10+9-b1341.35 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry: ide.new.stripes.ui=true, ide.balloon.shadow.size=0, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: org.intellij.plugins.postcss (211.6693.64), com.mallowigi (36.0), name.kropp.intellij.makefile (211.6693.108), pro.bashsupport (1.5.17.211), com.jetbrains.lang.ejs (211.6693.65), com.chrisrm.idea.MaterialThemeUI (6.4.1), org.intellij.scala (2021.1.373), com.intellij.lang.jsgraphql (2.9.1), Pythonid (211.6693.115), org.jetbrains.plugins.go (211.6693.111), net.ashald.envfile (3.2.1), ru.adelf.idea.dotenv (2021.1)
Kotlin: 211-1.4.32-release-IJ6693.72

[material-theme-config-files.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6437713/material-theme-config-files.zip)

**Comment by mallowigi** [comment]
Interesting, but I'm not sure that's something related to the plugin. Could you try without the plugin to see if that reproduces?

**Comment by yurique** [comment]
Ha, you're right! This does happen with a clean install as well.

Not even sure what made me so sure it was related to the Material Theme :) (maybe I first noticed this right after the plugin got an update or something like that 🤔).

I'll report this to JetBrains.

**Comment by mallowigi** [comment]
To be fair I don't think this is related to JetBrains either. From what I can see with your screen, the IDE has a resize listener that puts the toolbar in two lines when the screen resizes, but the magnet app probably uses another mechanism for resizing. I have the same issue with BetterTouchTool.

**Comment by yurique** [comment]
Good point. Although this wasn't happening before not so long ago.
