### ISSUE TITLE
Material oceanic list background and secondary color issue

### ISSUE THREAD

**Issue by Abdelraman** [ChrisRM/material-theme-jetbrains#1749]
Material oceanic list background and secondary color issue, makes suggestion very difficult to see kindly check the difference between the 2 images, the first for the latest version (paid version) the other which is much more better for an older version. Thanks for your efforts
![image](https://user-images.githubusercontent.com/4821833/117390949-54ea7380-aeef-11eb-81cb-1b65d51f3fc1.png)
![Screenshot 2021-04-10 225347](https://user-images.githubusercontent.com/4821833/117390968-5caa1800-aeef-11eb-9d84-ad9bd02aa1e3.jpg)

**Comment by mallowigi** [comment]
I also noticed that something has changed! Glad to see I wasn't seeing things.

**Comment by Abdelraman** [comment]
Can we have a quick fix for that or shall we wait for the next version ?
Thanks for your work.

**Comment by mallowigi** [comment]
I don't think I'll do another release for now, maybe on Sunday if I find the issue.

**Comment by mallowigi** [comment]
Just found out that the "unfocused selection" has been deprecated at some point. That also explains the similar issue in the Material UI Lite.

I'll have no choice but to change the color of the "focused selection".

This might take a while, as I need to adapt to all themes.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/117540742-3c767800-b019-11eb-8314-1e3bcdde23f6.png)
![image](https://user-images.githubusercontent.com/5015756/117540743-40a29580-b019-11eb-88b2-d430197c4314.png)

Which option is better?

**Comment by mallowigi** [comment]
That was my first options but because we have no shadows it would be blending with the background which is less than ideal (it's already happening with the menus and I hate it)

**Comment by mallowigi** [comment]
But yeah everyone prefers the first option (it's what's implemented in vscode as well), now I need to see if it renders well in all themes

**Comment by Abdelraman** [comment]
Thanks mallowigi, is there will be any update to install for this issue ?

**Comment by Abdelraman** [comment]
Hello Mallowigi, kindly check the difference between the two screen, after installing the new updates, suggestion on typing has this highlight color

![image](https://user-images.githubusercontent.com/4821833/118350876-36245680-b559-11eb-9a03-b09d5a086aee.png)

but on clicking the below selection the highlight color changes

![image](https://user-images.githubusercontent.com/4821833/118350923-5e13ba00-b559-11eb-97ef-be7658524d15.png)

**Comment by Abdelraman** [comment]
the second one is much more better and readable

**Comment by Abdelraman** [comment]
the same for file search as in the pic below, has a different highlight color

![image](https://user-images.githubusercontent.com/4821833/118351289-6836b800-b55b-11eb-974c-a98cd66e8dd3.png)

**Comment by mallowigi** [comment]
> the same for file search as in the pic below, has a different highlight color
> 
> ![image](https://user-images.githubusercontent.com/4821833/118351289-6836b800-b55b-11eb-974c-a98cd66e8dd3.png)

I won't change that. The lines are readable enough, it's not like the completion popup.

**Comment by Abdelraman** [comment]
yes, just wanted to maintain consistency between the whole app

**Comment by mallowigi** [comment]
I'm starting to regret my decision... I think I'll restore the old behaviour but introduce a setting to choose a specific style

**Comment by Abdelraman** [comment]
Why do you regret the changes, it is much more better specially the drop down list except what was mentioned about the first selection
