### ISSUE TITLE
Allow drag&drop for striped tool window tiles

### ISSUE THREAD

**Issue by Lootwig** [ChrisRM/material-theme-jetbrains#1750]
### Summary

Currently, the striped tool window tiles can only be moved around through the right click -> "Move" dialog. The native IDE's version can simply be dragged with the mouse.

### Environment

IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Licensed to David Schneider
Subscription is active until December 26, 2021.
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 8042M
Cores: 24
Registry: ide.new.stripes.ui=true, actionSystem.force.alt.gr=true, ide.balloon.shadow.size=0, go.run.processes.with.pty=false
Non-Bundled Plugins: CMD Support (1.0.5), com.giancarlocode.built-value-snippets (1.2.0), com.mallowigi (36.0), org.jetbrains.plugins.localization (211.6693.44), org.jetbrains.plugins.rest (211.6693.44), mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), Dart (211.7233), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), io.flutter (56.0.5), de.mariushoefler.flutter_enhancement_suite (1.5.0), com.chrisrm.idea.MaterialThemeUI (6.4.1), izhangzhihao.rainbow.brackets (6.17), Pythonid (211.7142.45), org.exbin.deltahex.intellij (0.2.4), org.jetbrains.plugins.go (211.7142.36), idea.plugin.protoeditor (2.3.1)
Kotlin: 211-1.5.0-release-759-IJ6693.72

**Comment by Rasool-deldar** [comment]
Please add drag & drop to tiles. This new version does not have this feature.
![image](https://user-images.githubusercontent.com/58503211/127808855-d51f3b04-8130-49df-886e-ee205dec1606.png)

**Comment by mallowigi** [comment]
It's not possible at the moment, sorry about that.
