### ISSUE TITLE
Bold property in Color Scheme settings is not applied

### ISSUE THREAD

**Issue by Jakumozo** [ChrisRM/material-theme-jetbrains#1751]
### Summary

Wherever keywords should be bold (set in Color Scheme settings), they are not bold. Happened after the update.
![Screenshot_2](https://user-images.githubusercontent.com/25872559/117551992-91ce7b80-b051-11eb-98ed-98c4772f93f0.png)

### Environment
WebStorm 2021.1.1
Build #WS-211.7142.46, built on April 30, 2021
Windows 10 10.0
Material Theme UI 6.4.1

**Comment by Jakumozo** [comment]
> Wow I really thought this was a bug I was going crazy, but it's not. To change this value you have to look in Javascript > Exported Class, not Class.

`Exported class` is inherited from `Class`. But even if not and set to be `Bold`, this still does not work. I have also tried other schemes and `Bold` is not applied to any of them.
![Screenshot_3](https://user-images.githubusercontent.com/25872559/117565892-6634ab00-b0bc-11eb-8f40-e8698210ce71.png)

**Comment by mallowigi** [comment]
Is bold not working for any of the keys?

**Comment by Jakumozo** [comment]
Yes, I have tried it on numbers, strings, braces, but bold is applied nowhere. I worked well before the update. I updated both `Webstorm` and `Material UI`, so not sure, is the IDE can be the problem.

**Comment by mallowigi** [comment]
There could be a problem with the font. What font are you using. And what antialiasing?

**Comment by Jakumozo** [comment]
I use `Inconsolata`. I have now tried all the others, but `Bold` never applied to them either. Is `antialiasing` set somewhere in `Webstorm`?

**Comment by mallowigi** [comment]
In Appearance setting, there is an antialiasing option. Check that you use Greyscale

**Comment by Jakumozo** [comment]
It was set as `Subpixel`, I have tried both and it did not help :(
Is there something else I can try?

**Comment by mallowigi** [comment]
I just checked with my version of Inconsolata and it worked fine... Also, please check with the plugin disabled and see if that reproduces.

**Comment by Jakumozo** [comment]
It seems the problem persists without the plugin. So, I guess it can be related to the IDE itself?
