### ISSUE TITLE
Keyword highlight overwrites instance method highlight

### ISSUE THREAD

**Issue by Jakumozo** [ChrisRM/material-theme-jetbrains#1753]
### Summary
Keywords color scheme overwrites instance method color scheme, if the name of the method matches one of the keywords.
![Screenshot_9](https://user-images.githubusercontent.com/25872559/117728915-c2015000-b1f2-11eb-8aca-5880fe76510c.png)

### Expected behavior

Instance method color scheme is not overwritten.

### Actual behavior

Instance method color scheme is overwritten.

**Comment by mallowigi** [comment]
Duplicate of #1742
