### ISSUE TITLE
Github theme "Checked out new branch" notification balloon has green text on green background

### ISSUE THREAD

**Issue by garethellis36** [ChrisRM/material-theme-jetbrains#1755]
I'm using the `Github (Material)` theme on the premium version (6.4.1). IntelliJ version is 2021.1.1.

This notification balloon is very hard to read because the text is green-on-green:
![image](https://user-images.githubusercontent.com/6451455/117814691-8602d500-b25c-11eb-9156-104162678b99.png)

This appears after checking a new VCS branch within the IDE.

**Comment by garethellis36** [comment]
Hello, I see this is marked as completed, but I still have this issue today. I'm on v7.11.0 of the plugin and IntelliJ 2022.2.3.

**Comment by mallowigi** [comment]
This repository is now archived, please use the new repository.
