### ISSUE TITLE
Add gruvbox themes

### ISSUE THREAD

**Issue by mbrito-yieldstreet** [ChrisRM/material-theme-jetbrains#1758]
[Gruvbox][1] is a gorgeous color scheme that would make a good addition to the Material Theme family. There is [another plugin][2] available that works mostly fine, but could do with a few tweaks.

[1]: https://github.com/morhetz/gruvbox
[2]: https://plugins.jetbrains.com/plugin/12310-gruvbox-theme

**Comment by mallowigi** [comment]
Sorry but I'm not planning to add more themes at the moment as it increases my working load for quite a lot and I have other priorities for now.

But I can invite you to make it yourself using the Material Theme UI extension perhaps :)

**Comment by mbrito-yieldstreet** [comment]
@mallowigi that's fair enough. I'll see what I can do when I get some free time myself :)
