### ISSUE TITLE
Use editor font by default

### ISSUE THREAD

**Issue by mbrito-yieldstreet** [ChrisRM/material-theme-jetbrains#1759]
### Summary
My most common reason to override a material color scheme is to disable the "Use color scheme font insead of the default" and "Use console font instead of the default" options. If these options were unchecked by default, I could leave all color schemes untouched, meaning I woldn't need to reset them after an upgrade.

### Expected behavior
"Use color scheme font instead of the default" and "User console font instead of the default" are unchecked by default, allowing users to use their chosen font without having to modify Material Theme color schemes.

### Actual behavior
These options are checked by default, requiring users to modify the color scheme (and reset them after an upgrade) just to use a different font.

**Comment by mallowigi** [comment]
I have a similar issue as well, I had in my backlog to be able to override the editor font through a setting, but I forgot about it. Maybe your solution is better.
