### ISSUE TITLE
Wrong default color in Arc Dark theme made the selected item could not be identified

### ISSUE THREAD

**Issue by zgr0629** [ChrisRM/material-theme-jetbrains#1761]
### Summary

"List Background Color" and "Highlight Colors" have same default value in Arc Dark theme made the selected item could not be identified.

![image](https://user-images.githubusercontent.com/5328562/119311277-71363080-bca3-11eb-82ce-97a822ecd809.png)

![image](https://user-images.githubusercontent.com/5328562/119311211-5bc10680-bca3-11eb-86c1-eeebadf3175d.png)

### Environment

material theme version: 6.5.0.1

**Comment by mallowigi** [comment]
fixed for next verison
