### ISSUE TITLE
Remove text or text background from "Project Frame Color" 

### ISSUE THREAD

**Issue by ctrlok** [ChrisRM/material-theme-jetbrains#1762]
### Summary

I'm using the Project Frame Color option and I have text on white background in the middle of the colored stripe. It will be nice to have option to remove this text and background while it's duplicate of title that already exist

### Steps to reproduce (if needed)

1. Enable Project Frame Color option
![CleanShot 2021-05-24 at 22 23 45@2x](https://user-images.githubusercontent.com/3265316/119397424-c0e61d80-bcde-11eb-9cf0-8fbe99bb33f4.png)

**Comment by mallowigi** [comment]
done for next version
