### ISSUE TITLE
how can I edit the notification background color?

### ISSUE THREAD

**Issue by Snax1210** [ChrisRM/material-theme-jetbrains#1764]
### Summary

how can I edit the notification background color?

### Expected behavior

...

![image](https://user-images.githubusercontent.com/31029217/119756097-9d38f800-bed5-11eb-93dc-127cf7d70463.png)

**Comment by mallowigi** [comment]
Which theme?

**Comment by Snax1210** [comment]
GitHub Dark

**Comment by cam2411** [comment]
Unsubcribe

**Comment by mallowigi** [comment]
Can you tell me how to reproduce?

**Comment by Snax1210** [comment]
The notification is "Re-run Spring Boot Annotation Processor to update generated metadata". Sorry I don't know how to reproduce,that is a private project.

**Comment by mallowigi** [comment]
I'm closing this since I don't know how to reproduce. I've checked all the color schemes color and I can't seem to find it.

**Comment by Snax1210** [comment]
Just add a annotation : "@ConfigurationProperties" on the Spring Java class

**Comment by Snax1210** [comment]
but I can't find how to edit the color schemes

**Comment by mallowigi** [comment]
reproduced

**Comment by Snax1210** [comment]
Awesome！
