### ISSUE TITLE
Version {0} in menu you say?

### ISSUE THREAD

**Issue by Adriansun** [ChrisRM/material-theme-jetbrains#1765]
IntelliJ (latest stable) with Material Theme UI (latest stable) go to "Help" menu and see that you can see what is in the latest version {0} of Material Theme UI. Is it suppose to be {0}? If yes then what does the {0} mean?

See picture. 

![Material Theme UI 01](https://user-images.githubusercontent.com/9981908/120035956-ae7e2380-bfff-11eb-942e-07a4101b65e3.png)

**Comment by Adriansun** [comment]
Yes. Windows 10, if that is what you mean.

**Comment by mallowigi** [comment]
Sorry, I don't have windows at the moment. I don't know why this has been added to the help menu, but this doesn't happen in Mac at least.

Also, what is the IDE/version ?

**Comment by Adriansun** [comment]
![Uploading versionIntellij.png…]()

**Comment by Adriansun** [comment]
![versionIntellij](https://user-images.githubusercontent.com/9981908/120056097-6b8d7180-c03a-11eb-918b-67b6cfb8c130.png)

**Comment by mallowigi** [comment]
fixed for next version
