### ISSUE TITLE
Change Notes not displaying properly in Plugins dialog for 6.5.1-2021.2 update

### ISSUE THREAD

**Issue by cknoblauch** [ChrisRM/material-theme-jetbrains#1768]
### Summary

Change Notes not populated for 6.5.1-2021.2 update.

### Expected behavior

For the change notes of the latest version to be shown properly on the Plugin Updates dialog.

### Actual behavior

The Change Notes has this mesage instead of the actual changes:

>  This is the change notes, but it will be overriden by Changelog.md

![image](https://user-images.githubusercontent.com/2798915/120205679-9e816200-c200-11eb-88a1-8201f8278ef8.png)

### Steps to reproduce (if needed)

1. Install Material Theme UI plugin on IntelliJ < 2021.2
2. Upgrade IntelliJ to 2012.2 (EAP at this point)
3. Start IntelliJ again and open the Plugin Settings to see the available Material Theme UI plugin update to 6.5.1-2021.2. The Change Notes display incorrectly.

### Environment

- OS: Linux 5.4.118-1-manjaro
- IntelliJ IDEA 2021.2 EAP (Community Edition), Build #IC-212.3116.43, built on May 27, 2021
- Non-Bundled Plugins: com.chrisrm.idea.MaterialThemeUI (6.5.0.1)

**Comment by mallowigi** [comment]
fixed for next version
