### ISSUE TITLE
material theme with android studio

### ISSUE THREAD

**Issue by 3xiaoxiao3** [ChrisRM/material-theme-jetbrains#1769]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

The icons are not aligned

### Expected behavior

![QQ图片20210603202917](https://user-images.githubusercontent.com/59803722/120644934-79178100-c4aa-11eb-8dba-172bcb53069b.png)

### Actual behavior

![QQ图片20210603202606](https://user-images.githubusercontent.com/59803722/120645016-8df41480-c4aa-11eb-9159-7bad767ced82.png)

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

### Environment
Android Studio Arctic Fox | 2020.3.1 Beta 3
Build #AI-203.7717.56.2031.7395685, built on May 25, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 6
Registry: ide.intellij.laf.enable.animation=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Statistic, com.alibaba.p3c.smartfox, com.codota.csp.intellij, leetcode-editor, org.jetbrains.kotlin, com.moxun.plugin.s2v, com.squareup.sqldelight, com.mallowigi.idea

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
How to reproduce?

**Comment by 3xiaoxiao3** [comment]
> How to reproduce?

if you use Material Theme in Android Studio 4.1+,you`v see that bug in the layout Interface

**Comment by mallowigi** [comment]
I don't, that's why I ask. In any case this looks like an issue with trees. The image you showed looks like a tree just like the Project View.

https://www.material-theme.com/docs/configuration/project-view-settings/

In this link you can see all settings related to tree. I'm afraid you will need to change the indent and height to the original ones.

**Comment by 3xiaoxiao3** [comment]
> I don't, that's why I ask. In any case this looks like an issue with trees. The image you showed looks like a tree just like the Project View.
> 
> https://www.material-theme.com/docs/configuration/project-view-settings/
> 
> In this link you can see all settings related to tree. I'm afraid you will need to change the indent and height to the original ones.

![QQ图片20210604222611](https://user-images.githubusercontent.com/59803722/120817056-f06d1380-c583-11eb-9072-7c7f42c01af6.png)
It`s in the component tree,I dont know how to change the indent and height in that interface
if you create a layout in android studio you`v see that issue

**Comment by mallowigi** [comment]
If you open the Material Theme UI Settings (check the link I sent), you would see the options related to the Project Tree. Try to change them and see if that fixes it.

**Comment by 3xiaoxiao3** [comment]
> If you open the Material Theme UI Settings (check the link I sent), you would see the options related to the Project Tree. Try to change them and see if that fixes it.

that won`t change the hight of these eyes,only change the hight of tree

**Comment by 3xiaoxiao3** [comment]
I found that setting but there`s another question
![QQ图片20210604232932](https://user-images.githubusercontent.com/59803722/120826379-f4e9fa00-c58c-11eb-90e5-1ecbfcd4bb82.png)
some of them are so small and some of them are so big

**Comment by 3xiaoxiao3** [comment]
> If you open the Material Theme UI Settings (check the link I sent), you would see the options related to the Project Tree. Try to change them and see if that fixes it.

I found that setting but there`s another question
![QQ图片20210604232932](https://user-images.githubusercontent.com/59803722/120896506-7193db80-c654-11eb-9801-5979ed9724fc.png)
some of them are so small and some of them are so big
