### ISSUE TITLE
Error in PicoPlugin

### ISSUE THREAD

**Issue by Jactaen** [ChrisRM/material-theme-jetbrains#177]
Just updated to 0.18 and get this in my console - running newest EAP PHPStorm:

```
10:52:58 PicoPluginExtensionInitializationException
         Cannot load java class com.intellij.psi.PsiClass
         ---- Debugging information ----
         message             : Cannot load java class com.intellij.psi.PsiClass
         class               : com.chrisrm.idea.icons.PsiElementAssociation
         required-type       : com.chrisrm.idea.icons.PsiElementAssociation
         converter-type      : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
         path                : /associations/associations/psi
         line number         : 75
         class[1]            : java.util.ArrayList
         converter-type[1]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
         class[2]            : com.chrisrm.idea.icons.Associations
         version             : 1.4.8
         -------------------------------
```

**Comment by ChrisRM** [comment]
Yeah, got it myself. I'm on it

**Comment by Jactaen** [comment]
If you need anything let me know what I can provide to you

**Comment by ChrisRM** [comment]
@Jactaen Can you please try the newest build and let me know how it goes?

**Comment by Jactaen** [comment]
@ChrisRM Im not sure how to manually install this, just installed it through the plugin installer in PHPStorm - can you provide some information about how to install?

**Comment by Kurre** [comment]
Latest build is now available through Plugin Repositories (version 0.1.8).
In case of doubt, just uninstall, restart and reinstall "Material Theme UI" plugin.

For manual installation, see: #180 

PS. I ain't seeing these errors anymore with the latest release :+1:

**Comment by Jactaen** [comment]
Seems like reinstall did the trick with the new build :)

**Comment by ChrisRM** [comment]
Cool, thanks for testing 👍
