### ISSUE TITLE
Unused variable is not clearly visible and readable

### ISSUE THREAD

**Issue by Ayanrocks** [ChrisRM/material-theme-jetbrains#1775]
### Summary

Not readable when declaring an unused variable in goland
### Expected behavior

Variable should be pretty clear to read while maintaining visuals to denote it's not used anywhere

### Actual behavior

Variable is not readable at all

### Steps to reproduce (if needed)
1. declare an unused variable

<img width="171" alt="Screenshot 2021-05-31 at 5 59 44 PM" src="https://user-images.githubusercontent.com/11027998/121300780-e85efc00-c914-11eb-92c6-4d388b92cecf.png">

GoLand 2021.1.2
Build #GO-211.7442.27, built on May 25, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.completion.variant.limit=500, documentation.show.toolbar=true, ide.new.stripes.ui=true, suggest.all.run.configurations.from.context=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: net.vektah.codeglance (1.5.4), zielu.gittoolbox (203.5.10), mobi.hsz.idea.gitignore (4.1.0), com.chrisrm.idea.MaterialThemeUI (6.5.0.1)

**Comment by mallowigi** [comment]
I am aware of this issue, it's even more pronounced for the Darker theme. IMO I need to change the color of the unused variables, perhaps make them slightly more white/less gray
