### ISSUE TITLE
The color of this scroll bar does not seem to be customizable

### ISSUE THREAD

**Issue by tlerbao** [ChrisRM/material-theme-jetbrains#1776]
The color of this scroll bar does not seem to be customizable
![image](https://user-images.githubusercontent.com/20442232/121313674-338b0600-c939-11eb-935b-83225bfd43cf.png)

**Comment by mallowigi** [comment]
Try to toggle the settings "Themed Scrollbars" or "Accent scrollbars"

https://www.material-theme.com/docs/configuration/component-settings/#transparent-scrollbars-and-accent-scrollbars

**Comment by tlerbao** [comment]
There is another small problem. I don’t know if you noticed that the scroll bar is not completely transparent, but a darker color than the left side. I don’t know if phpstorm is designed in this way or is a historical issue.
![image](https://user-images.githubusercontent.com/20442232/121455143-91216000-c9d6-11eb-94b1-aa8c0ccb6f01.png)

**Comment by mallowigi** [comment]
This is customizable via the "Accent Scrollbars" setting.

**Comment by mallowigi** [comment]
However I just found out that the setting doesn't apply right away, but only after changing the current theme. I'll fix it.

**Comment by tlerbao** [comment]
@mallowigi Excuse me, has the problem of the background color of the scroll bar on the left been fixed? Where do I set it up?
