### ISSUE TITLE
A small problem when the "themed title bar" is turned on

### ISSUE THREAD

**Issue by tlerbao** [ChrisRM/material-theme-jetbrains#1777]
When the "themed title bar" is turned on, there is no border line near the tab (or is it called the background color?). I think it should look perfect like Figure 2 (OCD), which was edited by Photoshop.

![image](https://user-images.githubusercontent.com/20442232/121346208-6690c200-c958-11eb-8ab5-409742bc91a8.png)

like this...
![1111](https://user-images.githubusercontent.com/20442232/121347162-7230b880-c959-11eb-8116-8ed43351fc52.png)

**Comment by mallowigi** [comment]
Are you talking about the borders over the tabs? I'm not a big fan of this idea...

**Comment by tlerbao** [comment]
Oh, just a small suggestion. I think there is a border on the left and no border on the right tab, which feels a bit abrupt.
