### ISSUE TITLE
Cannot set SDK in project settings 

### ISSUE THREAD

**Issue by mikelhamer** [ChrisRM/material-theme-jetbrains#1778]
### Summary
The "Add SDK" button in project settings does not expand into the arrow options when hovered over or clicked when the Material theme is enabled.

### Expected behavior
Add SDK should show arrow options when hovered over or clicked

### Actual behavior
Hovering over or clicking Add SDK does nothing

### Steps to reproduce (if needed)

1. Open new project without SDK specified
2. Go to project settings -> project
3. Try to set the SDK

![Screen Shot 2021-06-09 at 11 54 42 PM](https://user-images.githubusercontent.com/10012080/121466726-e1240680-c985-11eb-8c00-a668ea205ca8.png)

### Environment
IntelliJ IDEA 2021.1.2 (Ultimate Edition)
Build #IU-211.7442.40, built on May 31, 2021
Runtime version: 11.0.11+9-b1341.57 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.chrisrm.idea.MaterialThemeUI (6.6.0)
Kotlin: 211-1.4.32-release-IJ7442.2

**Comment by mallowigi** [comment]
Fixed

**Comment by mikelhamer** [comment]
Awesome!
