### ISSUE TITLE
Android Studio 2.0 stable Font not save

### ISSUE THREAD

**Issue by ghost** [ChrisRM/material-theme-jetbrains#178]
sorry , i don say english
首先我十分喜欢作者的主题,感谢作者的付出
问题是:
at Android Studio 2.0 下,IDE 字体 选择 微软雅黑 , 然后 关闭 IDE 重启
IED 重启 后 , 字体 就被 重置 了 一样 不是 微软雅黑 了
这个 问题 在 IDEA 16 也 存在.
希望 作者 能 解决
thank!

**Comment by rascafr** [comment]
I got

**Comment by rascafr** [comment]
I have the same problem :(

**Comment by Thisdk** [comment]
@rascafr now is fix the bug , Ha-ha

**Comment by rascafr** [comment]
Sure? :smile:

**Comment by denofevil** [comment]
Duplicates #54
