### ISSUE TITLE
When turn on "Striped tool windows", move tools windows to left or right doesnt work.

### ISSUE THREAD

**Issue by gerryhjs** [ChrisRM/material-theme-jetbrains#1782]
Plugin version:6.6.0
IDE version:idea 2021.1

**Comment by mallowigi** [comment]
You can only right click and select what you want

**Comment by gerryhjs** [comment]
I did this,but after I select only the tool button changed,tools windows doesnt change position

**Comment by mallowigi** [comment]
To change position you need to select it on the tool window settings itself, not the stripe

![image](https://user-images.githubusercontent.com/5015756/123524138-ea74d900-d6d0-11eb-99ca-28ad1d49248b.png)
