### ISSUE TITLE
安装了material-theme-jetbrains插件后，原生主题显示有问题。

### ISSUE THREAD

**Issue by ranbest** [ChrisRM/material-theme-jetbrains#1783]
安装了material-theme-jetbrains插件后，自带浅色主题显示有问题。
按钮鼠标移上去背景变黑了。
然后 tab标签高度变高了

**Comment by mallowigi** [comment]
你有截图吗？

**Comment by ranbest** [comment]
> 你有截图吗？
1.png  是禁用插件效果， 2.png 是启用插件效果。
1、主题都是官方主题 IntelliJ Light。鼠标移到按钮（下拉框）都会闪几下，而且变黑了。
2、还有，Debugger那个tab高度好像变高了，这个高度咱们的主题有配置吗？
3、浅色主题，咱们能不能再提供几个可预选主题（配色），比如，绿豆沙色

1.png:
![1.png](https://user-images.githubusercontent.com/15650275/122721102-d4b37e00-d2a2-11eb-83a7-c56e5b8334d3.png)

2.png:
![2.png](https://user-images.githubusercontent.com/15650275/122721127-e09f4000-d2a2-11eb-9cf6-5c20eb3e72e2.png)

**Comment by ranbest** [comment]
> 你有截图吗？
三楼已发

**Comment by mallowigi** [comment]
I'm not speaking chinese, but from what I can see this is a known issue happening when switching themes. Usually a restart should fix the issue.

**Comment by ranbest** [comment]
1、Well, restart doesn't seem to solve it.
2、I suggest adding two light color themes or color scheme ，Less red color, so that the code doesn't seem to have problems
