### ISSUE TITLE
Angular icon appears on wrong format

### ISSUE THREAD

**Issue by NawafSwe** [ChrisRM/material-theme-jetbrains#1784]
Hi, Thank you for the nice plugin I am really enjoying it. 
I noticed when I create a file in this format ``function.controller.js`` it understand it as angular file and add angular icon. 
is there any future fixes for this issue? Regardless file.controller or file.router ect. it gives angular icon in the file. 

#Screenshot 
<img width="607" alt="Screen Shot 2021-06-21 at 11 09 31 AM" src="https://user-images.githubusercontent.com/35840833/122728961-52ff2880-d281-11eb-832c-d01fbf74cab1.png">

### Environment
* OS (Windows, Linux, Mac) --> MAC
* IntelliJ Product + version (IDEA, RubyMine...) ---> WebStorm 
* Plugin version --> 6.60
* Plugin configuration (found in material_theme.xml) -->  cloud not find it. 
* If needed a list of enabled plugins NONE
* Material Theme Plugin version --> 6.60

**Comment by mallowigi** [comment]
Its' to be expected, but you can override it with a custom association.

**Comment by NawafSwe** [comment]
How?

**Comment by mallowigi** [comment]
Please check in the Atom Material Icons project's README.
