### ISSUE TITLE
Title bar uses wrong LAF

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ChrisRM/material-theme-jetbrains#1787]
### Summary

It looks like IntelliJ for some reason uses the Metal LAF (or similar) for the title bar when Material Theme UI is activated since the new 2021.2 EAP 6 released today.

Also, since 2021.2 EAP 2 or something, the bar under the title bar just mirrors some part of the screen (also seen on the screenshot

### Steps to reproduce (if needed)

1. Install IntelliJ 2021.2 EAP 6 and the newest version of Material Theme UI
2. Start it and see the title bar change
3. Deactivate it again and the title bar is back to default (without bugs)

### Environment

It should contain:
* OS: Windows 10
* IDEA 2021.2 EAP 212.4535.15
* Plugin version: 6.6.0-2021.2

### Screenshot

![grafik](https://user-images.githubusercontent.com/12763829/124027306-fde6b380-d9f2-11eb-8141-2bcb46cafcfb.png)

**Comment by Atulin** [comment]
Was just about to report the same
![image](https://user-images.githubusercontent.com/11233299/124286728-88dcc080-db4f-11eb-8281-bd5146ac8b40.png)
![image](https://user-images.githubusercontent.com/11233299/124286744-8b3f1a80-db4f-11eb-9f51-07573bfceddb.png)

**Comment by mallowigi** [comment]
fixed
