### ISSUE TITLE
Window "Move to" incorrect options

### ISSUE THREAD

**Issue by asonnleitner** [ChrisRM/material-theme-jetbrains#1789]
### Summary

When I have an open window (Terminal for example) and want to move the window I click on the 3 dots and hover over _Move to_ I get only 2 available options and that is Left and Right. So to get the correct options I have to disable the Striped Tool Windows feature and repeat the mentioned steps from above and get the correct options.

### Expected behavior

The correct behavior of the available positions should be Left Top, Left Bottom, Bottom Left, Bottom Right, Right Bottom, Right Top, Top Right, Top Left

![screenshot](https://i.imgur.com/bioRQzw.png)

### Actual behavior

I only get Left or Right 

![screenshot](https://i.imgur.com/mY6cIuI.png)

### Steps to reproduce (if needed)

1. Click 3 dots at window
2. Hover over _Move to_
3. View options

### Environment

WebStorm 2021.1.1
Build #WS-211.7142.46, built on April 30, 2021
Licensed to Andreas Sonnleitner
Subscription is active until January 6, 2022.
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 16
Registry: ide.new.stripes.ui=true, ide.balloon.shadow.size=0, js.debugger.webconsole=false, ide.images.show.chessboard=true
Non-Bundled Plugins: Key Promoter X (2021.1.1), String Manipulation (8.15.203.000.3), bundled-webstorm-help (211.7142.46), com.sunq.action.WebStormPX2REMTools (2.1.3), org.intellij.plugins.postcss (211.6693.64), com.mallowigi (36.0), com.therdnotes.aws-lambda-deployer (2021.1), in.thekalinga.snippet.intellij (6.1.0), io.techtrails.intellij.prisma (1.0.3.201), net.seesharpsoft.intellij.plugins.csv (2.17.0), zielu.gittoolbox (203.5.10), mobi.hsz.idea.gitignore (4.1.0), AWSCloudFormation (211.6693.108), com.intellij.kubernetes (211.7142.13), org.toml.lang (0.2.149.3939-211), quokka.js (1.0.303), wallaby.js (1.0.216), aws.toolkit (1.27-211), jones.restarteslintaction.restart-eslint-action (0.0.1), tv.twelvetone.intellij.plugins.intellivue (1.1.5), com.chrisrm.idea.MaterialThemeUI (6.6.0), com.intellij.lang.jsgraphql (2.9.1), izhangzhihao.rainbow.brackets (6.18), ru.adelf.idea.dotenv (2021.2)

**Comment by mallowigi** [comment]
That's the old behavior, it's no longer relevant with the striped tool windows.
