### ISSUE TITLE
Exception rejoining tabs in PHPStorm with paid version 6.7.2

### ISSUE THREAD

**Issue by vgsystems** [ChrisRM/material-theme-jetbrains#1792]
### Summary
IDE Fatal Error when rejoining tabs. Exception in plugin Material Theme UI 6.7.2

### Expected behavior
No exception should be fired.

### Actual behavior
Exception fired in PHPStorm. Also, it's happening since 3 or 4 versions before.

### Steps to reproduce (if needed)

1. First step: Split a view into two tabs.
2. Second step: Rejoin tabs with mouse
3. Third step: Exception fired.

<img width="1348" alt="exception_material" src="https://user-images.githubusercontent.com/7352160/124754757-dcbe1f80-df2a-11eb-9d94-949013522b18.png">

### Environment

PhpStorm 2021.1.4
Build #PS-211.7628.25, built on June 30, 2021
Subscription is active until February 15, 2022.
Runtime version: 11.0.11+9-b1341.60 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: debugger.watches.in.variables=false, run.processes.with.pty=TRUE, ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: com.mallowigi (36.0), com.xiaobing1024.laravel (1.1.1), com.intellij.plugins.html.instantEditing (211.6693.111), com.github.inxilpro.intellijalpine (v0.4.0), com.chrisrm.idea.MaterialThemeUI (6.7.2), de.espend.idea.laravel (0.15.4), de.espend.idea.php.annotation (8.0.0), fr.adrienbrault.idea.symfony2plugin (0.23.209), ru.adelf.idea.dotenv (2021.2)

### Attached files

Added error trace logs.

[introduced.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/6776924/introduced.txt)
[stacktrace.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/6776925/stacktrace.txt)

**Comment by mallowigi** [comment]
Can't reproduce. Is it happening in last version?

**Comment by vgsystems** [comment]
I can confirm that it's solved in the last version of the IDE + Theme. Also, before I updated the environment, two exceptions blew up. See attached.
![exception2](https://user-images.githubusercontent.com/7352160/128169836-5a1ac039-3b0a-4293-a09d-f534f62b41f6.png)
![exception](https://user-images.githubusercontent.com/7352160/128169845-11deb455-c72c-4c80-be37-745887163f25.png)
