### ISSUE TITLE
Material Theme UI plugin not available on Code With Me Guest

### ISSUE THREAD

**Issue by OljaKli** [ChrisRM/material-theme-jetbrains#1795]
Due to the dependency on `com.intellij.modules.lang` plugin becomes unavailable at Client side.
Please clarify why the dependency is needed?

To solve the issue:
- the dependency should be made optional;
- all the dependent code should be extracted to the dependent part. 

The issue in our bug tracker:
https://youtrack.jetbrains.com/issue/CWM-3226
please feel free to comment. Thank you

**Comment by mallowigi** [comment]
Is it something currently reproducible? Or should I wait for the release version? I had a similar problem with vcs features.
