### ISSUE TITLE
Small GUI

### ISSUE THREAD

**Issue by Angxstupst** [ChrisRM/material-theme-jetbrains#1796]
I use the "Material Theme UI" plugin. My problem is when I create a new Java class the GUI is wide, not small. How can I change it? (See pictues)

![Screenshot_185](https://user-images.githubusercontent.com/70912869/125684794-42f65de9-0756-40a7-be75-f37f7c7d5242.png)
![Screenshot_186](https://user-images.githubusercontent.com/70912869/125684797-b5303522-3110-4f86-a9da-4ae2854823b9.png)

**Comment by mallowigi** [comment]
Compact settings
