### ISSUE TITLE
Support Rubymine

### ISSUE THREAD

**Issue by the-ult** [ChrisRM/material-theme-jetbrains#18]
Your port looks awesome.. Should be the default skin for all Jetbrains IDE's :-)

Would be great if you'd support Rubymine as well.

**Comment by ChrisRM** [comment]
Sure, I'll add support for it as soon as I've fixed the bugs on the PhpStorm version.

**Comment by the-ult** [comment]
Fantastic. Thanks a lot for your work.

**Comment by ChrisRM** [comment]
@the-ult Please try the newest build. Should work with RubyMine

**Comment by the-ult** [comment]
Nice,

I'm gonna check it out and let you know how it works
