### ISSUE TITLE
Upgrading to latest version

### ISSUE THREAD

**Issue by kevinjbayer** [ChrisRM/material-theme-jetbrains#180]
My version in RubyMine is still 0.1.7 and when I browse repositories it shows me that it was last updated on 11/1/15 and version is also at 0.1.7.

Is there a way to manually update this, or does it just need to be submitted to the JetBrains repo when changes are made?

**Comment by Kurre** [comment]
Grab the latest [Material Theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/blob/master/Material%20Theme.zip) from repo and overwrite existing files in ~/.PhpStorm2016.1/config/plugins/Material Theme/lib directory.

That should do it.

**Comment by ChrisRM** [comment]
You should wait until the update is uploaded to the repo. There's some minor problems with the plugin, so I need to sort these out before I send it to the repo. See  https://github.com/ChrisRM/material-theme-jetbrains/issues/177

**Comment by ChrisRM** [comment]
A new version is out and should show up in your IDE.
