### ISSUE TITLE
Incompatible : require IDE build 202.* or older

### ISSUE THREAD

**Issue by nikunjparadva** [ChrisRM/material-theme-jetbrains#1801]
### Need Update
Hello Devs.

Recently i updated Android studio to latest version which is known as Arctic Fox.
https://android-developers.googleblog.com/2021/07/android-studio-arctic-fox-202031-stable.html

This plugin is really awesome. I am user of this Plugin but it was incompatible in this new version of android studio. Please update and make it compatible with it. 

---

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS = Windows
* IntelliJ Product + version = Android Studio Arctic Fox | 2020.3.1
* Material Theme Plugin version = 5.3.4

Please check attached Image
![image](https://user-images.githubusercontent.com/20983834/127633039-84155a06-0a05-4f8f-87d3-e87d970d2996.png)

**Comment by RobPFarley** [comment]
I'm on version 5.6.0.1 of the plugin and although the error @nikunjparadva had doesn't appear for me, Android Studio doesn't load the theme after a restart, it always reverts back to the default Darcula

**Comment by nikunjparadva** [comment]
> 
> 
> I'm on version 5.6.0.1 of the plugin and although the error @nikunjparadva had doesn't appear for me, Android Studio doesn't load the theme after a restart, it always reverts back to the default Darcula

### @RobPFarley about your issue i have solution for this issue
### Please check it out my answer on [Stackoverflow ](https://stackoverflow.com/a/68599712/5773037)

I hope it will be Helpful

**Comment by mallowigi** [comment]
Cannot reproduce
