### ISSUE TITLE
How do I revert... whatever this change is?

### ISSUE THREAD

**Issue by Atulin** [ChrisRM/material-theme-jetbrains#1802]
### Summary

The tool tabs in my IDE were replaced with this atrocity:

![image](https://user-images.githubusercontent.com/11233299/127720326-ab1976ce-3c52-418c-a1ca-920fe3ff0191.png)

### Expected behavior

The tool tabs in my IDE use both screen edges and the bottom of the screen, leaving plenty of screen real estate

### Actual behavior

Screen real estate is wasted by UI made for tablets, everything is moved around and completely fucks up my setup, and every button becomes yellow for some reason

### Steps to reproduce (if needed)

1. Update plugin
2. Open IDE
3. Wipe up the blood that started leaking from your eyes

**Comment by Atulin** [comment]
Settings —> Features — Striped Tool Windows (Experimental), if anybody was also looking for the option.

I was wondering, "none of my tool windows look like zebras, and yet this option is turned on? Turns out it doesn't make tool windows striped, it enables the iPad UI.

**Comment by mallowigi** [comment]
I agree that I need to find a better name

**Comment by Atulin** [comment]
"Large Tool Tabs" maybe? "Tool Tab To Buttons"? Something of the sort.

**Comment by Getz85** [comment]
Please, don't enable this by default.
I've spent too many time to find where this option was to deactivate it...

**Comment by fcFn** [comment]
Wow, spent quite some time finding out how to turn this off!! I even thought it's JB's doing. It was pretty rude, not gonna lie. Please don't turn it on by default!
