### ISSUE TITLE
Theme reset after restart in Android Studio 2020.3.1 Arctic Fox

### ISSUE THREAD

**Issue by ThexXTURBOXx** [ChrisRM/material-theme-jetbrains#1804]
### Summary

The theme is reset on every restart of Android Studio 2020.3.1 Arctic Fox.
Yes, 2020.3.1 is the newest stable release of Android Studio for now and, thus, only compatible with Material Theme UI 5.6.0.1.

### Expected behavior

Save the theme such that it is applied correctly after restart

### Actual behavior

The theme for the application is reset (everything is in Dracula, except for the editor)

### Something I have noticed

If you look at the `material_theme.xml`, the version is set to `5.5.0`, even though `5.6.0.1` is installed. Maybe this is related to the weird behavior? A hotfix release for `5.6.X` would be very nice until some newer Android Studio version is released which would be compatible with the newer versions of the plugin.

### Steps to reproduce (if needed)

1. Launch Android Studio 2020.3.1 Arctic Fox
2. Install Material Theme UI 5.6.0.1
3. Set any Material Theme
4. Restart Android Studio
5. See that the theme is reset

### Environment

* Windows 10
* Android Studio 2020.3.1 Arctic Fox
* Material Theme UI 5.6.0.1

**material_theme.xml**
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="highContrast" value="true" />
    <option name="allowDataCollection" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="tabFontSize" value="16" />
    <option name="accentColor" value="ff9800" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="-297a8b8a:1786967b0dc:-8000" />
    <option name="version" value="5.5.0" />
  </component>
</application>
```

<details>
<summary>Before restart</summary>

![grafik](https://user-images.githubusercontent.com/12763829/127767769-dc225ecc-9ebb-4c34-ab8d-68fa7c7041b2.png)

</details>

<details>
<summary>After restart</summary>

![grafik](https://user-images.githubusercontent.com/12763829/127767787-32a15367-561a-48e0-9bfe-00f611898383.png)

</details>

**Comment by mallowigi** [comment]
https://stackoverflow.com/questions/68572505/after-updating-to-android-studio-arctic-fox-i-cannot-use-any-custom-theme/68599712#68599712

**Comment by ThexXTURBOXx** [comment]
That instantly worked. Sorry for wasting your time then and thank you very much! :)

**Comment by mallowigi** [comment]
I'll keep this open until the version of Android Studio fixes it

**Comment by binarynoise** [comment]
This might be even worth getting pinned

**Comment by wakaztahir** [comment]
Same issue

**Comment by ThexXTURBOXx** [comment]
@wakaztahir See the StackOverflow answer that @mallowigi posted here. This gets rid of the issue entirely for now.
Otherwise wait until the next minor version of Android Studio is released.

**Comment by nikunjparadva** [comment]
Here is the Own Solution. 
https://github.com/ChrisRM/material-theme-jetbrains/issues/1801#issuecomment-890300295
