### ISSUE TITLE
Theme not working PHPStorm PS-212.4746.100

### ISSUE THREAD

**Issue by sn0rcha** [ChrisRM/material-theme-jetbrains#1805]
After updating PHStorm on the weekend, I'm getting the following message:

```Plugin error: Plugin 'Material Theme UI' (version '6.7.2') is not compatible with the current version of the IDE, because it requires build 211.* or older but the current build is PS-212.4746.100```

Pretty sure you are aware just posting here in case you're not :)

**Comment by mallowigi** [comment]
Please download latest update
