### ISSUE TITLE
Todo Icon taking preference over .vue icon

### ISSUE THREAD

**Issue by kevincam3** [ChrisRM/material-theme-jetbrains#1806]
### Summary

I have an vue component named TodosList.vue and it's not showing the Vue icon but instead the Todo icon

### Expected behavior

I expect that the Vue icon would take preference

### Actual behavior

The Todo icon is taking preference.

### Steps to reproduce (if needed)

1. Create a file name TodosList.vue
2. Look at the icon it has displayed

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Licensed to Kevin Campbell
Subscription is active until June 3, 2022.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: debugger.watches.in.variables=false, run.processes.with.pty=TRUE, debugger.valueTooltipAutoShowOnSelection=true, ide.experimental.ui.toolwindow.stripes=true, ide.balloon.shadow.size=0, eslint.additional.file.extensions=svelte
Non-Bundled Plugins: com.dubreuia (2.2.0), AceJump (3.8.3), CMD Support (1.0.5), Scratch (1.10), com.intellij.ideolog (203.0.27.0), com.intellij.plugins.macoskeymap (211.6432.7), in.thekalinga.snippet.intellij (6.1.0), com.mallowigi (38.0.0), mobi.hsz.idea.gitignore (4.2.0), com.atlassian.bitbucket.references (2021.2.171), org.nik.presentation-assistant (1.0.9), quokka.js (1.0.305), org.jetbrains.plugins.node-remote-interpreter (212.4746.57), com.intellij.plugins.html.instantEditing (212.4746.57), spy-js (212.4746.57), Karma (212.4746.57), com.intellij.plugins.webcomponents (212.4746.57), com.jetbrains.lang.ejs (212.4746.57), com.jetbrains.plugins.jade (212.4746.57), intellij.prettierJS (212.4746.57), com.dmarcotte.handlebars (212.4746.57), com.github.masahirosuzuka.PhoneGapIntelliJPlugin (212.4746.57), com.chrisrm.idea.MaterialThemeUI (6.8.0), de.espend.idea.php.annotation (8.0.0), izhangzhihao.rainbow.brackets (6.19), ru.adelf.idea.dotenv (2021.2)

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.
![image](https://user-images.githubusercontent.com/870934/127793643-bcaa1c41-7cc6-460b-895f-bc31c10a73c3.png)

**Comment by mallowigi** [comment]
This is not the correct repository but in general this is a design choice. I have a task to be able to disable specific associations in the future.

**Comment by kevincam3** [comment]
Ok, I'll just disable the file icons for now.
