### ISSUE TITLE
Selected symbols data is not stored globally

### ISSUE THREAD

**Issue by Rasool-deldar** [ChrisRM/material-theme-jetbrains#1807]
There is a problem in this new version, the location of the icons is not stored globally and you have to select the desired icon again in each project to display.

### Summary
There is a problem in this new version, the location of the icons is not stored globally and you have to select the desired icon again in each project to display.
...

### Expected behavior
Icons should be stored globally so that there is no need to select the desired icon in each new project
...

### Actual behavior
The data of the selected icons is stored in each project
...

### Environment

It should contain:
* OS Windows
* PhpStorm
* Plugin version 6.8.0.1
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

![image](https://user-images.githubusercontent.com/58503211/127811616-a9063bca-3172-4486-9d3c-0018b6c67476.png)

**Comment by mallowigi** [comment]
This is a known issue of the striped tool windows, for now this is not the priority so if it bothers you, you can still revert to the old (actual) layout
