### ISSUE TITLE
Stripe: Tool Window selected but hidden

### ISSUE THREAD

**Issue by Rasool-deldar** [ChrisRM/material-theme-jetbrains#1809]
When I click on the hide option, the icons are still active

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

Environment
It should contain:

OS Windows
PhpStorm
Plugin version 6.8.0.1
Plugin configuration (found in material_theme.xml)
If needed a list of enabled plugins
Material Theme Plugin version

![image](https://user-images.githubusercontent.com/58503211/127830910-58133a17-d290-48f2-934f-81003c62dd3c.png)

![image](https://user-images.githubusercontent.com/58503211/127831191-2fe899aa-fb99-4342-b5f5-c0ca3f8c66aa.png)

**Comment by mallowigi** [comment]
Yes this is a known issue, working on it

**Comment by mallowigi** [comment]
Closing the bugs related to the Striped Tool Windows, as this is on JetBrains' side and I cant do anything about it.
