### ISSUE TITLE
Indent in nextlevel items

### ISSUE THREAD

**Issue by Jactaen** [ChrisRM/material-theme-jetbrains#181]
Hi,

Is there a way to decrease indent of nextlevel items? Right now its about 20px indent and I would like a way to decrease this within material-theme?

![image](https://cloud.githubusercontent.com/assets/16868983/14518843/0bbe897a-021b-11e6-91f4-4f559c18eed8.png)

**Comment by ChrisRM** [comment]
Not sure tbh, but I'll see if I can find anything

**Comment by mallowigi** [comment]
Yeah it could, but i dont think it would look nice

**Comment by mallowigi** [comment]
How many people want this feature? Vote by saying +1

**Comment by Jactaen** [comment]
Actually its possible now: https://youtrack.jetbrains.com/issue/IDEA-126373

**Comment by mallowigi** [comment]
I delivered something in the latest release, go take a look
