### ISSUE TITLE
Theme Settings Not Saving In Latest Andorid Studio (2020.3)

### ISSUE THREAD

**Issue by rahat14** [ChrisRM/material-theme-jetbrains#1810]
Material Theme UI not changing editor background also not saving any theme settings in latest Android Studio Version name arctic fox which is based on IntelliJ 2020.3 . Tested on 3 windows 10 machines with same issue. Theme not saving after restarting android studio

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/1804
