### ISSUE TITLE
A lot of colors are brown after updating

### ISSUE THREAD

**Issue by EZPlugins** [ChrisRM/material-theme-jetbrains#1816]
### Summary
I recently updated my IntelliJ to 2021.2 and plugin version 6.8.0.1 and now in the editor a lot of the colors are brown.
The "Color Scheme" settings page in IntelliJ still shows the correct colors however.

### Expected behavior
Colors to match what's shown in "Color Scheme"

### Actual behavior
Colors are brown

Actual colors:
![idea64_nUGB7gQJpj](https://user-images.githubusercontent.com/70465175/128647694-5f9f4455-d60d-45e3-b862-668fd5d9f78c.png)
Preview colors:
![idea64_A4xZLXtR9d](https://user-images.githubusercontent.com/70465175/128647698-9c28a112-afcd-4d1c-a5c0-152c47b16077.png)

### Environment

IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 24
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support (1.0.5), GLSL (1.19), com.intellij.nativeDebug (212.4746.92), com.jetbrains.ChooseRuntime (1.2), org.antlr.intellij.plugin (1.16), com.mallowigi (38.0.0), ASM Bytecode Viewer (7.2), CheckStyle-IDEA (5.54.0), YourKit Java Profiler 2019.8-b141 Integration (2019.8.141.0), com.github.camork.fileExpander (1.7), com.intellij.plugins.html.instantEditing (212.4746.57), JProfiler (19.3), com.chrisrm.idea.MaterialThemeUI (6.8.0.1)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by mallowigi** [comment]
I never encountered that. Does that happen with your copy only or with the bundled color schemes as well?

**Comment by EZPlugins** [comment]
Looks to be only with my custom scheme, I've attached the .icls file.
[Arc Dark copy.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/6952692/Arc.Dark.copy.zip)

**Comment by mallowigi** [comment]
Please try to revert to the original color scheme https://www.material-theme.com/docs/configuration/color-schemes/#customization
