### ISSUE TITLE
Compatibility issue: Material Theme UI causes JFormDesigner's checkbox to disappear

### ISSUE THREAD

**Issue by SakuraKoi** [ChrisRM/material-theme-jetbrains#1817]
### Summary

After installed MaterialTheme (including lite and full edition), all checkboxes in JFormDesigner's "properties window" disappeared, the checkbox can only be seen(exactly, blinks) when the mouse clicks on it

### Expected behavior

Without Material Theme UI installed, every checkboxes are visible
![](https://i.loli.net/2021/08/09/goJASxlBUF2a6OD.png)

### Actual behavior

After Material Theme UI installed, checkboxes are gone
![](https://i.loli.net/2021/08/09/gufkJRm71Gc4Ysx.png)

even if im not using a material theme, just Darcula with Material Theme UI plugin installed
![](https://i.loli.net/2021/08/09/mcXNkuMrxd7jQOW.png)

### Steps to reproduce

1. Install JFormDesigner from IDEA plugin repo and restart IDEA
2. Create a JFormDesigner form and open it, everything working
3. Install Material Theme UI and restart IDEA
4. Open the form again and checkboxes disappeared

### Environment
```
IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1520M
Cores: 4
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (36.0), com.notime.intellijPlugin.backgroundImagePlus (1.0.3), GsonFormatPlus (1.6.1), JFormDesigner (7.0.4), com.haulmont.jpab (4.4-211), com.chrisrm.idea.MaterialThemeUI (6.7.2)
Kotlin: 211-1.4.32-release-IJ7628.19
```

Hope this issue can be fixed because material theme is awesome and i'm not wanna lose it, but the issue is really wired while designing a form

**Comment by mallowigi** [comment]
I dont think i can do anything about it. JFormDesigner's code is private and does not seem to use the usual checkboxes. I've been using it for years and got used to this. Maybe you could try to contact them about the issue? (I already tried with no success either)

**Comment by SakuraKoi** [comment]
okay, thank you again for your hardworking to bring the cool theme to me
