### ISSUE TITLE
the color scheme cannot manage the color preference after update

### ISSUE THREAD

**Issue by primabrucexu** [ChrisRM/material-theme-jetbrains#1818]
that's what I see in the editor which doesn't match what I see in the setting preview

![how it looks in the editor](https://user-images.githubusercontent.com/52796293/128680493-b060d1db-9a56-405f-90db-f665992371f9.jpg)

![how it looks in the preview window](https://user-images.githubusercontent.com/52796293/128680622-0aa209f8-8552-4b20-ba82-5d27e14611e6.jpg)

**Comment by mallowigi** [comment]
does it reproduce with other themes?

**Comment by primabrucexu** [comment]
not all of them have the problem

**Comment by mallowigi** [comment]
I suspect there's something wrong with your local color schemes. Please try to restore defaults and tell me if that happens again.

**Comment by primabrucexu** [comment]
It doesn't work. 
Can sync function be the problem? My windows which disable sync doesn't have problem like that.

**Comment by mallowigi** [comment]
It doesn't. Your color schemes are probably corrupted. If restore defaults doesn't work then the last resort would be to remove the schemes from the folder manually.

**Comment by primabrucexu** [comment]
How ? The system is MACOS.

**Comment by mallowigi** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs

--
Elior

**Comment by primabrucexu** [comment]
Nope, I delete every dir or file it mentioned, but still don't work. I even reinstall the software still don't work

**Comment by mallowigi** [comment]
Can you come to the slack channel so I can take a closer look? Thanks

--
Elior
