### ISSUE TITLE
Material UI latest update 6.8.1 scrollbar issue

### ISSUE THREAD

**Issue by Abdelraman** [ChrisRM/material-theme-jetbrains#1819]
File tree scrollbar background shows up with a light green unlike the older version, this new background is some how annoying.
current version 6.8.1
![Screenshot 2021-08-18 014510](https://user-images.githubusercontent.com/4821833/129814773-c8b9cb9a-3050-4815-9ca2-fccc4d6e0c69.png)

previous version 6.8.0.1
![image](https://user-images.githubusercontent.com/4821833/129814639-4a11f167-4ff3-47ee-9564-9d2a9c5ca7d5.png)

**Comment by mallowigi** [comment]
Thanks I'll fix it right away

**Comment by Abdelraman** [comment]
fixed in version 6.8.1.1, Thanks a lot
