### ISSUE TITLE
java debug mode, can't see the current debugging line

### ISSUE THREAD

**Issue by just2d** [ChrisRM/material-theme-jetbrains#182]
hi, thanks for the great plugin.
but in the debug mode, I can't see the current debugging line.
as you can see, the current debugging line is line 68, but the background color can't be seen clearly.

![33333](https://cloud.githubusercontent.com/assets/6417639/14632710/bd641372-064c-11e6-8987-bf53a5dc6c4e.png)

**Comment by thanos-irodotou** [comment]
that's easy to change if you don't want to wait.
`Settings > Editor > Colors & Fonts > General`. Then expand the `Editor` list and copy the code in `Selection background` (should probably be `214283`).
Go to `Settings > Editor > Colors & Fonts > Debugger` and change the `Background` code in `Execution point` to that value.

**Comment by just2d** [comment]
thanks, I'll give it a try.

**Comment by thanos-irodotou** [comment]
No problem, worked for me, hope it does for you too 😄

**Comment by thanos-irodotou** [comment]
On that note, it'd be nice to have a guide on how to fix such issues, so that we can open PRs, perhaps a Contributing.md ?

**Comment by denofevil** [comment]
Duplicates #90
