### ISSUE TITLE
[Large Tool Windows] Change the icons active states by shortcuts

### ISSUE THREAD

**Issue by asamofal** [ChrisRM/material-theme-jetbrains#1821]
### Summary
Hi. I really like this new feature  "Large Tool Windows". But new icons don't change their state when using the hotkeys instead of clicks. Each button has two states: active and not active. When click the button state is changing but if use a hotkey to open any tool window buttons don't respond on that.
...

### Expected behavior
The buttons should became active by hotkeys too.
...

### Actual behavior
Currently the buttons don't respond when using hotkeys.
...

### Steps to reproduce (if needed)
For example, if press ALT+2 *(default hotkey to open "Favorites" tool window)* Favorites button doesn't change it state.

You can also add Screenshots for a better understanding.

### Environment
PhpStorm 2021.2
Build #PS-212.4746.100, built on July 28, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.11-051311-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Current Desktop: ubuntu:GNOME

**Comment by mallowigi** [comment]
The large tool windows feature has been hold for now by request from JetBrains. There's even a chance the feature will be removed in future versions until the api becomes stable, which according to them will be as soon as 2022.1

All related issues will be closed for now
