### ISSUE TITLE
Code coverage percentage is unreadable against green bar in Rider

### ISSUE THREAD

**Issue by doomchild** [ChrisRM/material-theme-jetbrains#1822]
When viewing the unit test code coverage window, the percentage number is almost completely unreadable against the green bar.  Here is a screenshot showing the problem.

![coverage](https://user-images.githubusercontent.com/234520/130110978-51614324-451c-473f-983e-8a403f778568.png)

I captured this screenshot on a Mac, using Rider version 2021.2 (build #RD-212.4746.113) and Material Theme UI version 6.8.0.1, but I have verified that it also looks like this on Windows.

**Comment by mallowigi** [comment]
Closing it in favor of https://youtrack.jetbrains.com/issue/RIDER-66723

I have no possibility to see source code in Rider so I'll leave that to JB.
