### ISSUE TITLE
UI does not return from shadowed state after patch creation

### ISSUE THREAD

**Issue by torchwood1715** [ChrisRM/material-theme-jetbrains#1823]
### Summary

In 6.8.12 and in one or two earlier builds total Intellij IDEA UI remains shadowed after "Create Patch" dialog is closed after successfull patch creation.

### Expected behavior
UI returns to the previous look

### Actual behavior

UI remains shadowed, application restart needed for further work

### Steps to reproduce

1. SVN -> Create patch from local changes
![Screen1](https://user-images.githubusercontent.com/25612378/130467865-24ffd4df-5aa5-4ebb-8ca7-b8c787173962.jpg)

2. Save the patch
![Screen2](https://user-images.githubusercontent.com/25612378/130467929-e8d24f39-1292-453d-8264-147be1040c23.jpg)

3.  Close the dialog that saved successfully

4. UI is shadowed after dialog closed
![Screen3](https://user-images.githubusercontent.com/25612378/130470245-a15ea1c0-4d39-4bbd-9806-a88052d9b755.jpg)

### Environment

IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (38.0.0), CheckStyle-IDEA (5.55.1), EclipseCodeFormatter (20.9.203.000.0-Eclipse_2020-06-JavaOnly), org.jetbrains.plugins.spotbugs (1.2.4), Jetbrains TeamCity Plugin (2021.1.92869), com.haulmont.jpab (4.5-212), com.chrisrm.idea.MaterialThemeUI (6.8.1.2)
Kotlin: 212-1.5.10-release-IJ4746.92

[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/7032876/material_theme.zip)

**Comment by cagartner** [comment]
Still happening on 6.8.2:

![image](https://user-images.githubusercontent.com/4007696/132024183-bc6714bf-8873-4324-b1f9-51334dd1f4e4.png)

In my case, the problem seems when I'm using two monitors, the dialog window opens on the MacBook screen and the project is on the other screen.

**Comment by mallowigi** [comment]
Is it with the same reproducible steps?

**Comment by cagartner** [comment]
I recorded this screencast for you: 

https://share.vidyard.com/watch/43qN67VWAr3fkra1JdJKct?

**Comment by mallowigi** [comment]
Really on the new file popup? I use this popup all the time and it doesn't happen to me... I'll try with phpstorm maybe...

Just to be sure, can you remove and reinstall the plugin again?

**Comment by mallowigi** [comment]
Also, is it on the latest version of phpstorm?

**Comment by cagartner** [comment]
@mallowigi 
Actually, any popup cause this problem, new file dialog, debugger, delete dialog.

Yes, phpstorm is the latest version:

![image](https://user-images.githubusercontent.com/4007696/132054127-37d66d59-1302-4612-97cd-60e386d26af1.png)

**Comment by cagartner** [comment]
I think I found the problem, I uninstalled another plugin named: "Magento 2 - Utilities" and the problem stopped, you can close now.

**Comment by cagartner** [comment]
Sorry about that.

**Comment by mallowigi** [comment]
good to know, i'll investigate though
