### ISSUE TITLE
material-theme.com seems to be down...

### ISSUE THREAD

**Issue by kstratis** [ChrisRM/material-theme-jetbrains#1826]
Not sure if this is the right place but it seems that the website is down. 
(Full disclosure: Just after upgrading to v6.8.2, `what's new` page returned an error from within the IDE)

<img width="862" alt="Screenshot 2021-08-28 at 10 52 42 AM" src="https://user-images.githubusercontent.com/1859806/131210850-f923e3fd-b351-4b61-a21a-9f3f81161440.png">

**Comment by mallowigi** [comment]
Yes I know, there's an issue with the DNS. The entries are there but for some reason the changes don't seem to get applied.

The help said that it can take up to 48 hours to propagate, so I'm waiting, then after that I'll try to contact support to get it fixed.

**Comment by mallowigi** [comment]
it's back
