### ISSUE TITLE
Allow sidebar to span window height when placed on the right

### ISSUE THREAD

**Issue by nhedger** [ChrisRM/material-theme-jetbrains#1827]
### Summary

Let me first thank you for the awesome work you've done on this plugin.

I'd like to suggest what I consider to be a UI improvement.

I'd love for the sidebar to span the entire height of the window, _when placed on the right_.

While it does not bother me so much when the sidebar is on the left, I find it awkward to have a gap on top of my sidebar when using a themed title bar.

<img width="882" alt="Screenshot 2021-09-02 at 19 07 24" src="https://user-images.githubusercontent.com/649677/131887329-6ff7ec01-5533-4be2-addd-48f063690ba5.png">

### Expected behavior

I'd like for the sidebar to span the entire height of the window when placed on the right.

### Actual behavior

The sidebar stop right under the themed title bar and leaves a gap.

### Environment

PhpStorm 2021.2.1
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains (0.13.0), com.chrisrm.idea.MaterialThemeUI (6.8.2), nz.hailwood.inertiajs (0.1.2), com.laravel_idea.plugin (4.4.0.212), de.espend.idea.laravel (0.15.4)

**Comment by mallowigi** [comment]
Sorry, that's utterly impossible. The title bar is a special component of the system, not of the IDE. It's possible to change the color (hypothetically) but making the inside elements overlap it is not possible. And in my knowledge, no application has ever done that. Sorry!
