### ISSUE TITLE
Invisible checkboxes

### ISSUE THREAD

**Issue by iharobCP** [ChrisRM/material-theme-jetbrains#1828]
### Summary

All checkboxes are invisible, I had to switch to the dracula theme so that I can use the IDE.

### Expected behavior

Checkboxes should be visible checked or unchecked

### Actual behavior

No checkboxes are visible at all

### Steps to reproduce (if needed)

1. Start the IDE
2. Use any UI component that has a checkbox

![Captura de pantalla_2021-09-07_00-59-45](https://user-images.githubusercontent.com/85121160/132286818-5b210db6-9228-4bf5-ae6c-b487e9e59167.png)

### Environment

WebStorm 2021.2.1
Build #WS-212.5080.54, built on August 23, 2021
Licensed to Iharob Al Asimi
Subscription is active until September 25, 2021.
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.13-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: de.netnexus.camelcaseplugin (3.0.8), com.mallowigi (38.0.0), idea.plugin.protoeditor (212.5080.8), IdeaVIM (0.69), com.chrisrm.idea.MaterialThemeUI (6.8.2), Dart (212.5080.8), com.github.beansoftapp.flutter.storm (2021.2.0), com.intellij.react.css.modules (1.0.1)
Current Desktop: XFCE

**Comment by skalpa** [comment]
@iharobCP Was going to report the same problem and after comparing my plugins list with yours I noticed that disabling the "Atom Material Icons" plugin fixed the issue for me.

So I am not sure which plugin is responsible or if it is a compatibility problem when both are installed together.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/133819411-992d9f97-616f-4f63-8a32-f265b3461736.png)

Which version are you using?

**Comment by skalpa** [comment]
I disabled all the plugins except the bundled ones and Atom Material Icons + Material Theme UI and the problem persists.

PhpStorm 2021.2.2
Build #PS-212.5284.49, built on September 16, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10
Registry: ide.intellij.laf.enable.animation=true, run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi (41.1.0), com.chrisrm.idea.MaterialThemeUI (6.8.2)

![Screenshot 2021-09-18 000526](https://user-images.githubusercontent.com/4943191/133862503-98a15390-f044-49c7-b05f-be584c5bd6d1.png)

I was able to find out which option triggers the bug 😀. If I disable "enable file icons" the checkboxes disappear, if I enable it everything works.

This` a-file-icons.xml` triggers the bug:

```xml
<application>
  <component name="AtomFileIconsConfig">
    <option name="enabledIcons" value="false" />
    <option name="isEnabledIcons" value="false" />
    <option name="monochromeColor" value="546e7a" />
    <option name="accentColor" value="2470b3" />
  </component>
</application>
```

This one doesn't:

```xml
<application>
  <component name="AtomFileIconsConfig">
    <option name="monochromeColor" value="546e7a" />
    <option name="accentColor" value="2470b3" />
  </component>
</application>
```

My `material_theme.xml`:

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="compactMenus" value="true" />
    <option name="highlightColorEnabled" value="true" />
    <option name="accentMode" value="true" />
    <option name="compactSidebar" value="true" />
    <option name="isHighlightColorEnabled" value="true" />
    <option name="isCompactMenus" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="pristineConfig" value="false" />
    <option name="customSidebarHeight" value="22" />
    <option name="settingsSelectedTab" value="4" />
    <option name="tabsHeight" value="24" />
    <option name="accentColor" value="0955b3" />
    <option name="highlightColor" value="1e79e9" />
    <option name="selectedTheme" value="DARKER" />
    <option name="userId" value="-763c294a:17387e76d62:-8000" />
    <option name="version" value="6.8.1.2" />
    <option name="tabHighlightPosition" value="Bottom" />
  </component>
</application>
```

**Comment by huypxgear** [comment]
I have the same issue, all my checkboxes are disappeared. I have to re-install again version 6.8.1.2.

**Comment by mallowigi** [comment]
Managed to reproduce. Funny, it's not a big of Material Theme or Atom Material Icons separately, but it is when they are loaded together.

I'll investigate the cause, in the meanwhile please try to use the File Icons setting, or disable Atom Material Icons completely
