### ISSUE TITLE
[Docs] Clarify what constitues paid tier

### ISSUE THREAD

**Issue by Ginden** [ChrisRM/material-theme-jetbrains#1829]
### Summary

I'm user interested in purchasing product, but I don't know what I would pay for.

### Expected behavior

* I can see side-by-side comparison
* I can easily jump to paid version comparison from JetBrains plugin page

### Actual behavior

* JetBrains plugin page doesn't link to feature comparison
* Feature comparison page lacks any visual information about features of paid version
* Features of paid version are very loosely described (what does "Language Additions" mean? What "fonts" mean - do you bundle some fancy fonts?)

### Environment

N/A - this is related to documentation.

**Comment by mallowigi** [comment]
https://material-theme.com/docs/pricing/

**Comment by Ginden** [comment]
@mallowigi That's exactly page that I'm complaining about - it doesn't provide user with enough informations.

**Comment by mallowigi** [comment]
https://github.com/mallowigi/material-theme-docs/issues/78

**Comment by mallowigi** [comment]
I didn't think it was that vague, but I will try to at least attach links to the pages in question since everything is documented in the website. But I'm closing this issue since it is not in the right repository.
