### ISSUE TITLE
Change text color inside HTML Tags

### ISSUE THREAD

**Issue by Echosgraphik** [ChrisRM/material-theme-jetbrains#183]
Hi,

Very beautiful thème but this issue doesn't fix the problem : https://github.com/ChrisRM/material-theme-jetbrains/issues/163

**Comment by ChrisRM** [comment]
This is not really an issue with the plugin, but rather a personal preference of yours. If you want to change the colors, make a copy of the color scheme and change the colors to whatever you want.

**Comment by Echosgraphik** [comment]
Sorry but that don't works for us. Please read this issue. #163

**Comment by Echosgraphik** [comment]
We cannot change the text color inside HTML tag, it's impossible in your theme

**Comment by Linxflasher** [comment]
Hello, that theme is great. Unfortunately, I face the same problem - can't change HTML's text color. Could you please fix this?

**Comment by samIntegrateur** [comment]
Hello, +1 for this request, it works with another theme but not this one
