### ISSUE TITLE
Autofocus does not work when creating a new file with custom template

### ISSUE THREAD

**Issue by longprao** [ChrisRM/material-theme-jetbrains#1834]
### Summary

When creating a new file in the Project view, the IDE does not autofocus on "File name" if the chosen item is a custom File and Code Templates.

This only happens in recent versions of the plugin. I can't remember which, but could be in the last 1-2 month.

...

### Expected behavior

The IDE should autofocus on File Name to type right away.

...

### Actual behavior

Nothing is focused, need to use mouse to click on the Fire Name input field.

...

### Steps to reproduce (if needed)

1. Settings -> Editor -> File and Code Templates.
2. Create a new custom template. For ex: React TypeScript.
3. Right click on any item in Project view -> New (or Cmd + N) -> Choose the new custom template (For ex: React TypeScript).
4. File Name is not autofocused.

### Environment

MacOS 11.6
PhpStorm 2021.2.2 Build #PS-212.5284.49, built on September 16, 2021
Material Theme UI 6.9.0. Default configuratiom.
Atom Material Icons 41.1.0. Default configuration.

**Comment by mallowigi** [comment]
BTW thank you for suggesting me this feature I completely forgot about :)

**Comment by mallowigi** [comment]
Just checked and it reproduces in PHPStorm. But this is not related to the Material Theme, as disabling Material Theme (and Atom) does not solve it. Also this repository is deprecated, please note this for the future.
