### ISSUE TITLE
GitHub Dark dimmed theme request

### ISSUE THREAD

**Issue by michaelwestphal** [ChrisRM/material-theme-jetbrains#1837]
### Summary

Please consider adding a "GitHub Dark dimmed" theme as is available as a theme on the GitHub site: 

- https://github.blog/changelog/label/dimmed-mode/

![image](https://user-images.githubusercontent.com/1829174/136412944-0907069e-199c-4731-8824-43f0adc88c06.png)

(I personally find the "dimmed" version of their dark theme a bit easier on the eyes as far as a dark theme goes.)

Thank you for your excellent plug-in for the Jetbrains IDEs!!

**Comment by mallowigi** [comment]
It's already the dimmed one that is available - I found the pure dark unusable.
