### ISSUE TITLE
I often have to exit and open again to make the interface work normally

### ISSUE THREAD

**Issue by xming521** [ChrisRM/material-theme-jetbrains#1838]
### Summary
I often have to exit and open again to make the interface work normally

### Actual behavior
First open
![image](https://user-images.githubusercontent.com/32786500/136681428-2b5ccf16-928a-4f8e-879f-7d744c9ed5bd.png)

Restart pycharm
![image](https://user-images.githubusercontent.com/32786500/136681471-216e0000-7b55-4e28-beb6-fd7f4f5456d2.png)

### Environment
PyCharm 2021.2.2 (Professional Edition)
内部版本号 #PY-212.5284.44，September 15, 2021 构建
Licensed to 张 益铭
订阅有效期至 December 13, 2021。
For educational use only.
运行时版本: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1428M
Cores: 16
Registry: debugger.watches.in.variables=false, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X (2021.2), com.alayouni.ansiHighlight (1.2.4), com.intellij.ideolog (203.0.27.0), com.intellij.zh (212.231), net.seesharpsoft.intellij.plugins.csv (2.17.1), Statistic (4.1.7), com.mallowigi (42.0.0), com.chrisrm.idea.MaterialThemeUI (6.9.1), com.jetbrains.intellij.datalore (0.1.14-212), cn.yiiguxing.plugin.translate (3.1.1)

[options.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/7316837/options.zip)

**Comment by mallowigi** [comment]
Oh and this repository is deprecated.
