### ISSUE TITLE
Preventing WebStorm 2016.1 to start

### ISSUE THREAD

**Issue by nosachamos** [ChrisRM/material-theme-jetbrains#184]
It worked right after I installed. However, a day later, WebStorm wouldn't start anymore. If I remove the plugin, it starts normally. When I attempt to open a project with the plugin installed, it gives this error:

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing 'com.intellij.openapi.vcs.changes.ChangesViewI'

It's a shame, this is the best theme out there for WebStorm, IMHO. I'll check back periodically to see if this is fixed, it'd be awesome if we could use it in the future.

**Comment by hihell** [comment]
seems 2016.1 has many compatibility issue with color themes. Pycharm 2016.1 has the same issue.

**Comment by liamdemafelix** [comment]
Same issue with phpStorm 2016.1.

**Comment by MangeshPimpalkar** [comment]
+1

**Comment by laurynas-karvelis** [comment]
+1

**Comment by ChrisRM** [comment]
I'm not not even close to be able to reproduce this. Can someone give me the error stacktrace?

**Comment by imdpk** [comment]
+1 I am unable to open webstorm at this moment.

**Comment by imdpk** [comment]
Got it working by uninstalling and install with no projects open. This seem to have done the trick.

**Comment by ChrisRM** [comment]
Can you try [this build](https://github.com/ChrisRM/material-theme-jetbrains/raw/bug/184/Material%20Theme.zip)? Go to `Plugins` - `Install plugin from disk...` and select the zip you downloaded.

**Comment by liamdemafelix** [comment]
The build works as expected on phpStorm 2016.1.

Thanks!

**Comment by ChrisRM** [comment]
Should be fixed here: https://github.com/ChrisRM/material-theme-jetbrains/commit/fcacaad119bb67162ab76ee9d56c7994b0627a6f

Feel free to reopen if the problem persists
