### ISSUE TITLE
No outline button at startup

### ISSUE THREAD

**Issue by maicol07** [ChrisRM/material-theme-jetbrains#1842]
### Summary
When starting the IDE with a project already open, there is no outline button. Opening the Material Theme UI settings page, restores the outlined buttons

### Expected behavior
Outline button works when starting the IDE with a project already open

### Actual behavior
See summary

### Steps to reproduce (if needed)
1. Open/create a project
2. Close the IDE
3. Reopen the IDE

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS Windows 11
* IntelliJ Product + version (IDEA, RubyMine...) PHPStorm 2021.3
* Plugin version 6.9.1
* Plugin configuration (found in material_theme.xml): 
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="borderedButtons" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="overrideAccentColor" value="false" />
    <option name="pristineConfig" value="false" />
    <option name="useMaterialWallpapers" value="true" />
    <option name="useProjectTitle" value="false" />
    <option name="settingsSelectedTab" value="3" />
    <option name="accentColor" value="c69cff" />
    <option name="selectedTheme" value="LIGHTER" />
    <option name="userId" value="64b8df60:1798b82947e:-8000" />
    <option name="version" value="6.9.1" />
    <option name="stripedToolWindowsEnabled" value="true" />
  </component>
</application>
```
* If needed a list of enabled plugins
* Material Theme Plugin version 6.9.1

**Comment by mallowigi** [comment]
I have been using outline buttons as far as I can remember and I can't reproduce this. Can you provide a screenvid ?
