### ISSUE TITLE
Some buttons keep old theming after switching to new theme

### ISSUE THREAD

**Issue by bosycom** [ChrisRM/material-theme-jetbrains#1848]
### Summary

Switching from light theme to dark theme (or vice versa) keeps old theming for some buttons (see screenshot)

### Steps to reproduce (if needed)

1. Switch from a light theme to dark theme
2. Trigger a Jetbrains IDE dialog, such as File -> Invalidate Caches...

### Environment

PhpStorm 2021.2.3
Build #PS-212.5457.49, built on October 13, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2014M
Cores: 8
Registry: run.processes.with.pty=TRUE, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.github.lppedd.idea-conventional-commit (0.19.0), com.mallowigi (50.2.0), co.anbora.labs.firebase-syntax-highlighting (2.6.6), net.vektah.codeglance (1.5.4), com.deadlock.scsyntax (212.5457.18), intellij.prettierJS (212.5080.8), com.chrisrm.idea.MaterialThemeUI (6.9.1), ru.adelf.idea.dotenv (2021.3.0.212)

Using default Material Theme settings.

![Screenshot 2021-11-25 171805](https://user-images.githubusercontent.com/10790842/143475032-f35b4390-8724-48ec-b78f-4c12e4b2e2df.png)

**Comment by mallowigi** [comment]
Yes, I'm aware of that, and what's funny is that it's something that has been happening since day one. I'll try once more to find a solution to that.

**Comment by mallowigi** [comment]
But please report issues to the new repository, thanks.

**Comment by bosycom** [comment]
> But please report issues to the new repository, thanks.

I landed here after clicking on the GitHub link on the official material-theme.com page. If https://github.com/chrisrm/material-theme-jetbrains isn't the new repo, then please tell me the link to it. Thanks.

**Comment by bosycom** [comment]
> Yes, I'm aware of that, and what's funny is that it's something that has been happening since day one. I'll try once more to find a solution to that.

That is funny. I am only using the paid version since a couple of weeks, so I can't tell. Thanks for the effort, keep on the good work!
