### ISSUE TITLE
Unable to load premium features on start ip

### ISSUE THREAD

**Issue by baqirkhan** [ChrisRM/material-theme-jetbrains#1850]
### Summary
Whenever I start the IDE after shutdown, my premium features are not loaded even though they are already setup in the settings.
...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce (if needed)

1. Shutdown the system completely
2. Open the IDE after start

You can also add Screenshots for a better understanding.

### Environment
WebStorm 2021.3
Build #WS-213.5744.224, built on November 27, 2021
Licensed to Baqir Khan
Subscription is active until April 15, 2022.
For educational use only.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.5-76051505-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    ski.chrzanow.foldableprojectview (1.1.1)
    quokka.js (1.0.319)
    one.util.ideaplugin.screenshoter (1.7.1)
    name.kropp.intellij.makefile (213.5744.224)
    com.tabnine.TabNine (0.5.3)
    zielu.gittoolbox (212.8.3)
    mobi.hsz.idea.gitignore (4.3.0)
    com.intellij.database (213.5744.224)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)
    ImportCost (1.0.213)
    com.mallowigi (50.2.0)
    ru.adelf.idea.dotenv (2021.3.0.213)

Current Desktop: pop:GNOME

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
This has been fixed (hopefully) in the next version, please stay in touch. 

And don't create issues in this repository.
