### ISSUE TITLE
IDE not loading pane colors correctly, even though material ui is licensed.

### ISSUE THREAD

**Issue by jimmymain** [ChrisRM/material-theme-jetbrains#1851]
### Summary
Theme colors are not being loaded correctly even though Material Theme UI is Registered.
...

### Expected behavior
![image](https://user-images.githubusercontent.com/2555050/146129234-041bffc2-301d-4c97-a9a6-758e716c8d11.png)

...

### Actual behavior
![image](https://user-images.githubusercontent.com/2555050/146129260-2c25556a-8c9e-454a-ad4b-e56ff5c29001.png)

...

### Steps to reproduce (if needed)

1. First step
Use the IDE for several minutes, and then open it again.
2. Second step
Start the IDE

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Licensed to Craig Main
Subscription is active until April 30, 2022.
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8096M
Cores: 16
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.jetbrains.jumpToLine (0.1.7)
    com.crunch42.openapi (1.23)
    String Manipulation (8.23.203.000.0)
    Key Promoter X (2021.3)
    IdeaVIM (1.9.1)
    com.ppolivka.plugin.gitcleaner (1.1.4)
    com.mallowigi (50.2.0)
    com.chrisrm.idea.MaterialThemeUI (6.10.1)
    SequenceDiagram (2.1.4)
    com.haulmont.jpab (2021.6.0-213)
    aws.toolkit (1.36-213)
    izhangzhihao.rainbow.brackets (6.21)

**Comment by jimmymain** [comment]
[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/7716701/material_theme.zip)

**Comment by jimmymain** [comment]
This is happening all the time, I reinstalled, cleared all intelij cache and setup and started again, and it's still doing it.
So this is a bug with the latest version 2021.3.

It's super annoying.

**Comment by jimmymain** [comment]
Datagrip is the same with a new install.

![image](https://user-images.githubusercontent.com/2555050/146138139-5556a277-dff5-4161-9170-e48f5b10be93.png)

Re-Select theme in settings, and it's right again.

![image](https://user-images.githubusercontent.com/2555050/146138320-c8b01150-2686-46cc-980b-badc73f04b98.png)

**Comment by mallowigi** [comment]
Should be fixed in 6.12
