### ISSUE TITLE
Make the file browser colors and file selection colors more lighter so it is easier to see

### ISSUE THREAD

**Issue by johanbasson** [ChrisRM/material-theme-jetbrains#1853]
I love the Deep Ocean Theme, but the file browser and file selection colors seems hard to read.

![image](https://user-images.githubusercontent.com/45000795/146667376-a7576c74-3d75-4c2f-91ab-29f83d0994db.png)

![image](https://user-images.githubusercontent.com/45000795/146667406-01c44a8c-c6b7-4065-8beb-3532ebf45c24.png)

The file browser colors does not stand out or is hard to read against the very dark background. (See screen shots)

I would suggest making the color ligher so it is easier to see against the dark background.

### Environment

IntelliJ IDEA 2021.3 (Community Edition)
Build #IC-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.13.0-22-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    ide.balloon.shadow.size=0
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.4.1)
    org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
    com.mallowigi (50.2.0)
    com.chrisrm.idea.MaterialThemeUI (6.12.1)
    org.intellij.scala (2021.3.507)

Kotlin: 213-1.6.10-release-923-IJ5744.223
Current Desktop: X-Cinnamon

### Custom Theme Config :
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="contrastMode" value="true" />
    <option name="allowDataCollection" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isWizardShown" value="true" />
    <option name="accentColor" value="84ffff" />
    <option name="selectedTheme" value="DEEPOCEAN" />
    <option name="userId" value="3722f66a:17d5d5b87d1:-8000" />
    <option name="version" value="6.12.1" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
I think this is a matter of luminosity. You can try to increase the luminosity of your computer, or use the high contrast mode.

<img width="1792" alt="CleanShot 2021-12-19 at 10 16 55" src="https://user-images.githubusercontent.com/5015756/146668296-ca113666-8883-4248-a257-87ca3eb16903.png">
