### ISSUE TITLE
How to activate license in JetBrains Client for remote development

### ISSUE THREAD

**Issue by miralita** [ChrisRM/material-theme-jetbrains#1854]
I tried several times to select "Activate license", then close IDE and open again. Nothing changed

**Comment by mallowigi** [comment]
You need to login with your jetbrains account in which you purchased the license.

**Comment by miralita** [comment]
Where is this separate "login" option for plugin located? IDE itself shows that I am logged in and have active license (for IDE, of course).

**Comment by mallowigi** [comment]
You can find it in Help > Register/Buy

Make sure you are using the same account you bought the plugin for. Check in your jetbrains account that the licence indeed appears there.

**Comment by miralita** [comment]
It was not obvious, but for the successful activation of the license, the plugin must be installed on both the Host IDE and the client side, despite the fact that the installation on the client side is enough for it to work. Please add this to documentation.

**Comment by mallowigi** [comment]
I don't know the exact details of how the gateway is supposed to work, but the last time I remembered I had to install it in the client only?

**Comment by miralita** [comment]
Yes, plugin works with client-only installation, but "Help -> Register" window shows licenses from host (Goland in my case).  After I installed the plugin on the host, the license on the client was also picked up automatically.
