### ISSUE TITLE
Add support for IntelliJ IDEA 2022.1 EAP

### ISSUE THREAD

**Issue by alin-simionoiuDE** [ChrisRM/material-theme-jetbrains#1861]
IntelliJ IDEA 2022.1 EAP has been released

**Comment by pgnd** [comment]
@mallowigi 
Was this closed because there _is_ a 2022.1-EAP-compatible upgrade for the paid-plugin available?
I don't see either a recent tag or PR ...

**Comment by mallowigi** [comment]
This repository is archived.

--
Elior
