### ISSUE TITLE
Custom theme colors disappear after restarting IDE

### ISSUE THREAD

**Issue by dev1way** [ChrisRM/material-theme-jetbrains#1862]
### Summary

After IDE restart, applied custom theme resets to previous choosen theme (as for me its darkula)

### Expected behavior

After selecting custom theme, customizing it and restarting IDE, a can continue coding with my new customized theme

### Actual behavior

After selecting custom theme, customizing it and restarting IDE, the colors are reseted to previous state (as for me its material dark)

### Steps to reproduce (if needed)

1. Override Material Dark theme and change any one color
2. Apply changes and agree with selecting custom theme
3. Restart IDE

### Environment

Android studio Arctic Fox Patch 1

**Comment by mallowigi** [comment]
This has been fixed in latest versions, I'll try to see if I can make the changes work in older versions for android users

**Comment by dev1way** [comment]
I see that I already have the latest version:
![image](https://user-images.githubusercontent.com/25363842/152304667-068d39cf-9275-46bb-bbca-e63f0cd52820.png)

**Comment by mallowigi** [comment]
It's not the latest version. But like I said Android Studio uses an older version of the IntelliJ base, which does not include the mentioned fix.

**Comment by dev1way** [comment]
Is there any information about andorid studio?

**Comment by 1wayOnly** [comment]
Можно какую-нибудь информацию? Ты закрыл её потому что я русский?

**Comment by dev1way** [comment]
Any information?

**Comment by mallowigi** [comment]
I'm not working on older versions anymore. You'll have to use Android Bumblebee

**Comment by mallowigi** [comment]
Кстати у меня нет проблем с русскими (кроме государство) :)

**Comment by dev1way** [comment]
Thanks a lot!
