### ISSUE TITLE
Editor Font Size resets after restarting Rider

### ISSUE THREAD

**Issue by estebanfeldman** [ChrisRM/material-theme-jetbrains#1865]
### Summary
Changing the Font size will be reset next time I open Rider again.
...

### Expected behavior

Keep Editor font size to the one I set previously
...

### Actual behavior

Editor Font is reset to default every time Rider is restarted
...

### Steps to reproduce (if needed)

1. First step

Change Editor Font Size

2. Second step

Restart Rider

I opened a bug with Jetbrains but disabling Material Theme fixes the problem, hence I'm here now.

Here is the link to the bug report with all the detailed data, please take it from there

https://youtrack.jetbrains.com/issue/RIDER-74252

**Comment by mallowigi** [comment]
wrong repo

**Comment by estebanfeldman** [comment]
Sorry
