### ISSUE TITLE
(Some) custom colours are not restored correctly on startup

### ISSUE THREAD

**Issue by peppy** [ChrisRM/material-theme-jetbrains#1868]
In recent times, my custom colours are not correctly restored.

Here is an example of how I fix the issue:

https://user-images.githubusercontent.com/191335/154602386-c13664a5-78e4-4ff3-b8eb-4aa9473a0b0a.mp4

Note that before I made a 0x01 hex change to my custom colours, the rider interface is using a blue colour, rather than my specified gray theme. Once making an arbitrary change, the correct colours stick until next restart of Rider.

Note that this has been happening for a while now and should not be considered related to my use of EAP builds. Unfortunately i can't give an exact time frame of when it started. Please let me know if you need my configuration files.

```csharp
JetBrains Rider 2022.1 EAP 3
Build #RD-221.4501.83, built on February 17, 2022
Licensed to JetBrains Rider EAP user: pe@ppy.sh
Expiration date: March 19, 2022
Runtime version: 11.0.14+9-b1993.2 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
.NET 6.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 32
Registry:
    search.everywhere.actions=false
    search.everywhere.toolwindows=false
    idea.true.smooth.scrolling.interpolation.precision.touchpad=false
    ide.mac.pressAndHold.workaround=false
    search.everywhere.configurations=false
    external.system.configuration.import.enabled=false
    select.run.configuration.from.context=false
    ide.web.preview.enabled=false
    ide.tooltip.initialDelay=400
    run.popup.move.folders.to.top=true
    ide.balloon.shadow.size=0
    rider.enable.designer.winForms=false
    rdclient.asyncActions=false
    indexing.enable.entity.provider.based.indexing=false
    ide.new.project.model.index.case.sensitivity=true

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.27.0)
    izhangzhihao.rainbow.brackets (6.21)
    com.chrisrm.idea.MaterialThemeUI (7.0.0)
    AceJump (3.8.5)
    IdeaVIM (1.10.0)

```

**Comment by peppy** [comment]
Is this fixed in a new release? I've temporarily stopped using the plugin while waiting for a fix so it would be great to know if that's the case.

**Comment by mallowigi** [comment]
I fixed a lot of issues with EAP in the latest release, I haven't checked this one specifically though.

I'll test and tell you.

**Comment by peppy** [comment]
Thanks. Worth noting that this one in particular was applicable before EAP (has been happening for a while now).
