### ISSUE TITLE
Application menus have too much vertical padding on update to 6.14.1

### ISSUE THREAD

**Issue by rmoskal** [ChrisRM/material-theme-jetbrains#1870]
### Summary
I updated to the latest version of the plug-in yesterday and suddenly my pull-down menus in all jetbrains products are messed up.

...

### Expected behavior
I expect a reasonable spacing between the menu items.
...

### Actual behavior
lots of space between the menu items. See attached.
...

### Steps to reproduce (if needed)

1. update the theme
2. restart ide
![Screenshot from 2022-03-19 12-29-37](https://user-images.githubusercontent.com/562035/159130142-112e1418-b595-4b7f-9bb6-37428d40a95d.png)

You can also add Screenshots for a better understanding.

### Environment
PyCharm 2021.3.3 (Professional Edition)
Build #PY-213.7172.26, built on March 16, 2022
Licensed to Robert Moskal
Subscription is active until March 22, 2022.
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.16.14-200.fc35.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 28048M
Cores: 16
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.intellij.plugins.eclipsekeymap (213.5744.3)
    com.mallowigi (54.1.0)
    com.chrisrm.idea.MaterialThemeUI

Current Desktop: GNOME

-------------------------

<application>
  <component name="MaterialThemeConfig">
    <option name="allowDataCollection" value="true" />
    <option name="pristineConfig" value="false" />
    <option name="tabFontSizeEnabled" value="true" />
    <option name="tabFontSize" value="24" />
    <option name="accentColor" value="7e57c2" />
    <option name="selectedTheme" value="NIGHT_OWL" />
    <option name="userId" value="683f40cd:17925c72a6e:-8000" />
    <option name="version" value="6.14.1" />
  </component>
</application>

**Comment by mallowigi** [comment]
I can't reproduce, maybe this is a Linux issue. In any case, please try to enable "Compact Menus" from the Settings.

**Comment by rmoskal** [comment]
Enabling compact menus fixed it right up.  I'll leave it to you to close the ticket if you don't feel like digging deeper into linux issues.

**Comment by krisdages** [comment]
Would it be possible to make the height customizable for "compact menus"? I had the same issue, and enabling compact sort of fixed it, but now they're *too* short. :)

**Comment by mallowigi** [comment]
I tried on a linux machine (Ubuntu) and yet couldn't reproduce the problem. @krisdages is the issue on another linux distro as well?
