### ISSUE TITLE
Creating a new file text box need some padding 

### ISSUE THREAD

**Issue by Abdelraman** [ChrisRM/material-theme-jetbrains#1871]
### Summary
right click, create a new file, pops up a window to enter the file name this window text box is very narrow that the whole text doesn't appear, It seems that it needs some vertical padding

* OS (Windows)
* IntelliJ Product + version (phpstorm 2021.3.3)
* Plugin version 6.16.2

kindly check the attached screen shot
![image](https://user-images.githubusercontent.com/4821833/163199047-47e25c1a-a872-4e1c-ad48-f1d80280ebc8.png)

**Comment by mallowigi** [comment]
Unfortunately this is the maximum height I can provide, since apparently the new popup is fixed in height, give it more and the text box is cropped. That being said the top and left margins are a bit off, but nonetheless the version 6 is closed, so please update as soon as you can.

**Comment by Abdelraman** [comment]
Thanks @mallowigi for your efforts
