### ISSUE TITLE
[Help wanted] Activate the plugin offline

### ISSUE THREAD

**Issue by Dragon1573** [ChrisRM/material-theme-jetbrains#1872]
## Summary

- I bought a license and it's currently valid, but I can't activate the plugin with my JetBrains Account.
- I'm behind a proxy. The proxy could NOT be bypassed or disabled.
- The proxy blocked the whole Apex Domain of `*.jetbrains.com`.
- There's an activation server provided by the proxy administrator, we use this server for activating IDEs.
- I tried to activate **Material Theme UI** with the server, but there's NO matching license.

Is there any methods that I can get the **Activation Code** of my license and activate the plugin offline manually?

## Environment

**Note**: To protect security and privacy, some information is masked.

```text
PyCharm 2021.1.3 (Professional Edition)
内部版本号 #PY-211.7628.24，June 30, 2021 构建
Licensed to XXXXXXXXXX Co., Ltd.

运行时版本: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.andrey4623.rainbowcsv (2.0.1), com.XXXXXX.intellij.plugin.foundation (1.7.2), com.chrisrm.idea.MaterialThemeUI (6.7.2), com.intellij.ideolog (203.0.28.1), com.intellij.zh (211.247), indent-rainbow.indent-rainbow (1.7.0), izhangzhihao.rainbow.fart (1.3.6), net.seesharpsoft.intellij.plugins.csv (2.18.2), mobi.hsz.idea.gitignore (4.1.0), izhangzhihao.rainbow.brackets (6.18), com.kite.intellij (1.9.4)
```

**Comment by mallowigi** [comment]
Please ask such questions to JetBrains directly.
