### ISSUE TITLE
File Status Colors Revert

### ISSUE THREAD

**Issue by prevtakumiy** [ChrisRM/material-theme-jetbrains#1873]
I'm using the Moonlight theme and the File Status Colors Unknown was set to 7AF8CA, 

![スクリーンショット 2022-04-22 17 58 48](https://user-images.githubusercontent.com/8855351/164679193-c56e0cad-ec71-4abd-919b-7c203cc28992.png)

so I reset it to D1675A with Restore DEFAULT. 

![スクリーンショット 2022-04-22 18 24 06](https://user-images.githubusercontent.com/8855351/164679642-9dcfbc8e-03e4-4aba-8451-68c03ebe40b6.png)

However, uncheck Override Accent Color from Theme,

![スクリーンショット 2022-04-22 18 43 28](https://user-images.githubusercontent.com/8855351/164681945-1b9581e2-4077-478a-83e5-d9c909187403.png)

 it will return to the original 7AF8CA.

![スクリーンショット 2022-04-22 18 43 45](https://user-images.githubusercontent.com/8855351/164681997-8592bccd-eb71-4faa-8f98-2f5b6dac398d.png)

OS: macOS Monterey 12.3.1
IDE: IntelliJ IDEA 2022.1
Material Theme UI: 7.3.2
Atom Material Icons: 62.0.0

**Comment by mallowigi** [comment]
Please open in the material-theme-issues repository.
