### ISSUE TITLE
Annoying Icons From Material Theme & Material Icon

### ISSUE THREAD

**Issue by SupianIDz** [ChrisRM/material-theme-jetbrains#1878]
### Summary

To remove the material icon on the menu I tried to remove it via

1. Appearance & Behavior > Menus & Toolbar > find "Atom File Icon Settings" and delete it.
2. Appearance & Behavior > Menus & Toolbar > find "Material Theme" and delete it.

But that hasn't changed, the icon is still showing. This annoys me quite a bit, as that setting is used very rarely.

<img width="534" alt="Screen Shot 2022-07-27 at 10 35 40" src="https://user-images.githubusercontent.com/37969970/181148401-154f2cd2-6e28-4f10-a47a-43713357195d.png">

### Expected behavior
Both icons disappeared

### Actual behavior
There is no change at all.

### Environment

IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to Octopy ID / Supian M
Subscription is active until March 6, 2023.
Runtime version: 17.0.3+7-b469.32 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    project.tree.structure.show.url=false
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    com.intellij.plugins.expui (0.4)
    com.mallowigi (65.1.0)
    com.jetbrains.php (222.3345.118)
    com.chrisrm.idea.MaterialThemeUI (7.7.0)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by mallowigi** [comment]
Customization of the title bar is not yet available in the new ui. 

Please follow YouTrack issues for when this will be available. In the meantime I won't remove this icon so please bear with it.
