### ISSUE TITLE
The Material Theme is not compatible  with idea 2022.2

### ISSUE THREAD

**Issue by sukai-cheng** [ChrisRM/material-theme-jetbrains#1880]
when i turn on new UI option, it will be mess

There are a lot of problems pls solve it as soon as possible , thanks

<img width="824" alt="image" src="https://user-images.githubusercontent.com/35868545/184789701-b385cb97-eb01-4ac3-bf64-9761a94ecea0.png">

The Material Theme is not compatible

**Comment by mallowigi** [comment]
Can you post your settings?

**Comment by mallowigi** [comment]
Please report on the material-theme-issues repository thanks.
