### ISSUE TITLE
java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by ghost** [ChrisRM/material-theme-jetbrains#1882]
### Summary

Exception occur on project load

### Expected behavior

No throw exception

### Actual behavior

Throws exception

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.

Error: https://paste.gg/p/anonymous/85df13b01f55471099a694a7adf6c06a

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file. To find your configuration file, see: https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs. On Ubuntu this could be `~/.IntelliJIdea2019.1/config/options` for example.

Note that not providing any of the required info will result of your issue being closed.

IntelliJ IDEA 2022.2.2 (Community Edition)
Build #IC-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    editor.focus.mode.color.light=6b727d
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=6b727d

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (222.4167.35)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    com.chrisrm.idea.MaterialThemeUI (7.12.0)
    com.demonwav.minecraft-dev (2022.2-1.5.21)

Kotlin: 222-1.7.20-release-201-IJ4167.29

**Comment by mallowigi** [comment]
Please reinstall the plugin and reinstall version 7.11.0. Version 7.12.0 should have been available for Android Studio only but apparently it also targets Community users. I'll delete this version and try again to only target AS users.
