### ISSUE TITLE
IntelliJ gets stuck on "unloading plugin" dialog if Material Theme UI is enabled

### ISSUE THREAD

**Issue by Lootwig** [ChrisRM/material-theme-jetbrains#1885]
### Summary

So far, this seems to apply to multiple plugins, but I can reliably reproduce e.g. with the tailwindcss plugin. If Material Theme UI is enabled, IntelliJ just hangs in the "unloading" window and I need to force close it. Only when I disable Material, I can disable other plugins normally.

### Steps to reproduce (if needed)

1. Have Material Theme and tailwindcss enabled
2. uncheck tailwindcss in plugins
3. Hit "apply", dialog runs forever (see video below)

### Environment

IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to David Schneider
You have a perpetual fallback license for this version.
Subscription is active until September 28, 2025.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6
GC: G1 Young Generation, G1 Old Generation
Memory: 6000M
Cores: 10
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=474747
    ide.editor.tab.selection.animation=true
    terminal.persistent.tabs=false
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=474747
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    org.tbm98.flutter-riverpod-snippets (2.222.1)
    io.github.tbm98.flutter_generator_snippets (2.222.1)
    com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete (0.4.1)
    org.jetbrains.kotlin (222-1.7.20-release-201-IJ4167.29)
    org.intellij.plugins.postcss (222.4345.14)
    com.bloc.intellij_generator_plugin (3.3.0)
    com.antkorwin.unicoder (1.0)
    Statistic (4.2.6)
    Realigner (1.6.0)
    IdeaVIM (1.11.1)
    com.github.copilot (1.1.34.2009)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    intellij.prettierJS (222.4345.14)
    dev.blachut.svelte.lang (0.22.1)
    zielu.gittoolbox (212.9.9)
    Pythonid (222.4345.14)
    org.exbin.deltahex.intellij (0.2.6)
    com.chrisrm.idea.MaterialThemeUI (7.13.2)
    GLSL (1.21)
    Dummy Text Generator (1.2.0)
    Dart (222.4345.14)
    izhangzhihao.rainbow.brackets (6.26)
    io.flutter (70.2.5)
    de.mariushoefler.flutter_enhancement_suite (1.6.0)
    com.localizely.flutter-intl (1.17.3-2020.3)
    com.github.hayoi.haystack (1.3.01)
    andrasferenczi.dart-data-plugin (0.2.0)

Kotlin: 222-1.7.20-release-201-IJ4167.29

https://user-images.githubusercontent.com/39827040/197175032-2cf7af26-d099-4d6d-8007-692afc8c00dd.mov

**Comment by mallowigi** [comment]
There's nothing I can do about this. If there are no errors whatsoever related to the plugin so I'm declining responsibility.

Please report to JetBrains.
