### ISSUE TITLE
Incorrect text display

### ISSUE THREAD

**Issue by pavel-hushcha** [ChrisRM/material-theme-jetbrains#1886]
### Summary

Incorrect display of strings in *.feature files.

### Expected behavior

Vertical lines must be aligned with each other.
![image](https://user-images.githubusercontent.com/73911482/199803846-6eadcb08-38e4-4b4f-8790-88e3fb8be15c.png)

### Actual behavior

Vertical lines are not aligned.
![image](https://user-images.githubusercontent.com/73911482/199804112-781d714d-feb2-4aba-bec6-de54114bc1e4.png)

### Steps to reproduce (if needed)

1. Create *.feature file
2. Add scenario
3. Add strings with vertical lines

You can also add Screenshots for a better understanding.

### Environment

PyCharm 2022.2.3 (Professional Edition)
Build #PY-222.4345.23, built on October 10, 2022
Licensed to *******
You have a perpetual fallback license for this version.
Subscription is active until November 14, 2023.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=828bb8
    ide.editor.tab.selection.animation=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=828bb8

Non-Bundled Plugins:
    name.kropp.intellij.makefile (222.4345.14)
    indent-rainbow.indent-rainbow (2.0.2)
    com.tabnine.TabNine (0.7.27)
    org.intellij.plugins.hcl (222.4345.14)
    Key Promoter X (2022.3)
    zielu.gittoolbox (212.9.9)
    org.sonarlint.idea (7.1.1.54565)
    com.mallowigi (73.0.0)
    com.intellij.swagger (222.4345.14)
    izhangzhihao.rainbow.brackets (6.26)
    com.chrisrm.idea.MaterialThemeUI (7.14.2)

**Comment by mallowigi** [comment]
This is due to the ligatures:

![CleanShot 2022-11-03 at 22 25 25](https://user-images.githubusercontent.com/5015756/199826854-16cae05d-6f92-447c-b312-d0f7b1f1b886.png)

Since there's a ligature that transform fi to ﬁ, it shows one character instead of two, which induces the renderer on error. This is not related to the plugin but to the color scheme that enables ligatures by default.

Just disable the ligatures if it bothers you that much.

**Comment by pavel-hushcha** [comment]
@mallowigi thanks a lot, it works 👍
