### ISSUE TITLE
Markdown ``` tag

### ISSUE THREAD

**Issue by marcossegovia** [ChrisRM/material-theme-jetbrains#189]
Hi there, as you can see in the image attached, it is pretty difficult to visualize content within the ``` tag

![captura de pantalla 2016-05-07 a las 19 53 13](https://cloud.githubusercontent.com/assets/7728566/15093626/91228da8-148d-11e6-8d8e-22e30b2c4c66.png)

Is there anyway the plugin can do something to it?

Ty !

**Comment by mallowigi** [comment]
should be fixed in the latest release
