### ISSUE TITLE
UI Problem with WebStorm 2016.1, windows 10

### ISSUE THREAD

**Issue by rjorge99** [ChrisRM/material-theme-jetbrains#190]
Hi, I just installed the theme, and it changed the color of the editor, and some other parts, but for some reason i can not see the icons that you show in the example pictures. I see a normal file, edit.... menu. Also if I change the theme to darker, defaul, etc. It only changes the editor area, not the UI in general. Is there any extra steps to setup all the enviroment correctly? 
Thanks  This is the image of the current UI.

![screenshot_1](https://cloud.githubusercontent.com/assets/17952147/15095329/0855f07e-1487-11e6-982c-53624c4ec1de.jpg)

**Comment by ChrisRM** [comment]
As stated in the readme:

    This plugin will not set the new color scheme for you, as that would cause a couple problems. You need to set the new color scheme manually:

    1. Open the **Settings/Preferences** dialog again.
    2. In the left-hand pane, select **Editor** -> **Colors & Fonts**.
    3. In the **Scheme** dropdown, you'll find 3 new schemes: `Material Theme - Default`, `Material Theme - Darker` and `Material Theme - Lighter`. 
    4. Choose the scheme you like and hit **Apply** and **OK**.

    Shortcut: <kbd>Ctrl+'</kbd> (that's a backtick) then hit `1. Color scheme` and select your desired color scheme. 

To show the toolbar icons, go to `View` and click on `Toolbar`
