### ISSUE TITLE
Not Sure How to Change Background Color of Selected Line

### ISSUE THREAD

**Issue by dschinkel** [ChrisRM/material-theme-jetbrains#1902]
I cannot for the life of me figure out how to tweak selected the line color.  It's too light of a blue here.  I've been able to tweak everything else it seems under Editor | Color Scheme | General

<img width="1004" alt="Screenshot 2023-08-13 at 1 04 35 AM" src="https://github.com/ChrisRM/material-theme-jetbrains/assets/338798/5e93543d-1669-439a-bfca-7fb82a72ef64">

<img width="1155" alt="Screenshot 2023-08-13 at 1 06 49 AM" src="https://github.com/ChrisRM/material-theme-jetbrains/assets/338798/03a69401-08b1-40ef-ae15-300dc6145bd1">

**Comment by mallowigi** [comment]
Caret row
