### ISSUE TITLE
Project Pane is not changing to selected theme

### ISSUE THREAD

**Issue by dschinkel** [ChrisRM/material-theme-jetbrains#1903]
Webstorm 2023.2
Build WS-232.8660.143 (July21, 2023)

The Project Pane is not changing after I select a different theme.  Previous theme I had selected is still showing as the Project Pane theme...but it should show the Github Theme

<img width="1281" alt="Screenshot 2023-08-13 at 1 14 37 AM" src="https://github.com/ChrisRM/material-theme-jetbrains/assets/338798/2f4488f8-8005-44dd-97a8-a75ea9301c4b">
<img width="2560" alt="Screenshot 2023-08-13 at 1 14 43 AM" src="https://github.com/ChrisRM/material-theme-jetbrains/assets/338798/c19a4d9b-2d4d-46f6-9125-6a3f392b95e3">

**Comment by mallowigi** [comment]
You changed the color scheme.

**Comment by mallowigi** [comment]
Also wrong repo

**Comment by dschinkel** [comment]
Yea I always get confused where to change this stuff as there are 2 areas in prefs.  Sorry for posting in the wrong repo, I keep forgetting where to post this stuff.
