### ISSUE TITLE
Cannot Activate Plugin

### ISSUE THREAD

**Issue by daveschinkel** [ChrisRM/material-theme-jetbrains#1908]
Trying to activate my free version.  It says it will show the activate window when settings are closed, but never happens.  I click the activate button, click OK to get out of preferences, this causes IntelliJ to prompt me to restart.  I restart and then I never see an activation window

As you can see the activate button turned to scheduled but nothing ever came up

<img width="1147" alt="Screenshot 2023-10-18 at 4 51 26 PM" src="https://github.com/ChrisRM/material-theme-jetbrains/assets/146210003/b9f1e4e9-3a9d-4ced-91f5-19ec7e10b60b">

**Comment by mallowigi** [comment]
Go to Menu > Help > Buy/Register
