### ISSUE TITLE
Cannt find Material Theme - Default, Material Theme - Darker

### ISSUE THREAD

**Issue by a1219062954** [ChrisRM/material-theme-jetbrains#191]
Cannt find Material Theme - Default, Material Theme - Darker ,just Material Theme - Lighter.

**Comment by bullboa** [comment]
Have you looked under **Tools** -> **Material Theme** -> [**Darker Theme**, **Default Theme**, **Lighter Theme**]?
I had trouble finding it first as I don't have the GUI set up exactly as in the screenshots.

**Comment by mazzy89** [comment]
My same issue

**Comment by siddharthsudheer** [comment]
Having the same issue here! I dont see Material Theme under Tools

**Comment by eloquentbit** [comment]
Same issue here. No Material Theme under Tools
IntelliJ IDEA 2016.2.2
Build #IC-162.1628.40, built on August 16, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by eloquentbit** [comment]
Ok, my mistake. The option is under Tools menu (on the menubar) and not under the Tools in the Settings window
