### ISSUE TITLE
Bug in gutter in Intelij on latest Material UI and IDE update.

### ISSUE THREAD

**Issue by craigmain** [ChrisRM/material-theme-jetbrains#1911]
### Summary

The IDE has a huge gutter between the left hand pane and the line numbers.
This gutter is present whether or not the line numbers are ON or OFF, and seems unaffected by annotations.
The main editor window should be left aligned and not have a huge gutter.

...

### Expected behavior

There is no gutter
...

### Actual behavior
There is a huge gutter.
...

### Steps to reproduce (if needed)

1. Open an editor
2. Maximise windows
3. Gutter Appears

You can also add Screenshots for a better understanding.
![image](https://github.com/ChrisRM/material-theme-jetbrains/assets/137081829/0a6552ef-ee54-4652-8e4a-9cccff73d114)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Licensed to Craig Main
Subscription is active until April 30, 2024.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8096M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.distraction.free.mode=true
  editor.focus.mode.color.light=415967
  editor.focus.mode.color.dark=415967
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  IdeaVIM (2.10.2)
  org.jetbrains.jumpToLine (0.1.15)
  String Manipulation (9.12.0)
  PlantUML integration (7.8.1-IJ2023.2)
  com.intellij.ml.llm (241.14494.240)
  com.github.copilot (1.5.2.5345)
  com.haulmont.jpab (241.14494.158)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.chrisrm.idea.MaterialThemeUI (9.1.0)
  SequenceDiagram (3.0.8)
  com.dmarcotte.handlebars (241.14494.150)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.2.3+233)
  aws.toolkit (2.17-241)
Kotlin: 241.14494.240-IJ

**Comment by craigmain** [comment]
I took the time to try this with a brand new installation (clean) of intelij and material theme, and the problem is there, so I don't think it's an issue just with my imported configuration / other plugins.

**Comment by craigmain** [comment]
[material_theme.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/14906756/material_theme.zip)
I have added the material UI configuration files to the ZIP.

**Comment by mallowigi** [comment]
this repository is archived
