### ISSUE TITLE
When I change the IDE's font, then restart the IDE, it return to default font.

### ISSUE THREAD

**Issue by lylong616** [ChrisRM/material-theme-jetbrains#194]
As the title description, I operate as the follow steps.
Preference -> Appearance & Behavior -> UI Options -> Theme's second option Override default fonts by (not recommended) Name : "Choose the font you want" , Size: font size. Then I apply the changes. 

When I restart the IDE, the IDE's font change to default. Could fix this issue. Thanks very much.

**Comment by twaileit** [comment]
You better copy the theme and edit it then.
PHPStorm 2016.1 doesn't even allow to edit the theme (which is what I saw).

**Comment by pejaham** [comment]
I have a similar problem with that might be related running IntelliJ 2016.2 under Ubuntu 16.04/Gnome3 on a HiDPI monitor.

I scale the Gnome3 HiDPI to 2 and double the font size within IntelliJ to around 26 to make it look proportionally good (like font size 13 on a normal screen). With the Materialize plugin IntelliJ starts up with the font in double (=26) size, in preferences I change the font to something else and back to 26 and everything looks OK. After restarting IntelliJ the font is too large again. Also - when I change the Materialize font from darker to lighter the font size is doubled.

It looks like Materialize does some resetting of font size and/or ignoring HiDPI related stuff.

I really like the Materialize theme - but resetting the font size every time I startup the IDE is kind of a pain. It works great on OS-X with my HiDPI monitor.

**Comment by spawn-guy** [comment]
on win10 15" 4K display with the scaling factor set to 250% i get really small icons in file browser as well as Editor scheme' text setting is not scaled at all.
i do see proper scaling with both Darcula themes (theme and editor).

phpStorm 2016.1.2

**Comment by thusfar7** [comment]
Anyone? Anything?

**Comment by thusfar7** [comment]
Anyone? Anything?

**Comment by SalahAdDin** [comment]
@ChrisRM Not yet!

**Comment by vampirebitter** [comment]
the same error on Ubuntu16.04

**Comment by drgomesp** [comment]
Same issue on OSX

**Comment by thebasix** [comment]
No one gives a ...

**Comment by wejder** [comment]
there is a solution. it works for me ;D

PHPStorm -> Settings -> Appearance -> Override -> 12 -> Apply -> 11 -> Apply -> work -> exit -> sleep -> wake up -> return to line 1 ;D

**Comment by dandelionmood** [comment]
Same problem here with latest PHPStorm on Ubuntu 16.04 … That's a shame really :( …

**Comment by mallowigi** [comment]
I fixed it in my repo:

https://github.com/mallowigi/material-theme-jetbrains

Haven't tested it in PHPStorm though

**Comment by SalahAdDin** [comment]
@mallowigi Did you make a pull request?

**Comment by denofevil** [comment]
Duplicates #54
