### ISSUE TITLE
After install lock in PhpStorm 

### ISSUE THREAD

**Issue by pgrekovich** [ChrisRM/material-theme-jetbrains#195]
I have app lock after this plugin installed. Some restart of  the app didn't help me. But, if i  will delete iconloader.jar from plugin folder, all will work fine. 

- Windows 10 Pro x64
- PhpStorm 2016.1.1

**Comment by jzyinq** [comment]
I have same spec and same issue appears. Thanks for temporary fix though.

**Comment by mikeerickson** [comment]
@pgrekovich @jzyinq FYI, current version of plugin is black listed by JetBrains

see here https://github.com/ChrisRM/material-theme-jetbrains/issues/205

**Comment by ChrisRM** [comment]
I'm going to update the original issue #205 with the progress. Closing this.
