### ISSUE TITLE
Color scheme issues

### ISSUE THREAD

**Issue by SalahAdDin** [ChrisRM/material-theme-jetbrains#198]
Hi man, thank you for your theme, i could show to my parners that PyCham isn't less than Sublime because MaterialUI Theme.

I want put here twoo color scheme issued that maybe will be important:
- First: 
  ![contrastenomuyvisible](https://cloud.githubusercontent.com/assets/5034215/15781071/1bd979f2-296a-11e6-99f2-e3cd8f284252.png)  
  Can you see anything here? The contrast isn't easy to see, the case is this: i select this variable and i want edit the `Match`part, chagen for other word; theme take all variable and put a background color for show that this variable was selected, i think so, but, put a background color a littler darker than other, over the part of word selected, but this color isn't enough darker than the other color and we can't see witch part was selected.
  I think that put a more darker color for background will be better.
- Second:
  ![negronosevebienahi](https://cloud.githubusercontent.com/assets/5034215/15781070/1bd509d0-296a-11e6-84a2-e5200d85ef73.png)
  The general background color is dark, and the class name color is black, so, can you see easy the class name? I can, but, isn't easy to see. 
  I think that will be better this color by other with better contrast with the background.
- Third:
  ![moradonose ve bien](https://cloud.githubusercontent.com/assets/5034215/15781451/c7cfeb28-296b-11e6-9bdb-859ebe893214.png)
  In the same way, this purple, well, i think that haven't good contrast with the backgroud, i think, it's annoying to my eyes.

Thank you very much man!

**Comment by Robula** [comment]
Same issue in PyCharm 2016.1.4

**Comment by mallowigi** [comment]
Should be fixed in the last release
