### ISSUE TITLE
Question on color scheme for RubyMine

### ISSUE THREAD

**Issue by supercodepoet** [ChrisRM/material-theme-jetbrains#199]
I love this plugin but the color scheme for Ruby/Rails code really doesn't look like the code in the same file in Sublime Text with Material Theme. Am I missing something?

**Comment by SalahAdDin** [comment]
Put here your comparations please.

**Comment by alexandcote** [comment]
Here Ruby Style:
<img width="1300" alt="screen shot 2016-06-13 at 10 51 10 pm" src="https://cloud.githubusercontent.com/assets/4728325/16029774/6df9dc16-31b9-11e6-9168-601759a59d37.png">

Here ERB Style:
<img width="476" alt="screen shot 2016-06-13 at 10 51 18 pm" src="https://cloud.githubusercontent.com/assets/4728325/16029776/824c6eea-31b9-11e6-8e8e-10a5d17c366d.png">

**Comment by supercodepoet** [comment]
These are form Sublime Text:

Ruby Style:

<img width="1087" alt="screen shot 2016-06-14 at 7 34 56 am" src="https://cloud.githubusercontent.com/assets/249366/16042892/a2f24ec8-3202-11e6-95f2-f174536b1fe1.png">

ERB Style:

<img width="1054" alt="screen shot 2016-06-14 at 7 36 36 am" src="https://cloud.githubusercontent.com/assets/249366/16042919/c8110fb4-3202-11e6-8491-e6ee93f56f97.png">

**Comment by alexandcote** [comment]
I found a simple solution, just check `use inherited attributes` and you will be able to read your code.
![screen shot 2016-06-17 at 1 10 36 pm](https://cloud.githubusercontent.com/assets/4728325/16158785/f463f41e-348c-11e6-9a45-f4e9bf4c77d3.png)

**Comment by mannykary** [comment]
@supercodepoet - I was able to make the colors look like those in Sublime by getting the [original Material Theme .tmTheme file](https://github.com/equinusocio/material-theme/blob/develop/schemes/Material-Theme.tmTheme) and converting it to XML using Jetbrains' [colorSchemeTool](https://github.com/JetBrains/colorSchemeTool).

After I converted to XML, I just copied it to `~/Library/Preferences/<JETBRAINS APP>/colors/` (on OS X -- substitute <JETBRAINS APP> for your app, and create the colors directory if it doesn't exist). Then I restarted the IDE and selected the new scheme file in Preferences > Editor > Colors & Fonts.

I've put the XML file in my repo [here](https://github.com/mannykary/editor-themes/blob/master/idea/Material-Theme.xml), in case you're interested. 

@alexandcote - Perhaps the XML file that I generated can be adapted into this repo somehow.

**Comment by mannykary** [comment]
Here is what the colors look like with the new XML:

Ruby
<img src="http://imgur.com/cpBK17a.png">

ERB
<img src="http://imgur.com/fgZMAdV.png">

**Comment by supercodepoet** [comment]
@mannykary very sweet! Thanks will use for sure.

**Comment by mannykary** [comment]
@supercodepoet - I submitted a [PR](https://github.com/ChrisRM/material-theme-jetbrains/pull/232) that should fix the color issues. The reason why it looks so bad is because they were missing for Ruby and ERB (as well as Python, Django, and SASS).

**Comment by pharbod** [comment]
@mannykary so you changed value of ` INJECTED_LANGUAGE_FRAGMENT`? tried changing it via config > colors > Material Theme - Default copy.icls, restart, But didn't work for me. still the white background for injected code (ERB).

**Comment by mannykary** [comment]
@pharbod - not sure exactly what you mean, but the way I did it was I placed the modified color scheme in the config folder. (If you haven't already, you can grab my modified color schemes [here](https://github.com/ChrisRM/material-theme-jetbrains/pull/232/files)).

Depending on your OS, you'll have to place it in the `colors` folder (create it it doesn't exist):

OS X: `~/Library/Preferences/RubyMineXX/colors/`
Linux: `~/.RubyMineXX/config/colors`
Windows: `<USER HOME>\.RubyMineXX\config\colors`

(replace RubyMineXX with the name of your IDE)

Then restart the IDE and you should be able to select the new color scheme in Preferences (or Settings) > Editor > Colors & Fonts.

**Comment by marat-chardymov** [comment]
`@supercodepoet - I submitted a PR that should fix the color issues. The reason why it looks so bad is because they were missing for Ruby and ERB (as well as Python, Django, and SASS).`
@mannykary Have you already published these pull request changes? I'm using v0.2.1 of "Material Theme UI" plugin, still have issues with erb

**Comment by mannykary** [comment]
@marat-chardymov - I don't think that @ChrisRM (the owner of this repository) integrated my changes into the plugin yet. The PR that I submitted was merged to master, but there hasn't been a release/publish since then.

You can work around that by following the instructions in the [comment above](https://github.com/ChrisRM/material-theme-jetbrains/issues/199#issuecomment-247807596).

**Comment by pharbod** [comment]
Nevermind about editing code or manually replacing color scheme. Just go to setting > editor > colors and fonts > ERB, uncheck the background or set it to `32424A` if you want to. And you are all set :)

![screenshot_20160920_114828](https://cloud.githubusercontent.com/assets/13926209/18660912/54c1281e-7f28-11e6-90e3-0cd5dd6adf10.png)

**Comment by mannykary** [comment]
Cool, glad you figured it out.

FYI, I think the colors are a bit different in the actual Material theme,
but if you're happy with the way it looks now, then I would leave it as it
is. The cool thing is that you can make little tweaks here and there to
customize to your liking, which is what I ended up doing.

**Comment by mallowigi** [comment]
Closing this for the sake of old issues. It should be better in the next release.
