### ISSUE TITLE
Installation error in PhpStrom 9.0 and 9.5 (EAP)

### ISSUE THREAD

**Issue by shhetri** [ChrisRM/material-theme-jetbrains#2]
No matter how much I try, I get this error every time. I have tried the installation process in both PhpStrom 9.0 and 9.5 (EAP) in mac.

![phpstrom-materaial-theme-installation-error](https://cloud.githubusercontent.com/assets/6878832/10128902/ee6c6412-65d7-11e5-8a16-c7de411d59b5.png)

**Comment by ryanwinchester** [comment]
It works fine for me:

![screenshot](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screenshot+2015-09-27+23.15.19.png)

**Comment by shhetri** [comment]
I think JRE version is the problem. I have had java 1.8 installed in my system but PhpStrom is still using the old JRE version (1.6). I'll try to update that and see, if it works.

**Comment by ryanwinchester** [comment]
when i first installed phpstorm 9 it asked for JRE 1.6 I think.

try this version that is bundled with JDK 1.8 https://www.jetbrains.com/phpstorm/download/download_thanks.jsp?os=ws-jdk18

**Comment by ChrisRM** [comment]
Btw, do not use the EAP version for now. There will be a custom version for EAP builds.

**Comment by shhetri** [comment]
Installing PhpStrom with bundled JDK worked. I hope it looks as supposed to look like.

![screen shot 2015-09-28 at 3 05 39 pm](https://cloud.githubusercontent.com/assets/6878832/10131871/06ce3678-65f3-11e5-91e1-e5a847e468f5.png)

Thank you for the theme. :+1: 

The sidebar of preference pane looks off though.

![screen shot 2015-09-28 at 3 10 27 pm](https://cloud.githubusercontent.com/assets/6878832/10131893/3220df6a-65f3-11e5-9bac-3660e5ea82cc.png)

**Comment by ChrisRM** [comment]
Yeah, I haven't found a way to modify the preferences sidebar yet. Also, some ui elements like checkboxes, radio buttons etc will be improved.

**Comment by shhetri** [comment]
That's great.

**Comment by voydz** [comment]
@ChrisRM if you haven't already - maybe take a look into https://plugins.jetbrains.com/plugin/7055?pr=phpStorm there you will possibly find all the panes you need. At least this plugin does modify the preference sidebar, if I am not mistaken. Nevertheless awesome work!

**Comment by ChrisRM** [comment]
Thanks @voydz, I'll definitely look into that!
