### ISSUE TITLE
Change color excluded directories

### ISSUE THREAD

**Issue by sanderboom** [ChrisRM/material-theme-jetbrains#200]
Is there a way to change the color of the excluded directories (and library directories like `node_modules`) in the project panel? 

The current theming makes it rather stands out instead of fall away ;)

![image](https://cloud.githubusercontent.com/assets/5956570/16116527/be6f6f2e-33cd-11e6-9439-31da97f97c8c.png)

**Comment by SalahAdDin** [comment]
@ChrisRM I think that will be necessary improve many color in this theme.

**Comment by Zarriff** [comment]
Looks like this is actually a setting in PHPStorm using the Non-Project Files scope. See below.

![phpstorm_non_project_files](https://cloud.githubusercontent.com/assets/14187355/17063336/fc7fb4e2-5036-11e6-9b27-c9c1ebc22e42.jpg)

**Comment by sanderboom** [comment]
Thanks @Zarriff for pointing this out. A different default supplied by the theme would still be an improvement :)

**Comment by mallowigi** [comment]
Duplicate of #336
