### ISSUE TITLE
Small icons in 4K 28 inch monitor.

### ISSUE THREAD

**Issue by JakariaAmin** [ChrisRM/material-theme-jetbrains#204]
Thanks for the theme. But in my computer, the icons looks super small and tiny. Defaults icons was fine but this theme's icons are for some reason appearing very small. Also icons are kinda blurry, probably this theme is not DPI aware.
Here is a screenshot.
<img width="1038" alt="capture" src="https://cloud.githubusercontent.com/assets/11033159/16170712/14dca06c-358f-11e6-97e0-55e634593015.PNG">

4K 28 Inch monitor, DPI Scaling 150%.

**Comment by mallowigi** [comment]
Need to have an HiDPI computer with it... Help would be appreciated to determine all issues

**Comment by mallowigi** [comment]
Is this still relevant?

**Comment by musicformellons** [comment]
Seems I have same problem after upgrading to version 5.0 (I have hdpi screen).

**Comment by mallowigi** [comment]
I cant reproduce even though I'm on HiDPI :/

**Comment by JakariaAmin** [comment]
Thanks for reply, since the icons were too small to see, i disabled it last year. now installed the latest version and all the icons are in good size in my 4K 28 inch, 150% scaling. Thanks for fixing it.
