### ISSUE TITLE
Plugin disabled in latest Webstorm 2016.2 beta

### ISSUE THREAD

**Issue by vdclouis** [ChrisRM/material-theme-jetbrains#206]
![](https://cldup.com/Gvp_wJ0uTr.png)

**Comment by MingningShao** [comment]
I was also occurred such problem......

**Comment by talios** [comment]
As I mentioned in #205 4-5 days ago, the plugin is now blacklisted due causing breakages in other plugins ( see the linked youtrack ticket )

**Comment by Izopi4a** [comment]
is this fixable or is it gg wp?

**Comment by Delagen** [comment]
+1

**Comment by Izopi4a** [comment]
did anyone found an alternative dark theme ?

**Comment by roni-frantchi** [comment]
I can confirm the case remains for IntelliJ too.

**Comment by MingningShao** [comment]
I finally found an method to taken ui into effective,just reinstall intellij(rollback 2016.1 and reinstall 2016.2),and didn't update.Then it worked on.

**Comment by ChrisRM** [comment]
I'm going to update the original issue #205 with the progress. Closing this.
