### ISSUE TITLE
Stopped working on newest PhpStorm EAP build

### ISSUE THREAD

**Issue by nthrnth** [ChrisRM/material-theme-jetbrains#207]
PhpStorm 2016.2 EAP
Build #PS-162.1120.13, built on June 29, 2016

Problems found loading plugins:
Following plugins are incompatible with current IDE build: Material Theme UI

May be it's due to #205

**Comment by sidz** [comment]
@nthrnth Duplicated. https://github.com/ChrisRM/material-theme-jetbrains/issues/206

**Comment by mallowigi** [comment]
I've submitted a fix in my own fork, until the dev decides to merge it

**Comment by ChrisRM** [comment]
I'm going to update the original issue #205 with the progress. Closing this.
