### ISSUE TITLE
Bad visibility for diffs on default color scheme

### ISSUE THREAD

**Issue by marvhock** [ChrisRM/material-theme-jetbrains#209]
Hi, 
the current default color scheme lacks of good visibility for diffs. While its very important to see changes on a diff, I updated colors for diffs on PullRequest #208.

Original Diff:
![old](https://cloud.githubusercontent.com/assets/6747927/16493043/634e87fc-3ee4-11e6-96a4-37b047577ef5.png)

New Diff:
![new](https://cloud.githubusercontent.com/assets/6747927/16493044/634e5caa-3ee4-11e6-853a-fa2f9a6d3087.png)

- The contrast of changes is now clearly visibly (It was just dark blue before on multiple places)
- Deletion, Change, Conflict and Removal are clearly and correctly coloured now.

**Comment by ChrisRM** [comment]
Fixed in https://github.com/ChrisRM/material-theme-jetbrains/pull/208. Thanks @marvhock
