### ISSUE TITLE
Collapse/Expand nodes too subtle

### ISSUE THREAD

**Issue by mahngiel** [ChrisRM/material-theme-jetbrains#21]
The node handles could use a bit of lightness to allow them to standout without straining your eyes
![screenshot_42](https://cloud.githubusercontent.com/assets/1322045/10316588/3cc2cb92-6c1d-11e5-9df5-4d2d99eec34b.png)

**Comment by ChrisRM** [comment]
Agree! I'm on it

**Comment by ChrisRM** [comment]
Fixed. Added a lighter color for the handles
