### ISSUE TITLE
Compatibilty with PHPStorm

### ISSUE THREAD

**Issue by shaffe-fr** [ChrisRM/material-theme-jetbrains#210]
Hello,

The theme is not compatible with the latest PHPStorm build (PS-162.1120.13).

`Following plugins are incompatible with current IDE build: Material Theme UI`

**Comment by shaffe-fr** [comment]
Duplicated. #206

**Comment by ChrisRM** [comment]
I'm going to update the original issue #205 with the progress. Closing this.
