### ISSUE TITLE
Color scheme issues: select with DarkStyle

### ISSUE THREAD

**Issue by abkrim** [ChrisRM/material-theme-jetbrains#211]
I've seen quite a few open issues regarding the usability of the template void when it comes to the Dark Style, and the selection of a text, either in the editor or in the shell.

The truth is that the issue is very good, but it is a serious handicap that selection has a zero usability.

Is there any way to change it? I've been trying modifying the preferences but nothing.

![Image of Material Dark](https://dropbox.tamainut.net/owncloud/index.php/apps/files_sharing/ajax/publicpreview.php?x=1089&y=600&a=true&file=MigrateDatabase_php_-_setdart_-____desarrollos_setdart_.jpg&t=AFpeYrDIUWsTSgn&scalingup=0)

**Comment by SalahAdDin** [comment]
It's duplicated, i made the same issue, but, it's very important.

**Comment by mjdetullio** [comment]
I suggest making a copy of the scheme in Preferences -> Editor -> Colors & Fonts and then under General -> Editor -> Selection background change the value to `37474F` or whatever floats your boat.

I've been working a lot on tuning the scheme and may submit some updates, but mine is quite a bit more subdued compared to the standard highlighting so it may take awhile to consolidate.  My last personal scheme I found myself tweaking even after months of use, so it takes awhile to get everything right.

**Comment by abkrim** [comment]
A lot of thanks.-
