### ISSUE TITLE
It doesn't work with PyCharm

### ISSUE THREAD

**Issue by vienthet** [ChrisRM/material-theme-jetbrains#214]
After the restart the program just freezing, all the buttons are frozen as well so you can't do nothing i had to uninstall the ide and install again.

**Comment by SalahAdDin** [comment]
Until now PyCharm works fine me.

**Comment by jzyinq** [comment]
Check #195 for temporary fix

**Comment by ChrisRM** [comment]
I'm going to update the original issue #205 with the progress. Closing this.
