### ISSUE TITLE
Does not work with IDEA 2016.2 RC

### ISSUE THREAD

**Issue by ctongfei** [ChrisRM/material-theme-jetbrains#215]

**Comment by mradzinski** [comment]
+1

**Comment by atilkan** [comment]
+1

**Comment by SHEFFcode** [comment]
+1

**Comment by hotpixelgroup** [comment]
+1

**Comment by HamidHabib** [comment]
+1

**Comment by FlorianWerndl** [comment]
+1

**Comment by alexswiontek** [comment]
seems like a lot of the recent JetBrains updates have caused breaking changes on plugins and even basic functionality

**Comment by dorzki** [comment]
+1

**Comment by melbon** [comment]
+1

**Comment by roni-frantchi** [comment]
+1

**Comment by ChrisRM** [comment]
I'll see if I can sort this out now. Haven't had much time for this lately, I'm sorry.

**Comment by sweetcard** [comment]
+1

**Comment by niallobrien** [comment]
Really wish Jetbrains would stop breaking stuff. Downgrading Webstorm until resolved.

**Comment by ChrisRM** [comment]
I'm going to update the origin issue #205 with the progress. Closing this.

**Comment by ctongfei** [comment]
thanks!

**Comment by sweetcard** [comment]
Thank you very much.
