### ISSUE TITLE
Excluded Directories

### ISSUE THREAD

**Issue by niallobrien** [ChrisRM/material-theme-jetbrains#216]
Hi, using the default theme, the appearance of excluded directories seems a little too prominent - they stand out too much, almost like I've highlighted/marked them as directories of special importance. I'd much prefer for such directories to be subdued in their appearance.

![image](https://cloud.githubusercontent.com/assets/1525669/16770902/849e0782-4846-11e6-8b79-8c17276deb19.png)

Thoughs?

**Comment by niallobrien** [comment]
Apologies, I see that this is a duplication of https://github.com/ChrisRM/material-theme-jetbrains/issues/200

**Comment by Zarriff** [comment]
See my comment in #200. This is a setting in Appearance & Behavior > File Colors.

**Comment by niallobrien** [comment]
Thanks, closing.
