### ISSUE TITLE
Overriding global font loses its effect every time IDEA is restarted

### ISSUE THREAD

**Issue by ctongfei** [ChrisRM/material-theme-jetbrains#217]
Overridden global font: Fira Sans
Editor font: Fira Code

Every time IDEA is restarted, the global font is reverted to Lucida Sans on Mac OSX.

**Comment by rorschach** [comment]
same in linux(deepin)

**Comment by neg-serg** [comment]
The same problem. Also when you change _editor_ colorscheme font override work well.

**Comment by dougg0k** [comment]
Same issue. Ubuntu 16.04

**Comment by denofevil** [comment]
Duplicates #54
