### ISSUE TITLE
Not all icons are not loaded in "File structure" and "Search everywhere" popups

### ISSUE THREAD

**Issue by alexey-danilov** [ChrisRM/material-theme-jetbrains#222]
![screen shot 2016-07-15 at 4 17 41 am](https://cloud.githubusercontent.com/assets/4075759/16860723/38978580-4a43-11e6-8408-43b197bba6a1.png)
![screen shot 2016-07-15 at 4 09 41 am](https://cloud.githubusercontent.com/assets/4075759/16860722/38979412-4a43-11e6-9c20-b7130fc0b0a8.png)
![screen shot 2016-07-15 at 4 18 14 am](https://cloud.githubusercontent.com/assets/4075759/16860721/3895ff26-4a43-11e6-8462-27e1a5106d39.png)
![screen shot 2016-07-15 at 4 10 04 am](https://cloud.githubusercontent.com/assets/4075759/16860724/3899ddda-4a43-11e6-8d63-766eb1a754ce.png)

**Comment by alexey-danilov** [comment]
can anyone confirm if this is considered an issue and will be eventually fixed?

**Comment by fguimond** [comment]
I regularly use the structure tool and refer to these icons constantly to view . This is otherwise my favorite Intellij theme. Keep up the good work!

**Comment by SkyFather** [comment]
In file structure still the icon shows the java icon for example, I want the icon for the variable or function to show the actual property

**Comment by SalahAdDin** [comment]
@ChrisRM

**Comment by mallowigi** [comment]
should be fixed in the latest release
