### ISSUE TITLE
Material theme seems to half install?

### ISSUE THREAD

**Issue by CeramicTitan** [ChrisRM/material-theme-jetbrains#223]
![](http://puu.sh/q3gok/21eb2de694.png)
The workspace doesn't seem to be affected. When going into the settings it appears that that Material theme isn't even an option under the theme tab.

**Comment by przbadu** [comment]
exactly same issue here, I am using `webstrome 10.0`.

**Comment by 1Green** [comment]
Exact same issue with IntelliJ IDEA 2016.2 Build #IU-162.1121.32

**Comment by mjdetullio** [comment]
You have to go to Editor -> Colors & Fonts and change the scheme there as well.  I think you have to do this even when you switch from the default to Darcula, so I think this is fairly low priority.
