### ISSUE TITLE
groovy darker theme

### ISSUE THREAD

**Issue by vbasem** [ChrisRM/material-theme-jetbrains#227]
thanks for the great plugin, really love it.

Since I have some groovy code, the theme uses dark blue on dark background for many variable types and the result is unreadable (hardly visible blue parts in the screenshot):

![image](https://cloud.githubusercontent.com/assets/554690/17206082/595af2dc-54ae-11e6-8849-8fb8db157d02.png)

Would be great if we could support groovy as well (and gradle).

**Comment by northernwulf** [comment]
The same for some inherited values in groovy. 
![screenshot_1](https://cloud.githubusercontent.com/assets/6771075/23405168/12e80c34-fdca-11e6-8680-77f59c175ad7.png)

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.

**Comment by mallowigi** [comment]
Closing for lack of response. If needed please reopen.

**Comment by vbasem** [comment]
I apologize, it did indeed solve the issue. Thanks.
