### ISSUE TITLE
Debug console shows border on each line of output

### ISSUE THREAD

**Issue by FoxxMD** [ChrisRM/material-theme-jetbrains#228]
I can't find a place in Editor -> Colors & Fonts to fix this -- and I can't recall this border being there with the default theme. I am using Darker Theme. 

Any way I can remove the blue border around each line?

![screen shot 2016-08-02 at 9 21 44 am](https://cloud.githubusercontent.com/assets/4663766/17329953/dd4b25c0-5892-11e6-9307-9a578293972a.png)

**Comment by mallowigi** [comment]
Cant reproduce o_O
