### ISSUE TITLE
Git enabled files text colour no updated

### ISSUE THREAD

**Issue by JamesWhitfield** [ChrisRM/material-theme-jetbrains#234]
While using Git as the version control for a project, files that are registered with git use the default android studio colour scheme and as such are very difficult to read against the standard material design theme.  As shown below 'LoginTest.java' is a dark blue on a grey blue background and the commit message is black on the same background.

![image](https://cloud.githubusercontent.com/assets/12543552/17659165/b9c01148-62c8-11e6-82c0-1a4cbef7ce6e.png)

**Comment by mallowigi** [comment]
Android Studio are still left behind, sorry :/
