### ISSUE TITLE
How to change default font?

### ISSUE THREAD

**Issue by houzixiashanxiedaima** [ChrisRM/material-theme-jetbrains#235]
My OS is **`Windows 10`**,IDE version is **`Android Studio 2.1.3/2.1.2`**.I try to change the default font of the IDE,but when I restart IDE, it resets.

**Comment by SalahAdDin** [comment]
I think that it's [related](https://github.com/ChrisRM/material-theme-jetbrains/issues/230).

**Comment by houzixiashanxiedaima** [comment]
@SalahAdDin  YEAH，I asked in that issues,but no answer.

**Comment by denofevil** [comment]
Duplicates #54
