### ISSUE TITLE
Help attract JetBrains's attention to issues concerning line spacing and cursor size

### ISSUE THREAD

**Issue by roboslone** [ChrisRM/material-theme-jetbrains#236]
Material theme is awesome, but setting line spacing higher than 1.0 breaks cursor and text is alligned to bottom of the line, so it doesn't look as good as it could.

![Image](https://api.monosnap.com/rpc/file/download?id=ulPezgUEB2aS4KHSTafSLYz8cbXqM7)

Please help to attract JetBrains's attention to following issues by voting for them (one have to be logged in):
https://youtrack.jetbrains.com/issue/IDEA-149608
https://youtrack.jetbrains.com/issue/IDEA-98074

P.S. I'm not sure if it's the right place for that kind of request, but I can't think of any other. @ChrisRM , do you think you could add those links to README?

**Comment by SalahAdDin** [comment]
@ChrisRM Very bad issue!

**Comment by roboslone** [comment]
@SalahAdDin , would you care to elaborate on that?
