### ISSUE TITLE
PHPStorm 2016.2.1 Upgrade Icon Issue

### ISSUE THREAD

**Issue by drunkginger** [ChrisRM/material-theme-jetbrains#239]
Upgraded PHPStorm to 2016.2.1 and the icons in the Project Explorer defaulted back to the Darcula theme instead of the Material Theme UI icons.

**Comment by johnschmuff** [comment]
For me it is just the PHP files are no longer the Elephant icon. Non class PHP files are the base icon and the PHP files that are a class are a round icon with a large C in it.

**Comment by Bryant-Yang** [comment]
me too, I want my elephants :)

**Comment by lynkxyz** [comment]
Me too, plz fix it, i want my elephants

**Comment by landerss0n** [comment]
+1

**Comment by SpoonSimon** [comment]
+1

**Comment by wufantj** [comment]
+1

**Comment by sergejvoronov** [comment]
+1

**Comment by christianpohl** [comment]
+1

**Comment by mallowigi** [comment]
I have fixed it in my PR.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by welcoMattic** [comment]
+1

**Comment by fengcaiyiyi** [comment]
+10086
