### ISSUE TITLE
Overrides scheme after each restart

### ISSUE THREAD

**Issue by dvdpearson** [ChrisRM/material-theme-jetbrains#24]
Hey there,

When I change my selected scheme and I restart my PHPStorm, the default scheme is still the Material Theme scheme.

It'd nice to not override it since everyone would want to customize the scheme and create a new duplicated scheme.

Thanks.

**Comment by joecampo** [comment]
I think this is the same as #20

**Comment by ChrisRM** [comment]
Yep, working on it as we speak.

**Comment by dvdpearson** [comment]
Alright, I'm closing this one since it's a duplicate. Thanks!
