### ISSUE TITLE
I don't have icons in menu bar

### ISSUE THREAD

**Issue by syampolskiy** [ChrisRM/material-theme-jetbrains#241]
Why do I have old menu? http://prntscr.com/cblu5k
I want to see new menu with icons instead of text ;)
Webstorm 2016.2, Windows 8.1

**Comment by YozhEzhi** [comment]
Have you turned on toolbar?
`View` -> `Toolbar`.

**Comment by mornir** [comment]
I had the same issue. Thanks @YozhEzhi
