### ISSUE TITLE
Material UI not show in tools

### ISSUE THREAD

**Issue by Obka** [ChrisRM/material-theme-jetbrains#244]
Hello ,
After install Material theme i cant see any option in my Tools -> Material
please see the attachment .
Thank
![9-7-2016 3-33-35 am](https://cloud.githubusercontent.com/assets/13798815/18294069/e63da7cc-74ab-11e6-9df2-f6ae1b6d191c.png)

**Comment by mpixelz** [comment]
same issue here. any fix?
using the latest phpstorm
