### ISSUE TITLE
Bad visibility for context menu on Default Theme

### ISSUE THREAD

**Issue by alxdiardi** [ChrisRM/material-theme-jetbrains#247]
Hi. Context menu or menu bar have the same color like background and have no border, so their colors merge. Therefore it has a little inconvenience.
![attachment](https://cloud.githubusercontent.com/assets/22274427/18615406/3ab06dc4-7daf-11e6-897c-576963da631d.jpg)

**Comment by mallowigi** [comment]
I fixed it by setting `Separator.foreground=2E3C43` in default.properties. This adds a border with a lighter shade of Oceanic Blue

**Comment by oxysoft** [comment]
@mallowigi Could you tell me where to find this `default.properties`?

Thanks
