### ISSUE TITLE
Update to 0.2.1 cannot download (404)

### ISSUE THREAD

**Issue by markeijsermans** [ChrisRM/material-theme-jetbrains#251]
I'm unable to update the plugin within Intellij due to a 404 from jetbrains plugins site:
```
Plugin Material Theme UI was not installed: Cannot download "http://plugins.jetbrains.com/pluginManager/?action=download&id=com.chrisrm.idea.MaterialThemeUi&build=IC-162.2032.8&uuid=5da26476-4b5a-4df9-be4c-65ffe2a15f08": Connection failed with HTTP code 404
```

IntelliJ IDEA 2016.2.4
Build #IC-162.2032.8, built on September 9, 2016
JRE: 1.8.0_112-release-b343 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by park3** [comment]
Facing the same issue.

**Comment by jmesserli** [comment]
"http://plugins.jetbrains.com/pluginManager/?action=download&id=com.chrisrm.idea.MaterialThemeUi&build=IC-162.2032.8&uuid=5da26476-4b5a-4df9-be4c-65ffe2a15f08" redirects to "https://github.com/ChrisRM/material-theme-jetbrains/blob/master/Material%20Theme.zip?raw=true" which triggers the 404.

**Comment by hoangphucvu** [comment]
Same issue here how to fix it, I try to download and import zip file but not working

**Comment by jmesserli** [comment]
As a workaround: clone this repo, run `gradlew clean build` and manually install `build/distributions/Material Theme.zip`

**Comment by RomanAlaivi** [comment]
> As a workaround: clone this repo, run gradlew clean build and manually install build/distributions/Material Theme.zip

I'm new in intellij / Java. Could you help me maybe with how to do that? I'm not sure what gradlew clean build is or how to manually install it, but I did clone the repo. Thank you for any help!

**Comment by jmesserli** [comment]
@RomanAlaivi `gradlew clean build` will run the build script and generate the file you need to install the plugin for IntelliJ.

To install the plugin manually, open the IntelliJ settings (`CTRL + ALT + S`), navigate to `Plugins` and click on `Install plugin from disk...`. In the `Choose Plugin File` window that will open, navigate to `$clonedRepoDirectory/build/distributions/` and select `Material Theme.zip`. IntelliJ should prompt you to restart and after that, the plugin should be installed.

**Comment by herzog-sl** [comment]
Same issue here. Thanks for the workaround @jmesserli, but I don't have IntelliJ installed on my machine, just want to download and install the plugin from WebStorm.

**Comment by jmesserli** [comment]
@herzog-sl You should not need to have IntelliJ installed to build the plugin. Afaik the built `.zip` is the same for all JetBrains products.

**Comment by RomanAlaivi** [comment]
Thank you very much jmesserli. I've navigated into the directory but I can't see a build folder / distributions/ sub folder etc. What I see is [this](http://imgur.com/a/VDKu9).

**Comment by jmesserli** [comment]
@RomanAlaivi after you ran `gradlew clean build` with your terminal in the `material-theme-jetbrains` folder, you should be able to find `material-theme-jetbrains/build/distributions/`, where the zip should be located.

**Comment by RomanAlaivi** [comment]
Thanks, I think my issue is that I have no idea honestly how to run gradlew clean build. I just started a Java course, so it's all a little new to me;). I really appreciate you taking the time to offer your help though.

**Comment by jmesserli** [comment]
@RomanAlaivi no problem at all.

From your screenshot, I assume you are running Windows 10. 
What you have to do is open the `material-theme-jetbrains` folder in Windows Explorer. Then you'll `SHIFT + Right Click` an empty space in the folder and clich `Open terminal / command prompt here` (I don't know the exact name since my installation is german).
Once you have done that, a command prompt should open up where you can enter `gradlew.bat clean build` and then press enter.
This should start the build and after it finished, you should be able to find the built `Material Theme.zip` in the location I previously described.

Hope this helps.

**Comment by RomanAlaivi** [comment]
So it looks like it's not liking the gradlew command, as you can see [here](http://imgur.com/a/vYmmn). I'll see if I can get it working tomorrow morning, pretty late over here hah. Thank you very much again for helping me.

**Comment by jmesserli** [comment]
@RomanAlaivi that looks bad, good luck. If you need any help feel free to contact me at hi.github@peg.nu so we don't spam this issue.

**Comment by ChrisRM** [comment]
Fixing this asap

**Comment by ChrisRM** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/commit/eb0dc1897411b573ff2c69c79682c3f676bb51cd closes this one.

**Comment by kuige** [comment]
WebStorm 2019.1
Build #WS-191.6183.63, built on March 21, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/8212800/55713214-c27ef980-5a22-11e9-9fa3-a6bfe382ff72.png">
It happens again! 🙁

**Comment by vedantvohra1** [comment]
@kuige 

Opening the URL in a browser downloads the zip fine. I am having the same issue with the codealike plugin as well. It might be a JetBrains issue this time around. 

Meanwhile, the update can be installed manually from the zip file. Just copy paste the URL from the error prompt into a browser and it should start downloading immediately.

**Comment by mallowigi** [comment]
This is an old issue please refrain from hijacking it

**Comment by kuige** [comment]
I didn't do anything, and I tried again just now, and the plugin has successfully updated.
