### ISSUE TITLE
PHPStorm 16.3 EAP Stuck on Splash Screen

### ISSUE THREAD

**Issue by Mheetu** [ChrisRM/material-theme-jetbrains#253]
Just upgraded to PHPStorm 16.3 EAP and I can't get past the splash screen. I ended up having to backup and delete my `.PhpStorm2016.3` directory, launch PHPStorm, load settings from the backed up directory, and PHPStorm then throws an error (see below) and disables the plugin for me.

> Plugin 'com.chrisrm.idea.MaterialThemeUI' failed to initialize and will be disabled.  Please restart PhpStorm.
> 
> java.lang.AssertionError: Icon cannot be found in 'AllIcons.Windows.Maximize', aClass='class com.intellij.ide.ui.laf.darcula.DarculaLaf'
>     at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:71)
>     at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
>     at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:156)
>     at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:124)
>     at com.intellij.ide.ui.laf.darcula.DarculaLaf.parseValue(DarculaLaf.java:404)
>     at com.intellij.ide.ui.laf.darcula.DarculaLaf.loadDefaults(DarculaLaf.java:372)
>     at com.intellij.ide.ui.laf.darcula.DarculaLaf.initIdeaDefaults(DarculaLaf.java:276)
>     at com.intellij.ide.ui.laf.darcula.DarculaLaf.getDefaults(DarculaLaf.java:178)
>     at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
>     at com.chrisrm.idea.MTTheme.activate(MTTheme.java:52)
>     at com.chrisrm.idea.MTColorScheme.initComponent(MTColorScheme.java:10)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
>     at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:441)
>     at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
>     at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
>     at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
>     at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:448)
>     at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:400)
>     at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:386)
>     at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:74)
>     at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
>     at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
>     at java.awt.EventQueue.access$500(EventQueue.java:97)
>     at java.awt.EventQueue$3.run(EventQueue.java:709)
>     at java.awt.EventQueue$3.run(EventQueue.java:703)
>     at java.security.AccessController.doPrivileged(Native Method)
>     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
>     at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
>     at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
>     at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>     at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>     at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>     at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>     at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: java.lang.Throwable
>     ... 43 more

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/245
