### ISSUE TITLE
Color scheme not like sublime

### ISSUE THREAD

**Issue by abou7mied** [ChrisRM/material-theme-jetbrains#255]
This is a sample code using webStorm (I just changed whitespace color)
![image](https://cloud.githubusercontent.com/assets/3378281/19838296/b40b8186-9ed4-11e6-81f5-81db8930f009.png)

And this using sublime (I just installed the plugin from package control)
![image](https://cloud.githubusercontent.com/assets/3378281/19838307/f7779784-9ed4-11e6-9fe0-87fe4449ebb8.png)

I liked the sublime colors beacuse It visualize everything.
Is it something related to language definition or something similar?

**Comment by ShahidH** [comment]
Material Theme UI for Jetbrains still using outdated colors scheme.

References: 

https://github.com/ChrisRM/material-theme-jetbrains/issues/145
https://github.com/ChrisRM/material-theme-jetbrains/issues/199

**Comment by SalahAdDin** [comment]
@ChrisRM

**Comment by niamleeson** [comment]
The issue is with the IDE itself. Jetbrains IDE does not allow different colors for different keywords. Every keyword is grouped together.
