### ISSUE TITLE
Remote Host - excluded pathes not highlighted

### ISSUE THREAD

**Issue by ofca** [ChrisRM/material-theme-jetbrains#260]
My problem is related to "Remote Host" pane - before installing Material theme all not excluded pathes were highlighted to green and excluded were gray-ish. Now there's no highlighted entries at all, and to know which one directory/file is excluded I need to right click on it.

Just letting you know.

**Comment by mallowigi** [comment]
bump. how do you exclude paths in remote host?

**Comment by ofca** [comment]
Here is a screenshot. "node_modules" and "dist" directories are both "excluded" and should be somehow highlighted (marked) but their are not. To know which one is excluded you need to right click on them and look and the bottom of context menu if there is "exclude path" or "remove path from excluded" option.

![zrzut ekranu 2017-07-09 16 44 45](https://user-images.githubusercontent.com/679992/27994859-0f34a0d0-64c6-11e7-886e-997a3a22b36a.png)

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/27995062-bae26598-64d0-11e7-9127-26dc4a8cda37.png)

Welp, couldn't reproduce. This is what I get with the original Darcula theme (without the plugin). Again, no highlighted parts...

Maybe that's something they removed?

**Comment by ofca** [comment]
Ah, if so then sorry to trouble you. I know there were highlighted parts but maybe this was removed as you said.
