### ISSUE TITLE
WebStorm 2016.3 crashes when the theme is enabled

### ISSUE THREAD

**Issue by melbon** [ChrisRM/material-theme-jetbrains#263]
Hi, WebStorm 2016.3 crashes when the theme is enabled.
The only way to restart your IDE again is to disabled the plugin manually:

1. In ~\.WebStorm2016.3\config\disabled_plugins.txt file
2. Add com.chrisrm.idea.MaterialThemeUI 
3. Restart WebStorm

**Comment by mallowigi** [comment]
@ChrisRM now it's a good time to merge my PR

**Comment by JonathanYates** [comment]
Same issue here. Would be great if this could be fixed very soon.
