### ISSUE TITLE
In 2016.3 theme does not work

### ISSUE THREAD

**Issue by syampolskiy** [ChrisRM/material-theme-jetbrains#264]
Material Theme vanished from Plugins list and theme became default IntelliJ after upgrade Webstorm to 2016.3. What should I do to make theme work in Webstorm 2016.3?

**Comment by CaoLeilei** [comment]
我这边也遇到了同样的问题！

**Comment by 4n3ver** [comment]
Also, re-enabling the theme, would cause webstorm splash screen to load indefinitely

**Comment by mallowigi** [comment]
You can try to use my fork if you want to.

**Comment by wjvander** [comment]
I did what @mallowigi did in his PR, removed the icons and it works perfectly.

https://github.com/ChrisRM/material-theme-jetbrains/pull/259

**Comment by Izopi4a** [comment]
can you update it in the repository cuz it sais,  lkast updated 4 months ago, or its not up to you ?

**Comment by JonathanYates** [comment]
Same issue here. Would be great if this could be fixed very soon.

**Comment by sydor01** [comment]
Yeah, that would be awesome. I tried manually installing from the zip, but didn't work for me. Fortunately I still have 2016.2.4 and was able to back out to that version, but would rather keep up to date with 2016.3.

**Comment by dberthia** [comment]
Any ETA for when this fix will be deployed?
