### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by ChrisRM** [ChrisRM/material-theme-jetbrains#265]
Hi,

Would someone be interested in being a collaborator on this project? I really don't have time to fix issues and maintain the code base atm, but I will be later on. 

I don't want this project to stall, so if someone wants to help pushing the plugin forward I would really appreciate it. Let me know!

**Comment by denofevil** [comment]
@ChrisRM I can help with the maintenance for a while

**Comment by ChrisRM** [comment]
Fantastic, thanks @denofevil. Invite sent.

**Comment by skyrylyuk** [comment]
I can help with support Android Studio. I will be happy work on tasks relation with Android integration

**Comment by mallowigi** [comment]
I can also help
