### ISSUE TITLE
The theme is not supported in the latest updates

### ISSUE THREAD

**Issue by yabasha** [ChrisRM/material-theme-jetbrains#267]
Hi,

The theme was installed on Webstorm 2016.2.4 and it was working fine but with the latest updates it stopped working.

Regards,

**Comment by DualPixel** [comment]
I can confirm, upon installing the Theme the launcher instantly freezes up when it finishes loading the bar.

**Comment by JonathanYates** [comment]
Same issue here. Would be great if this could be fixed very soon.

**Comment by super-mario123** [comment]
The same issue in Android Studio 2.3Pre

**Comment by hielfx** [comment]
same in webstorm 2016.3

**Comment by yabasha** [comment]
I delete the plugin folder till it's fixed so I can use Webstorm 2016.3, I hope it will be fixed soon

**Comment by i-amin** [comment]
same issue here, splash screen freezes. i have webstorm 2016.3
