### ISSUE TITLE
VCS update icon and VCS commit changes icon are different

### ISSUE THREAD

**Issue by pakro** [ChrisRM/material-theme-jetbrains#268]
Don't know whether this is intentional but there is a difference in both icons.
It seems that the update is missing an icon since the commit has the "send letter" icon. Some other VCS related icons seems also to be affected.

**Comment by mallowigi** [comment]
Yep Jetbrains has changed the way they load icons. I've fixed it in my fork but the PR didn't get approved so...

**Comment by pakro** [comment]
Your PR is still open, I hope the maintainer will accept it. It seems that he is just currently inactive.

**Comment by gayanper** [comment]
Probably we could use your @mallowigi fork to install the plugin if this contains latest fixes until the maintainer accepts the pull.

**Comment by mallowigi** [comment]
If you can't wait, I have bundled my release at https://drive.google.com/open?id=0B_qRkKxpt9MTVG1DTmQ5UjU4TDg

Then in the Plugins window, select "Load plugin from disk" and select the zip file.
