### ISSUE TITLE
Update plugin at jetbrains repository

### ISSUE THREAD

**Issue by Komayo** [ChrisRM/material-theme-jetbrains#269]
Please update plugin at jetbrains repository.
With the last fix for the crash error of v.2016.3.
Thank you.

**Comment by yabasha** [comment]
review #267

**Comment by mallowigi** [comment]
If you can't wait, I have bundled my release at https://drive.google.com/open?id=0B_qRkKxpt9MTVG1DTmQ5UjU4TDg

Then in the Plugins window, select "Load plugin from disk" and select the zip file.
