### ISSUE TITLE
Change cursor color

### ISSUE THREAD

**Issue by DudeNamedBen** [ChrisRM/material-theme-jetbrains#27]
I love how this theme looks but I find the huge yellow cursor to be very distracting.
The cursor is like double the height of my code.
Is there an easy way to change size and maybe the color of the cursor?

**Comment by ChrisRM** [comment]
The caret size is set according to the Line Height you are using. You can easily customize the color by going to `Preferences` -> `Editor` -> `Colors & Fonts` -> `General`. Now, hit the "Save as..." button to create a copy of the theme. Now you can change the `Caret` color.

**Comment by DudeNamedBen** [comment]
Works perfectly. Thank you very much.
