### ISSUE TITLE
Webstorm 2016.3 stuck on startup after installation of  material theme

### ISSUE THREAD

**Issue by karlpatrickespiritu** [ChrisRM/material-theme-jetbrains#270]
I'm using Windows 10.

**Comment by rephchunhoong** [comment]
Hi @karlpatrickespiritu, please refer to https://github.com/ChrisRM/material-theme-jetbrains/issues/263 to get your webstorm started first, while waiting a pull request that fixes this issue.

**Comment by karlpatrickespiritu** [comment]
thanks @rephchunhoong. hope the the pull request will be merged soon. i love this theme! <3

**Comment by karlpatrickespiritu** [comment]
#263
