### ISSUE TITLE
Does the project have any pulse?

### ISSUE THREAD

**Issue by vbasem** [ChrisRM/material-theme-jetbrains#271]
A little worried about the pulse of the project. Perhaps we can assign more people with review/merge authority?

Would be a shame if it stopped here! Specially since it was submitted to jetbrains plugin rep.

**Comment by ChrisRM** [comment]
I have been really busy at work the latest months, so I haven't had time to do much here. I'm still pretty busy, but I will make more room for this project now that it has so many users. The issues are stacking up, but by glancing at it, there are a lot of duplicates and lots of minor issues. I'll give it some love the coming weeks.

**Comment by mallowigi** [comment]
If you can't wait, download the plugin at https://drive.google.com/open?id=0B_qRkKxpt9MTVG1DTmQ5UjU4TDg

Then in the Plugins window, select "Load plugin from disk" and select the zip file.

**Comment by ChrisRM** [comment]
I'm testing your pull request right now, @mallowigi. If all goes well, I'll merge it and update the plugin.

**Comment by vbasem** [comment]
Glad to hear there is still life in this project. Save us from bleeding our eyes out with the default look and feel in Intellij!
