### ISSUE TITLE
Method icons are not working for Java

### ISSUE THREAD

**Issue by gayanper** [ChrisRM/material-theme-jetbrains#272]
The method icons are not loaded when displaying methods in outline popup.
![image](https://cloud.githubusercontent.com/assets/7471994/20488202/2a3422f6-b02c-11e6-92fb-01871d20ac05.png)

**Comment by ChrisRM** [comment]
Woops, wrong button. You are correct, there are some issues with `com.intellij.psi.PsiClass`. I'm looking into it.

**Comment by gayanper** [comment]
Its seems removing the iconProvider in plugin.xml solves the problem.
``` diff
 <extensions defaultExtensionNs="com.intellij">
        <editorTabColorProvider implementation="com.chrisrm.idea.MTEditorTabColor"/>
--     <iconProvider implementation="com.chrisrm.idea.icons.MTFileIconProvider"/>
        <bundledColorScheme path="/colors/Material Theme - Lighter"/>
```
And i couldn't find the iconProvider in list of extension definition either at InteliJ SDK.

**Comment by gayanper** [comment]
Probably those changes will not be compatible with older Idea versions which i didn't check

**Comment by mallowigi** [comment]
No way this would remove all icon replacements whatsoever.

**Comment by mallowigi** [comment]
I thought this would prevent the icons to stop working but it looks like it's working. How is that possible?

**Comment by gayanper** [comment]
I guess i was only focusing java since im running the community version. My bad then i know why my PR got rejected. But i guess better to find a solution which ia based on intelij openapi extension points if possible to avoid more bugs like this in future.

**Comment by ChrisRM** [comment]
Can you try to pull the repo, build the plugin and see if the java icons work properly now, @gayanper?

**Comment by gayanper** [comment]
@ChrisRM Its still the same and now the java class icon is wrong as well which was fixed by #266.

**Comment by benj56** [comment]
Any update? Makes it impossible to see the visiblity of methods in the structure screen. I rely on it and will likely need to disable the theme until this is resolved. 

The right icons seem to be visisble for a second by the way, but then all of them change to the broken one.

Thanks!

**Comment by mjdetullio** [comment]
@gayanper Thanks for the hint on the `iconProvider` extension being the problem

**Comment by StefanSchrass** [comment]
I still see this on: 
IntelliJ IDEA 2017.1
Build #IU-171.3780.107, built on March 22, 2017

**Comment by denofevil** [comment]
@StefanSchrass updated plugin has not been published yet
