### ISSUE TITLE
Breadcrumbs colours are too dark after after 2016 upgrade

### ISSUE THREAD

**Issue by dabolichin** [ChrisRM/material-theme-jetbrains#275]
After upgrading to 2016.3 breadcrumbs colours of the editor are darker than before and it is hard to distinguish what is there.

**Comment by yangyang0507** [comment]
This is my config:
<img width="964" alt="qq20161130-1 2x" src="https://cloud.githubusercontent.com/assets/5666807/20738731/2fb4510e-b6f0-11e6-990f-2505f3c9882d.png">
<img width="972" alt="qq20161130-0 2x" src="https://cloud.githubusercontent.com/assets/5666807/20738733/2fc23dd2-b6f0-11e6-855a-9ab848c7b22d.png">
Current Default Hovered is same config

The result is:
<img width="236" alt="qq20161130-3 2x" src="https://cloud.githubusercontent.com/assets/5666807/20738729/2fad00c0-b6f0-11e6-8f48-eba181ed5d44.png">
<img width="241" alt="qq20161130-2 2x" src="https://cloud.githubusercontent.com/assets/5666807/20738730/2faf0f78-b6f0-11e6-8a22-6a9edfea4d98.png">

**Comment by nek4life** [comment]
Hmmm HTML breadcrumbs seem crazy bright and stick out like a sore thumb. Are they separate from this?

**Comment by mallowigi** [comment]
should be fixed in last release
