### ISSUE TITLE
Not compatibile with PHPStorm 2016.3.1

### ISSUE THREAD

**Issue by ajaxovic** [ChrisRM/material-theme-jetbrains#278]
After installation PHPStorm 2016.3.1 and importing settings, system said, that this plugin is not compatible and disable it. Re-enabling theme and restarting ide ends with infinite splash screen.

**Comment by omriLugasi** [comment]
also with WebStorm +1 please fix it i like this thame

**Comment by ThomasDK81** [comment]
I removed it and reinstalled it, that did the trick.

**Comment by guicara** [comment]
As Thomas said, I confirm that reinstalling the plugin did the trick. Thanks ;)
