### ISSUE TITLE
Dart icons

### ISSUE THREAD

**Issue by franklinyu** [ChrisRM/material-theme-jetbrains#282]
It would be great to have [Dart](https://www.dartlang.org/) icons in WebStorm (which is supported in default theme). Or I may just submit a pull request like 9a26d94c2101d60f36f60f4feaea3480772c0c88? They released [their icon](https://github.com/dart-lang/logos/blob/master/logos_and_wordmarks/dart-logo.png) in CC BY 3.0; does it work with this project?

![dart-logo](https://raw.githubusercontent.com/dart-lang/logos/master/logos_and_wordmarks/dart-logo.png)

**Comment by mallowigi** [comment]
I've made a fork of the project called... "Material Theme UI Fork" in the plugins section. Try to install it after disabling this one, until the maintainer comes back.

**Comment by franklinyu** [comment]
Fixed by #296.
