### ISSUE TITLE
Reached line color by a stepping Debug

### ISSUE THREAD

**Issue by fayway** [ChrisRM/material-theme-jetbrains#284]
During a Step-by-Step debugging, it's not easy to distinguish between a line with a breakpoint (line number 55 in the attached screenshot) and the reached line by the stepping (line number 56)

Is it possible to use a blue-ish background (eg: 4B6EAF) with a whiter font color as in the bottom part of the screenshot?

![debug_line_color](https://cloud.githubusercontent.com/assets/1507839/21457262/3abbf9f8-c92e-11e6-9efe-a3a741bcebaf.PNG)

**Comment by jchlu** [comment]
You can set whatever colours you wish for the breakpoint line:
![Properties Screengrab](http://d.jch.lu/ZWks/2UFZ05zD+)

**Comment by fayway** [comment]
Perfect, thanks a lot

**Comment by dylan-chong** [comment]
Why was this closed? Surely the default colour should not be one that everyone has to change.
