### ISSUE TITLE
Parameter hints not correctly colored in Darker

### ISSUE THREAD

**Issue by serebit** [ChrisRM/material-theme-jetbrains#286]
![Screenshot.](https://cloud.githubusercontent.com/assets/12981608/21486919/7ce8cc66-cb8b-11e6-871e-44d12aa9d8e3.png)

**Comment by ShahidH** [comment]
Temporary fix:

1. Settings
2. Editor > Colors & Fonts > Language Defaults
3. Inline parameter hint style.
4. Change background to: 263238

![phpstorm](https://cloud.githubusercontent.com/assets/784974/24577899/a1d45b60-16ce-11e7-92da-2cd72710c52d.png)

**Comment by iamjaredwalters** [comment]
@ShahidH Thanks for the workaround 👍

**Comment by mallowigi** [comment]
should be better in the latest release
