### ISSUE TITLE
Dark themes should have parent_scheme set to Darcula not Default

### ISSUE THREAD

**Issue by vsch** [ChrisRM/material-theme-jetbrains#289]
This causes all custom elements for which the scheme does not provide a color to be taken from a light scheme instead of dark scheme.

[IDEA-153539: Supplied Dark Themes define parent_scheme as 'Default' instead of 'Darcula'](https://youtrack.jetbrains.com/issue/IDEA-153539)

**Comment by cemerick** [comment]
Just to expand on my +1: without this change, the VCS annotations gutter sidebar, code regions in e.g. markdown files, and other miscellaneous areas are not rendered pleasantly in the default material theme (very light backgrounds, with very similarly light font colors, quite hard to read).

_With_ this change, these areas are all pleasantly congruent with the rest of the (otherwise excellent) dark theme.

**Comment by cemerick** [comment]
For other that want to try: I changed this (first) line in my material `Default.icls` file:

```xml
<scheme name="_@user_Material Theme - Default" version="142" parent_scheme="Default">
```

to

```xml
<scheme name="_@user_Material Theme - Default" version="142" parent_scheme="Darcula">
```

Before/after:

![capture2](https://cloud.githubusercontent.com/assets/47489/21794011/6ffbdaea-d6c4-11e6-98c0-57ee56980d66.PNG)
![capture](https://cloud.githubusercontent.com/assets/47489/21794010/6ffb0476-d6c4-11e6-9b4c-7509240d5dda.PNG)

**Comment by mallowigi** [comment]
👍

**Comment by Soldalma** [comment]
Hello Chas,

I have my own theme stored in
C:\Users\Soldalma\.PyCharmCE2016.3\config\colors, and I have been using it
for the editor. The main change is that I like a completely black
background. At the age of 63 I need a lot of contrast to see my code. I
would like to apply that theme to the remainder of PyCharm, not only the
editor. Is that possible?

Thanks for any suggestions.

FS

**Comment by cemerick** [comment]
@Soldalma Sorry, I'm just a user, and of IntelliJ for that matter, so I don't have any concrete suggestions there. The best I can offer is, if you really do want a high-contrast display, then your operating system probably offers an option to provide this on a system-wise basis.

**Comment by mallowigi** [comment]
I've made a fork of the project called... "Material Theme UI Fork" in the plugins section. Try to install it after disabling this one, until the maintainer comes back.

**Comment by ChrisRM** [comment]
Fixed in https://github.com/ChrisRM/material-theme-jetbrains/commit/780fce565ca22c68279049e8bc89862cb217a920. Nice work @mallowigi
