### ISSUE TITLE
Windows UI font size issue

### ISSUE THREAD

**Issue by pavinthan** [ChrisRM/material-theme-jetbrains#290]
I've updated PhpStrome Appearance and behavior > Appearance UI default font size to 13, but after restart me PhpStrome it's will be override by default
...

Operating system and version:
Windows 10
PhpStrome, WebStrome ...:
v2016.3
Material Theme release:
v0.2.2

**Comment by whynot123** [comment]
same issue here on clion 2016.3 with 0.2.2
when Override Default Fonts is set to custom font in Appearance panel, doesn't remember changes after restart

**Comment by pavinthan** [comment]
Thanks 👍

**Comment by johny-bravo** [comment]
@pavinthan this project seems to be no longer mantained, i suggest you use https://github.com/mallowigi/material-theme-jetbrains instead

**Comment by denofevil** [comment]
Duplicates #54
