### ISSUE TITLE
How do I install the Material theme in PyCharm

### ISSUE THREAD

**Issue by Soldalma** [ChrisRM/material-theme-jetbrains#291]
I downloaded Material_Theme.zip but I do not know how do I install it in PyCharm. Somehow I could not find instructions in GitHub. 

Also, can one modify a theme? I have my own editor theme that works well for me and I would like to use it in the PyCharm UI as well, but again I could not find a way to do it. The PyCharm menu only shows Darcula, IntelliJ and Windows.

I am using Community Edition 3.6.

**Comment by mallowigi** [comment]
There is an option "Install plugin from disk" in the Plugins section in the settings. 

As for the theme, it is under the "Color Scheme" section.

**Comment by Soldalma** [comment]
Elior,

many thanks for your suggestions. I was able to install the plugin, and
PyCharm restarted with the Material Theme. Later I changed back to another
theme and could not go back to the Material Theme as it did not appear
under Settings/Appearance and Behavior/Appearance Theme. The Theme dropdown
menu displayed the same themes as before.

I looked in several places for the "Color Scheme" section but could not
find it.

Thanks again.

Best regards,

FS

**Comment by mallowigi** [comment]
Yes, this is because the Material Theme is based on the Darcula theme by overriding most of its settings. Unfortunately switching back to Darcula reloads the original Darcula theme.

You need to select the Material Theme again using the icon on the toolbar or inside the Tools menu > Material Theme

**Comment by Soldalma** [comment]
Ok, I actually reinstalled it. Is there a way to change the colors? My eyes
are not very good and I need a blacker background. You mentioned a "Color
Scheme" section but I cannot find it.

Cheers,

FS

**Comment by mallowigi** [comment]
Settings > Editor > Colors and Fonts. You can click on "Save as" next to the Scheme, so you can edit the colors at your leisure.

**Comment by Soldalma** [comment]
Thanks. I am familiar with that menu and I have created my own theme for
the editor. However, the changes only apply to the editor and I would like
to have the changes applied to the application itself.

There is another menu at Settings/Appearance and Behavior/Appearance that
lets one change the application theme. However, it contains only three
items: Darcula, IntelliJ, and Windows. I would like to either modify these
themes or to be able to add my own theme that I used for the editor to that
list. Is that possible?

Thanks again for your help.

FS

**Comment by mfcecilia** [comment]
When I download the Material Theme, it is in a .zip file. 
I unpack the .zip file and there are 3 .jar files.
When I go into Pycharm and go to File>Import Settings>
one by one, I try each of the .jar files that were unpacked.
None of them work.
I get an error that says, "Invalid File"
"The file contains no settings to import. Make sure you have generated the file using 'File|Export Settings' feature."

**Comment by mallowigi** [comment]
You need to select the zip file itself

--
Elior

**Comment by mfcecilia** [comment]
I downloaded the .zip file, this time, without unpacking it.
I opened Pycharm and went to File>Import Settings>
I selected the .zip file and I got the same exact error:
"Invalid File
The file contains no settings to import. Make sure you have generated the file using 'File|Export Settings' feature."

**Comment by mallowigi** [comment]
Not import settings, but Settings > plugins > install plugin from disk

**Comment by mfcecilia** [comment]
Thanks for your help! It's working :)

**Comment by Momshad-Dinury** [comment]
mallowigi thanks

**Comment by jturi** [comment]
For easy install go to:

` Settings > Plugins > Browse repositories` 

then Search for `"theme"`

You will see Material Theme, Rainglow, Afterglow Theme etc.

Install it with one click and restart PyCharm.

**Comment by f1andre** [comment]
That works!

**Comment by SkylerLS** [comment]
Just for what it's worth. I use PHPStorm and PyCharm sometimes and Material has been just fine for PHPStorm but when opening PyCharm the UI was using the default one. 
I had to uninstall the theme entirely then reinstall it. Now it's working just fine.
Maybe this will help someone who sees this.

**Comment by forYueji** [comment]
@mallowigi    my attempt android studio 3.1.2 version install Material Theme hint Plugin Material Theme UI is incompatible with this installation .
about this problem  How Solve  Thank you

**Comment by mallowigi** [comment]
try to download the latest release

**Comment by mallowigi** [comment]
Look at the versions numbers in the plugin page, you'll see their compatibility with the different versions of the IDE. To see what version of the IDE you have, you can find it in the About window. 

As for the 2017.3 edition, I think the last compatible version is 1.6.1 if I'm not wrong.

**Comment by CptJason** [comment]
<img width="1009" alt="pycharm theme" src="https://user-images.githubusercontent.com/397285/47627922-cce0c180-db6d-11e8-9f31-7bacb513ca59.png">

**Comment by CptJason** [comment]
<img width="1014" alt="pycharm plugin" src="https://user-images.githubusercontent.com/397285/47627979-1fba7900-db6e-11e8-82ba-23a21318fb15.png">

**Comment by MitaiGit** [comment]
![Снимок экрана от 2019-04-17 10-52-47](https://user-images.githubusercontent.com/32243762/56264275-63df0d00-60ff-11e9-97ec-e7684bb6a018.png)
![Снимок экрана от 2019-04-17 10-53-53](https://user-images.githubusercontent.com/32243762/56264279-66d9fd80-60ff-11e9-86be-412bcd7f56cb.png)
?

**Comment by Kein** [comment]
> There is an option "Install plugin from disk" in the Plugins section in the settings.
> 
> As for the theme, it is under the "Color Scheme" section.

It tells a lot about IDE when you have to find this functionality on some random GH issue.
