### ISSUE TITLE
.c, .cpp, .h, .py, .pdf, .psd icons not showing or incorrect

### ISSUE THREAD

**Issue by johny-bravo** [ChrisRM/material-theme-jetbrains#292]
having this issue on win7 in Clion 2016.3 
with both 0.2.2 from jetbrains repo
and 0.2.3 from https://github.com/mallowigi/material-theme-jetbrains/commit/9cf39e7de0e899a2466b3b10b07f1abca8eeec69
psd icon seems to use `image.png` instead of `psd.png`
![image](https://cloud.githubusercontent.com/assets/11711568/21920892/17fcc2d8-d975-11e6-8356-d3e376e137b2.png)
python icon seems to work in tabs but not in source tree
![image](https://cloud.githubusercontent.com/assets/11711568/21921250/c820bc4e-d977-11e6-915f-e9c0f4e34027.png)

**Comment by mallowigi** [comment]
C files seem to work correctly in my build. As for the PSD, it might come from the inclusion in the "Images" category.  I'll release the fix in a future build, for now there is not enough changes for me to do so.

**Comment by mallowigi** [comment]
I've made a fork of the project called... "Material Theme UI Fork" in the plugins section. Try to install it after disabling this one, until the maintainer comes back.

**Comment by johny-bravo** [comment]
@mallowigi thanks, that's great! i ll check it out

**Comment by ChrisRM** [comment]
@mallowigi If you'd like, I can add you as a contributor to this repo, so you can push to it directly? I don't have enough time these days to maintain it, so any help would be great.

**Comment by mallowigi** [comment]
Well that would be best indeed.

**Comment by johny-bravo** [comment]
regards the bug, i tested this in clean VM with clean install of CLion 2016.3.2
some icons still don't work
![image](https://cloud.githubusercontent.com/assets/11711568/22186814/0e8ea334-e10d-11e6-90c6-b3fba7b8e036.png)
**.pdf .h .py**

**Comment by mallowigi** [comment]
Ok I'm trying in CLion. Why are the files in gray though?

**Comment by johny-bravo** [comment]
@mallowigi they are greyed out when aren't declared in `CMakeLists.txt`
were you able to reproduce?

**Comment by mallowigi** [comment]
Yeah and I found the fix. It could even fix issues related to the Java files and stuff.

**Comment by johny-bravo** [comment]
@mallowigi 
check out the up-to-date icons in `svg` here: https://github.com/jesseweed/seti-ui/tree/master/icons
some of them also seem updated vs used currently in jetbrains theme, ie `cpp` icon is no longer thin and is more consistent with `c` icon. 
color seems fine to me
![image](https://cloud.githubusercontent.com/assets/11711568/22211231/7a70d186-e19d-11e6-84b4-d7bc98d221d6.png)

**Comment by ChrisRM** [comment]
We should be using the icons found here: https://github.com/equinusocio/material-theme/tree/develop/icons

Keep in mind, this is the Material Theme, not Seti 👍  If you'd like to create a Seti-version, feel free to fork and adjust :-)
