### ISSUE TITLE
Bug? Menus with no borders and no dividers is very confusing.

### ISSUE THREAD

**Issue by martinaguilar** [ChrisRM/material-theme-jetbrains#293]
Background menus and window tools like project have the same color. Neither of both are clear and very confusing some times.

![capture1](https://cloud.githubusercontent.com/assets/377835/21993891/da6f0f46-dbfb-11e6-9d4d-48ea541b211f.png)

**Comment by martinaguilar** [comment]
while in darcula (default dark theme) is a little bit more clear while using borders and dividers.

![capture3](https://cloud.githubusercontent.com/assets/377835/21997766/c1ae201e-dc0f-11e6-81da-f8a92a3a066c.png)

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/247

BTW, I've made a fork with the project with some issues fixed. Try to find Material UI Fork in the plugins list.

**Comment by martinaguilar** [comment]
Mallowigi... this is Excelent!!!!!!! Just what I was looking for.
Thanks a Lot!

**Comment by denofevil** [comment]
Duplicates #247
