### ISSUE TITLE
Syntax for SCSS-files in PHPStorm is not as expected

### ISSUE THREAD

**Issue by Blueblau** [ChrisRM/material-theme-jetbrains#295]
The syntax highlighting for SCSS-files are not as expected, in PHPStorm for Windows.

I've tried to reinstall the plugin, but doesn't seem to help.

![image](https://cloud.githubusercontent.com/assets/1536598/22061534/9c8dc390-dd75-11e6-8c2c-0ffdee9fc94f.png)

**Comment by mallowigi** [comment]
I don't see what's the problem here.

**Comment by Blueblau** [comment]
Sorry for super late response. Didn't see your reply until now. 

The problem is that there are only two colors, setting one color to the key and one to the value. If you apply the default theme, you can see a colors for strings, numbers, variables, nodes and other selectors — not only two.

**Default theme**
![skaermbillede 2017-09-22 kl 11 36 10](https://user-images.githubusercontent.com/1536598/30738585-e1a81322-9f8a-11e7-93c1-1d754a32a556.png)

**Material theme**
![skaermbillede 2017-09-22 kl 11 36 35](https://user-images.githubusercontent.com/1536598/30738587-e5fcb66c-9f8a-11e7-8f62-fbedf19f498c.png)

**Comment by r3b311i0n** [comment]
For reference, this is how it looks like in Material Theme from **Sublime Text 3**

![scss-material](https://user-images.githubusercontent.com/10097295/30754056-e1850cc0-9fde-11e7-8648-bf7f6ceb083f.png)

**Comment by mallowigi** [comment]
<img width="1440" alt="screen shot 2017-09-22 at 22 12 04" src="https://user-images.githubusercontent.com/5015756/30760514-2399482a-9fe3-11e7-9f19-6029dde0f077.png">

**Comment by mallowigi** [comment]
don't see any problem here. You probably have an older version of the plugin.

You're on 2016.X right ?

**Comment by kluplau** [comment]
I installed it again today, as I got a brand new Macbook. Installed latest PHP Storm and installed Material Theme... So I think I was running latest... my co-worker had the same issue, on an older installation.

**Comment by mallowigi** [comment]
What is the version of the plugin? IDE? Make sure you have the bundled color schemes and not edited.

**Comment by r3b311i0n** [comment]
I think colour scheme settings are not cleared even if you uninstall and install the plugin, but I think restore defaults on colour scheme should bring you back to default settings.

![settings-idea](https://user-images.githubusercontent.com/10097295/30765082-5471eb3c-a00b-11e7-9183-8d4343503a76.png)

**Comment by mallowigi** [comment]
If the color scheme is blue means that you have edited it, and therefore do not get updates. You need to restore defaults to get them.

And yes, only bundled color schemes are uninstalled, if you edited them they will stay even if the plugin is uninstalled

**Comment by kluplau** [comment]
Will try that when I get back to the office Monday. Can't see how that can be the case tho, as this happened on a clean install of a Mac. PHP Storm and Material Theme was literally the first two things I installed.

**Comment by mallowigi** [comment]
well you saw in my screenshot that I'm not lying...

**Comment by kluplau** [comment]
Well, neither am I... 😄
