### ISSUE TITLE
Colours unreadable for Elixir

### ISSUE THREAD

**Issue by dylan-chong** [ChrisRM/material-theme-jetbrains#298]
<img width="1202" alt="screen shot 2017-01-21 at 7 42 05 pm" src="https://cloud.githubusercontent.com/assets/17482349/22172652/fd44f9a8-e011-11e6-82be-7a728926551c.png">

**Comment by mallowigi** [comment]
Elixir is not a bundled plugin, so of course it's not currently supported within the theme. However there are simple actions to make it work:

Go to Settings > Editor > Colors and Fonts > Elixir

Then for each property look on the right for a checkbox "Use inherited attributes of ..." and check it. It should pick the default colors. Some could not be picked though, it highly depends on the plugin. But you can change it to your will.

**Comment by dylan-chong** [comment]
Thanks, this solves the problem

**Comment by conradwt** [comment]
Thanks, this also solved my issue.  Is it possible that this could be made the default for the Elixir language?
