### ISSUE TITLE
Add more color to JS?

### ISSUE THREAD

**Issue by kirillrocks** [ChrisRM/material-theme-jetbrains#299]
BTW theme looks very good.

The only thing is that is too little color in JS. variables, object, function - all in the same blueish color.

**Comment by sajidali** [comment]
Please consider this.

**Comment by RDeluxe** [comment]
I agree, not enough contrasts and lack of lisibility in JS.

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.
