### ISSUE TITLE
[Error][Plugin] MTIconReplacer failed to initialize and will be disabled

### ISSUE THREAD

**Issue by voydz** [ChrisRM/material-theme-jetbrains#3]
I am encountering an error while enabling the material plugin in phpStorm 9.0.2 (PS-141.2462). (using the preinstalled Yosemite Java JRE 1.7.0_71-b14 x86-64). 

Here again the trace from phpStorm:
![Stacktrace](https://cloud.githubusercontent.com/assets/373533/10156863/6459899a-6685-11e5-8e7f-08d85b4af18e.png)

**This is a reference to the post https://github.com/ChrisRM/material-theme-jetbrains/issues/1#issuecomment-143606374 in issue #1 .**

**Comment by ChrisRM** [comment]
Tbh, I've only testet this on JRE 1.8.0.*. 

[PhpStorm 9 with JDK 1.8](http://download.jetbrains.com/webide/PhpStorm-9.0.2-custom-jdk-bundled.dmg)
> This alternative PhpStorm 9 distribution bundles JDK 1.8 customized by the JetBrains team for better performance. Please note this non-default option may contain some issues.

**Comment by voydz** [comment]
Thanks, I will used the bundled version in that case, but just to let you know. :)

**Comment by ChrisRM** [comment]
Yeah, I'll do more testing on different versions later :-)
