### ISSUE TITLE
Some yaml files use the extension yml

### ISSUE THREAD

**Issue by joshmiller83** [ChrisRM/material-theme-jetbrains#303]
Example:

![image](https://cloud.githubusercontent.com/assets/1440242/22830243/c4e8eaa8-ef73-11e6-85a5-e78fca7e9f44.png)

I'd like the icon to work with yml. I'll create a PR as soon as I can figure out where that would be.

Josh

**Comment by mallowigi** [comment]
All files starting with .git have the git icon

**Comment by denofevil** [comment]
Fixed via #297
