### ISSUE TITLE
Missing smarty icon

### ISSUE THREAD

**Issue by adaliszk** [ChrisRM/material-theme-jetbrains#304]
Hello, my problem is simple and easy to fix: The smarty .tpl filetype is getting a HTML5 icon instead of a nice smparty lamp.

If I adding them to the resources it will be replace the current icon?

**Comment by mallowigi** [comment]
Hum, I've added the Joomla icon for this because I thought they were related. Was I wrong?

**Comment by adaliszk** [comment]
Smarty is different than Joomla, I dont know that they are using it or not though, but dont use a joomla Icon for a tpl file.

**Comment by mallowigi** [comment]
Ok, do you have an icon for this? I would need two versions: one 16x16 and 32x32. Thanks!

**Comment by adaliszk** [comment]
it should be in src/main/resources/icons/fileTypes ?
If yes I just drop there a tpl.png and tpl@2x.png for you and create a pull request from it 😉
If not then where should I add it ?

**Comment by mallowigi** [comment]
Yep exactly

--
Elior

**Comment by mallowigi** [comment]
Actually rather rename it to smarty.png
