### ISSUE TITLE
Why is there a forked version in the IDEA plugins repository, what's the diff, and what repo/branch is that built from?

### ISSUE THREAD

**Issue by chris-johnson-tl** [ChrisRM/material-theme-jetbrains#307]
It links back to the same repo here, but the changelog doesn't match, so I'm assuming the code doesn't either.

**Comment by mallowigi** [comment]
This is a fork I've made to make changes because the dev owner is not working on the plugin. It fixes some of the recent issues and also contains features that I want to add myself.

**Comment by chris-johnson-tl** [comment]
Ok, thanks for the clarification.
