### ISSUE TITLE
Error when starting WebStorm 2017.1

### ISSUE THREAD

**Issue by mrenty** [ChrisRM/material-theme-jetbrains#315]
After updating to WebStorm 2017.1 (WS-171.3780.79) I got this error `com.intellij.ui.tabs.impl.DefaultEditorTabsPainter: method <init>()V not found`.

**Comment by vadim-kovalenko** [comment]
Same problema

**Comment by jbouhier** [comment]
Duplicate of https://github.com/ChrisRM/material-theme-jetbrains/issues/310

**Comment by denofevil** [comment]
@jbouhier thank you, closing this on in favour of #310
