### ISSUE TITLE
Parameter Name Hints (new PhpStorm feature) | Gray font with a gray background.  Hard to read.

### ISSUE THREAD

**Issue by mhosks** [ChrisRM/material-theme-jetbrains#321]
![image](https://cloud.githubusercontent.com/assets/12366078/24329677/8133a782-11c2-11e7-9b39-1f581019ada1.png)

**Comment by ruchern** [comment]
You can turn this off by hovering your mouse over the grey area for the option.

**Comment by denofevil** [comment]
Duplicates #286
