### ISSUE TITLE
Option to disable theme

### ISSUE THREAD

**Issue by ciscorucinski** [ChrisRM/material-theme-jetbrains#322]
Currently, there is an option to switch between 3 different themes. It would be nice to add an additional action to disable the theme completely.

Right now, in order to disable the theme, we have to uninstall the theme and then reinstall it to reenable it. 

A simple toggle mechanism would be beneficial.

**Comment by mallowigi** [comment]
I've implemented a "Remove Theme" that reinstalls Darcula colors, but it doesn't disable all other features such as the new buttons, tabs or the icons.

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.

**Comment by ciscorucinski** [comment]
It's fixed
