### ISSUE TITLE
[Darker variation] Selected text blends with background

### ISSUE THREAD

**Issue by ArtemGordinsky** [ChrisRM/material-theme-jetbrains#323]
Since updating all of my editors (PhpStorm, WebStrom, DataGrip) to version `2017`, I have an issue with selected text being unreadable in the search fields: both in-page search and "Find in Path", but not "Search everywhere". Is there an option I could tweak or a way I could fix this?
Example:
<img width="186" alt="screen shot 2017-04-06 at 09 44 11" src="https://cloud.githubusercontent.com/assets/1506254/24743209/b778f0c4-1aad-11e7-928f-16fde3ae392c.png">

**Comment by Arxi** [comment]
@ArtemGordinsky could you please tell me how you solved this? I'm facing the same problem. Thanks!

**Comment by ArtemGordinsky** [comment]
@Arxi I didn't, I think it just got better after one of the updates. Selected text is still hard to read but it's not as bad...
I guess you could try choosing a different sub-themes and accent colors to see if it improves the situation.
