### ISSUE TITLE
can not find Material Theme option in Tools

### ISSUE THREAD

**Issue by bergPro** [ChrisRM/material-theme-jetbrains#327]
i want to switch the IDE theme , but i can not find Material Theme option in Tools

**Comment by thanos-irodotou** [comment]
You mean switch to a different material theme? 
If so you should have a new dropdown button on the top menu (right most) in intellij (after installing the plugin). 
Looks like this for me (last button on the right)
![screen shot 2017-04-21 at 09 56 10](https://cloud.githubusercontent.com/assets/6057330/25270533/ecc62608-2678-11e7-9a19-e147b531c56a.png)

**Comment by bergPro** [comment]
@thanos-irodotou thanks!~  I switched to dark theme succeed.

**Comment by whitehollow** [comment]
I'm using Webstorm and can't find it not in toolbar and in Tools.
