### ISSUE TITLE
Does not open the Project Structure

### ISSUE THREAD

**Issue by Neitan96** [ChrisRM/material-theme-jetbrains#33]
In IntelliJ 14 Ultimate does not open the Project Structure, when you click simply does nothing.

**Comment by ChrisRM** [comment]
That's just wierd. Try uninstalling the plugin and see if that helps. If it does, please let me know.

**Comment by Neitan96** [comment]
When I uninstall the plugin function normally

**Comment by ChrisRM** [comment]
Can you try now, @Neitan96?

**Comment by ChrisRM** [comment]
Should be fixed. Tested on IntelliJ IDEA 14 CE
