### ISSUE TITLE
React Syntax errors being hidden in Darker theme

### ISSUE THREAD

**Issue by johhansantana** [ChrisRM/material-theme-jetbrains#333]
When I have the Default code theme it shows the syntax `class` error:
<img width="309" alt="screen shot 2017-05-12 at 1 53 32 pm" src="https://cloud.githubusercontent.com/assets/9933887/26010331/7d4d592e-371a-11e7-8069-e6adae3a6524.png">

But with the darker theme it doesn't:
<img width="338" alt="screen shot 2017-05-12 at 1 53 46 pm" src="https://cloud.githubusercontent.com/assets/9933887/26010337/85e96a6e-371a-11e7-82a7-3f62f52240d0.png">

**Comment by mallowigi** [comment]
Is it fixed? I cannot repoduce

**Comment by johhansantana** [comment]
@mallowigi it seems with latest patch it has been fixed
