### ISSUE TITLE
The background color of Ignored folders in Darker actually draws attention to them

### ISSUE THREAD

**Issue by novaterata** [ChrisRM/material-theme-jetbrains#336]
I find the lighter gray background color of ignored folders, e.g. build, .gradle, to highlight the folders and draw attention to them, this is very distracting, especially when these folders are expanded. I would expect the color to be darker or slightly redder than the default. I would rather select all folders so that it's that uniform blue than to look at it as it is now.

**Comment by mallowigi** [comment]
Yeah I've got to the same conclusion. This is because of a setting in Settings -> File Colors. I don't know if we can change it with a plugin but if we can I'll fix it

**Comment by ChrisRM** [comment]
I think I've found a solution to this. Just need to do some tests before I commit the changes.

**Comment by mallowigi** [comment]
@ChrisRM any updates?

**Comment by mallowigi** [comment]
Partially fixed with the use of File Colors.
