### ISSUE TITLE
Directories have different icons in PHPStorm

### ISSUE THREAD

**Issue by thatside-zaraffa** [ChrisRM/material-theme-jetbrains#337]
Directories with data of same type have different icons.
![2017-05-26 10-29-19](https://cloud.githubusercontent.com/assets/25102329/26485541/255f74fe-4200-11e7-8722-586891de08df.png)
"src" directory is Sources Root. First and last directories inside are both Symfony bundles with the same inner structure.
![2017-05-26 10-33-48](https://cloud.githubusercontent.com/assets/25102329/26485540/253f9fc6-4200-11e7-8738-a2d79865d597.png)

**Comment by mallowigi** [comment]
Directories which have opened files are in "blue cyan". Currently there is a bug that the icon is not updated until there is a change in one file, but still this is the case. Also, this takes precedence over "module directories icons".

**Comment by thatside-zaraffa** [comment]
IMO this should be configurable - UI becomes too overloaded by different
icons with different sense.

26 мая 2017 г. 10:15 PM пользователь "Elior Boukhobza" <
notifications@github.com> написал:

**Comment by thatside-zaraffa** [comment]
Furthermore, excluded directories have the same icon in another color - this adds even more confusion.

**Comment by mallowigi** [comment]
I've added an option to disable this behavior. It will be available in next version.
