### ISSUE TITLE
Palenight theme has set background for php code

### ISSUE THREAD

**Issue by yeluolei** [ChrisRM/material-theme-jetbrains#339]
so the code area of this theme with php language is black. should be removed

<img width="790" alt="1" src="https://cloud.githubusercontent.com/assets/1005679/26622390/d1af7180-461c-11e7-8ca5-730133cf577e.png">

**Comment by mallowigi** [comment]
I think I will have to go over php color scheme

**Comment by Jorijn** [comment]
+1

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.
