### ISSUE TITLE
Can't load Logcat, Memory and sth else in Android Monitor in AndroidStudio

### ISSUE THREAD

**Issue by Syehunter** [ChrisRM/material-theme-jetbrains#34]
Just Like this：
![](http://7xn4z4.com1.z0.glb.clouddn.com/QQ图片20151009181809.png)

**Comment by ChrisRM** [comment]
Can you try to download the newest version and see if it works better?

**Comment by ChrisRM** [comment]
Fixed. Tested on AS 1.4

**Comment by Syehunter** [comment]
thks
