### ISSUE TITLE
PHP - Random lines on Palenight theme

### ISSUE THREAD

**Issue by joshbrw** [ChrisRM/material-theme-jetbrains#341]
Hey! I really like the new Palenight theme, it gives a nice balance between dark and light - good work!

I'm having one small issue with it though, it seems to be adding random lines around my `namespace` and `use` statements.

See the screenshot:

![screen shot 2017-06-01 at 13 48 48](https://cloud.githubusercontent.com/assets/779766/26680408/417e9afe-46d1-11e7-931e-11a017182f87.png)

Any help you could provide would be massively appreciated. I had a look around the settings but couldn't find how to get rid of it!

**Comment by mallowigi** [comment]
It's "method separator" option (Editor > General > Appearance)

**Comment by joshbrw** [comment]
Hi @mallowigi, thanks for your reply. Unfortunately I have `Show method separators` disabled, so I don't think this is the culprit. See the screenshot below:

![screen shot 2017-06-01 at 14 42 49](https://cloud.githubusercontent.com/assets/779766/26682538/ae888bd0-46d8-11e7-8ac3-95fe95ac66a7.png)

**Comment by mallowigi** [comment]
It's an issue with PHP files then, it works fine in other file types. Please open a bug in Jetbrains.
