### ISSUE TITLE
Incorrect yarn.lock icon

### ISSUE THREAD

**Issue by peet** [ChrisRM/material-theme-jetbrains#346]
![image](https://cloud.githubusercontent.com/assets/1421344/26826989/0fe00308-4ab3-11e7-90c9-0f78c44d7bff.png)

The `yarn.lock` file incorrectly gets the generic `*.lock` red padlock icon, and not the blue kitten icon.

It is probably due to the order they are declared in `icon_associations.xml`

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.
