### ISSUE TITLE
Respect other icon providers

### ISSUE THREAD

**Issue by segrey** [ChrisRM/material-theme-jetbrains#347]
From https://youtrack.jetbrains.com/issue/WEB-27172

IntelliJ IDEA 2017.1.3 Ultimate
![image](https://user-images.githubusercontent.com/607109/26874131-1e88d0d8-4b85-11e7-9099-565eb4afa1c5.png)
Here `node_modules/debug` icon is shown as excluded with "Material Theme UI" version 0.3.0.1. However, it's different without the plugin
![image](https://user-images.githubusercontent.com/607109/26874251-9d9ab2ba-4b85-11e7-8789-5351f20f5ef8.png).
It's done via com.intellij.javascript.nodejs.library.NodeModulesDirectoryIconProvider which provides normal (unexcluded) directory icons for folders corresponding to direct dependencies from package.json.

Since `MTFileIconProvider` is declared as "first" (https://github.com/ChrisRM/material-theme-jetbrains/blob/v0.3.0.1/src/main/resources/META-INF/plugin.xml#L27), is it possible to take into account icons provided by other IconProvider?

**Comment by segrey** [comment]
Maybe it could be fixed with calling `PsiIconUtil.getProvidersIcon(element, flags)` from MTFileIconProvider.getIcon and and returning null in MTFileIconProvider if it calls itself.

**Comment by segrey** [comment]
Just figured out that it could probably be fixed on IDE side as well. Will update later.

**Comment by mallowigi** [comment]
The problem is that as soon as an icon is found in another provider all other providers are skipped. Therefore the plugin should load as first.

If you dont like the icons, in the next version there will be an option to disable the MT icons (also available in the EAP)

**Comment by segrey** [comment]
@mallowigi Yeah, I meant `MTFileIconProvider` stays "first", however its [getDirectoryIcon](https://github.com/ChrisRM/material-theme-jetbrains/blob/v0.3.0.1/src/main/java/com/chrisrm/idea/icons/MTFileIconProvider.java#L56) method will ask all other providers via `PsiIconUtil.getProvidersIcon(element, flags)` (skipping itself to avoid cycling). Seems now getDirectoryIcon method repeats IDE logic. BTW, is the plugin intended to change directory icons as well? If no, it could just return `null`.

**Comment by mallowigi** [comment]
I know, and yeah the point is to take priority over other providers to use the custom icons rather than the ones provided by Jetbrains (unless they are not provided)

As for the directory icons, I was planning to vote whether to replace directory icons or use the ones provided by Jetbrains. Currently the only custom icons are the regular folder, decorated with the "open folder" from the Sublime theme. All other directory icons are taken from the previous icons. I thought about replacing them but I don't like some of Jetbrains such as the package ones, so I will rather try to use the Sublime icon with decorations for each of its flavors.

**Comment by segrey** [comment]
Thanks, I see. If there would be an option to decorate JetBrains icons then probably it makes sense to use `PsiIconUtil.getProvidersIcon(element, flags)`. Otherwise (if Sublime icons are used), no such change is needed. Feel free to close this issue. Will try to fix `ProjectRootManager.getInstance(project).getFileIndex().isExcluded(vFile)` to return `false` for folders corresponding to direct dependencies (e.g. `node_modules/debug`).

**Comment by mallowigi** [comment]
That gave me an idea, maybe I'll create an icon to target directly node_modules (maybe something like an folder icon with a nodejs icon or somewhat).

**Comment by segrey** [comment]
Fixed in https://youtrack.jetbrains.com/issue/WEB-27355

**Comment by mallowigi** [comment]
Since you're in the IDEA team, any chance you'll take a look at https://github.com/JetBrains/intellij-community/pull/590 so it wouldn't fall into oblivion?

**Comment by segrey** [comment]
I've pinged guys from the UI team.
