### ISSUE TITLE
Missing icons for sqlite

### ISSUE THREAD

**Issue by ilabacheuski** [ChrisRM/material-theme-jetbrains#348]
I use fork of this repo, but think it might be a common problem. The pack missing icons for sqlite. Here are some png for it: 
![sqlite](https://user-images.githubusercontent.com/10571879/26964673-546ad486-4cfb-11e7-84a4-7d4ec2de8d8b.png)
![sqlite 2px](https://user-images.githubusercontent.com/10571879/26964672-54676918-4cfb-11e7-9ab4-73fdaf3f6772.png)

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.

**Comment by ilabacheuski** [comment]
It's fixed. Close issue
