### ISSUE TITLE
Custom Scheme Reverts to Default when Application Reloads

### ISSUE THREAD

**Issue by kkozee** [ChrisRM/material-theme-jetbrains#35]
Description: When a user saves a custom color and font scheme, applies it to the IDE, closes PhpStorm and then reopens it, the default scheme is automatically reapplied.

Steps to reproduce:

1) Go to Preferences > Colors & Fonts
2) "Material Theme - Default" is selected
3) Click "Save As..." and save new custom scheme name (i.e. "Material Theme - Default copy")
4) Make any changes such as font size and line spacing
5) Click "Apply"
6) Close PhpStorm and reopen
7) Head back to Preferences > Colors & Fonts to see that "Material Theme - Default" is once again selected.

**Comment by ChrisRM** [comment]
This was a known problem with the first release, but should be fixed now. Please download the newest build and try again.
