### ISSUE TITLE
Theme in statusbar options is not saved

### ISSUE THREAD

**Issue by osieffert** [ChrisRM/material-theme-jetbrains#350]
The option "theme in statusbar" is not saved. When PyCharm restarts, the theme bar appears again even if the checkbox is unchecked.

**Comment by thatside-zaraffa** [comment]
PHPStorm affected too. Furthermore, re-clicking the checkbox doesn't always hides the bar.

**Comment by mallowigi** [comment]
I know about this bug. It will be fixed on next release
