### ISSUE TITLE
Improper C++ file icon displayed for *.cc files.

### ISSUE THREAD

**Issue by joshru** [ChrisRM/material-theme-jetbrains#351]
It seems the theme will only show the C++ icon for files named *.cpp but not for *.cc

I tried to clone this repo and change the extension associations myself but I couldn't get it working properly.

**Comment by mallowigi** [comment]
Yeah I used the C icon for .cc (I don't remember why I did that but I assumed that it was the correct extension)

**Comment by joshru** [comment]
I can live with the C icon if you prefer having the .cc associated in that way. The nice blue C++ icon matches this pretty theme better though :wink:
