### ISSUE TITLE
Panels/tabs not matching theme colors

### ISSUE THREAD

**Issue by tarciozemel** [ChrisRM/material-theme-jetbrains#352]
I just updated the plugin and Project/Project Files panels don't match the chosed theme. Before I update, all the panels/tabs were dark instead using the Default theme bluish color.

I already tried to manually delete the icls files, as instructed in README, but here's a screenshot of my PhpStorm's at this moment (2017.1.4 build #PS-171.4694.2):

![phpstorm-material-bug](https://user-images.githubusercontent.com/133777/27045088-4cebcd78-4f76-11e7-8a66-b2a5538c7c3a.png)

At status bar, "Material Theme - Default" appears even I'm choosing Darker.

**Comment by mallowigi** [comment]
ARE you talking about the Darker color scheme maybe? To change the color of the ide you need to select a theme from the material theme icon on the toolbar (blue dot), not from the settings.

**Comment by tarciozemel** [comment]
My toolbar were hidden, sorry about that. Anyways, after choosing at the right place, colors still not matching as the README screenshot:

![captura de tela de 2017-06-12 14 13 58](https://user-images.githubusercontent.com/133777/27046106-98abd44e-4f79-11e7-99db-dc6c045547b6.png)

**Comment by mallowigi** [comment]
This is because you have Contrast mode enabled :)

--
Elior

**Comment by tarciozemel** [comment]
Unfortunately, it's not. Even deactivating the Contrast, it still doesn't look exactly like the screenshot shown in the README.

Anyway, now the colors are very close and thank you for all your help.

Regards.

**Comment by mallowigi** [comment]
If you are talking about the "Project" toolbar not being painted, then I agree. This was a feature that I implemented but which prevented Theme Switching to function correctly, so I removed it until I found a workaround. 

But as soon as I found the solution I will post the update with it. Cheers :)
