### ISSUE TITLE
New background-image won't go away.

### ISSUE THREAD

**Issue by LasseRafn** [ChrisRM/material-theme-jetbrains#353]
I keep changing the settings to another image or lower transparency to 0, but the image comes back after every restart.

**Comment by mallowigi** [comment]
Odd, it doesn't happen in my machine (classic...)

Which IDE? OS?

**Comment by bitecodes** [comment]
I have the same problem:

PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
Mac OS X 10.12.5

**Comment by LasseRafn** [comment]
Thats odd!

Clearning does not work either. In reference to the other issue.

macOS 10.12.5
PhpStorm 2017.1.4

**Comment by LasseRafn** [comment]
Demo:

![out](https://user-images.githubusercontent.com/2689341/27083571-498a70ca-5049-11e7-8e4a-4f7c11344e1d.gif)

**Comment by mallowigi** [comment]
I understand now, but yeah this is the expected behavior

From the README: 

> Therefore some things need to be known:

> If you rather want to use the IDE's feature, turn off the option in the Material Theme completely. This will prevent the background to be changed at start.
> If you want to disable the background completely, set the custom wallpaper path to be empty and the checkbox on, then click Apply, and finally uncheck the option and save.
> And same if you want to disable the plugin, it will not revert back the blank wallpaper, you will have to open the IDE's dialog.

**Comment by LasseRafn** [comment]
Ah, okay! Thanks :)

Where would that setting be?

**Comment by mallowigi** [comment]
Oh yeah I forgot to add the settings to this list as well...

It's on Preferences > Tools > Material Theme > Custom Wallpaper

**Comment by LasseRafn** [comment]
Thanks! And sorry for the trouble.. 

This is absolutely my favorite plugin for PhpStorm, thanks for maintaining it 👍 !
