### ISSUE TITLE
Background image when no editor tabs are open does not revert when uninstalling

### ISSUE THREAD

**Issue by davidvandusen** [ChrisRM/material-theme-jetbrains#354]
The latest version adds a background image when no editor tabs are open. When uninstalling the plugin, this image remains and there appears to be no recourse for removing it. I am not referring to a custom background image set using **set background image**, but rather to the background image that is shown when no files are open.

**Comment by davidvandusen** [comment]
This may be what https://github.com/ChrisRM/material-theme-jetbrains/issues/353 is referring to. I am using both WebStorm 2017.1.4 and RubyMine 2017.1.3 on macOS 10.12.5.

**Comment by davidvandusen** [comment]
Manual recourse is available after uninstalling, but I still believe it should be part of the uninstall. One may go to **Set Background Image**, choose the **Frame** radio button, and press **Clear**.

**Comment by mallowigi** [comment]
I've added a section to the readme to explain these issues .
