### ISSUE TITLE
'Material Theme - Palenight' not an option in Colors & Fonts

### ISSUE THREAD

**Issue by kylechadha** [ChrisRM/material-theme-jetbrains#356]
Just a heads up I don't see 'Material Theme - Palenight' as an option under Scheme in Editor > Colors & Fonts > Font.

Fantastic theme otherwise. 👍

**Comment by mallowigi** [comment]
Fon't know what you're talking about

**Comment by kylechadha** [comment]
In the readme it states:
```
In the Scheme dropdown, you'll find 4 new schemes: Material Theme - Default, Material Theme - Darker, Material Theme - Palenight and Material Theme - Lighter.
```

When I look at the Scheme drop down, I see Default, Darker, and Lighter, but no Palenight.

**Comment by mallowigi** [comment]
Which IDE? Os?

**Comment by mallowigi** [comment]
Cannot find this... Are you on Android Studio maybe?

**Comment by kylechadha** [comment]
IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

OS X El Capitan
Version 10.11.6

**Comment by mallowigi** [comment]
2016 versions are still using version 0.2.3 of the plugin yeah. You need to update the IDE.

--
Elior
