### ISSUE TITLE
Misalignment between lines and text in non-editor panels

### ISSUE THREAD

**Issue by jrsall92** [ChrisRM/material-theme-jetbrains#357]
I'm using the them for quite a while now and I have noticed that in some places (such as the event log) the line and the actual text are not aligned. More specifically, the text seems to have some more "background" to it, resulting when having the cursor on some text on a line, the text on the line above gets partially obstructed. that happens only when the window is active. I'm running Linux (fedora + gnome), if that has anything to do with it. Here it is how it looks:

![material-theme-issue](https://user-images.githubusercontent.com/4698389/27233307-e81eed60-52b0-11e7-9fe6-92360611c50a.png)

**Comment by mallowigi** [comment]
Sorry, cannot test on Linux ATM. If you are courageous enough to look it by yourself and send me a PR with the fix I'll gladly accept it :)
