### ISSUE TITLE
Variables are not highlighted

### ISSUE THREAD

**Issue by borNfreee** [ChrisRM/material-theme-jetbrains#36]
Hi,

when I click to the variable (double click or set cursor to the variable) it is not highlighted (or underlined) in other places in this file. So it's not possible to understand where this variables is used

**Comment by ChrisRM** [comment]
An improved version of the colour schemes are coming soon. :-)

**Comment by borNfreee** [comment]
This bug is not fixed and should be reopened. When you doubleclick to variable - **all** variables with the same name should be highlighted

**Comment by maksrafalko** [comment]
+1 to reopen this issue.

**Comment by ChrisRM** [comment]
Did you try the latest build, @maksrafalko?

**Comment by maksrafalko** [comment]
20 minutes ago. Bug is not fixed :(default theme).

Ps it would be great to add version to the archive or hash
19 окт. 2015 г. 8:02 PM пользователь "Chris Magnussen" <
notifications@github.com> написал:
