### ISSUE TITLE
[cosmetic] Line spacing in the file explorer seems to be a bit too much

### ISSUE THREAD

**Issue by salmansamie** [ChrisRM/material-theme-jetbrains#362]
<img width="368" alt="screen shot 2017-06-21 at 12 50 17" src="https://user-images.githubusercontent.com/17569327/27382887-9aec368c-5680-11e7-95a6-9ec032636573.png">

The line spacing in the project explorer seems to be a bit too much. I do have to frequently scroll to switch between a large number of files. I guess 0.5 would be better instead of 1 for most users.

**Comment by mallowigi** [comment]
There is an option to set "compact scrollbars"

**Comment by salmansamie** [comment]
I can't seem to find it in pycharm

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/27384431-7c70be5a-5697-11e7-9e44-1a485017e17a.png)

**Comment by salmansamie** [comment]
awesome! that worked. Thanks a lot @mallowigi
