### ISSUE TITLE
PhpStorm 2017.1.4 Color parsing

### ISSUE THREAD

**Issue by Dexvi** [ChrisRM/material-theme-jetbrains#363]
After reinstalling PhpStorm on my desktop some colors seem to be off. 

As you can see here a string with an variable in it becomes completly blue instead of the text being green and the variable another color. The color of the variable itself is also white now.
![stringparsing](https://user-images.githubusercontent.com/4672982/27422324-fe34c5e4-572d-11e7-963a-6f285de44862.PNG)

Overhere you can see protected variables are red here and while using $this it's white again.
![parsing](https://user-images.githubusercontent.com/4672982/27422375-350ea346-572e-11e7-9753-357ddd50f776.PNG)

When I did put back my original backup of all my settings all my variables where red again as I could remember it to be. I am almost running a clean PhpStorm and even tried it with a clean version.

## Information

- Application: PhpStorm
- Application version: 2017.1.4
- OS: Windows 10 Creators update

## Installed plugins

> AngularJS
Apache config (.htaccess) support
ASP
Behat Support
Blade Support
Codeception Framework
CodeGlance (Installed by myself)
CoffeeScript
Command Line Tool Support
Copyright
CSS Support
CVS Integration
Database Tools and SQL
Docker integration
Drupal Support
File Watchers
Gherkin
Git Integration
GitHub
GNU GetText files support (*.po)
Google App Engine Support for PHP
Haml
hg4idea
HTML Tools
Ini4Idea
IntelliLang
JavaScript Debugger
JavaScript Intention Power Pack
JavaScript Support
Joomla! Support
Less support
LiveEdit
Markdown support
Material Theme UI  (Installed by myself)
NodeJS
Perforce Integration
Performance Testing
Phing Support
PHP Annotations
PHP Docker
PHP Remote Interpreter
PHPSpec BDD Framework
PhpStorm Workshop
QuirksMode
Refactor-X
Remote Hosts Access
REST Client
ReStructuredText Support
Sass support
Settings Repository
SSH Remote Run
String Manipulation
Subversion Integration
Task Management
Terminal
TextMate bundles support
Time Tracking
tslint
Twig Support
UML Support
Vagrant
W3C Validators
WordPress Support
XPathView + XSLT Support
XSLT-Debugger
YAML

**Comment by mallowigi** [comment]
You're right. There is a property called "concatenation" which you can override its color. Don't know who would want to use this :/

Will be fixed on next version but on the meantime, you can override this at Settings > Colors > PHP > Strings > Concatenation

**Comment by Dexvi** [comment]
Thank you for you response and your workaround!

**Comment by pix2D** [comment]
On the default theme everything looks great. On the darker theme if you have HTML in a string then variables don't have colors (but the HTML tags do). I tried playing with string concatenation but it didn't have any affect.

```
echo "Test"; // looks fine
echo "Test $test"; // looks fine
echo "Test $test <br/>"; // Test and $test are the same color
```

**Comment by pix2D** [comment]
Found it, XML > Tag data. Set it to #C3CEE3 and then it's the same behavior as the default color scheme. Or set to #C3E88D to have the text colors identical regardless of what else is in the string.

**Comment by mallowigi** [comment]
would you be kind to do a PR ???

**Comment by pix2D** [comment]
Sure, I assume you prefer the same behavior as the default color scheme?

In my eyes it's not enough contrast since variables are white in the darker color scheme and having it a slight variation of white still makes it pretty similar. For that reason I prefer it set to #C3E88D, then the normal text in all strings is the same regardless of additional HTML (which is colored correctly).

**Comment by pix2D** [comment]
Default color scheme color:

[Imgur](http://i.imgur.com/vxKGxO0.png)

My preference (#C3E88D, same as default string color):

[Imgur](http://i.imgur.com/gglcmvm.png)

**Comment by mallowigi** [comment]
I think the first one makes more sense because we are talking about a template string. e.g. If the string was something more than this, such as 

![image](https://user-images.githubusercontent.com/5015756/28106826-1946d212-66ee-11e7-8b52-e11193855c1f.png)

so I wouldn't expect my html to be green.

**Comment by pix2D** [comment]
Ah I understand, I rarely have strings like that so not something I considered. PR submitted. :)

**Comment by delmicio** [comment]
![image](https://user-images.githubusercontent.com/2908209/58911052-661c1b80-86ed-11e9-9227-c90f901ea218.png)
Hi guys, how do I fix this with the Arc Dark theme?

> PhpStorm 2019.1.2
> Build #PS-191.7141.52, built on May 8, 2019
> JRE: 1.8.0_202-release-1483-b49 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> macOS 10.14.5
