### ISSUE TITLE
Error within PHPStorm

### ISSUE THREAD

**Issue by Karl456** [ChrisRM/material-theme-jetbrains#364]
This is only a small thing, but since upgrading to the new version I've been getting this error in PHPStorm:

`Icon cannot be found in '/icons/plugins/fileTypes/plist.png', aClass='class com,chrisrm.idea.icons.MTFileIconProvider'`

Just an annoying issue as PHPStorm warns me every 30 mins or so!

**Comment by mallowigi** [comment]
Please see #360
