### ISSUE TITLE
the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by satish-vellanki** [ChrisRM/material-theme-jetbrains#369]
Installing this on IntelliJ IDEA 14 gives me this error:
![image](https://user-images.githubusercontent.com/16909558/27661228-5e7fabe6-5c0e-11e7-90b0-8d1e6bfca48e.png)

JDK:
```
$ java -version                                                                                                                
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

I understand this is a certificate issue, does anyone else have this? Anyway to fix this? Is there a workaround? Thanks.

**Comment by mallowigi** [comment]
IDEA 14 is not supported anymore, sorry.
