### ISSUE TITLE
can't find 3 Material Themes in Colors & Fonts

### ISSUE THREAD

**Issue by chanxiaoxi** [ChrisRM/material-theme-jetbrains#37]
in the three step:
Go to Preferences -> Editor -> Colors & Fonts -> Scheme -> Choose between the 3 Material Theme's.
can't find Material Themes

**Comment by ChrisRM** [comment]
Make sure the plugin is installed. Under plugins, you'lll find Material Theme UI

**Comment by chanxiaoxi** [comment]
![qq20151009-0 2x](https://cloud.githubusercontent.com/assets/5090432/10397893/a5ba412c-6edc-11e5-8a3b-751151493c45.png)
Material Theme UI has installed,the phpstorm theme changed,but the editor field doesn't change
![qq20151009-2 2x](https://cloud.githubusercontent.com/assets/5090432/10397968/fa9c8c18-6edc-11e5-94f2-a51f368570ed.png)
 Colors & Fonts also can't find 3 Material Themes 
![qq20151009-1 2x](https://cloud.githubusercontent.com/assets/5090432/10398024/5c9033fc-6edd-11e5-8466-a861adc25342.png)
how can i fix it ?

**Comment by ChrisRM** [comment]
You can download the schemes from [here](https://github.com/ChrisRM/material-theme-jetbrains/tree/master/resources/colors) and place them in ~/Library/Preferences/WebIde90/colors.

I will check why they wasnt installed when you installed the plugin.

**Comment by chanxiaoxi** [comment]
In ~/Library/Preferences/ there is not WebIde90 folder, only WebIde80 folder exists, in WebIde80/colors there are some *.icls files.
My PHPStorm version is 8.0.3,Mac OS version is 10.11

**Comment by ChrisRM** [comment]
Put them in the WebIde80/colors folder

**Comment by chanxiaoxi** [comment]
It doesn't work!
PHPStorm Error Message: ``` Cannot read scheme Material Theme - Default.xml from '$ROOT_CONFIG$/colors' ```

**Comment by ChrisRM** [comment]
Try renaming the extension to .icls

**Comment by chanxiaoxi** [comment]
It not work! same error message!

**Comment by ChrisRM** [comment]
Not sure what causes this. Try upgrading to 9.0 maybe?
