### ISSUE TITLE
Default view references remote tracking image

### ISSUE THREAD

**Issue by AndyGee** [ChrisRM/material-theme-jetbrains#370]
The default view uses a background image that appears to be uses as a remote tracking image over https.
Behind a firewall the remote access is blocked and the certificate is not trusted. I get this every time a project is opened:
![image](https://user-images.githubusercontent.com/2536412/27725320-083cd25e-5d76-11e7-899d-820d7b7dbeb6.png)

I uninstalled the theme wanting to resolve this issue, but this single change is not reverted (i.e. the image is not uninstalled).

Please consider removing this remote image call from the theme, or adding the option to disable it. Especially when the theme is uninstalled.

**Comment by mallowigi** [comment]
If you want to remove the image, when you have no tabs opened, open the Command Palette (Ctrl-Shift-A) and select "Set background image" then remove the value set by the plugin.
