### ISSUE TITLE
Font crash after 5.0 update

### ISSUE THREAD

**Issue by wojtek1150** [ChrisRM/material-theme-jetbrains#373]
![image](https://user-images.githubusercontent.com/5401942/27818097-80b3b664-6094-11e7-902f-885457764c89.png)

After switch color theme to another some of text are back to normal, but still..

**Comment by mallowigi** [comment]
Hmm, you probably have a wrong instance of Roboto, maybe a different script or something. Change this in Settings > Appearance > Font

**Comment by BeeeQueue** [comment]
This is happening for me as well, the Roboto font seems corrupt in the IDE, while its variants are fine.

![Example](http://i.imgur.com/212fUOh.png)

**Comment by mallowigi** [comment]
Can you install it from the google fonts again? Maybe you have a corrupted version or something but in any case this is not something related to the plugin.

**Comment by wojtek1150** [comment]
@mallowigi Already tried. Still same. In other programs like Photoshop all is fine with this font

**Comment by mallowigi** [comment]
Well I have no fix for you then... Please set up another font in the settings.

Just for info, can you give me your system information? IDE, OS, JDK version...

**Comment by wojtek1150** [comment]
Other fonts, like OpenSans works fine, so for me there is no problem, but I think its plugin or IDE error if in any other apps font works fine. Sys info below

PhpStorm 2017.1.4
Build #PS-171.4694.2, built on May 16, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
