### ISSUE TITLE
version 5.0 suddenly makes my menu fonts and icons very small

### ISSUE THREAD

**Issue by musicformellons** [ChrisRM/material-theme-jetbrains#374]
This was working fine under my former version (4.4 ?). When I try to install the former version the problem remains...!

Here picture of problem with version 5.0 (I have HDPi screen):
![screenshot from 2017-07-04 21-48-38](https://user-images.githubusercontent.com/10334123/27841667-a5a41f4e-6103-11e7-9ec9-b3023bcf330c.png)

**Comment by mallowigi** [comment]
Hmm, it is probably because I'm setting the font size to 12 pixels... 
I really need to find an hidpi screen... 

Anyway for the moment you can fix this by going to Settings > Appearance > Override default fonts and select a better suited font and size.

Sorry for the troubles.

**Comment by musicformellons** [comment]
Yeah, after setting it to roboto thin size 30 it looks much better. Thanks.
