### ISSUE TITLE
Unreadable font

### ISSUE THREAD

**Issue by KraXarN** [ChrisRM/material-theme-jetbrains#377]
Just updated IntelliJ today to 2017.1.5. With it, it also updated the theme to 0.5.0, but when I started it up again, I was greeted to a weird, almost corrupted font
![](https://vgy.me/THQtGR.png)
I eventually managed to get into the font settings and after changing it, it got fixed.
However, instead of saying Roboto to the corrupted font (which I assume is what it is), it called it something else
![](https://vgy.me/9YdL3T.png)
Is there something wrong with the theme or the font installed on my pc?

**Comment by KraXarN** [comment]
Nevermind, reinstalling the theme and the font seems to have fixed it.

**Comment by DarthIwan** [comment]
I have exact the same issue. Reinstall do not help, the font is still unreadable. Any suggestions?

**Comment by kidroca** [comment]
I have the same problem, only after deleting `Users\me\.WebStorm2018.2\config\plugins\Material Theme` the problem got fixed - Andorid Studio is affected too
https://youtrack.jetbrains.com/issue/WEB-35260

**Comment by kidroca** [comment]
Reinstalling Material Theme Ui (or maybe this version) would break the fonts again:

![image](https://user-images.githubusercontent.com/12156624/46771377-ed022b00-ccfb-11e8-89b9-40ba17143794.png)

**Comment by mallowigi** [comment]
Try reinstalling the font from Google Fonts again.

**Comment by kidroca** [comment]
Thanks deleting and reinstalling Robot Font family from google fonts fixed this

Related to #957
