### ISSUE TITLE
Feature request: ability to set scrollbars opacity

### ISSUE THREAD

**Issue by Birowsky** [ChrisRM/material-theme-jetbrains#378]
Everything is hella beautiful in distraction free mode. But the scrollbars stand out like crazy. I would rather have them be barely visible.

**Comment by mallowigi** [comment]
I have already created an option to set a 0.5 opacity to scrollbars, so if you have the latest version of the theme you can play with that.

I don't want to add settings to customize the opacity though to not give too much customization, so a lot of people are asking for it, it will stay like this :)

**Comment by Birowsky** [comment]
I'm not able to find the opacity option:
<img width="794" alt="screen shot 2017-07-09 at 11 27 05" src="https://user-images.githubusercontent.com/3199950/27992632-8fbba8de-6499-11e7-8bd5-249c876bfe4f.png">

Also, I kinda didn't get it, are you going to add custom opacity option or not?

**Comment by mallowigi** [comment]
Normally if you have "Themed scrollbars" on you should have a reduced opacity scrollbars

![image](https://user-images.githubusercontent.com/5015756/27993117-9fe906b8-64ab-11e7-8601-65bf86993c5f.png)

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/27993127-c17b31fc-64ab-11e7-9f92-a72419f1c01f.png)

**Comment by mallowigi** [comment]
Though I saw that there was a problem with the Lighter theme, but I fixed that for next release

**Comment by Birowsky** [comment]
nice. thanx.

**Comment by Birowsky** [comment]
please don't forget the bottom scrollbars :}

<img width="242" alt="screen shot 2017-07-09 at 13 38 17" src="https://user-images.githubusercontent.com/3199950/27993474-0ce97770-64ac-11e7-9ce6-45e2ae967803.png">
