### ISSUE TITLE
Indents don't work when using Material Theme UI plugin

### ISSUE THREAD

**Issue by IvanBernatovic** [ChrisRM/material-theme-jetbrains#380]
Like the title suggests, when using Material Theme UI plugin in PHPStorm my settings for Blade templating engine (Settings -> Editor -> Code Style -> Blade) don't work. They work in Darcula theme which was my previous theme of choice. So my preference is having Tab Size, Indent and Continuation Indent all set to 2, but on Material Theme those settings don't work as pressing tab creates 4 spaces, not 2. I created my scheme which is duplicate of Default IDE scheme and it still didn't work. When I uninstalled Material Theme UI plugin everything worked fine again. So I guess that's an issue with plugin. Or I didn't understand something correctly?

**Comment by mallowigi** [comment]
Ok first of all, what are your specs?

IDE? OS? JDK? Material Plugin version?

**Comment by mallowigi** [comment]
bump

**Comment by IvanBernatovic** [comment]
Sorry for not responding, it was weekend.

So, my info:
IDE: PHPStorm 2017.1.4
OS: Linux Mint 18.2 (based on Ubuntu 16.04 LTS)
JDK: openjdk version "1.8.0_131"
Material Plugin was latest version. Installed it via PHPStorm Settings -> Plugins. It says it's v0.5.0.

Anyway, just to check again I tried to install Material Theme UI again and now indents work fine. Really strange. But I'm sure that indents didn't work properly last time even after restarting PHPStorm, what worked for me was uninstalling Material Theme UI. But now it works so I really don't know what happened. Maybe PHPStorm got bugged cause of something else that resolved after uninstalling and installing unrelated plugin like yours?
