### ISSUE TITLE
Cannot install on IntelliJ Idea 14

### ISSUE THREAD

**Issue by doomsbuster** [ChrisRM/material-theme-jetbrains#381]
Cannot install this plugin on my version of IntelliJ Idea Ultimate 14. When i click the install plugin button, the IDE shows a progress bar on the status bar, and then performs no action.

![image](https://user-images.githubusercontent.com/4811092/27996217-7880ac02-64ab-11e7-80ec-7d2562c96f33.png)

**Comment by mallowigi** [comment]
You would normally be able to install version 2.3.2, but if you are not able, but if you aren't, it means that something has changed since then, and unfortunately we've stopped supporting versions prior to 2016.1.4 (145.xxxx)
