### ISSUE TITLE
patreon, flattr, gratipay, bountysource, bitcoin, coinye etc.

### ISSUE THREAD

**Issue by michahell** [ChrisRM/material-theme-jetbrains#382]
Have a 'support us' part on your readme or something similar!
You guys are doing great work, I've been using Material theme for Webstorm for a while now, it's great, a gazillion times better than the default stuff there is.

**Comment by mallowigi** [comment]
There is already one!

**Comment by mallowigi** [comment]
Actually maybe I'll look into it, it will be the occasion to learn something new. Thanks for the tip :)

**Comment by michahell** [comment]
👍  !

**Comment by mallowigi** [comment]
Ok i've looked at it and it is bothersome for some of them. So I think we can close this.

Thanks though (and my Paypal account is still working ;))
