### ISSUE TITLE
Disable MT Theming

### ISSUE THREAD

**Issue by georgejdanforth** [ChrisRM/material-theme-jetbrains#383]
I'd like to disable the theming and use the Darcula theme, as mentioned in the documentation, however the only options I'm seeing are the following:
<img width="334" alt="screen shot 2017-07-11 at 9 29 37 pm" src="https://user-images.githubusercontent.com/13291384/28097808-6b077d86-6680-11e7-985c-7a0d480ba6d8.png">

Is this meant to be accomplished in a different way and I'm just being silly?

I'm using version 0.5.3.4 on PyCharm.

Thanks!

**Comment by mallowigi** [comment]
There is an option in the settings "Disable Material Theme"
