### ISSUE TITLE
Hard to read font since upgrading to 0.5.0 - Windows 10

### ISSUE THREAD

**Issue by mattisdada** [ChrisRM/material-theme-jetbrains#387]
Currently I am on Windows 10, when first launching the IDE (PhpStorm) with 0.5.0 all "system" fonts (everything but the code editor) has very blurry edges (honestly, gives me a headache trying to read).

If I switch Material themes back and forth the File Tree becomes good again (but the rest of the IDE still has blurry font)

This only started happening since upgrading to 0.5.0, was running fine on 0.4.*. Haven't upgraded PhpStorm in-between or touched fonts. 

Thanks!
-----------
First Launch:
![image](https://user-images.githubusercontent.com/314500/28154125-39830d8a-67ec-11e7-98a1-e114541856fc.png)

Switching the Material Theme and back:
![image](https://user-images.githubusercontent.com/314500/28154193-7b11fa54-67ec-11e7-8a1c-6729c2d351ac.png)

**Comment by mallowigi** [comment]
Do you have Roboto font installed? If not I suggest you do. If yes, maybe it's because it doesn't render well on 12px. Try to set it to 14 px (Appearance > Override default fonts).

If you don't want Roboto you can switch back to Tahoma, like your screenshot.

**Comment by mattisdada** [comment]
I already had Roboto installed, I also updated it from https://github.com/google/roboto to the latest version (it didn't make a difference)

Setting the font from 12px to 14px did not help, just made the fonts bigger (but still blurry). 

--

A workaround I am doing at the moment is over-ridding the font to be Sagoe UI under Appearance. But I still consider this an open bug, I imagine other users in similar environments may be having issues

**Comment by mallowigi** [comment]
I have troubles understanding why Roboto would have such problems rendering, but anyway I'm using in a Windows and Mac environment and it works very well.

There's not much I can do except redirecting users who encounter troubles to revert back to another font from the Settings.

**Comment by LasseRafn** [comment]
Thanks for informing about Tahoma default font 👍 Roboto feels wrong for me (used to Tahoma I guess)

**Comment by mattisdada** [comment]
Seems fixed now:
https://github.com/mallowigi/material-theme-jetbrains-eap/issues/87

Although I think it no longer defaults to Roboto?

**Comment by mallowigi** [comment]
Just checked, and it did defaults to Roboto
