### ISSUE TITLE
Can't change main code look

### ISSUE THREAD

**Issue by PiggyPiglet** [ChrisRM/material-theme-jetbrains#389]
Hi, the theme works on everything apart from this, ![Problem](http://i.imgur.com/qGxdSRA.png) No clue what I've done wrong here.

**Comment by mallowigi** [comment]
Just change the color scheme in the Settings.

**Comment by PiggyPiglet** [comment]
I tried that, the material theme doesn't come up in the scheme dropdown.

**Comment by mallowigi** [comment]
Which version? IDE? OS?

**Comment by PiggyPiglet** [comment]
Windows 10 Home
2017.1.5
0.5.3.4

**Comment by mallowigi** [comment]
Hmmm 

Have you tried uninstalled and reinstalled the plugin? I have no idea why it happens.

Which color schemes do you see?

**Comment by PiggyPiglet** [comment]
Hmm, I see them in schemes now. This is very strange, sorry for wasting your time.
