### ISSUE TITLE
Lacking Java / Windows Support?

### ISSUE THREAD

**Issue by tbezman** [ChrisRM/material-theme-jetbrains#39]
I want to start off by thanking you for porting my favorite theme ever to Jetbrains for realz!

Not sure if we're lacking some Java support or if it's because I'm on Windows, but here's the default.
![2015-10-09_16-47-43](https://cloud.githubusercontent.com/assets/6754223/10405236/9c7ea102-6ea5-11e5-8121-0b3cec804742.png)

**Comment by ChrisRM** [comment]
I haven't added any Java-specific settings in the colour scheme yet. I'll fix that very soon

**Comment by b3zman41** [comment]
Thanks so much for all of the effort you're putting into this, seriously appreciate it.

**Comment by ChrisRM** [comment]
No problem, glad you like it :+1:

**Comment by kisstkondoros** [comment]
As can be seen in the image these are the differences now:
1. Package coloring is better in Idea
2. Class coloring is not implemented in IDEA (it is not possible AFAIK)
3. Parameter coloring (can be done I suppose)
4. This and super are keywords in Java, I don't know why sublime highlights them in red (missing reference perhaps)

![image](https://cloud.githubusercontent.com/assets/14231157/10412839/d41a1914-6f92-11e5-9c4b-853ab8931505.png)

**Comment by ChrisRM** [comment]
Actually, there are class and interface scopes in IDEA. I'll be sending out an update soon. I want to get the default theme as close 100% as possible before doing the darker and lighter versions.
