### ISSUE TITLE
Remove italic style

### ISSUE THREAD

**Issue by iamkallolpratim** [ChrisRM/material-theme-jetbrains#392]
How to remove italic font style from the editor font?

**Comment by mallowigi** [comment]
look for places where it's italic in Colors And Fonts, then disable it.

**Comment by jasonrsmith** [comment]
Editing the color theme settings files directly seems to work:
```
sed -i '/<option name="FONT_TYPE".*/d' <jetbrains settings dir>/colors/*
```
e.g.
```
sed -i '/<option name="FONT_TYPE".*/d' ~/Library/Application Support/JetBrains/WebStorm2020.1/colors/*
```

**Comment by Starkemis** [comment]
@mallowigi Every 60 seconds in Africa, a minute goes by.
