### ISSUE TITLE
No Settings -> Tools -> Material Theme

### ISSUE THREAD

**Issue by ConstLhq** [ChrisRM/material-theme-jetbrains#393]
### No "Settings -> Tools -> Material Theme" can be found
All works fine but failed to find customize  plugin features in  Settings Panel under Settings -> Tools -> Material Theme. Any help?
![Screenshotfrom2017-07-2114-25-54.png](http://pasteupload.com/images/2017/07/20/Screenshotfrom2017-07-2114-25-54.png)

### Environment

IntelliJ IDEA 2017.2
Build #IU-172.3317.76, built on July 15, 2017
Licensed to ***
Subscription is active until March 30, 2018
JRE: 1.8.0_131-8u131-b11-2-b11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.9.0-3-amd64

**Comment by mallowigi** [comment]
You're right, I need to update the README

Settings are now under Appearance
