### ISSUE TITLE
Colors in Background tree and Toogle Contrats Check Mark 

### ISSUE THREAD

**Issue by soyFerrero** [ChrisRM/material-theme-jetbrains#395]
### Summary

In the update 7 i can not change the background color of the file tree and the color of all toolbars.

Also in Toogle Contrats  in the new icon , the checkmarck ( ✓ ) doesn't work and does not produce any behavior

### Environment
WebStorm 2017.2
Build #WS-172.3317.70, built on July 14, 2017
Licensed to Ferrero

JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
Please open issues in the eap, I didn't release a version here specifically for those issues. And I've already opened an issue for this.
