### ISSUE TITLE
Feature Request: Arc Colors / Theme

### ISSUE THREAD

**Issue by ideaweb** [ChrisRM/material-theme-jetbrains#396]
I love this theme and use it already on Mac. 

But i would love to see it on Linux as well. Is it possible to add "Arc Colors/Theme"?

https://github.com/horst3180/arc-theme

Main/Background colors would be enough.

**Comment by mallowigi** [comment]
Looks like a lot of work! I would suggest that you work on it and submit me a PR when you feel ready.

It's not that hard, you will see.

**Comment by ideaweb** [comment]
The idea was not to make a full Arc Theme, just replace the dark "green" background colors from Material Theme - Default.xml to the dark "blue" one from Arc. 

But if i have time i will give it try to make it by self. =)

**Comment by mallowigi** [comment]
I've added the theme in the EAP v10. Please take a look.
