### ISSUE TITLE
Sidebar / Minor Tab issue

### ISSUE THREAD

**Issue by ideaweb** [ChrisRM/material-theme-jetbrains#397]
![screen shot 2017-07-26 at 11 49 02](https://user-images.githubusercontent.com/1529649/28615188-83cdd7a6-71f8-11e7-82bc-e5d1baa82315.png)

Any chance to make the title of sidebar just flat w/o border as other items? If sidebar is active is something blue, inactive it has a gradient which looks not nice.

There is a tiny issue for active tab. Some tiny dots are always shown.

Thx and great work!

**Comment by mallowigi** [comment]
Yeah, this color is not easy to change, it is embedded into the IDE code without any option to change it and even assembly hacking (what I'm doing for the title window for example) is not working so until Jetbrains decide to refactor their code to allow customization we're pretty much stuck like this.

**Comment by mallowigi** [comment]
As for the second problem... eh I don't want to waste time on something that small.
