### ISSUE TITLE
Customize sidebar color

### ISSUE THREAD

**Issue by Piero87** [ChrisRM/material-theme-jetbrains#398]
Hi,
I want know if it's possible change the side bar and theme general color, I have the One Dark color scheme because I very like the atom default theme, and I want change to have a uniform appearance. It is possible?

**Comment by mallowigi** [comment]
Hum, currently no, but this is a good idea of a feature for the version 1.0.

It demands a lot of refactoring though so it will take some time

**Comment by mallowigi** [comment]
However you can create a different theme for the "Default" one.  I am planning to create a wiki to explain how to customize your theme, and possibly let people submit their creations and incorporate the best ones in the plugin.

**Comment by Piero87** [comment]
A wiki would be amazing

**Comment by pix2D** [comment]
@mallowigi Sorry for the issue hijack but would a different theme for the "Default" perhaps fix (or help with) https://github.com/ChrisRM/material-theme-jetbrains/issues/379 ?

Just trying to think of solutions, it's the only thing really bugging me with the plugin. Having the cursor yellow is just not obvious enough with a normal light color scheme that has dark text (the material light color scheme is terrible IMO).

**Comment by mallowigi** [comment]
Yep I agree with that too, but the original author made it like that so...

If you have a better option just send me the updated color scheme and if its' good enough I can include it as a secondary theme.

**Comment by mallowigi** [comment]
About the original issue: I've added custom theme support in the EAP. 

Now you can have your own colors (it is still buggy though, but it should work nonetheless)
