### ISSUE TITLE
Tab height does not respect device DPI scaling

### ISSUE THREAD

**Issue by BeeeQueue** [ChrisRM/material-theme-jetbrains#399]
### Summary

Tab height does not respect device DPI settings, therefore when sharing settings over multiple computers - for example via a settings repository - they will either be too big, or unreadable because they're too small.

### Expected behavior

Tab height should be the same across multiple devices with different DPI settings.

### Actual behavior

Tabs have different heights with different DPI settings.

### Steps to reproduce (if needed)

1. Set tab height to 30px at screen settings 1080p with recommended (100%) DPI scaling.
2. Set screen settings to 4k, recommended (200%) DPI scaling
3. Tab names are now unreadable because of height cutting them off

**1080p 150% scaling:**

![webstorm64_2017-07-28_15-54-09](https://user-images.githubusercontent.com/472500/28720640-13121aa6-73ae-11e7-9c93-df81340748b7.png)

**4k 250% scaling:**

![webstorm64_2017-07-28_15-58-24](https://user-images.githubusercontent.com/472500/28720659-229824ac-73ae-11e7-957a-e943c6bca869.png)

### Environment

WebStorm 2017.2
Build #WS-172.3317.70, built on July 14, 2017
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Material Theme UI 0.5.0

**Comment by mallowigi** [comment]
you're right, fixing

**Comment by mallowigi** [comment]
Fixed in 7.2 (I hope, don't have a high DPI screen)

**Comment by BeeeQueue** [comment]
Can confirm fixed. 👍
