### ISSUE TITLE
white "$" and quotes

### ISSUE THREAD

**Issue by Cog-g** [ChrisRM/material-theme-jetbrains#4]
Hi and many thanks for you work.

I can't use the php.jar and phpstorm.jar because I'm on EAP version and it breaks, so maybe I miss something but on the Screenshop I've seen, you don't seems to have make the dollar sign in white, like the sublime text theme. Do you think it's possible, or PHPStorm does not allow this at all?

Same question for string's double quotes. Do you think it's possible to make them white?

**Comment by ChrisRM** [comment]
PhpStorm doesn't give me that scope, so as far as I know, that's impossible.

**Comment by ryanwinchester** [comment]
Yeah I tried doing it too, but not possible
