### ISSUE TITLE
Android Studio 1.4 stable problem

### ISSUE THREAD

**Issue by jdpxiaoming** [ChrisRM/material-theme-jetbrains#40]
when I install the Material-theme-jetbrains ,My Logcat under Android Monitor disappear or never be used .

**Comment by ChrisRM** [comment]
Did you use the latest [build](https://github.com/ChrisRM/material-theme-jetbrains/blob/master/Material%20Theme.jar)?

**Comment by jdpxiaoming** [comment]
YES,I follow your wiki like this .
Download Material Theme.zip
Open Preferences -> Plugins -> Install plugin from disk... and choose the zip.
Go to Preferences -> Editor -> Colors & Fonts -> Scheme -> Choose between the 3 Material Theme's.

**Comment by mikeerickson** [comment]
@chrisrm excellent work on this scheme. Really liking it a lot (now trying to find same scheme for iTerm).  Really appreciate your efforts.

**Comment by asker517** [comment]
@ChrisRM amazing theme for AS .. thanks very much ..

**Comment by jdpxiaoming** [comment]
@ChrisRM  My Environment  is AS 1.4 stable version at Ubuntu Mate (14.04) , I like this dark theme ,Thank you for your work!

**Comment by jdpxiaoming** [comment]
![screenshot-4](https://cloud.githubusercontent.com/assets/911702/10502239/821448c8-731c-11e5-8c8b-7533cb54ae3a.png)
![screenshot-5](https://cloud.githubusercontent.com/assets/911702/10502242/8e0deeb8-731c-11e5-9aa6-1c3e3879c1fb.png)

**Comment by ChrisRM** [comment]
Is this still an issue guys?

**Comment by skyrylyuk** [comment]
Android Studio 2.2 - can't reproduce, all working . I thinks it issue can be close.
