### ISSUE TITLE
Sidebar Font Color not matching your Screenshots

### ISSUE THREAD

**Issue by bgarrant** [ChrisRM/material-theme-jetbrains#400]
In the screenshots of Material Theme UI for PHPStorm the fonts in sidebar are white.  Mine seem to be blue when using default color scheme.  How can I get them to be white?
![screen shot 2017-07-31 at 11 12 25 am](https://user-images.githubusercontent.com/2436728/28784394-52f7005c-75e1-11e7-9a88-c0aee8345451.png)

**Comment by bgarrant** [comment]
This is from your screenshot.  I am using latest 2017.2 PHPStorm by the way.
![screen shot 2017-07-31 at 11 15 31 am](https://user-images.githubusercontent.com/2436728/28784499-a667c32a-75e1-11e7-833f-86bfd0b5325e.png)

**Comment by mallowigi** [comment]
I know, this is something new from version 0.7.2.

This is done in order to match the sublime theme. For now this is not customizable but if enough people want it I can add an option.

**Comment by FerusGrim** [comment]
This is actually a big problem for me. =/

I'm using the Dark theme, and all my file colors are so gray that they're kind of [hard to read](http://i.imgur.com/kejqUo2.png).

Additionally, they're just a _tad_ lighter than files which are ignored by `.gitignore`. It actually took me a few moments to realize that the `.gitignore` plugin wasn't marking all my files as ignored, for some reason.

I suppose "big problem" is probably a bit of an overstatement, but I much preferred the tone before the 0.7.2 update. I'd endorse and appreciate a way to modify it! <3

**Comment by mallowigi** [comment]
Can we close this?

**Comment by FerusGrim** [comment]
@mallowigi Would it be possible for you to explain how to make this switch? I'm really lost, after updating. =/

I think I found the section that controls it, but I don't know what the previous colors were. Or maybe I'm in the wrong place, entirely.

**Comment by mallowigi** [comment]
There is a section under Editor > Colors and Fonts > Material File Colors. There you can set different colors for the file statuses, the original default status being "Up to date".

If you set "Up to date" to #FFFFFF, you will have white colors for files. Otherwise leave it unchecked to use the blu-ish color.

**Comment by FerusGrim** [comment]
@mallowigi Thank you! :D

Is that the only file color that I have to worry about if I wanted the pre-0.7.2 scheme?

**Comment by FerusGrim** [comment]
I may be missing something, but this doesn't seem to be working, for me.
http://i.imgur.com/QImcBx6.png
