### ISSUE TITLE
Can not display Chinese.

### ISSUE THREAD

**Issue by txgs888** [ChrisRM/material-theme-jetbrains#403]
### Summary

Chinese will be garbled, but the editor will not.

### Expected behavior

none

### Actual behavior

Chinese garbled, i tried changing the font:

![qq 20170802230925](https://user-images.githubusercontent.com/22268227/28881792-dee47968-77db-11e7-929e-061fa80bda27.png)
![qq 20170802231018](https://user-images.githubusercontent.com/22268227/28881804-ea2e33fe-77db-11e7-804a-8bcef3272531.png)
![qq 20170802231040](https://user-images.githubusercontent.com/22268227/28881809-f14e93f4-77db-11e7-81e1-34cc0af445c9.png)

The editor will not:
![qq 20170802231146](https://user-images.githubusercontent.com/22268227/28881819-f95c5568-77db-11e7-8623-b08785a83e31.png)

### Steps to reproduce

1. Open Idea

### Environment

* Operating system and version:
* Windows 10 64bit
* IntelliJ IDEA 2017.1.4
* Material Theme UI v0.7.2

I really like this theme, hope you can fix, thank you

**Comment by mallowigi** [comment]
https://www.google.com/get/noto/

Please install this font then change the font under Settings > Appearance > Override default font

**Comment by txgs888** [comment]
This is effective, thank you.
![qq 20170804005837](https://user-images.githubusercontent.com/22268227/28933601-39390260-78b0-11e7-9fc3-ad7d9aa15fc2.png)

**Comment by harrisdt15f** [comment]
![default](https://user-images.githubusercontent.com/27404296/44327602-aa596a80-a491-11e8-8065-1a6d3daae756.png)
I have already set as noto fonts but still can't show me with chinese characters.
it show me below help me. thanks .
![default](https://user-images.githubusercontent.com/27404296/44327526-7bdb8f80-a491-11e8-8091-463b1a95cedc.png)
![default](https://user-images.githubusercontent.com/27404296/44327554-89911500-a491-11e8-8ba4-2466a1e7eb70.png)

**Comment by mallowigi** [comment]
You need to set the font inside Editor > Font

**Comment by harrisdt15f** [comment]
![default](https://user-images.githubusercontent.com/27404296/44524086-c289ed80-a70e-11e8-8719-e657cf322e84.png)
I set the font inside my editor font,but problem still not solve.

**Comment by mallowigi** [comment]
Tis because the Noto Sans Mono is probably not able to display Chinese characters
