### ISSUE TITLE
Statement selection highlight is absent

### ISSUE THREAD

**Issue by vishrutarya** [ChrisRM/material-theme-jetbrains#404]
### Summary
Upon updating to DataGrip 2017.2 Build #DB-172.3544.109, toggling between possible statements for execution does not highlight the corresponding lines of code.

### Expected behavior
When multiple statements are detected, `cmd + enter` pops up a menu palette and switching between the statements _highlights the corresponding lines of code_. This was the behavior in previous versions of DataGrip and Material Theme.

### Actual behavior
Switching between the statements in the menu palette _does not highlight the corresponding lines of code_.

### Steps to reproduce (if needed)

1. Obtain a query with multiple executable statements, e.g., use a `WITH` clause
2. `cmd + enter`
3. Toggle between the possible statements to be executed
4. Observe whether 

### Screenshots
Notice that no lines of code are highlighted upon toggling between executable statements; the pink wavy lines are to blur potentially sensitive info. 
![screen shot 2017-08-03 at 1 42 10 pm](https://user-images.githubusercontent.com/12104721/28942948-ec8c3c6a-7851-11e7-9e91-21cf2d609ed0.png)

#### DataGrip
DataGrip 2017.2
Build #DB-172.3544.109, built on July 26, 2017
Licensed to LendUp / Vishrut Arya
Subscription is active until March 1, 2018
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
#### Material Theme
Version: 0.7.2

**Comment by mallowigi** [comment]
should be supported
