### ISSUE TITLE
Material them applied to the UI components but not my code

### ISSUE THREAD

**Issue by JayJayM** [ChrisRM/material-theme-jetbrains#405]
### Summary
I set up the Material theme, it applied to all IntelliJ components my code is still in the Darcula theme.
### Expected behavior
The theme should be applied to the code too, right?
### Actual behavior
I set up the Material theme, it applied to all IntelliJ components my code is still in the Darcula theme.

### Steps to reproduce (if needed)

![image](https://user-images.githubusercontent.com/8995276/28984495-34fd51fc-792c-11e7-8e66-f1eb7c621cbd.png)

### Environment

![image](https://user-images.githubusercontent.com/8995276/28984510-48d2e3cc-792c-11e7-8c06-82754124733d.png)

Maybe I'm doing something wrong, but I can't find what.
Thank you!

**Comment by mallowigi** [comment]
Options > Appearance > Color Schemes > Material Theme

**Comment by JayJayM** [comment]
thank you @mallowigi !
