### ISSUE TITLE
Sidebar element height (spacing between elements)

### ISSUE THREAD

**Issue by Edvinas01** [ChrisRM/material-theme-jetbrains#406]
At the moment there is an ability to change tab height. It would also be nice to have such feature for sidebar elements. Currently similar functionality is possible by enabling `Compact Statusbar` via material theme settings, but its a bit too extreme.

Image explanation:
![image](https://user-images.githubusercontent.com/8227320/29107971-7822b00a-7ce5-11e7-91dd-7ea5b063e9f0.png)

**Comment by mallowigi** [comment]
I've added the customization on v0.9.2
