### ISSUE TITLE
Option to disable uppercase tabs doesn't stick after restart

### ISSUE THREAD

**Issue by phoikoi** [ChrisRM/material-theme-jetbrains#407]
### Summary
The option in the theme preferences to disable the uppercase tab titles works only until restart.

### Expected behavior
After choosing the option in Preferences to disable the uppercase bold tabs, tab titles should remain lowercase, normal weight after restart of PyCharm

### Actual behavior
Unwanted uppercase bold tab titles return after restart of PyCharm.

### Steps to reproduce (if needed)

1. Disable uppercase bold tabs in Preferences -> Appearance -> Material Theme
2. Observe tabs have changed back to lowercase; restart PyCharm.
3. Observe tabs have returned to uppercase bold.

### Environment

PyCharm 2017.2
Build #PY-172.3317.103, built on July 25, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
Material Theme (EAP) plugin version 0.9.0

Note: I have also seen this same behavior on PyCharm running under Debian Linux x86-64.

**Comment by cesards** [comment]
I think it should be disabled by default :-/ I thought it was a bug.

**Comment by mallowigi** [comment]
Not on this repo yet

**Comment by dashmug** [comment]
I also get this bug on WebStorm 2017.2.1.

I also vote for this being disabled by default.

**Comment by salmansamie** [comment]
I have the same issue here. It's an eyesore. I vote for disabling it by default as well.

My Version:
PyCharm 2017.2.1
Build #PY-172.3544.46, built on August 9, 2017
Licensed to Salman Rahman
Subscription is active until August 31, 2021
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
