### ISSUE TITLE
Lighter Theme  are not working

### ISSUE THREAD

**Issue by larsroettig** [ChrisRM/material-theme-jetbrains#408]
If I change the change color theme in Editor > Color Theme to  the Lighter Theme most parts stay in the darker theme. 

How can i fixit ?

![phpstorm](https://user-images.githubusercontent.com/5289370/29363914-001b9920-8292-11e7-98ff-42656f17eabc.jpg)

**Comment by mallowigi** [comment]
Material Themes are not compatible with the IntelliJ (Default) Look and Feel, because they override the Darcula LAF.

I'm currently working on making the Lighter theme override the IntelliJ LAF but be aware that currently it is overriding the Darcula LAF, even though it is not a dark theme.
