### ISSUE TITLE
Can you small fontsize and line height?

### ISSUE THREAD

**Issue by stojankukrika** [ChrisRM/material-theme-jetbrains#41]
Here is like in default theme:
http://view.xscreenshot.com/50cfbd72a393d1f8986360b09853ab97
and how look like in material theme:
http://view.xscreenshot.com/dea03829b1a3fe9fdf5bf0476b335786
Can you change a font size and line space because a in default theme in same screen fit more lines of code?

**Comment by ChrisRM** [comment]
I set the default font size(12) and line height(1.0) in the newest build, https://github.com/ChrisRM/material-theme-jetbrains/commit/6a919cdcdc5b1960f4c54de3582556789a481e69.

If you want to modify the font, open `Preferences` -> `Editor` -> `Colors & Fonts` -> Now, next to `Schemes` hit `Save as...`. Hit enter, now you can change the font size and line height.

**Comment by soee** [comment]
I moved back to old settings. Maybe becuse i'm working on laptop 17" 1920x1080, previous settings for fonts were just perfect. Now default settings makes all to small :)

**Comment by ChrisRM** [comment]
Thankfully, it's pretty easy for users to customize it. I'll add a section for that in the README.

**Comment by stojankukrika** [comment]
THX. Now I see that use old version. Download a new version and now is perfect! TNX.

**Comment by SheinH** [comment]
@ChrisRM 
Hi, is there a way to also lower the line height on the rest of the UI like the sidebar?

**Comment by mallowigi** [comment]
no
