### ISSUE TITLE
Scroll to source and folder navigation no longer working

### ISSUE THREAD

**Issue by jkudish** [ChrisRM/material-theme-jetbrains#410]
### Summary

The scroll to source button in the sidebar as well as folder navigation are no longer working after upgrading to PhpStorm 2017.2.1.

I initially thought this was a problem in PhpStorm itself, but it seems to be the combination of 2017.2.1 and Material Theme UI. If I disable Material Theme UI plugin, then the button and folder navigation work as expected.

### Expected behavior

The scroll to source button and folder navigation should work.

### Actual behavior

Screenshots taken with Material Theme disabled, when it does work.

This button:

![image](https://user-images.githubusercontent.com/260253/29392368-4fe1385a-82b2-11e7-8d44-af7dcbbec479.png)

And this way of navigating to a folder:

![image](https://user-images.githubusercontent.com/260253/29392409-87c2f6fa-82b2-11e7-8617-65f7bb98d4f3.png)

Do absolutely nothing when Material Theme UI is enabled

### Steps to reproduce (if needed)

1. Enable Material Theme UI
2. Restart
3. Attempt the actions above

### Environment

PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
maybe related to the clusterfuck of version 0.9.0

Please update and tell me if it happens.

**Comment by jkudish** [comment]
How do I upgrade? I only see v0.5.0 available:

![image](https://user-images.githubusercontent.com/260253/29536688-a3579d0c-8673-11e7-875e-ca660e0ea479.png)

**Comment by mallowigi** [comment]
Download the EAP

**Comment by jkudish** [comment]
I don't feel like running beta PHPStorm just to get Material Theme to work, to be honest; might bring other issues. It's fine, I'll use the default darcula for now and try this again when there's an update.

I appreciate the help and quick responses anyway!

**Comment by mallowigi** [comment]
I wasn't talking about updating PhpStorm but only the material theme plugin. The 0.8.2 version should be available and it should work without issues

**Comment by jkudish** [comment]
Didn't realize there was a separate EAP just for the plugin.

I'll grab the latest and get it going again; thanks!
