### ISSUE TITLE
Debug phone button image toggle is backwards

### ISSUE THREAD

**Issue by litzinger** [ChrisRM/material-theme-jetbrains#411]
I recently upgraded to PHPStorm 2017.2, and thus updated the Material them to the latest version. I'm pretty sure the custom image used to indicate if the phone is on or off for debugging is backwards. I lost several hours of my life to trying to figure out why PHPStorm was not picking up xdebug connections even though the phone icon was green (indicating that it is listening for requests), but PHPStorm never saw the requests, however, when I clicked the phone button again to make it red, it magically started picking up requests. I took this as something was wrong with my settings in xdebug.ini, or possibly port forwarding, or something else is jacked with my vagrant machine. After spending nearly 5 hours on this I decided to uninstall the Material theme, and low and behold, PHPStorm correctly picked up on xdebug requests when the phone was green, and did not when the phone was red, which is the exact opposite of what happens when the Material theme is installed.

Either I'm losing my mind, or the custom icons used in the Material theme are backwards for this button.

Environment:
PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

**Comment by GeeH** [comment]
Could not reproduce here after fresh install of PhpStorm 2017.2 and Material Theme UI I see the Red "paused" debug button by default, when I start listening for connections I see the green button as expected. 

I'd be interested to see if this is a bug in PhpStorm or the plugin that got confused - if anyone reproduces this please let me know.

**Comment by litzinger** [comment]
Interesting. It definitely was backwards for me, and as soon as I uninstalled the theme it was correct. I'll try the theme again and take another look though.

**Comment by litzinger** [comment]
I just did another test and can confirm that when the theme is installed (I tried the EAP version this time) that Xdebug only picks up when the phone icon is red. When the icon is green, it does not accept incoming requests.

**Comment by GeeH** [comment]
@litzinger - does the icon start as red and listening, or start as green and not listening please?

**Comment by mallowigi** [comment]
The green icon means that AFTER PRESSING IT it starts listening xdebug connections (hence the tooltip "Start listening to XDEbug connections).

The red icon means that AFTER PRESSING IT it stops listening xdebug connection.

Try to think of an on/off switch (which it is, as a matter of fact).

**Comment by litzinger** [comment]
Thats inconsistent with the default icon though, which has a red circle with a line through it indicating that it is off/not listening. Clicking it makes it green. What you're describing is the exact opposite, and not very intuitive. Green is better representative, and frankly a universal indication of an on/active state.

**Comment by mallowigi** [comment]
Because this is not a toggle button. This is an action button that, when pressed, toggle the listening state. So pressing while it's green will start listening, and pressing while it's red will stop listening. Like a regular phone button.

IMO the designers at jetbrains didn't use a very good icon. At least they could have made a toggle button like other toggles in the ide

**Comment by litzinger** [comment]
I'm so confused. You said its not a toggle button, then immediately after said "when pressed, toggle the listening state".

The theme is just a visual override of the default visuals, it shouldn't change the default behavior, but this change does. Its not up to a theme designer to re-interpret what the functionality should be. I'm sorry if I'm coming off as stubborn on this, but I'm certain the visual state this theme indicates is absolutely incorrect.

**Comment by litzinger** [comment]
[Default theme off/Not listening state](https://www.dropbox.com/s/qlzvxctdyienkz9/debug-off.png?dl=0)

[Default theme on/listening state](https://www.dropbox.com/s/x3johf3h8273ovs/debug-listening.png?dl=0)

Your theme literally does the exact opposite of this... effectively changing the IDE behavior. I've been using PHPStorm for years, and after using your theme I was immediately thrown off by the visual change, so much so that I wasted over 4 hours debugging my server b/c I thought I was listening for a connection when the icon was green, just like the default theme.

**Comment by mallowigi** [comment]
Welp, I don't like it. But since it is confusing users apparently, I'd rather use the original behavior instead of reeducating users...

Gonna change it for next version.

**Comment by LordZardeck** [comment]
So I just came across the result of this conversation I think, showing a red icon when off and a green one when on. I recently lost lots of hours over this issue as well after the update. I can adjust, but I would ask if its going to be a state icon, can we change the red icon to remove the pause button? That doesn't make any sense and is confusing. The pause button makes me think it's running and I can stop it.

**Comment by LordZardeck** [comment]
> The green icon means that AFTER PRESSING IT it starts listening xdebug connections (hence the tooltip "Start listening to XDEbug connections).
>
>The red icon means that AFTER PRESSING IT it stops listening xdebug connection.
>
>Try to think of an on/off switch (which it is, as a matter of fact).

This honestly makes more sense

**Comment by litzinger** [comment]
I don't have any skin in the game anymore b/c I uninstalled this theme and went back to the default, however, I've shown this to a couple of co-workers who are UI nuts and they agree that the current implementation is very confusing. The fact of the matter is that this theme 100% diverges from the default behavior/theme of PhpStorm. So to me that is incorrect. Its equivalent to theming your website scrollbar to click the up button to scroll down, and down button to scroll up. Your users are are going to get very confused. A few years ago OS X inverted the scroll behavior when using the touch pad and made it default for everyone, but they did it b/c it was change to the operating system, not a theme, and they gave users the option of reverting to the old scroll design. If PhpStorm chooses invert the icon display, then by all means change the theme to match. But you're changing the theme just because you personally feel like the originating software got it wrong and forcing this behavior on your users.

**Comment by autaut03** [comment]
Hey there. First of all, thank you for your work, I really like your theme. Secondly, I'm sorry to comment on such an old issue, but this icon honestly drives me crazy. My imho: it's a button, not an indicator. It does the action, not reflects current state. Icon of any button should represent the same action as in the tooltip, which isn't what it's like right now. 

Say "Run" button - it's green when nothing is running, and red when clicked. How is the XDebug button different from it? Why isn't it consistent?

**Comment by mallowigi** [comment]
I’m not getting back to this old issue right now. Should the default xDebug changes to reflect the action button purpose, not the current state, I’ll change it again. You’re free to open an issue at Jetbrains.
