### ISSUE TITLE
Uppercase in tabs setting not being saved

### ISSUE THREAD

**Issue by sidner** [ChrisRM/material-theme-jetbrains#412]
### Summary
When changing "Toggle uppercase tabs" from active to not active, when I close the IDE and reopen it, the tabs are again in uppercase and the option is active. The setting is not being saved between "sessions".
...

### Expected behavior
When I reopen IntelliJ, I want the tabs to not be in uppercase.
...

### Actual behavior
Tabs are back in uppercase when I reopen IntelliJ
...

### Steps to reproduce

1. First step
Untick "Toggle uppercase tabs" option
2. Second step
Close IntelliJ
3. Third step
Re-Open IntelliJ and see that tabs are back in uppercase.

### Environment

IntelliJ IDEA 2017.2.3 EAP
Build #IU-172.3968.1, built on August 15, 2017
Licensed to EAP Member
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.19.0-32-generic

**Comment by BloodShura** [comment]
This happens actually worse to me: ALL plugin's settings (selected theme, etc) are reset when re-opening the IDE...

**Comment by mallowigi** [comment]
ok please try now

**Comment by sidner** [comment]
Seems like it's working properly again. Thank you for the fast fix.

**Comment by BloodShura** [comment]
While uppercase tabs seem to be saved correctly, other settings like selected theme, compact status bar, and project view decorators are still being re-set. (I'm on IDEA 2017.2.2, plugin version 0.9.1)

**Comment by mallowigi** [comment]
Yep there is something that causes the settings to get resetted to defaults... Investigating.

**Comment by mallowigi** [comment]
should be fixed now.

**Comment by Arthurin** [comment]
Hello,
I tried the uppercase format and didn't like it so I unchecked the box and saved my changes, but now it keeps displaying uppercase titles. In my case the setting is saved, I tried to check/uncheck and relaunch IDE a couple of time without success.

**Comment by mallowigi** [comment]
Which version are you on?

**Comment by Arthurin** [comment]
Nevermind it is working fine today, either a restart fixed it (I installed webstorm 2019.1, last version of material and tried other themes too the same day) or I dreamed it was a bug while checking the wrong box ^^ 
Have a good day
