### ISSUE TITLE
"Material File Colors" modifications only affecting non-Project files

### ISSUE THREAD

**Issue by FerusGrim** [ChrisRM/material-theme-jetbrains#413]
### Summary
In the 0.8.0 update, the ability to modify File Status Colors was added, in part thanks to the complaint(s) from #400. 

In this update, however, for whatever reason, it appears as though only files which aren't Project files are being updated.

![Example Image](http://i.imgur.com/6iX8zef.png)
...

### Expected behavior

I would expect, in this case, for all files to be affected by the setting.

...

### Actual behavior

As listed above, only non-project files are affected.
...

### Environment

IntelliJ IDEA 2017.2.2
Build #IU-172.3757.52, built on August 15, 2017
Licensed to FerusTech LLC / Nicholas Badger
Subscription is active until October 9, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
yep there was an issue with PsiNodes, e.g. files which are represented according to their types (class, interface...)

It is fixed in 0.9.2

**Comment by FerusGrim** [comment]
It is, indeed!

![Image Example](http://i.imgur.com/u3GpVlz.png)

I just noticed the update. Thank you, very much!

**Comment by FerusGrim** [comment]
Whoops - sorry to re-open this, but...

![Image](http://i.imgur.com/vK9bJql.png)

Is there a setting that affects the folder, as well? It seems to stick to the default color, no matter which type of content it holds.

**Comment by mallowigi** [comment]
It only affects the files, not the folders. Therefore the folder colors are not changeable and have either the bluish color or the accent color if there is an opened file

--
Elior
