### ISSUE TITLE
Update the released version in IntelliJ Repository Plugin

### ISSUE THREAD

**Issue by ronaldsuwandi** [ChrisRM/material-theme-jetbrains#415]
Currently the latest version in the IntelliJ Repository Plugin is still 0.5.0 https://plugins.jetbrains.com/plugin/8006-material-theme-ui

Any plan to release the newer ones there (not EAP version)?

**Comment by mallowigi** [comment]
Currently there are very important issues in the version 0.9.0, but I'm not the owner of the original repository so I need to wait for the owner to update it.

**Comment by ChrisRM** [comment]
0.8.2 is the latest release, updated now. Should be available in the IDE asap
