### ISSUE TITLE
Refactor dark text on dark background

### ISSUE THREAD

**Issue by dstodev** [ChrisRM/material-theme-jetbrains#417]
### Summary

Refactoring code has dark text on a dark background, making it difficult to read.

### Expected behavior

Refactoring has white text on a dark background.

### Actual behavior

Refactoring has black text on a dark background.

### Steps to reproduce

Note that not every step may be necessary, but this is how I set things up, not necessarily in order:

1. Material theme installed with Contrast mode enabled, accent "Tomato", and Darker theme set.
2. Change the color scheme to "Github". (Mine is slightly modified, but it just matters that this is a light color scheme). Do not change the whole IDE to a light theme if asks.
3. Note that this setup has a dark outer theme, with a light inner theme.
4. Try to refactor something, and notice that the text color is black, on a dark background.

This can be seen here: ![screenshot](https://user-images.githubusercontent.com/31356674/29730228-345f6ac8-8994-11e7-83c1-d827e1ffb269.png)

### Environment

PyCharm Community Edition 2017.2.2
Build #PC-172.3757.67, built on August 21, 2017
JRE: 1.8.0_152-release-915-b10 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version 0.8.2

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/343
