### ISSUE TITLE
Black border between sidebar and editor

### ISSUE THREAD

**Issue by LeGfrey** [ChrisRM/material-theme-jetbrains#418]
### Summary

Hi guys, first thank you for your awesome works !
I'm encountering an issue with sidebar on Webstorm (latest version).
I have a black border between my editor and my sidebar (when sidebar is active).
This is not very beautiful 😅 

### Expected behavior

No black border between editor and sidebar

### Actual behavior
![capture d ecran 2017-08-27 a 16 35 40](https://user-images.githubusercontent.com/11151445/29750773-3b7ea70c-8b46-11e7-9e05-75aacadb8b89.png)
Black border between editor and sidebar (cf screenshot attached)

### Environment
WebStorm 2017.2.2
Build #WS-172.3757.55, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3

**Comment by mallowigi** [comment]
I know about this, and this is not something I can fix right now.  What I want to do if I find a fix is to put a border shadow instead.

Will keep you posted

**Comment by LeGfrey** [comment]
Thank you for your fast answer ! You rocks 👍 

This is not so important as your theme is already very very good. But border shadow is an awesome idea.

Anyway thanks a lot for your work. ❤️

**Comment by blimey85** [comment]
I actually really like the border there. It does a nice job of differentiating between the two areas. If this gets changed can there be an option in settings to stay with the existing behavior?

**Comment by mallowigi** [comment]
I won't remove this separator, but instead replace with something with shadow if possible (though I'm very skeptical because it can consume up CPU...)
