### ISSUE TITLE
Inactive tab color should be darker

### ISSUE THREAD

**Issue by soee** [ChrisRM/material-theme-jetbrains#42]
Hi, 

first of all thank you for great theme. I'm working on default one and my small suggestion is to change a bit font for inactive tabs - make it darker so the active tab would be more visible. Now all inactive tabs get more attntion than the active one because of the background color and font color combination.

**Comment by ChrisRM** [comment]
As of now, that's not possible without a decent amount of hacking. Please add your votes to this thread on the JetBrains issue board: https://youtrack.jetbrains.com/issue/IDEA-146255

**Comment by b3zman41** [comment]
Close the issue?

**Comment by ChrisRM** [comment]
Hold on, I think I know how to fix this. I'll look at it later today

**Comment by soee** [comment]
Cool. Thank you @ChrisRM :)

**Comment by ChrisRM** [comment]
Just added a bottom border to the active tab. https://github.com/ChrisRM/material-theme-jetbrains/commit/e8eaaa0d29709e009b629370fd31300d20202797
