### ISSUE TITLE
Colours in Project view and database view are too dim

### ISSUE THREAD

**Issue by un000** [ChrisRM/material-theme-jetbrains#420]
### Summary
After last update I got too dim colours in every list view
![image](https://user-images.githubusercontent.com/19488486/29754398-cf90e93c-8b8c-11e7-853f-eb07cce45b3a.png)

![image](https://user-images.githubusercontent.com/19488486/29754403-e953f97c-8b8c-11e7-8f0f-0447b968c335.png)

### Expected behavior

More contrast colors

### Steps to reproduce (if needed)

1. Updated to 0.8.00

### Environment
```
PhpStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

Please fix it or tell me please where can I change that settings especially for DB View.
Thank You!

**Comment by mallowigi** [comment]
I'm going to release a feature allowing you to customize everything (almost...) in a few days. In the meantime I'd suggest you to change the background color to something more accustomed to the violet text

**Comment by mallowigi** [comment]
I've released the custom theme support beta in the EAP. Please take a look and report if anything is amiss.

**Comment by un000** [comment]
@mallowigi 

Sorry if I'm asking again, so how can I change the foreground color for `Database` Tool Window?
I have the bunch of perfect options to setup File Colors (Material File Colors) except Database.

**Comment by mallowigi** [comment]
The only way is to use a custom theme where you change the colors yourself.
