### ISSUE TITLE
Project pane icons appear low-res on 4k monitors

### ISSUE THREAD

**Issue by fractallian** [ChrisRM/material-theme-jetbrains#421]
In the latest update the icons look pretty bad (I'm using a 4k monitor) aside from the close-drawer icon. All other icons are fine though so it must be an issue with these particular icons.

<img width="108" alt="screen shot 2017-08-28 at 2 37 46 pm" src="https://user-images.githubusercontent.com/265980/29794845-9e1c0806-8bfe-11e7-9e6c-8138e05dc93c.png">

**Comment by mallowigi** [comment]
I know, this is fixed in version 0.9
