### ISSUE TITLE
HiDPI Icons

### ISSUE THREAD

**Issue by bjoernmayer** [ChrisRM/material-theme-jetbrains#422]
Hi,

some of the last added icons are missing HiDPI/Retina versions. Any chance that you add them in one of the upcoming versions?

See screenshots attached:

<img width="138" alt="screen shot 2017-08-29 at 10 26 44" src="https://user-images.githubusercontent.com/20116376/29812004-91a216c2-8ca5-11e7-827b-fd55c699010d.png">
<img width="64" alt="screen shot 2017-08-29 at 10 29 28" src="https://user-images.githubusercontent.com/20116376/29812003-91a17532-8ca5-11e7-846c-7e28ced247b2.png">

Thanks!

**Comment by mallowigi** [comment]
It's fixed in version 0.9.0. I will release the version as soon as I patch all critical bugs in it.

**Comment by bjoernmayer** [comment]
And now I see the other issues about that topic. Sorry!
