### ISSUE TITLE
Show keyboard shortcut underlines

### ISSUE THREAD

**Issue by LordZardeck** [ChrisRM/material-theme-jetbrains#423]
One of the reasons JetBrains is so powerful is it's extremely complete keyboard navigation. It's sometimes hard to remember all the shortcuts and navigation options. Just like many other apps, default JetBrains underlines the letters in their dialogs that tell you what you can use as a shortcut. For example, Alt+I on the commit dialog for the commit button.

This theme, however, doesn't display that underline, making it difficult to remember what the shortcuts are. Would it be possible to add underlines back?

Default: 
![](http://take.ms/mh3Gn)

Material Theme:
![](http://take.ms/q1jI0)

**Comment by blimey85** [comment]
Can you check that you have mnemonics turned on in settings? I believe there's two places to enable/disable this. Just want to make sure you have them both on already.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/29858924-5e3af646-8d68-11e7-8bff-0ae042542180.png)

**Comment by mallowigi** [comment]
You see that there are here, just not on the buttons (and they are not here if i disable the theme as well)

Maybe there's a setting for that, haven't found it.
