### ISSUE TITLE
Incompatible with PhpStorm 2016.2.2

### ISSUE THREAD

**Issue by dsentker** [ChrisRM/material-theme-jetbrains#425]
This plugin seems incomaptible with PhpStorm 2016.2.2  Build 162.

### Actual behavior
If i load the plugin from disk, an alert shows that this plugin is incompatible.  I've tried 0.2.1 as well as 0.2.2 .

### Environment
PhpStorm 2016.2.2
Build #PS-162.2380.11, built on October 24, 2016
JRE: 1.8.0_112-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by mallowigi** [comment]
Download Material Theme UI EAP
