### ISSUE TITLE
[Suggestion] Update colors of files ignored by git

### ISSUE THREAD

**Issue by Thomas-X** [ChrisRM/material-theme-jetbrains#426]
Currently, the gitignore color is grey, together with a dark background this seems like the worst possible decision to make when you're going for readability. There should be a better contrast for this.
![h2kshgakvq](https://user-images.githubusercontent.com/21952645/29878736-9b2b1910-8da3-11e7-87c6-5007478e92db.png)

**Comment by mallowigi** [comment]
Does nobody of you ever read the README?

**Comment by mallowigi** [comment]
My apologies for the last comment. It's just that sometimes it's a pain to repeat the same things over and over.

Anyway in the README there is a section about explaining how you can change the file colors  in the Color Scheme settings. That should fix your issues about ignored files and even regular files.
