### ISSUE TITLE
[Suggestion] A solid way to change icons 

### ISSUE THREAD

**Issue by Thomas-X** [ChrisRM/material-theme-jetbrains#427]
Since there recently was a feature implemented that give you somewhat of a functionality to disable material icons or enable it and whatnot. Why is there not the ability the change icons and basic color names of i.e files ignored by git? 

**My take on the solution:**
Update the doc for development to include basic stuff like editing the build.gradle to not give errors on first run / compilation. 

Other issues are getting shot down with the argument that this theme is opinionated, but at least give some solid documentation for development to back that argument up.

**Comment by mallowigi** [comment]
First of all, I'm updating the README at every opportunity possible to update about the changes introduced in each release. I know a README is not the best place of all (I will maybe create a github pages at some time, if I'm not lazy) but you should keep an eye on it in every new release (or do a git diff to see what has changed).

As for the icons, currently there is no way to change it. I'm following the a-file-icon repository for it and follow them closely for their icons, but I also take some liberty of changing the icons if deemed necessary. The only option you have would be to change the icons yourself by forking the project and overriding the bundled icons with your own.

Finally yeah, I can understand that some of you are unhappy with some of the features added by this theme, and for this usually I give enough customization for everyone to have his own settings, but I cannot please everyone, and for some of my decisions you just have to stick with it, or fork the project and tweak whatever you want to.

The README gives enough information on how to build the project locally. Recently I got helped (finally) by someone who didn't even know Java and managed to build the project locally, so it shouldn't be that hard.

To conclude: I have a lot of things to do, and I'm currently fixing all issues and try to implement the 0.10 version, so any help is appreciated. If you want to contribute and build a documentation, you're more than welcome.
