### ISSUE TITLE
Formatting file results in document shift

### ISSUE THREAD

**Issue by luveti** [ChrisRM/material-theme-jetbrains#429]
### Summary

Running "Code->Reformat Code" results in tab width being increased, and the right margin of the document moving.

### Expected behavior

I would expect the document tab widths and right margin to be correct when the file is opened.

### Actual behavior

Things are shifted upon running "Code->Reformat Code".

### Steps to reproduce (if needed)

1. Create a blank file, a javascript file in my case
2. Write some code
3. Run "Code->Reformat Code"

![2017-09-04_12-40-56](https://user-images.githubusercontent.com/4952718/30034464-a66499c6-916f-11e7-9ae4-515fee6cfffc.gif)

### Environment

WebStorm 2017.2.3
Build #WS-172.3968.27, built on August 29, 2017
Licensed to Cameron Kline
Subscription is active until January 3, 2018
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
Never heard of that. Could you provide me the list of plugins you use?

**Comment by luveti** [comment]
Here's a list of my active plugins:

.ignore (2.1.1)
CSS Support (172.3968.27)
EditorConfig (172.3968.27)
File Watchers (172.3968.27)
Git Integration (8.1)
JavaScript Debugger (1.0)
JavaScript Support (1.0)
Lines Sorter (1.0.1)
Markdown support (2017.2.20170419)
Material Theme UI (0.8.2)
NodeJS (172.3968.27)
Sass support (172.3968.27)
Settings Repository (172.3968.27)
Terminal (0.1)
Vue.js (172.3968.27)

**Comment by luveti** [comment]
I just want to point out that I use tabs instead of spaces in my code. It appears the majority of this plugin uses spaces instead of tabs. Have you done much testing with tabs?

**Comment by mallowigi** [comment]
I can't reporduce, and in any case the plugin doesn't mess with tabs at all...

Does somebody have the same problem?
