### ISSUE TITLE
IDE Fatal Errors - Webstorm

### ISSUE THREAD

**Issue by jasonhodges** [ChrisRM/material-theme-jetbrains#430]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
When trying to access the Material Theme settings under Appearance in Preferences, the settings pane continues displaying a loading indicator and Webstorm reports IDE Fatal Error 
...

### Expected behavior
Should be able to access the settings pane
...

### Actual behavior
Unable to access the settings pane
...

### Steps to reproduce (if needed)

1. First step
2. Second step
3. Third step

You can also add Screenshots for a better understanding.
![screen shot 2017-09-06 at 10 19 55 am](https://user-images.githubusercontent.com/1988476/30122983-b584954e-92ed-11e7-9505-804cdbcf20c3.png)
![screen shot 2017-09-06 at 10 20 36 am](https://user-images.githubusercontent.com/1988476/30122991-bb15c51e-92ed-11e7-889e-b52359789535.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* If needed a list of enabled plugins

WebStorm 2017.2.3
Build #WS-172.3968.27, built on August 29, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
Which plugin version ? Try to install the latest update (10.3)

**Comment by jasonhodges** [comment]
@mallowigi I had installed the regular Material Theme UI, not EAP. Should I remove the UI version and only install EAP? Thanks

**Comment by mallowigi** [comment]
Yes

**Comment by jasonhodges** [comment]
Thanks for the help @mallowigi
