### ISSUE TITLE
PyCharm: File and Folder Names Hidden in "Scratches" View

### ISSUE THREAD

**Issue by chukkwagon** [ChrisRM/material-theme-jetbrains#438]
### Summary

File and Folder names are hidden under the "Scratches" view in PyCharm

### Expected behavior

I expect to be able to see the file and folder names

### Actual behavior

![image](https://user-images.githubusercontent.com/8526206/30387894-a09a3f9a-9873-11e7-9027-39f3a6efda9d.png)

### Steps to reproduce (if needed)

1. Open PyCharm Project
2. Open Project View (ALT + 1)
3. Switch to "Scratches" view

![image](https://user-images.githubusercontent.com/8526206/30387990-e99c620e-9873-11e7-9a10-31e36998469c.png)

### Environment

PyCharm 2017.2.3
Build #PY-172.3968.37, built on September 1, 2017
Licensed to AlertMedia / Charlie McBride
Subscription is active until May 2, 2018
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-33-generic

**Comment by mallowigi** [comment]
I changed the color to the "disabled" color.

**Comment by chukkwagon** [comment]
@mallowigi i don't understand how that resolves my issue. I am still seeing the issue and I have the latest version of PyCharm and your plugin.

**Comment by mallowigi** [comment]
Do you have a custom color scheme or a modified version of the ones bundled?

**Comment by chukkwagon** [comment]
no i'm using the out of the box configuration for material theme. I haven't changed anything.

**Comment by philipbulley** [comment]
I have the same problem. I can only see the highlighted file.

![image](https://user-images.githubusercontent.com/309607/31337410-27db795e-acf3-11e7-854a-20f463eec434.png)

Material Theme UI 0.10.4

WebStorm 2017.2.4
Build #WS-172.4155.35, built on September 11, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
This has been fixed in the latest builds
