### ISSUE TITLE
Darker Theme default colors incorrect

### ISSUE THREAD

**Issue by robertfreund** [ChrisRM/material-theme-jetbrains#439]
It seems with latest version of Material Theme 'Darker' the default text color has changed to some dark grey color. Is this expected and how can one change it back to the previous white color that was used?
Material Theme UI EAP 0.10.3 (tried changing it back with custom theme but had other issues)
IntelliJ 2017.2.3
NOTE: notice how dark all the items are in the project explorer. 
<img width="369" alt="screen shot 2017-09-13 at 12 46 45 pm" src="https://user-images.githubusercontent.com/10730956/30389724-b1d540bc-9881-11e7-86f1-bd7c0615feee.png">

See Previous Here:
IntelliJ 2017.0.2
Material Theme UI 0.6.0.1

NOTE: notice how the items are much closer to white.

<img width="258" alt="prev" src="https://user-images.githubusercontent.com/10730956/30390069-e0855d06-9882-11e7-991d-0fa9fd7d4c73.png">

**Comment by ljurgs** [comment]
I also have this issue and I find the theme much more difficult to work with now. If someone could tell me how to revert to the old colour scheme I would be very grateful.

**Comment by mallowigi** [comment]
Settings > Color Scheme > Material File Colors > Up To Date

**Comment by robertfreund** [comment]
This solution works for files but has no affect on directories. Is there a subsequent setting for directories as well?

**Comment by mallowigi** [comment]
Nope not for directories . There is still the accent color for directories with opened files in it.

But give it a chance, you will get use to it quickly

**Comment by mallowigi** [comment]
I forgot that I added the option for custom themes! You can change it in your custom theme by changing the "Label text" color
