### ISSUE TITLE
Malformed text in certain sections in the IDE.

### ISSUE THREAD

**Issue by LEO318x** [ChrisRM/material-theme-jetbrains#442]
### Summary

When apply the plugin and restart the IDE, the config, buttons and others sections the text is malformed.

### Expected behavior

Texts in certain sections should be displayed correctly.

### Actual behavior

![](https://i.imgur.com/ONsYZbw.png)

### Steps to reproduce (if needed)

1. Install the Plugin
2. Restart the IDE
3. Enjoy!

### Environment

IntelliJ IDEA 2017.2.4
Build #IU-172.4155.36, built on September 11, 2017
Licensed to Mike Molina
Subscription is active until May 30, 2018
For educational use only.
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
This issue with Roboto again... I don't know what is causing this, but try to reinstall the Roboto don't from Google fonts, or replace the font with something else under Appearance > Override custom fonts 

I wish I could reproduce this so I can address this issue or at least write it in the known issues section

**Comment by LEO318x** [comment]
Reinstalling the font (Roboto) fixed the problem.

*Additional Info: The problem returns when Intellij IDEA is updated to another version. (In my case)
