### ISSUE TITLE
Material Theme Scheme Copy Not Saving

### ISSUE THREAD

**Issue by jabacchetta** [ChrisRM/material-theme-jetbrains#443]
### Summary

Creating a copy of the scheme (as suggested in the docs) does not consistently stay active.

### Expected behavior

When creating a copy of the material theme color scheme and setting that copy as the editor scheme, it should stay set as the scheme of choice.

### Actual behavior

The color scheme is constantly being reset to Material Theme Default.

### Steps to reproduce

1. Preferences > Editor > Color Scheme
2. Create a duplicate of Material Theme Default. Give the copy a unique name, save it, and then apply the changes.
3. From here, you can either close WebStorm and reopen it OR you can go to Appearance & Behavior > Material Theme and make changes to those settings. Either one of these actions will reset the color scheme from your custom version of material theme to the default version.

### Environment
Material Theme UI Version 0.10.4
WebStorm 2017.2.4
Build #WS-172.4155.35, built on September 11, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by mallowigi** [comment]
I finally found the issue. It happens since the passing in 2017.3 EAP

It will be fixed in the latest EAP (0.11.1)
