### ISSUE TITLE
Beta Testing

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#446]
Hi people,

A lot of issues surfaced lately, related to color schemes, remote hosts and whatnot.

I want to close this version and release a new tag so please download the EAP and beta-test with it and tell me for every issue you find.

Thanks

**Comment by DarklordMogrithe** [comment]
I don't see the customization menu anymore (the one added by the plugin as a top-level settings tab). Not sure if it was intentionally removed or not. Other than that, my issue is fixed and everything else seems to be working just fine. Good work!

**Comment by mallowigi** [comment]
What do you mean?

**Comment by DarklordMogrithe** [comment]
I remember there being a "Custom Material UI" tab (or similar) in the settings menu. I think it was between Keymap and Editor. I never used it so I can't describe it much better.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/30629215-56596756-9de3-11e7-8baf-f706650d47a5.png)

**Comment by hoof** [comment]
Thanks for making the greatest theme ever for IntelliJ! It's been a pleasure all the way. But today - new laptop.....

Installed latetst intellij and plugged in the EAP. The LAF is updated but editor windows is still "normal" Darcula: 
![image](https://user-images.githubusercontent.com/427736/30663583-66ed252c-9e4b-11e7-882d-bd8c0edd07e6.png)
And is it me, or does the UI look a bit funky around where the "sidebars" meet the middle part?

**Comment by mallowigi** [comment]
This screenshot was made during the version 0.5.0, and this was how the tool window headers looked at the time. It changed since then but it still retained the colors used at the time, e.g. what you see in the screenshots is what color the tool window headers have when they are in focus.

As for the black line, it happens only on Mac, not on Windows.

**Comment by DarklordMogrithe** [comment]
Whoops, looks like I'm blind. Didn't check in Appearance & Behavior.
