### ISSUE TITLE
PHPStorm IDE Fatal Error

### ISSUE THREAD

**Issue by matt-bailey** [ChrisRM/material-theme-jetbrains#449]
It seems that Material Theme UI is causing an IDE Fatal Error when I try and open Preferences. Here are the details.

![screen shot 2017-09-27 at 14 56 37](https://user-images.githubusercontent.com/969385/30917591-47c1bdcc-a394-11e7-9aad-b960a0088881.png)

![screen shot 2017-09-27 at 14 56 15](https://user-images.githubusercontent.com/969385/30917600-4d84cf10-a394-11e7-9e79-3d1c80c2ffbe.png)

![screen shot 2017-09-27 at 14 56 26](https://user-images.githubusercontent.com/969385/30917608-51fa6654-a394-11e7-9cf2-2c10c7d2b98c.png)

Any suggestions?

**Comment by mallowigi** [comment]
Please use the Material Theme EAP for the time being

**Comment by matt-bailey** [comment]
Thanks, that works.
