### ISSUE TITLE
0.2.2 only available in Android Studio

### ISSUE THREAD

**Issue by mgohin** [ChrisRM/material-theme-jetbrains#451]
OS : OSX
Android Studio version : 2.3.3

In plugins, I only have the v0.2.2. I did not found any clue about this issue.
In my Intellij Idea, I do have the last version and it's very nice ;)

<img width="821" alt="screenshot at sept 28 21-52-18" src="https://user-images.githubusercontent.com/3430304/30987454-578e8786-a497-11e7-84fb-dca9f51362dd.png">

**Comment by mallowigi** [comment]
Material Theme 0.3+ is supported for Android Studio 3.0+ . When the version will be out you will be able to enjoy the latest features.

**Comment by mgohin** [comment]
Ok, thanks for the quick answer ;)
