### ISSUE TITLE
Preferences don't open in last version of Gogland EAP

### ISSUE THREAD

**Issue by DexterHD** [ChrisRM/material-theme-jetbrains#452]
### Summary

Can't open Preferences window on last version of Gogland IDE.

### Expected behavior

Preferences window opened

### Actual behavior

Got error window

![ide fatal errors 2017-09-29 13-53-39](https://user-images.githubusercontent.com/1532188/31013222-ccf03084-a51d-11e7-8492-31918d059fd2.png)
![ide fatal errors 2017-09-29 13-53-12](https://user-images.githubusercontent.com/1532188/31013223-ccf14a14-a51d-11e7-8ab4-ad6a1aa5f0bc.png)

### Steps to reproduce (if needed)

1. Install last version of Gogland EAP
2. Install and enable Material UI Theme Plugin
3. Go to `Preferences`

You can also add Screenshots for a better understanding.

### Environment

![monosnap 2017-09-29 13-53-55](https://user-images.githubusercontent.com/1532188/31013229-d3f1e5b2-a51d-11e7-9bcf-fa8a64d8a2a9.png)

**Comment by MrCraftCod** [comment]
Also happens in CLion CLion CL-173.2696.23 & IntelliJ IU-173.2696.26.

**Comment by skalfyfan** [comment]
@DexterHD @MrCraftCod 

Take a look at this:
https://github.com/mallowigi/material-theme-jetbrains-eap

There is an EAP version of Material Theme available. If you fire up your IDE and go to plugins you should be able to find it.

**Comment by MrCraftCod** [comment]
Indeed, it does work better with this version. Thank you @skalfyfan
