### ISSUE TITLE
Cannot change darkblue background color using custom theme?

### ISSUE THREAD

**Issue by krims0n32** [ChrisRM/material-theme-jetbrains#454]
### Summary

Setting up a custom theme, I cannot find a way to change the darkblue background color in project view but also version control. I figured out its hexcode to be: #0d293e. 

### Expected behavior

Find an option to change the background color in Appearance & Behavior -> Material Custom Theme.

### Actual behavior

A bunch of colors is listed, but not a color set to #0d293e.

### Steps to reproduce (if needed)

1. Install Material Theme plugin
2. Edit Material Custom theme colors
3. Apply Material Custom theme

You can also add Screenshots for a better understanding.

### Environment

PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
Licensed to PhpStorm Evaluator
Expiration date: November 9, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.4-1-ARCH

![screenshot_2017-10-10_13-28-04](https://user-images.githubusercontent.com/661853/31384393-197f4710-adbf-11e7-90d6-1a45c7711e37.png)
![screenshot_2017-10-10_13-26-37](https://user-images.githubusercontent.com/661853/31384394-1997724a-adbf-11e7-8528-f8926172616b.png)

**Comment by mallowigi** [comment]
Two ways of doing that:
1. Jetbrains way: Settings > Version Control > File Status Colors
2. Material way: Settings > Editor > Color Scheme > Material File Colors

**Comment by krims0n32** [comment]
Hi there. Forgot to mention I already looked there, both in Version Control and Material File Colors. I see a bunch of custom colors but cannot find this particular one. Can you show me a screenshot of how it should look?

**Comment by mallowigi** [comment]
It's the "Modified" color

**Comment by mallowigi** [comment]
and no you can't
