### ISSUE TITLE
Font or guide for new icon?

### ISSUE THREAD

**Issue by franklinyu** [ChrisRM/material-theme-jetbrains#458]
I'm interested in adding new icon for [smali](https://github.com/JesusFreke/smali). It should be just a single letter "S", like current icon for C. I think it might be preferred to keep the font consistent? Any hint or guideline about that? Or will that be merged at all?

**Comment by mallowigi** [comment]
icons must be similar to the official framework/extension/library icon. According to the docs there is still no official icon for smali, so I'd refrain adding a custom icon for that. 

Try to submit your icon to https://github.com/file-icons/atom first. If it got merged, I'll merge yours.
