### ISSUE TITLE
Status bar is too large on MacOS High Sierro

### ISSUE THREAD

**Issue by paul321** [ChrisRM/material-theme-jetbrains#459]
See the attached screenshot:
![screen shot 2017-10-12 at 4 04 08 pm](https://user-images.githubusercontent.com/555502/31497276-4a501c9e-af67-11e7-9c52-64759cc5a237.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017

JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

**Comment by mallowigi** [comment]
This is on purpose. You can disable it in the Settings "Compact Statusbar"
