### ISSUE TITLE
PhpStorm v9.0.2: Plugin fails to initialize

### ISSUE THREAD

**Issue by bglover** [ChrisRM/material-theme-jetbrains#46]
Using PhpStorm v9.0.2 on Windows 10 x64, after restarting following installing the plugin, PhpStorm reports the following plugin error:

![material-theme-plugin-error](https://cloud.githubusercontent.com/assets/3111309/10412128/7f79362a-6f41-11e5-9649-1078d28f4749.PNG)

**Comment by ChrisRM** [comment]
@bglover Please try the newest [build](https://github.com/ChrisRM/material-theme-jetbrains/blob/master/Material%20Theme.zip?raw=true)

**Comment by bglover** [comment]
That fixed it. Thanks.
