### ISSUE TITLE
Improve Lighter Theme and add Arc Light and One Light Theme

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#461]
We need to improve lighter themes, they currently suck

**Comment by mallowigi** [comment]
Okay they also suck in the Sublime Plugin... Is someone using that at all?

**Comment by jongmmm** [comment]
I prefer lighter themes! Easy on my eyes. To me, it is still great, but one thing.

![image](https://user-images.githubusercontent.com/15218754/31724917-dc08a1f0-b3d7-11e7-9e11-9562fcb6fe26.png)

In the left pane, ignored folders are `highlighted` with darker background color. Can we change this to white background with grey font, etc?

**Comment by mallowigi** [comment]
Its' because of the File Colors feature. See in the README to know how to fix this.

I also like lighter themes, but this one is ugly imo...
