### ISSUE TITLE
Cannot see Branches in Git -> Pull Changes

### ISSUE THREAD

**Issue by clarkebishop** [ChrisRM/material-theme-jetbrains#464]
### Summary
With any Dark theme, you cannot see the branches clearly in VCS -> Git -> Pull ...
...

### Expected behavior
Expect a way to set the color to improve visibility.
...

### Actual behavior
Cannot find a way to change the color. 
...

### Steps to reproduce (if needed)

1. Set Material Theme to the Default Theme. (The problem also seems to occur with any other dark them. 
2. Go to VCS -> Git -> Pull ...

You can also add Screenshots for a better understanding.

![screen shot 2017-10-13 at 5 29 10 pm](https://user-images.githubusercontent.com/24296869/31567380-41363c5c-b03d-11e7-8b36-6a39020f1da6.png)

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
Licensed to Ultimate Software / Clarke Bishop
Subscription is active until March 28, 2018
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins

**Comment by mallowigi** [comment]
Plugin version?

**Comment by mallowigi** [comment]
Managed to reproduce.

This has been fixed in 173.X versions.

**Comment by clarkebishop** [comment]
Thanks for taking a look!

**Comment by Bradleycorn** [comment]
Confirmed I can see branches in the Pull list in 173.x, but now they have A LOT of space between them. It's cumbersome when dealing with a repo that has a large number of branches.
 
<img width="662" alt="screen shot 2017-11-10 at 12 03 35 am" src="https://user-images.githubusercontent.com/4521694/32643664-e5d4cae4-c5aa-11e7-917f-4518305f78b4.png">
