### ISSUE TITLE
Lighter theme should be a light theme

### ISSUE THREAD

**Issue by Kaishiyoku** [ChrisRM/material-theme-jetbrains#47]
First of all I have to say a big thanks for the great work that have been done here, keep going :+1: 

I don't know what the plans are for the "Lighter theme" but it should be really a light theme. Why? Because dark text on light background is more readable for people with astigmatism, I experienced it myself during this week...I used dark themes all over for several years now, coming back to light themes again. For more information this blog post should be helpful: http://blog.tatham.oddie.com.au/2008/10/13/why-light-text-on-dark-background-is-a-bad-idea/

**Comment by ChrisRM** [comment]
This theme is just a port of Material Theme for Sublime, so I will try to make it as similar as possible to this one: ![Lighter theme](https://camo.githubusercontent.com/c92011ed3bf162558e2cbf1a73f0fadd28d12dbe/687474703a2f2f657175696e75736f63696f2e6769746875622e696f2f6d6174657269616c2d7468656d652f6173736574732f696d672f6d6174657269616c2d6c696768742e706e67)

**Comment by edouard-lopez** [comment]
:+1:

**Comment by Juchar** [comment]
Is this actually still under active development or not?

**Comment by ChrisRM** [comment]
@Juchar It is, I just lack the time atm. Keep reporting issues and I'll fix them as soon as the workload at work goes down a bit.
