### ISSUE TITLE
Enhancement Request: solarized color scheme theme.

### ISSUE THREAD

**Issue by tmeusburger** [ChrisRM/material-theme-jetbrains#471]
### Enhancement Request

I wasn't sure if you were taking theme requests but in the case that you are it would be awesome to get a solarized theme.  

Solarized is a popular color scheme that is used extensively and supported in many elements.  So far I've been using an adaption of the custom theme in order to get a close approximation.  Lots of people in our dev shop use solarized and it's a bit of a hassle to tweak the custom themes for each user. 

I'd be happy to provide what I have so far, but it's definitely lacking and I would appreciate someone with a design focus helping out polishing it.

Thank you! Really love the overall look and feel of the plugin but have gotten so used to solarized.

**Comment by mallowigi** [comment]
Well, you have the custom themes feature. Send me the list of values of what you think is a good combination and I'll see what I can do.

Ideally I'd like to open an API to let other plugins develop their own themes but its not for the moment.

**Comment by tmeusburger** [comment]
Sounds great, I'll post up the values early next week (playing with them and want to land on something reasonable first). Thanks for taking a look and helping.
