### ISSUE TITLE
Unable to adjust project files font color.

### ISSUE THREAD

**Issue by edinchev** [ChrisRM/material-theme-jetbrains#476]
### Summary

When applying a color to the database, I can't see the text because it's gray. I'd prefer it to be white instead.

Using DataGrip 2017.2.2, Material Darker theme, Windows 10 Pro (v.1703)

Looked through all the settings and didn't see a way to adjust this.

Using Darcula theme for now which doesn't have this issue.

**Material Dark**

![image](https://user-images.githubusercontent.com/15091453/32172301-7f63f4da-bd51-11e7-9ed8-99d836faa2f3.png)

**Darcula**

![image](https://user-images.githubusercontent.com/15091453/32173157-6671fb86-bd54-11e7-879a-79cfe9817732.png)

**Comment by ForsakenHarmony** [comment]
I'm having problems with this too, the contrast makes it unreadable, the file colors don't apply properly as well
Removing all the colors except for the second one of my scheme (`Non-Project Files (Material Darker)`) fixes it, but it only applies to the current project

**Comment by mallowigi** [comment]
The text color will not change folks. If you want you can still use the custom theme and change the color itself, or use a different, darker green color.

As for the file colors, I'm aware of this problem for a long time and unfortunately the only fix I can propose is the one I wrote on the readme, so bear with it.

You're welcome to look at the code and try to fix it

**Comment by hadian90** [comment]
Is this consider a same problem as above 
<img width="164" alt="screen shot 2017-11-22 at 12 59 11 pm" src="https://user-images.githubusercontent.com/2718199/33111163-6dfbf5ba-cf87-11e7-9b78-22a295ad9258.png">

It too dark for me, nothing like readme screenshot
