### ISSUE TITLE
On the darker theme, annotations is still not visible. 

### ISSUE THREAD

**Issue by say8425** [ChrisRM/material-theme-jetbrains#479]
### Summary

In 1.1.2 pre version, #460 is not fixed yet.
Can't see Annonations propery with the Darker theme

### Steps to reproduce (if needed)

 1. Select the darker theme
 1. Right click on line numbers column
 1. Check Annotate (GIT init needed)

<img width="1400" alt="32151358-9c255b96-bd5f-11e7-8d14-acc82308dac6" src="https://user-images.githubusercontent.com/3258867/32305321-36adc748-bfb8-11e7-90b5-211b98ca6e9a.png">

### Environment

RubyMine 2017.2.4
Build #RM-172.4155.44, built on September 27, 2017
Licensed to Iumsocius inc. / 펭 귄
Subscription is active until November 25, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13

**Comment by mallowigi** [comment]
Check if you got a copy of the color scheme and restore defaults. There should be the fix.

**Comment by pahan35** [comment]
@mallowigi looks like here is the same problem for Dracula theme.
![image](https://user-images.githubusercontent.com/13823215/49049590-4b219980-f1e8-11e8-9db1-c70a4ae0d222.png)

Should I create a separate issue for it?

**Comment by mallowigi** [comment]
I will fix the selection color, but the annotations should work fine. MAke sure you have reset the color scheme to defaults.
