### ISSUE TITLE
Custom theme configuration

### ISSUE THREAD

**Issue by Mr-SD** [ChrisRM/material-theme-jetbrains#481]
Hi, I'd like to modify this plugin's custom theme programmatically based on color schemes generated by tools such as pywal so I'd like to know where this plugin reads from/stores it's configuration files/settings?

**Comment by mallowigi** [comment]
you can find the colors in the config directory. It is named material_custom_theme.xml.

I think though that you have to change the default values in order to see the keys in the xml file.

**Comment by Mr-SD** [comment]
Thanks, specifically I found it under `config/options/material_custom_theme.xml`.
I also created a [script](https://github.com/Mr-SD/intellijPywal) that can automatically generate themes and color schemes based on pywal and this plugin.

**Comment by mallowigi** [comment]
Awesome dude!
