### ISSUE TITLE
Theme colors hiding file name text

### ISSUE THREAD

**Issue by LordZardeck** [ChrisRM/material-theme-jetbrains#482]
Currently while using the material theme, I cannot see the file names of my scratches unless I have the file selected:

![](http://take.ms/UoTHa)

**Comment by mallowigi** [comment]
Did you change the color scheme at some point? What controls this color is the "Suppressed" key in Material File Colors (in Color Scheme). It should be #546E7A

**Comment by LordZardeck** [comment]
Ahh, okay, thanks. Didn't think that got changed, but at this point i have no idea what's been changed.
