### ISSUE TITLE
Custom Theme bluish Text Color

### ISSUE THREAD

**Issue by ddnexus** [ChrisRM/material-theme-jetbrains#484]
### Summary

I am trying to customize the UI with all neutral shade of gray (removing the bluish color-cast). After changing the provided settings for the custom theme, there is still a lot of UI text scattered around that appears to be tinted with #B0BEC5. Searching for that color I found 46 occurrences in the file at this path:

`.RubyMine2017.2/config/plugins/Material Theme/lib/material-theme-jetbrains/colors/Material Theme - Lighter.xml.`

### Expected behavior

Being able to customize the color of all the UI text in the Material Custom Theme settings.
Unless I am missing a place where to edit that color, it looks like bug, since it is not a Darcula color. Is there any work around that I can use until it will get fixed? Thanks.

### Environment

RubyMine 2017.2.4
Build #RM-172.4155.44, built on September 27, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-16-generic

**Comment by mallowigi** [comment]
Can you send a screenshot of what you see and what seems to be the problem ?

**Comment by ddnexus** [comment]
Attached a few screenshots. 

### Options and Custom Colors assigned

![material theme options and colors](https://user-images.githubusercontent.com/100721/32530307-e8a78afe-c46f-11e7-95f9-fa589283f93b.png)

![material custom colors](https://user-images.githubusercontent.com/100721/32530317-11a03762-c470-11e7-8a41-fb727b43f0e0.png)

Notice:
- all the possible options define only grey colors, however...
- the caret color does't get changed even after a restart (it is always yellow). 
- the selected item foreground text ("Material Theme" and "Material Custom Theme" in the sample) screenshot should not be #FFFFFF (no text foreground is set to #FFFFFF)
- all the popup values and string values settings are displayed in #B0BEC5
- All the tool-tip balloons text on hover (not shown) are displayed in #B0BEC5

### Other screenshots

![offending color in text plugins](https://user-images.githubusercontent.com/100721/32530547-5e1e5b0e-c471-11e7-9bd7-0c753bb5c8e4.png)

- many texts and UI items are displayed in #B0BEC5 above

![menu](https://user-images.githubusercontent.com/100721/32530583-944f0c14-c471-11e7-89f3-07ff49e7f937.png)

- the Project panel (as all the other panels) menu items are displayed in #B0BEC5
- the top bar of all the panels gets the bluish background color when selected. When is not selected it is nice and transparent, defined only with the top and bottom border. That is Darcula is it possible to override it?
- the active item is displayed in that dark blue #0D293E. That is Darcula. Is it possible to override it?
- the tab background of the docker panel is not defined in any of the custom colors. Where is it coming from?  Is it possible to override it?

![tabs and selected](https://user-images.githubusercontent.com/100721/32530846-22ec5eda-c473-11e7-822e-2d85b34f8c16.png)

![tabs and list](https://user-images.githubusercontent.com/100721/32530972-f9385688-c473-11e7-8ddb-c81119c97b62.png)

- the tab text is displayed in #B0BEC5
- the tab background is not neutral and it is not defined in any of the custom colors. Where is it coming from?  Is it possible to override it?
- the items in the list are displayed in  #B0BEC5
- the selected item in the list is displayed in #FFFFFF not defined anywhere in the custom colors

HTH

**Comment by ddnexus** [comment]
A shorter summary for the faulty Custom Colors found so far:

- the Foreground Color applies only to part of the texts (as explained in the post before many texts are displayed with in #B0BEC5) 
- the Selection Foreground Color doesn't apply to anything (always displayed in #FFFFFF)
- the Caret Color doesn't apply to anything (always displayed in yellow)

**Comment by mallowigi** [comment]
- The Caret Color is not the color of the caret you see in the editor, but rather the color of the caret in the IDE components (like inputs and searches). If you want to change the caret color in the editor, it's in the color schemes.
- About the default foreground color (B0BEC5), it could be a bug or something I cannot change. I will tell you more once I get to test it
- The blue background color is hardcoded in the IDE. I can't change it.
- For the tabs, I remember having this issue but I thought no one would notice as there is hardly settings with the default tabs (e.g. not JBEditorTabs), but I'll fix this
- As for the selected item in list, it might be a bug.

**Comment by mallowigi** [comment]
As for the last issue, with the search box: I know about it and after I've tried countless times to find the cause of this bug, I've decided to not fix it as it is not an easy task to do. They used a different component than the input component for the search that I cannot theme (except changing the border color), but in some occurences they are actually using the input component??? Like I said I tried to understand but couldn't, unfortunately.

**Comment by ddnexus** [comment]
Thanks for you answers!

- The caret color I am referring to is not the one in the editor but the one in the IDE components. It stays yellow, but it is not a big problem at all. I just reported it for completeness. If it is difficult to find, I could switch to a yellow cursor also in the editor - as you can notice I am a consistency-freak :)
- The default foreground text is very likely a bug, since Darkula doesn't use it. Hoping that you can find out a quick fix.
- Good luck to squash the selected text bug!
- If you tried so hard to find the cause of the search UI bug, then... welcome to the consistency-freak club :). That little glitch is actually not so upsetting.... we can live with it, right? ;)
- What about the bluish top bar of the panels? I suspect it is also hard-coded in the IDE, but please, tell me that I am wrong!

**Comment by mallowigi** [comment]
Ok, I've worked on that and I think I fixed most of the issues here.

Please download the EAP plugin and tell me if it's fixed.

**Comment by ddnexus** [comment]
You mean download from the Plugins interface? I'not sure I see a new version there. Version: 1.2.1-pre is that one? It looks like it is the same I have already. Do I miss anything?

**Comment by mallowigi** [comment]
Actually I'm in the process of removing the EAP so please download the non-EAP version as soon as you see the update available

**Comment by ddnexus** [comment]
Thanks for the update. 

Actually, only the fixed white selected item has been fixed and it now reflects the custom color. All the rest that has been reported is still as it was before, plus there are some more problems, especially with the B0BEC5 color.

Now there are more items that have that color, like for example the text of the check-boxes in the settings. But the worse usability problem introduced by this release is that the B0BEC5 color is used also as a selection background through the whole application (when it is not an item in a list, mentioned above).

It is practically impossible to read a light gray text on a light blue background with the same brightness. I appears for example in the opening project list, panel menu items, certain list items and selectable text.

Another quite annoying issue is that the Editor Color Style is changed back to Material Oceanic at each application restart.

A curious thing is also that with Contrast Mode the apply button in the settings works almost like a toggle: almost each time you click on it, it toggle the contrast mode colors on and off (not the contrast mode option, that remain checked).

One last thing is: the button/tabs that remain bluish/greenish (see last screenshot "Accepted Words")

I reset the styles and restarted the app a couple of times, I even uninstalled the pluging and reinstalled, but no progress. 

A few screenshoots:

![error-detail](https://user-images.githubusercontent.com/100721/32689978-43928294-c721-11e7-8c09-d1344375f449.png)

![project-list](https://user-images.githubusercontent.com/100721/32689988-57ed2ae6-c721-11e7-97eb-733096085e96.png)

![item-selection](https://user-images.githubusercontent.com/100721/32690032-0a4fee08-c722-11e7-9c15-bda0334aa2da.png)

![radio-and-checks](https://user-images.githubusercontent.com/100721/32690043-5c558cb2-c722-11e7-8e3b-b1f1fd6d2b45.png)

![panel-menu](https://user-images.githubusercontent.com/100721/32689998-6ac05f76-c721-11e7-9966-ff44fb04898d.png)

![button-tab](https://user-images.githubusercontent.com/100721/32690001-818651c0-c721-11e7-8b7c-adf55cacc3fe.png)

**Comment by ddnexus** [comment]
As a side note: please, consider to keep the EAP, since it still works better in my case. I am currently back to use it.

**Comment by mallowigi** [comment]
Hey. Can you go there? https://gitter.im/Material-Theme-Jetbrains/Lobby#

**Comment by ddnexus** [comment]
Closing this issue since the main problem of the B0BEC5 color appear to be fixed in 1.3.1. I will open another issue just for the minor glitches left. Thanks!
