### ISSUE TITLE
Row height in Data View

### ISSUE THREAD

**Issue by jaskiratr** [ChrisRM/material-theme-jetbrains#485]
### Summary
When I view a Data Frame or an Array in a Data View, the text is not legible due to incorrect row height/line spacing.

### Expected behavior
It works fine when I turn off the Material Theme.

![image](https://user-images.githubusercontent.com/8619877/32693489-7a719174-c6f9-11e7-8a02-c806585263d9.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/8619877/32693467-43741250-c6f9-11e7-9842-3616bb81becb.png)

### Environment
PyCharm Community Edition 2017.2.4
Build #PC-172.4343.24, built on October 19, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Material UI Plugin Version: 1.3.0-revert
Windows 10 Pro
Dell XPS 9550 (4K Screen)

Any help would be appreciated.
Thank you!

**Comment by mallowigi** [comment]
Please download latest version and check the "Compact Table Cells" setting
