### ISSUE TITLE
Plugin 'Material Theme UI' is incompatible with this installation

### ISSUE THREAD

**Issue by kostonstyle** [ChrisRM/material-theme-jetbrains#487]
Hi all  
When I try to install the theme, I've got following error message:
![screenshot from 2017-11-13 10-17-25](https://user-images.githubusercontent.com/701611/32717968-e18357c2-c85b-11e7-8591-7fc2ee2da4ce.png)

My IntellJ version:
> IntelliJ IDEA 2017.2.5
> Build #IU-172.4343.14, built on September 26, 2017  

I took: 
![screenshot from 2017-11-13 10-19-41](https://user-images.githubusercontent.com/701611/32718076-3285d7e4-c85c-11e7-9209-b7704874d1b6.png)  

What am I doing wrong?

**Comment by mallowigi** [comment]
Yes I also got this error. Just try again after uninstalling the plugin and it should be fine
