### ISSUE TITLE
Git Pull Window - Branches list spacing is too big

### ISSUE THREAD

**Issue by Bradleycorn** [ChrisRM/material-theme-jetbrains#488]
### Summary

When you open the Git->Pull dialog box, there is A LOT of spacing between the branches in the branches list. This is cumbersome to deal with when working on a repo with a lot of branches. 

This issue only appears on IntelliJ versions 173.x. 
On 172.x versions of IntelliJ, this issue with the spacing does not appear, but these versions suffer from #464 which makes it virtually unusable on 172.x versions.

### Expected behavior

The spacing between branches in the branches list should be smaller (preferably, the Intellij default) so that the list of branches is easily scrollable.

<img width="668" alt="screen shot 2017-11-13 at 9 21 07 am" src="https://user-images.githubusercontent.com/4521694/32730138-1859b546-c854-11e7-8504-b343e5bdb170.png">

### Actual behavior

The branches list has a lot of spacing between branches.

<img width="662" alt="screen shot 2017-11-10 at 12 03 35 am" src="https://user-images.githubusercontent.com/4521694/32730040-cfac41e2-c853-11e7-85c1-063e8d053ca6.png">

### Steps to reproduce (if needed)

1. Use a 173.x version of IntelliJ
2. From the Menu's, choose: VCS -> Git -> Pull...
3. See the spacing in the "Branches to merge list"

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3622.25, built on November 9, 2017
Expiration date: December 9, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by dudong0726** [comment]
also on windows 7 
IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3622.25, built on November 9, 2017
IntelliJ IDEA EAP User
Expiration date: December 9, 2017
JRE: 1.8.0_152-release-1012-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by ddnexus** [comment]
also on Linux
RubyMine 2017.3 EAP
Build #RM-173.3622.24, built on November 9, 2017
RubyMine EAP User
Expiration date: December 9, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-16-generic

**Comment by mallowigi** [comment]
Fixed in latest EAP by a new setting

**Comment by Bradleycorn** [comment]
@mallowigi what's the new setting?

**Comment by mallowigi** [comment]
Compact table cells

**Comment by dudong0726** [comment]
resolved
