### ISSUE TITLE
File Setting Color Scheme — The menu list not horizontal alignment

### ISSUE THREAD

**Issue by dudong0726** [ChrisRM/material-theme-jetbrains#489]
### Summary
The menu list not to be horizontal in Color Scheme and Code Style 
...

### Expected behavior

![image](https://user-images.githubusercontent.com/1704803/32761483-90dec080-c92e-11e7-8d1b-572827a7b644.png)

...

### Actual behavior
![image](https://user-images.githubusercontent.com/1704803/32761374-f7a5b0a4-c92d-11e7-9133-4b0431fbe4c8.png)

...

### Environment
IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3622.25, built on November 9, 2017
IntelliJ IDEA EAP User
Expiration date: December 9, 2017
JRE: 1.8.0_152-release-1012-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

MTU Version: 1.3.0-beta7

**Comment by mallowigi** [comment]
I cannot change this. It used to be a gear icon and now it’s an hamburger menu icon, that’s it.
