### ISSUE TITLE
Bug with border color in Light theme

### ISSUE THREAD

**Issue by monolithed** [ChrisRM/material-theme-jetbrains#490]
### Summary
![qbhygodzis](https://user-images.githubusercontent.com/803674/32892379-1beee592-cae7-11e7-8bab-857b1a3fd84d.gif)

### Expected behavior

![img-2017-11-16-15-48-05](https://user-images.githubusercontent.com/803674/32892151-5339089e-cae6-11e7-8625-814a2b309706.png)

### Actual behavior

![img-2017-11-16-15-47-50](https://user-images.githubusercontent.com/803674/32892164-5bdfd0ea-cae6-11e7-8a2a-7c62f51c25ec.png)

You can also add Screenshots for a better understanding.

### Environment

```
PyCharm 2017.2
Build #PY-172.3317.103, built on July 25, 2017
Licensed to Mail.ru LLC / Mail.ru Games LLC Alexander
Subscription is active until February 6, 2018
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

**Comment by monolithed** [comment]
@mallowigi the bug with moving is still existing (

![pwkhejjggn](https://user-images.githubusercontent.com/803674/34201715-71913432-e586-11e7-8bf1-869a5678bd4e.gif)

**Comment by mallowigi** [comment]
I know but it's something fairly small that occurs only on Mac, and on Lighter theme. I've tried to take a look but couldn't even reproduce it, so I'm closing it as it's no big deal.

You're welcome to look into it :)

**Comment by fabiobiondi** [comment]
I have the same problem but even if I don't move them (Webstorm 2017.3.1 - El Capitan 10.11.6) 

![image](https://user-images.githubusercontent.com/1772083/34448862-3030d290-ecf2-11e7-9ad5-76aad67eaafc.png)
