### ISSUE TITLE
Add colour scheme for es6/typescript features

### ISSUE THREAD

**Issue by pavilion** [ChrisRM/material-theme-jetbrains#491]
As decorators "@ThisIsADecorator"
And value types as "string" at
a: string;
Example of how it looks now
![image](https://user-images.githubusercontent.com/3165436/32927524-f05ceb1e-cb44-11e7-97bf-9c217d11bfe0.png)
Example of how should it look
![image](https://user-images.githubusercontent.com/3165436/32927557-2ab7e584-cb45-11e7-8071-4df11400a212.png)

**Comment by mallowigi** [comment]
Can you do a PR?

**Comment by pavilion** [comment]
IDEA team are already already looking forward to fix this issue.

Decorators.
![image](https://user-images.githubusercontent.com/3165436/33089888-f6655930-cee9-11e7-9be6-4f256387f475.png)
Built-in types.
https://youtrack.jetbrains.com/issue/WEB-27744

**Comment by mallowigi** [comment]
Please open the issue as soon as they implement this. Closing this for now.

**Comment by pavilion** [comment]
They have implemented it
