### ISSUE TITLE
C# Rider not work Highlights

### ISSUE THREAD

**Issue by Avatarchik** [ChrisRM/material-theme-jetbrains#492]
JetBrains Rider 2017.2.1
Build #RD-172.4144.1873, built on November 12, 2017
Licensed to Avatarchik

JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

http://take.ms/k981q

**Comment by mallowigi** [comment]
Don't understand

**Comment by Avatarchik** [comment]
before http://take.ms/VrDFh
now http://take.ms/7dbE0

**Comment by mallowigi** [comment]
Ah yeah, I changed the red color to a white one because red looks like errors
