### ISSUE TITLE
StatusBar interference cannot be disabled?

### ISSUE THREAD

**Issue by ddnexus** [ChrisRM/material-theme-jetbrains#493]
I like to use the [project-label ](https://github.com/drinchev/project-label) plugin. It is a simple but useful plugin that shows the project name on a custom project-colored label strip in the StatusBar.

The theme own StatusBar interfere with it even if I want the original StatusBar (i.e. StatusBar small as the original theme, and no drawing of the theme name). How could I just skip the StatusBar features all together and get the project-label back?

**Comment by mallowigi** [comment]
So you want them to both coexist or do you want to see the Project Label? I don't know why they don't coexist at the moment but if you want the stauts bar you can just disable the feature through the options.

Besides this project looks pretty broken to me in the latest EAP.

**Comment by ddnexus** [comment]
I think I have disabled all the options, but I could have missed something, Please could you tell me what are the options to set?

**Comment by mallowigi** [comment]
Theme in StatusBar

**Comment by ddnexus** [comment]
It is off, and still the label of the other plugin does not appear. I
played also with the other options related to the StatusBar height but no
improvement.

**Comment by mallowigi** [comment]
I see that the label is indeed not appearing. I will investigate why.
