### ISSUE TITLE
Chevron Icon inconsistency

### ISSUE THREAD

**Issue by ddnexus** [ChrisRM/material-theme-jetbrains#494]
If you disable the Material Icons because you want to use the original icons, the chevron icons of the open/close toggle of the tree list doesn't get reverted to the classic right/down triangle.

You have to disable also the Material Components in order to get the triangles back (so loosing all the Material look items all over the UI). It looks like that icon is somehow hard-coded in the tree drawing component or somewhere, and it is inconsistent for example with the open/close toggles of the list of settings, which remains a triangle regardless the settings for icons and components.

It would be nice for the tree to respect the Icon Settings: with the Material Icons on it should display a chevron, with the Material Icons off it should respect the original triangle (or whatever is the system symbol for that).

**Comment by mallowigi** [comment]
Yep because the arrows are from the custom components. e.g. the Tree. It is not something themeable like the file icons.

I can specify a toggle inside the custom tree component to check if the icons setting is enabled, but IMHO it doesn't make sense as it isn't an icon.

Let others decide whether they want it or not, but for now I'll refrain doing that.

**Comment by ddnexus** [comment]
Well, it is a graphic item, and as it is inconsistent between different parts of the UI (i.e. files tree, settings tree), and that makes me a bit uncomfortable, but I am a consistency-freak, as you know :).

BTW, I just wanted it to report it. You should put this as low priority, since there are more important fixes to take care of.

**Comment by mallowigi** [comment]
I will add an option to switch between chevrons and other icons such as the triangle
