### ISSUE TITLE
Non-project files categories impossible to remove!

### ISSUE THREAD

**Issue by ddnexus** [ChrisRM/material-theme-jetbrains#495]
The Non-project files categories added by the Material Theme keep getting added even if you delete them! That's annoying, because it pollutes the menu, and I don't even use the Enable File Colors feature!

**Comment by mallowigi** [comment]
There's nothing I can do about that. Just ignore them and put them at the bottom of the list.

**Comment by ddnexus** [comment]
What about not putting them in automatically? If the user want them a
paragraph in the README could give instructions about how to add them
manually.

**Comment by mallowigi** [comment]
You're right. I can add an action to install them if the user wants them.

**Comment by ddnexus** [comment]
You are my hero! :)
Thanks!

**Comment by ddnexus** [comment]
This is great! Thanks!
