### ISSUE TITLE
Option to revert back to old progress bar

### ISSUE THREAD

**Issue by anidotnet** [ChrisRM/material-theme-jetbrains#496]
The new progress bar style is kinda dull and fat. Please add an option to revert back to old progress bar style which was before version 1.3.1.171.4155.1

**Comment by mallowigi** [comment]
Which version are you on? If you are on the latest EAP, you should know that this progress bar is introduced by Jetbrains, and there is no way to revert  to the old style

**Comment by mallowigi** [comment]
And if you're pre-EAP, you can still disable the Material Components to revert to the Jetbrains style. I won't restore the hybrid state.
