### ISSUE TITLE
Tabs don't respect custom theme colors

### ISSUE THREAD

**Issue by ddnexus** [ChrisRM/material-theme-jetbrains#498]
It looks like there are 2 possible offending colors for tabs:

![tabs and selected](https://user-images.githubusercontent.com/100721/32530846-22ec5eda-c473-11e7-822e-2d85b34f8c16.png)

![button-tab](https://user-images.githubusercontent.com/100721/32690001-818651c0-c721-11e7-8b7c-adf55cacc3fe.png)

**Comment by ddnexus** [comment]
The type of tab shown in the second screenshot is fixed, while the one in the first screenshot is still not fixed in 1.3.2.

**Comment by mallowigi** [comment]
Yes because they are hardcoded in the API, I can't change it as easily as the others.

**Comment by ddnexus** [comment]
I mean the background color is fixed, the tab style is not Material-like as for example the tabs in the editor. E.g. text and data tabs are Material-like. But it is probably difficult to patch, as you just wrote :/
