### ISSUE TITLE
Commit message, white separator

### ISSUE THREAD

**Issue by Cog-g** [ChrisRM/material-theme-jetbrains#5]
Hi again,

Is it possible to fix the color of the seperator in commit review?

![image](https://cloud.githubusercontent.com/assets/1284945/10159373/353daf16-6698-11e5-8617-5739908bc5b0.png)

**Comment by ChrisRM** [comment]
I'll have a look at that

**Comment by ChrisRM** [comment]
@Cog-g I'm not able to reproduce this. Can you try the newest build?

**Comment by Cog-g** [comment]
Hi, I've just downloaded last version minutes ago, and it's the same:

![image](https://cloud.githubusercontent.com/assets/1284945/10410087/1a4dfcd6-6f37-11e5-83fc-e93707bb9c68.png)

![image](https://cloud.githubusercontent.com/assets/1284945/10410091/3193d672-6f37-11e5-8828-77fd2526d09d.png)

**Comment by ChrisRM** [comment]
I'll see if I can improve support for EAP builds. As of now it is not fully supported.
