### ISSUE TITLE
Regression of #342

### ISSUE THREAD

**Issue by vpassapera** [ChrisRM/material-theme-jetbrains#502]
### Summary

Color & Fonts scheme not being honored after restart.

### Expected behavior

Scheme to persist after a restart.

### Actual behavior

After a restart, scheme reverts back to default "Darcula".

### Steps to reproduce

1. Install material theme ui plugin and select (Darker, Default, Palenight)
2. Go to File/PhpStorm > Settings/Preferences > Editor > Colors & Fonts
3. Select any item that was custom installed to the colors dir.
4. Restart PHPStorm
5. Setting reverts back to Darcula.

Same issue that #342 addressed :(

**Comment by mallowigi** [comment]
Yep, only happens with light themes. Investigating.

**Comment by vpassapera** [comment]
Why closed? :(
