### ISSUE TITLE
Git Pull Changes Dialog: Branch Colors Do Not Contract Correctly

### ISSUE THREAD

**Issue by DmacMcgreg** [ChrisRM/material-theme-jetbrains#504]
Notice the text color:
![pull_changes_and_admintransactiondetail_jsx_-_admin-fe-app_-____documents_code_veem_admin-fe-app_](https://user-images.githubusercontent.com/3266023/33027733-f6f8278c-cde1-11e7-8512-26d109e91aae.jpg)

* OS : Mac OSX 10.12.5
* IntelliJ Product : Webstorm
* Plugin version: 1.0.0
* Plugin configuration : default

**Comment by mallowigi** [comment]
You're probably on older versions of Webstorm (2017.X)

**Comment by DmacMcgreg** [comment]
2017.2, but I see no updates.

**Comment by mallowigi** [comment]
This has been fixed in 2017.3+. Sorry you'll just have to wait for the new Webstorm to be released.
