### ISSUE TITLE
Dark title bar

### ISSUE THREAD

**Issue by avendael** [ChrisRM/material-theme-jetbrains#505]
The gray title bar looks out of place when the rest of the theme is dark

![image](https://user-images.githubusercontent.com/53690/33028322-98ed40f4-ce50-11e7-8990-ab5c315fb0d9.png)

Other macos apps do this already, whether it be from custom themes or not

![image](https://user-images.githubusercontent.com/53690/33028362-bac3466a-ce50-11e7-877e-1400c5409b07.png)

![image](https://user-images.githubusercontent.com/53690/33028531-24db5006-ce51-11e7-8b19-b5eb05b5bb90.png)

**Comment by mallowigi** [comment]
Interesting. I'll take a look.

**Comment by mallowigi** [comment]
There is no way to do it via the plugin, but you can activate it from the Registry (Command Palette -> Registry) and check the option `ide.mac.allowDarkWindowDecorations`

**Comment by avendael** [comment]
I can't find this option in the registry. What intellij version are you using?

**Comment by avendael** [comment]
I tried adding it to idea.properties but it has no effect.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/33241235-66cf079a-d2cb-11e7-8623-545970ca74e4.png)

**Comment by avendael** [comment]
It's not in the intellij version that I'm using :( I'm on intellij ultimate 2017.2.6. What version are you using?

**Comment by mallowigi** [comment]
2017.3 

That means that there is a possibility that this will be added to the UI at some point then
