### ISSUE TITLE
Add an option to "hide" scrollbar in custom themes or components

### ISSUE THREAD

**Issue by avendael** [ChrisRM/material-theme-jetbrains#506]
Intellij does not have this option, nor does it honor the macOS "[hide scrollbars except when scrolling](https://stackoverflow.com/questions/45765214/intellij-idea-hide-vertical-scrollbar)" setting. It's probably a Java app thing. But since this plugin can edit the scrollbar thumb color, perhaps it can "cheat" by setting its transparency to 100%.

**Comment by mallowigi** [comment]
I will not set the transparency to 100% as it is very inconvenient. The "Transparent Scrollbars" option should be enough don't you think?

**Comment by avendael** [comment]
Yes, I think so. It would also be awesome if it’s possible to allow changing the scrollbar color in the custom theme settings page.

**Comment by mallowigi** [comment]
I don't want to develop stuff that people will barely use it. If you want you can try fiddling with the project by yourself, PR are appreciated ^^

**Comment by avendael** [comment]
Ok that's fair.
