### ISSUE TITLE
Plugin Error 1.3.3

### ISSUE THREAD

**Issue by Altroo** [ChrisRM/material-theme-jetbrains#508]
Hello i've just updated to version 1.3.3 & i'm getting this.

![sans titre](https://user-images.githubusercontent.com/30314254/33039776-140e9802-ce31-11e7-9f12-ee5cbfb8aee5.png)

Then i've downloaded the plugin & extracted it manually but still the same error, this error is on windows, on mac it works fine.

**Comment by mallowigi** [comment]
I've released a new version that reverts this change. Please check 1.3.3.1
