### ISSUE TITLE
Override parameters values clipped vertically

### ISSUE THREAD

**Issue by nwolfe-xx** [ChrisRM/material-theme-jetbrains#509]
### Summary
When trying to edit values in the Run/Edit Configurations/Spring Boot/Override parameters list, the value edit box is clipped on the top and bottom, so you can barely read the value that you are typing in.

### Expected behavior
No clipping of text

### Actual behavior
Text entered into the Value column is clipped until the edit session is done.

### Steps to reproduce (if needed)

1. Go to Run/Edit Configurations
2. Click the + button in the upper left of the popup to create a new run config
3. Choose Spring Boot from the list
4. In the Override parameters section, click the + button to add a new parameter
5. Double click in the new row, underneath the "Value" column header.
6. Start typing, notice that the characters you are typing are clipped and you can only see the very middle of the characters (vertically).
7. When you tab out of the field, the characters are fine.  It is only a problem when you are trying to edit the values.

### Environment

IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017
Subscription is active until June 6, 2018
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
![screen shot 2017-11-20 at 3 26 36 pm](https://user-images.githubusercontent.com/852529/33047040-880de5b0-ce08-11e7-8e2f-0992e4ddc573.png)

**Comment by mallowigi** [comment]
I cannot fix this. If you need to see clearly what you are entering I suggest you to disable the Material Components.
