### ISSUE TITLE
Install instructions are out of date?

### ISSUE THREAD

**Issue by Anahkiasen** [ChrisRM/material-theme-jetbrains#51]
Tried downloading the .jar from the README but the file doesn't exist anymore. I downloaded the zip but it has three .jar files in it, should all three be installed manually?

**Comment by Anahkiasen** [comment]
Nevermind, figured it out. Needed to install the zip itself

**Comment by mikeerickson** [comment]
Take the opportunity to contribute my clarifying directions which lead you astray. Future users will benefit

**Comment by ChrisRM** [comment]
I'll update the readme.
