### ISSUE TITLE
Panel tab height is too tall

### ISSUE THREAD

**Issue by ddnexus** [ChrisRM/material-theme-jetbrains#511]
The tab height in Darkula have a more functional height that does not waste real estate.

The tabs styled by the theme have a quite tall look, which may be just a cosmetic problem in the settings for example, but become a real problem in some of the panes (e.g. Docker). They are a lot taller than needed, wasting quite a lot of precious real estate there.

The height of the tabs should not change from the original, only the background color should change.

**Comment by mallowigi** [comment]
This is not an easy feat to do, as the height of the tabs are linked to each other, e.g editor tabs and code style tabs for example share the same height.

If that really bothers you you can reduce the tab height in the settings, but that will also influence the editor tabs.

**Comment by ddnexus** [comment]
That is absolutely not the case! I thought about that before posting the issue, and there is no relation whatsoever between the panel tabs and the editor tab height.

**Comment by ddnexus** [comment]
No relation between the theme-styled height and the height in the settings. The theme-styled tabs have their fixed hard-coded height in both the UI Panels and Settings, and are not affected by the Tab Height set in the Material Theme Settings:

![tabs-in-panel](https://user-images.githubusercontent.com/100721/33153982-d07268c4-d017-11e7-8b20-e34817011380.png)

![tabs-in-settings](https://user-images.githubusercontent.com/100721/33153989-dda1b37e-d017-11e7-8c8f-f67b49573e5d.png)
