### ISSUE TITLE
Font ligatures do not display within the editor when the theme is active.

### ISSUE THREAD

**Issue by DavZZar** [ChrisRM/material-theme-jetbrains#515]
### Summary

When using fonts with ligatures such as [FiraCode](https://github.com/tonsky/FiraCode) while the theme is active, the ligatures do not render! However, in the Editor Settings preview [Settings -> Editor -> Font], they are rendered correctly.

### Expected behavior

The font dependant font ligatures to be rendered.

### Actual behaviour

Ligatures are not rendered.

### Environment

- IntelliJ IDEA 2017.2.6
- Build #IU-172.4574.11, built on November 13, 2017
- Windows 10 10.0
- Material Theme UI 1.3.3.1
- ```
  <application>
   <component name="MaterialThemeConfig">
     <option name="version" value="1.3.3.1" />
     <option name="selectedTheme" value="DARKER" />
     <option name="highlightColor" value="e91e63" />
     <option name="highlightColorEnabled" value="true" />
     <option name="highlightThickness" value="3" />
     <option name="isContrastMode" value="true" />
     <option name="isBoldTabs" value="true" />
     <option name="accentColor" value="e91e63" />
     <option name="compactSidebar" value="true" />
     <option name="tabsHeight" value="50" />
     <option name="isCompactStatusBar" value="true" />
     <option name="isCompactTables" value="true" />
     <option name="defaultBackground" value="" />
     <option name="upperCaseTabs" value="true" />
   </component>
 </application>

### Screenshots

![2017-11-26 09_12_51-learning intellij - c__users_david_ideaprojects_learning intellij - main java](https://user-images.githubusercontent.com/7673161/33238690-711c5568-d28a-11e7-8e7c-522bd8a0dda0.png)

![2017-11-26 09_13_51-learning intellij - c__users_david_ideaprojects_learning intellij - main java](https://user-images.githubusercontent.com/7673161/33238691-7bc3d234-d28a-11e7-8c49-543ef815e173.png)

**Comment by mallowigi** [comment]
You need to activate it in Settings -> Editor -> Color Scheme Font.
