### ISSUE TITLE
Android Studio design view background colours

### ISSUE THREAD

**Issue by ElHyperion** [ChrisRM/material-theme-jetbrains#516]
### Summary

Design view in Android Studio isn't properly skinned. The background behind the whole Design view, some elements in the Attributes tab and the unselected tab of Design / Text selector below.

### Expected behavior

The background colour should copy the colour of the surrounding area, as seen on [this screenshot](https://i.imgur.com/GXw6osm.png) of the default Darcula theme. The gray edges of textboxes in the Attributes should probably have different colour too, than the default Darcula gray tone.

### Actual behavior

The aforementioned elements retain their default colour, without any respect to the currently selected Material colour theme. [Here is a screenshot](https://i.imgur.com/n5vjPdw.png) with Material UI enabled. You can clearly see on the right that the constraint designer above, the drop down lists and text input fields all have gray backgrounds and borders from the Darcula theme. The "Text" tab below is gray on the screenshot but somehow it appears fine now.

### Environment

Tested on Windows 10 and Linux Mint 18.2, the issue is identical. Happens with clean Material UI install, nevermind the custom syntax colour theme on the screenshot.

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
/ Linux 4.10.0-38-generic

**Comment by mallowigi** [comment]
I will see if there is anything I can do but from the look of it it doesn’t look good, because that means that they are not using the global colors and instead implement their own, thus being harder to change. But I’ll look and give you the results.

**Comment by mallowigi** [comment]
Sorry, there is no way to do this atm.

**Comment by nooballday** [comment]
is it still not possible?

**Comment by mallowigi** [comment]
Maybe they changed it, reopening it atm

**Comment by mallowigi** [comment]
will be available next release
