### ISSUE TITLE
Double-shift is broken in light theme on Windows

### ISSUE THREAD

**Issue by oleg-py** [ChrisRM/material-theme-jetbrains#517]
### Summary
When trying to search everywhere using double-shift, and the lighter / custom light theme is enabled, nothing happens. This only occurs for me on Windows (works properly on osx), I've seen this happen on two different machines with Windows 10.

### Expected behavior
After clicking double shift, search box appears with dropdown of recent files.

### Actual behavior
Nothing happens after clicking double shift.

### Environment
Windows 10 Pro v.1709 build 16299.64

Intellij IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.78, built on November 21, 2017

JRE: 1.8.0_152-release-941-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Material Theme plugin: 1.3.4

Plugin config:
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="1.3.4" />
    <option name="selectedTheme" value="LIGHTER" />
    <option name="defaultBackground" value="https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-eap/master/src/main/resources/themes/wall.jpg,60" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Fixed in the latest version 1.3.5
