### ISSUE TITLE
Color tag greyed out in android studio

### ISSUE THREAD

**Issue by td0** [ChrisRM/material-theme-jetbrains#518]
### Summary
The color of color tag resources in Android Studio is greyed out for all color schemes but Default Theme. I can't find any solution on google, since you know, it's quite complicated.

### Expected behavior
Here is the screenshot of Default Theme (No Issue)
![image](https://user-images.githubusercontent.com/4467386/33288764-f295cb72-d3ef-11e7-95f3-d33d3788b611.png)

### Actual behavior
3 other color schemes

Lighter:
![image](https://user-images.githubusercontent.com/4467386/33289485-4c66ee68-d3f2-11e7-8934-5d89662a2469.png)

Darker:
![image](https://user-images.githubusercontent.com/4467386/33288820-241f0a8c-d3f0-11e7-9602-cbf96847f478.png)

Palenight:
![image](https://user-images.githubusercontent.com/4467386/33288879-513bfd04-d3f0-11e7-91ed-77d30c84cf75.png)

### Steps to reproduce
I don't know how, it just happened. I did try to Restore Defaults, didn't work. Tried several times to make sure, even I did restart my Android Studio IDE after Restore Defaults.
The weird thing is, when I launched Android Studio and it was still building gradle and stuffs, the color tag had colors.
![image](https://user-images.githubusercontent.com/4467386/33289911-a3abb784-d3f3-11e7-9c0c-4d874761d230.png)

After completed the initial build, it got greyed out again. And it only happens specifically for color tag only. I have 11  other color schemes installed on my Android Studio, there's no issue for any other color scheme but those 3 (Palenight, Darker, Lighter). 

### Environment
OSX El Capitan, Android Studio 3.0.1 stable. Plugin version 1.3.4
![image](https://user-images.githubusercontent.com/4467386/33289208-67421268-d3f1-11e7-9a7c-6dce6457aae3.png)

**Comment by mallowigi** [comment]
I fixed it in one of the latest releases. Basically you need to reset the color schemes and it should be okay

**Comment by td0** [comment]
Turned out I need to reinstall the Material Theme plugin to fix it. Restoring the color scheme to default didn't help.

Thanks anyway, you can close this issue
