### ISSUE TITLE
Font color merges with tabs (module settings in AS) + gradle

### ISSUE THREAD

**Issue by objaa** [ChrisRM/material-theme-jetbrains#52]
subject:

![](http://i.imgur.com/yHbrORY.png)

![](http://i.imgur.com/rEo1B0t.png)

and in gradle bug with themes:
dark theme:
![](http://i.imgur.com/SM6oeFT.png) 
default theme (without bug)
![](http://i.imgur.com/JnUXxm6.png)

i set def. theme + def font colors. ;o

**Comment by ChrisRM** [comment]
I don't think I have access to those tabs, so I'm unable to set the color. And yeah, the darker theme is not yet finished.
