### ISSUE TITLE
Does it work on 2017.3 ?

### ISSUE THREAD

**Issue by Izopi4a** [ChrisRM/material-theme-jetbrains#520]
Hi, i am thinking that i am doing something wrong... 

and dont get me wrong, 2017.3 was really just released but the plugin is enabled and my material styles are missing ? Its like the plugin is not even installed.

ubuntu 16.04
phpstorm 2017.3
EAP version of the plugin 1.3.0

again... it could be me, doing something wrong ?

Sorry for the spam if its my bad

**Comment by mallowigi** [comment]
Yes it should be working. What styles are you talking about? There should still be the popup on the toolbar

**Comment by Izopi4a** [comment]
i am seeing the Darcula theme nothing more.

In appearance & behavior there is no material theme option, which was there before the upgrade.

If you have any idea what i broke just pressing upgrade on my phpstorm i will be more than happy

**Comment by Izopi4a** [comment]
oh ok i got it.

after uninstalling the plugin, when I search for material theme, a new one pops in the results, where the version is 1.3.7

something went wrong somewhere i guess.. it used to say "Material theme EAP"

sorry, i am still confused what really happen for me,but i blame the ubuntu and the storm. 

sorry again. Have a nice evening/day.

**Comment by mallowigi** [comment]
Yep I removed the EAP from the repository
