### ISSUE TITLE
Android Studio DPI Scale Issue(Error)

### ISSUE THREAD

**Issue by onatakduman** [ChrisRM/material-theme-jetbrains#523]
### Expected behavior

This [image](https://i.hizliresim.com/4GvWAY.png) from Intelij IDEA, it has expected appearance. Icons and texts has normal size. 

### Actual behavior

This [image](https://i.hizliresim.com/0GoWXV.png) from Android Studio, the plugin disrupt the text sizes and icons of Android Studio. And I don't know reason of bug, because there is not a error. I changed DPI scale of Windows and it still continued. Also I tried to Ignore the High DPI Scaling but doesn't affect it.

### Environment

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="1.3.7" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="defaultBackground" value="https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-eap/master/src/main/resources/themes/wall.jpg,60" />
  </component>
</application>

```

**Comment by mallowigi** [comment]
Have you tried without the plugin?

**Comment by onatakduman** [comment]
Yes, I tried and it has normal DPI scale without plugin. So I was format the computer yesterday. It’s OK now. I think the updates of android studio may have corrupted files. but I have tried to delete and reload the android studio and settings files before also.

**Comment by mallowigi** [comment]
i also experienced issues with Android Studio but as far as I know nothing I did could have changed this behavior. So can I close it?

**Comment by onatakduman** [comment]
Yes, you can and thanks.
