### ISSUE TITLE
AS cannot load plugin when starts up

### ISSUE THREAD

**Issue by elementlo** [ChrisRM/material-theme-jetbrains#524]
the new version 1.3.9 cause a problem when I start AS, it says something wrong with the plugin manager and alert a dialog , after that nothing will continue working , like below.
![image](https://user-images.githubusercontent.com/10020581/33695094-6113fb76-db36-11e7-9a39-e27f113eeaeb.png)

**Comment by vdelricco** [comment]
Same issue for me after upgrading to 1.3.9.

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

**Comment by ending0421** [comment]
Same issue for me 

Android Studio 3.0.1
Build #AI-171.4443003, built on November 10, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
Plugin version 1.3.9

**Comment by tnaffh** [comment]
Same issue for me here too after updating the plugin

`Mac (High Sierra)
Android Studio 3.0.1`

![screen shot 2017-12-07 at 3 56 25 pm](https://user-images.githubusercontent.com/9331942/33718777-4dbd3840-db67-11e7-81e7-c628bd61323b.png)
