### ISSUE TITLE
Fatal error initializing plugin com.chrisrm.idea.MaterialThemeUI

### ISSUE THREAD

**Issue by voiddog** [ChrisRM/material-theme-jetbrains#525]
### Summary
Android Studio 3.0.1 update theme plugin version to 1.3.9, then catch error:

> Cannot load project:
> com.intelij.ide.plugins.PluginManager$StartupAbortedException:
> Fatal error initializing plugin com.chrisrm.idea.MaterialThemeUI

### Environment

* Android Studio 3.0.1
* Build #AI-171.4443003, built on November 10, 2017
* JRE: 1.8.0_152-release-915-b08 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Mac OS X 10.13.1
* Plugin version: 1.3.9

**Comment by yzyDavid** [comment]
Linux 4.13.13, with all other same config, also encoutered this problem.

**Comment by jitkang** [comment]
I am using Windows 10 here with PHPStorm. IDE crashed after restart with update version 1.3.9.

**Comment by mallowigi** [comment]
Got the issue as well. I'm investigating.

**Comment by queiroz** [comment]
Just followed an update and found the same issue 👍

**Comment by Rock610** [comment]
Got the issue as well.just following

**Comment by davilinho** [comment]
I can't open Android Studio! (Mac OSX High Sierra)

**Comment by voiddog** [comment]
My solution is that uninstall 1.3.9 and download 1.3.7 to install it .

**Comment by davilinho** [comment]
Meanwhile I’ve uninstalled it, and when it’s fixed, I’ll install again

**Comment by HugoCastelani** [comment]
Happens with me as well.

**Comment by mallowigi** [comment]
Finally found the time to fix it! Please download latest version (1.4.0)

**Comment by Windrushfarer** [comment]
Version 1.4.0 now working for me. Same error. I'm using WebStorm 172.4 and MacOS High Sierra.
Also I can't download plugin in Preferences only manually.
