### ISSUE TITLE
enhance Active Tab Highlight color

### ISSUE THREAD

**Issue by yuxh** [ChrisRM/material-theme-jetbrains#526]
1. Active Tab Highlight color doesn't change tab background, even in contrast mode the active tab not stick out enough especially the  bottommost one.

https://github.com/ChrisRM/material-theme-jetbrains/issues/164#event-623763919

### Summary

...

### Environment
IntelliJ IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.127, built on November 27, 2017
Subscription is active until January 30, 2018
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Windows 10 10.0
material theme 1.3.9

**Comment by mallowigi** [comment]
This is in order to comply with the File Colors Settings where you can change tab colors for certain files. I am not going to change this unless you have a better doable idea.

**Comment by yuxh** [comment]
ok,I turn on "use in Editor Tabs" in File colors settings,and change corresponding theme Local colors. It seems better
