### ISSUE TITLE
Right hand ruler is always shown

### ISSUE THREAD

**Issue by jgwconsulting** [ChrisRM/material-theme-jetbrains#528]
### Summary
When the Material UI plugin is installed a right hand margin rule is always shown, regardless of settings. (Toggle Material Theme makes no difference). Uninstalling the plugin resolves this issue. 

This is a recent change in behaviour for me, as of WebStorm 2017.3

![image](https://user-images.githubusercontent.com/1101369/33762598-02afbe4c-dc05-11e7-87a3-512c176e72de.png)

### Expected behavior
Right hand margin ruler should not be shown unless WebStorm is configured to show it.

### Actual behavior
Right hand margin ruler is always shown when the plugin is installed.

### Environment
WebStorm 2017.3
Build #WS-173.3727.108, built on November 25, 2017
Licensed to Jerome Wilson
Subscription is active until June 7, 2018
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Settings file: https://www.dropbox.com/s/ufu05g5z34z3pz4/settings.jar?dl=1

IDE Info:
Custom plugins: [CMD Support (1.0.5), Database Navigator (3.0.7621.0), Material Theme UI (1.3.7), Ini4Idea (173.3727.84), .ignore (2.3.2), BashSupport (1.6.12.173), HashiCorp Terraform / HCL language support (0.6.9.1), Markdown support (173.2696.26), AWS CloudFormation (0.5.41)]
Disabled plugins:[AWS Elastic Beanstalk Integration for Web Languages (0.8.7), Markdown Navigator (2.3.1)]
Build version: WebStorm 2017.3 Build #WS-173.3727.108 November 25, 2017
Java version: 1.8.0_152-release-1024-b6amd64
Operating System: Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

**Comment by mallowigi** [comment]
Editor > General > Appearance > "Show Hard Wrap Guide"

**Comment by jgwconsulting** [comment]
Hi, thanks for looking at this so quickly :) I'm loving the plugin - makes WebStorm even more of a pleasure to use.

I already have that settign turned off, I'm afraid:

![image](https://user-images.githubusercontent.com/1101369/33763976-6e2d10b6-dc0a-11e7-9aa2-0dc4a83f4bbf.png)

**Comment by jgwconsulting** [comment]
I raised it initially with JetBrains, thinking it was related specifically to .test.ts files (at this point I was using the EAP of the plugin). Having uninstalled and reinstalled the (this time non-EAP version) plugin it's happening on all file types.

https://youtrack.jetbrains.com/issue/WEB-30008

**Comment by mallowigi** [comment]
Editor > Code Style > Visual Guides maybe ?

**Comment by jgwconsulting** [comment]
No, that doesn't seem to have any effect, I'm afraid. 

As there's no one else reporting this problem I guess it's a weird edge case to do with my particular environment / conflicts with other plugins maybe? Anyway, it's not a massive issue. At some point I'll take some time to uninstall all other plugins and see if that helps, then report back.

**Comment by mallowigi** [comment]
At the very least you can set the color of the margins to the background color inside Color Scheme > General > Editor > Guides > Visual Guides

**Comment by jgwconsulting** [comment]
That's a cunning plan! Thank you :)
