### ISSUE TITLE
Git: ignored files and not modified files are very similar color

### ISSUE THREAD

**Issue by pavlovskyarto** [ChrisRM/material-theme-jetbrains#529]
Hello. Colors issue. Material oceanic.
Screenshot:
http://joxi.ru/MAj3VpWF4l090r

**Comment by mallowigi** [comment]
I know. I don't know what color to set to ignored files.

**Comment by SunDwarf** [comment]
It'd be nice if the ignored files had the current colour, and the normal files were just simply a lighter white. I cannot tell them apart on my installation at all.

**Comment by mallowigi** [comment]
I changed them to a brown color for now. And there is no way I will set the file color to white, sorry.
