### ISSUE TITLE
Incomprehensible words after installing "Material Theme UI" on Webstorm 2017.3

### ISSUE THREAD

**Issue by dark06** [ChrisRM/material-theme-jetbrains#530]
### Summary

Incomprehensible words after installing "Material Theme UI"

### Expected behavior

Webstorm with Material Theme and english words

### Actual behavior

Webstorm with Material Theme but incomprehensible words 

### Steps to reproduce

1. Open Webstorm 2017.3
2. Click on "File" > "Settings"
2. Navigate to "Plugins"
3. Click "Browse repositories..."
4. Search for "Material Theme UI"
5. Install and restart Webstorm.

![screenshot](https://user-images.githubusercontent.com/28400414/33856135-6924e17e-dec7-11e7-86c6-190d20ef3ec0.JPG)

### Environment
WebStorm 2017.3
Build #WS-173.3727.108, built on November 25, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
#442
