### ISSUE TITLE
Use modified TextFieldWithPopupHandlerUI API

### ISSUE THREAD

**Issue by kkmic** [ChrisRM/material-theme-jetbrains#533]
https://github.com/ChrisRM/material-theme-jetbrains/blob/1056ce1dbbdbdf8fe59704f83931809a81354e5d/src/main/java/com/chrisrm/idea/ui/MTTextFieldUI.java#L48
Please use new API for TextFieldWithPopupHandlerUI.  It doesn't have a parametrized constructor since 181. There is only the default one. Neither it has myTextField. To refer to the text field please use protected BasicTextUI.getComponent() method.

**Comment by mallowigi** [comment]
Thanks for the update

**Comment by mallowigi** [comment]
@kkmic do you know how can i do to support both versions? Or can you reinstall the default constructor ?

**Comment by kkmic** [comment]
By default do you mean the one with JTextField ? Theoretically yes, I can leave this constructor as a deprecated no-op constructor because the field is redundant. 
Can you create a new version of you LaF for 181 ? I can give you exact build number since which the API change had happened.

**Comment by mallowigi** [comment]
I want to be able to have the versions prior to 181 still work with the refactor. Changing to getComponent is a no-brainer but for the constructor disappearance I cannot fix it easily, and if possible I don't want to deploy two versions of the plugin for 181+ and one for below.

**Comment by mallowigi** [comment]
By the way, I'd love if you can remove this weird condition:

https://github.com/JetBrains/intellij-community/blob/master/platform/platform-api/src/com/intellij/ui/SearchTextField.java#L119

Why bother if I'm on mac or not? Can't you just use the regular TextFieldUI for the search input?

**Comment by kkmic** [comment]
We put ourselves carrying around a bunch of deprecated code then. There is the same issue for DarculaComboBoxUI which accepts a JComboBox. I tend to delete the constructor. 
Actually KB suggested that I contact with you and rise this cleanup as a git issue. What's the burden of having two versions ?
Regarding SearchTextField. It's another issue. And as you might have seen the class doesn't extend JTextField and they are setting a TextFieldUI/Border to a non text field component. We'll probably re-engineer this.

**Comment by mallowigi** [comment]
Alright keep me informed. For now I'll wait until 181 is down to do this.

The problem about the versioning is that I can't have 1.4.1 that have since-build 171 and another 1.4.1 with a since-build 181...

If I might, when you're rewriting stuff, please use UIManager to retrieve properties instead of hardcoded colors. It would be much simpler for me :)

**Comment by kkmic** [comment]
Why should you care about 171 after all ?
I'll keep in mind your request at least for Darcula.
As of Window/Mac themes, we have a team of designers that specify colors so using them directly.

**Comment by mallowigi** [comment]
That is appreciated. I look further to see the new stuff on the new EAP.
