### ISSUE TITLE
Disable dark titlebar

### ISSUE THREAD

**Issue by JSteitz** [ChrisRM/material-theme-jetbrains#537]
Like the title, how do I disable this feature?
I have a Dark Theme on, but I don't want the Titlebar being dark.

> Experimental feature to set a dark title bar on Mac for Dark themes (only for last EAPs)

**Comment by mallowigi** [comment]
Fine, I'll add a setting for it.

**Comment by JSteitz** [comment]
Thank you very much.
Great work here.
