### ISSUE TITLE
MoveTabRight does not move the cursor to the new split

### ISSUE THREAD

**Issue by cjongseok** [ChrisRM/material-theme-jetbrains#538]
### Summary
MoveTabRight (Window -> Editor Tabs -> Move Right), which moves the current file to the new vertical split, does not move the cursor to the new split.
In editor's default theme, MoveTabRight moves its cursor to the new split.

### Expected behavior
new split + cursor on the NEW split

### Actual behavior
new split + cursor on the EXISTING split
(It seems that MoveTabRight moves the cursor to the new split, but the cursor comes back to the original split immediately. I belive Material Theme sets the cursor to the original split after splitting)

### Steps to reproduce (if needed)
1. Set color scheme as Material Oceanic
2. Open two+ files
3. Do MoveTabRight
Then you can see the view as below.
On MoveTabRight, the cursor(small yellow) moves to the highlited line in the right split(new split), but comes back to the one in the left split(original split), immediately.
<img width="1677" alt="screen shot 2017-12-17 at 1 39 28 pm" src="https://user-images.githubusercontent.com/15207721/34076615-c879f26a-e32f-11e7-9037-024421c99e79.png">

For the comparison, I tested MoveTabRight with Default color scheme.
You can see the cursor(small black) is on the new split.
<img width="1678" alt="screen shot 2017-12-17 at 1 37 33 pm" src="https://user-images.githubusercontent.com/15207721/34076599-8b4e1862-e32f-11e7-92c8-adbfb7e88a86.png">

### Environment
GoLand 2017.3
Build #GO-173.3727.144, built on November 30, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

Material Theme UI
version: 1.4.2
configuration:
[material_theme.xml.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/1565325/material_theme.xml.txt)

enabled plugins:
* Docker integraion
* IdeaVim
* Markdown support

**Comment by mallowigi** [comment]
I just tried and it works ok... You probably have something that messes it up. Try to disable IDEAVim and tell me the results
