### ISSUE TITLE
Bold and enlarged fonts on project window.

### ISSUE THREAD

**Issue by jumangitjs** [ChrisRM/material-theme-jetbrains#541]
### Summary
After installing the most recent update, i seem to have enlarged fonts in the project window.
I tried toggling bold directories, nothing changes

### Environment
Windows 10 1709
Intellij 2017.3.1

![image](https://user-images.githubusercontent.com/28138385/34153159-1311459a-e4ec-11e7-8183-4b13c9f20289.png)

**Comment by mallowigi** [comment]
It's the recent update changes. If you want to disable it turn on "Custom Sidebar Height" and set a height lower than 28. Or disable Material Theme styles.

**Comment by jumangitjs** [comment]
so does this mean if i don't like the bold fonts for the project tree, i have to uninstall material theme itself? that's sad. i've been using this for a while and also i can't seem to install older versions.

**Comment by mallowigi** [comment]
It's not bold fonts, it's slightly larger fonts. Besides, what do you mean you cannot install lower versions?

**Comment by mallowigi** [comment]
Bold fonts come from the "bold directories" option.

**Comment by jumangitjs** [comment]
i tried installing older versions of this via downloading the jar itself in the jetbrains site.

current config, also tried restarting multiple times
![image](https://user-images.githubusercontent.com/28138385/34155938-1aebda50-e4f6-11e7-9494-2fd6f1e42bef.png)

**Comment by mallowigi** [comment]
That's weird. I'll take a look

**Comment by jumangitjs** [comment]
thank you! your effort is highly appreciated.

**Comment by mallowigi** [comment]
I've fixed the bold directories option, but as far as I know if you disable it you will not get bold directories.

You will still get the bigger fonts though, but I think it's better this way. If you don't want it, please set the "Custom sidebar height" to a number less than 28.

**Comment by dirkniblick** [comment]
I installed this plugin into Intellij IDEA 2017.3.1 and realized I didn't care for how it looked.  I uninstalled the plugin and the fonts in my tool windows, specifically the Project one, **remained** enlarged (honestly this is what turned me off to the plugin) even after restarting Intellij and my Windows 10 1703 PC.  I ended up reinstalling IDEA and the fonts went back to normal.

**Comment by mallowigi** [comment]
It shouldn’t. I need to check why it’s the case. Thanks for the tip.
