### ISSUE TITLE
Tab text color (and tree active files color)

### ISSUE THREAD

**Issue by alexraileanu** [ChrisRM/material-theme-jetbrains#542]
### Summary

Which is the option to change the colors for the tab text color and the active items (so non-ignored (using the .ignore plugin)) in the tree view?

Screenshots:

The non-ignored files are the grey ones and the ignored files are colored blue. This is counter intuitive and I would like to change it but I can't find the option.
<img width="243" alt="screen shot 2017-12-19 at 14 49 29" src="https://user-images.githubusercontent.com/2884755/34160087-dac147aa-e4cb-11e7-8d91-137a7791089c.png">

Same here. The ignored file is actually brighter than the non-ignored one.
<img width="238" alt="screen shot 2017-12-19 at 14 50 56" src="https://user-images.githubusercontent.com/2884755/34160150-0cc45896-e4cc-11e7-985f-e63c3159d79c.png">

Thanks.

**Comment by mallowigi** [comment]
Git ignored files should be brown, verify that you have the latest update of the color scheme

**Comment by alexraileanu** [comment]
I have the latest updates for both Material Design and the .ignore plugin.

**Comment by mallowigi** [comment]
Ok can you check inside your color schemes folder if there is a copy of the material themes?

**Comment by mallowigi** [comment]
And if you have, please delete them and restart the IDE. Ignored files should be brown.

**Comment by alexraileanu** [comment]
Ok. I did all those steps and I further investigated and it seems like you are indeed correct. It does show the correct behaviour now but the colors are still wrong. This is likely something on the .ignore plugin so I will check there.

Thanks again :).

**Comment by mallowigi** [comment]
Can you try to delete the copy of Darcula in the color schemes as well? It could be because of it

**Comment by alexraileanu** [comment]
Thanks a lot, @mallowigi ! It seems to have fixed the issue!

**Comment by alexraileanu** [comment]
@mallowigi I'm bothering you again with this issue. It has reappeared once again. If I follow the steps above and I change my font from the default Fira Code to anything else (from Editor -> Color Schemes -> Color Scheme Font) the issue reappears. Any ideas?

**Comment by alexraileanu** [comment]
Nevermind! This was my mistake and I'm sorry for any confusion I might have caused. The way I fixed it was by changing the color to what I wanted in Editor -> Color Scheme -> Material File Colors and I changed the 'Ignored (.ignore plugin)' color to grey as it was before. Thanks again, @mallowigi
