### ISSUE TITLE
Button text and all main programm is unreadble

### ISSUE THREAD

**Issue by vaqif14** [ChrisRM/material-theme-jetbrains#544]
Button text and all main programm text is unreadble 
![12](https://user-images.githubusercontent.com/19408818/34171067-1dafeef4-e4fe-11e7-8da2-f4b2e57c5bc3.png)

**Comment by mallowigi** [comment]
Please download Roboto from here https://material.io/guidelines/resources/roboto-noto-fonts.html and tell me the results

**Comment by vaqif14** [comment]
The litle fonts was readble when i installed font you linked all things go unreadble
![2017-12-19_22-07-55](https://user-images.githubusercontent.com/19408818/34174203-356947c4-e509-11e7-90e1-21e9caf9dcb4.png)

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/377

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/373

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/387

**Comment by mallowigi** [comment]
This issue keeps coming and I have no idea what is causing this.

**Comment by vaqif14** [comment]
No changes :(

**Comment by mallowigi** [comment]
Try to go to Settings > Appearance > Override default fonts (second checkbox) and set another font

**Comment by vaqif14** [comment]
i changed to Tahoma font and all works .Thanks
