### ISSUE TITLE
Bad rendering on hovering Tool windows

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#548]

**Comment by mallowigi** [comment]
Partly fixed: now you can choose whether to keep this hack through an action in the menu

**Comment by dudong0726** [comment]
the option is ineffective at all

**Comment by dudong0726** [comment]
the option to patch the window header tool is ineffective at all，pls reopen this issue！

**Comment by mallowigi** [comment]
I can’t. All of the solutions I tried turned out to fail. We will have to wait until JB decides to remove this hard coded color.

I will remove the faulty action and the hack altogether in a future version. So sad it doesn’t work :/

--
Elior
