### ISSUE TITLE
Dark Title Bar Custom Color

### ISSUE THREAD

**Issue by slovenianGooner** [ChrisRM/material-theme-jetbrains#550]
The Dark Title Bar setting is brilliant, but is it possible to change it to the color of the theme / or it should do that by default. That is how the transition between title bar and sidebar/editor would be really slick and sexy.

![screen shot 2017-12-20 at 10 52 28](https://user-images.githubusercontent.com/1257629/34201190-fb093f88-e573-11e7-8700-a5b6b4658e02.png)

Similar to what Code does.

**Comment by mallowigi** [comment]
You're right but currently there is no way. If you want to know this is something that Jetbrains is planning for 2018.1 but as far as I saw in the code the only option is to to set it dark.

I don't even know if they are planning to release it to the public, but if they do I'll see if we can do more than that.
