### ISSUE TITLE
Icon directories

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#554]
A good feature would be to be able to have more directory icons - for example tests with a test icon, angular projects with an angular icon, ruby projects with a ruby icon and so on.

**Comment by mallowigi** [comment]
If someone is kind enough to make an icon directory for Ruby, Python, Scala and PHP that would be appreciated :)

**Comment by azdanov** [comment]
What should be the main color for the folder? Or each folder will have unique color. For example PHP and Python blue, Scala and Ruby red.

| @1x | @2x |
| ------------- |:-------------:|
| ![filderphp](https://user-images.githubusercontent.com/6123841/36311065-b76a345c-1332-11e8-86a9-73ab9c14c15b.png) | ![filderphp 2x](https://user-images.githubusercontent.com/6123841/36311080-c5fb4998-1332-11e8-861d-0ddf473996d6.png) |

**Comment by mallowigi** [comment]
It should be the same color as the usual icon, e.g. PHP is violet, Scala is Brown, Python yellow, Ruby red.

I think Kotlin should be done as well, but I'm not sure. I havent thought a lot about the question, just that it depends on the inherent plugin whether they changed the icon or not. I know that those ones did, but Java/Javascript did not. I need to think about Android Studio as well, even though for some reason I didn't managed to get the source code for it.

**Comment by azdanov** [comment]
Another try. Doesn't look that good.
Probably will try with purple folder icon, and php word with background overlay.

| Closed | Open|
| ------------- |:-------------:|
| ![folder-closed 2x](https://user-images.githubusercontent.com/6123841/36314070-59f5c476-133c-11e8-97cd-e24e350af731.png) | ![folder-open 2x](https://user-images.githubusercontent.com/6123841/36314081-6325b966-133c-11e8-9c81-dfe41b76b348.png) |

**Comment by azdanov** [comment]
| Closed |
| ------------- |
| ![php 2x](https://user-images.githubusercontent.com/6123841/36314464-a3c46304-133d-11e8-89c0-4f024f6d393c.png)|

**Comment by mallowigi** [comment]
Yes I like that! Note that you probably don't need to do for open/closed state. It doesnt matter much since it appears at the toplevel of the project, the rest of the icons will behave regularly (open/closed/excluded/sources/tests etc)

**Comment by azdanov** [comment]
Ok, will be adding icons in new comments as I finish them.

PHP:

| @1x | @2x |
| ------------- |:-------------:|
|![php](https://user-images.githubusercontent.com/6123841/36317724-8de6ae6c-1346-11e8-95cf-27b709f7c747.png) | ![php 2x](https://user-images.githubusercontent.com/6123841/36317725-8e0ea156-1346-11e8-9d79-c12ca42e6690.png) |

**Comment by azdanov** [comment]
Suggestions are welcome.

Python:

| @1x | @2x |
| ------------- |:-------------:|
|![python](https://user-images.githubusercontent.com/6123841/36319155-b896ec0e-134a-11e8-8522-7e6a24092527.png) |![python 2x](https://user-images.githubusercontent.com/6123841/36319153-b87b6196-134a-11e8-874e-1c60d2f77f93.png) |

**Comment by mallowigi** [comment]
I like the icon with the two colors !

**Comment by mallowigi** [comment]
With no outline though

**Comment by azdanov** [comment]
Ruby:

| @1x | @2x |
| ------------- |:-------------:|
| ![ruby](https://user-images.githubusercontent.com/6123841/36325931-0359338e-1362-11e8-8341-8644078a4552.png) | ![ruby 2x](https://user-images.githubusercontent.com/6123841/36325930-033ae8f2-1362-11e8-8db4-25a98031a156.png) |

**Comment by azdanov** [comment]
Kotlin:

| @1x | @2x |
| ------------- |:-------------:|
| ![kotlin](https://user-images.githubusercontent.com/6123841/36328064-6e706f3c-1369-11e8-967a-5f9909c81971.png) | ![kotlin 2x](https://user-images.githubusercontent.com/6123841/36328065-6e8e2f22-1369-11e8-88c2-75dc482d597c.png) |

**Comment by azdanov** [comment]
What color should Scala folder be?
Original logo is [red](https://www.scala-lang.org/).
But in source files it is green.

**Comment by mallowigi** [comment]
I think red is good. I need to change the default color as well.

**Comment by azdanov** [comment]
Scala:

| @1x | @2x |
| ------------- |:-------------:|
| ![scalafolder](https://user-images.githubusercontent.com/6123841/36329593-2fe78c4a-136f-11e8-9119-bbe4ffec4eaa.png) | ![scalafolder 2x](https://user-images.githubusercontent.com/6123841/36329594-3008425a-136f-11e8-90dc-94e499df77ca.png) |
| ![scalaicon](https://user-images.githubusercontent.com/6123841/36329595-3025e3b4-136f-11e8-8977-891350a94bc5.png) | ![scalaicon 2x](https://user-images.githubusercontent.com/6123841/36329596-3047c060-136f-11e8-86db-c664b6661fcb.png) |

**Comment by mallowigi** [comment]
This is not a good red, please use #FF5370

**Comment by mallowigi** [comment]
Hey @azdanov ! I've been trying to impleement this for a while and currently i couldn't find a way to "mark" projects, there is no indication whatsoever of what kind of project we are.

So my second approach would be an associations-like approach, e.g. specific folder names being replaced. Common folder names are usually found:
- config
- log
- vendor
- node_modules
- bower_components
- db
- assets
- js/javascript/scripts
- styles/css/stylesheets
- views/templates
- lib
- dist
- tmp
- public
- migrate

WDYT?

**Comment by azdanov** [comment]
Yep, @mallowigi, I think it is a sound approach, many other editors have plugins that target specific directory names.

For example: [visual studio code](https://github.com/PKief/vscode-material-icon-theme/blob/d34d1f22ed6c902c1786bd71ccb779ab8b755287/src/icons/folderIcons.ts#L24) and [atom](https://github.com/file-icons/atom/blob/952a1b34fdba4162bfcafe760e236698aa49b657/lib/icons/.icondb.js#L17).

I think it will be a good idea to use what they have already implemented (if possible) and add what is needed on top of that.

**Comment by mallowigi** [comment]
Great resource thanks!
