### ISSUE TITLE
material component button click behavior

### ISSUE THREAD

**Issue by phisch** [ChrisRM/material-theme-jetbrains#561]
### Summary
The material button component has a weird behavior when being drag-clicked. If you press and hold the mouse button on a button, then drag the mouse off the button and release the click, the button still fires the click event.

The default components used by jetbrains don't do that, they do not fire a click event after dragging and releasing off the button.

### Expected behavior
No click fired.

### Actual behavior
Click fired.

### Steps to reproduce (if needed)
1. open settings
2. click and hold the left mouse button on "OK"
3. drag the cursor off the button
4. release the mouse click

-> settings window is now closed due to a fired click event on the "OK" button

![material-button-click-event](https://user-images.githubusercontent.com/1282767/34484600-f8c4fd50-efc5-11e7-9f96-8fe3b3182eb7.gif)

### Environment
PhpStorm 2017.3.2
Build #PS-173.4127.29
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.9-1-ARCH

Material Theme UI Version: 1.5.1.2

**Comment by mallowigi** [comment]
I knew about this but I didn't know that the usual buttons don't do that.

I'll check

**Comment by mallowigi** [comment]
Fixed on 1.5.2.2
