### ISSUE TITLE
material component button highlight color

### ISSUE THREAD

**Issue by phisch** [ChrisRM/material-theme-jetbrains#562]
### Summary
When hovering a material component button, the color briefly changes to `Button Highlight Color` and shortly after that to `Active Component Colors`. The reverse happens once the cursor leaves the button (drag-out).

### Expected behavior
I am not sure if some behavior has been defined for this, but i would say:
Keep the `Button Highlight Color` while hovering, change to `Active Component Colors` while the mouse button is held down.

### Actual behavior
See [summary](#Summary)

### Steps to reproduce (if needed)

1. set distinct colors for `Button Highlight Color` and `Active Component Colors` (e.g. yellow and pink)
2. hover a material component button

![material-button-hover-colors](https://user-images.githubusercontent.com/1282767/34484780-70a95a54-efc7-11e7-8fd9-24e80e405cb4.gif)

### Environment

PhpStorm 2017.3.2
Build #PS-173.4127.29
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.9-1-ARCH

Material Theme UI Version: 1.5.1.2

**Comment by mallowigi** [comment]
Yeah the behavior is not that good. I will change the behavior soon to use a darker color of the Active Component color and maybe even introduce a better animation.

**Comment by mallowigi** [comment]
Should be better from 1.5.2.2

haven't tested in all themes, hope it's good ^^'

**Comment by phisch** [comment]
This is way more intuitive and polished!
