### ISSUE TITLE
main menu font size changes when applying custom theme settings

### ISSUE THREAD

**Issue by phisch** [ChrisRM/material-theme-jetbrains#564]
### Summary
Pressing "OK" in the settings panel will switch the main menu font size whenever the `Material Custom Theme` section was selected prior, no matter if no actual settings where touched.

Let me know if this might be a setup based problem, which needs some more information to be solved.

### Expected behavior
Font size stays the same.

### Actual behavior
Font size changes.

### Steps to reproduce (if needed)
1. open the settings panel (Ctrl+Alt+S)
2. select `Appearance & Behavior -> Material Custom Theme`
3. press the "OK" button

![font-size-switch](https://user-images.githubusercontent.com/1282767/34504566-93cb38c4-f01f-11e7-9026-2434132474ab.gif)

### Environment

PhpStorm 2017.3.2
Build #PS-173.4127.29
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.9-1-ARCH

Material Theme UI Version: 1.5.2.2

**Comment by mallowigi** [comment]
I know about this, I haven't been able to find a solution for this up to now but I'll try again.
