### ISSUE TITLE
Missing selection color in rename dialog for Arc-Dark theme

### ISSUE THREAD

**Issue by jopohl** [ChrisRM/material-theme-jetbrains#566]
### Summary
When using the Arc-Dark theme the selection in rename refactoring dialog (Ctrl+F6) is colored in a way that is very hard to differ from normal background.

### Expected behavior

Selection should be colored in normal selection color.

### Actual behavior

Selection is not colored in normal selection color (see screenshot)
![rename](https://user-images.githubusercontent.com/18219846/34570045-e4bcdf34-f16a-11e7-9e42-9d3d3346469a.png)

### Environment

Plugin Version: 1.5.2.2
PyCharm 2017.3.2 (Professional Edition)
Build #PY-173.4127.16, built on December 18, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.10-2-MANJARO

**Comment by mallowigi** [comment]
fixed

**Comment by jopohl** [comment]
Much better, thanks!
