### ISSUE TITLE
MTJ incompatible with Jetbrains IntelliJ 2017.3.2

### ISSUE THREAD

**Issue by FerusGrim** [ChrisRM/material-theme-jetbrains#567]
### Summary

Material Theme UI EAP is [incompatible with IntelliJ 2017.3.2](https://i.imgur.com/O7n47az.png).

### Environment

IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 25, 2017
Licensed to Nicholas Badger
You have a perpetual fallback license for this version
Subscription is active until June 4, 2019
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
The EAP has been removed from the repository. Please use the Material UI plugin

**Comment by FerusGrim** [comment]
I didn't even notice! :D

Is there a good way to keep up-to-date on these kinds of important changes, other than periodically checking the plugin page?
