### ISSUE TITLE
Highlight text background color

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#57]
I have "modified" my local installation theme to show the highlighted text with a different background color.  Just wanted to throw it out there, maybe something can be done to the default installation so that this can be done already

**Comment by ChrisRM** [comment]
Highlighted text has a different background color by default. Do you mean the current caret line?

**Comment by mikeerickson** [comment]
Not exactly, I am referring to highlighted text (either within current line or anywhere else).   Perhaps the highlighted text default background was not different enough from canvas background?   I can send you a screenshot of before and after (it is at home, not there right now)

**Comment by ChrisRM** [comment]
Please do :+1:

**Comment by mikeerickson** [comment]
I have a screenshot from my Windows machine here at work.   The first require command is hlghlighted but very difficult to differentiate between background color and highlighted text

![highllighted-require](https://cloud.githubusercontent.com/assets/183153/10434934/9ad9f3c8-70d1-11e5-80a4-66d6c886ff22.png)

**Comment by mikeerickson** [comment]
In addition, trying to figure out where the comment color is defined.   They too are difficult to read so I want to change the foreground color of all comments?

Let me know if you need anything else...

**Comment by mikeerickson** [comment]
One more item.,..

In order to change the background color of highlight text, I select the `Background` checkbox, however, the area where the color should appear is very difficult to read because it so close to canvas background.   So you will just have to click around where the picker SHOULD be to find it :-)

**Comment by ChrisRM** [comment]
Oh, the darker theme isn't done yet. The default theme should be better :-)

**Comment by mikeerickson** [comment]
Ahhhhhh, ok!  Sorry about that :-)  

FWIW, it was quite easy to color (I used 657661 instead of 444444) had to update for PHP and JS code.

I have a vision issue (problems with white background, contrast) so I have to use dark themes OR light themes, but then I have to invert colors.

If you want feedback when you get darker theme done, let me know.

Thx for info!

**Comment by mikeerickson** [comment]
@ChrisRM BTW, I dont know if you heard my other comment about this project, but I just wanted to say THANK YOU!  You've done an awesome job, my hats off to you!
