### ISSUE TITLE
icons are not replaced

### ISSUE THREAD

**Issue by DanielRuf** [ChrisRM/material-theme-jetbrains#577]
macOS 10.12.5
PhpStorm 2017.3.2

I tried several times but so far the Scss files and other icons are not replaced.

<img width="293" alt="bildschirmfoto 2018-01-08 um 18 04 15" src="https://user-images.githubusercontent.com/827205/34682488-5071f8c2-f49f-11e7-83b0-55f83f65e58d.png">

**Comment by mallowigi** [comment]
Are you sure you’re not on power save mode by chance? I’ve just found out that it cancels out icon providers

**Comment by DanielRuf** [comment]
I've disabled it now, uninstalled and reinstalled it and it is still the same. Some icons are replaced but not all.

**Comment by DanielRuf** [comment]
*it = the theme

**Comment by mallowigi** [comment]
Just to make sure: you need to be not on power save mode, have the material icons on and the files need to be indexed right? Other than that what plugins do you use?

**Comment by DanielRuf** [comment]
Regarding the indexing: I think it is not disabled but how could I make 100% sure it is active?

Power save mode is currently off.

The material icons in the theme settings were enabled by default.

Will provide a list of my plugins tomorrow.

**Comment by DanielRuf** [comment]
It seems they are now replaced after several restarts. I'll close this issue here.

**Comment by DanielRuf** [comment]
Thanks for the great support and theme as plugin.
