### ISSUE TITLE
patch windows header tool action is noneffective 

### ISSUE THREAD

**Issue by dudong0726** [ChrisRM/material-theme-jetbrains#581]
### Summary
the option to patch windows header tool is  noneffective at all
...

### Expected behavior
the windows header tool patch become effective
...

### Actual behavior
the option to patch windows header tool is  noneffective at all

...
IntelliJ IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.127, built on November 27, 2017

JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
plugin version 1.5.3.2

**Comment by mallowigi** [comment]
I will remove this action and the whole hack in a future version. The code is too buggy to be shipped like that.

By the event JB decides to let us patch this thing normally I will work a solution out. For now it’s better off table. Sorry 

You can try to reach out to them if you want to
