### ISSUE TITLE
Material Theme UI 与IntelliJ 2017.3.2不兼容。(Material Theme UI is incompatible with IntelliJ 2017.3.2.)

### ISSUE THREAD

**Issue by Alanlxh** [ChrisRM/material-theme-jetbrains#583]
### Summary

Opent  a  project which Files without icons.

### Expected behavior

Files with icons;

### Actual behavior

Files without icons;

### Steps to reproduce (if needed)

1. Open idea-2017.3.2 contains latest Material Theme UI  plugin

![image](https://user-images.githubusercontent.com/29367057/34817250-6be532a4-f6f2-11e7-9fe2-d33b633e9c9f.png)

**Comment by mallowigi** [comment]
Material Theme EAP is deprecated. Also if you dont have icons maybe you have the "hide file icons" option checked

**Comment by Alanlxh** [comment]
When uninstall this plugin ,idea works well.
![image](https://user-images.githubusercontent.com/29367057/34820997-3ca2edbe-f6fd-11e7-972e-9277671f1e2a.png)

**Comment by dudong0726** [comment]
EAP  插件已经废弃，使用 正式版本即可。Material Theme UI

**Comment by Alanlxh** [comment]
我标题写错了，我用的就是ui




| |
卢星晖
邮箱：luxinghuis@163.com
|

签名由 网易邮箱大师 定制

在2018年01月11日 21:34，dongdu 写道：

EAP 插件已经废弃，使用 正式版本即可。Material Theme UI

**Comment by dudong0726** [comment]
![image](https://user-images.githubusercontent.com/1704803/34828760-83bd5344-f719-11e7-89ca-422d78826f3f.png)

**Comment by Alanlxh** [comment]
你好，我这边打开项目的某个模块的文件时，这个模块就会高亮显示。还有一种情况，当我修改文件内容时，模块也会高亮显示。因此当模块高亮显示时，我会困惑，是因为哪种原因导致的高亮，如果您知道怎么解决，烦请指导，谢谢。

**Comment by mallowigi** [comment]
这是从功能，如果你不希望它取消选择该 "Project View Decorators" 选项

**Comment by mallowigi** [comment]
(this is autotranslated content ^^)
