### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by TartanLeGrand** [ChrisRM/material-theme-jetbrains#584]
Hello, there is a problem with language.

Version 1.5.3.2

Screen :

![image](https://user-images.githubusercontent.com/25587164/34820248-4608c2bc-f6c0-11e7-854e-95f1e4e8904e.png)

**Comment by mallowigi** [comment]
Was it working fine in the previous versions?

**Comment by TartanLeGrand** [comment]
Yes I never had problems with that.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/34826427-26281744-f6df-11e7-9a67-c95e4a398921.png)

Check override default fonts and select a font that works.

**Comment by TartanLeGrand** [comment]
![image](https://user-images.githubusercontent.com/25587164/34827623-0d9fb56e-f6db-11e7-86d5-abca67bbb6c9.png)
This is my settings

**Comment by simioluwatomi** [comment]
I can confirm this. I use both PhpStorm and Android Studio. Everything works fine on PhpStorm but Android Studio is messed up See attached screenshots

![whatsapp image 2018-04-10 at 23 02 32](https://user-images.githubusercontent.com/22191563/38586685-aa1649d6-3d16-11e8-9af1-1d31a69510d1.jpeg)
![whatsapp image 2018-04-10 at 23 10 22](https://user-images.githubusercontent.com/22191563/38586686-aaa08e16-3d16-11e8-92cb-071b4ff26132.jpeg)
