### ISSUE TITLE
Spread Operator, Ellipses, '...', etc. Formatted Incorrectly With Fira Code

### ISSUE THREAD

**Issue by embryCODE** [ChrisRM/material-theme-jetbrains#592]
### Summary

Blue formatting color on dot in JavaScript confuses the ellipses/three dots/spread operator in Fira Code. 

### Expected behavior

I'm assuming that three dots should have the blue color of single dots in JavaScript.

### Actual behavior

With ligatures off, we have this:

<img width="101" alt="screen shot 2018-01-18 at 7 03 49 am" src="https://user-images.githubusercontent.com/8334188/35099704-9d9da1a6-fc1e-11e7-8ba1-c3a0dd74ea23.png">

And with ligatures on, we have this:

<img width="109" alt="screen shot 2018-01-18 at 7 04 16 am" src="https://user-images.githubusercontent.com/8334188/35099717-aaa5dc92-fc1e-11e7-8666-0d92120cae4b.png">

Note, when disabling the blue color for "Dot" in JavaScript, everything works fine. After researching this issue in Fira Code, it seems that ligatures don't work between two highlighting colors. See https://github.com/tonsky/FiraCode/issues/402

Even without ligatures, it seems odd to me that the third of the three dots is blue while the first two are not.

**Comment by mallowigi** [comment]
What can I do? Ellipsis is a character while dot is a token of the language. And I will not change the color of the dot to white.

**Comment by mallowigi** [comment]
The spread operator is not themed in the IDE. If you want to open a bug for this, you can go to their YouTrack page.
