### ISSUE TITLE
Dark titlebar changes my windows' title bar color too

### ISSUE THREAD

**Issue by gencer** [ChrisRM/material-theme-jetbrains#594]
### Summary

Dark titlebar changes my windows' title bar color too.

### Expected behavior

Only IDE should have its own color for dark titlebar.

### Actual behavior

All windows (outside of IDE) becomes my IDE title color. I believe you play with windows native title bar APIs? If so, this affect all windows but not just IDE.

### Steps to reproduce (if needed)

1. Run IDE (RubyMine for my case). Unfocus then focus again.
2. Check other windows'es title bar. They will change to match IDE's color.

![image](https://user-images.githubusercontent.com/1711576/35117871-10676032-fca1-11e7-9ab9-2f37bf4fcd38.png)

### Environment

RubyMine 2017.3.2
Build #RM-173.4301.17, built on January 11, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/component-settings/#dark-title-bar

**Comment by LXGaming** [comment]
Ok, How do I turn this shit off?
I've turned off 'Dark title bar' in the IDE settings and changed Windows settings but the title bar still changes when I reopen the IDE.

It may look good in the IDE but it looks like absolute shit in every other program, This 'feature' should be opt-in if it's modifying OS level settings.

**Comment by gencer** [comment]
@LXGaming, yeah, that was my actual intention on this issue but it gets closed :) 

@mallowigi, after we open a project (after the welcome screen disappears and IDE gets opened), dark title bars comes again even if we disable it.

**Comment by mallowigi** [comment]
Yeah there is something amiss here. I will issue a fix right away.

As for being opt-in, I agree but on the other hand it would be easily missed by new adopters, and people can just disable and change it afterwards.

**Comment by LXGaming** [comment]
Thank you for fixing this.
