### ISSUE TITLE
This plugin permanently changes WebStorm even if you uninstall it

### ISSUE THREAD

**Issue by stevensacks** [ChrisRM/material-theme-jetbrains#595]
I installed this plugin, decided it wasn't for me and uninstalled it.

Now, the title bar of the app is black, the project explorer font size is much larger than normal.

I cannot figure out how to fix it. I've uninstalled and reinstalled WebStorm, didn't work. I tried changing the WebStorm theme to default and to Darcula, no fix.

Whatever you did to change the title bar and the font/icon size in the project tab is permanent.

**Comment by mallowigi** [comment]
Sorry about that. I need to add this to the README. 

Read this section to revert it back https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/component-settings/#dark-title-bar

**Comment by mallowigi** [comment]
https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/file-status-colors/#caveats

**Comment by stevensacks** [comment]
Hm. I can't find the file status colors and that note doesn't say exactly how to find them. I tried searching for them in the preferences and the command palette. No luck.

**Comment by mallowigi** [comment]
It's under Version Control > File Status Colors

**Comment by stevensacks** [comment]
![screen shot 2018-01-20 at 2 01 09 am](https://user-images.githubusercontent.com/162252/35162172-d1e4b356-fd85-11e7-8c25-6392f24bb60e.png)

**Comment by stevensacks** [comment]
Ah found it.

**Comment by stevensacks** [comment]
Ok thanks.

**Comment by mallowigi** [comment]
Ok now it's "opt-in" and I even added an alert when checking this option. 

Sucks that there is no other way though. I can see that Electron apps have this ability but I don't know how they did it.

**Comment by k3n** [comment]
I feel like the central tenet of this issue remains: "This plugin permanently changes WebStorm even if you uninstall it".

While I appreciate FOSS and your willingness to contribute to the ecosystem, I'm really regretting that I even tried this plugin out, because even after uninstalling, I can't get back to normal.

**Comment by mallowigi** [comment]
Can you elaborate?

--
Elior
