### ISSUE TITLE
Angular inline tags

### ISSUE THREAD

**Issue by azdanov** [ChrisRM/material-theme-jetbrains#597]
Bug happens when reformat command is issued, or manual formatting is applied to `template` (needs restart to fix). Otherwise it works fine from cold start.

<img width="751" alt="screen shot 2018-01-21 at 21 39 05" src="https://user-images.githubusercontent.com/6123841/35198175-b5b3c036-fef3-11e7-82b5-a0e613436a99.png">

Also similar behaviour with `styles`.

<img width="425" alt="screen shot 2018-01-21 at 21 43 29" src="https://user-images.githubusercontent.com/6123841/35198218-4741298a-fef4-11e7-8d0c-c272654abde3.png">

```
IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.2784.17, built on January 18, 2018
IntelliJ IDEA EAP User
Expiration date: February 17, 2018
JRE: 1.8.0_152-release-1136-b1 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
```

**Comment by mallowigi** [comment]
How does it look in Darcula ?

**Comment by azdanov** [comment]
<img width="749" alt="screen shot 2018-01-22 at 17 46 13" src="https://user-images.githubusercontent.com/6123841/35229477-31d8c424-ff9c-11e7-9129-a4e2fe093fc4.png">

Thanks for suggestion.
I guess it's possibly related to `2018.1 EAP`.

**Comment by mallowigi** [comment]
Thanks
