### ISSUE TITLE
Error : ClassNotFoundException - Change Look and Feel

### ISSUE THREAD

**Issue by infiniityr** [ChrisRM/material-theme-jetbrains#598]
Hi,

When I open Intellij Idea I got 2 ClassNotFoundException. They are both related to "Look and Feel". Some screenshots are provided below.

<img width="346" alt="capture d ecran 2018-01-22 a 14 06 00" src="https://user-images.githubusercontent.com/15141959/35222220-72f0e082-ff7d-11e7-901d-758ffb70e97e.png">
<img width="347" alt="capture d ecran 2018-01-22 a 14 06 08" src="https://user-images.githubusercontent.com/15141959/35222221-730f010c-ff7d-11e7-846a-a37ff2028962.png">

I just tried to unistall the plugin and install it back but the error is still here.

**Comment by mallowigi** [comment]
Are you using JFormDesigner plugin?

**Comment by infiniityr** [comment]
Yes... I used it and I didn't unistall it... 
Now it works better
Thank you !
