### ISSUE TITLE
Wrong tab background color for excluded directories (dark themes)

### ISSUE THREAD

**Issue by Kiyozz** [ChrisRM/material-theme-jetbrains#599]
### Summary

After upgrading to 1.6.0.4, my excluded directories have a white background. Switch light/dark theme doesn't fix it.

### Expected behavior

Excluded tabs keep the right color.

### Actual behavior

Excluded tabs are white.

### Steps to reproduce

1. Update to 1.6.0.4
2. Restart IDE
3. Look at your files tree.

[![https://gyazo.com/d5fa8233ca8d12a86d302a07f09bf170](https://i.gyazo.com/d5fa8233ca8d12a86d302a07f09bf170.png)](https://gyazo.com/d5fa8233ca8d12a86d302a07f09bf170)

### Environment

PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
Licensed to FTPROD
Subscription is active until February 14, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2
Material Theme UI 1.6.0.4

**Comment by mallowigi** [comment]
https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/excluded-files-colors/

**Comment by DrunkenPoney** [comment]
Link is dead and I have the same issue

**Comment by Kiyozz** [comment]
Hello @DrunkenPoney, you need to change the color of the exclude folders. 

Link : http://www.material-theme.com/docs/configuration/excluded-files-colors/#material-file-colors
