### ISSUE TITLE
Custom theme colors don't work

### ISSUE THREAD

**Issue by artemirq** [ChrisRM/material-theme-jetbrains#600]
### I change custom theme color(background) and this not changed in IDE

![image](https://user-images.githubusercontent.com/17342159/35232523-b9f7ae28-ffac-11e7-8778-7b551f4cc7ac.png)

### Environment

IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018
Licensed to Artem Batura
Subscription is active until September 2, 2018
For educational use only.
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
You need to select "Custom Theme" in the list of themes

**Comment by artemirq** [comment]
@mallowigi I not have Custom Theme in the list of themes :c
![image](https://user-images.githubusercontent.com/17342159/35390350-27a96448-01ec-11e8-9731-a0f903124f5c.png)

**Comment by mallowigi** [comment]
Please read the documentation
