### ISSUE TITLE
Color is changed to white when the text is seleted

### ISSUE THREAD

**Issue by rabbitmeow** [ChrisRM/material-theme-jetbrains#601]
How to custom the color of the selected text? I don't want it to be changed. Thank you very much!
![image](https://user-images.githubusercontent.com/20941062/35233809-20f9dc7c-ffda-11e7-8408-d535d3bcd1dc.png)

**Comment by mallowigi** [comment]
Color scheme > General > Selected text color

**Comment by rabbitmeow** [comment]
Sorry, I cannot find this option.

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/35262767-b421176a-001e-11e8-9dec-5a76f5cb627a.png)

**Comment by rabbitmeow** [comment]
Thank you very much!

**Comment by svipben** [comment]
@mallowigi Why not disabling this by default? After I installed this theme I think it was a bug.
