### ISSUE TITLE
Angular color-coded icons

### ISSUE THREAD

**Issue by azdanov** [ChrisRM/material-theme-jetbrains#603]
[VSCode Material Icon Theme](https://github.com/PKief/vscode-material-icon-theme) implements color coding for different angular files based on the file ending, e.g [*.service.ts](https://github.com/PKief/vscode-material-icon-theme/blob/63776246ba20472d8a1e712cf2399ac4b4cc241f/src/icons/fileIcons.ts#L361) for yellow icon.

<img width="175" alt="screen shot 2018-01-23 at 18 28 27" src="https://user-images.githubusercontent.com/6123841/35287668-91365772-006b-11e8-9a03-cd762812c060.png">

Would it be possible to achieve something similar with material-jetbrains theme?

**Comment by mallowigi** [comment]
It is possible, yes

**Comment by azdanov** [comment]
Cool.

Will have a look if i conjure up a PR. Although my Java skills are almost non-existent.

**Comment by azdanov** [comment]
Converted some svg icons to png, will these work?

@1x | @2x
:-------------------------:|:-------------------------:
![angular component](https://user-images.githubusercontent.com/6123841/35331852-8348261c-0111-11e8-82e2-7462a44db479.png) | ![angular component 2x](https://user-images.githubusercontent.com/6123841/35331853-8362c9a4-0111-11e8-8198-dfef2a82e773.png)
![angular directive](https://user-images.githubusercontent.com/6123841/35331854-837c4d34-0111-11e8-9d63-075f4ed0c85f.png) | ![angular directive 2x](https://user-images.githubusercontent.com/6123841/35331855-839501e4-0111-11e8-9fb8-1cbed29f91c1.png)
![angular guard](https://user-images.githubusercontent.com/6123841/35331856-83af902c-0111-11e8-87ce-52b15919e714.png) |  ![angular guard 2x](https://user-images.githubusercontent.com/6123841/35331857-83c976f4-0111-11e8-924f-7006c05971d0.png)
![angular pipe](https://user-images.githubusercontent.com/6123841/35331858-8402146e-0111-11e8-9d73-480bf3b7ebe8.png) |  ![angular pipe 2x](https://user-images.githubusercontent.com/6123841/35331859-842190c8-0111-11e8-8f1c-29b1e5d77bfc.png)
![angular resolver](https://user-images.githubusercontent.com/6123841/35331860-8440936a-0111-11e8-8fa4-ca9767b6ca65.png) | ![angular resolver 2x](https://user-images.githubusercontent.com/6123841/35331862-845ebebc-0111-11e8-8a6a-e4e4d5b7ccfc.png)
![angular routing](https://user-images.githubusercontent.com/6123841/35331863-84798f1c-0111-11e8-806d-0fb7fe46d65c.png) | ![angular routing 2x](https://user-images.githubusercontent.com/6123841/35331864-8497e8f4-0111-11e8-80fc-14fd5ae36296.png)
![angular service](https://user-images.githubusercontent.com/6123841/35331865-84b19c0e-0111-11e8-9b11-3fa19a087e45.png) | ![angular service 2x](https://user-images.githubusercontent.com/6123841/35331866-84cb98de-0111-11e8-8f8e-39557279aae2.png)
![angular](https://user-images.githubusercontent.com/6123841/35331867-84e4be86-0111-11e8-8541-3a9be99b4970.png) | ![angular 2x](https://user-images.githubusercontent.com/6123841/35331868-84ff2776-0111-11e8-9f21-8abefe5b720a.png)
