### ISSUE TITLE
Excessive update noise

### ISSUE THREAD

**Issue by AlekseyKorzun** [ChrisRM/material-theme-jetbrains#604]
I would like to bounce an idea of implementing a release schedule instead of continually pushing the updates out.

We are using a wide array of JetBrains tools and recently implemented the Material Theme on all of them. At the moment, the level of noise caused by constant updates to this theme is unbearable. 

For example, I will launch PyCharms and get prompted to update the theme, then I context switch to WebStorm and get an update prompt again. Now, I need to open DataGrip and boom another update prompt. 

This kind of flow would have been acceptable if the releases were staggered, but this happens every other day now. I'm aware that this is not a big deal to most of the individual users, but it is an issue when you apply scale to the equation. 

I propose to stand-up a release schedule (security updates can live on separate schedule) where all of the updates are staged as an RC. Then RC is promoted to stable (triggers updates) once every two weeks or so.

**Comment by mallowigi** [comment]
In the beginning I planned to use the eap channel for the develop branch until the release seemed stable, but for some reason I couldn't get it to work and gave up.

But you're right, I should space up the releases instead of continuously deploying every time I fix a bug or add a feature
