### ISSUE TITLE
application configuration edit dialog layout optimalize..

### ISSUE THREAD

**Issue by xinkunZ** [ChrisRM/material-theme-jetbrains#606]
Material theme plugin has change textfield height, so the "before launch" panel is too small to show  its content.  so  is there any fix?

![image](https://user-images.githubusercontent.com/7759897/35310002-45d31d36-00ea-11e8-9ade-75698b45dfd2.png)

**Comment by mallowigi** [comment]
You can resize the window

**Comment by xinkunZ** [comment]
I wan't to , but it is max size........

**Comment by mallowigi** [comment]
Well, sorry about that. I have added an option for compact dropdowns in the new version, but until then you can move the window outside of the bounds and then resize it

--
Elior
