### ISSUE TITLE
Project view font size changes after re-opening the IDE

### ISSUE THREAD

**Issue by anidotnet** [ChrisRM/material-theme-jetbrains#607]
The font size of project view changes even if the "Custom Sidebar Height" is set to 26. To restore it, I have to delete the .idea folder of the project. Then for the first time when I import the project, the font size look normal and as expected. But when I close the IDE and reopen it again, the font size gets larger again. It is kind of annoying.

![screenshot from 2018-01-24 09-44-40](https://user-images.githubusercontent.com/696662/35314399-c8233f7c-00eb-11e8-89f0-67118442eb6b.png)

![screenshot from 2018-01-24 09-45-10](https://user-images.githubusercontent.com/696662/35314404-cee43db6-00eb-11e8-9c7b-59135be23e60.png)

IntelliJ IDEA 2017.3.3 (Ultimate Edition)
Build #IU-173.4301.25, built on January 15, 2018

JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-25-generic

Plugin Version: 1.6.0.4

**Comment by mallowigi** [comment]
There is an option called “Material Fonts”. Disable it and you’re good .
