### ISSUE TITLE
Build progress dialog issue

### ISSUE THREAD

**Issue by rishabh876** [ChrisRM/material-theme-jetbrains#608]
### Summary

Android Studio build progress Dialog have no background or text. 

### Expected behavior
Dialog used have text and a background body

### Actual Behavior
<img width="843" alt="screen shot 2018-01-24 at 2 50 19 pm" src="https://user-images.githubusercontent.com/7318534/35324495-e2383388-0116-11e8-9fa4-447e45679e83.png">

### Steps to reproduce (if needed)

1. Build a Project
2. Observe the progress dialog 

### Environment

Android Studio 3.0.1
OS - Mac
Plugin version  - 1.6.0.4 (Started happening since last few Versions)
Note: I am also using my own Custom Darcula Color scheme.

**Comment by mallowigi** [comment]
I cannot reproduce this, besides the progress bars look like a much older version of the plugin which is weird.

Maybe it's because it's on Mac and I have AS only on Windows? Will check that later.
