### ISSUE TITLE
Tiny pixel artifacts in Tool Windows

### ISSUE THREAD

**Issue by sparkbuzz** [ChrisRM/material-theme-jetbrains#611]
### Summary

Pixel artifacts in the left of most Tool Windows

### Expected behavior

Tool Windows should be clean and consistent, no artifacts left behind.

### Actual behavior

Some Tool Windows, like the Project and Favorites windows leaves a pixel behind when navigating up/down the list using the keyboard arrow keys. The color of the pixel seems to correspond to whatever the accent color of the theme is set to.

### Steps to reproduce (if needed)

1. Open the Project, Favorites or Structure View from **> View > Tool Windows > Project/Favorites/Structure**

2. Using the keyboard, navigate up and down the tree.

3. Notice the pixel artifacts left behind on the left of each menu item as you navigate away.

<img width="340" alt="pixel-artifacts" src="https://user-images.githubusercontent.com/612695/35378891-095eab12-01bd-11e8-8df1-df06c3a7c562.png">

### Environment

PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
Licensed to Josef van Niekerk
Subscription is active until May 1, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

* Plugin version: 1.6.0.4
* Plugin configuration: default

**Comment by mallowigi** [comment]
I will not fix this, this looks like a very minor issue
