### ISSUE TITLE
Dark borders in light theme

### ISSUE THREAD

**Issue by sparkbuzz** [ChrisRM/material-theme-jetbrains#612]
### Summary

Dark borders in light theme

### Expected behavior

Border colors should be consistent with the rest of the theme

### Actual behavior

Borders are black in editor view

### Steps to reproduce (if needed)

1. Select the light theme.

2. Open one or more files in the editor

<img width="662" alt="screen shot 2018-01-25 at 10 49 50" src="https://user-images.githubusercontent.com/612695/35379122-be440f90-01bd-11e8-9729-570daaef8e17.png">

### Environment

PhpStorm 2017.3.3
Build #PS-173.4301.34, built on January 18, 2018
Licensed to Josef van Niekerk
Subscription is active until May 1, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

* Plugin version: 1.6.0.4
* Plugin configuration: default

**Comment by mallowigi** [comment]
I will redo the tabs shortly, to be able to use the tab indicator in light themes as well. It might fix the issue.
