### ISSUE TITLE
Terminal tabs are not in line with the theme

### ISSUE THREAD

**Issue by ivarkallejarv** [ChrisRM/material-theme-jetbrains#613]
Terminal on its own looks very neat:
![image](https://user-images.githubusercontent.com/14091739/35402544-94792bf8-0205-11e8-8ca4-c97cb28bb3d4.png)

The problem I have with it, is when I open multiple tabs of the terminal:
![image](https://user-images.githubusercontent.com/14091739/35402573-ab9d67a4-0205-11e8-9970-0b4edfe1a14f.png)

Multiple large tabs that have a different color when compared to the rest of the theme.

Would prefer it if the tabs were smaller(Perhaps similar to the terminal header/title) , had a better color(one that's more in line with the theme).

OS: Windows 10
Product: Webstorm 2017.3.3
Plugin version: 1.6.0.4
Theme: Material Oceanic, default

**Comment by mallowigi** [comment]
I know about this, and unfortunately there is no fix for that. Until Jetbrains decides to acknowledge this plugin and let us modify the colors instead of using hardcoded values.
