### ISSUE TITLE
Is it possible to change the autocompletion window's colours?

### ISSUE THREAD

**Issue by brainplot** [ChrisRM/material-theme-jetbrains#615]
Hello everybody,

After switching to this theme, which is really great, setting it up and restarting IntelliJ a couple of times I noticed that the autocompletion window is not exactly how I'd like it to be: the currently-selected line is a little unreadable, as shown in the screenshot below:

![ss](https://user-images.githubusercontent.com/28014843/35479055-744f4dbe-03ed-11e8-9570-65de7874b55c.png)

It's good that the matching characters have the same colour as the theme accent but instead, the package name under the selection is quite unreadable to me: there's not enough contrast between the selection colour and the text being displayed underneath.
The colour scheme I chose is Material Palenight, with the Brick accent colour.
After searching online for quite a bit (including the Github issues already closed) and digging into the IntelliJ's colour settings I was unable to change the colour of the selected suggestion in order to make it darker; or give it more contrast anyway.

### Environment
OS: Arch Linux
IntelliJ IDEA 2017.3.3 (Community Edition)
Build #IC-173.4301.25, built on January 15, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.15-1-ARCH

Plugin Configuration:
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="1.6.0.4" />
    <option name="selectedTheme" value="PALENIGHT" />
    <option name="isContrastMode" value="true" />
    <option name="accentColor" value="e57373" />
  </component>
</application>
```

#### EDIT
By changing the colour scheme to Material Darker I get better contrast and readability improves quite a bit:

![ss](https://user-images.githubusercontent.com/28014843/35479163-abbe72fe-03f0-11e8-8b0d-f8ae18325bd4.png)

Is there any way to make the autocompletion window with Material Palenight enabled as readable as with Material Darker?

**Comment by mallowigi** [comment]
I think the problem is inherent with the Palenight theme as a whole: List items foreground and selected background color are too close to one another. Unlike Darker, Oceanic and the others.

Maybe the solution is to brighten the foreground color for lists.

**Comment by brainplot** [comment]
@mallowigi thank you for replying. I had another look within the settings but I can't find "List items foreground". Could you please tell me where I can find it?
Given that the autocompletion window always keeps the same colours (except for its background), no matter what colour scheme you choose, I thought that the colour of the selection and fonts are in this panel here. Am I wrong?

![ss](https://user-images.githubusercontent.com/28014843/35483012-1b52a99a-043d-11e8-9510-92fc799b74bd.png)

I also had a look through all the items under "Color Scheme" (screenshot below) but I still can't find it.

![ss](https://user-images.githubusercontent.com/28014843/35483047-8f938f4a-043d-11e8-870f-ce0c8628d70e.png)

Forgive me if I'm being blind or something :laughing:

**Comment by mallowigi** [comment]
I never said it’s something configurable. It’s something that comes from the theme itself.

**Comment by brainplot** [comment]
All right, I'll sadly switch to Darker or Oceanic, which are those that come next according to my preferences. It's a shame though, I've got Palenight set up pretty much anywhere :)

Thank you for your assistance!

**Comment by mallowigi** [comment]
Sorry I didnt' pay attention that you were talking about the package name, not the entry itself.

I'll see what I can do

**Comment by brainplot** [comment]
Yeah, the package name is definitely what's suffering the most from this issue. Choosing an appropriate accent colour can help give more contrast to the matching bit of the statement but then again, I can't do much for package names.

Also, all the entries that **are not** selected can be considered quite acceptable in terms of contrast and readability; it's just the selection marker that makes them a lot harder to read when each entry is being selected.

The solution would be either darkening the selection marker for the list (or even for the whole colour scheme, if you can target the autocompletion list specifically) or brightening up the foreground colour, with the latter ruining the whole theme a bit, to be honest, as that's exactly the foreground colour in any Material Palenight scheme I've seen so far.

**Comment by mallowigi** [comment]
Maybe the selection color is not right? How is it in VSC ?

**Comment by brainplot** [comment]
In VSC it looks like this:

![ss](https://user-images.githubusercontent.com/28014843/35487646-43c390ba-047e-11e8-9f1c-3a6704fc4e25.png)

I used the JavaScript syntax because you don't get autocompletion suggestions in VSC with the Java syntax enabled; but that shouldn't make much of a difference right?

**Comment by mallowigi** [comment]
What I did was to change the color of the package name to the same color as the "menu accelerators", e.g. the shortcuts in the menus and so on. 

The selected backgronud color might be problematic though. It looks like the contrast color, but lists should have the selected background color for selected item usually.

Maybe setting a bgColor with transparency will do the trick

**Comment by brainplot** [comment]
Can you actually set transparency? I mean, all the colours are just RGB values and those can't encode any transparency can they?

**Comment by mallowigi** [comment]
I can in the bundled themes only. Custom themes are not.

--
Elior

**Comment by brainplot** [comment]
All right then, thank you!
