### ISSUE TITLE
I am using AppCode, and I find the colors are too light

### ISSUE THREAD

**Issue by Daopr** [ChrisRM/material-theme-jetbrains#616]
I am using AppCode, and I find the colors are too light, and obviously different with the same theme in other IDEs. sometimes like been washed out. the colors sometimes makes me sleepy, could you light up the colors?

**Comment by mallowigi** [comment]
Can you provide screenshots?

**Comment by mallowigi** [comment]
I think you are talking about the colors in the Project View right ?

**Comment by mallowigi** [comment]
Closing for lack of response

**Comment by DrDoa** [comment]
Sorry， I was busy last period. 
Thanks for your responding !
I means the editor color schema, and I find I could adjust them to a high contrast by my own.
And I have done this for my self.


![20](https://user-images.githubusercontent.com/8122371/36639253-aa5b17f0-1a43-11e8-9ec0-6d095d43134c.jpg)

![21](https://user-images.githubusercontent.com/8122371/36639254-aa95f3fc-1a43-11e8-8bd0-99d8bd38227b.jpg)
