### ISSUE TITLE
Prepare thyself for the new UI for ToolWindowHeader

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#619]
It's happening (probably not for the incoming versions but still)

**Comment by dudong0726** [comment]
is  amazing,

**Comment by dudong0726** [comment]
when its ready to test,pls let me know the first time !   ill test and feedback

**Comment by mallowigi** [comment]
I’m afraid it will take quite some time. It’s in the backlog but I’m not sure they will release it in the next months
