### ISSUE TITLE
Ignored Folders: Font not readable

### ISSUE THREAD

**Issue by gregorskii** [ChrisRM/material-theme-jetbrains#62]
Hi there,

Excellent work.

When hiding folders from sources the editor changes the background and the text color of the row in the file list, and also changes the font. The font is unreadable.

I am using Intellij 14.1.5.

<img width="304" alt="screen shot 2015-10-13 at 8 54 25 am" src="https://cloud.githubusercontent.com/assets/1130448/10460206/37926496-7188-11e5-9a86-36500554e47c.png">

Thanks!

**Comment by mikeerickson** [comment]
@gregorskii Hey Greg

You can update this using FIle Status option (see screenshot)
![file-status](https://cloud.githubusercontent.com/assets/183153/10461214/2d0900e8-718d-11e5-9106-f41f9def1d7b.png)

**Comment by gregorskii** [comment]
Nope unfortunately that is not the same thing. Its not ignored by the gitignore plugin its being ignored by Intellij's Package config.

<img width="703" alt="screen shot 2015-10-13 at 2 20 17 pm" src="https://cloud.githubusercontent.com/assets/1130448/10468740/91875b3c-71b5-11e5-9f04-077596b8c578.png">
