### ISSUE TITLE
Support for 2018.1?

### ISSUE THREAD

**Issue by EdwardDrapkin** [ChrisRM/material-theme-jetbrains#620]
Hey there!

Are there plans to support this version?  Anything I can do to help?

**Comment by mallowigi** [comment]
It's already supporting 2018.1, what are you talking about ?

**Comment by EdwardDrapkin** [comment]
When I upgraded to the 2018.1 EAP, it disabled the plugin and there's no update available for it.

**Comment by mallowigi** [comment]
What IDE ?

**Comment by EdwardDrapkin** [comment]
phpstorm

**Comment by mallowigi** [comment]
What plugin are you talking about ?

**Comment by mallowigi** [comment]
![image](https://user-images.githubusercontent.com/5015756/35686291-9ed5dd0c-0774-11e8-8c92-0e42880b05d9.png)

**Comment by JoeriTheGreat** [comment]
I have the same problem!
2017.3.6 works fine

2018.1 - The color sheme works but not the UI (see screenshot)
<a href='https://postimg.org/image/nse1vcsnv/' target='_blank'><img src='https://s17.postimg.org/nse1vcsnv/phpstorm.jpg' border='0' alt='phpstorm'/></a>
