### ISSUE TITLE
Commit/Push button on Git VCS UI missing in PyCharm 2018.1

### ISSUE THREAD

**Issue by SunDwarf** [ChrisRM/material-theme-jetbrains#621]
### Summary

The commit button is missing on the commit window.

### Expected behavior
It wouldn't be missing.
Without the plugin: ![Example shwoing it not missing](https://files.catbox.moe/ag6xht.png)

### Actual behavior
It is. 
![Example showing it missing](https://files.catbox.moe/j9tfoq.png)

### Environment

PyCharm 2018.1 EAP (Professional Edition)
Build #PY-181.3263.12, built on January 30, 2018
PyCharm EAP User
Expiration date: March 1, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.13-1-ARCH

**Comment by roboslone** [comment]
+1, please fix this

**Comment by sowelie** [comment]
I'm seeing this in IntelliJ IDEA as well.

**Comment by mallowigi** [comment]
![intellij idea-eap 2018-02-02 at 10 31 44](https://user-images.githubusercontent.com/5015756/35723855-72671bc4-0804-11e8-8d06-023288c0dd2e.png)

You can disable the "merge buttons" option on the settings as well. 

I don't know what is the cause of that, probably something new they introduced that broke the previous API

**Comment by roboslone** [comment]
@mallowigi @sowelie how did you get those awesome black window frames?

**Comment by mallowigi** [comment]
For the first question, it’s the “themed title bar” setting.

And if you’re talking about the upper case buttons, it’s a feature upcoming in the next version, which is planned in a few weeks

**Comment by mallowigi** [comment]
Please reopen

**Comment by NikosVlagoidis** [comment]
Is this closed? I just downloaded 2018.1 and I cannot see the merged button.

**Comment by NikosVlagoidis** [comment]
thank you!

**Comment by phoenixJu** [comment]
it works，thanks
