### ISSUE TITLE
Weird looking text throughout phpstorm

### ISSUE THREAD

**Issue by ricardo118** [ChrisRM/material-theme-jetbrains#622]
### Summary

Weird looking text throughout phpstorm except in some scenarios when enabling the theme.

### Expected behavior

On a fresh install of 2017.3.4 (without any settings/configs imports) installing material theme ui via the first configuration setup or after manually via settings the text becomes like this:

https://i.imgur.com/06nZ7du.png

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

Windows 10
PHPStorm 2017.3.4
Latest plugin version

**Comment by mallowigi** [comment]
This happens inconsistently because of a wrong Roboto font. Just change the font in Settings > Appearance > Override custom fonts
