### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by IllgiLP** [ChrisRM/material-theme-jetbrains#623]
### Summary
  IntelliJ shows error on startup

### Expected behavior
 No error

### Actual behavior
 there is still one

Screenshot: 
http://short.skydis.de/bdbba5

### Environment

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 29, 2018
Licensed to Cornelius Illgen
Subscription is active until May 14, 2018
For educational use only.
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
This happens when the JFormDesigner plugin is enabled. I didn’t find a fix to it and it looks like it’s the plugins fault so disable it or just ignore this error.
