### ISSUE TITLE
Editor tab has a black outline border In Material Light Theme

### ISSUE THREAD

**Issue by threadflow** [ChrisRM/material-theme-jetbrains#624]
### Summary

In Material Light Theme mode, editor tab has a black outline border some times.

Some times it is normal.

normal time:

<img width="917" alt="screen shot 2018-02-03 at 16 37 34" src="https://user-images.githubusercontent.com/1308665/35768955-abe0fdbc-093e-11e8-9173-a66be11198d1.png">

abnormal time:

<img width="888" alt="screen shot 2018-02-03 at 16 37 22" src="https://user-images.githubusercontent.com/1308665/35768949-992af470-093e-11e8-8d4c-f85b546602cc.png">

<img width="187" alt="screen shot 2018-02-04 at 00 25 48" src="https://user-images.githubusercontent.com/1308665/35769190-3e4f86c0-0942-11e8-9fcb-bc90774ace1a.png">

### Environment

* OS:  MacOS 10.13.3 (17D47)
* IntelliJ Product: PyCharm 2017.3.3 (Professional Edition) Build #PY-173.4301.16, built on January 11, 2018
* JRE: 1.8.0_152-release-1024-b11 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* Plugin version: 1.6.0.4
* Plugin configuration: 

material_theme.xml

`
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="1.6.0.4" />
    <option name="selectedTheme" value="LIGHTER" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="3f51b5" />
    <option name="hideFileIcons" value="true" />
    <option name="tabsHeight" value="50" />
    <option name="darkTitleBar" value="true" />
    <option name="arrowsStyle" value="Plus-Minus" />
  </component>
</application>
`

material_custom_theme.xml

`<application>
  <component name="MaterialCustomThemeConfig">
    <option name="notificationsColor" value="1e272c" />
    <option name="treeSelectionColor" value="546e7a" />
    <option name="buttonHighlightColor" value="f2f1f1" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="d3e1e8" />
    <option name="tableSelectedColor" value="bde3df" />
    <option name="contrastColor" value="f4f4f4" />
    <option name="disabledColor" value="d2d4d5" />
    <option name="secondaryBackgroundColor" value="eae8e8" />
    <option name="caretColor" value="ffcc00" />
    <option name="inactiveColor" value="fafafa" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="d2d4d5" />
    <option name="textColor" value="7e939e" />
    <option name="foregroundColor" value="546e7a" />
    <option name="backgroundColor" value="fafafa" />
  </component>
</application>`

* enabled plugins: Fresh installed PyCharm with only Material UI installed abled

**Comment by mallowigi** [comment]
Will be fixed in the next version.
