### ISSUE TITLE
Incompatible with EAP 2018.1

### ISSUE THREAD

**Issue by mikemand** [ChrisRM/material-theme-jetbrains#629]
### Summary

Several dialogs and things are broken in the 2018.1 EAP. I cannot open Settings (the dialog does not appear at all). New File is missing the input box to name the file. New "X" (Stylesheet, HTML File, etc.) dialogs are missing their inputs as well.

### Expected behavior

It should work just like it did for 2017.3.

### Actual behavior

See summary above. Here are some screenshots:

![screen shot 2018-02-05 at 4 42 25 pm](https://user-images.githubusercontent.com/745184/35834708-3152d1ae-0a94-11e8-9528-675ad5062109.png)
![screen shot 2018-02-05 at 4 45 09 pm](https://user-images.githubusercontent.com/745184/35834722-3a4c0e60-0a94-11e8-9524-0f12bc460576.png)

Even trying to resize the dialogs does not make them appear.

### Steps to reproduce (if needed)

1. Install or update to the 2018.1 EAP
2. Either already have Material Theme installed, or install it.
3. Pretty display, but no dialogs are functioning.

As a note, it appears as though you can toggle Material Theme Components and it fixes the problems.
![screen shot 2018-02-05 at 4 49 34 pm](https://user-images.githubusercontent.com/745184/35834825-aab73d8c-0a94-11e8-825e-2d97583ff834.png)

### Environment

PhpStorm 2018.1 EAP
Build #PS-181.3263.18, built on January 31, 2018
PhpStorm EAP User
Expiration date: March 2, 2018
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

#### Plugin version

Material Theme UI EAP
Version:  1.3.0-173.3622

#### Plugin configuration

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="1.3.0" />
    <option name="selectedTheme" value="DARKER" />
    <option name="highlightColor" value="80cbc4" />
    <option name="highlightColorEnabled" value="true" />
    <option name="isContrastMode" value="true" />
    <option name="isMaterialDesign" value="false" />
    <option name="isCustomTreeIndentEnabled" value="true" />
    <option name="customTreeIndent" value="4" />
    <option name="accentColor" value="80cbc4" />
    <option name="compactSidebar" value="true" />
    <option name="statusBarTheme" value="false" />
    <option name="tabsHeight" value="32" />
    <option name="isCompactStatusBar" value="true" />
    <option name="defaultBackground" value="https://raw.githubusercontent.com/mallowigi/material-theme-jetbrains-eap/master/src/main/resources/themes/wall.jpg,60" />
  </component>
</application>
```

#### Active plugins

[Dummy Text Generator (1.0.11), Key Promoter X (5.11), String Manipulation (5.7.143.000.0), WakaTime (9.0.1), .ignore (2.4.0), Makefile support (1.2.2), EditorConfig (181.2784.29), BashSupport (1.6.12.181), PHP Class Templates (1.0.2), PHP RegExp Support (0.9.3), Php Inspections (EA Extended) (2.3.16), PHP inheritDoc helper (1.5.0), Extra Actions (1.2.1), Laravel Plugin (0.15), Rainbow Brackets (3.1.1), Material Theme UI EAP (1.3.0-173.3622), PostCSS support (181.3007.17), Markdown Navigator (2.4.0), PHP composer.json support (1.0.24), .env files support (0.6), PHP Lambda Folding (0.3.0)]

**Comment by mallowigi** [comment]
Material Theme eap is deprecated, please use the Material Theme UI and tell me the results

**Comment by mikemand** [comment]
Hi @mallowigi. That worked, thank you! If you put out a deprecation notice, I either didn't get it or missed it. I will be more careful in the future. 👍
