### ISSUE TITLE
Lots of issues on PHPStorm 8.x

### ISSUE THREAD

**Issue by mikeerickson** [ChrisRM/material-theme-jetbrains#63]
Hey Chris

One of my coworkers was trying out the theme and while a lot of it worked great, there are quite a few odd appearances with PHPStorm 8.x.  Another coworker is using PHPStorm 9.0.2 and it looks fine.

If you care to support PHPStorm 8.x, I can create a list of all the things that look amiss and send it over.  Or you can just support 9.x and beyond.

Also, for those dark horses, ColorIDE is a MUST have 

Let me know what you think.

**Comment by ChrisRM** [comment]
> If you care to support PHPStorm 8.x, I can create a list of all the things that look amiss and send it over. 

Please do.

ColorIDE should be avoided, as it actually overwrites some of the core files in your installation.

**Comment by mikeerickson** [comment]
Oh really? I had to use ColorIDE for my 9.x installations to make all backgrounds match (those in the project panel and terminal panel).  

I will create an 8.x VM at home and record / mention all the issues that I am seeing.    But I will say, without ColorIDE on 8.x there are a lot more issues (see above for just two examples).

**Comment by ChrisRM** [comment]
The project panel and terminal can be fixed without ColorIDE. I'll do some testing here as well.

**Comment by mikeerickson** [comment]
@ChrisRM Oh, didnt realize that.... cool deal.
