### ISSUE TITLE
Issues with latest EAP

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#632]
- --Tree indicator is not printed in Settings--
- --Clear and search buttons are gone--
- Textboxes padding
- Checkboxes border
- --Action button radius--
- --Option button are too bright, they look disabled--

**Comment by ForsakenHarmony** [comment]
https://gist.github.com/ForsakenHarmony/306487949674764bfd3b0aaccf5ac988

**Comment by mallowigi** [comment]
Which version?

**Comment by AfroMetal** [comment]
PyCharm 2018.1 EAP, can't even open settings, commit window only has 'Cancel' button, without 'Commit'.

**Comment by dudong0726** [comment]
Action button radius 

IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.3494.3, built on February 6, 2018
IntelliJ IDEA EAP User
Expiration date: March 8, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by mallowigi** [comment]
@AfroMetal i need the whole version number, e.g. what you have in the about window

**Comment by AfroMetal** [comment]
@mallowigi 
PyCharm 2018.1 EAP (Professional Edition)
Build #PY-181.3263.12, built on January 30, 2018
PyCharm EAP User
Expiration date: March 1, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.16-1-MANJARO

**Comment by mallowigi** [comment]
Try downloading the 1.8.0.2b3 at https://plugins.jetbrains.com/plugin/8006-material-theme-ui

**Comment by AfroMetal** [comment]
@mallowigi that version works. Strange that IDE did not show me update information. Thanks!

**Comment by ForsakenHarmony** [comment]
![](https://i.imgur.com/MHdTh5V.png)
