### ISSUE TITLE
Sidebar customization

### ISSUE THREAD

**Issue by toioski** [ChrisRM/material-theme-jetbrains#633]
A killer feature could be the possibility to customize the **sidebar** (a.k.a project tree view): the background color, the line-height, the font family and color, the icons. Right now the theme is able to customize this stuff, so it should be all about adding some options in the Material Theme panel in Settings.

**Comment by mallowigi** [comment]
Background color: This can be done via File Colors
Line Height: Custom Line Height in settings
Font Family: Appearance > Override custom fonts
Icons: Material Icons (allowing more customization is demanding a lot of work, but you can develop a plugin with your own icons if you want to)

I don't know what you are talking about but all this stuff is already here

**Comment by toioski** [comment]
**Sidebar background color:** I can't find the option to change the background color. Could you tell me exactly where is the option? 
**Sidebar line height**: same as above. I can change the line height for the editor (Settings -> Editor -> Font -> Line Spacing), but I can't find any Custom Line Height option.
**Sidebar font size**: is it possible to change the font size only for the sidebar? 

Maybe it's just my fault, but I think I am missing something if it's all already possible

**Comment by mallowigi** [comment]
Background color: 
![image](https://user-images.githubusercontent.com/5015756/35927154-ae82d6d4-0c32-11e8-9855-01acd523311f.png)

Line Height
![image](https://user-images.githubusercontent.com/5015756/35927133-a2d3a5fc-0c32-11e8-9066-7e0a93ca7cd6.png)

Font size: No, but I'm not sure

**Comment by toioski** [comment]
**Sidebar background**: The **File Colors** options it's for changing the background color of the files in the sidebar, but not for the whole sidebar background (correct me if I am wrong). What I would like to achieve is the similar to the effect of when you select the option **Toggle Contrast**: the sidebar background color turns darker. 

**Sidebar line height**: sorry, I didn't get that **Sidebar Height** was the line height. Maybe you could change this label to **Sidebar line height** for a better understanding?

Anyway, thanks for the great work you have done!

**Comment by mallowigi** [comment]
You can add a file color for the scope "All" to do what you want.
![image](https://user-images.githubusercontent.com/5015756/35927909-8b62d7b0-0c34-11e8-8c39-fd01a9ab611f.png)

**Comment by toioski** [comment]
Yes, I know, but as we can see from your screenshot everything outside your root folder (e.g. `adm-redesign`) will not be colored (like `External Libraries`, `Scratches and Consoles` and all the empty space below)

**Comment by mallowigi** [comment]
Yes you're right. Maybe I'll add this in the future but not atm

**Comment by mikeerickson** [comment]
Was this ever addressed?  I am unable to set project pane background color. I have tried all the above mentioned suggestions.
