### ISSUE TITLE
Subdirectories are picked as src directory

### ISSUE THREAD

**Issue by yar00001** [ChrisRM/material-theme-jetbrains#634]
For some reason the child directories in the project explorer have the src directory icon and are using the different text color. I don't have this problem in the default theme.

**Comment by mallowigi** [comment]
Can you provide a screenshot of what should be and what it is ?

**Comment by yar00001** [comment]
Sure! Here's the screenshot. `module` is correctly recognized as a subdirectory but `dao`, `model` etc are not. At first I thought there is an uncommitted change in one of the files but then I recognized the directory icon is different.
![github](https://user-images.githubusercontent.com/2102983/35988639-dcf40674-0cb3-11e8-94c3-a014a14a9a48.png)

**Comment by mallowigi** [comment]
The color you see is from the accent color, and can be toggled via the “Project view decorators “ option. As for the folder icon, it looks like because you have a file open from one of those directories. You can also toggle this behavior using the same setting.

**Comment by yar00001** [comment]
Correct me if I'm wrong but a file should have that accent color if an uncommitted change is made in the file. None of those files are open btw. I don't have a problem with the icon but it's just misleading because of the git thing I mentioned.
P.s. I don't have this problem in the rest of the projects.

**Comment by mallowigi** [comment]
https://mallowigi.github.io/material-theme-jetbrains-eap/docs/configuration/component-settings/#project-view-decorators
