### ISSUE TITLE
Can not display Chinese When I search in files

### ISSUE THREAD

**Issue by asstea** [ChrisRM/material-theme-jetbrains#635]
### Summary

Can not display Chinese When I search in files, but the editor will not.

### Expected behavior

none

### Actual behavior

![image](https://user-images.githubusercontent.com/15345948/35954796-c47af4f0-0cc6-11e8-952f-299d426b59cb.png)

This setting will solve the problem, but to restart the above problems.

![image](https://user-images.githubusercontent.com/15345948/35954819-dc74075e-0cc6-11e8-8bdf-272bb271a029.png)

### Steps to reproduce (if needed)

1. Open Idea
2. used search

### Environment

* Windows 10 64bit
* WebStorm 2017.3.4
* Material Theme UI 1.6.0.4

I really like this theme, hope you can fix, thank you

**Comment by mallowigi** [comment]
I’m not sure but it could be because of the Fira Code font.

Try to change it in Settings > Color Scheme > Color Scheme font

**Comment by dudong0726** [comment]
try to uncheck Material Fonts  setting in  Settings > Apperance > Material Theme
the problem resolved 

@mallowigi  please looks at this issue

![image](https://user-images.githubusercontent.com/1704803/36019519-8856eb88-0dba-11e8-9c19-14481c568367.png)

**Comment by mallowigi** [comment]
Have you tried what I said? I can’t verify at the moment but it is likely that it’s because of the editor font, which doesn’t support Chinese characters. But I’ll check as soon as I can

**Comment by asstea** [comment]
Use dudong0726 methods, I solved the problem, thank you.

**Comment by asstea** [comment]
Use dudong0726 methods, I solved the problem, thank you.

**Comment by lvtanxi** [comment]
Windows 10 64bit
Material Theme UI 1.6.0.4
Android Studio
Can not display Chinese When I search in files, but the editor will not.

**Comment by mallowigi** [comment]
I fixed it in 1.6.1, try to download it and tell me the results

**Comment by mallowigi** [comment]
The last fix (1.6.1) will now use the current editor color scheme's font in search fields. Please try that and tell me the results

**Comment by DukeAnn** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/878#issuecomment-414567240
