### ISSUE TITLE
Update from 1.6.0.3 to 1.6.0.4 does not work

### ISSUE THREAD

**Issue by chrisonline** [ChrisRM/material-theme-jetbrains#636]
I get the info that an update is available to 1.6.0.4!
I hit Update and I see the "restart" info.

After restart of Android Studio I get again the info for the update 1.6.0.4!
Tried this several times. Seems there is a problem installing 1.6.0.4!

I am currently on 1.6.0.3 and Android Studio 3.0.1

**Comment by mallowigi** [comment]
then delete the plugin from the configuration folder and reinstall from scratch
