### ISSUE TITLE
Incorrect background color when in Welcome Screen

### ISSUE THREAD

**Issue by kmer1224** [ChrisRM/material-theme-jetbrains#637]
### Summary

Incorrect background color when in Welcome Screen.

### Expected behavior

None

### Actual behavior

<img width="780" alt="screen shot 2018-02-09 at 16 11 11" src="https://user-images.githubusercontent.com/13390788/36017830-51ec113c-0db4-11e8-8d40-3d023cdefef8.png">

### Steps to reproduce (if needed)

1. Open Android Studio and in welcome screen

### Environment

* macOS 10.13.3
* Android Studio 3.0.1
* Material Theme UI 1.6.0.4
* Both theme and scheme are in One Dark and the main IDE font is Source Code Pro (12 pt)

**Comment by mallowigi** [comment]
Currently Android Studio is based on 173.XXXX which is 2017.3, but I've stopped developing for 2017.3. I will check it again when they update to 181.XXXX

**Comment by kmer1224** [comment]
ok, thank you!!
