### ISSUE TITLE
Not all icons are monochrome

### ISSUE THREAD

**Issue by roboslone** [ChrisRM/material-theme-jetbrains#638]
PyCharm 2018.1 EAP (Professional Edition)
Build #PY-181.3263.12, built on January 30, 2018
PyCharm EAP User
Expiration date: March 1, 2018
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

Material Theme UI version: 1.8.0.2b3

I've noticed that protobuf icons aren't monochrome in "Project" view (Cmd+1) and "Navigate -> File" dialog. They are, however, monochrome in "Recent Files" dialog.

Also, OS X menus show huge icons now.
<img width="329" alt="screen shot 2018-02-09 at 18 25 10" src="https://user-images.githubusercontent.com/1941275/36034930-9b079ed8-0dc6-11e8-87c7-79cd610e8e1b.png">
<img width="281" alt="screen shot 2018-02-09 at 18 20 55" src="https://user-images.githubusercontent.com/1941275/36034931-9b263b22-0dc6-11e8-8596-d778ae5ab7bd.png">
<img width="374" alt="screen shot 2018-02-09 at 18 20 45" src="https://user-images.githubusercontent.com/1941275/36034932-9b41b1e0-0dc6-11e8-8a9a-e2d7438dea6e.png">
<img width="516" alt="screen shot 2018-02-09 at 18 20 34" src="https://user-images.githubusercontent.com/1941275/36034933-9b5e0426-0dc6-11e8-8dc1-6b817fe44c6c.png">

**Comment by mallowigi** [comment]
Hmm yeah... the only icons that are monochromed are the one provided by the plugin... I wonder if there is a way to apply to all icons...

**Comment by mallowigi** [comment]
Okay I managed to fix most of them, but I couldn't find how to for the rest. Guess that will be good enough.

**Comment by roboslone** [comment]
Thanks!
