### ISSUE TITLE
Uppercase buttons look bad with long text

### ISSUE THREAD

**Issue by roboslone** [ChrisRM/material-theme-jetbrains#639]
PyCharm 2018.1 EAP (Professional Edition)
Build #PY-181.3263.12, built on January 30, 2018
PyCharm EAP User
Expiration date: March 1, 2018
JRE: 1.8.0_152-release-1136-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3

Material Theme UI version: 1.8.0.2b3

In "Plugins" settings:
<img width="516" alt="screen shot 2018-02-09 at 18 27 28" src="https://user-images.githubusercontent.com/1941275/36035147-2337c968-0dc7-11e8-8674-5e4d4a010cb2.png">

With highlighting:
<img width="534" alt="screen shot 2018-02-09 at 18 29 38" src="https://user-images.githubusercontent.com/1941275/36035177-37a58f52-0dc7-11e8-84a2-0c5475938808.png">

**Comment by mallowigi** [comment]
I know that, this is why I made an option out of this. There is a limit on how much I can customize, and sadly this is one of them. If that bothers you then disable this option.

**Comment by roboslone** [comment]
Id doesn't bother me, other buttons look great! Just didn't know if you're aware of this.

**Comment by mallowigi** [comment]
I think that Jetbrains fixed the width in a lot of buttons, while some are ok (like Apply). I reduced the size and added more padding when in uppercase mode, so for most buttons it looks alright.
