### ISSUE TITLE
Pycharm freezes on Windows 8.1

### ISSUE THREAD

**Issue by gj1118** [ChrisRM/material-theme-jetbrains#64]
I install this theme for Pycharm 4.5 . I am on windows 8.1 . I have tried restarting my machine multiple times but nothing works. It seems that Pycharm has frozen and will not respond.. 

Can you please let me know what could be happening ?

Thanks

**Comment by ChrisRM** [comment]
I'm not sure. Try removing the plugin manually by deleting it from config/plugins. [This FAQ](https://devnet.jetbrains.com/docs/DOC-181) should show you the location of your plugins

**Comment by gj1118** [comment]
got it working by deleting the .idea folder inside the directory where my scripts were.
