### ISSUE TITLE
Breaks PyCharm 2018.1 EAP 4

### ISSUE THREAD

**Issue by roboslone** [ChrisRM/material-theme-jetbrains#640]
I'm also reporting this to jetbrains, but it seems like Material Theme UI bug.
PyCharm practically freezes on startup and slows OS as well.
<img width="1920" alt="screen shot 2018-02-09 at 18 36 08 2" src="https://user-images.githubusercontent.com/1941275/36035756-e8ca794a-0dc8-11e8-8da8-37bb00cbf2d0.png">

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/631
