### ISSUE TITLE
Compatibility with IntelliJ Platform 2018.1

### ISSUE THREAD

**Issue by bulenkov** [ChrisRM/material-theme-jetbrains#642]
Hi,
We recently refactored com.intellij.ide.ui.laf.intellij.MacIntelliJIconCache and moved it to com.intellij.ide.ui.laf.IconCache 
Could you please update MTTextFieldUI class. Thanks

![image](https://user-images.githubusercontent.com/4202603/36094845-11c81496-0ff0-11e8-842c-78e52374e582.png)

**Comment by kkmic** [comment]
We have deprecated but not deleted the following methods/classes/fields used in Material theme:

1) Deprecated com.intellij.ide.ui.laf.darcula.ui.TextFieldWithPopupHandlerUI constructor with parameter JTextField use com.intellij.ide.ui.laf.darcula.ui.TextFieldWithPopupHandlerUI default constructor instead
2) Deprecated com.intellij.ide.ui.laf.darcula.ui.DarculaTextFieldUI constructor with parameter JTextField, use com.intellij.ide.ui.laf.darcula.ui.DarculaTextFieldUI default constructor instead
3) Deprecated com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI constructor with parameter JComboBox, use com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI default constructor instead
4) Deprecated com.intellij.ide.ui.laf.darcula.ui.TextFieldWithPopupHandlerUI.myTextField field, use javax.swing.plaf.basic.BasicTextUI.getComponent() instead
5) Deprecated com.intellij.ide.ui.laf.intellij.MacIntelliJIconCache class and its getIcon() method, use more generic class name com.intellij.ide.ui.laf.IconCache. The MacIntelliJIconCache was essentially moved to the upper package and renamed to IconCache.

Please update your plugin to use new methods.

**Comment by mallowigi** [comment]
Thanks, I’ve already seen the updates and started working on it. They will be available soon but I’ll wait until a new eap is out in order to fix the sinceBuild
