### ISSUE TITLE
Lighter file name in inactive tab making it hard to read

### ISSUE THREAD

**Issue by chamisf** [ChrisRM/material-theme-jetbrains#644]
### Summary

In Material Lighter theme when edited file ( may be one under a versioning control system ) stay in a inactive tab it is hard see the file name.  See this.

![image](https://user-images.githubusercontent.com/10853008/36140049-e6507c5a-10c5-11e8-84f4-46b6bb317983.png)

### Expected behavior

It would be nice if file name color bit darker for edited files.

### Actual behavior

Lighter file names which is hard to distinguish.

### Steps to reproduce (if needed)

1. Edit file which is in subversion control system ( svn in my case)
2. Switch tab to other file
3. See the previous tab which is now inactive

You can also add Screenshots for a better understanding.

### Environment

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 30, 2018

JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
I am not pushing updates to 2017.3 values, sorry. You can change the color of the modified files from the Material File Colors inside the Color Scheme.
