### ISSUE TITLE
Project tree arrow's margin

### ISSUE THREAD

**Issue by domenico-ruggiano** [ChrisRM/material-theme-jetbrains#648]
### Summary

In the project tree the margin between the arrows and the folder icons is not enough. 

### Screenshot

![screenshot 17 _li](https://user-images.githubusercontent.com/30785662/36340887-da9a1ac4-13e5-11e8-9c50-42eb488a5551.jpg)

You can see it where the are the red dots, when the arrow is expanded it overlaps with the file icon.

### Environment

IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017

JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Plugin version: Material Theme UI v1.6.1

My pc is a Dell XPS with **Touch-screen InfinityEdge Ultra HD 4K da 15,6" (3.840 x 2.160) display.**

**Comment by mallowigi** [comment]
Its' because you changed the Custom Tree Indent setting

**Comment by domenico-ruggiano** [comment]
@mallowigi no, it isn't. I did not changed the Custom Tree Indent setting. 

I've seen that setting and trying to change it and setting it to the max value of **10**, the arrow it's almost still touching the icon folder
