### ISSUE TITLE
Viewport split icons are the Nintendo Switch logo...

### ISSUE THREAD

**Issue by ds84182** [ChrisRM/material-theme-jetbrains#653]
### Summary

The viewport split icons are the logo for the Nintendo Switch.

### Expected behavior

For them to not be the logo for the Nintendo Switch.

### Actual behavior

They're the logo for the Nintendo Switch.

### Steps to reproduce (if needed)

1. Right click a file in a tab.
2. Observe the icon to the left or right of the split horizontal and split vertical buttons.
3. https://commons.wikimedia.org/wiki/File:Nintendo_Switch_Logo.svg

### Environment

I'm quite sure I don't need to provide any environment information at this point. I've just installed the theme today :)

Anyways, an alternative would be https://material.io/icons/#ic_view_stream

**Comment by ds84182** [comment]
Forgot to provide a screenshot:

![image](https://user-images.githubusercontent.com/2268005/36404807-05df5024-15bb-11e8-81af-05ee745fbafd.png)

**Comment by BHSPitMonkey** [comment]
I noticed this too, today, and think it's amusing... but why include a product's trademark in an MIT-licensed theme like this?

**Comment by mallowigi** [comment]
The icons are taken from https://materialdesignicons.com and I didn’t break any rules so I don’t understand what the fuss is about

--
Elior

**Comment by guilhermesteves** [comment]
Maybe you should change to [arrow-split-vertical](https://materialdesignicons.com/icon/arrow-split-vertical) and [arrow-split-horizontal](https://materialdesignicons.com/icon/arrow-split-horizontal) to avoid further problems with Nintendo

**Comment by mallowigi** [comment]
I’ve changed it anyways in the next version
