### ISSUE TITLE
Sidebar border color issue.

### ISSUE THREAD

**Issue by mikenovikov** [ChrisRM/material-theme-jetbrains#655]
![sidebar-divider-issue](https://user-images.githubusercontent.com/4421441/36421656-6f68cf90-164a-11e8-8915-c9ca50e32162.png)
### Summary
Border color changing sometimes. 

### Expected behavior
Should be #262626, but sometimes is #0f0f0f.

### Steps to reproduce (if needed)
1. Open sidebar (or any other tool window)
2. Click on editor, then on sidebar. 
3. Resize tool window.

### Environment
* Mac OS X 10.13.3
* Build #IU-173.4548.28, built on January 30, 2018
* Plugin version: latest

**Comment by mallowigi** [comment]
wait for this to be merged https://github.com/JetBrains/intellij-community/commit/9951bd829cf07fa101a6de7594a6357b818a0d17

**Comment by mallowigi** [comment]
Happens again on Webstorm 2018.1

**Comment by mallowigi** [comment]
Jeez it's still hardcoded... f*ck it.

**Comment by rikiless** [comment]
Is it possible to hide that border or change its color? thanks
