### ISSUE TITLE
How can I only use the color scheme, and nothing else.

### ISSUE THREAD

**Issue by Gino** [ChrisRM/material-theme-jetbrains#656]
Hi,

I would like to **only** use the color scheme, nothing else. By installing the plugin, everything is activated and when I manually disable components, my IDE is already affected ..

Basically when I install the plugin, my whole IDE is ruined ..
I would like to **only** have the color scheme, no sidebar affects and such.

**Comment by mallowigi** [comment]
just export the bundled color schemes and uninstall the plugin

**Comment by mallowigi** [comment]
You should be able to disable everything: components, fonts, theme colors, icons... from the settings. Though I must admit that it is a use case that I don't check very often so it might still not working completely.
