### ISSUE TITLE
Add border while using 'Split Vertically'

### ISSUE THREAD

**Issue by adwil13** [ChrisRM/material-theme-jetbrains#659]
This is something between bug and feature request ;)

Right now it looks like this:
![image](https://user-images.githubusercontent.com/6338635/36594095-081a61dc-189d-11e8-8822-b816aeca3198.png)

And you can't really tell where is resize handle because border is missing.

It should look something like this (notice the grey line next to scrollbar):
![image](https://user-images.githubusercontent.com/6338635/36594306-e5d4391c-189d-11e8-8594-7a16b1775035.png)

**Comment by mallowigi** [comment]
fixed in 2.1.3
