### ISSUE TITLE
Dark title bar not working in Android Studio

### ISSUE THREAD

**Issue by jeroenboumans** [ChrisRM/material-theme-jetbrains#660]
### Summary

I've installed the latest stable version (3.0.1) of Android Studio. I've also got PHP Storm EAP and Webstorm EAP installed. The last two seem to have the option available to darken the title bar. In Android Studio this is not the case.

A screenshot of WebStorm: https://i.imgur.com/ujuD1L7.png
A screenshot of Android Studio: https://i.imgur.com/LHUHkxv.png

### Expected behavior

It should show the "Toggle Dark Title Bar" option in the toolbar menu.

### Actual behavior

I've installed the latest stable version (3.0.1) of Android Studio. I've also got PHP Storm EAP and Webstorm EAP installed. The last two seem to have the option available to darken the title bar. In Android Studio this is not the case.

### Steps to reproduce (if needed)

1. Install Android Studio 3.0.1. 
2. Install Material Theme UI 1.6.1
3. Install Material Theme UI via Preferences / Tools / Plugins
4. Restart Android Studio
5. Check the toolbar menu if it says "Toggle Dark Title Bar".

### Environment

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

Plugins:
Material Theme UI 1.6.1

**Comment by mallowigi** [comment]
Yes this is not supported because Android Studio is still on previous versions of IntelliJ

It will change as soon as they migrate to the 2017.3 versions
