### ISSUE TITLE
Quick Doc tooltips missing material colors

### ISSUE THREAD

**Issue by brianegan** [ChrisRM/material-theme-jetbrains#665]
First: You're awesome. Thanks so much for this plugin!

Second, sorry if this is a duplicate -- I searched the Issues and Readme and didn't find a similar issue, but I might have missed it.

### Summary

Quick Documentation windows contain a mix of Material and Darcula colors.

### Expected behavior

The tooltip shows up with those beautiful Material UI colors.

### Actual behavior

It shows Darcula in some places, material in others.

<img width="908" alt="screen shot 2018-02-28 at 1 33 09 pm" src="https://user-images.githubusercontent.com/126604/36788396-0d277de6-1c8e-11e8-8d93-d542fb0703ba.png">

### Steps to reproduce (if needed)

  1. Enable "Show quick documentation on mouse move" feature in Settings > General
  2. Hover over a class that contains documentation
  3. See the Documentation window pop up
  4. Notice it uses Darcula colors rather than Material Theme UI colors

### Environment

IntelliJ IDEA 2017.3.4 (Community Edition)
Build #IC-173.4548.28, built on January 30, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

**Comment by mallowigi** [comment]
- I fixed the header in the latest builds, it is available on 2018.1 only.
- As for the main content, you're right. I'll try to look into it.

**Comment by brianegan** [comment]
Cool, thanks again :)

**Comment by mallowigi** [comment]
It looks like they updated their documentation component on 2018.1, and it looks fine with it, so I,m gonna close this one as I am not releasing for previous versions

**Comment by brianegan** [comment]
Yep, no worries. Thanks for checking it out! I'll wait for 2018.1 stable
