### ISSUE TITLE
not project file and decompiled source code tab color are irritating

### ISSUE THREAD

**Issue by jeffrey-igaw** [ChrisRM/material-theme-jetbrains#667]
### Summary

After update material ui, unsolution files and decompiled source codes tab is irritating. (So..Red..)

please change to little yellow? or how can i change that?

(this is atom one dark theme)

![image](https://user-images.githubusercontent.com/30995427/36884032-9410cc42-1e21-11e8-9405-36c49167951b.png)

### Environment

```
JetBrains Rider 2018.1 EAP
Build #RD-181.3782.222, built on February 23, 2018
Rider EAP User
Expiration date: March 25, 2018
JRE: 1.8.0_152-release-1136-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

![image](https://user-images.githubusercontent.com/30995427/36884058-ba281458-1e21-11e8-9e53-74ff52dcff4d.png)

**Comment by mallowigi** [comment]
You can change it under Settings > Appearance > File Colors > Non project files

Then edit and select the material background color in the list.

It should not be red but I think I have an idea why it is. I’ll take a look

**Comment by jeffrey-igaw** [comment]
Ok i will try that next monday!
Thanks to your help

**Comment by jeffrey-igaw** [comment]
![image](https://user-images.githubusercontent.com/30995427/37071465-f9aeec64-21ff-11e8-8bb6-2216abcb9725.png)

![image](https://user-images.githubusercontent.com/30995427/37071471-014110ba-2200-11e8-8e5f-8e97f98431d5.png)

Hmmmmm, i don't know, i changed File Colors > Non project files, but the red background color is not Non Project Files color..

**Comment by mallowigi** [comment]
Hummm you are in Rider as I can see... I haven’t tested on Rider for a while, I will check it when I have the time. In the meantime you can revert to a previous version from the plugins page.

--
Elior

**Comment by mallowigi** [comment]
I can see that Rider doesn't let the user customize the oclors... Anyway the next version will have a darker red, but for the moment just disable file colors or exclude the files from the list from the toolWindow menu
