### ISSUE TITLE
Theme name with fuzzy font

### ISSUE THREAD

**Issue by strongbugman** [ChrisRM/material-theme-jetbrains#669]
### Summary
We can see the "Material Oceanic" is very vague：
![image](https://user-images.githubusercontent.com/16114285/37071816-6133cc62-21f9-11e8-88d8-2a02fe50ad04.png)

### Expected behavior
Clear font

### Actual behavior
Fuzzy font

### Steps to reproduce (if needed)

Just open the IDE

### Environment

PyCharm 2017.3.3 (Community Edition)
Build #PC-173.4301.16, built on January 11, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3(2016 MacBookPro)

**Comment by mallowigi** [comment]
It’s intended .
