### ISSUE TITLE
At the top of the color is not easy to distinguish

### ISSUE THREAD

**Issue by huclengyue** [ChrisRM/material-theme-jetbrains#67]
![qq20151014-1](https://cloud.githubusercontent.com/assets/9107717/10476323/52bfbea6-727f-11e5-9ff2-988ced5013a4.png)
The color  not easy to distinguish,I don't the currently selected。
How can I modify the color.

**Comment by ChrisRM** [comment]
Download the newest build. It should have a bottom border on the active tab
