### ISSUE TITLE
PyCharm SciView display issues

### ISSUE THREAD

**Issue by blitzd** [ChrisRM/material-theme-jetbrains#670]
### Summary

In the new SciView in PyCharm any 'View as DataFrame' seems to have excessive padding on the fonts, causing only half of the text to be viewable. When clicking on any of the values it does display it properly without so much padding, but both the normal display and hover have the excessive padding.

### Expected behavior

This (but with Material Theme applied):

![image](https://user-images.githubusercontent.com/1502984/37158178-c3022ba4-22b8-11e8-8edc-130f268b2177.png)

### Actual behavior

This:

![image](https://user-images.githubusercontent.com/1502984/37158192-cda8e3ea-22b8-11e8-90ab-b1fa921822f5.png)

### Steps to reproduce (if needed)

View Pandas dataframe with Material UI theme.

### Environment

PyCharm 2017.3.3 (Professional Edition)
Build #PY-173.4301.16, built on January 11, 2018
JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.6-300.fc27.x86_64
Material Theme UI 1.6.0.4

.xml is:

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="1.6.0.4" />
    <option name="highlightColor" value="80cbc4" />
    <option name="isContrastMode" value="true" />
    <option name="accentColor" value="80cbc4" />
    <option name="tabsHeight" value="25" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Please check the option "Compact Table Headers" or something like that.

**Comment by blitzd** [comment]
'Compact Table Cells' - not sure why I didn't see that when I was looking before, but thanks!
