### ISSUE TITLE
Look up list for code completion stays visible after switching to another application

### ISSUE THREAD

**Issue by ignmc** [ChrisRM/material-theme-jetbrains#674]
### Summary

This have been bothering me for some time in Android Studio. After partially writing some code, the code completion list pops up. If I open the documentation of any of the suggested methods/variables/etc and then switch to another app by pressing alt + tab or clicking in the taskbar, the lookup list stays on top of this other app. I can even interact with the suggestions (double clicking one of them autocompletes my code normally in the editor).
The problem disappeared after uninstalling the theme.

### Expected behavior

The lookup list disappears when switching to another app.

### Actual behavior

The lookup list stays visible, blocking interaction with whatever is behind it.

![untitled](https://user-images.githubusercontent.com/28968411/37375079-d3d42570-26fc-11e8-9e19-2e106a157157.png)

### Steps to reproduce

1. Type some code until the code completion list appears

![untitled2](https://user-images.githubusercontent.com/28968411/37375215-63f2f262-26fd-11e8-8ab7-3be93a0ecdbd.png)

2. Press ctrl + q to open the documentation of any of the suggestions.

![untitled3](https://user-images.githubusercontent.com/28968411/37375320-c445baaa-26fd-11e8-83b8-8f79eba57438.png)

3. Press Alt + Tab to switch to another app or click it in the taskbar. The frame with the documentation disappears but the list with the suggestions doesn't.

![untitled4](https://user-images.githubusercontent.com/28968411/37375443-627797b6-26fe-11e8-8346-fb86245db78a.png)

When this happens I have to go back to Android Studio, press Esc and then go back to my app.

I was unable to reproduce it in IDEA.

Also, when you open the suggestion list with Ctrl + Espace, the ide will automatically show the documentation of whatever element is highlighted in the list (without pressing Ctrl + Q), reducing the steps required to reproduce the issue and making it appear more frequently.

### Environment

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

```
<application>
  <component name="MaterialThemeConfig"> 
    <option name="version" value="1.6.1" /> 
    <option name="highlightColor" value="80cbc4" /> 
    <option name="highlightColorEnabled" value="true" /> 
    <option name="accentColor" value="80cbc4" /> 
  </component>
</application>
```

I'm not entirely convinced that the problem is the plugin , but seeing the problem disappear when I uninstalled it made me report it here.

**Comment by mallowigi** [comment]
I'm also aware of this, but I don't see why it could be related to the plugin. If it is I need to know why, it's interesting.

**Comment by mallowigi** [comment]
Alright, I've taken a look and it looks it was resolved on the latest version of Canary so I'm closing this
