### ISSUE TITLE
Overriding Settings

### ISSUE THREAD

**Issue by jaqxues** [ChrisRM/material-theme-jetbrains#679]
When installing it, Material Theme UI overrides the preferences (e g the font styles). It might be useful to implement a dialog to let the user know that and recommend exporting the settings as a backup. Alternatively, a backup option that backs the \.AndroidStudio3.0\config\colors and \.AndroidStudio3.0\config\codestyles up would be a practical feature.

**Comment by mallowigi** [comment]
It doesn't, it just changes the font of the IDE. If you set a custom font yourself it should not override it. Also, disabling the "Material fonts" option should revert this feature
