### ISSUE TITLE
Icons disappear

### ISSUE THREAD

**Issue by jobdtc** [ChrisRM/material-theme-jetbrains#68]
All icons disappear after some time.

![screenshot 2015-10-14 09 16 15](https://cloud.githubusercontent.com/assets/9447525/10477154/38ebd4ae-7254-11e5-9636-131bc391f33e.png)

I use the following java version according to my terminal.

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

I'm on OS X 10.10.4 with PHPStorm 9.0.2

**Comment by ChrisRM** [comment]
Seems to be an issue with JDK 1.6. Try downloading PhpStorm with bundled JDK 1.8. Visit https://www.jetbrains.com/phpstorm/download/, beneath the download button, you'll find "Using OS X 10 Yosemite? Get PhpStorm 9 with JDK 1.8".

**Comment by jobdtc** [comment]
Cool! Downloaded that version. My colleague is using the 1.8 version too, but he has the cool elephant php icons. How do I fix these?

**Comment by jobdtc** [comment]
Nevermind, these seems to be fixed with the new version!
Thanks for your help.
