### ISSUE TITLE
v2.0.0 introduced borders in menus and bottom of menubar.

### ISSUE THREAD

**Issue by gencer** [ChrisRM/material-theme-jetbrains#682]
### Summary

There is a border between toolbar and menubar. This was not exists until v2.0.0. It could be requested earlier by someone else but, is there any way to make borders disappear or at least "0px"? I do not want to see unnecessary borders.

**Note:** I know this could be an expected behavior. But my one of primary reasons to use material theme is, it hasn't so much borders and unnecessary colorizing in IDE. At least if we can have an option like "Disable borders", that would be great.

### Expected behavior

No borders like older versions of this theme.

### Actual behavior

v2.0.0 introduced borders. Especially bottom of menubar.

![image](https://user-images.githubusercontent.com/1711576/37643006-42b7180c-2c30-11e8-8426-b96290204006.png)

### Environment

RubyMine 2018.1 EAP
Build #RM-181.4203.207, built on March 15, 2018
RubyMine EAP User
Expiration date: April 14, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
I agree for the option. I will do it in a further release

**Comment by gencer** [comment]
Glad to hear that! I will patiently await for this feature.

**Comment by gencer** [comment]
@mallowigi, those borders comes back with 2018.2 release (currently working on RubyMine 2018.2 EAP)

Also there is an issue with bg of dropdown:

![image](https://user-images.githubusercontent.com/1711576/41808154-26e29bc2-76e2-11e8-8672-4906b6180e55.png)

**Comment by mallowigi** [comment]
The dropdowns are ok, this has been changed into a select menu instead. As for the separators, I’ll check if I want to change it, imo it’s okay like this
