### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Polyterative** [ChrisRM/material-theme-jetbrains#683]
Your readme is not working properly:
```
<script type='text/javascript' src='https://ko-fi.com/widgets/widget_2.js'></script><script type='text/javascript'>kofiwidget2.init('Buy Me a Coffee', '#46b798', 'U7U27VXE');kofiwidget2.draw();</script>
```

**Comment by mallowigi** [comment]
Yeah i know but whatever. It seems that the "ko-fi" page is not serving the widget.

I will remove this one day, it's not like anyone is buying me a coffee anyway!
