### ISSUE TITLE
keep the bread crumbs icon in navigation bar more material

### ISSUE THREAD

**Issue by dudong0726** [ChrisRM/material-theme-jetbrains#684]
![image](https://user-images.githubusercontent.com/1704803/37654490-3666041c-2c7d-11e8-8dd2-1868231e43de.png)

is any plan change those icon to the material one?

**Comment by mallowigi** [comment]
Good idea!

**Comment by dudong0726** [comment]
the newNavBarUI is very cool ,good job!
