### ISSUE TITLE
the folder icon size is different

### ISSUE THREAD

**Issue by dudong0726** [ChrisRM/material-theme-jetbrains#686]
![image](https://user-images.githubusercontent.com/1704803/37701188-0c7d5720-2d29-11e8-8f63-7eae588771ea.png)
![image](https://user-images.githubusercontent.com/1704803/37701303-5ef89988-2d29-11e8-9b3b-46a9af33ac72.png)

just like above

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.400, built on March 19, 2018
Licensed to lan yu
Subscription is active until October 14, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
plugin version: 2.0.1

**Comment by mallowigi** [comment]
It looks like you have  a custom resolution... What is your DPI ?

**Comment by mallowigi** [comment]
It looks like every icon get a custom scale except for the folders.

**Comment by mallowigi** [comment]
Did you change the font size in Appearance?

**Comment by dudong0726** [comment]
yes

**Comment by mallowigi** [comment]
I saw it happens, this is a weird artifact and I don't have the strength to find the cause. Once you restart the IDE everything becomes fine.

**Comment by dudong0726** [comment]
yep
