### ISSUE TITLE
File icons doesn't show

### ISSUE THREAD

**Issue by claudioviola** [ChrisRM/material-theme-jetbrains#687]
### Summary
File icons doesn't change after that I installed the plugin
...

### Steps to reproduce (if needed)

1. Install plugin
2. Active plugin
3. Restart webstorm

Screenshot here
![schermata 2018-03-21 alle 11 33 44](https://user-images.githubusercontent.com/6689594/37705374-194cf032-2cfc-11e8-951d-293b1d0cf7e4.png)

### Environment
Webstorm 2017.3.4
Material Theme 1.6.1

**Comment by mallowigi** [comment]
Do you have the Material File Icons option checked ?

**Comment by claudioviola** [comment]
Based on this I think so
![schermata 2018-03-21 alle 14 40 11](https://user-images.githubusercontent.com/6689594/37712966-c74f871c-2d15-11e8-9630-46c73db3322e.png)

**Comment by mallowigi** [comment]
I remember someone reporting this in the past. Can you Invalidate Cache and Restart (File > Invalidate cache) and check again?

**Comment by claudioviola** [comment]
I have just tried but nothing has changed...

**Comment by mallowigi** [comment]
Also make sure that you aren't in Power Save mode

**Comment by claudioviola** [comment]
Fantastic! Works!!
many thanks!
