### ISSUE TITLE
the absent theme disappear when restart IDEA

### ISSUE THREAD

**Issue by dudong0726** [ChrisRM/material-theme-jetbrains#689]

**Comment by dudong0726** [comment]
the new version 2.1 the External Themes is disabled !

**Comment by mallowigi** [comment]
It wasn’t intended to be in the release, it’s going to be in a separate plugin to demonstrate the external themes feature.

I will post something in the website as soon as it is ready.

**Comment by dudong0726** [comment]
a good feature. i like the absent mode
