### ISSUE TITLE
Staying updated with user-defined colors within the text editor only

### ISSUE THREAD

**Issue by ciscorucinski** [ChrisRM/material-theme-jetbrains#69]
I really like your overall project here. 

I have been wanting a Material themed IDE but never really had the experience in doing it myself. After looking at your modifications, I decided to try modifying it to fit my design aesthetics. I have a project that I really love, but I also want to stay updated to your current builds.

How can a person mitigate issues with your modifications of the whole IDE with my user-defined modifications of the source code coloring only??

**Comment by ChrisRM** [comment]
I assume you've created a copy of the color scheme of your choice and made your own modifications. By doing so, this plugin will not override your custom scheme. 

On that note, I will be creating a more generic theme soon, which will update the entire UI according to your editors color scheme.

**Comment by ciscorucinski** [comment]
Ok, so I can just update to your newest build, and then just switch to my custom scheme. That sounds good.

That seems like a huge feat right there. Updating the whole UI based on my editors color scheme. Would be nice to see how that works.

**Comment by ciscorucinski** [comment]
Anyways, you are looking for requests in color schemes. 

I am new to more advanced features of Git / GitHub. 

I would like to contribute my color scheme. I just need to fork this project, but was trying to figure out where I would insert my color scheme files.

**Comment by ChrisRM** [comment]
This should get you going pretty fast: https://help.github.com/articles/using-pull-requests/

**Comment by ChrisRM** [comment]
> Updating the whole UI based on my editors color scheme. Would be nice to see how that works.

It will set the background, borders and text color according to the
