### ISSUE TITLE
Write-unsafe context! error

### ISSUE THREAD

**Issue by Jamesking56** [ChrisRM/material-theme-jetbrains#690]
### Summary
When updating my IDE settings, an error comes up afterwards stating that there has been an exception in the Material Theme UI.

### Expected behavior
I save the settings and no error box appears.

### Actual behavior
An error appears after saving my general IDE settings:

![screenshot from 2018-03-22 09-12-20](https://user-images.githubusercontent.com/253237/37761291-27b777cc-2db1-11e8-94e9-8a76494ebe41.png)

### Steps to reproduce (if needed)

1. Install Material Theme UI.
2. Select `Arc Dark` as your theme.
3. Open `File -> Settings...`
4. Change and save a setting.

### Environment

PhpStorm 2017.3.6
Build #PS-173.4674.46, built on March 15, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-116-generic

My OS is Ubuntu 16.04 LTS Desktop

**Comment by mallowigi** [comment]
won't fix for 2017.3, sorry
