### ISSUE TITLE
Fuzzy (duplicated) text in path box of "Find in path" window when using "Directory"

### ISSUE THREAD

**Issue by Proteo** [ChrisRM/material-theme-jetbrains#692]
### Summary

The text in the path box of the "Find in path" window appears fuzzy, it looks like the text is duplicated because you can delete it and a copy remains visible behind the cursor:

Opening the window, with Material Theme UI:

![screen shot 2018-03-23 at 1 58 39 pm](https://user-images.githubusercontent.com/376077/37846152-21e2bc88-2ea3-11e8-9edc-fc8a8fd37b76.png)

After actually **_deleting_** the text in the box:

![screen shot 2018-03-23 at 2 07 01 pm](https://user-images.githubusercontent.com/376077/37846283-8508a37c-2ea3-11e8-964a-598ced23b407.png)

Opening the window, without Material Theme UI:

![screen shot 2018-03-23 at 2 26 58 pm](https://user-images.githubusercontent.com/376077/37847186-594febe8-2ea6-11e8-8cf8-13e30a4c186a.png)

After deleting the text, without Material Theme UI:

![screen shot 2018-03-23 at 2 28 24 pm](https://user-images.githubusercontent.com/376077/37847223-85f6da94-2ea6-11e8-8d19-df6c692b60fe.png)

### Steps to reproduce

1. Install Material Theme UI.
2. Open the "Find in path" dialog window, select the "Directory" option. Enter some text and click somewhere else so the box loses focus.

### Environment

Material Theme UI 2.1.1
PhpStorm 2018.1 EAP
Build #PS-181.4203.513, built on March 21, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
macOS 10.13.3

**Comment by mallowigi** [comment]
Yeah i know, I've already fixed it, it will be available in 2.1.2.
