### ISSUE TITLE
Tabbed Pane is wrong in Lighter themes

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#694]

**Comment by IceMan81** [comment]
Is this referring to the issue where the selected tabs when using light themes like Solarized Light are not visible?
I've an issue with the the tabb colors and wanted to confirm before I opened a new issue.

**Comment by popovdenys** [comment]
Do we both speak about the same issue : (https://youtrack.jetbrains.com/issue/WEB-31801) ?

Regards

**Comment by mallowigi** [comment]
@IceMan81 I’m referring to tabs such as the ones found in “Spelling” in the settings.

What is it you are talking about?

**Comment by IceMan81** [comment]
I’m referring to the tabs in different panels like version control. For example, if the “log” tab is chosen under Version Control, the active tab color makes the tab name difficult to read.
