### ISSUE TITLE
Unthemed panel headers in WebStorm 2018.1 final

### ISSUE THREAD

**Issue by hoichi** [ChrisRM/material-theme-jetbrains#699]
### Summary

After upgrading to WebStorm 2018.1, all the panel headers are pale grey on white.

### Expected behavior

Panel headers should be themed like everything else.

### Actual behavior

![image](https://user-images.githubusercontent.com/3592345/37958605-a31c2ffa-31b9-11e8-940b-8fa9fececb16.png)

![image](https://user-images.githubusercontent.com/3592345/37958662-bcef8224-31b9-11e8-8dba-f8e97339046a.png)

### Steps to reproduce (if needed)

1. Run WebStorm
2. Open any panel
3. Try changing Matherial Theme or looking in custom colors.

### Environment

WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
Licensed to Sergey Samokhov
Subscription is active until May 8, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-42-generic

My Linux is Mint 18.3 w/Cinnamon.

**Comment by mallowigi** [comment]
Which theme have you selected?

**Comment by hoichi** [comment]
Tried several: Oceanic, Pale Night & Arc Dark. Text color in headers does change, but not the headers’ background.

**Comment by hoichi** [comment]
And here’s a header with Material Theme toggled off.
![image](https://user-images.githubusercontent.com/3592345/37964203-57f4407a-31c9-11e8-9376-d103c7fe4d21.png)

**Comment by hoichi** [comment]
And by the way, a focused panel’s header has a different background. Not sure if it was the case in earlier versions.
![image](https://user-images.githubusercontent.com/3592345/37964412-124aa5ae-31ca-11e8-9cce-9b760632cae2.png)

**Comment by mallowigi** [comment]
Which version of the plugin do you have?

**Comment by hoichi** [comment]
Man! I was still on `Material Theme UI EAP` for some reason. I guess I’ve updated it in my Windows installation, but not under Mint. Or maybe JetBrains updater imported an obsolete plugin config from somewhere.

Either way, the problem is gone after reinstalling plugin. Sorry about that and thanks for your time and for the great work!
