### ISSUE TITLE
New build

### ISSUE THREAD

**Issue by ChrisRM** [ChrisRM/material-theme-jetbrains#7]
I've managed to pack everything inside a single installable plugin.

**Installation**
1. Download [Material Theme.jar](http://cdn.hifive.no/material-ui/Material%20Theme.jar)
2. Open `Preferences` -> `Plugins` - > `Install plugin from disk...` and choose the jar.

That's it. Starting to look alright I think. Let me know how it goes. Still have a way to go with the UI icons.

**PhpStorm only, only tested on OS X.**. Separate versions for other platforms coming soon.

<img width="1440" alt="screen shot 2015-10-03 at 02 14 34" src="https://cloud.githubusercontent.com/assets/309292/10260483/8acd06a8-6976-11e5-8162-1ddaef05d4e8.png">

**Comment by B-iggy** [comment]
Good work!
For me (Windows 10) it's not quite finished yet ;)
![phpt](https://cloud.githubusercontent.com/assets/7815434/10261820/3901b636-69ab-11e5-808b-c9a44cdc222f.PNG)
It's like a GTK Theme for windows. Ugly buttons and missing contrast here and there.

I have to change the "Look and Feel" to Windows, then back to Darcula for nice UI again.
Unfortunately this is all reset to your plugin theme when I'm restarting. So for now I can't use your plugin and only pick the .icls theme color scheme.

Without a windows machine it will be hard but hopefully you get it! :+1:

**Comment by ChrisRM** [comment]
I'll look into it. Think its an easy fix actually.

**Comment by ChrisRM** [comment]
@B-iggy can you try to download the new build? Should fix the colors.

**Comment by B-iggy** [comment]
Very nice Chris! :) Looks good. Only the "Tip of the Day" text is not white but I don't care. Only for style points ;)

Good job and thanks!

![phps](https://cloud.githubusercontent.com/assets/7815434/10264835/893bf57c-6a18-11e5-9d19-1af45a7dcd2a.jpg)

**Comment by levan1993** [comment]
What about "Darker" theme?

**Comment by ChrisRM** [comment]
Its on my todo-list, but I have a crazy amount of icons to convert first..

**Comment by slovenianGooner** [comment]
Getting a crazy tab color on Mac OS X (yeah Chris, I bought a Mac).

<img width="1680" alt="screen shot 2015-10-04 at 15 27 12" src="https://cloud.githubusercontent.com/assets/1257629/10268049/aaf7ba18-6aac-11e5-8395-84485619821e.png">

**Comment by ChrisRM** [comment]
@slovenianGooner Fixed in the newest [build](http://cdn.hifive.no/material-ui/Material%20Theme.jar). Also added a ton of new file icons.

**Comment by slovenianGooner** [comment]
Yup, all fine and dandy now! Cheers for the speedy response.
