### ISSUE TITLE
BG Color is brown

### ISSUE THREAD

**Issue by visualcookie** [ChrisRM/material-theme-jetbrains#70]
When no file is opened, there's this box that tells you that there are no files opened and what you can do to open one. Problem is, that this window in the editor is still brown and looks weird to me (See Screenshot).

![appcom-web-mensa_-___applications_ampps_www_appcom-web-mensa_](https://cloud.githubusercontent.com/assets/1857554/10488376/a94dfb84-7298-11e5-98fc-a1eaf3afbfdf.png)

**Comment by EspadaV8** [comment]
That looks grey to me in your screenshot and a colour picker says that it's #353536 which is definitely a grey. Could your monitor colour calibration be out?

**Comment by blazeworx** [comment]
:+1: Also experiencing this. 

![image](https://cloud.githubusercontent.com/assets/4718238/10503821/cf734b0a-72c7-11e5-86bf-06c157a14c05.png)

**Comment by EspadaV8** [comment]
@blazeworx your screenshot look brown to you? Colour picking that gives me #282829 which is grey (although a different grey from @visualcookie) and neither of your screenshots look brown to me

**Comment by blazeworx** [comment]
Its not brown, but its not a color from the theme. It is a grey, from the built-in Darcula UI.

**Comment by visualcookie** [comment]
Sorry, I do have an iMac which reflects myself pretty bad, that's why I first thought it's brown.

**Comment by mpiffault** [comment]
I think it looks brown because the dominant color of the theme is blueish. I agree with @blazeworx it's a bit discordant.

**Comment by Landish** [comment]
Having the same issue, does anybody know, how to fix this?

**Comment by mallowigi** [comment]
I actually happen to like it like this. It does a good contrast.

**Comment by mallowigi** [comment]
Since it was hard to change the color as it is hardcoded in the code, instead I made use of the "set background" feature to show a nice background, changeable thru the settings.

Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.
