### ISSUE TITLE
Flat buttons & fields don't work anymore

### ISSUE THREAD

**Issue by Flynrod** [ChrisRM/material-theme-jetbrains#700]
### Summary

I have updated IntelliJ IDEA for version 2018.1 (latest right now). And I updated Material UI too.

### Expected behavior

That the fields and flats of Material UI are displayed.

### Actual behavior

These are the macOS system buttons that are displayed.
![2018-03-28 14 41 45](https://user-images.githubusercontent.com/29288223/38029447-2cbf8bd0-3296-11e8-9462-bc534be8a3be.png)

### Steps to reproduce (if needed)

1. Update IntelliJ idea from 2017.**X** to 2018.1
2. Browse plugins IntelliJ IDEA and update Material UI to latest version
3. Restart IntelliJ IDEA

### Environment

* IntelliJ IDEA 2018.1 (Ultimate Edition)
* Build #IU-181.4203.550, built on March 26, 2018
* Licensed to [private]
* Subscription is active until October 1, 2018
* JRE: 1.8.0_152-release-1136-b20 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.13.3

**Comment by mallowigi** [comment]
Make sure the "Material Design" checkbox is checked

**Comment by Flynrod** [comment]
I checked "**Material Components**" and it works! Thank's!
