### ISSUE TITLE
does not support Webstorm 2018.1

### ISSUE THREAD

**Issue by Macfly** [ChrisRM/material-theme-jetbrains#702]
### Summary
Just updated Webstorm to the last version and the plugin is not compatible the the version installed.

### Expected behavior
Material theme

### Actual behavior
Stock theme

### Environment

WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
Licensed to WebStorm Evaluator
Expiration date: April 27, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by carlosflorencio** [comment]
I'm getting the same behaviour after upgrading to 2018.1.

Since you closed this, did you found a workaround?

**Comment by Macfly** [comment]
Yes. The version installed on webstorm was outdated (it was version 1.6).i
removed it and installed the last version manually (downloaded from the
website and installed for file)
