### ISSUE TITLE
Tasks & Context creating error and disabling the plugin

### ISSUE THREAD

**Issue by fearlex** [ChrisRM/material-theme-jetbrains#707]
### Summary

When adding a new Task & Context server, the settings can't be saved and the plugin gets disabled.

![screen shot 2018-03-30 at 11 42 14 am](https://user-images.githubusercontent.com/89010/38143698-bd0bcce2-340f-11e8-97f8-b720235b3744.png)

![screen shot 2018-03-30 at 11 35 32 am](https://user-images.githubusercontent.com/89010/38143703-c1f86ada-340f-11e8-978b-64a104189c79.png)

### Expected behavior

Task & Content servers can be saved without getting a conflict with Material UI plugin.

### Actual behavior

It Throws an exception and disables the plugin.

### Steps to reproduce (if needed)

1. Go to Settings/Tools/Task/Servers
2. Try adding a new server (ex Trello)
3. Trying applying the changes.

![screen shot 2018-03-30 at 11 42 14 am](https://user-images.githubusercontent.com/89010/38143759-fe52ec3a-340f-11e8-86b2-79a92a35366a.png)
![screen shot 2018-03-30 at 11 35 32 am](https://user-images.githubusercontent.com/89010/38143760-fe8f4360-340f-11e8-903f-b18dc6cea722.png)

### Environment

PhpStorm 2018.1
Build #PS-181.4203.565, built on March 28, 2018
JRE: 1.8.0_152 - release - 1136 - b20 x86_64
JVM: OpenJDK 64 - Bit Server VM by JetBrains s . r . o
macOS 10.13.4

**Comment by mallowigi** [comment]
Can't reproduce on PHPStorm MacOS with version 2.1.5.3

**Comment by mallowigi** [comment]
I've found out though that the Kotlin plugin was causing issues. Try disabling it perhaps.

**Comment by fearlex** [comment]
@mallowigi I appreciate you looking into this. It happens to me every time. I'm trying to add a Trello board, not sure if it is specific to Trello Task server or not.

I don't have the Kotlin plugin installed.

I will keep trying to see if I can find a pattern that can help you reproduce this

Thanks.

**Comment by mallowigi** [comment]
Maybe if you can attach me your idea.log file I can find something

**Comment by fearlex** [comment]
Hi @mallowigi 

Here it is. Thanks for looking into this.

[idea.log](https://github.com/ChrisRM/material-theme-jetbrains/files/1866393/idea.log)

**Comment by mallowigi** [comment]
Hi @fearlex 

Is it still happening? I've tried to add Trello boards and it worked without fail...

**Comment by fearlex** [comment]
Hi @mallowigi 

I just tried it again, and indeed is working. Something must have had to fix itself or on one of the recent updates.

Thanks for checking in on this.
