### ISSUE TITLE
Directories icons was visible only one time before change branch

### ISSUE THREAD

**Issue by marcinlesek** [ChrisRM/material-theme-jetbrains#710]
### Summary

Directory icons was available one 1 time, after change of branch, they're gone and now it's impossible to get them back.

<img width="202" alt="zrzut ekranu 2018-03-31 o 22 59 14" src="https://user-images.githubusercontent.com/13199192/38167560-29aaf4a4-3537-11e8-8453-689a4a946e5e.png">

<img width="139" alt="zrzut ekranu 2018-03-31 o 23 00 07" src="https://user-images.githubusercontent.com/13199192/38167565-47dc9b76-3537-11e8-8b21-f4164348df04.png">

Also, this option is checked in Material preferences:
<img width="1022" alt="zrzut ekranu 2018-03-31 o 23 03 32" src="https://user-images.githubusercontent.com/13199192/38167594-ce1f6498-3537-11e8-8571-f59d5795f6b6.png">

`Invalidate Caches & Restart` didn't helped, also rerun, another project etc.

### Steps to reproduce (if needed)

1. Open project

### Environment

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
Licensed to Marcin Łesek
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
Material Theme UI Plugin Version: 2.1.5.3

I didn't found `material_theme.xml` in `.idea` unfortunately.

Thanks in advance.

Best,
Marcin

PS. You're doing great job with this plugin. 👍

**Comment by mallowigi** [comment]
It's possible, you just have to edit one file and they will reappear. I am aware of this issue, I will fix it when i have the time.

**Comment by marcinlesek** [comment]
Thanks, you're right, they reappeared. So I will wait for fix for it.

Best,
Marcin
