### ISSUE TITLE
Missing VCS Commit/Push button in WebStorm 2018.1

### ISSUE THREAD

**Issue by Viperwow** [ChrisRM/material-theme-jetbrains#714]
Summary
The commit/push button is missing in the commit window

Expected behaviour:
It wouldn't be missing

Actual behaviour:
It is missing

Environment:
WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
Subscription is active until March 14, 2019
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
Will be fixed in next version
