### ISSUE TITLE
NPE for option button with Material Theme when dialog is closed

### ISSUE THREAD

**Issue by pchel-** [ChrisRM/material-theme-jetbrains#717]
See [this issue](https://youtrack.jetbrains.com/issue/IDEA-189621) for additional details.

Looks like `super.uninstallListeners()` should be added to `MTOptionButtonUI.uninstallListeners()`.
https://github.com/ChrisRM/material-theme-jetbrains/blob/a8da295361a728004d0dec5e9ccd51f4ae9b7f47/src/main/java/com/chrisrm/idea/ui/MTOptionButtonUI.kt#L51.

**Comment by mallowigi** [comment]
Is it something new? What ide/version do you use?

**Comment by pchel-** [comment]
Yes, it is [Rider 2018.1 EAP](https://www.jetbrains.com/rider/eap/).
See [this comment](https://youtrack.jetbrains.com/issue/IDEA-189621#focus=streamItem-27-2806286-0-0) for the steps to reproduce.

**Comment by mallowigi** [comment]
Thanks, works like a charm!
