### ISSUE TITLE
Github Commit Button is missing

### ISSUE THREAD

**Issue by Max-mit-dem-langen-Cock** [ChrisRM/material-theme-jetbrains#719]
### Summary

It isn't possible to commit things to a GitHub repository because the Button is missing

### Expected behavior

I should be able to Commit things to a GitHub repository

### Actual behavior

The Button to Commit is missing

### Steps to reproduce

1. Click the "Commit" Button for your Project
2. In the bottom right the "Commit" Button is missing. There is only a "cancel" Button

![bug](https://user-images.githubusercontent.com/26352108/38509512-60e9bd28-3c22-11e8-864d-636e37ca5d1d.jpeg)

### Environment

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
Licensed to *****
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by mallowigi** [comment]
#715
