### ISSUE TITLE
UI font/colors and spacing between items (icons & filenames) and in panels

### ISSUE THREAD

**Issue by blazeworx** [ChrisRM/material-theme-jetbrains#72]
Firstly, a huge thank you for creating this theme! I love it! 

Now moving onto the Issue :smile:, I understand it may not be possible to make a 1 to 1 exact port of this theme but maybe it would be possible to at least get similar spacing between the items. I feel like its all too close together in the Jetbrains theme and if this were possible it would make a huge difference in the overall feel of the theme. 

I do not know enough about the Jetbrains UI, but if possible changing the folder text color and the files text color would get it much closer in appearance.

Here is a side by side comparison of the left side panels (project browsing panel). Sublime on the left, Jetbrains on the right

![image](https://cloud.githubusercontent.com/assets/4718238/10503518/d24497ec-72c4-11e5-92be-93aaa9b26df2.png)

**Comment by EspadaV8** [comment]
Just throwing my 2 pence in, I prefer the Jetbrains version. Seems like a lot of wasted space in Sublime. Are there currently any settings to change the spacing in the tree views?

**Comment by blazeworx** [comment]
@EspadaV8 I can definitely appreciate that :+1: However, I think it is more consistent with the overall design / look and feel of the theme with that spacing. I would settle for a setting that I can change myself, if one exists of course.

**Comment by ChrisRM** [comment]
I think I'm gonna leave the spacing as is for now. I'll consider an optional setting for this.

**Comment by soee** [comment]
I also like if there is less space wasted here. When it comes to trees structure i like to see as many items as possible ;)
