### ISSUE TITLE
cannot install material-theme-jetbrains-2.1.5.3 on AndroidStudio3.1

### ISSUE THREAD

**Issue by Wensibob** [ChrisRM/material-theme-jetbrains#720]
![image](https://user-images.githubusercontent.com/24890876/38535434-00e90782-3cb6-11e8-9106-38b2900a0d86.png)

When I try to install this plugin from FS,I find the error above

**Comment by dudong0726** [comment]
AS3.1 based on ide-2017.3, but the last release version of MT plugin is compatible for 2018.1 and above.
