### ISSUE TITLE
a font/encode issue in "annotate"

### ISSUE THREAD

**Issue by sxcooler** [ChrisRM/material-theme-jetbrains#722]
### Summary

while I click "annotate" on the context menu of editor left side(line number), the author name in utf-8 characters displays as ??
![image](https://user-images.githubusercontent.com/3192045/38543660-bb16024c-3cd7-11e8-8223-d8605920230e.png)

### Expected behavior

show Chinese characters

### Actual behavior

showing ??

### Steps to reproduce (if needed)

1. Install WebStorm 2018.1
2. Install Material Theme Plugin
3. commit some lines of codes in UTF-8 chars(e.g. Chinese)
4. Right click at the left side bar of editor, then click "annotate" on the shown context menu.

### Environment

WebStorm 2018.1
Build #WS-181.4203.535, built on March 23, 2018
Licensed to ***
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
Material Theme Plugin v2.1.5.3
enabled plugins are just default ones
MTP configs are default too

**Comment by mallowigi** [comment]
The Fira Code font cannot display Chinese characters, please change the font to another one in Color scheme
