### ISSUE TITLE
Issues with Android studio 3.1.1

### ISSUE THREAD

**Issue by sedestrian** [ChrisRM/material-theme-jetbrains#725]
### Summary
The theme is having some issues on Android Studio 3.1.1 (Oceanic in this case but every dark theme is having it)

### Expected behavior

All sections colored correctly

### Actual behavior

<img width="1083" alt="screen shot 2018-04-17 at 10 48 49" src="https://user-images.githubusercontent.com/1345755/38859279-f6e6b61c-422d-11e8-9dee-3731dda96455.png">
<img width="508" alt="screen shot 2018-04-17 at 10 49 17" src="https://user-images.githubusercontent.com/1345755/38859286-f908fe8c-422d-11e8-96aa-6605a9b54710.png">

### Steps to reproduce (if needed)

Go to an xml file and this happens

### Environment

Android Studio 3.1.1
Build #AI-173.4697961, built on April 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.4

**Comment by mallowigi** [comment]
The Android Studio Designer is not open source, I've tried to fix this but it is unfortunately hardcoded in the IDE.

**Comment by sedestrian** [comment]
Oh ok, i was convinced that in previous versions it was colored correctly but i must be confused
