### ISSUE TITLE
Left panel background color in preferences window

### ISSUE THREAD

**Issue by blazeworx** [ChrisRM/material-theme-jetbrains#73]
Not sure if this may be just my installation (I was running the Darcula theme from Jetbrains before) or if I am missing something or if this can be set some how?

However this is what the preference window looks like on my version of PHPStorm EAP (9.5) 143.129.

Note the grey background in the left panel of the window.

![image](https://cloud.githubusercontent.com/assets/4718238/10503763/470c154e-72c7-11e5-8921-d449aec202f9.png)

**Comment by ChrisRM** [comment]
I haven't found a way to customize it yet. I'll see I can find a way this weekend.

**Comment by ChrisRM** [comment]
@bulenkov added this: https://github.com/JetBrains/intellij-community/commit/a6eef48f92f73fbaa9d5c0817e0c16f0e4d7c8c0

I'm guessing this will be implemented in the next release (2016.2), so I have already added the appropriate option here: https://github.com/ChrisRM/material-theme-jetbrains/commit/fd15184c0aad065477585ae6202e41c432c7edf6

Tested and works on the JetBrains master branch.
