### ISSUE TITLE
Updating to latest verison v2.1.7.3.android crashes plugin in PyCharm Professional

### ISSUE THREAD

**Issue by TheAnarchoX** [ChrisRM/material-theme-jetbrains#733]
### Summary

Updating the plugin to the latest version crashes it and throws the error:
```text
Plugin Error:
	Problems found loading plugins:
	Plugin "Material Theme UI" was not loaded: 
    required plugin "org.jetbrains.android" not installed.
```

### Expected behavior

That beautiful Theme of mine I love and cant work without

### Actual behavior

```text
Plugin Error:
	Problems found loading plugins:
	Plugin "Material Theme UI" was not loaded: 
    required plugin "org.jetbrains.android" not installed.
```
### Steps to reproduce 

1. Update the plugin via the plugin manager
2. Restart PyCharm
3. See the event log

#### Alternative steps
1. Install the plugin via the plugin manager
2. Restart PyCharm
3. See the event log

### Environment

PyCharm 2018.1 (Professional Edition)
Build #PY-181.4203.547, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by Kapulara** [comment]
Same for Webstorm.

**Comment by Kapulara** [comment]
I've found a temporary fix:

### 1. Remove current version
`Preferences -> Plugins -> Material Theme UI -> Uninstall`

### 2. Download old version
Go to: https://plugins.jetbrains.com/plugin/8006-material-theme-ui

Download version 2.1.7.1 ([Direct Link](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=45178))

### 3. Install Plugin from Disk
`Preferences -> Plugins -> Install Plugin from Disk -> Restart Webstorm`

**Comment by kstratis** [comment]
Same problem in Rubymine

**Comment by mallowigi** [comment]
It's only for android studio guys. Please downgrade to 2.7.1.2

**Comment by Kapulara** [comment]
It automatically updated when I was updating my Plugins. This is because in the Plugin.yml contains Webstorm in Version 2.7.1.3

https://plugins.jetbrains.com/plugin/8006-material-theme-ui/update/45237

![image](https://user-images.githubusercontent.com/1766076/39095208-f9f73a1c-463c-11e8-9afb-206eb7268046.png)

Even though it's only compatible with Android Studio
