### ISSUE TITLE
Updating to latest version 2.1.7.3.android in PhpStorm 2018.1 causes errors

### ISSUE THREAD

**Issue by craigsansam** [ChrisRM/material-theme-jetbrains#734]
### Summary

After updating to the latest version of the plugin (Version: 2.1.7.3.android) , PhpStorm 2018.1 is no longer able to load the plugin.

### Expected behavior

The plugin loads without errors.

### Actual behavior

Upon starting PhpStorm, the following event is displayed:

```Problems found loading plugins: Plugin "Material Theme UI" was not loaded: required plugin "org.jetbrains.android" not installed.```

### Steps to reproduce (if needed)

1. Update to the latest version of the plugin in PhpStorm 2018.1
2. Restart PhpStorm

You can also add Screenshots for a better understanding.

### Environment

PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
Licensed to Craig Sansam
Subscription is active until July 16, 2018
JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

Plugin Version: Version: 2.1.7.3.android

**Comment by kstratis** [comment]
Same here

**Comment by Nosherwan** [comment]
I have had the same issue.

**Comment by mallowigi** [comment]
ITs not written android for nothing... sheesh...

**Comment by mallowigi** [comment]
Please downgrade to 2.7.1.2

**Comment by craigsansam** [comment]
@mallowigi - I did notice that... I'd be prepared for loads of people complaining about this when their plugins auto-update! Bad idea releasing a breaking change to an existing plugin...

**Comment by mallowigi** [comment]
Yes I thought that specifying a dependency to android studio would only display the plugin to android studio users...

I'll bump the version later in the evening, and too bad for the AS users.
