### ISSUE TITLE
2.7.1.3.android is only for android studio. Do not install outside

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#735]
Maybe I should create a new plugin specifically for Android Studio

**Comment by gabrieli** [comment]
@mallowigi I don't think it's possible to select a previous version for installing from webstorm. I just took 2.7.1.3 few minutes ago, after updating Webstorm as well and the plugin stopped

**Comment by Kapulara** [comment]
@gabrieli it's possible to downgrade manually:

### 1. Remove current version
`Preferences -> Plugins -> Material Theme UI -> Uninstall`

### 2. Download old version
Go to: https://plugins.jetbrains.com/plugin/8006-material-theme-ui

Download version 2.1.7.2 ([Direct Link](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=45236))

### 3. Install Plugin from Disk
`Preferences -> Plugins -> Install Plugin from Disk -> Restart Webstorm`

**Comment by mallowigi** [comment]
Ok i bumped the version. AS users would have to download the version manually though.
