### ISSUE TITLE
Letters in dialogs and settings menu are offset by 1 letter.

### ISSUE THREAD

**Issue by Renari** [ChrisRM/material-theme-jetbrains#736]
### Summary

For my installation of the Material Theme plugin on my home computer all of the button prompts (and the dropdowns on the settings menu) become wrong by 1 letter. For example the word `apple` would show as `bqqmf`.
![](https://i.imgur.com/lh6Ikhj.png)

...

Buttons to show the correct text.

...

Buttons show gibberish.

...

### Environment

PhpStorm 2018.1.1
Build #PS-181.4445.72, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme Version 2.1.7.4

```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.1.7.4" />
    <option name="selectedTheme" value="ONE_DARK" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Lol I swear I have no clue why this happens, I would open an issue to JetBrains if it was reproducible, but sadly it isn’t.

Can you uninstall and reinstall the ide and see if it happens again?

**Comment by mallowigi** [comment]
Can you try to reinstall the Roboto font (see the readme on how to do it)?

**Comment by mallowigi** [comment]
Or better, can you send me your installed roboto font?

**Comment by Renari** [comment]
[Roboto.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/1936851/Roboto.zip)

**Comment by mallowigi** [comment]
https://youtrack.jetbrains.com/issue/IDEA-185665

**Comment by mallowigi** [comment]
Anyway, try to download a fresh install of Roboto from Google Fonts, restart the IDE and see if it soves the issue

**Comment by Renari** [comment]
Reinstalling Roboto did fix the issue.
