### ISSUE TITLE
Git > Annotate in Webstorm Dark Theme doesn't show any information

### ISSUE THREAD

**Issue by cueo** [ChrisRM/material-theme-jetbrains#738]
### Summary
In Webstorm (Dark mode), usernames and date info are not visible on doing Git > Annotate.

...

### Expected behavior
<img width="175" alt="screen shot 2018-04-24 at 10 18 39 am" src="https://user-images.githubusercontent.com/13873846/39166729-e1509180-47a8-11e8-96c7-976c20df1fbf.png">

...

### Actual behavior
<img width="205" alt="screen shot 2018-04-24 at 10 16 01 am" src="https://user-images.githubusercontent.com/13873846/39166703-babdb548-47a8-11e8-843d-8536f2963998.png">

...

### Steps to reproduce (if needed)

1. Switch to Material Theme Dark mode
2. Right click in a file
3. Go to Git
4. Click Annotate

### Environment
WebStorm 2018.1.1
Build #WS-181.4445.68, built on April 9, 2018
Licensed to Intuit Inc.

JRE: 1.8.0_152-release-1136-b27 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

**Comment by mallowigi** [comment]
Which color scheme are you using?

**Comment by cueo** [comment]
Material darker

**Comment by mallowigi** [comment]
I’m talking about the color scheme, not the theme. What you see at Settings > Editor > Color Scheme

**Comment by cueo** [comment]
Yeah, I'm also mentioning the same
<img width="1342" alt="screen shot 2018-04-25 at 12 24 02 pm" src="https://user-images.githubusercontent.com/13873846/39230291-98245f7e-4883-11e8-9924-2376528edcae.png">

**Comment by mallowigi** [comment]
I see that you have an edited color scheme. can you reset to defaults?

**Comment by cueo** [comment]
That works but it still has a white font on grey background, not as elegant and uniform as IntelliJ

**Comment by mallowigi** [comment]
Well I didn't put too much time on working on it, looks readable to me

**Comment by cueo** [comment]
It shouldn't be much of an effort replicating the same into Webstorm, right? I can maybe take a look at it if you could point me in the right direction.

**Comment by mallowigi** [comment]
What colors do you want though ?

**Comment by mallowigi** [comment]
The files are in the resources/colors folder

**Comment by cueo** [comment]
Same as in IntelliJ
<img width="175" alt="screen shot 2018-04-24 at 10 18 39 am" src="https://user-images.githubusercontent.com/13873846/39166729-e1509180-47a8-11e8-96c7-976c20df1fbf.png">

**Comment by cueo** [comment]
Sorry, man. It seems to be behaving as expected now.

**Comment by tunjid** [comment]
@cueo 

How did you fix this? Mine still has this issue

**Comment by cueo** [comment]
@tunjid 

Settings > Editor > Color Scheme > Click on the three dots and reset to default > Restart
