### ISSUE TITLE
Code completion selected line not visible in light theme

### ISSUE THREAD

**Issue by dzimmerer** [ChrisRM/material-theme-jetbrains#739]
### Summary

Using code completion the default line is not visible, only if you select a line, the line background gets darker and the text color is white, otherwise both are just gray, so you cannot see the actual text  

### Expected behavior

Make the text color a different (brighter) color when using the code completion popup.

### Actual behavior

The text color is nearly the same as the background color when using the code completion popup (for the default suggestion).

### Steps to reproduce (if needed)

1. Install Material Theme.
2. Use the lighter theme
3. Use code completion

![image](https://user-images.githubusercontent.com/13333807/39235911-8f86e618-4877-11e8-806b-9c2c52f20dff.png)

### Environment
Ubuntu 16.04
Pycharm 2018.1
Pugin version 2.1.7.4

**Comment by mallowigi** [comment]
Can;t reporduce, looks fine in my machine:

![image](https://user-images.githubusercontent.com/5015756/39242274-2fa9a814-4892-11e8-8573-45ab8cbeeed0.png)

**Comment by mallowigi** [comment]
Got to reproduce.

**Comment by daishenghao** [comment]
Got to reproduce too.
window10
webstorm 2018.1
Pugin version 2.1.7.1
