### ISSUE TITLE
Grails support for IntelliJ

### ISSUE THREAD

**Issue by cameronoxley** [ChrisRM/material-theme-jetbrains#74]
Hi @ChrisRM, awesome idea, thanks for creating the much needed theme!

I know its a long shot (and that you're still in the process of adding Java support), but Icon support for Grails/Groovy would be a fantastic addition when you do.

![screen shot 2015-10-15 at 10 22 39](https://cloud.githubusercontent.com/assets/1674847/10508345/c7208e18-7326-11e5-828d-5a5e42e0a658.png)

**Comment by ChrisRM** [comment]
I'll add to my todo-list :+1:

**Comment by mallowigi** [comment]
Should be done in the latest release
