### ISSUE TITLE
Numbers cut off in array viewer table

### ISSUE THREAD

**Issue by pbreach** [ChrisRM/material-theme-jetbrains#740]
### Summary

When debugging through code there are times when I need to use the "...View as Array" feature in Pycharm from the Debugger window where the variables are listed. When I click "...View as Array" the window comes up but the header is on top of a portion of the array contents.

### Expected behavior

With the default Darcula theme I'm able to see the numbers clearly in the "...View as Array" window:

![image](https://user-images.githubusercontent.com/8889265/39256456-f62ec264-487c-11e8-9704-fb54594e62f2.png)

...

### Actual behavior

With Material UI I see the numbers cut off:

![image](https://user-images.githubusercontent.com/8889265/39257277-29522878-487f-11e8-91e5-fc4482fc9bf8.png)

...

### Environment

PyCharm 2018.1.1 (Community Edition)
Build #PC-181.4445.76, built on April 9, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Material Theme Plugin version: 2.1.7.4

**Comment by mallowigi** [comment]
Enable "Compact Table Cells" in the settings

**Comment by pbreach** [comment]
This worked thank you!
