### ISSUE TITLE
Skip breakpoints icon is not clearly

### ISSUE THREAD

**Issue by xinkunZ** [ChrisRM/material-theme-jetbrains#741]
* ver: 2.2.0
* there is no difference between [skip breakpoints] and  [not skip breakpoints]

![image](https://user-images.githubusercontent.com/7759897/39289204-b1019ae0-495d-11e8-8c0c-d1ba6e7cbd05.png)
![image](https://user-images.githubusercontent.com/7759897/39289291-158c2f5c-495e-11e8-831a-61d28d4533fe.png)

**Comment by mallowigi** [comment]
fixed
