### ISSUE TITLE
EditorComponent's project must not be null in order to be used with RepositoryLibraryWithDescriptionEditor

### ISSUE THREAD

**Issue by akon89** [ChrisRM/material-theme-jetbrains#742]
### Summary
IntelliJ crash when configuring Groovy library (click the suggested popup to configure a library). Added the library using Maven repository. 

Error message:
>EditorComponent's project must not be null in order to be used with RepositoryLibraryWithDescriptionEditor
> java.lang.AssertionError: EditorComponent's project must not be null in order to be used with RepositoryLibraryWithDescriptionEditor
> 	at com.intellij.jarRepository.RepositoryLibraryWithDescriptionEditor.edit(RepositoryLibraryWithDescriptionEditor.java:56)
> 	at com.intellij.openapi.roots.ui.configuration.libraryEditor.LibraryPropertiesEditorBase$1.actionPerformed(LibraryPropertiesEditorBase.java:53)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:133)
> 	at java.awt.Component.processMouseEvent(Component.java:6541)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.awt.Dialog.show(Dialog.java:1077)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:427)
> 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
> 	at com.intellij.facet.impl.ui.libraries.LibraryOptionsPanel.g(LibraryOptionsPanel.java:323)
> 	at com.intellij.facet.impl.ui.libraries.LibraryOptionsPanel.access$700(LibraryOptionsPanel.java:74)
> 	at com.intellij.facet.impl.ui.libraries.LibraryOptionsPanel$6.actionPerformed(LibraryOptionsPanel.java:292)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:133)
> 	at java.awt.Component.processMouseEvent(Component.java:6541)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.awt.Dialog.show(Dialog.java:1077)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:427)
> 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
> 	at org.jetbrains.plugins.groovy.config.DefaultGroovyFrameworkConfigNotification.lambda$createConfigureNotificationPanel$0(DefaultGroovyFrameworkConfigNotification.java:48)
> 	at com.intellij.ui.EditorNotificationPanel$1.hyperlinkActivated(EditorNotificationPanel.java:126)
> 	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
> 	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:212)
> 	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:136)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> 
> java.lang.AssertionError: EditorComponent's project must not be null in order to be used with RepositoryLibraryWithDescriptionEditor
> 	at com.intellij.jarRepository.RepositoryLibraryWithDescriptionEditor.edit(RepositoryLibraryWithDescriptionEditor.java:56)
> 	at com.intellij.openapi.roots.ui.configuration.libraryEditor.LibraryPropertiesEditorBase$1.actionPerformed(LibraryPropertiesEditorBase.java:53)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:133)
> 	at java.awt.Component.processMouseEvent(Component.java:6541)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.awt.Dialog.show(Dialog.java:1077)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:427)
> 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
> 	at com.intellij.facet.impl.ui.libraries.LibraryOptionsPanel.g(LibraryOptionsPanel.java:323)
> 	at com.intellij.facet.impl.ui.libraries.LibraryOptionsPanel.access$700(LibraryOptionsPanel.java:74)
> 	at com.intellij.facet.impl.ui.libraries.LibraryOptionsPanel$6.actionPerformed(LibraryOptionsPanel.java:292)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> 	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> 	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> 	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> 	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> 	at com.chrisrm.idea.ui.MTButtonUI$1.mouseReleased(MTButtonUI.java:133)
> 	at java.awt.Component.processMouseEvent(Component.java:6541)
> 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
> 	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
> 	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
> 	at java.awt.Dialog.show(Dialog.java:1077)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
> 	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:427)
> 	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1682)
> 	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1631)
> 	at org.jetbrains.plugins.groovy.config.DefaultGroovyFrameworkConfigNotification.lambda$createConfigureNotificationPanel$0(DefaultGroovyFrameworkConfigNotification.java:48)
> 	at com.intellij.ui.EditorNotificationPanel$1.hyperlinkActivated(EditorNotificationPanel.java:126)
> 	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
> 	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:212)
> 	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:136)
> 	at java.awt.Component.processEvent(Component.java:6306)
> 	at java.awt.Container.processEvent(Container.java:2237)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4897)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4719)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.awt.EventQueue$4.run(EventQueue.java:735)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:837)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:762)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

### Expected behavior
Shouldn't crash.

### Actual behavior
Crashed immediately upon configuration of the Groovy library using Maven.  

### Steps to reproduce (if needed)

1. Have a project that needs Maven, but is not configured for it.
2. Click the top suggestion window to configure it.
3. Chose library (using Maven).
4. Crashed. (first time this has happened)

This is the way the library is configured.
![image](https://user-images.githubusercontent.com/38504773/39334797-642120aa-496d-11e8-8ab8-1a0e456a7d98.png)

### Environment

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Plugin Version: Material Theme UI 2.1.7.4

Configuration XML

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.1.7.4" />
    <option name="selectedTheme" value="DARKER" />
    <option name="accentColor" value="e57373" />
  </component>
</application>

```

**Comment by mallowigi** [comment]
I am not able to reproduce your case. I tried following your steps but I don't get the popup you are displaying. Do you have an example open source project where this happens?

**Comment by akon89** [comment]
I had just imported this project [https://github.com/igorpopovio/jira-scripting](https://github.com/igorpopovio/jira-scripting) when it happened, so it may be possible to reproduce from that.

**Comment by mallowigi** [comment]
Still cannot reproduce. Can you send me video step maybe?

**Comment by akon89** [comment]
I will if it occurs again.  I've only seen it the first time I reported it.  Did you want me to close this until / if it happens again?

**Comment by MaciejWWojcik** [comment]
I have the same problem with all of my projects using WebStorm. 
In every start of webstorm I receive this errors. 
It's strange because everything works fine apart from "project" view in Project.
"Project files" or "Problems" or "Changed Files" are good, but "Project" is in "loading" state every time

**Comment by MaciejWWojcik** [comment]
Please look at this: 
https://imgur.com/a/Q5eGnUY

**Comment by mallowigi** [comment]
There should be a problematic file extension. Can I see the project files? Or at least can you provide me a list of extensions used in the project ?

**Comment by MaciejWWojcik** [comment]
@mallowigi This [project](https://github.com/MaciejWWojcik/online-planning-poker) is a good example of this. 
It's i think standard angular cli generated project + some dependencies
if you want to check it - remember about running npm install first

**Comment by mallowigi** [comment]
Sigh... cannot reproduce :(

**Comment by MaciejWWojcik** [comment]
i'm using version: 2.2.0.1 if this helps

**Comment by mallowigi** [comment]
Maybe you have some plugins that interfere with the plugin?

**Comment by MaciejWWojcik** [comment]
I exported you my webstorm settings - maybe you can try if you can reproduce error. https://ufile.io/o71ej
And there is list of my plugins: https://imgur.com/a/CI4DpSd

**Comment by mallowigi** [comment]
no dice
![image](https://user-images.githubusercontent.com/5015756/39515110-c4540710-4e01-11e8-9c53-92a9b5183106.png)

**Comment by mallowigi** [comment]
bumping this because i have no way to reproduce. Maybe you can send me a video of the project you try to clone?

Also, don't know if this could be a fix, but have you tried to uninstall and reinstall the plugin?

**Comment by MaciejWWojcik** [comment]
@mallowigi I will do this tomorrow

**Comment by mallowigi** [comment]
Another question: are you on Linux maybe? ChromeOS? Are you admin on your machine?

**Comment by MaciejWWojcik** [comment]
Yes, admin on macOS High sierra 10.13.4

**Comment by MaciejWWojcik** [comment]
@mallowigi Webstorm just inform me about update in plugin. After installation and restart all is working fine! 
😃 👍
