### ISSUE TITLE
Feature Request: Nord and/or Tomorrow themes

### ISSUE THREAD

**Issue by domi91c** [ChrisRM/material-theme-jetbrains#743]
This is just a request for the [Nord](https://github.com/arcticicestudio/nord) theme and [Tomorrow Night](https://github.com/chriskempson/tomorrow-theme) theme. They are both pretty popular. 

Thanks for the great work also. You've made Intellij so much more useable.

**Comment by mallowigi** [comment]
I don't plan for doing other themes at the moment. You can still work on theme using the Custom theme editor and submit your theme scheme once you think you're done. I can then help you create a plugin for it.
