### ISSUE TITLE
Tab background not styled for external files

### ISSUE THREAD

**Issue by ERROPiX** [ChrisRM/material-theme-jetbrains#752]
Hi,

I am using PHPStorm 2018.1.2, Windows 10, Material One Dark theme

When I open php file from the File Explorer that's not within a project, the tab is colored in default Dracula theme

![external file tab](https://user-images.githubusercontent.com/6576868/39664372-40382f30-507a-11e8-9082-3446f837640e.PNG)

Thanks

**Comment by mallowigi** [comment]
This should be fixed in latest version. If you see when choosing a color for any scope, you will see a new option "Theme" that allows you to set a color adapted to your current theme.

**Comment by ERROPiX** [comment]
@mallowigi, I  solved it by going to File | Settings | Appearance & Behavior | File Colors and deleted the scopes to match all tabs
