### ISSUE TITLE
Code Style tabs not taking the look and feel of meterial theme

### ISSUE THREAD

**Issue by ERROPiX** [ChrisRM/material-theme-jetbrains#755]
Using latest material theme version with PHPStorm 2018.1.2

![phpstorm-codestyle-tabs](https://user-images.githubusercontent.com/6576868/39678534-70f2a760-5186-11e8-983d-4dcd8911bda8.png)

**Comment by mallowigi** [comment]
This is a recurring issue that I’ve not been able to solve for a long time, but I’ll try again now that I’ve solved all the remaining issues

**Comment by ERROPiX** [comment]
That's good, thank you for the hard work

**Comment by ERROPiX** [comment]
Hi @mallowigi,

The issue is the same about deployment tabs

![phpstorm-deployment-tabs](https://user-images.githubusercontent.com/6576868/39715925-b2fa3ab0-5226-11e8-90f0-7d44aed75f45.png)

I also, noticed that there is some random lines and dots around tabs on deployment configuration window (see screenshot above)

These are random positioned scratches that disappears and appear when changing tabs

Thanks

**Comment by mallowigi** [comment]
I cannot fix these, I tried before and have no idea why it happens. I managed to theme the tabs nonetheless take a look.
