### ISSUE TITLE
Tree View left border is not looking good with the arrows

### ISSUE THREAD

**Issue by ERROPiX** [ChrisRM/material-theme-jetbrains#756]
Using latest material theme version with PHPStorm 2018.1.2

![atom-treeview-border](https://user-images.githubusercontent.com/6576868/39678550-a4e0ac5c-5186-11e8-99d0-69825c981286.png)

Maybe remove the left border?

**Comment by mallowigi** [comment]
This is something that I thought I’ve fixed in the latest version. I will not remove the indicator but the arrows need to be more on the right. Or adding more padding.

**Comment by ERROPiX** [comment]
Hi @mallowigi,
I know I can adjust the padding by changing "Custom Tree Indent" but it still look bad to have the arrows and border on the left, maybe a better option to have the border in the right side?

**Comment by ERROPiX** [comment]
Your theme is a good work, and I am just suggesting giving us more options:
![phpstorm-custom-indent](https://user-images.githubusercontent.com/6576868/39705962-cda3e93e-5207-11e8-9cd0-6c9d9cc9de8b.png)
