### ISSUE TITLE
lots of IllegalAccessError  when i click on an editor tab on PyCharm

### ISSUE THREAD

**Issue by danleyb2** [ChrisRM/material-theme-jetbrains#76]
IllegalAccessError: com/intellij/ui/tabs/impl/JBEditorTabsPainter

![n](https://cloud.githubusercontent.com/assets/9919961/10521660/c8347e9c-7379-11e5-890c-9f7f7afe5a26.png)

**Comment by ChrisRM** [comment]
I'll look into it later tonight.

**Comment by ChrisRM** [comment]
@danleyb2 Can you try the newest build?

**Comment by danleyb2** [comment]
ok @ChrisRM
