### ISSUE TITLE
Support content root folder color coding

### ISSUE THREAD

**Issue by hdennen** [ChrisRM/material-theme-jetbrains#761]
[Content roots](https://www.jetbrains.com/help/webstorm/content-root.html) are great but without the visual cue in the file tree it's much harder to use.

**Comment by mallowigi** [comment]
Can you elaborate?

**Comment by mallowigi** [comment]
Which version are you on? This should not happen in latest versions

**Comment by hdennen** [comment]
1.6.1

**Comment by hdennen** [comment]
You know what I'm on webstorm 2017.3, could that be it?

**Comment by mallowigi** [comment]
It works for sure on Webstorm 2108.1 versions. 2017 versions are not supported unless they’re critical fixes.

**Comment by hdennen** [comment]
Just upgraded to latest webstorm and Material and the content roots are still not color coded :(
 
There is color coding for public and node_modules though.

**Comment by hdennen** [comment]
OK now it's working, needed another restart. Sorry for taking your time.
