### ISSUE TITLE
Warning notification colour is too much

### ISSUE THREAD

**Issue by CLINT0N** [ChrisRM/material-theme-jetbrains#762]
Hi,

First of all thanks for the great work that you do, switching back to Darcula always reminds me just how awesome this theme is.

Sorry for not filling out the template but I don't think this issue needs one. I am using the latest version 2.2.2 which contains the following change "Change notification colors (success, warn, error)". Using PhpStorm 2018.1.2.

After installing this update I tested the colours out, success looks fine, I think error could be toned down a tiny bit but is also fine. However the warning colour just looks terrible and does not contrast well with the light text:

![Warning Notification](https://user-images.githubusercontent.com/19330442/39826368-588bb626-53ac-11e8-90db-f4d66b8d7137.png)

Please make it less orange and more yellow :)

**Comment by mallowigi** [comment]
I agree...................

**Comment by mallowigi** [comment]
changed to a yellow color
