### ISSUE TITLE
Editor active tabs doesn't look like your screenshots

### ISSUE THREAD

**Issue by ERROPiX** [ChrisRM/material-theme-jetbrains#764]
Hi,

I am using PHPStorm 2018.1.3, with Material One Dark

![phpstorm-editor-tabs](https://user-images.githubusercontent.com/6576868/39867881-f134d612-544e-11e8-9e3f-654af5fe930c.png)

As I can see, current tab have a border with the accent color, but it's background is the same as all the tabs, any idea how to make it different, is there a settings under Material Theme?

**Comment by mallowigi** [comment]
There is a documentation website, have you checked it ?
