### ISSUE TITLE
Make colour editor easier to understand

### ISSUE THREAD

**Issue by mrgrieves4** [ChrisRM/material-theme-jetbrains#765]
At the moment, it's quite hard to know what the colours relate to - in particular because it's often not clear whether a colour is a foreground or a background colour. 

It would be good to group foreground and background colours together, so that it's easy to spot ta a glance where colour contrast isn't good.  (As improving colour contrast is the reason I installed this plugin)

Some of the labels are not massively helpful either - for example, I wanted to change the colours of the deployment popup so thought maybe that would be notification colour (it wasn't).  I've also got no idea what a misc colour or a contrast colour is for.

One last thing - the colours and the labels are so far apart it's not that easy to spot which ones relate to each other.

It has taken me quite a while to set things up properly, but now I have it's made jetbrains apps so much more comfortable to use, so thank you !!

**Comment by mallowigi** [comment]
Have you checked the documentation? I tried to make things much clearer with examples and stuff so go take a look. I know some of the color descriptions might get too abstract, but thats because there are many resources grouped under the same name so it can be hard to find the right name.

**Comment by mrgrieves4** [comment]
Ah no I didn't see the documentation - the link on the plugin page to documentation is broken, but I've found it now.  I'll have a look, thanks.

Putting the examples into the UI might not be a bad thing, though.
