### ISSUE TITLE
Small font on 4k screen on the latest version - 2.2.3.1

### ISSUE THREAD

**Issue by PaulMuriithi** [ChrisRM/material-theme-jetbrains#766]
### Summary
The fonts on the rest of the IDE apart from the editor are tiny after installing this theme.
Before:
![screenshot from 2018-05-11 09-14-37](https://user-images.githubusercontent.com/4158695/39910156-8a341206-54fe-11e8-8a78-862e4d78467e.png)
After:
![screenshot from 2018-05-11 09-15-42](https://user-images.githubusercontent.com/4158695/39910174-9b9a125c-54fe-11e8-9b1f-ba3c6d606d02.png)

### Expected behavior
The fonts should remain the same.

### Actual behavior
They are tiny

### Steps to reproduce (if needed)
1. Install theme
2. Restart IDE
3. Note the fonts

### Environment
IntelliJ IDEA 2017.3.5 (Ultimate Edition)
Build #IU-173.4674.33, built on March 5, 2018
JRE: 1.8.0_171-b11 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 4.13.0-39-generic
Material Theme Plugin version: 1.6.1
#### Graphics
Card-1: Intel Device 5917
Card-2: NVIDIA Device 1d10
Display Server: X.Org 1.18.4 driver: nvidia Resolution: 3840x2160@60.00hz
GLX Renderer: GeForce MX150/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 384.111

**Comment by PaulMuriithi** [comment]
Don't say it is related to https://github.com/ChrisRM/material-theme-jetbrains/issues/204 because I am already using the latest version(which was the solution to that issue)

**Comment by mallowigi** [comment]
I never tested on 4K screens, but just to be sure, have you checked on Webstorm 2018.1? I am not releasing fixes for Webstorm 2017 unless it’s critical anyway.

**Comment by PaulMuriithi** [comment]
I have just tested on the latest:
```
IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
JRE: 1.8.0_171-b11 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 4.13.0-39-generic
Material Theme Plugin version: 2.2.3.1
```
Before:
![screenshot from 2018-05-19 21-37-32](https://user-images.githubusercontent.com/4158695/40272084-197225ea-5bb0-11e8-8e23-71b2a07886c7.png)

After:
![screenshot from 2018-05-19 21-36-37](https://user-images.githubusercontent.com/4158695/40272086-22518e80-5bb0-11e8-9d72-e32f71f3287e.png)

**Comment by mallowigi** [comment]
Hi, do you have the latest EAP? If yes, can you download the version 2.3.4 from the 'eap' tab in this link: https://plugins.jetbrains.com/plugin/8006-material-theme-ui and tell me if it fixes the issue.
