### ISSUE TITLE
Mac menubar icons not retina ready

### ISSUE THREAD

**Issue by fcornelius** [ChrisRM/material-theme-jetbrains#767]
The icons for menu entries in the mac menu bar seem to have a low resolution on retina screens.

<img width="328" alt="bildschirmfoto 2018-05-11 um 12 52 42" src="https://user-images.githubusercontent.com/9767036/39921191-448ec7e8-551a-11e8-8d34-55bab577b6de.png">

### Environment

* IntelliJ IDEA 2018.1.1 (Ultimate Edition) Build #IU-181.4445.78, built on April 9, 2018
* JRE: 1.8.0_152-release-1136-b27 x86_64
* JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
* macOS 10.13.4
* Material Theme UI Version: 2.2.3

**Comment by mallowigi** [comment]
It’s the case without the material plugin as well.

**Comment by fcornelius** [comment]
Thanks for the info, any fix known for this?
