### ISSUE TITLE
Default theme - dropdown/context menus needs some shadow or border

### ISSUE THREAD

**Issue by soee** [ChrisRM/material-theme-jetbrains#77]
Dropdown menus or context menu uses the same background as panels etc. This leads to situation that it is hard to recognize what items belongs to menus and what not.

So those menus probably should have different color or some border or shadow.

**Comment by ChrisRM** [comment]
They have both a border and shadow here. Can you send me a screenshot of what it looks like @soee?

**Comment by soee** [comment]
@ChrisRM There you go:

![snapshot30_alt](https://cloud.githubusercontent.com/assets/1798417/10538723/d3defa48-73fa-11e5-832c-f77d3e35425a.png)
![snapshot29_alt](https://cloud.githubusercontent.com/assets/1798417/10538724/d7704310-73fa-11e5-8397-9bf2ac6e814a.png)

**Comment by ChrisRM** [comment]
Thanks! I'll set a darker color for the menus on windows.

**Comment by nonameolsson** [comment]
This is the only thing that I feel is missing from the theme. How's it going?

**Comment by BartKoppelmans** [comment]
Any progress on this?

**Comment by LasseRafn** [comment]
Can this be done? :-)

**Comment by marlboro** [comment]
What a fantastic theme!  This is the only issue that is driving me nuts.  Any idea when this will be resolved?

**Comment by Borkason** [comment]
It would be fantastic if this could be added.

**Comment by mallowigi** [comment]
@ChrisRM I fixed it by setting Separator.foreground=2E3C43 in default.properties. This adds a border with a lighter shade of Oceanic Blue

**Comment by SalahAdDin** [comment]
Was fixed?
