### ISSUE TITLE
Material Theme stuck on Oceanic

### ISSUE THREAD

**Issue by BDeus** [ChrisRM/material-theme-jetbrains#771]
Hi,
i'm currently stuck with oceanic theme. When i changed the theme the different panel and menu still remain on oceanic.
I tried to change directly on options.xml
`<property name="com.chrisrm.idea.MaterialThemeUI.theme" value="LIGHTER" />`
but at startup the value change to OCEANIC.
See attach screenshot with lighter theme (only editor switch to lighter)
![material-theme](https://user-images.githubusercontent.com/4964831/39992427-0c3c9cca-5773-11e8-9adb-fa493e45813a.png)

If any of you have a idea, i would appreciate it.

* OS: Windows
* IntelliJ: 2018.1.3
* Material Theme Plugin version: 2.2.3

**Comment by mallowigi** [comment]
No no you can't change in options.xml directly. At least change the material_theme.xml file. But I never heard that you can't change the themes from the switcher...

**Comment by mallowigi** [comment]
How do you change the theme ?

**Comment by BDeus** [comment]
from the switcher in options, i change to the lighter theme. It did not change the different right/left panels (see in the screenshot)

**Comment by BDeus** [comment]
Ok sorry, i changed the theme via Settings > Editor > Color Theme.
I didn't see the switcher on the IDE toolbar.
