### ISSUE TITLE
PhpStorm Terminal error messages not readable

### ISSUE THREAD

**Issue by marcoflorian** [ChrisRM/material-theme-jetbrains#772]
### Summary

The error messages in the Terminal inside PhpStorm are not readable. 

### Steps to reproduce (if needed)

1. Install PhpStorm
2. Install Material Theme Plugin
3. Run script with error messages

Current behavior in the Terminal inside PhpStorm

<img width="514" alt="screen shot 2018-05-14 at 7 06 56 pm" src="https://user-images.githubusercontent.com/6256009/40029518-9f5b39da-57aa-11e8-88b2-9a74eda0e70d.png">

Current behavior in the Terminal outside PhpStorm

<img width="401" alt="screen shot 2018-05-14 at 7 07 45 pm" src="https://user-images.githubusercontent.com/6256009/40029535-bd2b092c-57aa-11e8-8615-705782a08533.png">

### Environment

PhpStorm 2018.1.2
Build #PS-181.4668.78, built on April 25, 2018
Licensed to Marco Florian
Subscription is active until April 7, 2019
For educational use only.
JRE: 1.8.0_152-release-1136-b29 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
Material Theme UI Version: 2.2.0.1

**Comment by mallowigi** [comment]
You don't have the Grep Console plugin don't you?

**Comment by marcoflorian** [comment]
@mallowigi no Grep Console plugin. List of the plugins enabled below.

.env files support (0.6)
AngularJS (181.4668.78)
Apache config (.htaccess) support (181.4668.78)
ASP (0.1)
BashSupport (1.6.13.181)
Behat Support (181.4668.78)
Blade Support (181.4668.78)
Codeception Framework (181.4668.78)
CoffeeScript (181.4668.78)
Command Line Tool Support (181.4668.78)
Copyright (8.1)
CSS Support (181.4668.78)
CVS Integration (11)
Database Tools and SQL (181.4668.78)
Docker integration (181.4668.78)
Drupal Support (181.4668.78)
EditorConfig (181.3741.1)
File Watchers (181.4668.78)
Gherkin (999.999)
Git Integration (8.1)
GitHub (181.4668.78)
GNU GetText files support (*.po) (181.4668.78)
Haml (181.4668.78)
Handlebars/Mustache (181.3741.1)
HTML Tools (2.0)
HTTP Client (181.4668.78)
hunspell (1.0)
IDE Settings Sync (181.4668.78)
Ideolog (181.0.7.0)
Ini4Idea (181.4668.78)
IntelliLang (8.0)
JavaScript Debugger (1.0)
JavaScript Intention Power Pack (0.9.4)
JavaScript Support (1.0)
Joomla! Support (181.4668.78)
Laravel Plugin (0.15)
Less support (181.4668.78)
Markdown support (181.4668.78)
Material Theme UI (2.2.0.1)
Mercurial Integration (10.0)
NodeJS (181.4668.78)
Perforce Integration (2.0)
Performance Testing (181.4668.78)
Phing Support (181.4668.78)
PHP Docker (181.4668.78)
PHP Remote Interpreter (181.4668.78)
PHPSpec BDD Framework (181.4668.78)
PhpStorm Workshop (181.4668.78)
QuirksMode (181.4668.78)
Refactor-X (2.01)
Remote Hosts Access (0.1)
ReStructuredText Support (181.4668.78)
Sass support (181.4668.78)
Settings Repository (181.4668.78)
SSH Remote Run (0.1)
Subversion Integration (1.1)
Task Management (1.0)
Terminal (0.1)
TextMate bundles support (181.4668.78)
Time Tracking (1.0)
tslint (181.4668.78)
Twig Support (181.4668.78)
UML Support (1.0)
Vagrant (181.4668.78)
Vue.js (181.4668.78)
W3C Validators (2.0)
WordPress Support (181.4668.78)
XPathView + XSLT Support (4)
XSLT-Debugger (1.4)
YAML (181.4668.78)

**Comment by taha-moghaddam** [comment]
I have this problem, too.
