### ISSUE TITLE
Love the new icons, any chance we can make plugins consistent?

### ISSUE THREAD

**Issue by blackxored** [ChrisRM/material-theme-jetbrains#773]
### Summary

The new (monochrome) icons look great, however they stand out when you're using plugins that add stuff to tool window bar.
 

### Expected behavior

Either all icons to be monochrome or an option to disable monochrome icons altogether. Consistency above all ;)

### Actual behavior

<img width="633" alt="screenshot 2018-05-15 21 19 40" src="https://user-images.githubusercontent.com/133308/40078789-f9e84790-5885-11e8-8477-d393fd2d3c09.png">

### Steps to reproduce (if needed)

1. Install a plugin like the ones above.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.2371.4, built on May 15, 2018
IntelliJ IDEA EAP User
Expiration date: June 14, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

If possible please also give out your Material Theme/Material Custom Theme configuration file.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
These icons don't come from the plugin but from Jetbrains. I am currently working on a fix to bring back the Material Icons.
