### ISSUE TITLE
Edit Terminal / Debugger Tab colors

### ISSUE THREAD

**Issue by brianegan** [ChrisRM/material-theme-jetbrains#775]
Hey hey -- sorry if this is documented and I couldn't find it! I just noticed the tab colors for terminal / debugger now have a nice background color! Woohoo!

One Q: The default setting is a bit bright for my taste. I changed quite a few of the color options and read through the docs, but didn't find a setting that affected the tab color for debugger / terminal. Is there any option? Sorry if I missed it!

Thanks again for the all the hard work. <3 this plugin :)

**Comment by mallowigi** [comment]
Can you provide a screenshot of it ?

**Comment by brianegan** [comment]
<img width="1072" alt="screen shot 2018-05-17 at 9 25 09 pm" src="https://user-images.githubusercontent.com/126604/40199134-66870b3c-59cd-11e8-8253-1ab1e3abc707.png">

**Comment by mallowigi** [comment]
Oh, it's the Tabbed Pane highlight color. I think it's the highlight color or the misc color

**Comment by mallowigi** [comment]
my bad it's the selection background color

**Comment by brianegan** [comment]
Ah, ok interesting -- I tried modifying that color in the settings and restarting, but I don't see a visual change. Thanks for your help

**Comment by mallowigi** [comment]
You need to select the Custom Theme in the list in order to see the custom colors, right?

--
Elior

**Comment by brianegan** [comment]
Oh, dammit -- thanks.

**Comment by brianegan** [comment]
Would there be a possibility of Splitting the "Selection Background Color" And "tabs colors" apart? The contrast of the default "selection background color" looks great in most places, but is just a bit bright for tabs, especially with "High Contrast Mode" on

**Comment by mallowigi** [comment]
The most I can do is put that color into another group, such as highlight color

**Comment by brianegan** [comment]
Cool, appreciate your time and chatting through this. I've found a "happy medium" between something that works for selections as well as the tabs. 

I do think it'd be great to be able to tweak them independently, but I can imagine that's not a trivial task :)
