### ISSUE TITLE
Sidebar / Compact sidebar vertical item distance

### ISSUE THREAD

**Issue by Helmi** [ChrisRM/material-theme-jetbrains#779]
Thanks for the theme. I like it a lot even though it could need some visual fine tuning and better weighing of sizes and distances.

One important thing to me is the vertical distance of the items in the sidebar. In default mode, they are spaced too far IMHO while in the compact sidebar mode the distance is nearly non-existent. 

Maybe the compact mode should stay that way but I would reduce the normal mode distance by at least 20-30%. I would test out a good value but I totally don't know how to modify it.

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/development/installation/

You can meddle with it until you find yourself a good setting, then use your fork instead of the original.

I do not plan to allow more fine tuning at the moment
