### ISSUE TITLE
Intellij 15 EAP doesn't start

### ISSUE THREAD

**Issue by emartynov** [ChrisRM/material-theme-jetbrains#78]
Thanks for plugin!

I've tried to install and got exception on restart:
<img width="851" alt="screenshot 2015-10-16 17 24 18" src="https://cloud.githubusercontent.com/assets/295424/10545800/c96e91ce-742a-11e5-9150-6aa01cfb8a62.png">

Sorry can not copy paste

**Comment by emartynov** [comment]
Same happens with Android Studio 1.5 Preview

**Comment by ChrisRM** [comment]
I'm not prioritizing EAP builds atm, but I'll look into it later.

**Comment by emartynov** [comment]
Android Studio is always in preview :) And IntelliJ 15 is just beatiful :)

**Comment by topka** [comment]
IntelliJ IDEA 15 is already in Public Preview, release is expected in early November. Would be awesome to have it working in 15 once it's released.

**Comment by Kussie** [comment]
Would be awesome to get support in Idea 15

**Comment by voydz** [comment]
Version 0.1.7 works for me with phpStorm 10 EAP (should be the 15 Idea engine if I am not mistaken).

**Comment by emartynov** [comment]
Just tried and still see issues but Stacktrace is looking differently
