### ISSUE TITLE
Failed to create Look and Feel

### ISSUE THREAD

**Issue by achrafbou1** [ChrisRM/material-theme-jetbrains#780]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary

This error pops up everytime i startup IntelliJ Ultimate and it happened everytime i install this plugin. I tried installing it from the plugin menu as well as a manual installation, with no success.

### Expected behavior

IDE starts correctly, without any dialog messages popping up everytime.

### Actual behavior
Two identical dialog messages pop up.

##Screenshot of the problem

![image](https://user-images.githubusercontent.com/30400532/40266016-27734e12-5b33-11e8-8790-df5ffd0cde98.png)

### Environment

IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
Licensed to OS

JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

* Windows 10 64-bit
* Intellij 2018.1.3
* Material Theme UI version 2.2.3.1
* Couldn't find thefile material_theme.xm

**Comment by mallowigi** [comment]
It's from JFormDesigner. You need to change the settings at Settings > Other > JFormDesigner > Look and Feels and uncheck the option "Enable Look and Feel switching"
