### ISSUE TITLE
Font size of project tree

### ISSUE THREAD

**Issue by Paviluf** [ChrisRM/material-theme-jetbrains#782]
Hello,

Is there a way to change the font size of the project tree (sidebar) ? The font size is too big for me. If the setting exist I didn't found it and if it's not possible would you consider to add it please ?

Thanks !

**Comment by mallowigi** [comment]
Have you tried changing the font size in appearance > override font?

**Comment by Paviluf** [comment]
Yes but it doesn't change the project tree font size.

**Comment by mallowigi** [comment]
I just found out that it did. But you need to restart the IDE

**Comment by Paviluf** [comment]
That work ! Thank you.
