### ISSUE TITLE
Contrast is less than ideal when using the lighter theme outside

### ISSUE THREAD

**Issue by Maxr1998** [ChrisRM/material-theme-jetbrains#783]
First of all, I really love this theme. Makes development in Android Studio much more pleasant. So, thanks a lot for creating it!

I'm generally using the dark theme, but if I'm outside or near a bright window, it's more practicable to use the light theme. However, contrast and readability of the syntax highlighting is kinda bad, especially for comments, JavaDoc/KDoc, but also the light cyan of the class attributes..
So, if it's possible, I'd suggest adding maybe a variant of the Lighter theme with better contrast, or improve upon the lighter theme.
If you want, I could take a look at what I can do :)

**Comment by mallowigi** [comment]
OMG the difference between FiraCode and Menlo in Mac are light night and day:
![firacode](https://user-images.githubusercontent.com/5015756/41189743-50ed7368-6bdb-11e8-84ec-28b61d7911cb.png)
![menlo](https://user-images.githubusercontent.com/5015756/41189744-51109b54-6bdb-11e8-974d-914376177223.png)

I don't know what to do, FiraCode looks great on Windows (and possibly Linux) but crap on Mac...
