### ISSUE TITLE
Dark Theme does not render variables properly

### ISSUE THREAD

**Issue by hhimanshu** [ChrisRM/material-theme-jetbrains#79]
As you could see, variables are not visible

<img width="813" alt="screen shot 2015-10-17 at 10 57 14 am" src="https://cloud.githubusercontent.com/assets/6589036/10560362/01868934-74be-11e5-91a7-cb50c85a1e00.png">

**Comment by ChrisRM** [comment]
I'm not able to reproduce this. Please provide me an example code @hhimanshu

**Comment by hhimanshu** [comment]
Try this code

```
package com.identity.business

import com.harness.UnitSpec

class LocalhostTest extends UnitSpec {
  behavior of "Localhost"

  "Mac Address" should "return a non-empty String" in {
    Localhost.getMacAddress should not be empty
  }

  "nodeId" should "return same hash for Mac Address when asked twice" in {
    val nodeIdOne: Int = Localhost.nodeId
    val nodeIdTwo: Int = Localhost.nodeId

    nodeIdOne shouldEqual nodeIdTwo
  }

  "getNodeId" should "return different hashed for different inputs" in {
    val hashOne = Localhost.getNodeId("StringOne")
    val hashTwo = Localhost.getNodeId("StringTwo")

    hashOne should not equal hashTwo
  }
}
```
I still see issues (upgraded last night). and I am using `IntelliJ IDEA 14 CE`
<img width="1279" alt="screen shot 2015-10-31 at 8 15 58 am" src="https://cloud.githubusercontent.com/assets/6589036/10864331/d53050f0-7fa7-11e5-8683-596e2967d848.png">

**Comment by Juchar** [comment]
Just as a hint, maybe it helps:
the class `java.io.File` has a lot of those black on black variables in it (using theme version `1.7`).

**Comment by hhimanshu** [comment]
Yeah, It really discourages me from using Dark theme

**Comment by tomrenn** [comment]
+1, seeing the same thing for Java in Android Studio 2.0 (Preview 3) based off Idea 14 (I believe)

**Comment by mbilbille** [comment]
Plan to release this fix any time soon?
