### ISSUE TITLE
Custom Theme is broken (thanks IDEA!)

### ISSUE THREAD

**Issue by mallowigi** [ChrisRM/material-theme-jetbrains#793]
*sigh*

**Comment by yudhir** [comment]
I am seeing that Version Control > File Status Color > Upto date colors is always setback to a non contrasting color . Even Changing it , it is restored back to the same color. Is this plugin responsible?

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/file-status-colors/

In short yes, but this is by definition.

**Comment by yudhir** [comment]
Oh! Ok , No problems , fixed through that at least for now,

**Comment by mallowigi** [comment]
I've issued a fix, looks much better now (2.3.3.2)
