### ISSUE TITLE
how to change color of navigation bar and menu in phpstorm 2018.1.4

### ISSUE THREAD

**Issue by LdDv9** [ChrisRM/material-theme-jetbrains#798]
i can't change color of navigation bar and menu in phpstorm 2018.1.4, issue in this link 

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000017799-Can-t-change-color-of-navigation-bar-and-menu-in-php-storm-2018?flash_digest=ff428d06df1c9b5b6670fbb3fa5ec483950ca653

**Comment by mallowigi** [comment]
You can find your answer here http://www.material-theme.com/
