### ISSUE TITLE
Little color fix?

### ISSUE THREAD

**Issue by B-iggy** [ChrisRM/material-theme-jetbrains#8]
Hey Chris,

can you please adjust the color of the equal sign (in js) to white? It's too unitary.

For reference in sublime:
![sublime](https://cloud.githubusercontent.com/assets/7815434/10263432/54c55a32-69ef-11e5-93d9-901d44a850df.PNG)

and this is how it looks like in my PhpStorm:
![phpstorm](https://cloud.githubusercontent.com/assets/7815434/10263437/609a0b8c-69ef-11e5-89b7-8e17ea708302.PNG)

**Comment by ChrisRM** [comment]
tbh, the screenshot you provided of the phpstorm scheme is not at all what I'm getting here. What I'm seeing in your sublime shot doesn't look correct either. Did you modify your scheme somehow?

**Comment by B-iggy** [comment]
Nope. In sublime I did the normal install procedure for the material theme and in PhpStorm I only copied your material theme.icls in the color config directory.

Maybe Windows 10 specific. Or can anyone with Windows 10 show us their color scheme for a javascript file?

**Comment by ryanwinchester** [comment]
I can conform in OS X variables are not red

![screenshot](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screenshot+2015-10-03+13.37.47.png)

**Comment by ryanwinchester** [comment]
Sublime text:

![](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/Screenshot+2015-10-03+13.44.56.png)
