### ISSUE TITLE
Font size on HiDPI display

### ISSUE THREAD

**Issue by pejaham** [ChrisRM/material-theme-jetbrains#804]
Since updating to version Materialize Theme UI 2.4.0 the font size in the Materialize controlled windows (i.e. Project Toolwindow) is tiny (all JetBrains products). Maybe the introduction of being able to set the font size in 2.4.0 introduced this bug. I had to revert to 2.2.3.1.

**Comment by mallowigi** [comment]
The default font size is 12. Try to change to a bigger value since it is now customizable.

I need to test on HiDPI displays but as far as I saw in the code, it was 12 by default.

**Comment by pejaham** [comment]
I am aware of the fact that I can configure the font size. I think, though, that the plugin should be HiDPI aware and scale automatically. Otherwise the 12pt setting in IDEA (general and editor settings) are different from the 12pt setting in the plugin, i.e. the plugin would need 24pt to display 'real' 12pt in the host application. I would consider this a bug.

**Comment by mallowigi** [comment]
should be fixed
