### ISSUE TITLE
Code editor background are not supported in Android Studio 1.4

### ISSUE THREAD

**Issue by stepango** [ChrisRM/material-theme-jetbrains#81]

**Comment by ChrisRM** [comment]
I need a bit more information here.

**Comment by stepango** [comment]
![screen shot 2015-10-20 at 10 41 40 am](https://cloud.githubusercontent.com/assets/1287797/10596472/33b2a45a-7717-11e5-8a01-b3334a12373e.png)

Plugin version 0.1.6

**Comment by ChrisRM** [comment]
You need to set the color scheme manually. From the docs:

> Go to Preferences -> Editor -> Colors & Fonts -> Scheme -> Choose between the 3 Material Theme's.

I guess Preferences is actually "Settings" in AS.
