### ISSUE TITLE
HighDPI issues with Arrows and trees

### ISSUE THREAD

**Issue by testmyusernamebaby** [ChrisRM/material-theme-jetbrains#811]
1- Arrow icons are blurred
2- if [folders or file] selected sequentially white line begin appear down each one of selected items 
3- black lines in toolbar
photos ..
1- https://imgur.com/92K0bBc
<img src="https://i.imgur.com/92K0bBc.png">

2- https://imgur.com/OR75Rrk
<img src="https://i.imgur.com/OR75Rrk.png">

3- https://imgur.com/dRsA4nR
<img src="https://i.imgur.com/dRsA4nR.png">
_______________________________________________________________________
Request :
please make scrollbars like atom scrollbars

**Comment by mallowigi** [comment]
Can you provide enviornment details ?

**Comment by testmyusernamebaby** [comment]
@mallowigi 

PhpStorm 2018.1.5
Build #PS-181.5281.19, built on June 7, 2018
Windows 10 10.0

Note : not just phpstorm all Intellij products the same problem
__________
the problem appear since PhpStorm 2017.3 or 2017.4

**Comment by testmyusernamebaby** [comment]
@mallowigi 
i detect the problem it's DPI scaling

**Comment by mallowigi** [comment]
What is your dpi scaling ?

**Comment by testmyusernamebaby** [comment]
the default one 
when i change dpi to system the problem fixed but it became so blurred

**Comment by mallowigi** [comment]
how do you change the dpi? AFAIK it's on Windows Display settings > size of text ...

**Comment by testmyusernamebaby** [comment]
right click on phpstorm -> properties -> compatibility -> change DPI settings

**Comment by testmyusernamebaby** [comment]
i fixed it when change font size to 100% it was 125% 
but it really small any other fix ????

**Comment by mallowigi** [comment]
OK! Found it. It looks like an issue from Jetbrains.

Setting the dpi to 150%/200% doesnt show the problem, but 125% does.

For the rest of the bugs:
2. I also could not reproduce the issue in 150%
3. WDYM exactly? 

So yeah, not a bug on my end. (yes!)

**Comment by mallowigi** [comment]
On a sidenote, the icons render so well at a higher DPI!

**Comment by testmyusernamebaby** [comment]
but when i disable material plugin every things are ok and no problem

**Comment by mallowigi** [comment]
Interesting. Also anything is blurry when I'm on 125%... 
![image](https://user-images.githubusercontent.com/5015756/41305668-48398dbc-6e7c-11e8-84e9-3eb531c22fcf.png)
