### ISSUE TITLE
UI Plugin for Jetbrains PHPStorm has broken in the latest update

### ISSUE THREAD

**Issue by Smileysoftware** [ChrisRM/material-theme-jetbrains#812]
An update to Material Theme plugin has broken the IDE. 
The IDE is utterly unusable sadly.

I have had to remove the plugin by deleting the files in ~/Library/Application Support

I'm using OSX 10.13.5 on a MBP 15"

Thanks in advance

**Comment by mallowigi** [comment]
what do you mean by "broken" and "unusable"? Also can you provide your environment details?

**Comment by rweber7912** [comment]
I have the same problem! Macbook Pro 15", macOS High Sierra 10.13.4 PhpStorm 2018.1.5 and the latest Material Theme UI plugin. If I delete whole folder from ~/Library/Application Support it's all fine, but as soon as I install Material Theme UI I can't even pass PhpStorm project selection window. Now it's stuck on startup banner! Let me know where I can find more info/log so I can paste it here. Hopefully there's more details somewhere. Nothing in PhpStorm works, so I can't even see error messages.

**Comment by deepakprathapani** [comment]
I am facing similar issue. My IntelliJ is frozen while loading. 
IntelliJ version : Community Edition 2018.1
OS version: macOS Sierra Version 10.12.6

**Comment by mallowigi** [comment]
Can you please provide your environment details and your material_theme.xml file ?

**Comment by deepakprathapani** [comment]
Where do I find that?

**Comment by deepak-on-air** [comment]
List of other existing plugins,
BlackCaiman
EclipseFormatter
IdeaVim
lombok-plugin
Material Theme

**Comment by mallowigi** [comment]
~/Library/Preferences/<PRODUCT><VERSION>/material_theme.xml ..........................

**Comment by deepak-on-air** [comment]
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.4.0.3-2018.1" />
    <option name="userId" value="-516935f7:163f4c1dcd2:-8000" />
  </component>
</application>

**Comment by deepak-on-air** [comment]
`<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.4.0.3-2018.1" />
    <option name="userId" value="-516935f7:163f4c1dcd2:-8000" />
  </component>
</application>`

**Comment by mallowigi** [comment]
still can't reproduce. Also I don't know what the BlackCaiman is

Do you have the logs perhaps ?

**Comment by deepak-on-air** [comment]
That's an internal company plugin. Since others are facing the similar issue, I presume that this might not be the root cause.

**Comment by mallowigi** [comment]
Can you disable the plugin and try again? I've installed the other plugins and still cannot reproduce the issue. And your settings file is the default one

**Comment by deepak-on-air** [comment]
No luck

**Comment by mallowigi** [comment]
Do you happen to see errors on the logs ?

**Comment by deepak-on-air** [comment]
I do see some exceptions in the log file yeah.

**Comment by deepak-on-air** [comment]
Attaching the partial log file with all the exceptions captured. 
[Log to Upload.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/2095250/Log.to.Upload.txt)

**Comment by mallowigi** [comment]
What is the version of the plugin you have ?

**Comment by deepak-on-air** [comment]
I deleted the plugin now since my workspace doesn't open. Although I presume material_theme.xml (updated earlier) should have those details.

**Comment by mallowigi** [comment]
Ok I'll try to reproduce with those details. I'm seeing call to an API that wasn't available in previous versions of the IDE. Since I've tested only on the last release of the 2018.1, it's possible it got broken on older versions.

I'll see if it's possible to fix, otherwise I'll demand you to update to the latest release.

**Comment by deepak-on-air** [comment]
Do update here once you fix and push the latest build.

**Comment by darbyjack** [comment]
Idk how I can help but I'll add in that on my IntelliJ I get stuck on the loading screen ever since the last update. I have to remove the Material Theme too in order to launch.

**Comment by mallowigi** [comment]
For all who are stuck: either download the latest 2018.1 release or downgrade the plugin to version 2.2.3 from the plugins page. I’ll try to see if the latest changes can be set on older versions but if it’s not, I’ll rollback the changes

**Comment by darbyjack** [comment]
Thanks for the quick response. Downgrading fixed it!

**Comment by darbyjack** [comment]
I'm currently running on v2.2.3 with Build #IU-181.4203.550

**Comment by deepak-on-air** [comment]
Plugin worked after upgrading my IDE to IDEA 2018.1.4.

**Comment by mallowigi** [comment]
Ok fixed.
