### ISSUE TITLE
Use matching terminal color scheme for atom one dark

### ISSUE THREAD

**Issue by gpspake** [ChrisRM/material-theme-jetbrains#814]
### Summary

The atom one dark theme seems to use a terminal/console scheme that doesn't match the rest of the editor (I think it seems to be using the oceanic theme for the terminal)

Notice how they seem mismatched:
![material one dark](https://i.imgur.com/h9CZp7C.png)

### Expected behavior

I expect a matching one-dark background and color scheme in the terminal as the rest of the editor

### Actual behavior

Instead the theme seems to use the oceanic theme. (I'd really be content if I could just change the background)

### Environment

* macOS High Sierra
* IntelliJ Idea 2018.1.4 (Ultimate Edition)
* Material Theme UI 2.4.0.4-2018.1
* Plugin configuration (found in material_theme.xml)
* No additional plugins installed

material_theme.xml
```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.4.0.4-2018.1" />
    <option name="selectedTheme" value="ONE_DARK" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="userId" value="34b00b10:163fac8632b:-8000" />
    <option name="allowDataCollection" value="true" />
  </component>
</application>
```
material_custom_theme.xml
```
<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by gpspake** [comment]
Uh... looks like it's fixed. Awesome! Thanks @mallowigi 😸

**Comment by armved** [comment]
Still have this issue, version 2.1.3

**Comment by mallowigi** [comment]
it has been fixed on recent versions, please update

**Comment by armved** [comment]
Uh, I thought I have last version. Just needed to click "Reload list of plugins" to see that I have old version. Thanks!
