### ISSUE TITLE
Change folder decorators 

### ISSUE THREAD

**Issue by VitalyKrenel** [ChrisRM/material-theme-jetbrains#816]
Hello! It would be nice to have an option for setting the color of folder decorators. I think it may help when you use monochrome icons. 
Right now monochrome icons option makes folder decorators almost useless as decorators are close to being invisible (like any decent ninja but whatever):

<img src="https://user-images.githubusercontent.com/17354709/41459411-317857bc-7092-11e8-9a64-76dee138105a.png" width="150">

I don't know how the process of adding decorators is built, but if you are adding a small additional SVG icon coloring should be a problem, right?

Whether or not, thanks in advance.

**Comment by mallowigi** [comment]
Yes but I can't do this because the monochrome filter applies to all icons regardless of whether they are decorators.

I can add an option to specify the color of the monochrome, but it would beat the point of monochrome, no?

**Comment by VitalyKrenel** [comment]
@mallowigi Alright, then. Probably, the color of the monochrome filter isn't a necessary thing (at least for the majority of people using the material theme), so just leave decorator question as it is.
