### ISSUE TITLE
CLion 2018.2 EAP Support?

### ISSUE THREAD

**Issue by vemilyus** [ChrisRM/material-theme-jetbrains#820]
The plugin doesn't show up in the "Browse Plugins" list.

CLion 2018.2 EAP
Build #CL-182.3208.14, built on June 13, 2018
CLion EAP User
Expiration date: July 13, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

**Comment by mallowigi** [comment]
That's weird, they should at least contain previous versions...

Here's the latest build:
[Material Theme-2.4.1.2-2018.2.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2108668/Material.Theme-2.4.1.2-2018.2.zip)

**Comment by vemilyus** [comment]
The build definitely works, perhaps it's just some issue with the plugin repository.
