### ISSUE TITLE
Kotlin files aren't recognized

### ISSUE THREAD

**Issue by SirWellington** [ChrisRM/material-theme-jetbrains#827]
### Summary

The Atom File Icons aren't appearing for Kotlin files.

...

### Expected behavior

A nice pretty kotlin icon for .kt or kotlin files.

---

### Actual behavior

![screen shot 2018-06-21 at 2 36 59 pm](https://user-images.githubusercontent.com/992646/41746831-9d59399c-7560-11e8-8451-e1f25e360cbf.png)
![screen shot 2018-06-21 at 2 37 05 pm](https://user-images.githubusercontent.com/992646/41746840-9fe6eb14-7560-11e8-8b84-11bc40e31c74.png)

---

### Environment

IntelliJ IDEA 2018.2 EAP (Ultimate Edition)
Build #IU-182.2757.3, built on May 28, 2018
IntelliJ IDEA EAP User
Expiration date: June 27, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

Material Theme Plugin version: `2.4.0.5-2018.2`

**Comment by mallowigi** [comment]
Can you send me the list of plugins you use ?

**Comment by SirWellington** [comment]
Why was this closed?

**Comment by mallowigi** [comment]
Because it's very likely that this is occuring on your configuration. I work with Kotlin and I don't see your gear icon. 

It could be because of a plugin

**Comment by SirWellington** [comment]
Classic "it works on my computer so it must be you" response. If you don't want to help, give it to someone who is.

**Comment by mallowigi** [comment]
It's not because I closed the issue that I don't want to help. Again, give me the list of the plugins......

**Comment by SirWellington** [comment]
I did my own investigation. Your last comment gave me some ideas. Disabling an unused **_Afterglow Theme_** fixed my issue. Thank you.
