### ISSUE TITLE
The "Help Make Material Theme UI Better" message in events log is not dismissable

### ISSUE THREAD

**Issue by tzurbaev** [ChrisRM/material-theme-jetbrains#829]
### Summary

I've noticed that on every PhpStorm's startup there's a usage statistics permission message in the event log:

> Help Make Material Theme UI Better: We are asking your permission to send information about your configuration (what is enabled and what is not) and feature usage statistics (e.g. how frequently you are using a feature). This data is anonymous, does not contain any personal information, collected for use only by the Material Theme Plugin Team and will never be transmitted to any third party.

This message contains no links to settings and I was unable to find any option to enable/disable this telemetry in PhpStorm's settings.

### Expected behavior

There's should be an ability to dismiss this message by enabling/disabling usage statistics.

### Actual behavior

There's no option (if it is, it's not clear & I was unable to find it) and the message keeps spamming me at every IDE startup. 

### Steps to reproduce (if needed)

1. Start your IDE.
2. Look at the events log. The message is here.
3. Clear events log, restart IDE. The message is still here.

Screenshot: https://i.imgur.com/Yn5B6xn.png

### Environment

PhpStorm 2018.1.6
Build #PS-181.5281.35, built on June 15, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-45-generic

* OS: Ubuntu 17.10
* IntelliJ Product: PhpStorm 2018.1.6
* Plugin version: 2.4.2-2018.1

I'm not sure where to find both plugin configuration file & custom theme configuration file. If required, please, guide me to its location & I'll provide it.

**Comment by mallowigi** [comment]
Hum, it should appear as a popups and only after selecting an option (i.e opt-in or opt-out) then the message would not come back.

Do you have the notifications disabled by chance? (Settings -> balloon notifications)

**Comment by tzurbaev** [comment]
@mallowigi Yes, balloon notifications were disabled. I've enabled balloons, restarted IDE and there was a popup with buttons. Now the message is gone, thank you! :+1:

**Comment by LeeMatt3000** [comment]
Did anyone clear this up?  I'm having the same issue...
