### ISSUE TITLE
[icon] old PHP icon is still displayed

### ISSUE THREAD

**Issue by jaoued** [ChrisRM/material-theme-jetbrains#83]
Hi,

The new php icon is missing from 1.0.5 and 1.0.6 versions of this plugin.

Env: Windows 7 - PhpStorm 9.0.2, 

Regards.

**Comment by strebl** [comment]
Same problem.

Env: Windows 10 - PhpStorm EAP 143.279

**Comment by jaoued** [comment]
Hi @ChrisRM ,

I installed the new version (0.1.61) and i still have the old php icon.

@strebl are you the same problem?

Regards.
