### ISSUE TITLE
Directory Exclusion 

### ISSUE THREAD

**Issue by anandpatel** [ChrisRM/material-theme-jetbrains#830]
How do you change the colour excluded folders? I am using the Oceanic theme and don't like the white highlighting.

![issues_ _chrisrm_material-theme-jetbrains_and_encounter_edu____sites_encounter_edu_](https://user-images.githubusercontent.com/1301184/41852903-4fa41b14-7884-11e8-8d4c-ce0dbe122b7a.png)

**Comment by mallowigi** [comment]
Appearance > File Colors. If you selected "Theme", just restart and it'll be okay.
