### ISSUE TITLE
Structure, always at the bottom

### ISSUE THREAD

**Issue by WinstonN** [ChrisRM/material-theme-jetbrains#832]
Hi Hi, 

### Summary

Small issue I picked up. My structure is on the right in Jetbrains (I use IntelliJ, PHPStorm, PyCharm) but it always defaults to the bottom, as you can see from the image here https://snag.gy/QiuIUL.jpg
I drag it to the top, save the layout, but as soon as I reopen the application, structure is at the bottom again. 

This makes it difficult to navigate code methods

### Environment

IntelliJ IDEA 2018.1.5 (Community Edition)
Build #IC-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-23-generic

**Comment by mallowigi** [comment]
Can you make sure that it's not a bug from the IDE but from the plugin?

**Comment by WinstonN** [comment]
Hi @mallowigi 

By default, without Material Theme UI this does not happen. I also didn't used to happen, the third last update (I think it was) caused this

Winst

**Comment by WinstonN** [comment]
@mallowigi You are right, I disabled material theme ui, restarted the IDE, and the tab was still at the bottom. It could very well be a IDE bug, I am closing this issue

Winst
