### ISSUE TITLE
Material One Dark Color Scheme disappeared

### ISSUE THREAD

**Issue by phildinh** [ChrisRM/material-theme-jetbrains#833]
### Summary
Since this morning's update, I can't find "Material One Dark" from the Color Scheme anymore.

### Expected behavior

"Material One Dark" should be shown in the Color Scheme.

### Actual behavior

"Material One Dark" doesn't show up in the Color Scheme.

### Steps to reproduce (if needed)

Update the theme to the latest build (2.4.2?)

### Environment

IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
Yep I deleted it, it was a clone of the Darker with only the background color changed.

**Comment by phildinh** [comment]
Could you please re-add it? It honestly really blends well with the Atom One Dark theme, such a pleasure for the eyes.
The Darker one has the same text highlighting but the background is way too dark for me.

Screenshot for reference:
![image](https://user-images.githubusercontent.com/33832968/41962632-d176103a-79f5-11e8-8298-f04040584757.png)

**Comment by mallowigi** [comment]
Nope. It's adding too much support for such a small change. You can simply duplicate the Darker and change the background color with the one of the One Dark, or even simply import the color scheme.
