### ISSUE TITLE
Compact statusbar bug

### ISSUE THREAD

**Issue by yasuokav** [ChrisRM/material-theme-jetbrains#834]
### Summary

I turned off "Compact Statusbar". But the status bar becomes compacted when multiple projects opened.

### Steps to reproduce

1. Open Project1
2. Open Project2
3. Re-open Project2
4. The status bar of Project2 becomes compacted (If not, please repeat step3)

### Environment
* macOS 10.13.5
* IntelliJ IDEA 2018.1.5 (Ultimate Edition)
* Material Theme UI 2.4.2
* Default config

**Comment by mallowigi** [comment]
I've fixed this in the next release.
