### ISSUE TITLE
Material icons appear in WebStorm Navigation Bar but not Project Tool window

### ISSUE THREAD

**Issue by techpeace** [ChrisRM/material-theme-jetbrains#835]
### Summary

Some Material icons render correctly in the WebStorm 2018.1.5 Navigation Bar, but render as the default gear wheel icon in the Project Tool sidebar window:

![](http://share.voxable.io/0s0n1T1v2F3d/[635e548f15760e3b326ee3f82e7ad22f]_Screen%20Shot%202018-07-02%20at%202.12.27%20PM.png)

![](http://share.voxable.io/3n1p0K1f1d43/[80d729df1dcdaa424adbc6738e954aec]_Screen%20Shot%202018-07-02%20at%202.12.09%20PM.png)

...

### Expected behavior

Files of the same type should render the same material icon in both the Navigation Bar and Project Tool window.

...

### Actual behavior

Some file types (e.g. `.vue`, `.ts`) render the correct icon in the Navigation Bar, and the default icon in the Project Tool window.

...

### Environment

* OS (Windows, Linux, Mac)

macOS 10.13.5

* IntelliJ Product + version (IDEA, RubyMine...)

WebStorm 2018.1.5

* Material Theme Plugin version

2.4.2-2018.1

Here are [the contents of my Material Theme settings files](https://gist.github.com/techpeace/7bf8bd769c16ba1fd88bfa35d9651e17).

Thanks!

**Comment by mallowigi** [comment]
Do you use the Afterglow plugin by chance?

**Comment by mallowigi** [comment]
Ok I know you are using the Afterglow plugin. The plugin is incompatible with the Material Theme.

**Comment by techpeace** [comment]
Ah! I forgot that was installed. Indeed, disabling Afterglow fixed the issue with the icons.

Thanks!
