### ISSUE TITLE
[Question] How to change general text color?

### ISSUE THREAD

**Issue by jeffrey-igaw** [ChrisRM/material-theme-jetbrains#837]
### Summary

![1](https://user-images.githubusercontent.com/30995427/42212031-f0e93f1a-7eef-11e8-90a8-9ec2552f7251.png)

Hi!

When i use material(2.5.0) with `one atom dark` theme and update Rider 18.2, general font color is so white...! XD

How to change theses? maybe looks like real white(`#FFFFFF`). it seems a little strong to me. T_T

Thanks. :)

### Environment
```
JetBrains Rider 2018.2 EAP
Build #RD-182.3458.147, built on June 30, 2018
Rider EAP User
Expiration date: July 30, 2018
JRE: 1.8.0_152-release-1226-b7 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
* Plugin version : 2.5.0

**Comment by mallowigi** [comment]
Nobody reads the documentation eh...

You need to disable the "High Contrast mode"

**Comment by jeffrey-igaw** [comment]
@mallowigi oh my god. I'm really sorry, I don't know High Contrast Mode is enabled as defualt after update plugin. I'll check the documents from now on. 😥
