### ISSUE TITLE
Lighter theme

### ISSUE THREAD

**Issue by stojankukrika** [ChrisRM/material-theme-jetbrains#84]
Hi, when is planned to release date of Lighter theme?

**Comment by ChrisRM** [comment]
I hope to release an improved version later this week.

**Comment by stojankukrika** [comment]
great! TNX.

**Comment by yeluolei** [comment]
waiting for a better lighter theme

**Comment by IceMan81** [comment]
@ChrisRM Firstly, your theme is pretty cool! Thanks for the work you have put in. I look forward to the lighter theme as well since I use Intellij on Windows for my day job. I prefer the dark themes only on my Retina display.

**Comment by thedevsaddam** [comment]
@ChrisRM Is the lighter theme will be appear not not???
