### ISSUE TITLE
How to remove the background image

### ISSUE THREAD

**Issue by smartlin** [ChrisRM/material-theme-jetbrains#844]
hello，I don't want to use this theme，But I can't get rid of the background image，What should I do?
Thanks!

![1](https://user-images.githubusercontent.com/4127844/42726533-7ddd0fce-87c8-11e8-80ca-5bb7b94ef10a.jpg)

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/faq-troubleshooting/
