### ISSUE TITLE
Allow sending information about usage

### ISSUE THREAD

**Issue by baao** [ChrisRM/material-theme-jetbrains#845]
Hi, 

I'm using your theme and am showed the message 

> Help Make Material Theme UI Better: We are asking your permission to send information about your configuration (what is enabled and what is not) and feature usage statistics (e.g. how frequently you are using a feature). This data is anonymous, does not contain any personal information, collected for use only by the Material Theme Plugin Team and will never be transmitted to any third party.

I'd like to allow this, but don't find where I can allow it. There's no link in the text, and in the settings I don't find an option to allow sending the data to you. 

Where is it?

(I'm using intelij idea latest on an iMac)

**Comment by mallowigi** [comment]
It’s in the notification itself. Until you make a choice you will be presented the option. 

You can check in the documentation website for more information

**Comment by baao** [comment]
There's nothing in the notification itself

<img width="2549" alt="bildschirmfoto 2018-07-15 um 15 15 36" src="https://user-images.githubusercontent.com/9019906/42734320-0b25ba42-8842-11e8-82d7-d64d7d9fde9a.png">

**Comment by mallowigi** [comment]
I see. Someone else had the same problem. You need to display Balloon notifications to see the buttons.

**Comment by baao** [comment]
Thanks. That was it!

**Comment by nothingismagick** [comment]
Well, this is still happening - maybe it warrants an explanation somewhere.
