### ISSUE TITLE
Atom One Light: bad color at title

### ISSUE THREAD

**Issue by langolf** [ChrisRM/material-theme-jetbrains#846]
"Content is identical" title
![stat-controller js userslangolfworkbadooimages--jshon_v3new-versionoverlayswhats-new 2018-07-16 10 am-41-06 1](https://user-images.githubusercontent.com/1225205/42752117-da347876-88e4-11e8-956e-a9ece8a93ce3.jpg)

**Comment by mallowigi** [comment]
Did you apply the theme without restarting? There are some issues when switching Lafs that require a full restart

**Comment by mallowigi** [comment]
fixed in next version
