### ISSUE TITLE
Improve Monokai Pro syntax highlight

### ISSUE THREAD

**Issue by sajmonella9** [ChrisRM/material-theme-jetbrains#847]
VSC Syntax : 

![image](https://user-images.githubusercontent.com/8018061/42758468-ee4d9f08-8903-11e8-86dc-d269bde6b760.png)

![image](https://user-images.githubusercontent.com/8018061/42758547-3a124c36-8904-11e8-9b20-088fb16b7154.png)

PhpStorm Syntax : 

![image](https://user-images.githubusercontent.com/8018061/42758486-042b36aa-8904-11e8-9429-1e91f4ba9c96.png)

![image](https://user-images.githubusercontent.com/8018061/42758564-461e9188-8904-11e8-8586-c26e3b371276.png)

Example 👍

**Comment by mallowigi** [comment]
Yea, looks like the Monokai Pro theme is not completely faithful to the original theme. I'll work on it

**Comment by mallowigi** [comment]
Or did you have something else in mind

**Comment by sajmonella9** [comment]
i mean syntax numbers after $var or for example another words / tags like "solid" , "normal" , bold etc... is on the same color.
