### ISSUE TITLE
Unable to install latest versions of the plugin on Android Studio 3.1.3 / 3.2 Beta 4

### ISSUE THREAD

**Issue by leinardi** [ChrisRM/material-theme-jetbrains#851]
### Summary
Unable to install latest versions of the plugin of this plugin plugin on Android Studio 3.1.3 / 3.2 Beta 4

![image](https://user-images.githubusercontent.com/273338/43033775-656598f0-8cd0-11e8-9cd7-a543a9968aa7.png)

The latest working version for Android Studio 3.2 Beta 4 seems to be 2.4.2-2018.1.

### Expected behavior

The plugin should install correctly

### Actual behavior

The error "Plugin 'Material Theme UI' is incompatible with this installation' is shown

### Steps to reproduce (if needed)

1. Download the version 2.6.1 of the plugin from here: https://plugins.jetbrains.com/plugin/8006-material-theme-ui
2. Try to install the plugin in Android Studio (Settings -> Plugins -> Install plutin from disk...)

### Environment
Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29-generic

Android Studio 3.2 Beta 4
Build #AI-181.5281.24.32.4886486, built on July 11, 2018
JRE: 1.8.0_152-release-1136-b04 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29-generic

**Comment by mallowigi** [comment]
android-studio-ide-181.4884283-mac.zip

Unfortunately the SDK they are using is still 181, while the plugin's latest version for 181 is 2.4.2-2018.1

You will have to wait until AS merges the 182.3208.14 at least, and there is no plans on supporting 2018.1 releases. But the 2.4.2 release is pretty decent. It doesnt have the One Light or Deep Ocean theme but that's all. And if someone is courageous enough to make them available to these versions, I'll gladly merge.
