### ISSUE TITLE
[Question] What is the minimum IDE version required to support external themes?

### ISSUE THREAD

**Issue by xdrop** [ChrisRM/material-theme-jetbrains#852]
Hello and thanks for this awesome plugin! 🌟 

I'm using Material Theme UI and the extension points you described [here](
https://github.com/ChrisRM/material-theme-jetbrains#external-theme)  to publish the [Night Owl](https://github.com/xdrop/night-owl-jetbrains) theme.

I was just wondering what is the minimum version we need to set the IDE as in order to be able to get a version of Material Theme UI with external themes support?

On the [2.0.0](https://plugins.jetbrains.com/plugin/8006-material-theme-ui/update/44268) update I see 181.3494.1 but on your example [Dracula Theme](https://github.com/mallowigi/dracula-theme-jetbrains/blob/master/build.gradle) you list 182.2371.4

**Comment by mallowigi** [comment]
Try to read this, it should answer your questions
http://www.material-theme.com/docs/development/external-themes/

But in short, it should work from 2018.1+, but I've refactored it in 2018.2 so you should be developing for it.

**Comment by xdrop** [comment]
Okay, great thanks!
