### ISSUE TITLE
Bold Directories option does not appear to do anything

### ISSUE THREAD

**Issue by nazrhyn** [ChrisRM/material-theme-jetbrains#853]
### Summary
It doesn't seem like the **Project View / Bold Directories** option does anything. When I turn it on in my configuration, this is what directories look like:   
![image](https://user-images.githubusercontent.com/1672405/43085452-066546f8-8e69-11e8-8776-b585b28d05bf.png)

I tried loading a clean WebStorm profile and installing only the Material Theme plugin and turning on this option, and this is what I got:   
![image](https://user-images.githubusercontent.com/1672405/43085492-1a826918-8e69-11e8-836d-51a03e2c457b.png)

I included my configuration with this setting on and off; it appears that setting is actually called `isBoldTabs`, which is interesting, considering the label says "directories".

While I am on Linux, I seem to remember never having this setting do anything, even when I was on Windows; though, I can't be sure.

### Expected behavior
Bold directories? :nerd_face:

### Actual behavior
Not-bold directories. :cry:

### Environment
WebStorm 2018.2
Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-46-generic
Material Theme Plugin 2.6.1
Plugin Configuration https://gist.github.com/nazrhyn/047c16beb2a0fa5644ea472ada933b15

**Comment by mallowigi** [comment]
I just found out that this feature depends on the "Bookmark" style in Color Scheme, e.g. in the bundled themes this setting is set to bold, and the "Bold Directories" is using this style to decorate the folders. 

So if you're using another scheme or changed the color scheme, and the "Bookmark" setting is not bold, your directories won't be bold. On the other hand you can also set it to italic if you want to :)

I will not fix this for the moment, it's not that much used, maybe later 😃

**Comment by nazrhyn** [comment]
Heyy, that works if I change that to bold. Well, good to know :+1:.
