### ISSUE TITLE
One window wraps another one which contains the editor (WebStorm 2018.2)

### ISSUE THREAD

**Issue by Viperwow** [ChrisRM/material-theme-jetbrains#854]
### Summary

Seem window wrap another window component

### Expected behavior

Only one window header

### Actual behavior

Two window headers

### Steps to reproduce

1. Just open the editor

### Environment

WebStorm 2018.2
Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material theme UI plugin Version: 2.6.1

### Screenshots

![webstorm_ui_bug](https://user-images.githubusercontent.com/2028086/43125601-3050e3da-8f33-11e8-8435-e7ad87ef73c5.png)

**Comment by Viperwow** [comment]
Found one thing, when I install this plugin on a fresh installation of the WebStorm 2018.2 - no bugs

**Comment by mallowigi** [comment]
Thanks for the info
