### ISSUE TITLE
Material Oceanic background colour breaks in latest version

### ISSUE THREAD

**Issue by kstratis** [ChrisRM/material-theme-jetbrains#857]
### Summary

Material Oceanic theme seems to be broken.

### Expected behavior

The background color code of the theme is `#263238`. This should normally be the background color.

### Actual behavior

The background color code of the theme turns out to be `#1F292E` even though its value is set to `#263238`. 

### Steps to reproduce (if needed)

1. Upgrade to PyCharm 2018.2
2. Use the latest Material Theme plugin v2.6.1
3. Apply the Material Oceanic theme.

In **RubyMine 2018.1** this is what it used to look like:

![screenshot 2018-07-26 11 12 54](https://user-images.githubusercontent.com/1859806/43249969-dd815912-90c4-11e8-8176-8c5385fc3427.png)

In **PyCharm 2018.2** it looks like this: (Notice the difference in background colour contrast)

![screenshot 2018-07-26 11 13 40](https://user-images.githubusercontent.com/1859806/43250047-0f24d16a-90c5-11e8-812c-7b340c45670f.png)

### Environment

* macOS High Sierra
* PyCharm 2018.2
* Material Theme UI v2.6.1

**Comment by LXGaming** [comment]
I've noticed the same thing

**Environment**
- Windows 10
- IDEA 2018.2
- Material Theme UI v2.6.1

**Comment by mallowigi** [comment]
Oops, it’s a new setting called “High Contrast”. You can find it in the features tab or in the action panel .

**Comment by mallowigi** [comment]
No, that's the point of the High Contrast - to provide contrast between the editor and the theme: http://www.material-theme.com/docs/configuration/component-settings/#high-contrast

I don't know which indicator you'd want, since there is already a toggle button in the Action Toolbar. 

I agree with thinking it's a bug, but this will change from next version.
