### ISSUE TITLE
New Atom One Dark colorscheme doesn't highlight parens, brackets

### ISSUE THREAD

**Issue by alexozer** [ChrisRM/material-theme-jetbrains#859]
### Summary

It appears that in the latest Pycharm and material theme, the Atom One Dark colorscheme doesn't highlight parenthesis, brackets, and braces. Previously I believe they were blue.

![example](http://i.imgur.com/P24yrYp.png)

### Environment

```
PyCharm 2018.2 (Professional Edition)
Build #PY-182.3684.100, built on July 24, 2018
Licensed to Alex Ozer
Subscription is active until September 2, 2018
For educational use only.
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-109-generic
Material UI: 2.6.1
```

**Comment by mallowigi** [comment]
I have no recollection of that and from the VCS history, it doesn't look like it. But anyway, first make sure you are not using an edited version of the One Dark Scheme, and second, if you want to change it you can go to Settings > Color Scheme > General > Code > Matched Brace and change the color. The default value should have a background of 383d48 and an effect color of 557ecf.
