### ISSUE TITLE
No file icons in project tree list

### ISSUE THREAD

**Issue by armybean** [ChrisRM/material-theme-jetbrains#86]
I am using PhpStorm 9.0.2 and I just installed your great plugin and I see no file icons. :( Sometimes, when I start the IDE, the icons are there but then disappear. Any chance to fix this?

![image](https://cloud.githubusercontent.com/assets/1634208/10590334/610a217e-76b0-11e5-9961-f53f2e4f6a7c.png)

**Comment by Maqsim** [comment]
@ChrisRM Hey. Any updates? This is really blocking issue.

**Comment by ChrisRM** [comment]
I'm having a hard time reproducing this. You're on OS X, right?

**Comment by Maqsim** [comment]
@ChrisRM Yes, I'm. Mac OS Yosemite, Java 8 update 60 (build 1.8.0_60-b27), WebStorm 10.0.4

**Comment by Maqsim** [comment]
@ChrisRM  Ok, I've found steps how to reproduce it.

1. Start IDE
2. Hide Project tree sidebar
3. Show Project tree sidebar

Here is a Jing demonstrates it http://screencast.com/t/AVDUgL0G

**Comment by armybean** [comment]
I am using OS X El Capitan.

**Comment by ChrisRM** [comment]
Cool, thanks. It doesn't happen here, but I'll try some different approaches

**Comment by brunolanevik** [comment]
I have this problem too and I'm not OS X Yosemite.

**Comment by bu1ka** [comment]
I have the same behavior. I'm using os x 10.9.5

**Comment by Maqsim** [comment]
@ChrisRM Request status :)

**Comment by ChrisRM** [comment]
Should be fixed in the newest version. Open a new issue if it isn't

**Comment by Maqsim** [comment]
Yeah, it's fixed!
