### ISSUE TITLE
Atom One Light : Diff & Merge colors in v2.7.0 unreadable

### ISSUE THREAD

**Issue by IceMan81** [ChrisRM/material-theme-jetbrains#860]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
The diff colors makes codes unreadable for Atom One Light. Screenshot is attached.

2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

![image](https://user-images.githubusercontent.com/1093778/43343695-0409bb60-919c-11e8-86ea-517c5c3a50a2.png)

It should contain:
* OS (Windows, Linux, Mac) : Windows 7
* IntelliJ Product + version (IDEA, RubyMine...) : Latest Intelij 2018.2.1
* Plugin version : 2.7.0.
* Plugin configuration (found in material_theme.xml) : Atom Light
* If needed a list of enabled plugins
* Material Theme Plugin version

**Comment by mallowigi** [comment]
are you sure you have pristine color schemes? The 2.7.0 should have fixed this issue.
