### ISSUE TITLE
wrong color on DataGrip

### ISSUE THREAD

**Issue by Allkoman** [ChrisRM/material-theme-jetbrains#861]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
### Summary
This area show wrong color

![image](https://user-images.githubusercontent.com/9135356/43352985-a68cbbd0-925f-11e8-82a3-ed7f7a189af2.png)

### Steps to reproduce (if needed)

1. First step
Update DateGrip to 2018.2 version on MacOS
2. Second step
Install Material Theme UI 2.7.0 version
3. Third step
Set theme `Oceanic Theme`

### Environment
DataGrip 2018.2
Build #DB-182.3684.106, built on July 25, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
Material Theme Plugin version : 2.7.0

```
#material_theme.xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.7.0" />
    <option name="userId" value="4c3cda4d:164dee1a443:-8000" />
    <option name="allowDataCollection" value="true" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
https://youtrack.jetbrains.com/issue/DBE-6808
