### ISSUE TITLE
Replace in Path throws exception in plugin 

### ISSUE THREAD

**Issue by xplwowi** [ChrisRM/material-theme-jetbrains#866]
### Summary

Replace in Path...->Replace All causes "Wrong parent window" exception in Material Theme UI plugin.

### Expected behavior

Successful global replacement.

### Actual behavior

Nothing happens except the error message.

### Steps to reproduce (if needed)

1. Open project
2. Right click on sources folder and choose "Replace in Path..." or select this option from menu Edit->Find. 
3. Enter from / to strings and press "Replace All".

![image](https://user-images.githubusercontent.com/5732649/43371595-9d8502fe-9395-11e8-8ff3-4d24c39f4faf.png)

![image](https://user-images.githubusercontent.com/5732649/43371438-8125830c-9392-11e8-8b1e-0cb2aad1232a.png)

### Environment

PyCharm 2018.2 (Professional Edition)
Build #PY-182.3684.100, built on July 24, 2018
JRE: 1.8.0_152-release-991-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29-generic

Material Theme UI 2.7.0 (problem existed also in previous versions)

[stacktrace.txt](https://github.com/ChrisRM/material-theme-jetbrains/files/2239289/stacktrace.txt)

**Comment by mallowigi** [comment]
Can you share your material theme settings?

**Comment by xplwowi** [comment]
Zipped settings attached
[options.zip](https://github.com/ChrisRM/material-theme-jetbrains/files/2243480/options.zip)

**Comment by mallowigi** [comment]
Cannot reproduce, sadly

**Comment by xplwowi** [comment]
You are right - problem disappeared on PyCharm installed from scratch.
Thanks for your work!
