### ISSUE TITLE
Use Material Theme UI the title bar of other windows has also changed.

### ISSUE THREAD

**Issue by InternetNetwork** [ChrisRM/material-theme-jetbrains#867]
### Summary

After the Material Theme UI(2.7.0) is used in WebStorm(2018.2), the title bar of other windows also becomes black (Closing the plugin also cannot be cancelled).

<img width="710" alt="foobar black window title bar" src="https://user-images.githubusercontent.com/41902016/43394144-46d29722-942c-11e8-81e6-ce16eb2a85c5.png">

<img width="710" alt="not an activity window" src="https://user-images.githubusercontent.com/41902016/43394698-2eee7d9a-942e-11e8-9f88-f4ab98edfbcb.png">

### Expected behavior

The title bar of other windows should not have a black title bar.

### Environment information：

WebStorm 2018.2
Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0.17134.165
Material Theme UI  2.7.0

material_theme.xml

<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.7.0" />
    <option name="selectedTheme" value="DARKER" />
    <option name="darkTitleBar" value="true" />
    <option name="userId" value="-bba9cf3:164d56e0d09:-8000" />
    <option name="isHighContrast" value="true" />
  </component>
</application>

**Comment by InternetNetwork** [comment]
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.7.0" />
    <option name="selectedTheme" value="DARKER" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="darkTitleBar" value="true" />
    <option name="userId" value="-bba9cf3:164d56e0d09:-8000" />
    <option name="isHighContrast" value="true" />
  </component>
</application>

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/configuration/other-tweaks-settings/#windows-10
