### ISSUE TITLE
Default font too dark?

### ISSUE THREAD

**Issue by Miccighel** [ChrisRM/material-theme-jetbrains#869]
I'm using your theme since a while now, and there is a thing that i cannot understand how to modifiy. In paritcular, the "system font" is a bit too dark for me, is there a way to change it? 

![cattura](https://user-images.githubusercontent.com/6783459/43397320-b74b33d8-9404-11e8-8409-99c6493bee8e.PNG)

**Comment by mallowigi** [comment]
You can turn on the high contrast mode, it should render better

**Comment by Miccighel** [comment]
Have a look here, this is a screenshot of the same window from another JetBrains IDE with 2.6.1 plugin version. I think something is happened, since i did not tampered with the default settings 
![cattura](https://user-images.githubusercontent.com/6783459/43448188-953ab328-94ad-11e8-8904-4de6827d9a24.PNG)

**Comment by mallowigi** [comment]
Yes because the Highlight mode was enabled by mistake in 2.6.1. The default state is not not enabled, meaning that you have to activate it manually

**Comment by Miccighel** [comment]
Ah okay, can you point me about how to do it, since i did not find it?

**Comment by mallowigi** [comment]
It’s ok the settings under the components tab

**Comment by Miccighel** [comment]
Found it, now it looks much better in my opinion. Thanks!
