### ISSUE TITLE
Impossible to understand that file is Untracked in VCS (i.e. git)

### ISSUE THREAD

**Issue by borNfreee** [ChrisRM/material-theme-jetbrains#87]
This is how Untracked file looks like in Darcula theme - it's red:

![bug](https://api.monosnap.com/rpc/file/download?id=BNPLbAd2HB9sVM2n2FOy4pfxav5FQ8)

This is how Untracked file looks like in Material Default Theme (README2.md is Untracked, README.md is already exist in git):

![](https://api.monosnap.com/rpc/file/download?id=D3ixSRIWPlHpNfvW9wWBcDTfyipm8I)

Is it possible to change the color of untracked / added but not commited files?
Thank you

**Comment by jchlu** [comment]
You can control this colour yourself, in a copy of the Default theme:
![2015-10-20_10-24-57](https://cloud.githubusercontent.com/assets/496597/10603278/14528cc6-7715-11e5-8927-351f440d08d6.png)

**Comment by borNfreee** [comment]
Thanks @jchlu for the info, didn't know it. But I suggest to make this change in the plugin

**Comment by ChrisRM** [comment]
@borNfreee Agree. I'll send out an update soon.
