### ISSUE TITLE
Default asterisk symbol shown instead pencil Material Them icon when file was edited

### ISSUE THREAD

**Issue by vgsystems** [ChrisRM/material-theme-jetbrains#870]
### Summary
After upgrade to PhpStorm 2018.2, the pencil icon on tab bar when the file was updated don't appear and default asterisk sign it's shown. 

![asterisk](https://user-images.githubusercontent.com/7352160/43418894-a8de2cac-943f-11e8-9975-20b165362475.png)

![icons_enabled](https://user-images.githubusercontent.com/7352160/43418925-c0915374-943f-11e8-9d53-0959e53229d9.png)

### Expected behavior
The pencil should be shown when the file was edited and not saved.

### Actual behavior
Default asterisk symbol appears when the file was edited. 

### Steps to reproduce
1) Upgrade to 2018.2
2) Import settings from 2018.1
3) All it's fine excepts this icon

### Environment

PhpStorm 2018.2
Build #PS-182.3684.42, built on July 26, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

### Material Theme Settings for 2018.2

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.7.0" />
    <option name="highlightColor" value="cb0a00" />
    <option name="highlightColorEnabled" value="true" />
    <option name="highlightThickness" value="3" />
    <option name="isContrastMode" value="true" />
    <option name="accentColor" value="80cbc4" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="isDecoratedFolders" value="false" />
    <option name="settingsSelectedTab" value="3" />
    <option name="userId" value="-6f8da1e6:164d1551abb:-8000" />
    <option name="allowDataCollection" value="false" />
  </component>
</application>
```

### Material Theme Settings for 2018.1
```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.4.2-2018.1" />
    <option name="highlightColor" value="cb0a00" />
    <option name="highlightColorEnabled" value="true" />
    <option name="highlightThickness" value="3" />
    <option name="accentColor" value="80cbc4" />
    <option name="compactSidebar" value="true" />
    <option name="isCompactStatusBar" value="true" />
    <option name="isCompactTables" value="true" />
    <option name="darkTitleBar" value="true" />
    <option name="compactDropdowns" value="true" />
    <option name="isDecoratedFolders" value="false" />
    <option name="settingsSelectedTab" value="2" />
    <option name="fileStatusColorsEnabled" value="true" />
    <option name="userId" value="-6f8da1e6:164d1551abb:-8000" />
    <option name="allowDataCollection" value="false" />
  </component>
</application>
```

Thanks!

**Comment by mallowigi** [comment]
They probably changed the icons... will take a look

**Comment by vgsystems** [comment]
Thanks ;)

**Comment by mallowigi** [comment]
I can't reproduce. Maybe it's another plugin? Can you post here the list of plugins?

**Comment by vgsystems** [comment]
I had the same plugins before and after update, I didn't add anything new. This is the list:

#### Disabled

![disabled](https://user-images.githubusercontent.com/7352160/43574053-799363f8-9643-11e8-8287-4d4bf5f3fbb4.png)

#### Custom

![custom](https://user-images.githubusercontent.com/7352160/43574095-955ffcae-9643-11e8-849a-f7319a5e8ab2.png)

#### Enabled

![enabled_1](https://user-images.githubusercontent.com/7352160/43574202-dd3c151c-9643-11e8-9a11-e0db0466df10.png)
![enabled_2](https://user-images.githubusercontent.com/7352160/43574205-ddfca8ea-9643-11e8-8242-daff66a274d6.png)

**Comment by mallowigi** [comment]
Ok, I couldn't reproduce... 

Perhaps you can export your settings?

**Comment by vgsystems** [comment]
Do you want the .jar file?

**Comment by mallowigi** [comment]
https://join.slack.com/t/material-theme-ui/shared_invite/enQtMzgzNTUxMjQ2MTQ1LWU3Y2ZlYTBlNDEyZmU5YTMzNjAxZjc0NmVkMTk1NzdmNDI1NDAwMzI4NWYxZjVmYzUyYTgwZWEzNjE2YTg2NTA

**Comment by mallowigi** [comment]
I FOUND IT!!!! What a nasty bug from Jetbrains!!!!

Apparently if you have unchecked "hide tabs if there is no space" from the Editor Tabs settings, at start Jetbrains is replacing the default Asterisk icon (the one I replaced with a pencil) with a * character... and it stay like this until next restart, regardless of the setting being checked or not!

So to fix this, you will have to leave the "Hide tabs if there is no space" on... or wait till JB fix this.

**Comment by mallowigi** [comment]
https://youtrack.jetbrains.com/issue/IDEA-196772

**Comment by vgsystems** [comment]
Hi! I can confirm that if I enable the option "hide tabs if there is no space" pencil appeared again!

Thank you!!
