### ISSUE TITLE
PyCharm hangs when opening settings

### ISSUE THREAD

**Issue by bsavio** [ChrisRM/material-theme-jetbrains#872]
### Summary
PyCharm consistently hangs when I go to open settings. Once I remove the plugin it works again. Note, it also occurred after upgrading to 2.7.

PY-182.3684.100, JRE 1.8.0_152-release-1248-b8x64 JetBrains s.r.o, OS Windows 7(amd64) v6.1 Service Pack 1
...

### Expected behavior
Settings window opens
...

### Actual behavior
Application hangs and doesn't recover
...

### Steps to reproduce (if needed)

1. Go to File -> Settings
2. PyCharm freezes

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* Plugin version 
* Plugin configuration (found in material_theme.xml)
* If needed a list of enabled plugins
* Material Theme Plugin version

If possible please also give out your Material Theme/Material Custom Theme configuration file.

Note that not providing any of the required info will result of your issue being closed.

**Comment by mallowigi** [comment]
Can you paste here your material theme settings

**Comment by bsavio** [comment]
Are you talking about this?

`<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.7.0" />
    <option name="highlightColor" value="80cbc4" />
    <option name="accentColor" value="80cbc4" />
    <option name="userId" value="1453d0bc:1645b4c9793:-7fff" />
    <option name="allowDataCollection" value="true" />
  </component>
</application>`

**Comment by mallowigi** [comment]
Hum... no info here... Can you provide the logs then ?

**Comment by bsavio** [comment]
[idea.log](https://github.com/ChrisRM/material-theme-jetbrains/files/2250158/idea.log)

**Comment by mallowigi** [comment]
I am not able to reproduce. Please connect to the slack channel so we can pinpoint the problem

**Comment by rhlahuja** [comment]
I also encounter a similar issue after upgrading to 2018.2 (no problems on 2018.1.4). PyCharm doesn't hang, but the Preferences menu just doesn't open/display at all via `⌘,`  or `PyCharm > Preferences`. Disabling the theme via `Material Components > Toggle Material Theme` or rolling back to 2018.1 resolves the issue.

[Here](https://github.com/ChrisRM/material-theme-jetbrains/files/2259873/idea.log) is my idea.log - I believe the relevant part is the `ERROR - e.actions.ShowSettingsUtilImpl - null `.



My `About PyCharm`:
PyCharm 2018.2 (Professional Edition)
Build #PY-182.3684.100, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6


Let me know if I should provide more info or reach out on the Slack channel, and thanks for your work on this great theme!

**Comment by bsavio** [comment]
Unfortunately, my company blocks slack.  If there's anything else we can do or we can try please let me know.  I do love the extension by the way and I definitely want to continue to use it.

**Comment by bsavio** [comment]
Quick update.  I  uninstalled pycharm and re-installed.  I installed the latest Material Theme plugin and I have not had the problem for the past few days.  I'll report back if it happens again.  Thanks for your help and again I love the theme.  You guys are doing great work
