### ISSUE TITLE
Branch overview gone after install

### ISSUE THREAD

**Issue by NGuldager** [ChrisRM/material-theme-jetbrains#873]
Before installation I had an overview of my current branch, and a branch selector down next to event log. Now it's gone.

![image](https://user-images.githubusercontent.com/2247698/43518449-694ad15a-958c-11e8-823e-4b06a46ac694.png)

**Comment by mallowigi** [comment]
what do you mean? can you provide a screenshot of it without the plugin?

**Comment by mallowigi** [comment]
Ah i see what you meant: In the menu select View > Status Bar
