### ISSUE TITLE
MaterialUI Theme makes Rider super-janky

### ISSUE THREAD

**Issue by fluffynuts** [ChrisRM/material-theme-jetbrains#874]
### Summary
I have MaterialUI installed on all of my JetBrains IDEs (that I use):
- DataGrip
- WebStorm
- Rider

I noticed that Rider was super janky -- there were times when moving my mouse over the IDE would cause the mouse movement to stutter and I could see CPU usage spikes, so, on a hunch, I disabled MaterialUI in Rider and the problem is now gone.
I see it especially when mousing over unit tests in the test explorer -- see steps to repro

I don't see this happening in the file browser in WebStorm or in the server browser in DataGrip, where the same IDE behavior ("peeking" at partially-obscured tree items) exists.

### Expected behavior
Theme plugin should not affect IDE performance

### Actual behavior
Theme plugin appears to make IDE janky, spiking CPU usage as the mouse moves over certain UI elements.

### Steps to reproduce (if needed)

1. Install and activate MaterialUI in Rider
2. Open a .net project and run all tests (you're welcome to use one of my projects: https://github.com/fluffynuts/NExpect which has > 500 tests, with some long names and tree items in there, so it should show the issue)
3. Expand all tests to make sure you have long lines of text
4. Resize the test explorer pane so that it's too narrow to display all of the text of a test tree node (this is a common scenario as the test runner adds more text past the test name
5. Move the mouse over test tree nodes. It appears that as the IDE tries to do a "peek" on items which are too long to see fully in the test window, the IDE janks quite considerably.

I'm seeing this on other panes too, so it's not just in the test explorer -- this is just a nice place to repro the issue. It got to a point where I'm swearing at Rider for being slow and crap, but meanwhile, it's not Rider's fault )':

### Environment

JetBrains Rider 2018.1.3
Build #RD-181.4952.311, built on June 27, 2018
Licensed to Clyral / Davyd McColl
You have a perpetual fallback license for this version
Subscription is active until July 22, 2019
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material UI version: 2.4.2-2018.1 (I've disabled the plugin for now, but this is copied out of the plugin page)

I'm not sure where to find my MaterialUI config file -- if it would be helpful, please let me know where to find it and I'll attach to this issue.

**Comment by mallowigi** [comment]
Sorry, I don't have the time to work on such causes. As a non user of Rider, debugging such cases would be too hard to reproduce, and I don't have a lot of time anyways.

I will try to reproduce using your steps and if something comes out, I'll let you know, but otherwise, sorry but you'll have to work without it (or find a solution yourself).

**Comment by fluffynuts** [comment]
I understand and I appreciate your efforts (:
