### ISSUE TITLE
ctrl + f (find)

### ISSUE THREAD

**Issue by Abdelraman** [ChrisRM/material-theme-jetbrains#878]
first of all i would like to thank you for this awesome plugin, when I start typing in find bar ctrl + f some weird question mark inside a box appears when typing Arabic letters

**Comment by mallowigi** [comment]
Yep it’s a recurrent question, it’s because the font in the text fields have been changed to Fira Code which is Latin only. While I don’t know why you would need to enter Arabic or Chinese characters in the find window since code is usually written in English, if you need to use another font you will have to disable the “material fonts” setting

**Comment by mallowigi** [comment]
Is it possible that it's because you don't have Roboto font installed?

Can you install this font and restart?
https://fonts.google.com/specimen/Roboto?selection.family=Roboto

**Comment by Abdelraman** [comment]
I have to use some Arabic in localization files and search for, it was working fine until I used override default fonts in appearance and behavior. Any suggestion BTW i also installed Roboto but nothing happened

**Comment by mallowigi** [comment]
So wait, you have "override default font" enabled?

**Comment by Abdelraman** [comment]
Yes, is there is a problem ? :(

**Comment by mallowigi** [comment]
Indeed, because the font you selected might not be able to display arabic characters. Try a font like Roboto or Lucida Sans

**Comment by Abdelraman** [comment]
The same font was working before installing material theme the font name is Segoe ui

**Comment by mallowigi** [comment]
I see I’ll try to reproduce

**Comment by mallowigi** [comment]
Can you try in the 2.7.1 and see if that's fixed?

**Comment by Abdelraman** [comment]
sorry but nothing changed

**Comment by mallowigi** [comment]
Okay I've changed it so the font used will be the Global font set in Settings > Editor > Font. There you can select a font which displays Arabic characters, like Monospaced.

Note that at the moment this setting is hardcoded at start, meaning that changing the font will be applied at next restart only.

**Comment by DukeAnn** [comment]
### The following settings can solve the problem.

![snipaste_2018-08-21_14-39-06](https://user-images.githubusercontent.com/15902491/44384909-61b4b680-a550-11e8-8db2-84e45d3b340b.png)

![snipaste_2018-08-21_14-39-35](https://user-images.githubusercontent.com/15902491/44384926-75601d00-a550-11e8-946f-b1cf82c3968f.png)

![snipaste_2018-08-21_14-43-52](https://user-images.githubusercontent.com/15902491/44384979-a6d8e880-a550-11e8-8bb0-14e6c12f955d.png)

**Comment by Jecvay** [comment]
thanks for the referenced
