### ISSUE TITLE
CMD+SHIFT+F Lags and Loses Focus

### ISSUE THREAD

**Issue by chukkwagon** [ChrisRM/material-theme-jetbrains#879]
### Summary
Trying to perform a project search with cmd+shift+f and the search box loads quite slowly and when it does load I cannot type in the search input. I have to escape and relaunch the search (often resulting in the same behavior). I disabled material theme and search behaved as I expected.

### Expected behavior
system search should load and allow me to enter a search query.

### Actual behavior
system search loads slowly and I cannot enter text into the input.

You can also add Screenshots for a better understanding.

### Environment
IntelliJ IDEA 2018.2 (Ultimate Edition)
Build #IU-182.3684.101, built on July 24, 2018
Licensed to ...
Subscription is active until January 7, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

If possible please also give out your Material Theme/Material Custom Theme configuration file.

Note that not providing any of the required info will result of your issue being closed.

**Comment by Stex** [comment]
I am experiencing the same problem and therefore didn't want to open a new issue - I am not sure wy this one was closed though.

For me, "Find in path", "Find ClassName" and "Find Filename" are behaving as described below, "Search Everywhere" works completely fine.

**Behaviour**: 

1. I open one of the above mentioned dialogs
2. I type something, seemingly the dialog is not in focus
3. I close the dialog by clicking into the main window (ESC is not working)
4. The editor is blocked for a few seconds
5. The text I wanted to write in the dialog appears in the editor

As a screencast:

![delayed_input](https://user-images.githubusercontent.com/27221/43782103-ced822a8-9a5e-11e8-8184-20b5e649a1c6.gif)

Please let me know whether I should open a new issue or this one could be re-opened.

**Comment by chukkwagon** [comment]
@Stex I closed it because I couldn't find a consistent way to reproduce it. Appreciate the screen capture as it illustrates the behavior i was seeing, but I was seeing it in all search contexts. Maybe open a new issue so that the maintainers see it?

**Comment by Stex** [comment]
@chukkwagon Will do. For me, it happens in all search dialogs except for the "Search Everywhere", maybe because it's a different kind of dialog

**Comment by mallowigi** [comment]
https://youtrack.jetbrains.com/issue/IDEA-187808

Short fix: Open the registry and disable action.aware.typeahead.

Also this occurs only when the Material Theme option is disabled, don't know why atm
