### ISSUE TITLE
Show Help Contents" Icon off-centre

### ISSUE THREAD

**Issue by cameronoxley** [ChrisRM/material-theme-jetbrains#88]
Hey @ChrisRM,  -Thanks again for taking the time for this project.

Just to add a small issue to your seemingly ever growing list:
I've noticed the "Show Help Contents" Icon is off-centre in the preferences menu.

![screen shot 2015-10-20 at 11 13 00](https://cloud.githubusercontent.com/assets/1674847/10602953/bfb02f82-771b-11e5-8480-6cc62f49a4f2.png)

Looking forward to Java support!

**Comment by ChrisRM** [comment]
The icon itself is centered, and there's no way to edit those buttons without too much hacking. I think we're gonna have to live with that.
