### ISSUE TITLE
No way to disable analytics (mixpanel)

### ISSUE THREAD

**Issue by yusijs** [ChrisRM/material-theme-jetbrains#885]
### Summary
After upgrading to the latest material theme (and webstorm edition), I noticed calls going to mixpanel.com. After searching a bit, I found that this was implemented for analytics. 

I'm generally fine with this, but our corp. proxy is giving me grief every time I open webstorm. When I attempted to find a way to disable this, I couldn't find anywhere to change this.

### Expected behavior
There should be an easy to reach way to turn off analytics / tracking

### Actual behavior
Unable to find a way to turn off analytics / tracking.

### Environment

WebStorm 2018.2
Build #WS-182.3684.70, built on July 20, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
Material Theme Plugin version: 2.7.2

**Comment by mallowigi** [comment]
You can set the 
    <option name="allowDataCollection" value="true" /> to false in material_theme.xml

**Comment by yusijs** [comment]
Thanks.

I do feel this should be made a bit more available through the UI though.
