### ISSUE TITLE
Font Information in Readme

### ISSUE THREAD

**Issue by bcalik** [ChrisRM/material-theme-jetbrains#89]
Hello,

Could you please provide the font family, size, line height, and OS used for screenshots in readme.md?
Is that El Capitan on retina screen? My fonts are not that smooth. Looks really ugly for me.

Thanks.

![screen shot 2015-10-20 at 16 09 24](https://cloud.githubusercontent.com/assets/9222368/10607873/278a60f4-7745-11e5-8475-4cf3cfd0ed44.png)

**Comment by ChrisRM** [comment]
I'm using [Fira Code](https://github.com/tonsky/FiraCode). Line height is set to 1.6 and font size is 15. I'm running on Yosemite.
