### ISSUE TITLE
One dark theme has very difficult to read text

### ISSUE THREAD

**Issue by arminsumo** [ChrisRM/material-theme-jetbrains#891]
### Summary
One Dark theme very hard to read text. Here is an example: 
<img width="169" alt="screen shot 2018-08-14 at 10 45 43 am" src="https://user-images.githubusercontent.com/31675549/44108437-4006fca6-9faf-11e8-9d98-6d5c16e6db91.png">

The blue background with light gray text is difficult to read. This is happening using the scala plugin, when your cursor is on a function in a class.

### Environment
IntelliJ IDEA 2018.2 (Community Edition)
Build #IC-182.3684.101, built on July 24, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

**Comment by mallowigi** [comment]
did you restart after applying the one dark theme? I don't see any problems in my end.
