### ISSUE TITLE
Code completion window background color?

### ISSUE THREAD

**Issue by mxs42** [ChrisRM/material-theme-jetbrains#892]
Sorry if I'm asking known question, I tried to search but had no luck.
How can I change code completion color? 

![webstorm64_2018-08-14_21-16-45](https://user-images.githubusercontent.com/34000717/44110152-a700ddde-a007-11e8-9477-c181dbc93f27.png)

I tried to look for this color in settings, Popups and Hints > Tooltip has the same color as this window (`#292D3E`) but changing it doesn't affect it.

Currently this popup looks strange, it should look like navigation tree IMO
![webstorm64_2018-08-14_21-20-43](https://user-images.githubusercontent.com/34000717/44110248-e8efa798-a007-11e8-88c1-1ee4b7e38479.png)

I use Material Deep Ocean theme.

**Comment by mallowigi** [comment]
Good idea. It is currently using the Selection Color but I'll check if there is the possibility to add opacity.

**Comment by mallowigi** [comment]
I've changed it in 2.8.2
