### ISSUE TITLE
UI Text becomes random characters/garbage on Windows

### ISSUE THREAD

**Issue by MeirBon** [ChrisRM/material-theme-jetbrains#895]
### Summary

Whenever I enable the Material Theme plugin all text of the IDEs UI becomes garbage (see screenshot). Note that I added my environment information for CLion, but it was the same on every Jetbrains IDE I tried (PyCharm, PhpStorm and Idea). I already deleted my configuration files and set CLion up from scratch, but that didn't change anything.

### Expected behavior

Readable text in UI.

### Actual behavior

Text becomes random characters, garbage.

### Environment

CLion 2018.2.1
Build #CL-182.3911.40, built on August 7, 2018
Licensed to Mèir Noordermeer
Subscription is active until January 4, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### Screenshot
![capture](https://user-images.githubusercontent.com/23170672/44159286-3b59cb80-a0b7-11e8-9d83-113e68717fc5.PNG)

**Comment by mallowigi** [comment]
Feature Settings
Q: I’ve set “Material Fonts” but now my texts are all scrambled!
A: This is a rare bug that occurs and honestly I don’t know why it happens. It could be because the JDK caches fonts or because there are conflicts between Roboto fonts, or that you have a bad version of Roboto. Try to reinstall the Roboto font and restart the computer. If it still doesn’t work, just disable the option or select another font in the settings.

**Comment by MeirBon** [comment]
Ah okay, I was looking through issues but couldn’t find it.. Turns out I was looking in the wrong place, my apologies. Thanks a lot for the answer.

**Comment by imlouisrussell** [comment]
@mallowigi Uninstalling Roboto and selecting another font does not help.

**Comment by mabdelfattah** [comment]
I have the same problem even with material fonts disabled!

**Comment by jimfilippou** [comment]
I also have this problem, and it's weird

**Comment by moequraishi** [comment]
> Feature Settings
> Q: I’ve set “Material Fonts” but now my texts are all scrambled!
> A: This is a rare bug that occurs and honestly I don’t know why it happens. It could be because the JDK caches fonts or because there are conflicts between Roboto fonts, or that you have a bad version of Roboto. Try to reinstall the Roboto font and restart the computer. If it still doesn’t work, just disable the option or select another font in the settings.

How do you want us to simply "Disable the option or select another font in the settings" when we can't read anything to navigate in the system menus? Not everyone works for Jetbrains to know where things are without reading them. Just an FYI.

**Comment by mabdelfattah** [comment]
@Xalaxis Yup, mine is Dell, and I've "SupportAssist" installed :) ! But I can already see that Roboto is fine in Windows Fonts app, and still, the theme is not working with Roboto

![image](https://user-images.githubusercontent.com/721987/46950189-fb9e6880-d094-11e8-855d-e4df96bbf037.png)

**Comment by jimfilippou** [comment]
@Xalaxis exactly! so for dell users just reinstall roboto

**Comment by Xalaxis** [comment]
@mabdelfattah Have you used the bottom of that page to make sure that all the fonts located in the SupportAssist directories have been uninstalled?

**Comment by mabdelfattah** [comment]
@Xalaxis OK, that was my mistake, I uninstalled Dell's Roboto copy manually and re-installed it, and it is working fine now.
