### ISSUE TITLE
Updates too frequent

### ISSUE THREAD

**Issue by mswilson4040** [ChrisRM/material-theme-jetbrains#897]
Updates are way too frequent. This is starting to feel like notepad++ and iTunes. Everytime you open WebStorm there's an update. With the new wizard that pops up, it's even a lesser user experience since we have to step through that thing too.

**Comment by mallowigi** [comment]
So? It’s not an issue per se.

If you think updates are too frequent, simply don’t update and wait until there is a new milestone to update.

Or you can fork the project and use your fork instead. There are many possibilities.

Thanks
