### ISSUE TITLE
Uppercasing Run/Debug combo makes it unreadable

### ISSUE THREAD

**Issue by MikeSuiter** [ChrisRM/material-theme-jetbrains#898]
### Summary
![image](https://user-images.githubusercontent.com/5289509/44274092-e1681b80-a206-11e8-925b-d31524e28a6e.png)

...

### Expected behavior
Don't uppercase so text isn't long and unreadable
...

### Environment

IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
It's not because it's uppercase that it's unreadable, but rather because of the name of the run configuration. Just change the name, or disable the uppercase buttons in the settings.

**Comment by MikeSuiter** [comment]
@mallowigi Even short with camelCase names it looks like crap. This is not a button (which should be uppercase) but a combobox/select/dropdown field which I have never seen one with uppercase value for the selected item in Material Design. 

https://material.io/design/components/menus.html#exposed-dropdown-menu

![image](https://user-images.githubusercontent.com/5289509/44283241-5e08f300-a223-11e8-860d-c5a594603a8a.png)

Anyway the uppercase for this field just happened with the last update (IntelliJ updated at the same time also).

**Comment by mallowigi** [comment]
This is something IntelliJ have been doing for a while now (I think it appeared in 2018.1), the "Run configurations" is not a dropdown anymore but a button which displays a list upon clicking (we can call this a dropdown button), and therefore is gaining the same style as other buttons.

Like I said, it's usually pretty readable and pretty as well: http://prntscr.com/kjwmhx , but indeed for long names it appears a bit outstretched (and for paths it's even worse).

A simple fix would be to change the name of the configuration, something like "Publish Dockerfile" or "Runtime dockerfile"

http://prntscr.com/kjwop8
