### ISSUE TITLE
Restore accent color to default

### ISSUE THREAD

**Issue by pwsandoval** [ChrisRM/material-theme-jetbrains#899]
It's very simple, after installing the theme and selecting the Darker Theme, I selected the accent color Tomato (like red), but now I want to return to the accent color that comes by default (as in the capture of the official page).

I cann't find an option to do this.

PhpStorm 2018.2.1
Build #PS-182.3911.43, built on August 8, 2018
Subscription is active until April 23, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by mallowigi** [comment]
If you have the “override accent color” option selected, then you can switch to the darker theme and it will replace the accent color with the darker one.

**Comment by mallowigi** [comment]
The default is now bundled into the theme, it’s not 80cbc4 anymore.

**Comment by mallowigi** [comment]
You can also select the “turquoise accent color” action from the accents menu/command palette.
