### ISSUE TITLE
Cursor should be same height as font, not line height.

### ISSUE THREAD

**Issue by kodi** [ChrisRM/material-theme-jetbrains#9]
I changed line height to 2.4, just to illustrate.

<img width="359" alt="screen shot 2015-10-03 at 9 50 26 pm" src="https://cloud.githubusercontent.com/assets/51153/10264844/d483e0ee-6a18-11e5-9f28-2a1bcec6bddf.png">

**Comment by B-iggy** [comment]
also teal equal signs! ;)
and yes, I can confirm this issue.

**Comment by ChrisRM** [comment]
I guess that's a jetbrains bug and not specific to the plugin?

**Comment by ChrisRM** [comment]
About the teal equal sign, isn't that how it should be?

**Sublime Material Theme**

<img width="381" alt="screen shot 2015-10-03 at 22 14 17" src="https://cloud.githubusercontent.com/assets/309292/10264927/233706d2-6a1c-11e5-840d-73e1d9080e82.png">
