### ISSUE TITLE
Hard to determine current line when debugging in PHPStorm

### ISSUE THREAD

**Issue by jjeaton** [ChrisRM/material-theme-jetbrains#90]
This is what it looks like when stepping through with the debugging in PHPStorm 9.0.2.

![2015-10-20 at 9 45 am](https://cloud.githubusercontent.com/assets/835509/10609093/f93e35f2-770f-11e5-84a5-e82bf2617765.png)

It's difficult to tell which line is the current line, and I believe in the default PHPStorm theme there's a caret in the gutter that signifies the line. I think adding the caret back would be helpful to better tell which line is currently being debugged.

**Comment by selcukbulca** [comment]
:+1: Same issue for Android Studio.

**Comment by jjeaton** [comment]
I'm able to improve this by changing the color of the Execution Point to a more striking color, but I can't figure out how to add back the caret in the gutter. The default execution point background color is very similar to the default background color which makes it (at least for me, with partial colorblindness) difficult to tell which line is currently executing.

![2015-11-19 at 8 37 am](https://cloud.githubusercontent.com/assets/835509/11272172/eaba1f78-8e98-11e5-86a2-fa51646070de.png)

**Comment by mallowigi** [comment]
Fixed in the new release
