### ISSUE TITLE
Failed to initialize - FIXED

### ISSUE THREAD

**Issue by DaCush** [ChrisRM/material-theme-jetbrains#900]
### Summary
I had the theme installed however I did a fresh installation of Windows 10 today to clear my SSD.  I install the theme again and this time after I restart I get an error saying that it failed to initialize and and to restart Pycharm.  I was originally using version 2.7.2 and this time used 2.8.1 however I tried going back to 2.7.2 and it resulted in the same error. 
One thing to note: I spent the first 3 hours after reinstalling Windows uninstalling and reinstalling Pycharm and Java because it kept saying that my environment variables weren't pointing to jdk.dll and no matter how many times I tried fixing that by adding JAVA_HOME and the directory and taking out java directory in the path variable it wouldn't fix.  Then I decided to try restarting my computer and Pycharm worked with no issues.  This is a screenshot of my environment variables in case that matters as well as the failed to initialize error I get after restarting Pycharm.
Screenshot: https://ibb.co/g8vR3K
![error](https://user-images.githubusercontent.com/10594068/44313001-cc81b880-a3bd-11e8-90f7-2286673c2d5b.png)

### Environment
PyCharm 2018.2.1 (Community Edition)
Build #PC-182.3911.33, built on August 5, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrainis s.r.o
Only Default Plugins
Material Theme Plugin 2.8.1 (also tried 2.7.2)
There is no Material Theme xml file although I'm sure that's because it wasn't able to initialize

I'm really hoping this is an easy fix because I don't think I can go without your theme xD
**EDIT: I was able to get it working by actually browsing the repositories instead of installing by disk.  SO HAPPY!  haha.  I'm not sure why the java file installing by disk wouldn't work this time but I'm happy to get it working bia repository.**

**Comment by mallowigi** [comment]
???
