### ISSUE TITLE
How can I change scheme of reserved words?

### ISSUE THREAD

**Issue by Luberen** [ChrisRM/material-theme-jetbrains#905]
![italic](https://user-images.githubusercontent.com/26616056/44345646-dcd58880-a4ce-11e8-8bbb-549acaaeca32.PNG)

I want to remove italic scheme of reserved words but I can't find related option.
I've changed 'Keyword' scheme in **Settings | Editor | Color Scheme | Language Defaults** but nothing has changed in java files.

**Comment by mallowigi** [comment]
It should be in Java > Keywords
