### ISSUE TITLE
Proper Uninstall/Reset for Android Studio

### ISSUE THREAD

**Issue by donnfelker** [ChrisRM/material-theme-jetbrains#906]
### Summary
I'm looking for some details on how to properly uninstall and reset Android Studio back to its original state. 

### Expected behavior
When I uninstall the theme, the settings should be removed/etc (or a proper removal doc should explain next steps).

### Actual behavior
IDE colors are changed in various locations and I cannot reset them. I've gone as far as to delete Android Studio and remove it from the file system. When I install a new copy, it is picking up color and theme information from some folder that I'm unaware of. I need to know where this folder is so that I can completely uninstall this theme.  
...

### Steps to reproduce (if needed)

1. Install Android Studio
2. Install this theme
3. Set it to Oceanic blue or something else, change the theme colors a few times. 
4. Uninstall theme
5. Android Studio is left in an inconsistent state for themes/colors. 
 

### Environment
Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

If possible please also give out your Material Theme/Material Custom Theme configuration file. 
(NONE: it was deleted and removed AFAIK).

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/faq-troubleshooting/

**Comment by mallowigi** [comment]
Just read the section http://www.material-theme.com/docs/faq-troubleshooting/#file-status-colors

**Comment by donnfelker** [comment]
Unfortunately that didn't work.

**Comment by mallowigi** [comment]
Can you post a screenshot of what you mean?

**Comment by k3n** [comment]
Yup, doesn't work. File status colors are not working at all post-uninstall, even though the colors are all defaulted. On top of that, it'd be nice to have a warning letting us know that this plugin will irrevocably change our file status color settings **before** installation, with steps on how to backup/restore them.

After uninstalling this plugin, I'm left with broken file status colors, and even if/when I get them working again, I'll still have to go back in and setup my custom colors. Thanks a lot.

**Comment by mallowigi** [comment]
The documentation explains how to revert to the old version.

--
Elior

**Comment by perlun** [comment]
For reference, what I had to do to properly reset my IntelliJ was to export the settings, then wipe the settings folder, then do a clean import. The suggestions given in the documentation was not enough to reset things like file icons in the Project explorer.

But, export + import worked well.
