### ISSUE TITLE
Material UI file-icons are not showing 

### ISSUE THREAD

**Issue by Niko9911** [ChrisRM/material-theme-jetbrains#907]
### Summary
Material UI file-icons are not showing. Phpstorm uses default icons for files instead of Material UI icons.
...

### Expected behavior
Load Material UI icon for the files.
...

### Actual behavior
Load default icons for the files.
...

### Workaround
By going to Settings → Appearance & Behavior → Material Theme → Icons
Unchecking box "Enable Material icon" and pressing apply (without restart) and then repeating by checking same box and pressing apply and again skipping restart, the icons start showing again until next IDE restart.

### Environment
Info:
* OS `Ubuntu 18.04.1 LTS` `4.15.0-32-generic #35-Ubuntu SMP x86_64 GNU/Linux`
* IDE `PhpStorm 2018.2.1 Build #PS-182.3911.43, built on August 8, 2018`
* JRE: `1.8.0_152-release-1248-b8 amd64`
* Plugin version: `2.8.2`
* Plugin configuration (couldn't find)

**Comment by mallowigi** [comment]
I am not able to reproduce on Windows, can you provide screenshots?

**Comment by mallowigi** [comment]
I need screenshots to make sure that's a wanted behavior and not a bug.

**Comment by loxK** [comment]
I can confirm. Also if I disable "hide file icon" file icons are showing. Indeed. But the icon of that option always made me think it was related to "hidden" files icons.

![Peek 18-09-2020 12-40](https://user-images.githubusercontent.com/136687/93545633-a4a21c00-f9ac-11ea-97cb-330676b1ccb3.gif)
