### ISSUE TITLE
can't install plugin from disk

### ISSUE THREAD

**Issue by qianfangyuan** [ChrisRM/material-theme-jetbrains#908]
Mac 10.12.4
Golang:2017.3.3
material-theme-jetbrains:2.8.1

I downloaded the .zip file,And Settings > plugins > install plugin from disk
but it show "failed to load plugin descriptor from file material-theme-jetbrains-2.8.1.zip"

**Comment by mallowigi** [comment]
2.8.1 is not compatible with 2017.3
