### ISSUE TITLE
Is it impossible to remove space in file tabs?

### ISSUE THREAD

**Issue by Luberen** [ChrisRM/material-theme-jetbrains#909]
![file_tab](https://user-images.githubusercontent.com/26616056/44473237-d1b75f80-a66a-11e8-8075-0d368575a2d6.PNG)

If I choose 'Uppercase bold tabs' option, unintended space is made in file's name.
Is it impossible to remove this?

**Comment by mallowigi** [comment]
Yes as it is trying to display a “friendly name” for the file .
