### ISSUE TITLE
Uppercase in settings buttons label and run/debug selectbox

### ISSUE THREAD

**Issue by ndywicki** [ChrisRM/material-theme-jetbrains#910]
### Summary

WIth a fresh IntelliJ IDEA Ultimate 2018.2.2 buttons label in Settings are in uppercase (Ok, Apply, Install Plugin...) and also in selectbox of run / debug tools. See screenshots when Material UI theme is activated.

### Expected behavior

Labels should keep the camelCase format

### Actual behavior

Buttons labels and selectbox are in uppercase 

### Steps to reproduce

1. Install IntelliJ IDEA 218.2
2. Install Material UI 2.8.2
3. Restart IntelliJ

### Environment

IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

- Material Plugin 2.8.2
- Rainbow bracket 5.9.1
- Sonar lint 3.5.1.2759
- Lombok Plugin Version: 0.19-LATEST-EAP-SNAPSHOT

Same issue with all Material themes

### Screenshots:

Dracula default theme
![material-ui-disabled](https://user-images.githubusercontent.com/1721344/44493658-13470b00-a669-11e8-8775-2c3c8cd390a8.JPG)

With Material UI enabled
![material-ui-upper2](https://user-images.githubusercontent.com/1721344/44493659-13dfa180-a669-11e8-9f6f-f3475040c9fb.jpg)
![material-ui-upper](https://user-images.githubusercontent.com/1721344/44493660-13dfa180-a669-11e8-87ec-7b8e8ece0ee0.jpg)

Thanks !

**Comment by mallowigi** [comment]
Tis not a bug...

**Comment by ndywicki** [comment]
Hi Elior,

ok finally I found the option for disable upper case in the runner selectbox...

For me and other :
**Settings > Componnents tab >Uncheck Uppercased buttons**

Thanks

**Comment by mallowigi** [comment]
Just FYI, there is a help button in the settings that open a website with all options and features explained, as well as FAQs and troubleshooting issues.
