### ISSUE TITLE
Better support/clarity for syncing theme settings through Jetbrains Account Sync

### ISSUE THREAD

**Issue by nivekastoreth** [ChrisRM/material-theme-jetbrains#911]
### Summary

When configuring IntelliJ to pull settings from a Jetbrains Account, the plugin is correctly installed (when configured to do so) but then the Material Wizard prompts the user to perform the first time configuration settings.  This leaves the user in a very confusing situation where their apparent options are to either either make changes to their existing settings unwillingly or otherwise not knowing how to abort the process and leaving all of the settings being imported exactly as they are defined in the Jetbrains Account.

### Expected behaviour

When initializing upon first sync with a Jetbrains Account that has existing Material Plugin settings defined, the `Material Wizard` should either not appear and apply its settings (immediately or after prompting the user to restart to apply settings), or the `Material Wizard` should offer the user the option of skipping the wizard step and applying the stored settings directly.

### Actual behaviour

The Material Wizard appears with the first time configuration as if no settings are defined, and it is unclear how to correctly proceed to 1. not change your existing settings 2. apply your existing settings

### Steps to reproduce

1. From machine A sync settings to Jetbrains Account, with plugin syncing enabled
2. From machine B enable Jetbrains Account syncing (that has not had Material Theme plugin installed previously)

### Environment

IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Material Theme Plugin version: Version: 2.8.2 (side note: release notes stop at 2.8.1 in the plugin repo documentation)

##### material_theme.xml (from the computer initiating the sync with the jetbrains account) :
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.8.2" />
    <option name="selectedTheme" value="DARKER" />
    <option name="highlightColor" value="80cbc4" />
    <option name="isContrastMode" value="true" />
    <option name="accentColor" value="FF9800" />
    <option name="upperCaseButtons" value="false" />
    <option name="userId" value="-4c7c2494:16535248eff:-8000" />
    <option name="allowDataCollection" value="true" />
    <option name="treeFontSizeEnabled" value="true" />
    <option name="isHighContrast" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
This is because the wizard is displaying according to the presence of a property “isWizardShown” in the settings. Since this property wasn’t defined in previous iterations, as such the wizard would appear unbeknownst of whether the plugin was already installed or not. However since this setting is serialized in the config file, theoretically it should be persisted in the account settings and therefore not show up on other machines (but I can’t say for sure, I disabled the sync settings as it is buggy as hell)

There is nothing that can be fixed here, unless you can prove that the wizard is showing despite the property being set in the config file.

**Comment by mallowigi** [comment]
Note that if that’s the case, then it could be a problem relevant to the settings itself. Since the wizard activates at start, there is the possibility that the sync had not occurred yet and therefore the material theme config wasn’t downloaded yet.

**Comment by nivekastoreth** [comment]
> Since this property wasn’t defined in previous iterations

Hmm, if this value was added in the 2.8.2 release, that could be the case.  I only started using this plugin on 2018-08-16 using the mainline release version of IntelliJ and the 2.8.0 version of the plugin (or so I believe; that's the version my laptop still has on it from the day I was playing with this)

> Since the wizard activates at start, there is the possibility that the sync had not occurred yet and therefore the material theme config wasn’t downloaded yet.

Just noting that the sync had to at least be partially done since the sync itself is what installed the plugin.

> (but I can’t say for sure, I disabled the sync settings as it is buggy as hell)

Yeah... I ended up doing the same, but I filed this ticket mostly because when the wizard opened up, I had no idea how to back out without making changes that would be pushed to my jetbrains account.

> unless you can prove that the wizard is showing despite the property being set in the config file

I'll try re-creating on my laptop in a bit and when the wizard opens I'll look at the `material_theme.xml` to determine if 1. the file exists at this time and 2. if it has the `isWizardShown` value set.  I've not done intellij plugin development myself, so if I need to do something to test this other than renaming/deleting the `.IntelliJIdea2018.2` folder from my home directory please let me know.

**Comment by mallowigi** [comment]
There is a possibility that the sync is resetting settinsgs at start so the wizard would show up anytime. If that's the case, then I'm sorry for those users but there is not an easy way to fix this.
