### ISSUE TITLE
Plugin doesn't reset VCS file name colors on uninstall

### ISSUE THREAD

**Issue by mosinnik** [ChrisRM/material-theme-jetbrains#912]
plugin version: 2.8.2
idea build: 182.4129.33

**Comment by mosinnik** [comment]
@mallowigi It nice that it described somewhere but it wasn't clear for me when I installed this plugin. So is there some real problem to revert default colors back on uninstallation?

**Comment by mosinnik** [comment]
@mallowigi already done, but for history you should reset every color (~20) ans it is annoying and made me to write this issue

**Comment by mallowigi** [comment]
Yep it is annoying, hence why I wrote a full section on the documentation about it: http://www.material-theme.com/docs/configuration/file-status-colors/#caveats

This feature is not enabled by default, and you can also blame Jetbrains for removing this nice feature for everyone, requiring such tricks to get it back.
