### ISSUE TITLE
Tab Bar and Tab Color Opacity

### ISSUE THREAD

**Issue by Luberen** [ChrisRM/material-theme-jetbrains#914]
![tabbar1](https://user-images.githubusercontent.com/26616056/44613792-56190680-a854-11e8-8a39-6a7239cbebdd.PNG)
![tabbar2](https://user-images.githubusercontent.com/26616056/44613794-5913f700-a854-11e8-982f-81ebb1d8691d.PNG)
Currently only blue underbar shows what tab I have selected. I hope there is more clearer distinction between selected tab and unselected tab, like VSCode.

![gauge](https://user-images.githubusercontent.com/26616056/44613817-b445e980-a854-11e8-9491-e2ff3c0a4bf1.PNG)
In 'Tab Color Opacity' option, I would like to see exact value of opacity.

**Comment by mallowigi** [comment]
There is, but for that you need to activate the contrast mode, as the regular mode prefers to show the tab strip as one unified color, with the indicator the only way to differentiate between tabs, as per the material design tabs design.

The opacity is there to control opacity of the colors when you have the file colors enabled, so you can decide whether to prioritize file colors  over the material theme’s colors. You can look at the documentation for a better explanation and examples.
