### ISSUE TITLE
Wrong icon association/regex

### ISSUE THREAD

**Issue by diwms** [ChrisRM/material-theme-jetbrains#918]
### Summary
Hi there,

I have a wrong association in project tree view between icon and file type.
Pls, help me understand what is wrong, or probably where I can configure my own rules for this types.
...

### Expected behavior
Should be recognized as a class and have the proper icon like other classes.

![image](https://user-images.githubusercontent.com/968394/44721989-4d366800-aad4-11e8-95e7-04069d12ad6d.png)
...

### Actual behavior
All files which contain "test|Test" word recognized by **phpStorm** as test (even if it is class/interface)

![image](https://user-images.githubusercontent.com/968394/44721908-08123600-aad4-11e8-84a9-e02209b7bdb9.png)
...

### Steps to reproduce

1. Just create TestSome.php file

### Environment
PhpStorm 2018.2.2
Build #PS-182.4129.45, built on August 22, 2018

JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-33-generic
Material theme version - the latest - 2.8.1

**Comment by diwms** [comment]
I see that this regex is commented in config.
Should it be uncommented as well?

https://github.com/ChrisRM/material-theme-jetbrains/blob/master/src/main/resources/icon_associations.xml#L215

**Comment by mallowigi** [comment]
This is a bug with PHPStorm. I disabled the plugin and I got the same behavior. Apparently they are using regexpes to determine whether to show the TestUnit icon.

I uncommented the entry in order to display the PSI Icons (C, I, etc...)
