### ISSUE TITLE
Monokai Pro colors are different from the official version

### ISSUE THREAD

**Issue by ytang** [ChrisRM/material-theme-jetbrains#919]
### Summary

Monokai Pro colors are different from the official version. For example, the yellow color for strings is `#ffd866` in the official [Monokai Pro](https://www.monokai.pro/), but it is `#fbd85c` in [this plugin](https://github.com/ChrisRM/material-theme-jetbrains/blob/master/src/main/resources/colors/Monokai%20Pro.xml#L783). Other colors are off, too.

### Expected behavior

The colors should match the official [Monokai Pro](https://www.monokai.pro/).

### Actual behavior

The colors are different from the official [Monokai Pro](https://www.monokai.pro/).

### Environment

IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1293-b1 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.17.18-200.fc28.x86_64
Plugin version: 2.8.2
Plugin configuration:
```xml
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.8.2" />
    <option name="selectedTheme" value="MONOKAI" />
    <option name="accentColor" value="ffd866" />
    <option name="userId" value="..." />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

**Comment by ytang** [comment]
[Install it in Visual Studio Code](https://www.monokai.pro/vscode/) and examine `~/.vscode/extensions/monokai.theme-monokai-pro-vscode-1.1.8/themes/Monokai Pro.json`.

**Comment by ytang** [comment]
Alternatively, just download it from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/monokai/vsextensions/theme-monokai-pro-vscode/1.1.8/vspackage and unzip it.

**Comment by lucas993** [comment]
Plus, it looks different than Sublime...

**Comment by mallowigi** [comment]
Fixed
