### ISSUE TITLE
File Rename window color clash

### ISSUE THREAD

**Issue by mahngiel** [ChrisRM/material-theme-jetbrains#92]
When you refactor a class name and have it rename the file, the yellow used for Class names clashes with the background color of highlighted lines
![screenshot_46](https://cloud.githubusercontent.com/assets/1322045/10619218/a0bb4ed4-7731-11e5-95e6-4691f78006bb.png)

**Comment by mallowigi** [comment]
Please download the latest version (it's not available in the plugin repository yet, you will have to download and install it manually) and tell me if it is fixed.
