### ISSUE TITLE
Using theme messy code

### ISSUE THREAD

**Issue by QQ1355470410** [ChrisRM/material-theme-jetbrains#921]
### Summary

Using theme messy code
![image](https://user-images.githubusercontent.com/19506950/44827078-0b2c3400-ac44-11e8-8ec8-b45ed0123a79.png)

### Environment

Info:

* OS: ```Windows 10```
* IDE: ```PhpStorm 2018.2.2 Build #PS-182.4129.45, built on August 22, 2018```
* JRE: ```1.8.0_152-release-1248-b8 amd64```
* Plugin version:  ```2.8.2 ```

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/895
