### ISSUE TITLE
Wrong project icon is visible 

### ISSUE THREAD

**Issue by DiabolusExMachina** [ChrisRM/material-theme-jetbrains#922]
### Summary

I have disabled the Material Icons. Most are ok but the main project folder displays sometimes the material-theme icon.

### Expected behavior
Idea default project folder icon is used if material icons are disabled

### Actual behavior
Material project folder is sometimes used
![grafik](https://user-images.githubusercontent.com/4548046/44853815-383e0e00-ac67-11e8-848b-e910b65a569b.png)

### Steps to reproduce (if needed)

Install Theme, disable icons, work with idea. 

### Environment

}IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
Subscription is active until March 11, 2019
JRE: 1.8.0_152-release-1226-b1 amd64
JVM: OpenJDK 64-Bit Server VM by New Oracle
Windows 7 6.1

**Comment by mallowigi** [comment]
You need to disable the project view components as well.
