### ISSUE TITLE
"Don't Share" still enables data collection.

### ISSUE THREAD

**Issue by chad-horton** [ChrisRM/material-theme-jetbrains#923]
### Summary

The Data Collection Consent popup always sets `allowDataCollection` to `true` in `material_theme.xml`, regardless of whether "Share Anonymous Statistics" or "Don't Share" is selected.

### Expected behavior

When selecting "Don't Share", `allowDataCollection` should be set to `false`.

### Actual behavior

When selecting "Don't Share", `allowDataCollection` is set to `true`.

### Steps to reproduce (if needed)

1. Install Material UI in a installation of your IDE

OR

1. Delete the `mt.showStatisticsAgreement` property in `config/options/options.xml` of your IDE config folder.
2. Start your IDE.
3. Select "Don't Share"
4. Verify the result in `config/options/material_theme.xml`

### Environment

```
IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018
Licensed to [REMOVED]
You have a perpetual fallback license for this version
Subscription is active until [REMOVED]
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
Also tested on PyCharm 2018.2,2
Material UI Theme v2.8.2
material_theme.xml: 
```<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.8.2" />
    <option name="userId" value="[REMOVED]" />
    <option name="allowDataCollection" value="true" />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
Hum that's true, the "don't share" is actually setting nothing, thus for new entries it wouldn't change anything, but if you delete the property from the options to see the popup again, clicking "don't share" will actually not revert the property.

I'll fix it on next release.
