### ISSUE TITLE
Material Theme doesn't override Darcula theme

### ISSUE THREAD

**Issue by vicmns** [ChrisRM/material-theme-jetbrains#924]
### Summary

So I installed the material theme plugin, and it changes the general IDE theme to oceanic. But the background, text font and size doesn't change in the actual editor...

### Expected behavior

The editor view should be affected also by the plugin

### Actual behavior

The editor still shows the Darcula theme schema (see attached image).

![image](https://user-images.githubusercontent.com/1101060/45108451-3ad6b280-b102-11e8-910c-73028d76b6d8.png)
![screenshot from 2018-09-05 11-52-29](https://user-images.githubusercontent.com/1101060/45108497-5cd03500-b102-11e8-9fa1-b7f5dbdf0b79.png)

### Environment

Android Studio 3.2 RC 2
Build #AI-181.5540.7.32.4974118, built on August 23, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-33-generic

**Comment by mallowigi** [comment]
Read the doc

**Comment by vicmns** [comment]
I'm a moron, was trying to change the color schema looking at the Appearance UI Options section, not the color scheme section...

Sorry about this...
