### ISSUE TITLE
Can I change the selected background color of the project view?

### ISSUE THREAD

**Issue by Jonzzs** [ChrisRM/material-theme-jetbrains#935]
How can I change the selected background color of the project view?
And the selected background color of the project view when focus is lost.

**the normal:**

![](https://ws2.sinaimg.cn/large/006tNbRwgy1fv8yez32uij30fu0jggmx.jpg)

**focus is lost:**

![](https://ws3.sinaimg.cn/large/006tNbRwgy1fv8yf48exkj30fg0k8jsp.jpg)

**Comment by Jonzzs** [comment]
Ask another question, can I change the folder icon color？If you can, can you tell me how to do it?

**Comment by mallowigi** [comment]
Not at the moment. Maybe I’ll add it in the future but it’s not planned for now.
