### ISSUE TITLE
Provide minimum contrast

### ISSUE THREAD

**Issue by rhoerbe** [ChrisRM/material-theme-jetbrains#937]
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.

---

When submitting a bug report, first, read the README and check if this is a known issue.

Then, check on the Github issues if a similar issue has been posted.

If nothing of the sort, please follow the following template:
✂ ---------------- ✂ ----------------- ✂ ---------------- ✂ ---------------- 

### Summary
Using certain IDE dialogues, such as refactor/rename, or add comment for git commit: the text box uses a black font on dark grey background. The text is hard to read.

### Expected behavior

All IDE text should have a minimum contrast. The combination of background/foreground color should have a minimum effective contrast ratio. The W3C WVAG recommends a minimum ratio of 4.5:1 (https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=143#qr-visual-audio-contrast-contrast). This might be too limiting for the expressivity of the color schema, but such low levels as certain text boxes are too extreme on the other side.

### Actual behavior

black text on dark grey background

### Steps to reproduce (if needed)

See screenshot

### Environment

PyCharm 2018.1.4 (Professional Edition)
Build #PY-181.5087.37, built on May 24, 2018
Licensed to Rainer Hörbe
Subscription is active until May 13, 2019
For educational use only.
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

I am using the default Material Theme configuration file.

Same problem as with jet brains Dracula theme: https://youtrack.jetbrains.com/issue/PY-31791

![bildschirmfoto 2018-09-14 um 10 40 13](https://user-images.githubusercontent.com/4348479/45540756-89283780-b80d-11e8-849c-f45f1b30d9bb.png)

**Comment by mallowigi** [comment]
It’s because you are using a light theme with a dark look and feel. This issue is also happening without the plugin enabled. 

There is no way to fix this issue, the text color comes from the color scheme while the ide color comes from the theme, and I can’t change he theme color according to the color scheme loaded.
