### ISSUE TITLE
NullPointer on IntelliJ Startup

### ISSUE THREAD

**Issue by thomhurst** [ChrisRM/material-theme-jetbrains#938]
![image](https://user-images.githubusercontent.com/30480171/45692259-3e325b00-bb52-11e8-80f8-75e0a6b10223.png)

I cannot enable Material Theme UI as it errors on start up.
Tried plugin 2.8.3 and 2.9pre and IntelliJ 2018.2 and 2018.3

IntelliJ IDEA 2018.2.2 (Community Edition)
Build #IC-182.4129.33, built on August 21, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0 (v1607)

**Comment by mallowigi** [comment]
Try version 2.6 or manually disable the wizard by setting the property “isWizardShown” in the config file
