### ISSUE TITLE
on Mac, in WebStorm, the plugin causes Webstorm to lock up intermittently

### ISSUE THREAD

**Issue by royrico** [ChrisRM/material-theme-jetbrains#94]
As the title says on Mac, in WebStorm, the plugin causes WebStorm to lock up intermittently.  Sometimes, it will show almost all windows, but the project window just shows "initializing" and never comes back.  Other times, it'll show my project windows, but they will be completely blank.   

Usually, this happens when I resume from sleeping on my mac.    Please let me know what you need me to include to help you debug this. Thanks!

**Comment by BHSPitMonkey** [comment]
My Linux install of 9.0.2 prompted me to update this plugin today. I accepted, and after restarting the IDE it now freezes with the Project and bottom panes just showing "Initializing...". I renamed the .ZIP file I had originally loaded the plugin from and now it starts without incident. I can't be sure the two events are related...

**Comment by martin-wiseweb** [comment]
Same here. Installed the theme and now I can' start PHPStorm

**Comment by ChrisRM** [comment]
Can you guys try installing the newest build and let me know how if this still is an issue?

**Comment by imdpk** [comment]
Any update on this? I am running into the same issue.

**Comment by imdpk** [comment]
I am using WebStorm last Mac OSX

**Comment by ChrisRM** [comment]
@imdpk Do you have the newest build from the official repo installed? https://plugins.jetbrains.com/plugin/8006

**Comment by imdpk** [comment]
@ChrisRM just updated and seems to be working perfect!

**Comment by imdpk** [comment]
@ChrisRM Thanks alot! Any recommended color schemes?

**Comment by ChrisRM** [comment]
Personally I'm using the Default UI theme, but with a custom Facebook-ish color-scheme. 

Let me know if you're interested, and I'll upload it.

![image](https://cloud.githubusercontent.com/assets/309292/15145720/915adb28-16b7-11e6-955b-db8621cd04f5.png)

**Comment by imdpk** [comment]
Love it easy on the eyes for sure can you upload or email it to me?

**Comment by imdpk** [comment]
@ChrisRM

**Comment by ChrisRM** [comment]
https://www.dropbox.com/s/2p841lwomjchfqy/Pacely%20Theme.icls?dl=1

**Comment by twaileit** [comment]
Those locks also seem to happen kinda random in PHPStorm on Windows.
At least with Version 2016.1.0

I have just updated to 2016.1.1 and will report, how it is doing here.

**Comment by ChrisRM** [comment]
Make sure you update the plugin as well

**Comment by twaileit** [comment]
I just started it the 2nd time, it hanged up again.
I am using the latest version of the Plugin (v0.1.9), active theme is Default Material theme.

Unfortunately PHPStorm is not throwing any errors or something (it is not even saying that there is no response, it just stops doing anything).
