### ISSUE TITLE
Wizard keeps starting each time I start IntelliJ

### ISSUE THREAD

**Issue by c0d3x** [ChrisRM/material-theme-jetbrains#940]
Material Theme UI Updated v2.9.0-pre1.
Keeps starting the wizard each time I start IntelliJ and I cannot just use my last theme until I set it again. I also get the same Material UI Updated balloon saying the same message each time.

**Comment by oupvo01** [comment]
I have the same problem. It's getting pretty annoying...

Material plugin version: v2.9.0-pre1
IntelliJ version: 2018.2.1

**Comment by mallowigi** [comment]
Duplicate of #936
