### ISSUE TITLE
[question] Is this background can be changed ?

### ISSUE THREAD

**Issue by winter-ice** [ChrisRM/material-theme-jetbrains#941]
### Summary
Is this background can be changed ?
![image](https://user-images.githubusercontent.com/24680921/45833150-8ad68b80-bd36-11e8-80a9-0d3926a40428.png)

**Comment by mallowigi** [comment]
You need to click right on the background and select “change background image”

**Comment by ahokinson** [comment]
Why is this the default behavior? Given that not everybody uses the Oceanic theme, I think this is a really bad decision.

How is this
<img width="1552" alt="screen shot 2018-10-14 at 20 46 43" src="https://user-images.githubusercontent.com/1762048/46924411-5d59c680-cff2-11e8-95c5-3d52942c9e05.png">
somehow preferable to this?
<img width="1552" alt="screen shot 2018-10-14 at 20 47 05" src="https://user-images.githubusercontent.com/1762048/46924415-62b71100-cff2-11e8-84da-7e3a23b5eef3.png">

I am also unable to remove it. I was able to capture the second screenshot very quickly before it was replaced by the default background image.

I cannot see how to adjust these settings to remove it.
<img width="776" alt="screen shot 2018-10-14 at 20 49 26" src="https://user-images.githubusercontent.com/1762048/46924448-be819a00-cff2-11e8-9e70-af1fff0a26f1.png">

**Comment by mallowigi** [comment]
In the latest version I added an action to just remove the background. Check it in the menu.

**Comment by mallowigi** [comment]
And it’s not the default decision, I don’t know on what grounds you are saying that.

**Comment by nathan815** [comment]
@mallowigi Where is the action to remove this image located in PhpStorm?

**Comment by ahokinson** [comment]
@nathan815 
![screen shot 2018-12-11 at 11 15 10](https://user-images.githubusercontent.com/1762048/49796986-0fcdb180-fd36-11e8-8cc5-b8d36d146e28.png)
