### ISSUE TITLE
PhpStorm will not load project with Material Theme UI 2.9.0-pre1

### ISSUE THREAD

**Issue by sblomberg** [ChrisRM/material-theme-jetbrains#942]
### Summary

Material Theme UI 2.9.0-pre1 results in [various exceptions](https://gist.github.com/sblomberg/9d148ede2c38623010beddb433705dd7) in PhpStorm that prevents any editor windows from opening. Possibly a duplicate of #938 but I am able to enable Material Theme UI - it just prevents me from accessing PhpStorm nearly completely. I can't even load the Preferences window to disable the plugin. In order to disable the plugin I have to remove it from its directory at `~/Library/Application Support/PhpStorm2018.2/Material Theme/`

### Expected behavior

PhpStorm loads my project (or any project) with Material Theme UI installed.

### Actual behavior

Unable to load the project view for any project, existing or new, with Material Theme UI 2.9.0 installed and activated.

### Steps to reproduce

1. Install and activate Material Theme UI 2.9.0
2. Restart PhpStorm
3. Select a project from the recent projects sidebar, or choose Create New Project, or Open any folder
![image](https://user-images.githubusercontent.com/2219531/45907419-67a2ef00-bdbd-11e8-874e-508ae0e13a98.png)
4. PhpStorm fails to load project. Navigating to PhpStorm -> Preferences... in the task bar also fails to load any content.
![image](https://user-images.githubusercontent.com/2219531/45907519-ca948600-bdbd-11e8-8fed-6aad0b41e004.png)
5. Opening the `idea.log` file at `~/Library/Logs/PhpStorm2018.2/idea.log` produces this output: https://gist.github.com/sblomberg/9d148ede2c38623010beddb433705dd7

### Environment

PhpStorm 2018.2.3
Build #PS-182.4323.68, built on September 13, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Material Theme UI 2.9.0-pre1

Config file from `~/Library/Preferences/PhpStorm2018.2/options/material_theme.xml`:
```<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.9.0-pre1" />
    <option name="isContrastMode" value="true" />
    <option name="accentColor" value="79aecb" />
    <option name="userId" value="1f575425:1655dd5bccb:-8000" />
    <option name="allowDataCollection" value="true" />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

Config file from `~/Library/Preferences/PhpStorm2018.2/options/material_custom_theme.xml`:
```<application>
  <component name="MaterialCustomThemeConfig">
    <option name="treeSelectionColor" value="546e7a" />
    <option name="highlightColor" value="425b67" />
    <option name="secondBorderColor" value="2a373e" />
    <option name="contrastColor" value="1e272c" />
    <option name="secondaryBackgroundColor" value="32424a" />
    <option name="buttonColor" value="2e3c43" />
    <option name="selectionForegroundColor" value="ffffff" />
    <option name="selectionBackgroundColor" value="546e7a" />
    <option name="textColor" value="607d8b" />
    <option name="foregroundColor" value="b0bec5" />
  </component>
</application>
```

**Comment by mfullbrook** [comment]
I have the same symptoms. PHPStorm fails to get pass the splash/loading screen even though the progress bar is at 100%.  

@sblomberg thanks for the tip for removing the plugin.

@mallowigi removing the plugin reminds me how much i appreciate the plugin, keep up the good work.

**Comment by rdarcy1** [comment]
I'm also having this issue, any ideas on how to downgrade to 2.8.3? The changelog says it's possible to revert but I can't find any documentation on how to do it.

**Comment by thunder87** [comment]
Having the same problem, downgrading to 2.8.3 seems to have fixed the problem.

**Comment by sblomberg** [comment]
@mallowigi What's the resolution on this issue? Is there a new release available that fixes this problem?

**Comment by mallowigi** [comment]
I think it’s related to the bug that has been plaguing the version 2.9.0.pre. A new version has been released and is fixing this issue as well.
