### ISSUE TITLE
Theme Font - Wierd Characters

### ISSUE THREAD

**Issue by sheinfeld** [ChrisRM/material-theme-jetbrains#950]
Hey there,

After I updated the Theme to 2.9 pre i got this wierd characters all over the UI,

I tried to replace the font but it seams not to be working with  this theme or other that rely on this as base.

![screenshot_1](https://user-images.githubusercontent.com/34421632/46247413-fb4e6e00-c402-11e8-9944-bd507c01f182.png)

**Comment by Phikko** [comment]
Hey, I also have this problem. I tried other versions but problem is still there. I went down to 2.7.1 version by version and nothing worked.
![image](https://user-images.githubusercontent.com/30830448/46250719-d547be80-c440-11e8-85d2-75d5cceda3ce.png)

**Comment by nachodd** [comment]
I have the exact same problem here!! Make's me crazy, only way to fix this is to disable/uninstall the plugin. 
Have you guys manage to solve the problem??

**Comment by mallowigi** [comment]
http://www.material-theme.com/docs/faq-troubleshooting/#feature-settings

**Comment by nachodd** [comment]
I can confirm that this worked for me: 

- Setting the option: "override defualts font by.." to an specific font, in Settings > Apparearance & Behavior > Apparearance
![image](https://user-images.githubusercontent.com/4997040/46287724-d91b3400-c559-11e8-8c13-158a91263716.png)

- Reinstalling Roboto Font 
- Restarting my computer
- Installing Material Theme UI
