### ISSUE TITLE
Folder icon doesn't work with non-empty directory

### ISSUE THREAD

**Issue by MiracleWisp** [ChrisRM/material-theme-jetbrains#951]
1.When i create a controllers/routes folder it has special icon.
![image](https://user-images.githubusercontent.com/24497522/46249494-ad515e80-c432-11e8-8075-d07c4e6d476d.png)

2.But when i add any js file it become default folder
![image](https://user-images.githubusercontent.com/24497522/46249499-d4a82b80-c432-11e8-8c91-ee80ccbc18f7.png)

WebStorm 2018.2.3
Build #WS-182.4323.44, built on September 3, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

Plugin version 2.9.0-pre1
Material Theme Plugin Darker

**Comment by TomCorvus** [comment]
Hi everyone,

I have the same problem with the JS folder.
When the folder is empty or contains minified JS files, it works.

![Image](https://image.ibb.co/f2Vjwz/screen0001.jpg)

But when there is a JS file in it, the icon disappear
![Image](https://image.ibb.co/dGiJpK/screen00002.jpg)

PhpStorm 2018.2.4
Build #PS-182.4505.42, built on September 27, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Version 2.9.0 of Material Theme UI

Thanks for your work !

**Comment by nazrhyn** [comment]
Just to chime in on this one, the breadcrumb _does_ display the custom folder icon, while the directory tree does not:

![image](https://user-images.githubusercontent.com/1672405/46544619-13eed600-c892-11e8-9a1c-62dba4c13d8c.png)

![image](https://user-images.githubusercontent.com/1672405/46544631-1cdfa780-c892-11e8-92a5-3548a2c1e37c.png)

**Comment by mallowigi** [comment]
The bug here is that it should display OPEN directories when there is a file opened in the editor when the "Project View Decorators" option is on, independently of the folder name. Since there are no "open states" for custom folders, the default "open folder" should be shown, however the bug here is that it shows the close folder.

Next version will fix this.
