### ISSUE TITLE
Display local VCS change markers in the left gutter instead of the right

### ISSUE THREAD

**Issue by gavingolden** [ChrisRM/material-theme-jetbrains#953]
### Summary
I'd prefer that local VCS changes show up in the left gutter instead of the right. Is it possible to add this as a configuration option?

### Environment
IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
Plugin Version: 2.8.3

**Comment by mallowigi** [comment]
what do you mean exactly?

**Comment by gavingolden** [comment]
The VCS gutter indicators for lines modified/added/deleted aren't appearing to the left of the code editor but instead on the right. I can't figure out how to get them back on the left. Is this not controlled by the material plugin?

**Comment by mallowigi** [comment]
No. You probably changed a setting in the IDE, but I don't know which one
