### ISSUE TITLE
Material Theme in IntelliJ Corrupting Menu Text (v. 10/1/18)

### ISSUE THREAD

**Issue by imlouisrussell** [ChrisRM/material-theme-jetbrains#954]
### Summary
Material Theme in IntelliJ Corrupting Menu Text
...

### Expected behavior
Menu text is readable
...

### Actual behavior
Menu text is broken (see attached screenshot)
...

### Steps to reproduce (if needed)

1. Open IntelliJ

You can also add Screenshots for a better understanding.

### Environment

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
IntelliJ IDEA 2018.2.4 (Community Edition)
Build #IC-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theem UI v2.9.0

If possible please also give out your Material Theme/Material Custom Theme configuration file.

Note that not providing any of the required info will result of your issue being closed.

![intellij](https://user-images.githubusercontent.com/1108329/46312765-ebf23080-c57a-11e8-97bf-126d6a6b747c.png)

**Comment by imlouisrussell** [comment]
Accidental close.

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/895#issuecomment-413259427
