### ISSUE TITLE
Getting mix of English and some other language in dialogs. 

### ISSUE THREAD

**Issue by MikeSuiter** [ChrisRM/material-theme-jetbrains#955]
### Summary
Some labels and buttons are in foreign language. I didn't change any settings so don't know if this is a bug or if I accidentally did an IntelliJ keyboard shortcut that caused this. 
...

### Expected behavior
All be in English
...

### Actual behavior
Mix of English and some other language (or just random characters)
...

### Steps to reproduce (if needed)

This is strange since I've been using Material Theme for a while now and suddenly got mixed languages with 2.8.3. I installed 2.9.0 today and same problem. I even uninstalled and reinstalled and the problem comes back. The problem doesn't happen with Darcula theme. 

You can also add Screenshots for a better understanding.

![image](https://user-images.githubusercontent.com/5289509/46312407-9d4c9280-c58a-11e8-935b-592e2b6779e3.png)

![image](https://user-images.githubusercontent.com/5289509/46312641-4b583c80-c58b-11e8-913d-9e0c24483814.png)

### Environment

IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
Licensed to XXX
Subscription is active until February 1, 2019
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

material_theme.xml
```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.9.0" />
    <option name="userId" value="-30bf6e76:166314186f9:-8000" />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/895#issuecomment-413259427
