### ISSUE TITLE
Highlight usages of current element at caret not working

### ISSUE THREAD

**Issue by rmirabelle** [ChrisRM/material-theme-jetbrains#960]
### Summary

Automatic highlighting of matching variable usages does not work in PHP Storm with material theme oceanic enabled

### Expected behavior

With Settings > General > Highlight usages of element at caret checked,  clicking to select a variable should automatically highlight other usages of that variable within scope.

### Actual behavior

Clicking a variable does nothing.  To get highlighting, you're forced to type CTRL + SHIFT + F7

### Steps to reproduce (if needed)

Click on any PHP variable

You can also add Screenshots for a better understanding.

![highlighted](https://user-images.githubusercontent.com/87966/46541874-1b5eb100-c88b-11e8-975c-0cdb772dc84b.png)
![not_highlighted](https://user-images.githubusercontent.com/87966/46541878-1dc10b00-c88b-11e8-9afd-b8b9992da5eb.png)

### Environment

PhpStorm 2018.2.4
Build #PS-182.4505.42, built on September 27, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

IDE Info:
Custom plugins: [Material Theme UI (2.9.0)]
Disabled plugins:[]
Build version: PhpStorm 2018.2.4 Build #PS-182.4505.42 September 27, 2018
Java version: 1.8.0_152-release-1248-b8amd64
Operating System: Windows 10 (10.0, amd64)
JVM version: OpenJDK 64-Bit Server VM JetBrains s.r.o

**Comment by mallowigi** [comment]
Are you sure you're using a pristine color scheme?
<img width="230" alt="2018-10-05_21-39-20" src="https://user-images.githubusercontent.com/5015756/46553834-3c54ef80-c8e7-11e8-8f9b-c951c36d2141.png">
