### ISSUE TITLE
Plugin hint not readable on Monokai Pro theme

### ISSUE THREAD

**Issue by Benxter83** [ChrisRM/material-theme-jetbrains#965]
### Summary

When using Monokai Pro Theme in the current version 2.9.2 and IntelliJ pops up a (plugin) hint for that file, it is not readable because it is bright font color on bright yellow background. See attachment. 

![material_ui](https://user-images.githubusercontent.com/27850740/46616376-b6b98580-cb1a-11e8-9640-8b517fd44fec.png)

### Expected behavior

Hint is readable

### Actual behavior

Hint is not readable

### Steps to reproduce (if needed)

1. Switch to Monokai Pro Theme
2. Make sure you don't have a plugin for .log files
3. Open a log file

### Environment

IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
Licensed to ****
Subscription is active until *****
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

Plugin version 2.9.2

**Comment by Benxter83** [comment]
Why did you close it?

**Comment by mallowigi** [comment]
It should be fixed on version 2.9.3

**Comment by Benxter83** [comment]
Yes it is not fixed with 2.9.3. still there.

**Comment by Benxter83** [comment]
Also not fixed in 2.9.3.1

**Comment by mallowigi** [comment]
What do you mean not fixed? It should be brown

**Comment by mallowigi** [comment]
or it's something else... How do you reproduce it ?

**Comment by Benxter83** [comment]
I don't know why it is solved now, but I uninstalled the plugin, restarted and installed it agin. Now it's fine.
Thank you for the fix.
