### ISSUE TITLE
Off-color boxes in the status bar

### ISSUE THREAD

**Issue by nazrhyn** [ChrisRM/material-theme-jetbrains#966]
<sup>From [our conversation in Slack](https://material-theme-ui.slack.com/archives/CB9T8GZEF/p1539023812000100), earlier.<sup>
### Summary
![image](https://user-images.githubusercontent.com/1672405/46627270-e90db780-cb07-11e8-890b-c7d20dc02c5c.png)
![image](https://user-images.githubusercontent.com/1672405/46627274-eca13e80-cb07-11e8-8c89-fd0dffe836a8.png)

There are some small off-color boxes in the status bar. I wonder if these are from the region where I've disabled something? (e.g. I have the theme name disabled.)

### Expected behavior
No boxes. :smile_cat: 

### Actual behavior
Boxes. :crying_cat_face:

### Environment
WebStorm 2018.2.4
Build #WS-182.4505.50, built on October 3, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic (Ubuntu 18.04)
Material Theme Plugin 2.9.2

**Comment by mallowigi** [comment]
fixed on next version
