### ISSUE TITLE
Always reinitializes the settings on start

### ISSUE THREAD

**Issue by foxbunny** [ChrisRM/material-theme-jetbrains#967]
### Summary

Since the last update, whenever I start IntelliJ, Material design settings wizard pops up and resets my settings.

### Expected behavior

To not reset my settings.

### Actual behavior

It resets my settings every time IJ starts.

### Steps to reproduce (if needed)

n/a

### Environment

IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
Licensed to ********
Subscription is active until ********
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

> If possible please also give out your Material Theme/Material Custom Theme configuration file.

Not sure where to locate that. But I would provide it if you tell me where I can find it.

**Comment by mallowigi** [comment]
Download version 2.9.2

**Comment by foxbunny** [comment]
That was quick. :D Thanks it's fixed now.

**Comment by foxbunny** [comment]
Oh, darn it. It says it's updated to 2.9.0. Will try again.

**Comment by foxbunny** [comment]
Ok, definitely fixed in 2.9.2. Sorry about the noise.
