### ISSUE TITLE
[issue] PhpStorm include path entries go black after losing focus

### ISSUE THREAD

**Issue by ERROPiX** [ChrisRM/material-theme-jetbrains#970]
PhpStorm 2018.2.4
Material Theme 2.9.2
Setting Path `File | Settings | Languages & Frameworks | PHP`

![phpstorm-php-includes](https://user-images.githubusercontent.com/6576868/46737638-ee980880-cc93-11e8-8cf3-169cbf145f3d.PNG)

This issue occurs after clicking on any of the include path entries, then clicking somewhere else, or in other words when they lose focus. the text become black and they get some kind of border, see picture above

Thanks

**Comment by mallowigi** [comment]
will be fixed next release

**Comment by ERROPiX** [comment]
Thank you @mallowigi for the update
