### ISSUE TITLE
Problems with last Update October 04

### ISSUE THREAD

**Issue by MarcoGarcia10** [ChrisRM/material-theme-jetbrains#971]
### Summary

Problems with language PHPStorm 2018.2.4

### Actual behavior

All the IDE change language with the last update, IDK if just need to wait the next update.
I post the picture with the problem.

### Steps to reproduce

1. I Updated October 4th, 2018

********* Screenshot *************
![screenshot 15](https://user-images.githubusercontent.com/27243689/46749904-5b070d80-cc7c-11e8-8592-48dd0a9bebb3.jpg)

### Environment

PhpStorm 2018.2.4
Build #PS-182.4505.42, built on September 27, 2018
Licensed 
Subscription is active until June 22, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

*Material Theme UI 
Updated v2.9.1

Thank in advance,
Regards.

**Comment by mallowigi** [comment]
https://github.com/ChrisRM/material-theme-jetbrains/issues/968
