### ISSUE TITLE
Broken Font/layout 

### ISSUE THREAD

**Issue by lmotor** [ChrisRM/material-theme-jetbrains#972]
Hi, 
I installed last version of plugin on fresh phpstorm and this is what happen. 
Please see screenshot.
![image](https://user-images.githubusercontent.com/10991619/46755917-94646b00-ccc6-11e8-9ab3-147a4fc3c89d.png)

**Comment by mallowigi** [comment]
Please see closed issues this issue has been solved plenty of times
