### ISSUE TITLE
Material Icons are shown instead of stock icons

### ISSUE THREAD

**Issue by marhkb** [ChrisRM/material-theme-jetbrains#975]
### Summary
After updating to 2.9.3.1 I am not able to get stock icons any more
...

### Expected behavior
As all icons are disabled in the options I expect that the stock icons are shown
...

### Actual behavior
The material icons are shown instead
...

### Environment

IntelliJ IDEA 2018.2.4 (Community Edition)
Build #IC-182.4505.22, built on September 21, 2018
JRE: 1.8.0_152-release-1343-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.14.74-1-lts
![icons](https://user-images.githubusercontent.com/3630213/46886448-4765cd80-ce5b-11e8-9f53-7a3bf79f0db0.png)
![project](https://user-images.githubusercontent.com/3630213/46886594-a0cdfc80-ce5b-11e8-8271-6ebcdaddd719.png)
![settingd2](https://user-images.githubusercontent.com/3630213/46886449-4765cd80-ce5b-11e8-9e1c-9c5e98341afe.png)
![settings1](https://user-images.githubusercontent.com/3630213/46886450-47fe6400-ce5b-11e8-808b-a14039a3fa7f.png)

**Comment by mallowigi** [comment]
perhaps there were an issue with icon associations (though I couldn't reproduce).

I fixed that, take a look on the last version (2.9.3.2)

**Comment by mallowigi** [comment]
I can see in your screenshot that the option “file icons” is off. Is it on purpose?

**Comment by mallowigi** [comment]
Ah never mind. I will investigate.

**Comment by mallowigi** [comment]
Oh I get it. I completely missed that. Good find I’ll send a fix asap.
