### ISSUE TITLE
Allow code completion popup to be transparent

### ISSUE THREAD

**Issue by urosjarc** [ChrisRM/material-theme-jetbrains#988]
The code completion popup blocks your view of code that's under the popup. In Visual Studio this problem is solved by making the code completion popup transparent while you hold down the control key on your keyboard, making the text underneath readable again. Is it possible for IntelliJ to do something similar?

I would be really interested if you can check if this is possible within this plugin theme?

> [Issue ticket IDEA-126993](https://youtrack.jetbrains.com/v2/issue/IDEA-126993)
> [stackoverflow/annoying-hint-box-in-jetbrain-ides](https://stackoverflow.com/questions/33888793/annoying-hint-box-in-jetbrain-ides)

**Comment by mallowigi** [comment]
Nice idea. I’m not sure I can do it but I’ll check it out.

**Comment by mallowigi** [comment]
Alright after many tries, I give up. It's not currently possible within the capabilities of the plugin SDK. Sorry.

**Comment by urosjarc** [comment]
Thank you anyway 🙂
