### ISSUE TITLE
Android Studio version not visible on title screen when using Material Darker Theme

### ISSUE THREAD

**Issue by tamimmirza** [ChrisRM/material-theme-jetbrains#991]
### Summary
When loading android studio with the material theme UI plugin enabled. I chose the Material Darker look and noticed that the version number of Android Studio does not show 

### Expected behavior
The following screenshot is utilising the native Darcula theme on Android Studio

![an1](https://user-images.githubusercontent.com/35456031/46943916-2cc56b80-d08a-11e8-81b9-9aa07cb2b2c9.png)

### Actual behavior
And when the same is done using Material Darker Theme. We get this:

![an](https://user-images.githubusercontent.com/35456031/46943944-4666b300-d08a-11e8-8a95-7a65e606fd4f.png)

### Environment

Android Studio 3.2.1
Build #AI-181.5540.7.32.5056338, built on October 9, 2018
JRE: 1.8.0_152-release-1136-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Material Theme Plugin version: 2.4.1.5-2018.1

**Comment by mallowigi** [comment]
Sorry I'm not developing release for versions previous to 2018.2

Either use Android Canary or bear with it.
