### ISSUE TITLE
`TreeClosed.svg` cannot be found

### ISSUE THREAD

**Issue by cwrau** [ChrisRM/material-theme-jetbrains#994]
### Summary

On every Idea launch the theme throws an exception, because an icon cannot be found

### Expected behavior

Icon is found

### Actual behavior

Icon is not found

### Steps to reproduce (if needed)

1. Launch Idea

### Environment

IntelliJ IDEA 2018.2.4 (Ultimate Edition)
Build #IU-182.4505.22, built on September 18, 2018
Licensed to Chris Werner Rau
Subscription is active until March 22, 2019
For educational use only.
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-34-generic

* Plugin version
  * 2.9.3.3
* Plugin configuration (found in material_theme.xml)
  * ```
	<application>
	  <component name="MaterialThemeConfig">
	    <option name="version" value="2.9.3.3" />
	    <option name="userId" value="2b3dc8c1:16633e9b90e:-8000" />
	    <option name="isWizardShown" value="true" />
	  </component>
	</application>
	```

Exception:

```
java.lang.Throwable: Icon cannot be found in '/icons/nodes/TreeClosed.svg', aClass='class com.chrisrm.idea.icons.tinted.TintedIconsService'
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:148)
	at com.intellij.openapi.util.IconLoader.getIcon(IconLoader.java:109)
	at com.chrisrm.idea.icons.tinted.TintedIconsService.getThemedIcon(TintedIconsService.java:174)
```

**Comment by mallowigi** [comment]
Will fix soon
