### ISSUE TITLE
Material icon disappearance

### ISSUE THREAD

**Issue by TheMesoria** [ChrisRM/material-theme-jetbrains#997]
### Summary

As everyone knows, Material Theme gives you option to use icons in project tree, and automatically changes when text matches presets, like here:

![image](https://user-images.githubusercontent.com/9269398/47028331-7cc72f80-d169-11e8-8d30-fb88da8fc83a.png)

### Expected behavior

As example image above, name and image stays as is.

![image](https://user-images.githubusercontent.com/9269398/47028478-c879d900-d169-11e8-9a67-52d964945c26.png)
![image](https://user-images.githubusercontent.com/9269398/47028501-cf085080-d169-11e8-9f33-b2bdb40938cb.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/9269398/47028556-e3e4e400-d169-11e8-9467-6b7d5b648957.png)

With one small twist:

![image](https://user-images.githubusercontent.com/9269398/47028589-f52df080-d169-11e8-839b-88819d031166.png)

Top control bar DO recognize those names. Which is interesting in some way.

### Steps to reproduce (if needed)

1. Install MT on any Jetbrains product.

### Environment

```
CLion 2018.2.4
Build #CL-182.4505.18, built on September 17, 2018
Licensed to Wojciech <SURNAME>
Subscription is active until October 29, 2018
For educational use only.
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic
```

Fun fact, I have perpetual fallback license, although it does not updated it here... doubt that is connected, because I find same issue on all my Laptops, but mentioning, maybe it is...

```
<application>
  <component name="MaterialThemeConfig">
    <option name="version" value="2.9.3.2" />
    <option name="selectedTheme" value="DARKER" />
    <option name="accentColor" value="FF9800" />
    <option name="darkTitleBar" value="true" />
    <option name="userId" value="-7c0a9078:1666e26e545:-8000" />
    <option name="isHighContrast" value="true" />
    <option name="overrideAccentColor" value="true" />
    <option name="isWizardShown" value="true" />
  </component>
</application>
```

I think I am doing something wrong, or I am just plainly misunderstanding concepts, but hopefully I will understand them now :)

Have a great day!

**Comment by mallowigi** [comment]
This is a known behavior, it’s because of the “Project view decorators” which is changing the directories when a file is opened.

**Comment by TheMesoria** [comment]
Is there known fix/work around?
